### ISSUE TITLE
Buildah cannot be executed in the non-privileged container of k8s

### ISSUE THREAD

**Issue by q384566678** [containers/buildah#1011]
I created a non-privileged container in k8s, but could not execute buildah. Later, I found that it could be executed correctly before this [patch](https://github.com/projectatomic/buildah/pull/836/commits/f1f087c8e51b3854a1ef2cb9127fe7e7a3f885cb) ,but it could not be executed after this patch modified the `unshare.go` file.

If I add privileges to the `yaml` file, I can execute buildah correctly.

Error info:
```
root@zz-ubuntu-78f657b855-ljrx8:~# buildah images
Error during unshare(CLONE_NEWUSER): Invalid argument
ERRO[0000] error parsing PID "": strconv.Atoi: parsing "": invalid syntax 
ERRO[0000] (unable to determine exit status)  
```

yaml file for creating non-privileged containers in k8s:
```
$ cat ubuntu.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zz-ubuntu
  labels: 
    label: ubuntu-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ubuntu
  template:
    metadata:
      labels:
        app: my-ubuntu
    spec:
      containers:
      - name: test-ubuntu
        image: ubuntu:16.04
        command: ["sleep", "10000"]
```
Output of buildah version:
```
Version:         1.4-dev
Go Version:      go1.8.7
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      07aa077
Built:           Thu Sep 13 10:34:15 2018
OS/Arch:         linux/amd64
```

Output of uname -a:
```
Linux zz-ubuntu-78f657b855-ljrx8 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TomSweeneyRedHat** [comment]
@giuseppe PTAL

**Comment by q384566678** [comment]
@nalind PTAL

**Comment by giuseppe** [comment]
could you use the `chroot` isolation?  You can set it with the env variable `BUILDAH_ISOLATION=chroot`, or as a flag to `buildah run`

**Comment by q384566678** [comment]
> could you use the chroot isolation? You can set it with the env variable BUILDAH_ISOLATION=chroot, or as a flag to buildah run

No. The same error will still occur.
The following function is called in the main function:
```
maybeReexecUsingUserNamespace(c, false)
```

Finally, an error is reported in the `unshare.c` file.

```
	if ((flags & CLONE_NEWUSER) != 0) {
		if (unshare(CLONE_NEWUSER) == -1) {
			fprintf(stderr, "Error during unshare(CLONE_NEWUSER): %m\n");
			_exit(1);
		}
	}
```

**Comment by rhatdan** [comment]
@q384566678 Is this still an issue?  @giuseppe could you look at this.

**Comment by giuseppe** [comment]
this is happening because the user has no `CAP_SYS_ADMIN`.  Either `CAP_SYS_ADMIN` or the possibility to create a user namespace is required, otherwise there is no way to create a buildah container.

`unshare` is probably blocked by seccomp, could you tweak seccomp to allow it?

**Comment by MiyKh** [comment]
Same problem when running a non-privileged  Buildah container on Openshift

**Comment by TomasTomecek** [comment]
Related: https://github.com/containers/libpod/issues/1092 (unprivileged podman in an openshift pod)

**Comment by rhatdan** [comment]
We now have working versions of buildah with podman and fuse-overlay.

Need a container image with buildah/fuse-overlay installed.  Need to run buildah --isolation chroot, and the container has to have the /dev/fuse device.  Also needs a version of container-selinux > 2.84  But it now works.
