### ISSUE TITLE
Feature request: ONBUILD for oci images

### ISSUE THREAD

**Issue by kbaegis** [containers/buildah#1032]
**Description**
>  A mechanism to support something similar to ONBUILD instructions provided by docker. For the actual functionality, I'm looking for a standard way to imprint the "toolchain" for images built by my utility. I want this stored both as a label as well as an ENV and tracks the image layers all the way back to scratch. 

---
image1.Dockerfiile
```
FROM <scratch>
LABEL $NAMESPACE.genesis="scratch"
....
ONBUILD ARG GENESIS="<image1url> (<git commit>); scratch"
```

image2.Dockerfile
```
FROM <^^>
....
ONBUILD ARG GENESIS="<image2url> (<git commit>);${GENESIS}"
ONBUILD ENV GENESIS="$GENESIS"
ONBUILD LABEL $NAMESPACE.genesis="$GENESIS"
```

I'd like to be able to pull these labels with `buildah inspect <image uri>|jq '.OCIv1.config.Labels."$NAMESPACE.genesis"'` in order to see the full list of layers and versions. I'm completely open to better ways to do this.

**Comment by rhatdan** [comment]
OCI Images do not support ONBUILD, so would need to build Docker image.

Do you expect buildah to help generate some of these fields?

**Comment by kbaegis** [comment]
1) Validating that this functionality doesn't already exist elsewhere and I simply missed it
2) Verifying that this is a valid thing to do

I'd prefer to omit the --format=docker when I run these. Is there a workaround that I could use for oci images?

**Comment by kbaegis** [comment]
I've build in an incredibly ugly workaround by explicitly passing the first FROM statement in a grep of the build file to --build-arg. I'm still very curious how others are solving this problem.

**Comment by rhatdan** [comment]
@kbaegis Join me (dwalsh) on #buildah on IRC on Freenode

**Comment by rhatdan** [comment]
This would need to be added to the spec.  So open the issue there.
