### ISSUE TITLE
buildah push failed if we try to push an image twice

### ISSUE THREAD

**Issue by ypu** [containers/buildah#1045]
**Description**
buildah push will failed if we push the same image twice. This is not related with the push destination, just use docker-daemon as an example. And I use tree to check the image layer under /var/lib/containers/storage/overlay/ before and after the buildah push. Here is the diff results:
```
# diff -Nubr before after 
--- before	2018-09-28 22:50:51.281095617 +0800
+++ after	2018-09-28 22:50:59.966096102 +0800
@@ -419,5 +419,6 @@
 ├── link
 ├── merged
 └── work
+    └── work
 
-21 directories, 399 files
+22 directories, 399 files
```

**Steps to reproduce the issue:**
1. buildah pull busybox
2. buildah push busybox docker-daemon:buildahtest:latest
3. buildah push busybox docker-daemon:buildahtest:latest

**Describe the results you received:**
The second push failed with following error
```
# buildah push busybox docker-daemon:buildahtest:latest
Getting image source signatures
Copying blob sha256:f9d9e4e6e2f0689cd752390e14ade48b0ec6f2a488a05af5ab2f9ccaf54c299d
 1.00 KiB / 1.31 MiB [>-----------------------------------------------------] 0s
error pushing image "busybox" to "docker-daemon:buildahtest:latest": error copying layers and metadata: Error writing blob: open /var/lib/containers/storage/overlay/f9d9e4e6e2f0689cd752390e14ade48b0ec6f2a488a05af5ab2f9ccaf54c299d/merged/bin/[: no such file or directory
```

**Describe the results you expected:**
buildah push can finished normally

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
# buildah version
Version:         1.4-dev
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      2b307e7
Built:           Thu Sep 27 20:00:39 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**
This is a RHEL 7 host

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 was this something you were looking at already?

**Comment by umohnani8** [comment]
@TomSweeneyRedHat no I wasn't.

**Comment by TomSweeneyRedHat** [comment]
Thanks for the 411 @umohnani8 I'll take a look then.

**Comment by rhatdan** [comment]
I think this is something recently fixed by @nalind.  We might need to re-vendor in containers/storage and containers/image and finally put out buildah 1.4

**Comment by rhatdan** [comment]
@ypu Is this off the current upstream?  It looks like we have all of the patches in upstream storage and image.

**Comment by ypu** [comment]
Hi @rhatdan 
Get a fresh buildah source code. And try this again. The problem already fixed. So will closed this issue. 
Thanks a lot for your update,
