### ISSUE TITLE
buildah mishandles insecure registry config

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1047]
I have `172.30.255.124:5000` configured as an insecure registry in registries.conf.  That seems to work fine for pulling the blob as seen below, but then as soon as the dockerfile processing starts, a failure occurs because buildah tries to access the registry over https.

```
Pulling image 172.30.255.124:5000/openshift/ruby@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae ...
Getting image source signatures
Copying blob sha256:256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65
 71.23 MiB / 71.23 MiB  3s
Copying blob sha256:efb19fea0fdb7178d5deedd98a3cbf90284dbc01f468e1dc8117b2d1becd34e9
 8.92 MiB / 8.92 MiB  0s
Copying blob sha256:b4570fdc208ced0033bf04a67323eda6cd72d92bcfab46bac200860a587722cc
 4.63 KiB / 4.63 KiB  0s
Copying blob sha256:213e4e250552a0d0e7e7c69ef31e783085154c9cf91cea80ed705b3eb5a35cc0
 157.87 KiB / 157.87 KiB  0s
Copying blob sha256:cb2ae87f9dc0eeb210670522c740de539310cbe565c8775f9438fc5a6dee56d4
 80.23 MiB / 80.23 MiB  3s
Copying blob sha256:8965056fa1335fd78743b362217a12f1e3f85a8f862378adadfa46248ee4551b
 13.18 MiB / 13.18 MiB  0s
Copying blob sha256:0c54dc45450aba434ffdbff89994d7cb5cd7f4fb074d284fb11f8d2239599b33
 1.82 KiB / 1.82 KiB  0s
Copying blob sha256:3834b16e2f5c97ee46bcb71b5a219f1205b906b09cb70cc0c0d8fbea34569c34
 3.92 KiB / 3.92 KiB  0s
Copying blob sha256:ff4625cd4ac9741afe593d4d03a0c4a0820b64bc679d68ae27d9b94f52402e02
 157.52 KiB / 157.52 KiB  0s
Copying config sha256:c7101e5b8b2912bb90834b291d4cc8a114da575e1bf9b9e305070cf2b395dd3d
 16.42 KiB / 16.42 KiB  0s
Writing manifest to image destination
Storing signatures
STEP 1: FROM 172.30.255.124:5000/openshift/ruby@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae
error: build error: error creating build container: 1 error occurred:

* Error determining manifest MIME type for docker://172.30.255.124:5000/openshift/ruby@sha256:a18c8706118a5c4c9f1adf045024d2abf06ba632b5674b23421019ee4d3edcae: pinging docker registry returned: Get https://172.30.255.124:5000/v2/: http: server gave HTTP response to HTTPS client
@bparees
```

@nalind

**Comment by rhatdan** [comment]
@nalind @mtrmac PTAL

**Comment by mtrmac** [comment]
This is probably https://github.com/containers/image/pull/484 , or at least closely related.

**Comment by rhatdan** [comment]
@vrothberg Could you take a look at this, since it is in the area you have been playing with.

**Comment by vrothberg** [comment]
> @vrothberg Could you take a look at this, since it is in the area you have been playing with.

Sure, we're currently discussing a solution.

**Comment by mrunalp** [comment]
Any update on this?

**Comment by mrunalp** [comment]
Did https://github.com/containers/image/pull/534 take care of this? If yes, is it vendored into buildah?

**Comment by vrothberg** [comment]
@mrunalp it's vendored into buildah and works (just checked locally) but it's not yet in a release.

@TomSweeneyRedHat @rhatdan, maybe we can bump a new release next week once we decided how to proceed with https://github.com/containers/buildah/pull/1244?

**Comment by vrothberg** [comment]
I am closing the issue as it's fixed in master.

**Comment by rhatdan** [comment]
Yes once we get #1244 in, hopefully today or Monday, we cut a new release.

**Comment by lsm5** [comment]
ack

**Comment by lsm5** [comment]
> @lsm5 We will need a new buildah build as well to include this. We can wait till next week to land all the fixes.

@fkluknav ^
