### ISSUE TITLE
buildah pushes new copies of content it pulled down

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1048]
Since only a single new layer is produced by the build, the final push should only need to push a single new layer (after checking w/ the registry to confirm the base layers are already present).  Instead multiple layers appear to be getting copied/pushed.  This means builds are slower than they need to be and also we're duplicating content in the registry.

```
build.build.openshift.io/nodejs-ex-5 started
Cloning "https://github.com/openshift/nodejs-ex" ...
	Commit:	905416d88f74bfb734efac2a7e835948128a1df1 (Merge pull request #204 from jeffdyoung/ppc64le)
	Author:	Honza Horak <hhorak@redhat.com>
	Date:	Tue Sep 25 07:47:27 2018 +0200
Getting image source signatures
Copying blob sha256:256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65
 71.23 MiB / 71.23 MiB  3s
Copying blob sha256:efb19fea0fdb7178d5deedd98a3cbf90284dbc01f468e1dc8117b2d1becd34e9
 8.92 MiB / 8.92 MiB  0s
Copying blob sha256:b4570fdc208ced0033bf04a67323eda6cd72d92bcfab46bac200860a587722cc
 4.63 KiB / 4.63 KiB  0s
Copying blob sha256:213e4e250552a0d0e7e7c69ef31e783085154c9cf91cea80ed705b3eb5a35cc0
 157.87 KiB / 157.87 KiB  0s
Copying blob sha256:cb2ae87f9dc0eeb210670522c740de539310cbe565c8775f9438fc5a6dee56d4
 80.23 MiB / 80.23 MiB  3s
Copying blob sha256:dd35aa435a3cc5cdd2454dd4142e1dbbe1abf0ba3a41770b5585168292287b12
 363.66 MiB / 363.66 MiB  11s
Copying config sha256:2a11e2ded5cc5b6d65514efad90a42526088209d14ebb59916c3a79bee1f9b7b
 13.05 KiB / 13.05 KiB  0s
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image 172.30.255.124:5000/openshift/nodejs@sha256:a718a9daf8074aacd08e2de2679c067b39790f8e89e860f31d03e8fadd2d424a
Using buildah to create image temp.builder.openshift.io/test/nodejs-ex-5:57646f8d
STEP 1: FROM 172.30.255.124:5000/openshift/nodejs@sha256:a718a9daf8074aacd08e2de2679c067b39790f8e89e860f31d03e8fadd2d424a
STEP 2: LABEL "io.openshift.build.source-location"="https://github.com/openshift/nodejs-ex"       "io.openshift.build.image"="172.30.255.124:5000/openshift/nodejs@sha256:a718a9daf8074aacd08e2de2679c067b39790f8e89e860f31d03e8fadd2d424a"       "io.openshift.build.commit.author"="Honza Horak <hhorak@redhat.com>"       "io.openshift.build.commit.date"="Tue Sep 25 07:47:27 2018 +0200"       "io.openshift.build.commit.id"="905416d88f74bfb734efac2a7e835948128a1df1"       "io.openshift.build.commit.ref"="master"       "io.openshift.build.commit.message"="Merge pull request #204 from jeffdyoung/ppc64le"
STEP 3: ENV OPENSHIFT_BUILD_NAME="nodejs-ex-5"     OPENSHIFT_BUILD_NAMESPACE="test"     OPENSHIFT_BUILD_SOURCE="https://github.com/openshift/nodejs-ex"     OPENSHIFT_BUILD_COMMIT="905416d88f74bfb734efac2a7e835948128a1df1"
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 1001:0 /tmp/src
STEP 7: USER 1001
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source
---> Building your Node application from source
Current git config
url.https://github.com.insteadof=git@github.com:
url.https://.insteadof=ssh://
url.https://github.com.insteadof=ssh://git@github.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/openshift/nodejs-ex
remote.origin.fetch=+refs/heads/master:refs/remotes/origin/master
branch.master.remote=origin
branch.master.merge=refs/heads/master
---> Installing dependencies
---> Using 'npm install -s --only=production'
added 120 packages from 353 contributors and audited 198 packages in 3.604s
found 5 vulnerabilities (2 low, 1 moderate, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
---> Cleaning up npm cache
---> Fix permissions on app-root
STEP 9: CMD /usr/libexec/s2i/run
STEP 10: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]temp.builder.openshift.io/test/nodejs-ex-5:57646f8d
Getting image source signatures
Skipping fetch of repeat blob sha256:1d31b5806ba40b5f67bde96f18a181668348934a44c9253b420d5f04cfb4e37a
Skipping fetch of repeat blob sha256:f9bf6da67ad76eda795b09950846da99c31057732f81be0c8ca5cfb6765b4e78
Skipping fetch of repeat blob sha256:cd97d0208235aecc4598e631755f2e7b3e0507c0417624b48952de773e847a1d
Skipping fetch of repeat blob sha256:f0897fc7c83ef3ac1a5de2783fe98dde5fe543aafa9c21f1086edc4064704b4c
Skipping fetch of repeat blob sha256:c9ea146b90092dd458a829fdfbf22b59da533d8f29788721a25d3237e8880366
Skipping fetch of repeat blob sha256:47e56bf0fc10dbc6e237ec2809085e41ededf0203cd5a1603d1c39ea29c6997e
Copying blob sha256:3ebf8a7e73b732045337a029b137c5f064032e9e0133594df4adf7242aea991e
 8.19 MiB / 8.19 MiB  0s
Copying config sha256:d7579df434c3d2d0ce2399ca83fb277e9fd1433f66ce9e1ecaab08e9125ae44e
 14.72 KiB / 14.72 KiB  0s
Writing manifest to image destination
Storing signatures
--> d7579df434c3d2d0ce2399ca83fb277e9fd1433f66ce9e1ecaab08e9125ae44e

Pushing image 172.30.255.124:5000/test/nodejs-ex:latest ...
Getting image source signatures
Copying blob sha256:1d31b5806ba40b5f67bde96f18a181668348934a44c9253b420d5f04cfb4e37a
 198.64 MiB / 198.64 MiB  19s
Copying blob sha256:f9bf6da67ad76eda795b09950846da99c31057732f81be0c8ca5cfb6765b4e78
 29.49 MiB / 29.49 MiB  2s
Copying blob sha256:cd97d0208235aecc4598e631755f2e7b3e0507c0417624b48952de773e847a1d
 20.00 KiB / 20.00 KiB  0s
Copying blob sha256:f0897fc7c83ef3ac1a5de2783fe98dde5fe543aafa9c21f1086edc4064704b4c
 1.99 MiB / 1.99 MiB  0s
Copying blob sha256:c9ea146b90092dd458a829fdfbf22b59da533d8f29788721a25d3237e8880366
 240.29 MiB / 240.29 MiB  21s
Copying blob sha256:47e56bf0fc10dbc6e237ec2809085e41ededf0203cd5a1603d1c39ea29c6997e
 724.08 MiB / 724.08 MiB  1m6s
Copying blob sha256:3ebf8a7e73b732045337a029b137c5f064032e9e0133594df4adf7242aea991e
 8.19 MiB / 8.19 MiB  0s
Copying config sha256:d7579df434c3d2d0ce2399ca83fb277e9fd1433f66ce9e1ecaab08e9125ae44e
 14.72 KiB / 14.72 KiB  0s
Writing manifest to image destination
Storing signatures
Successfully pushed //172.30.255.124:5000/test/nodejs-ex:latest@7352cb6297087c8ac640cfe3942e6637fa5726bc1ccb3d8c605d73c594340f7a
Push successful
```

@nalind

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
Yes, I’m working on that in https://github.com/mtrmac/image/tree/blob-info-caching .

**Comment by rhatdan** [comment]
@mtrmac any progress?

**Comment by mtrmac** [comment]
> @mtrmac any progress?

@rhatdan https://github.com/containers/buildah/pull/1193#issuecomment-442318275

**Comment by wwilson** [comment]
It looks like this is now fixed in containers/image:

https://github.com/containers/image/pull/526

Is the next step to vendor this into buildah?

**Comment by mtrmac** [comment]
That has already happened in https://github.com/containers/buildah/pull/1218 , so this should work as expected with current `master`.

**Comment by rhatdan** [comment]
CLosing as it is in master.

**Comment by 42wim** [comment]
It works, but buildah doesn't yet behave completely like docker for this.

We're using artifactory as docker registry and we have multiple registries on it (with multiple hostnames, registry1.tld, registry2.tld), the current code will only check blobs from the same registry although they're also available on the other. 

with docker doing a 
```
docker pull registry1.tld/image:tag
docker tag registry1.tld/image:tag registry2.tld/image2:tag 
docker push registry2.tld/image2:tag
```
will not push the image to registry2.tld because it's already there (i'm not sure if this is default registry behaviour, but it does so with artifactory and docker).

Doing the same with buildah will cause a repush of the image as it's not checking for the existing blob.

Removing the registry sanity checks and setting always the same `scope.Opaque` in the boltdb cache fixes this for me and now buildah behaves the same as docker.

Is there a reason why this isn't the default action, are there security implications ? (as it are sha256 hashes creating collisions there are not feasible)

My changes are here https://github.com/42wim/buildah/commit/4464fa64013b2c7a4584944bff4c67681bb8aa87 in the vendored github.com/containers/image directory

**Comment by rhatdan** [comment]
@mtrmac WDYT?

**Comment by rhatdan** [comment]
@42wim Could you open an issue with containers/image or better yet a PR so we can discuss it there?

**Comment by devurandom** [comment]
In which version was this released?

I am using buildah 1.7.1 and still see it repeatedly pushing layers originating from `docker://docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine` to my own repository at `docker://docker.io/<...>` every single time I run `buildah push`. Each time the registry is the same, the repository is the same, and only the tag differs. I would expect buildah to not push the layers from `docker://docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine` at all, but only those that I added.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by devurandom** [comment]
How to reproduce:
```
$ buildah pull docker://docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine
$ buildah push docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine docker://docker.io/devurandom/issue-1048
Getting image source signatures
Copying blob bcf2f368fe23 [======================================] 5.5MiB / 5.5MiB
Copying blob 344fb4b275b7 [======================================] 3.5KiB / 3.5KiB
Copying blob 714e1dd7c2e4 [======================================] 95.6MiB / 95.6MiB
Copying blob 985f0e8ca9de [======================================] 18.6MiB / 18.6MiB
Copying blob c9782632b293 [======================================] 14.0MiB / 14.0MiB
Copying blob f2974ddaacff [======================================] 4.4MiB / 4.4MiB
Copying config e9daa35cb7 [======================================] 6.2KiB / 6.2KiB
Writing manifest to image destination
Storing signatures
Successfully pushed //devurandom/issue-1048:latest@sha256:8cf2993a0eb9e5b1b39ca198765bb90ac0a0a80156f173c8e8093f8c047436fd
$ buildah push docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine docker://docker.io/devurandom/issue-1048
Getting image source signatures
Copying blob bcf2f368fe23 [==============================>-------] 4.5MiB / 5.5MiB
Copying blob 344fb4b275b7 [======================================] 3.5KiB / 3.5KiB
Copying blob 714e1dd7c2e4 [=>------------------------------------] 5.0MiB / 95.6MiB
Copying blob 985f0e8ca9de [=========>----------------------------] 5.0MiB / 18.6MiB
Copying blob c9782632b293 [============>-------------------------] 4.8MiB / 14.0MiB
Copying blob f2974ddaacff [======================================] 4.4MiB / 4.4MiB
^C⏎
```

The same also happens when pushing images derived from `docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine` that only add one additional layer and whose name does not start with `docker.io/`, i.e. they are definitely and unmistakably local.

**Comment by mtrmac** [comment]
@devurandom thanks for your report.

Can you re-test with `buildah --debug push …`, please? When trying this, I do see debug entries like
```
DEBU[0000] Skipping blob sha256:714e1dd7c2e4561ac781f38261a4985a3e6e9f5aa84b8b1640d73510d1471e61 (already present): 
```

I’m afraid the _progress bars_ always exist in that version, even if no copy actually happens; 
https://github.com/containers/image/pull/603 will make that clearer in the future.

The `--debug` output should also clarify whether/how the cache is being used, either
```
DEBU[0000] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 
```
or a debug entry saying `using a memory-only cache`.

**Comment by devurandom** [comment]
My problem is not with the progress bars per se, but they show that `buildah push` is actually uploading something. (And uploading 95MB takes an awfully long time with my internet connection.)

```
$ buildah --debug push docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine docker://docker.io/devurandom/issue-1048
DEBU[0000] running [buildah-in-a-user-namespace --debug push docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine docker://docker.io/devurandom/issue-1048] with environment [<...> _BUILDAH_STARTED_IN_USERNS=1 BUILDAH_ISOLATION=rootless], UID map [{HostID:1000 ContainerID:0 Size:1} {HostID:10000 ContainerID:1 Size:1000}], and GID map [{HostID:1000 ContainerID:0 Size:1} {HostID:10000 ContainerID:1 Size:1000}]
DEBU[0000] [graphdriver] trying provided driver "vfs"
DEBU[0000] registry "docker.io" is not listed in registries configuration "/etc/containers/registries.conf", assuming it's not blocked
DEBU[0000] parsed reference into "[vfs@/home/<USERNAME>/.local/share/containers/storage+/run/user/1000]docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine"
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
DEBU[0000]  Using "default-docker" configuration
DEBU[0000]   Using file:///var/lib/atomic/sigstore
DEBU[0000] error accessing certs directory due to permissions: stat /etc/docker/certs.d/docker.io: permission denied
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io
DEBU[0000] Skipping scan of /etc/docker/certs.d/docker.io due to permission error: open /etc/docker/certs.d/docker.io: permission denied
DEBU[0000] Error creating parent directories for blob-info-cache-v1.boltdb, using a memory-only cache: mkdir /var/lib/containers/cache: permission denied
DEBU[0000] IsRunningImageAllowed for image containers-storage:[vfs@/home/<USERNAME>/.local/share/containers/storage]docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine@e9daa35cb7cbb3e8ec35a10ba7ce75bf5e2446aafdde24c09319c2695aad7633
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] Checking /v2/devurandom/issue-1048/blobs/sha256:344fb4b275b72fa2f835af4a315fa3c10e6b14086126adc01471eaa57659f7a5
DEBU[0000] Checking /v2/devurandom/issue-1048/blobs/sha256:985f0e8ca9de22f0e84a42cfad63dc274bc7553c3c90528b01f235cf4f9804e9
DEBU[0000] Checking /v2/devurandom/issue-1048/blobs/sha256:f2974ddaacff81c31123eb45c664798d07a842497e789aa830cd5dece5c4fcad
DEBU[0000] GET https://registry-1.docker.io/v2/
DEBU[0000] Checking /v2/devurandom/issue-1048/blobs/sha256:bcf2f368fe234217249e00ad9d762d8f1a3156d60c442ed92079fa5b120634a1
DEBU[0000] Checking /v2/devurandom/issue-1048/blobs/sha256:714e1dd7c2e4561ac781f38261a4985a3e6e9f5aa84b8b1640d73510d1471e61
DEBU[0000] Checking /v2/devurandom/issue-1048/blobs/sha256:c9782632b29336d8b74bcf2515a07ab22d55fd16007c576be85068558728fb60
Copying blob bcf2f368fe23 [--------------------------------------] 0b / 5.5MiB
Copying blob 344fb4b275b7 [--------------------------------------] 0b / 3.5KiB
Copying blob 714e1dd7c2e4 [--------------------------------------] 0b / 95.6MiB
Copying blob 985f0e8ca9de [--------------------------------------] 0b / 18.6MiB
Copying blob c9782632b293 [--------------------------------------] 0b / 14.0MiB
Copying blob f2974ddaacff [--------------------------------------] 0b / 4.4MiB
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401
Copying blob bcf2f368fe23 [--------------------------------------] 0b / 5.5MiB
Copying blob 344fb4b275b7 [--------------------------------------] 0b / 3.5KiB
Copying blob 714e1dd7c2e4 [--------------------------------------] 0b / 95.6MiB
Copying blob 985f0e8ca9de [--------------------------------------] 0b / 18.6MiB
Copying blob c9782632b293 [--------------------------------------] 0b / 14.0MiB
Copying blob f2974ddaacff [--------------------------------------] 0b / 4.4MiB
Copying blob bcf2f368fe23 [--------------------------------------] 0b / 5.5MiB
Copying blob 344fb4b275b7 [--------------------------------------] 0b / 3.5KiB
Copying blob 714e1dd7c2e4 [--------------------------------------] 0b / 95.6MiB
Copying blob 985f0e8ca9de [--------------------------------------] 0b / 18.6MiB
Copying blob bcf2f368fe23 [--------------------------------------] 0b / 5.5MiB
Copying blob 344fb4b275b7 [--------------------------------------] 0b / 3.5KiB
Copying blob 714e1dd7c2e4 [--------------------------------------] 0b / 95.6MiB
Copying blob 985f0e8ca9de [--------------------------------------] 0b / 18.6MiB
Copying blob c9782632b293 [--------------------------------------] 0b / 14.0MiB
Copying blob f2974ddaacff [--------------------------------------] 0b / 4.4MiB
DEBU[0001] ... not present
DEBU[0001] exporting filesystem layer "c6bfa152e298b90baccc06b383b3745f2c68c9bb2fca7fe9c282c72c20aa36db" without compression for blob "sha256:f2974ddaacff81c31123eb45c664798d07a842497e789aa830cd5dece5c4fcad"
DEBU[0001] ... not present
DEBU[0001] exporting filesystem layer "4425bdb56d6cf9f407bb697fd204ef975a7495fe783c8f33255e59e175b872c5" without compression for blob "sha256:344fb4b275b72fa2f835af4a315fa3c10e6b14086126adc01471eaa57659f7a5"
DEBU[0001] ... not present
DEBU[0001] exporting filesystem layer "bcf2f368fe234217249e00ad9d762d8f1a3156d60c442ed92079fa5b120634a1" without compression for blob "sha256:bcf2f368fe234217249e00ad9d762d8f1a3156d60c442ed92079fa5b120634a1"
Copying blob bcf2f368fe23 [--------------------------------------] 0b / 5.5MiB
Copying blob 344fb4b275b7 [--------------------------------------] 0b / 3.5KiB
Copying blob 714e1dd7c2e4 [--------------------------------------] 0b / 95.6MiB
Copying blob 985f0e8ca9de [--------------------------------------] 0b / 18.6MiB
Copying blob c9782632b293 [--------------------------------------] 8b / 14.0MiB
Copying blob f2974ddaacff [--------------------------------------] 0b / 4.4MiB
DEBU[0001] No compression detected
DEBU[0001] Compressing blob on the fly
DEBU[0001] Uploading /v2/devurandom/issue-1048/blobs/uploads/
DEBU[0001] POST https://registry-1.docker.io/v2/devurandom/issue-1048/blobs/uploads/
DEBU[0001] No compression detected
DEBU[0001] Compressing blob on the fly
DEBU[0001] Uploading /v2/devurandom/issue-1048/blobs/uploads/
DEBU[0001] POST https://registry-1.docker.io/v2/devurandom/issue-1048/blobs/uploads/
DEBU[0001] No compression detected
DEBU[0001] Compressing blob on the fly
DEBU[0001] Uploading /v2/devurandom/issue-1048/blobs/uploads/
DEBU[0001] POST https://registry-1.docker.io/v2/devurandom/issue-1048/blobs/uploads/
DEBU[0001] No compression detected
DEBU[0001] Compressing blob on the fly
Copying blob bcf2f368fe23 [--------------------------------------] 8b / 5.5MiB
Copying blob bcf2f368fe23 [--------------------------------------] 8b / 5.5MiB
Copying blob 344fb4b275b7 [--------------------------------------] 8b / 3.5KiB
Copying blob 714e1dd7c2e4 [--------------------------------------] 8b / 95.6MiB
Copying blob 985f0e8ca9de [--------------------------------------] 8b / 18.6MiB
Copying blob c9782632b293 [--------------------------------------] 8b / 14.0MiB
Copying blob bcf2f368fe23 [==============================>-------] 4.5MiB / 5.5MiB
Copying blob 344fb4b275b7 [======================================] 3.5KiB / 3.5KiB
Copying blob bcf2f368fe23 [==============================>-------] 4.5MiB / 5.5MiB
Copying blob bcf2f368fe23 [======================================] 5.5MiB / 5.5MiB
Copying blob 344fb4b275b7 [======================================] 3.5KiB / 3.5KiB
Copying blob 714e1dd7c2e4 [==>-----------------------------------] 8.5MiB / 95.6MiB
Copying blob 985f0e8ca9de [=============>------------------------] 7.0MiB / 18.6MiB
Copying blob c9782632b293 [=================>--------------------] 6.5MiB / 14.0MiB
Copying blob f2974ddaacff [======================================] 4.4MiB / 4.4MiB
^C⏎
```

Please note that I redacted the output of environment variables and am showing you only the last two. If you need the value of specific environment variables, please ask for them. Likewise, I also redacted my username.

**Comment by mtrmac** [comment]
> ```
> DEBU[0000] Error creating parent directories for blob-info-cache-v1.boltdb, using a memory-only cache: mkdir /var/lib/containers/cache: permission denied
> ```

You are running in some kind of confined `root` account it seems, preventing the recording and use of the data necessary to avoid re-pushing.

**Comment by devurandom** [comment]
> > ```
> > DEBU[0000] Error creating parent directories for blob-info-cache-v1.boltdb, using a memory-only cache: mkdir /var/lib/containers/cache: permission denied
> > ```
> 
> You are running in some kind of confined `root` account it seems, preventing the recording and use of the data necessary to avoid re-pushing.

I am running `buildah` as a regular user. Is something special necessary to support this? For example when when building `buildah` yourself?

**Comment by devurandom** [comment]
To test that hypothesis I temporarily made `/var/lib/containers` world-writable, but still `buildah` tries to upload the `714e1dd7c2e4`-layer, even though it for sure is already in the repository, since I previously pushed the whole image.

**Comment by mtrmac** [comment]
Interesting; 

> > > ```
> > > DEBU[0000] Error creating parent directories for blob-info-cache-v1.boltdb, using a memory-only cache: mkdir /var/lib/containers/cache: permission denied
> > > ```
> > 
> > 
> > You are running in some kind of confined `root` account it seems, preventing the recording and use of the data necessary to avoid re-pushing.
> 
> 
> I am running `buildah` as a regular user. Is something special necessary to support this? For example when when building `buildah` yourself?

I’m sorry, you are right; apparently rootless `buildah` does end up with `Geteuid() == 0` at that pull/push path.

Is it _intended_ that `buildah` runs within a user namespace during the pull/push process, without any container being involved?

If so, that gets us into a ~surprising situation that `Geteuid() == 0`, not a different FS namespace (at least, I assume?), but system-wide paths are not accessible.


> To test the hypothesis that the cause is just the writeability of the `/var/lib/containers` directory, I temporarily made `/var/lib/containers` world-writable, but still `buildah` tries to upload the `714e1dd7c2e4`-layer. This is even though it for sure is already in the repository, since I previously pushed the whole image.

FWIW `buildah` can only avoid redundant pushes on the _second_ attempt; the first one uploads the image _and_ records that it has been uploaded and what the result of compressing the image is, the second one uses the recorded compression results to notice that a re-upload is not necessary. Only one push with the cache involved will always do a full upload.

**Comment by devurandom** [comment]
> FWIW buildah can only avoid redundant pushes on the second attempt; the first one uploads the image and records that it has been uploaded and what the result of compressing the image is, the second one uses the recorded compression results to notice that a re-upload is not necessary. Only one push with the cache involved will always do a full upload.

Is it not possible to download the list of layers present in the remote repository before starting to upload anything? Those do not even have to be stored permanently, if the cache directory is not accessible, but should be small enough to hold in memory.

**Comment by mtrmac** [comment]
> > Is it intended that buildah runs within a user namespace during the pull/push process, without any container being involved?
> 
> No idea. I did not do that on purpose. `buildah` must be doing that by itself.

Sure; that was a question put to buildah maintainers, I’m sorry about being unclear.

> > FWIW buildah can only avoid redundant pushes on the second attempt; the first one uploads the image and records that it has been uploaded and what the result of compressing the image is, the second one uses the recorded compression results to notice that a re-upload is not necessary. Only one push with the cache involved will always do a full upload.
> 
> Is it not possible to download the list of layers present in the remote repository before starting to upload anything

- No.
- Even if it were possible, the mapping between uncompressed data on local disk and compressed data in the registry needs to exist for the two to match; and that’s what the “blob info cache” is supposed to be.

**Comment by devurandom** [comment]
Can I make `buildah` compress the local data, so that it can compare it directly with the data in the registry?

Some information on the `/var/lib/containers` directory: `buildah push` creates `/var/lib/containers/cache` with my regular user being the owner. There appears to be no other user ID involved, i.e. not even those that I granted to `buildah` using `/etc/subuid`.

**Comment by mtrmac** [comment]
> Can I make `buildah` compress the local data, so that it can compare it directly with the data in the registry?

No.

The cache is supposed to work. Let’s just make it work instead of inventing a completely different implementation.

**Comment by rhatdan** [comment]
If you are running as non root then /var/lib/containers/cache should not be used.  We should be using ~/.local/share/containers/cache
Could this be the bug?

**Comment by mtrmac** [comment]
I’ve reproduced this; apparently rootless buildah ends up with EUID=0 at the point of the image copy, and that’s why the copy code tries to use the root-owned cache path.

(Sure, buildah could override that path, but it’s not just _this_ path; e.g. the path of `~/.docker/config.json` would also point to root’s path if (R)UID==0. So, this seems like a more general design concern — one that I expect has already been considered, with a known solution / design decision. So, I’m asking about the existing design, not trying to reverse-engineer what it is, at this point.)

**Comment by rhatdan** [comment]
@giuseppe @mtrmac We can fix the blob path in the buildah patch above.  I am not sure how we fix the ~/.docker/config.json, if this is read after entering the User Namespace.

**Comment by devurandom** [comment]
Regarding the finding-existing-layers-on-first-push issue, just for comparison: `docker push` will also find layers present in other repositories and e.g. report `714e1dd7c2e4: Mounted from library/clojure` on the first push. On subsequent pushes it will report `714e1dd7c2e4: Layer already exists`. (Same for `bcf2f368fe23`, which I tried to find using `skopeo` previously.)

**Comment by mtrmac** [comment]
Docker works exactly the same way AFAIK, it’s only that you’ve had a working “cache” recording the necessary data for some time, but with `buildah` you are starting from scratch.
