### ISSUE TITLE
Tutorial install instructions omit RHEL repository information

### ISSUE THREAD

**Issue by estroz** [containers/buildah#1054]
**Description**

`buildah` installation instructions in the [intro tutorial](https://github.com/containers/buildah/blob/master/docs/tutorials/01-intro.md) omit a few steps necessary to install on RHEL. You have to consult [`install.md`](https://github.com/containers/buildah/blob/master/install.md) or search for [these docs](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/finding_running_and_building_containers_without_docker) for full instructions. I can create a PR with these additions for the tutorial page if you'd like.

**Comment by TomSweeneyRedHat** [comment]
Please and Thank You @estroz !

**Comment by TomSweeneyRedHat** [comment]
Closed with #1060
