### ISSUE TITLE
buildah tries to parse incorrect value

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1057]
https://github.com/containers/buildah/blob/master/pull.go#L193-L204

Two problems with this code:

1) pullError should be logged when it's non-nil
2) the hasRegistry() call ultimately fails because it's passing a `docker://blahblah` value to `Parse()` which doesn't expect the protocol prefix and throws an error.  (an error which is *also* not logged in a useful manner since it just reports `error parsing image name` without showing the value it was trying to parse).

@nalind

**Comment by TomSweeneyRedHat** [comment]
@bparees the hasRegistry() function was replaced in https://github.com/containers/buildah/commit/6e0074eeedbc903acddeb7bb04093d615de055e5.  However that was still having issues with handling a fully specified image name like `docker://blahblah`.  I've hopefully addressed that with #1117.

I'll work on logging the non-nil error, I'll see if I can sneak that into #1117 too.

**Comment by rhatdan** [comment]
It looks like this is fixed.
