### ISSUE TITLE
Sort CLI flags

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1086]
@QiWang19 create this PR: https://github.com/containers/libpod/pull/1619 in Podman.  We need to do a similar thing here in Buildah.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan when you get a chance, can you tweak whatever bits for @QiWang19 here in Buildah that you did in Podman please?  We can't get Git to let us assign the issue to herself.  I've self assigned just to hold it for the moment.

**Comment by rhatdan** [comment]
Seems like we have it.
