### ISSUE TITLE
Buildah bud chokes when running in a non default network namespace

### ISSUE THREAD

**Issue by najamelan** [containers/buildah#1094]
**Description**

I have setup my system so as to only allow internet access from certain ns namespaces (for security). This means that I have to run buildah in a ns that is not the default if I want it to download packages during container build. However when doing so, I get the following error:

`container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused "mountpoint for cgroup not found""`

The error takes place on the first `RUN` command in the docker file, even for something like `RUN id`

When running in the default namespace, I don't get this error, but I can't build succesfully, because of lacking internet access.

**Steps to reproduce the issue:**
1. Create a docker file with a `RUN` command
2. run buildah bud in a network namespace other than the default with `ip netns exec namespace buildah bud ....`

**Output of `buildah version`:**
```
buildah 1.4-2
```

**Output of `cat /etc/*release`:**

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Output of `uname -a`:**

```
Linux computer 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

has not been changed from the defaults

**Comment by rhatdan** [comment]
@ypu Could you try this out with buildah 1.5 and see if it still happens.

**Comment by najamelan** [comment]
Sorry for the delay, I'm plugged into internet again. I just tested with buildah version: 
```
Version:         1.5
Go Version:      go1.11.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      e94b4f98
Built:           Wed Nov 28 11:10:56 2018
OS/Arch:         linux/amd64
```
I still have the same error, except for the line numbers:
`container_linux.go:337: starting container process caused "process_linux.go:280: applying cgroup configuration for process caused \"mountpoint for cgroup not found\""`

**Comment by rhatdan** [comment]
@najamelan Could you give us the exact Command you are executing and a simplified Dockerfile, which shows this issue?

By any chance could you check if `podman build` also shows this behaviour?

Lastly are you executing buildah as root or non-root.

**Comment by TomSweeneyRedHat** [comment]
@najamelan Can you run the command again with `--debug` please?  `bulidah --debug bud ...` and let us know what shows up there.  Also is there anyghing in journalctl of interest?

**Comment by najamelan** [comment]
I try to give you a complete guide to reproduce. You need to run buildah in a network namespace that is not the default. I run into this because my default namespace does not have internet access and buildah wants to download the base image. So I suppose you will probably need a ns with internet access. To set this up is +/- like this:
```bash
# Make sure the kernel can forward packages:
#
sysctl --write net.ipv4.ip_forward=1

# create a new namespace
#
ip netns add container

# create a virtual ethernet device to connect it to your default namespace
#
ip link add def_container type veth peer name container_def

# Move one end into the container ns
#
ip link set container_def netns container

# Give them both an ip address
#
                         ip addr add 10.0.0.10/24  dev def_container
ip netns exec container  ip addr add 10.0.0.20/24  dev container_def

# Turn them on
#
                         ip link set def_container  up
ip netns exec container  ip link set container_def  up

# Setup the routing
#
                        ip route add 10.0.0.20  via 10.0.0.10
ip netns exec container ip route add default    via 10.0.0.10


# Ok, all that's left for internet access is NAT masquerading. You can do it with any firewall you want, this is firehol configuration:
#
# Nat for container
#
router4 container2internet outface eth0  src 10.1.1.20 <--- CHANGE THE NAME OF YOUR NETWORK CARD IF NEEDED (eg. eth0 or wlan0)

	# does not inherit the rule parameters from router (so re-specify src)
	#
	masquerade src 10.1.1.20

	server     any accept
	policy         reject

```
You can do all this in a virtual machine if you don't want to mess with your network setup as long as the vm has internet access.
Now you should be able to run commands that need internet in the new network namespace:
```bash
# get a shell in the new ns
#
ip netns exec container bash

# verify that it works
#
ping 8.8.8.8
```

Contents of `Dockerfile`
```Dockerfile
FROM alpine:latest

RUN id
```

Command: `buildah bud --tag buildahbug .` Verify that it works in the default namespace, then verify it does not work in the container namespace.

Feedback:
Nothing shows up in journalctl
Running as root or unprivileged gives the same result.
Output from podman-build is almost identical, it does not seem to recognise a --debug option.

Output from --debug, this is the last part, and I suppose the relevant part, the rest is in the attached [buildah.log](https://github.com/containers/buildah/files/2721243/buildah.log):
```
DEBU[0000] Running ["runc" "create" "--bundle" "/tmp/buildah603891595" "--pid-file" "/tmp/buildah603891595/pid" "--no-new-keyring" "--console-socket" "/tmp/buildah603891595/console.sock" "buildah-buildah603891595"] 
container_linux.go:337: starting container process caused "process_linux.go:280: applying cgroup configuration for process caused \"mountpoint for cgroup not found\""
DEBU[0000] "/tmp/buildah603891595/mnt/rootfs" is apparently not really mounted, skipping 
error running container: error creating container for [/bin/sh -c id]: : exit status 1
ERRO[0001] error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[id] Flags:[] Attrs:map[] Message:RUN id Original:RUN id}: error while running runtime: exit status 1 
ERRO[0001] exit status 1                                
```

**Comment by najamelan** [comment]
Ok, I found something relevant. When run in a network namespace, `mount | grep cgroup` will return nothing. It seems you can't see any cgroup mount points from within a network namespace. I have no idea why this is. I will investigate a bit further.

**Comment by najamelan** [comment]
I made some progress. Apparently `ip netns exec` creates a mount namespace, in order to bind mount network configuration files like resolv.conf per namespace. I suppose that they don't propagate all other mount points to the new namespace. I will ask if that's intended behavior.

**Comment by najamelan** [comment]
According to Eric Biederman the code for iproute2 will need to be updated since cgroups and others aren't mounted in the same way they used to. So I will close this because it's not a buildah issue. No idea of the ETA for a patch.
