### ISSUE TITLE
`buildah version` errors out

### ISSUE THREAD

**Issue by TomasTomecek** [containers/buildah#1106]
```
# buildah version
strconv.ParseInt: parsing "": invalid syntax
# rpm -q buildah
buildah-1.4-2.dev.git19e44f0.fc30.x86_64
# buildah --debug version
ERRO[0000] strconv.ParseInt: parsing "": invalid syntax 
```

Same error when invoked both as root and as a normal user.

This is Fedora Rawhide.

**Comment by TomSweeneyRedHat** [comment]
Interesting, not happening for me on F29, but will take a look.

Thanks for the report @TomasTomecek

**Comment by TomSweeneyRedHat** [comment]
@lsm5 the version.go file looks for main.buildInfo variable to get the build time of the Buildah project.  The Makefile code looks like:

```
/Makefile:BUILD_INFO := $(if $(shell date +%s),$(shell date +%s),$(error "date failed"))
./Makefile:LDFLAGS := -ldflags '-X main.gitCommit=${GIT_COMMIT} -X main.buildInfo=${BUILD_INFO} -X main.cniVersion=${CNI_COMMIT}'
```
This seems to be working in Fedora 28/29 and other places just fine, but not apparently in Fedora Rawhide?  Any thoughts as to why?

**Comment by swilmet-uclouvain** [comment]
I have the same problem with the buildah package installed from Fedora 29: `buildah-1.4-3.git608fa84.fc29.x86_64`

**Comment by rhatdan** [comment]
Could you try

dnf -y update buildah --enablerepo=updates-testing

And see if it works correctly in buildah 1.5?

**Comment by TomSweeneyRedHat** [comment]
This should be fixed in upstream and v1.5 of Buildah.  We just cut the v1.5 on Thursday and are working on getting RPM's together now for it.

**Comment by swilmet-uclouvain** [comment]
> Could you try
> 
> dnf -y update buildah --enablerepo=updates-testing
> 
> And see if it works correctly in buildah 1.5?

I confirm that it works correctly with buildah 1.5, thanks!

**Comment by TomasTomecek** [comment]
yup, works
