### ISSUE TITLE
rootless buildah should honor ~/.config/containers/storage.conf

### ISSUE THREAD

**Issue by giuseppe** [containers/buildah#1113]
**Description**

when re-executing in a new user namespace, "vfs" is hardcoded as the storage driver.

Podman changes some of the defaults in `storage.DefaultStoreOptions` when in rootless mode:

https://github.com/containers/libpod/blob/master/cmd/podman/libpodruntime/runtime.go#L40

These settings can be overriden by the `~/.config/containers/storage.conf` file

**Comment by rhatdan** [comment]
@giuseppe could you open a PR to make this happen?

**Comment by mathstuf** [comment]
Hmm. Maybe `registries.conf` could also be read from the user's config directory too while we're at it? Or is that a different codepath altogether?

**Comment by rhatdan** [comment]
@giuseppe https://github.com/containers/libpod/pull/1693 to get buildah to honor storage settings.

**Comment by giuseppe** [comment]
I've opened a PR that adds the missing pieces to buildah: https://github.com/containers/buildah/pull/1124

@mathstuf that will be supported once the PR lands, and a per-user `~/.config/containers/registries.conf` file is used.
