### ISSUE TITLE
buildah from fail when using an explicit docker: transport

### ISSUE THREAD

**Issue by robmv** [containers/buildah#1117]
**Description**

`buildah from` fail when using an explicit `docker:` transport. This is a regression, probably caused by  the introduction of `buildah pull`, It worked before 1.4 release.

**Steps to reproduce the issue:**
1. Run `buildah from docker://centos:centos7` or `buildah from docker://docker.io/centos:centos7`

**Describe the results you received:**

Both cases fail with the error `invalid reference format` error when the `docker:` transport is explicit.

**Describe the results you expected:**

It should work as when the `docker:` transport is implicit as `buildah pull docker://centos:centos7` and `buildah pull docker://docker.io/centos:centos7` works perfectly.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.4-3.git608fa84.fc28.x86_64
```

**Output of `buildah version`:**

```
Version:         1.4
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      608fa84
Built:           Thu Oct  4 12:40:10 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
Linux private.example.com 4.18.13-200.fc28.x86_64 #1 SMP Wed Oct 10 17:29:59 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:** (Comments removed)

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
mountopt = "nodev"

[storage.options.thinpool]
ostree_repo = ""
skip_mount_home = "false"
```

**Comment by TomSweeneyRedHat** [comment]
@robmv Interesting.  Thanks for the issue report, will take a look into it.

**Comment by TomSweeneyRedHat** [comment]
@robmv #1120 should fix this issue for you.  If not, please reopen this issue or create a new one as appropriate.  Thanks again for letting us know about the problem.
