### ISSUE TITLE
Export rootfs of an image

### ISSUE THREAD

**Issue by mathstuf** [containers/buildah#1118]
It'd be nice if buildah could export a rootfs to a directory, tarball, or mount to a given directory. My use case is that I'd like to use `systemd-nspawn` to run the resulting containers, but there's no way to export and/or mount an image filesystem at a well-known location (namely `/var/lib/machines/$nspawn_name`) for use with it.

I suppose one way to do it is to have some `ExecStartPre=` to `buildah mount` followed by a bind mount to `/var/lib/machines/%i`, but passing the directory that `buildah` has mounted needs a pipe which isn't easy without a shell script or the like to make the proper command line. It would also be susceptible to `buildah umount -a` causing failures (either on the `systemd-nspawn` side or on the `buildah umount` side).

**Comment by mathstuf** [comment]
Actually, I missed that only *containers* can be mounted, so `buildah mount $image` would be nice to have first.

**Comment by mathstuf** [comment]
A quick poke makes it look like it isn't exactly straightforward, but I also might be missing something.

**Comment by rhatdan** [comment]
Do you want this thing to be readonly?  If readonly we could allow the mounting of an image, but it would take some wiring into containers/storage and then be pickupable by podman/buildah.

If you want to be able to modify the image, then you really do want a container.  A buildah container that has not been modified is pretty much the equivalent of an image.

**Comment by mathstuf** [comment]
My containers are `ReadOnly=true`, so I'm fine with that restriction.

**Comment by rhatdan** [comment]
@nalind How hard would it be to get containers/storage to mount images read/only at a specific location?  Or would we still need to mount then in the same location, and force the user to bind mount to their desired location?

**Comment by rhatdan** [comment]
I think we will tell users to bind mount from the hard coded location.

**Comment by mathstuf** [comment]
That's unfortunate because that location is not stable (it depends on the container ID which is not predictable given an image name/ID). Maybe some kind of "how to" example could be added to the docs?

**Comment by andrew-aladev** [comment]
@mathstuf 
```
crossdev_container=$(buildah from "$DOCKER_USERNAME/aarch64-unknown-linux-gnu-gentoo-stable-amd64-crossdev:latest")
crossdev=$(buildah mount "$crossdev_container")
copy "$crossdev/usr/aarch64-unknown-linux-gnu/" /
buildah unmount "$crossdev_container"
```

I've just used this code, works fine.

**Comment by mathstuf** [comment]
I ended up with:

```sh
#!/bin/sh

set -e

readonly image="$1"
shift

readonly target="/var/lib/machines/$image"

readonly container="$( buildah from --pull=false --name "infra.$image" "$image:latest" )"
readonly mount="$( buildah mount "$container" )"
exec mount -o bind "$mount" "$target"
```

and a corresponding umount script:

```sh
#!/bin/sh

readonly image="$1"
shift

readonly target="/var/lib/machines/$image"

umount "$target"
buildah umount "infra.$image"
exec buildah rm "infra.$image"
```

that gets run as part of the `ExecStartPre` and `ExecStopPost` commands in the `.service` associated with each image's systemd service.
