### ISSUE TITLE
image push resumed at wrong offset

### ISSUE THREAD

**Issue by bparees** [containers/buildah#1133]
I'm seeing sporadic push failures... from the buildah side, the error is:

```
2018-10-28T02:39:21.258666068Z error: build error: Failed to push image: error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.skip_mount_home=false,overlay.mountopt=nodev,overlay.override_kernel_check=false]docker-registry.default.svc:5000/e2e-test-build-image-source-r8gd7/inputimage:latest" to "docker://docker-registry.default.svc:5000/e2e-test-build-image-source-r8gd7/inputimage:latest": Error writing blob: Error uploading layer to https://docker-registry.default.svc:5000/v2/e2e-test-build-image-source-r8gd7/inputimage/blobs/uploads/c38c3834-65d9-4378-9b85-d0c6d841abb3?_state=x36zMpkRWAUwQMA45gqwbIwb4oOSQmGRqi8shuHLjM17Ik5hbWUiOiJlMmUtdGVzdC1idWlsZC1pbWFnZS1zb3VyY2UtcjhnZDcvaW5wdXRpbWFnZSIsIlVVSUQiOiJjMzhjMzgzNC02NWQ5LTQzNzgtOWI4NS1kMGM2ZDg0MWFiYjMiLCJPZmZzZXQiOjE3NTE1NSwiU3RhcnRlZEF0IjoiMjAxOC0xMC0yOFQwMjozOTowOVoifQ%3D%3D&digest=sha256%3Aa38d357764a3aa20c2241433436db6cc24ea898a7f3c0904d66ca2323f302123: blob upload invalid
```

from the registry side, the error is:

```
time="2018-10-28T02:39:20.748537421Z" level=error msg="upload resumed at wrong offest: 0 != 175155" go.version=go1.10.3 http.request.contenttype=application/octet-stream http.request.host="docker-registry.default.svc:5000" http.request.id=41427703-4ca2-4743-8a88-681d8dd2d397 http.request.method=PUT http.request.remoteaddr="172.16.2.15:51296" http.request.uri="/v2/e2e-test-build-image-source-r8gd7/inputimage/blobs/uploads/c38c3834-65d9-4378-9b85-d0c6d841abb3?_state=x36zMpkRWAUwQMA45gqwbIwb4oOSQmGRqi8shuHLjM17Ik5hbWUiOiJlMmUtdGVzdC1idWlsZC1pbWFnZS1zb3VyY2UtcjhnZDcvaW5wdXRpbWFnZSIsIlVVSUQiOiJjMzhjMzgzNC02NWQ5LTQzNzgtOWI4NS1kMGM2ZDg0MWFiYjMiLCJPZmZzZXQiOjE3NTE1NSwiU3RhcnRlZEF0IjoiMjAxOC0xMC0yOFQwMjozOTowOVoifQ%3D%3D&digest=sha256%3Aa38d357764a3aa20c2241433436db6cc24ea898a7f3c0904d66ca2323f302123" http.request.useragent=Go-http-client/1.1 openshift.auth.user="system:serviceaccount:e2e-test-build-image-source-r8gd7:builder" openshift.auth.userid=45f9ed87-da5a-11e8-9657-42010a8e0004 vars.name=e2e-test-build-image-source-r8gd7/inputimage vars.uuid=c38c3834-65d9-4378-9b85-d0c6d841abb3
```

You can see the full log (both the build output and registry log) here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/21372/pull-ci-openshift-origin-master-e2e-gcp-builds/5/build-log.txt

/cc @dmage @legionus as it would be useful for you to take a look at the request flow in the registry log but i don't think this is a registry issue as we've only started seeing this failure since moving to buildah to push the images.

**Comment by dmage** [comment]
@bparees though, it looks like a storage problem on the registry side. The client has successfully uploaded 175155 bytes (using `PATCH /v2/e2e-test-build-image-source-r8gd7/inputimage/blobs/uploads/c38c3834-65d9-4378-9b85-d0c6d841abb3`). But the subsequent PUT request doesn't know anything about these bytes.

**Comment by bparees** [comment]
I couldn't tell from the log whether the registry was expecting the put to start at 175155 but the client set the offset to zero, or vice versa.

(obviously both should be expecting 175155, but it wasn't clear to me which one was using 0 instead).

**Comment by rhatdan** [comment]
@bparees Are you still seeing this issue?

**Comment by bparees** [comment]
I don't think so.  though i'm also unaware what might have fixed it.

**Comment by rhatdan** [comment]
Well reopen if it happens again.

**Comment by zhujian7** [comment]
The same issue for me, occasionally instead of always happened.

It is worth mentioning that I used an HAProxy before 3 registries, and when I upload an image, some blobs are processed by registry A, and some other blobs are processed by registry B.

**Comment by vrothberg** [comment]
> It is worth mentioning that I used an HAProxy before 3 registries, and when I upload an image, some blobs are processed by registry A, and some other blobs are processed by registry B.

This sounds fishy. @mtrmac, do you have an idea what could lead to wrong offsets?

**Comment by mtrmac** [comment]
The request at “registry A”, with `http.request.id=fdd0f08e-f49e-4aab-bfec-e54ab794916e` , has
```
http.request.useragent="docker/18.03.1-ce go/go1.9.5 git-commit/9ee9f40 kernel/3.10.0-1062.4.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.03.1-ce \\(linux\\))"
```
Same for “registry B”, with `df1ee77c-0c88-4f45-85a6-74c73d03b24c`, and “registry C”. 

None of the logs contain a single mention of the expected “Buildah/…” user agent, so I can’t see how this is supposed to be Buildah-related.

It might well be some server-side bug exposed both by Buildah (per the original report) and by Docker CE, but I don’t think we have diagnosed it at that time.

**Comment by paulliss** [comment]
It might be related to
[https://github.com/distribution/distribution/issues/3420](url)
