### ISSUE TITLE
Build tag 'ostree-1' missing even when library available

### ISSUE THREAD

**Issue by Silvanoc** [containers/buildah#1136]
**Description**

Build tag **ostree-1** required to include `vendor/github.com/containers/storage/pkg/ostree/ostree.go` is missing.

**Steps to reproduce the issue:**
1. Prepare a build environment where the OStree library is available (e.g. `libostree-dev` in Debian, `ostree` in Arch Linux, ...).
2. Build `buildah` from source code.
3. Setup an OStree repository (value `ostree_repo`) in `/etc/containers/storage.conf`.
4. Call `# buildah from ...` to see it failing with the error message `overlay: ostree_repo specified but support for ostree is missing` coming from [containers/storage](https://github.com/containers/storage/blob/09abf3a26b8a3aa69e29fd7faeb260b98d675759/drivers/overlay/overlay.go#L265).

The script [ostree_tag.sh](https://github.com/containers/buildah/blob/60485e6d778d9adf77d978e3c23e7685483addee/ostree_tag.sh) is adding the build tag `containers_image_ostree_stub` if OStree is missing, not adding any other tag otherwise.

But `containers/storage` expects the tag `ostree-1` to [include `pkg/ostree/ostree.go` in the build](https://github.com/containers/storage/blob/09abf3a26b8a3aa69e29fd7faeb260b98d675759/pkg/ostree/ostree.go#L1), adding [`pkg/ostree/no_ostree.go` otherwise in the build](https://github.com/containers/storage/blob/09abf3a26b8a3aa69e29fd7faeb260b98d675759/pkg/ostree/no_ostree.go#L1).

I'm not providing the following information, because I don't have right now access to the system where I faced the issue, but I've analyzed it above at code-level and a PR will follow right after entering this issue.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
Looks like this is fixed in upstream.
