### ISSUE TITLE
Slow speed pushing to private registry, even slower inside (privileged) container

### ISSUE THREAD

**Issue by 42wim** [containers/buildah#1140]
**Description**

`buildah push` to a private registry is upto 2x slower then `docker push`
`buildah push` inside a privileged docker container (using overlay) to a private registry is upto 4x slower then `docker push`

**Steps to reproduce the issue:**
1. Create a big image using docker or buildah, push to private registry
2. Remove image locally from docker/buildah
3. Time Docker pull image from private registry
4. Time Buildah pull image from private registry
5. Remove image from private registry
6. Time docker push image to private registry
7. Remove image from private registry
8. Time buildah push image to private registry
9. Run privileged docker container
10. Time Buildah pull image from private registry
11. Remove image from private registry
12. Time Buildah push image to private registry

**Describe the results you received:**

Native:
* docker pull: 35s
* buildah pull: 49s
* docker push: 1m5s
* buildah push: 2m18s

Inside container (using overlay):
* buildah pull: 1m14
* buildah push: 4m27

**Describe the results you expected:**

Same or better speed

**Output of `rpm -q buildah` or `apt list buildah`:**

``` 
buildah-1.4-1.gite9d18fc.el7.x86_64 
```

**Output of `buildah version`:**

```
Version:         1.5-dev
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      e9d18fc
Built:           Thu Oct 18 23:23:16 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.5.1804 (Core) (same inside container)
```

**Output of `uname -a`:**

```
Linux kstest-1 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
[storage.options.thinpool]
```

**Comment by TomSweeneyRedHat** [comment]
@42wim TYVM for the issue report.  We'll take a look at it.

**Comment by rhatdan** [comment]
@mtrmac Is looking into fixes for this in containers/image.

**Comment by 42wim** [comment]
I've did some more tests and what I thought were identical servers are behaving differently.
At some servers I get almost the same speed as with docker. (inside/outside the container)
(all those servers are actually vmware machines which should be identical)

I'll have to check with our datacenter people tomorrow to see where the difference lies.

So this looks like an issue on my side, sorry for wasting your time.

**Comment by 42wim** [comment]
Got confirmation, the issue was overloaded ESX machines, sorry again for the noise.

**Comment by TomSweeneyRedHat** [comment]
Glad to hear you located the issue @42wim and TYVM for the follow up.  As @rhatdan noted, @mtrmac is looking into performance improvements, so we're hopeful the build process will get even faster in the future.
