### ISSUE TITLE
Cannot modify `resolv.conf` inside of the container

### ISSUE THREAD

**Issue by mathstuf** [containers/buildah#1142]
I'd like to be able to modify the `/etc/resolv.conf` file inside of the container (namely, to be a symlink to `/run/systemd/resolve/resolv.conf`), but `buildah run` bind mounts over this path and it cannot be modified this way. Something like `--net none` should prevent bind-mounting over `/etc/hosts` and `/etc/resolv.conf`

**Comment by rhatdan** [comment]
Works in buildah 1.5
