### ISSUE TITLE
Image build fails with SIGSEGV on insufficient disk space

### ISSUE THREAD

**Issue by jmencak** [containers/buildah#1161]
**Image build fails with SIGSEGV on insufficient disk space**

**Steps to reproduce the issue:**
I cannot reproduce it now after I've cleaned up the space (and filled it again), but it was on a partition 98% full.

**Describe the results you received:**

    buildah bud  -t jmencak/cluster-node-tuning-operator -f Dockerfile .
    STEP 1: FROM openshift/origin-release:golang-1.10
    STEP 2: COPY . /go/src/github.com/openshift/cluster-node-tuning-operator/
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xa69192]
    
    goroutine 1 [running]:
    github.com/projectatomic/buildah.(*Builder).Add(0x0, 0xc42048cb00, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4210a86a0, 0x1, ...)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/_build/src/github.com/projectatomic/buildah/add.go:87 +0x52
    github.com/projectatomic/buildah/imagebuildah.(*Executor).Copy(0xc4201c6000, 0x0, 0x0, 0x0, 0xc4207333b0, 0x1, 0x1, 0x0, 0xc4203fe2d0)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/_build/src/github.com/projectatomic/buildah/imagebuildah/build.go:446 +0x720
    github.com/openshift/imagebuilder.(*Builder).Run(0xc4200c18c0, 0xc42013e000, 0x12a3860, 0xc4201c6000, 0x0, 0x0, 0x0)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/src/github.com/openshift/imagebuilder/builder.go:284 +0x357
    github.com/projectatomic/buildah/imagebuildah.(*Executor).Execute(0xc4201c6000, 0x12a35a0, 0xc42001a318, 0xc4200c18c0, 0xc4201ec310, 0xc42048c345, 0x24)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/_build/src/github.com/projectatomic/buildah/imagebuildah/build.go:754 +0xd6f
    github.com/projectatomic/buildah/imagebuildah.(*Executor).Build(0xc4200c1340, 0x12a35a0, 0xc42001a318, 0xc42045e1e0, 0x2, 0x2, 0x0, 0x0)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/_build/src/github.com/projectatomic/buildah/imagebuildah/build.go:1141 +0x25b
    github.com/projectatomic/buildah/imagebuildah.BuildDockerfiles(0x12a35a0, 0xc42001a318, 0x12aea40, 0xc4204d4900, 0xc420024140, 0x49, 0x0, 0x0, 0x0, 0x0, ...)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/_build/src/github.com/projectatomic/buildah/imagebuildah/build.go:1256 +0x10e5
    main.budCmd(0xc4200be2c0, 0x0, 0x0)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/cmd/buildah/bud.go:239 +0x169d
    github.com/urfave/cli.HandleAction(0xb98ee0, 0xcd6440, 0xc4200be2c0, 0x0, 0xc4204ecc00)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/src/github.com/urfave/cli/app.go:501 +0xd2
    github.com/urfave/cli.Command.Run(0xca533c, 0x16, 0x0, 0x0, 0x127c230, 0x1, 0x1, 0xcbf810, 0x31, 0x0, ...)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/src/github.com/urfave/cli/command.go:165 +0x4bb
    github.com/urfave/cli.(*App).Run(0xc4203861c0, 0xc4200100d0, 0xd, 0xd, 0x0, 0x0)
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/src/github.com/urfave/cli/app.go:259 +0x740
    main.main()
            /builddir/build/BUILD/buildah-4888163cf12b4e0c0d32ef7eb0ed941c2c81d4f7/cmd/buildah/main.go:120 +0xe49
    ERRO[0001] exit status 2                                
    make: *** [Makefile:53: local-image] Error 2

**Describe the results you expected:**

Information about insufficient disk space to complete the operation.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.3-1.git4888163.fc27.x86_64
```

**Output of `buildah version`:**

```
buildah version 1.3 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
Fedora release 27 (Twenty Seven)
```

**Output of `uname -a`:**

```
Linux x1.lan 4.18.16-100.fc27.x86_64 #1 SMP Sun Oct 21 09:33:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
@ypu Could you setup a test for this on buildah 1.5 to see if it still happens.  I would guest just create a small partition on /var/lib/containers and then run the Dockerfile.

**Comment by rhatdan** [comment]
I believe this is fixed in the current release,  Reopen if I am mistaken.
