### ISSUE TITLE
Create `buildah info` command, ensure rootless status is noted within

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1168]
If possible, update `buildah info` to show if it is or is not a rootless container.  Similar to what @vrothberg did here:  https://github.com/containers/libpod/pull/1793

**Comment by giuseppe** [comment]
where should this information go?  AFAICS we don't have a `buildah info`

**Comment by TomSweeneyRedHat** [comment]
Got so use to podman info, I'd forgotten we don't have one for Buildah.  That would be the right landing spot for that.  @rhatdan @nalind any objections to creating and info command?

**Comment by rhatdan** [comment]
Nope lets add one.

**Comment by rhatdan** [comment]
Fixed in current release.
