### ISSUE TITLE
r

### ISSUE THREAD

**Issue by caiodearaujo** [containers/buildah#1191]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
I take it that this is a mistake.  Closing, reopen if you have a real issue.
