### ISSUE TITLE
Unable to use buildah on travis CI

### ISSUE THREAD

**Issue by Jiri-Kremser** [containers/buildah#1194]
I would like to check if my dockerfiles are buildable with `buildah bud ..`, but it's really pain to make the buildah working on Travis CI. They use ubuntu based docker images so what I am doing is adding those custom repos and installing packages like `libostree(-dev)` to make it working, but no luck. I got message that the package is not there. So either your https://github.com/containers/buildah/blob/master/install.md#ubuntu is broken or I am missing something important.

makefile entry:
https://github.com/radanalyticsio/spark-operator/pull/150/files#diff-b67911656ef5d18c4ae36cb6741b7965R26

build fails with:
https://travis-ci.org/radanalyticsio/spark-operator/jobs/458034589#L476

Btw. have you considered adding those binaries with buildah as part of the GH [releases](https://github.com/containers/buildah/releases)? I know it's not super secure as RPMs, but it would be much easier to work with... Similarly what oc does [here](https://github.com/openshift/origin/releases).

**Comment by rhatdan** [comment]
@Jiri-Kremser If you don't have libpostree-dev installed then make should build buildah without support for ostree, which should be fine.

**Comment by estroz** [comment]
I'm seeing a [similar issue]https://travis-ci.org/operator-framework/operator-sdk/jobs/460529459#L866 with `seccomp`, even after explicitly installing it. This issue didn't arise a few weeks ago.

**Comment by rhatdan** [comment]
Closing as this issue has gone stale, reopen if you still have the issue.
