### ISSUE TITLE
travis CI cannot build with seccomp

### ISSUE THREAD

**Issue by estroz** [containers/buildah#1203]
**Description** the installation script expects `seccomp` to be a Go package but cannot find it under the expected paths in travis CI, even after explicitly installing `seccomp` via `apt`.

**Steps to reproduce the issue:**
1. `git clone https://github.com/containers/buildah ${GOPATH}/src/github.com/containers/buildah`
1. `cd ${GOPATH}/src/github.com/containers/buildah`
1. `make runc all TAGS="apparmor seccomp"`
1. `sudo make install install.runc`

**Describe the results you received:** see [this error](https://travis-ci.org/operator-framework/operator-sdk/jobs/460529459#L866).

**Describe the results you expected:** no installation errors (a few weeks ago these same steps worked as expected).

**Output of `buildah version`:**

```
master (2c632d1a2de0192c3f18a2542ccb6f30a8719b1f)
```

**Comment by estroz** [comment]
This problem exists locally on my machine. The issue is variable expansion in the [Makefile](https://github.com/containers/buildah/commit/3a5f084652e628d69b1d033cd959da02c144de2c#diff-b67911656ef5d18c4ae36cb6741b7965R8). I'll make a PR.

**Comment by TomSweeneyRedHat** [comment]
Thanks @estroz !

**Comment by rhatdan** [comment]
PR Merged closing the isue.
