### ISSUE TITLE
Should CommitOptions.Compression exist?

### ISSUE THREAD

**Issue by mtrmac** [containers/buildah#1215]
`CommitOptions.Compression` is used, via `makeImageRef`, in `containerImageRef.NewImageSource`, when deciding whether to compress or not the temporary file which contains the newly added, or the squashed, layer (and to use the compressed layer digest in the created manifest).

The created layer is then copied in `Builder.Commit` to the destination of the commit: AFAICS, in almost all cases, this is c/storage:

- `cmd/buildah/commit.go` could use any destination if the user uses the _transport_`:`… syntax, but falls back to `ResolveName`+`ParseStoreReference` (which is likely to be the common case); meanwhile, it defaults to `archive.Gzip` unless the user explicitly opts out.
- `imagebuildah/Executor.Commit`’s destination is _always_ a `ParseStoreReference`; the only in-tree user, `cmd/buildah/bud.go`, hard-codes `archive.Gzip`

c/storage, when used as a destination, always uncompresses the layer; so, AFAICS, compressing the layer is just undone.

Meanwhile, `copy.Image` already has destination-specific logic to decide whether to compress data on push or not, so a `buildah commit docker://…` would have the layer compressed by `copy.Image` whether or not `containerImageRef` creates a compressed layer.

So, the compression at time of `NewImageSource` seems at best redundant, at worst a fairly costly waste.

Am I missing some other why the compression exists?

The only other use I could find is `containerImageRef.computeLayerMIMEType`, which
- seems like something `copy.Image` should handle automatically
- can, strictly speaking, continue to exist whether or not `NewImageSource` actually creates a compressed blob or not.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind @mtrmac Is this still and issue?

**Comment by mtrmac** [comment]
The option continues to exist; do you have any other reason to think the situation changed?

**Comment by rhatdan** [comment]
@mtrmac I am going through hundreds of issues, and ones that have not changed for several months, I want to verify if they are still a problem and try to get people to start working on them. Otherwise they are either not important, or forgotten.

**Comment by rhatdan** [comment]
@ashley-cui Could you open a PR to remove the Compression flag.

**Comment by rhatdan** [comment]
Looks to me like we always disablecompression by default in master.  Reopen if I am mistaken.

**Comment by mtrmac** [comment]
https://github.com/containers/buildah/blob/cd72e45f3f13e283a6be427d3ea198a52284145d/cmd/buildah/commit.go#L120 is still the default.

**Comment by nalind** [comment]
#1336 also set `--disable-compression` to `true` by default.  Is it getting overridden or turned off later?

**Comment by mtrmac** [comment]
@nalind Thanks, I missed that. Anyway, I think it’s up to you whether this should be kept open.

**Comment by rhatdan** [comment]
Right, the very next line turns it off by default
	if iopts.disableCompression {
		compress = imagebuildah.Uncompressed
	}
And iopts.disableCompression is true by default for buildah bud and buildah commit, which is why I disabled this.
$ podman build --help | grep disable-compression
  -D, --disable-compression                        don't compress layers by default (default true)
