### ISSUE TITLE
containerImageRef.NewImageSource potentially unnecessarily writes all layers to disk

### ISSUE THREAD

**Issue by mtrmac** [containers/buildah#1216]
If `containerImageSource.exporting`, `containerImageRef.NewImageSource` creates on-disk copies of all layers in `i.path`; `GetBlob` then only returns a handle to that on-disk copy.

This is potentially quite wasteful if the layers already exist on the destination, and this can be determined from their uncompressed digests already (and even more wasteful if `compress` is set, see #1215). Couldn’t the reading of layers be moved into `GetBlob` directly, apart from the new layer with unknown digest I guess?

The `.exporting` case happens only if `Builder.Commit` was called with a non-c/storage destination, which I guess is pretty rare (?), so this is fairly low-priority.

**Comment by rhatdan** [comment]
@mtrmac @TomSweeneyRedHat @nalind Is this still an issue?

**Comment by mtrmac** [comment]
Clearly so: https://github.com/containers/buildah/blob/4693117a8d9a36cd24ffc6ecb80b65b7b495a611/image.go#L319

**Comment by rhatdan** [comment]
Well can we move forward on this?

**Comment by TomSweeneyRedHat** [comment]
@nalind, was this helped any with your latest layers fixes/changes?

**Comment by rhatdan** [comment]
@nalind Have you had a chance to look at this?

**Comment by rhatdan** [comment]
@nalind @vrothberg @mtrmac A few year old issue, Do you think we should still work on this?

**Comment by mtrmac** [comment]
From a quick look it still seems to be an issue. As for how important it is, no idea.

**Comment by rhatdan** [comment]
Still an issue, although I do not see anyone ever getting this high on the priority list.

**Comment by rhatdan** [comment]
@nalind What should we do with this, it is our oldest issue?
