### ISSUE TITLE
rootless buildah and rootless podman don't share image store

### ISSUE THREAD

**Issue by TomasTomecek** [containers/buildah#1224]
**Description**

I suspect that buildah doesn't respect `~/.config/containers/storage.conf` or there is something wrong with my system:

```
$ buildah version
Version:         1.5
Go Version:      go1.11.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64

$ podman images
REPOSITORY                          TAG        IMAGE ID       CREATED        SIZE
docker.io/library/python            3-alpine   aadc3feb2b19   2 weeks ago    82MB
registry.fedoraproject.org/fedora   29         a5cc8ccd230a   7 weeks ago    306MB
registry.fedoraproject.org/fedora   latest     ded494ce3076   2 months ago   264MB
registry.fedoraproject.org/fedora   28         ded494ce3076   2 months ago   264MB

$ buildah images
IMAGE NAME                                               IMAGE TAG            IMAGE ID             CREATED AT             SIZE
registry.fedoraproject.org/fedora                        29                   a5cc8ccd230a         Oct 15, 2018 13:04     306 MB
<none>                                                   <none>               582c5196af9e         Dec 6, 2018 16:18      306 MB
localhost/sourcegit-failed                               latest               53e77c3e94f8         Dec 6, 2018 16:19      306 MB

$ cat ~/.config/containers/storage.conf
RunRoot = "/run/user/1000"
GraphRoot = "/home/tt/.local/share/containers/storage"
GraphDriverName = "overlay"
GraphDriverOptions = ["overlay.mount_program=/usr/bin/fuse-overlayfs"]
```

As you can see, the sets of images for both tools are different. What am I doing wrong?

Edit: I recall this worked just fine with buildah 1.4 but once I updated to 1.5, they both seem to be using a rootless store on their own.

**Comment by rhatdan** [comment]
I would think that could be an issue.

What does buildah info show?
Podman info?

**Comment by giuseppe** [comment]
the `storage.conf` generated by podman is wrong.  This was fixed upstream and going to be included in the next release.

Could you manually fix it to look like:

```toml
[storage]
driver = "overlay"
runroot = "/run/user/1000"
graphroot = "/home/tt/.local/share/containers/storage"
[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by TomasTomecek** [comment]
oh nice, that works, thanks @giuseppe!

didn't realize the config has wrong syntax

**Comment by Logibox** [comment]
Hi, @giuseppe could you link the upstream issue/pr please?

**Comment by giuseppe** [comment]
@Logibox this is the original issue: https://github.com/containers/buildah/issues/1113

Previously Buildah wasn't honoring that configuration file

**Comment by Logibox** [comment]
Ah ok, does that PR just cover the conf file location? Because I'm still getting the an inconsistency in file format between the defaults of buildah and podman.

Default config file generated by buildah:
```
[matthewyates@home-workstation Workspace]$ rm ~/.config/containers/storage.conf
[matthewyates@home-workstation Workspace]$ buildah --help
NAME:
   buildah - an image builder

USAGE:
... <omitted> ...
matthewyates@home-workstation Workspace]$ cat ~/.config/containers/storage.conf
RunRoot = "/run/user/1000"
GraphRoot = "/home/matthewyates/.local/share/containers/storage"
GraphDriverName = "overlay"
GraphDriverOptions = ["overlay.mount_program=/usr/bin/fuse-overlayfs"]
```

Default config file generated by podman
```
[matthewyates@home-workstation Workspace]$ rm ~/.config/containers/storage.conf

[matthewyates@home-workstation Workspace]$ podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-1.git9551f6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 67ab7549b44484cc3f201d7bb2b58b922f8edc24'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 1623277568
... <omitted> ...
[matthewyates@home-workstation Workspace]$ cat ~/.config/containers/storage.conf
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/matthewyates/.local/share/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

```
[matthewyates@home-workstation Workspace]$ podman --version
podman version 0.12.1.2
[matthewyates@home-workstation Workspace]$ buildah --version
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)
```
These are both the latest packaged version in fedora 29

**Comment by giuseppe** [comment]
@Logibox, PR here: https://github.com/containers/buildah/pull/1246

**Comment by juhp** [comment]
Is this supposed to be fixed now with buildah-1.6-2.git5f95bd9.fc29.x86_64 (currently still updates-testing)?
Or can someone tell me what I need to do to get buildah and podman to agree on `images`?

**Comment by aplatypus** [comment]
Today is 2020-10 ... 14 months since the last comment and I'm fairly sure `podman` and `buildah` are as recent as available from the `kubic` repository and PPA (using Ubuntu 20.04).

```
 $ buildah --version ; echo "  --  --  --" ; podman --version
buildah version 1.16.4 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
  --  --  --
podman version 2.1.1
```

Tree times now after following a very simple tutorial `podman` does NOT find the local (rootless) image listing -- As follows:
```
 $ podman images ; echo "--------" ; buildah images
REPOSITORY  TAG     IMAGE ID  CREATED  SIZE
--------
REPOSITORY                      TAG      IMAGE ID       CREATED          SIZE
localhost/buildah-hello-world   latest   95f98ba5fdc5   31 minutes ago   66.6 MB
localhost/express-hello-world   latest   08b9100b9f90   4 weeks ago      66.4 MB
docker.io/library/alpine        latest   a24bb4013296   4 months ago     5.85 MB
```
I am expecting that they both use the `$HOME/.config/containers/`  configuration set.  

I am left wondering why this issue is closed since clearly it has not been resolved in the current installs.  Looking at the above "manual solution"  hasn't helped me much.  At the very LEAST, it would be good when the `man` page has a URL to explain, clearly  how thing need to be configured for `rootless` mode to ensure that both `podman` and `buildah` share the same (rootless) local image store.  If that's what is needed . . .

**Comment by giuseppe** [comment]
can you share the configuration files you have under `~/.config/containers` ?  The default configuration (without any config file present) is to share the same image store

**Comment by aplatypus** [comment]
Thanks @giuseppe ...

These are essentially just comments with some other notes I found along the way.  only these two files are present:

  * containers.conf
  * storage.conf

I'm wanting to be using rootless mode.  As there are no entries in the config files put on my system, I presumed that `buildah` is using a known default.  Is it possible to interrogate `buildah` to find where it keeps local images?

The trick (from my perspective) is to understand where/what settings control these basics?  It seems that empty settings don't have compatible or convergent default values.

Is there a concise tutorial or cheat sheet that will get things started?  I'm happy to get in-deep later once I can move from a working config to the next working config, etc., etc.

Cheers :-)
       

**containers.conf**
```
########
#
#   $HOME/.config/containers/containers.conf
#     * 2020-08-31
#
#   The containers configuration file specifies all of the available configuration
#   command-line options/flags for container engine tools like Podman & Buildah,
#   but in a TOML format that can be easily modified and versioned.
#
#   Please refer to containers.conf(5) for details of all configuration options.
#   Not all container engines implement all of the options.
#   All of the options have hard coded defaults and these options will override
#   the built in defaults. Users can then override these options via the command
#   line. Container engines will read containers.conf files in up to three
#   locations in the following order:
#
#    1. /usr/share/containers/containers.conf
#    2. /etc/containers/containers.conf
#    3. $HOME/.config/containers/containers.conf (Rootless containers ONLY)
#
#    Items specified in the latter containers.conf, if they exist, override the
#   previous containers.conf settings, or the default settings.
#
##  ref:
#     * [Setup and Use of Podman in a Rootless environment](https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md)
#
########

```

**storage.conf**
```
########
#
#   $HOME/.config/containers/storage.conf
#     * 2020-08-31
#
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
#
##  ref:
#     * [Setup and Use of Podman in a Rootless environment](https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md)
#     * [How to build a container image from scratch as a non-root user?](https://stackoverflow.com/a/54753516/108350)
#
########


##  Rootless mode:
#
#   graphroot="$HOME/.local/share/containers/storage"
#   runroot="$XDG_RUNTIME_DIR/containers"
#
#   $XDG_RUNTIME_DIR defaults on most systems to /run/user/$UID.

####[ end ]###
```

**Comment by hexmode** [comment]
FINALLY... I was trying to understand why buildah was creating images that podman couldn't see.  It wasn't till I came across this bug that I found the answer.

* non-working version of buildah package in debian: 1.11.6-1
* working version: 1.19.3+dfsg1-2
