### ISSUE TITLE
buildah from docker-daemon:debian:latest doesn't work as expected

### ISSUE THREAD

**Issue by xinminglai** [containers/buildah#1236]
**Description**

buildah from docker-daemon:debian:latest doesn't work as expected as buildah pull

**Steps to reproduce the issue:**
1.  run `docker pull debian:latest`
2.  buildah from docker-daemon:debian:latest

**Describe the results you received:**

error will be: error parsing reference to image "docker-daemon:debian:latest": error parsing image name "docker-daemon:debian:latest": invalid reference format

**Describe the results you expected:**

buildah from command should support the same feature as buildah pull

**Output of `rpm -q buildah` or `apt list buildah`:**

**Output of `buildah version`:**

```
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
Gentoo Base System release 2.6
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

```

**Output of `uname -a`:**

```
Linux air 4.19.2-gentoo #1 SMP Fri Nov 16 08:07:59 -00 2018 x86_64 AMD Ryzen 7 2700 Eight-Core Processor AuthenticAMD GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[registries.search]
# registries = ['']
```

**Comment by TomSweeneyRedHat** [comment]
A bit of background info from our IRC chat with @xinminglai .  This command worked with Buildah v1.2. 
Test scenarios: 
```
 buildah from docker-daemon:debian:latest   # fails
 buildah pull docker-daemon:debian:latest     # succeeds
 buildah from docker.io/debian:latest              # succeeds after the prior pull
```

**Comment by rhatdan** [comment]
I believe this works now, so closing.  Reopen if you do not agree.
