### ISSUE TITLE
Recommended way to push image to insecure registry using buildah

### ISSUE THREAD

**Issue by dharmit** [containers/buildah#1247]
**Description**

What's the recommended way to push an image to a remote insecure registry (`docker-distribution`)? I used `--tls-verify=false` with `buildah push` command and it worked. Is that the recommended way or should I add the info to some configuration file the way it's done for Docker?

I'm using `buildah` from git repo:
```bash
$ buildah version
Version:         1.6-dev
Go Version:      go1.10.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      4674656
Built:           Thu Dec 20 10:26:50 2018
OS/Arch:         linux/amd64
```

**Comment by rhatdan** [comment]
I think so, and you can also mark the registry as insecure in /etc/containers/registries.conf

@TomSweeneyRedHat Any thing else to add?

**Comment by dharmit** [comment]
Thank you, Dan & Tom.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Idea for a quick blog...

**Comment by TomSweeneyRedHat** [comment]
@rhatdan yep, I've had a working with registries with podman/buildah blog thought for a bit now, need to git to it.
