### ISSUE TITLE
About buildah pull --all

### ISSUE THREAD

**Issue by zhouhao3** [containers/buildah#1248]
Is it necessary to add the `--all` option to the `pull` command to download the image of all tags？
I find `podman` does not have that either.

**Comment by rhatdan** [comment]
Did not know that exists, so yes we should add this flag.
@TomSweeneyRedHat Could you look into adding this flag to buildah and podman.

**Comment by rhatdan** [comment]
@QiWang19 might be something you could look at if @TomSweeneyRedHat Does not have time.
