### ISSUE TITLE
ENV variable expansion is different in Dockerfile based builds and in buildah config --env

### ISSUE THREAD

**Issue by janosi** [containers/buildah#1250]
**Description**
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Dockerfile based builds expand environment variables that are defined in the Dockerfile. In case of "buildah config" the environment variables are not expanded from the container image but used from the host.

**Steps to reproduce the issue:**
1. Dockerfile with 2 ENV commands. E.g. 
ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH
2. Run "buildah bud" on this Dockerfile
3. Run "buildah config --env GOPATH=/go --env=$GOPATH/bin:$PATH" in a different build process based on the same base image

**Describe the results you received:**
1. In the Dockerfile based build the environment variables are expanded ("interpolated" in Docker terminology) and the "buildah inspect" shows the following:
```
"Env": [
                "GOPATH=/go",
                "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
```
That is, the GOPATH from the Dockerfile ENV is expanded into the PATH definition, and PATH is used from the base image.

2. In the "buildah config --env" based build the environment variables are not expanded, and the host level ones are used. "buildah inspect" shows the following:
```
 "Env": [
                "GOPATH=/go",  
 "PATH=/home/janosi/go/bin:/usr/local/go/bin:/home/janosi/bin:/home/janosi/.local/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
            ],
```

**Describe the results you expected:**
I would expect a consistent handling of the env variables. Maybe the Dockerfile way is the right one?

**Output of `rpm -q buildah` or `apt list buildah`:**

```
apt list buildah
Listing... Done
buildah/xenial 1.6-1~dev~ubuntu16.04.2~ppa8 amd64
```

**Output of `buildah version`:**

```
 buildah -v
buildah version 1.6-dev (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `podman version` if reporting a `podman build` issue:**

**Output of `cat /etc/*release`:**

```
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Output of `uname -a`:**

```
 uname -a
Linux k8ssctp 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat /etc/containers/storage.conf
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by KenYN** [comment]
The expansion of `$GOPATH` etc is performed by the `bash` shell for Buildah, so it's not quite as simple a fix. I had a similar problem trying to duplicate:

    RUN echo Acquire::https::proxy "$https_proxy"; >> /etc/apt/apt.con

My solution (which won't work for your situation) was to do:

    echo "Acquire::https::proxy \"$https_proxy\";" >> $mountpoint/etc/apt/apt.conf

Maybe if you echo the commands to a file, then use `source <file>`?

**Comment by janosi** [comment]
Arrrggghh, my bad :( Of course it is the shell.... :( How blind I can be.
Now, if I pass the env variable definition wrapped with single quotes it works fine.
Thank you @KenYN for the hint! I close this issue.
