### ISSUE TITLE
Make .CreatedAt and other timestamps time.Time types

### ISSUE THREAD

**Issue by KenYN** [containers/buildah#1266]
I recently posted [this question](https://stackoverflow.com/questions/54071278/formatting-a-go-date-in-a-bash-friendly-manner) to StackOverflow about formatting timestamp output from:

    buildah images --format '{{.CreatedAt}}' my_image

But I was informed that `.CreatedAt` is a `string`, so I was out of luck. The string is also not localised and is missing timezone information, so even as it is it is not terribly useful. The recommendation given was to request an extra `CreatedAtTime time.Time` field that would allow users to format however they needed. (Specifically, I want to add a check to my `buildah` scripts to skip processing if the script is older than the image)

This is my contribution to the call for discussion in https://github.com/containers/buildah/issues/537#issuecomment-382353350.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @rhatdan PTAL

It may also affect Podman (Cc @baude @mheon)

**Comment by rhatdan** [comment]
This is a good idea.

**Comment by TomSweeneyRedHat** [comment]
@KenYN I'm hesitant to change the format of the timestamp as it is now.  But I'd be OK with adding a new field for them, basically appending "Raw" to is, so you can do:
```
# buildah images --format '{{.ID}} {{.CreatedAtRaw}}'
3f53bb00af943dfdf815650be70c0fa7b426e56a66f5e3362b47a129d57d5991 2018-12-20 19:21:30.122610396 -0500 EST
8e09da8f6701d7cde1526d79e3123b0f1109b78d925dfe9f9bac6d59d702a390 2019-01-08 09:22:52.330623532 -0500 EST
```
I'm going to assume this would be useful and will get a PR together for the image side of things anyway and we can then move on to containers and Podman.

**Comment by TomSweeneyRedHat** [comment]
@KenYN We've created the CreatedAtRaw field for images with #1269 and I think the other dates we're displaying are fine.  If you think we need further work here, please re-open and let us know which field(s) is problematic for you.
