### ISSUE TITLE
Accessing NVidia driver runtime inside container

### ISSUE THREAD

**Issue by KenYN** [containers/buildah#1280]
Cannot use driver built into the NVidia driver images as [described here](https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-\(Beta\)).

As a more general question, is there a Buildah equivalent of 
`docker run --runtime=nvidia`? Currently I workaround by pushing my containers to Docker and running them there.

**Steps to reproduce the issue:**
1. `cont=$(buildah from nvidia/driver:396.37-ubuntu16.04)`
2. `buildah run $cont nvidia-smi`

**Describe the results you received:**

> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

**Describe the results you expected:**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
...etc...

```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/xenial,now 1.6-1~dev~ubuntu16.04.2~ppa8 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.5-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      18309de
Built:           Mon Nov 19 18:31:08 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Output of `uname -a`:**

```
Linux machine-name-A 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
This seems like a use case for podman not buildah?  Buildah is only for building container images, podman is for running container images, works just like the Docker CLI.

**Comment by KenYN** [comment]
I see - I just checked podman and I see reports like https://github.com/containers/libpod/issues/884 and Google gives me lots of other useful information for "podman nvidia". I'll explore these and if I have any issues I'll report to podman.
