### ISSUE TITLE
buildah inside of a podman container runs in rootless mode

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#1296]
It is running as root but still puts its content in /root/.local ...

It should be using /var/lib/containers/.

**Comment by rhatdan** [comment]
This is breaking some demos.

**Comment by giuseppe** [comment]
is the podman container using namespaces?

**Comment by TomSweeneyRedHat** [comment]
@giuseppe any further thoughts?

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/buildah/pull/1323
