### ISSUE TITLE
RFE - Report that configuration files are missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1307]
**Description**

I'm just making an issue so it doesn't get lost in the shuffle.  In #810 @rhatdan noted that we should at least throw a warning if the required [configuration files](https://github.com/containers/buildah/blob/master/install.md#configuration-files) such as registry.conf, storage.conf, policy.json, mount.conf, etc are not found when running a Buildah command.

This is probably a good one for someone getting their feet wet in Buildah to take on.

**Comment by rhatdan** [comment]
I agree. lets setup a library in buildah that checks this.
pkg/utils/
or something like that which validates all of the tools required for setup exists.

**Comment by rhatdan** [comment]
Why do we need this if the errors look pretty good and the tools actually work in some cases without the files.

Lets examine the errors.
# No registries.conf
```
 buildah from fedora
(image name "fedora" is a short name and no search registries are defined in /etc/containers/registries.conf): while pulling "fedora" as "localhost/fedora": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
```

# No Policy.json
```
buildah from fedora:f28
The following failures happened while trying to pull image specified by "fedora:f28" based on search registries in /etc/containers/registries.conf:
* "localhost/fedora:f28": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
* "docker.io/library/fedora:f28": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
* "registry.fedoraproject.org/fedora:f28": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
* "quay.io/fedora:f28": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
* "registry.access.redhat.com/fedora:f28": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
* "registry.centos.org/fedora:f28": error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
```

# No /etc/containers/storage.conf

```
# buildah from fedora:28
Getting image source signatures
Copying blob 012cb44e3253: 85.49 MiB / 85.49 MiB [=========================] 26s
Copying config 4c5b21baa7a0: 1.99 KiB / 1.99 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
fedora-working-container-1
```

**Comment by QiWang19** [comment]
I agree. I don't think this is necessary

**Comment by TomSweeneyRedHat** [comment]
I didn't double check before throwing up this RFE, just saw @rhatdan's request there to verify the file existence and didn't want to lose that thought before cleaning that issue up.  From what I see above, the verbiage could be better for registries.conf and policy.json.  I still think there's some value to at least printing out a warning if either of those files is not found with a message to that effect.

**Comment by rhatdan** [comment]
I think we have enough checks in the code now.
