### ISSUE TITLE
"runc": executable file not found

### ISSUE THREAD

**Issue by mstavares** [containers/buildah#1309]
Hi,

I have the same issue that is described here https://github.com/nkhare/k8s-cicd-webinars/issues/6

error:
error running container: error creating container for [/bin/sh -c mkdir -p /usr/src/app]: : exec: "runc": executable file not found in $PATH

This is running in a docker:
RUN sudo apt-get install golang-go -y

RUN mkdir ~/buildah
RUN cd ~/buildah
RUN export GOPATH=pwd
RUN git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah
RUN sudo cp -a /projects/src/github.com/projectatomic/buildah/vendor/github.com/opencontainers/runc /usr/bin/.
RUN sudo apt-get install buildah -y

Am I missing something?

Thanks,

**Comment by rhatdan** [comment]
You need to install runc and a few other packages in order to make this work, or just install the buildah package which should pull in the packaged software.  Look at https://github.com/containers/buildah/blob/master/install.md

**Comment by mstavares** [comment]
Hi @rhatdan 

Thanks a lot!
