### ISSUE TITLE
Ctrl+C doesn't stop image push

### ISSUE THREAD

**Issue by EmilienM** [containers/buildah#1328]
Demo of how to reproduce:
<a href="https://asciinema.org/a/lCodlrrnfV63YVyZxbTtQG8LW" target="_blank"><img src="https://asciinema.org/a/lCodlrrnfV63YVyZxbTtQG8LW.svg" /></a>

Basically try to push an image with buildah and Ctrl+C won't stop the build.

**Comment by rhatdan** [comment]
@vrothberg I think your change to the new progress bar fixed this issue. Could you confirm?
@EmilienM Please reopen if this is still an issue.
