### ISSUE TITLE
feature request: buildah manifest functionality

### ISSUE THREAD

**Issue by grooverdan** [containers/buildah#1347]
The docker experimental manifest commands to to create multiarch manifests are quite nice and it would be nice to do these without a docker daemon.

The create, push, annotate and inspect subcommands are sufficient.

ref: https://docs.docker.com/engine/reference/commandline/manifest/#usage

**Comment by rhatdan** [comment]
@mtrmac @vrothberg  WDYT
I think a similar request was made for podman or skopeo?

**Comment by mtrmac** [comment]
Yes, https://github.com/containers/libpod/issues/713 .

**Comment by mtrmac** [comment]
Also https://github.com/containers/image/pull/400 is a very good starting point.

**Comment by rhatdan** [comment]
@mtrmac Could you pick up with @nalind left off to finish the PR?

**Comment by konrad-ohms** [comment]
If you need a workaround for now, you could have a look into https://github.com/estesp/manifest-tool.
I am using buildah to push the images and use the manifest tool to produce multiarch manifests afterwards. That should work without requiring a Docker installation.

**Comment by grooverdan** [comment]
And even better,  https://github.com/estesp/manifest-tool being an Apache-2 licensed go implementation could be be used as code source and test reference.

**Comment by rhatdan** [comment]
@vrothberg Is this something you would want to look into?

**Comment by cpmoore** [comment]
Any updates on this issue?
It’s a feature our organization needs due to multiple architecture images. 
It’s even more important with OpenShift 4 moving away from docker.

**Comment by rhatdan** [comment]
Well we have it in Podman now.  Is that good enough, or do we need it in Podman?

**Comment by rhatdan** [comment]
Fixed in master.
