### ISSUE TITLE
Confirmation that buildah does (now, no longer) not require the same privileges as a Docker daemon does to run, to update Kaniko's README

### ISSUE THREAD

**Issue by vorburger** [containers/buildah#1349]
I'm wondering if this from https://github.com/GoogleContainerTools/kaniko#comparison-with-other-tools:

> buildah requires the same privileges as a Docker daemon does to run,
> (while kaniko runs without any special privileges or permissions.)

is still accurate? My understanding, based on reading e.g. #518, is that it's not (anymore).

If someone can confirm this, should I raise a PR to Kaniko to rectify this?

@rhatdan @TomSweeneyRedHat @vbatts

**Comment by vbatts** [comment]
On 19/02/19 15:45 -0800, Michael Vorburger ⛑️ wrote:
>I'm wondering if this from https://github.com/GoogleContainerTools/kaniko#comparison-with-other-tools:
>
>> buildah requires the same privileges as a Docker daemon does to run,
>> (while kaniko runs without any special privileges or permissions.)
>
>is still accurate? My understanding, based on reading e.g. #518, is that it's not (anymore).
>
>If someone can confirm this, should I raise a PR to Kaniko to rectify this?

I feel this is not correct. A `git blame` to see who added that, and
what the reasoning was, and then a PR to correct it would be great.

**Comment by vrothberg** [comment]
> is still accurate? My understanding, based on reading e.g. #518, is that it's not (anymore).

Buildah works rootless so the document isn't accurate anymore.

> I feel this is not correct. A `git blame` to see who added that, and what the reasoning was, and then a PR to correct it would be great.

It looks like it hasn't been updated. At the time of writing, the statement was true.

**Comment by vrothberg** [comment]
I opened https://github.com/GoogleContainerTools/kaniko/pull/573 to update the description.

**Comment by vorburger** [comment]
Would it be worthwhile to raise another PR to Kaniko to mention how Buildah's `build-using-dockerfile` (bud) can also build an image using instructions from Dockerfile/s, even if Buildah does not necessarily
require a Dockerfile?  

Only because the way it now reads (thanks @vrothberg), while we've clarified the non root user / privileges aspect, if I were to read the Kaniko README without any background, one could think: "kaniko ... Dockerfile .. Buildah .. doesn't seem  to support Dockerfile at all, so not for me, I'm not even going to have a look".

**Comment by rhatdan** [comment]
Yes we should fix the wording.

**Comment by vrothberg** [comment]
I'll give it another shot.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/buildah/pull/1362 over at Buildah. Please provide feedback. Once it's merged can we update the description over at Kaniko.

**Comment by rhatdan** [comment]
The Buildah description has merged.
