### ISSUE TITLE
buildah --platform to take os/arch format and set default ARGS {BUILD|TARGET}{PLATFORM|OS|ARCH|VARIANT}

### ISSUE THREAD

**Issue by grooverdan** [containers/buildah#1368]
When building on docker a number of default arguments can be used to create a cross build package explicit arguments without relying on on shell `RUN` commands to determine the native architecture.

Docker ref:  https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

These could also set the required docker v1/v2 schema without the use of `buildah config`.

**Comment by rhatdan** [comment]
@grooverdan I would be fine with adding support for these?  Are you interested in opening a PR for them?

**Comment by grooverdan** [comment]
Doesn't seem too bad. Got a few other work items to clear first. Warning - it will be the first golang code I've written.

**Comment by rhatdan** [comment]
No Problem.  You'll enjoy the experience.

**Comment by rhatdan** [comment]
@grooverdan Have you gotten back to this?

**Comment by grooverdan** [comment]
Started pottering and adding code fragments in the right place, haven't forgotten and its formally on my work plan of things to do.

**Comment by grooverdan** [comment]
Started pottering and adding code fragments in the right place, haven't forgotten and its formally on my work plan of things to do.

**Comment by rhatdan** [comment]
@grooverdan Are you still interested in this?  Should I have @ashley-cui Take a stab?

**Comment by grooverdan** [comment]
I'm mostly there:
https://github.com/grooverdan/buildah/tree/args-target-platform

Remaining implementation:
* Complete a working test case
* Ensure FROM directives pull from the os/arch
* Ensure output images is tagged with os/arch
* Some mounting of the qemu executable of /proc/sys/fs/binfmt_misc/qemu-${arch} while building(?)

**Comment by grooverdan** [comment]
#2241 :balloon:  continuing.....

**Comment by rhatdan** [comment]
What is left to do?

**Comment by grooverdan** [comment]
I rebased it all yesterday. Need to go through the test failures and fix some of the plumbing with the executor stages removed. Expect this to be submitted in the next few days.

**Comment by smac89** [comment]
Hello. Any progress on this yet?

**Comment by rhatdan** [comment]
@grooverdan Are you still looking at this?

**Comment by grooverdan** [comment]
haven't forgotten it but got much further down my to look at queue. Got as far as https://github.com/grooverdan/buildah/tree/args-target-platform_2 during a rebase but there's gaps (which I can't remember at the moment)

**Comment by rhatdan** [comment]
@grooverdan Ping again.

**Comment by grooverdan** [comment]
@rhatdan I'm so sorry. I've left IBM and with my current focus I doubt I'll ever get time do reaquaint my understanding with the buildah codebase again. I'll leave the partial rebase there if some has the time to identify the gaps I've left. Hopefully the test suite is in a good enough state in the branch to identify gaps.

**Comment by rhatdan** [comment]
This is all handled now, I believe in the current release.

**Comment by jonstelly** [comment]
Should this work and set the typical docker args:

Dockerfile
```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet
ARG TARGETPLATFORM
ARG TARGETARCH
ARG BUILDPLATFORM
```

When using docker buildx like `docker buildx build --platform=linux/arm64 .` it sets those build arguments.  But when running with buildah I get these warnings:

```bash
> buildah bud --os=linux --arch=arm64 -t myimg:arm64 .
WARN missing "TARGETPLATFORM" build argument. Try adding "--build-arg TARGETPLATFORM=<VALUE>" to the command line
WARN missing "TARGETARCH" build argument. Try adding "--build-arg TARGETARCH=<VALUE>" to the command line
WARN missing "BUILDPLATFORM" build argument. Try adding "--build-arg BUILDPLATFORM=<VALUE>" to the command line
```

```bash
> buildah bud --platform=linux/arm64 -t myimg:arm64 .
WARN missing "TARGETPLATFORM" build argument. Try adding "--build-arg TARGETPLATFORM=<VALUE>" to the command line
WARN missing "TARGETARCH" build argument. Try adding "--build-arg TARGETARCH=<VALUE>" to the command line
WARN missing "BUILDPLATFORM" build argument. Try adding "--build-arg BUILDPLATFORM=<VALUE>" to the command line
```

Then inspecting the image shows history like (note the value is amd64 instead of arm64):

```json
{
    "created": "2021-04-13T02:23:49.450762Z",
    "created_by": "/bin/sh -c #(nop) ARG TARGETPLATFORM=linux/amd64",
    "empty_layer": true
},
{
    "created": "2021-04-13T02:23:49.4508238Z",
    "created_by": "/bin/sh -c #(nop) ARG TARGETARCH=amd64 TARGETPLATFORM=linux/amd64",
    "empty_layer": true
},
{
    "created": "2021-04-13T02:23:49.4512675Z",
    "created_by": "/bin/sh -c #(nop) ARG BUILDPLATFORM=linux/amd64 TARGETARCH=amd64 TARGETPLATFORM=linux/amd64",
    "empty_layer": true
}
```

The images do seem to get generated correctly, maybe this is only an issue of variables not being set when generating the history information?

**Comment by TomSweeneyRedHat** [comment]
@jonstelly buildx/builder toolkit functionality is slowly winding it's way into Buildah.  But most of it is not yet included and I believe the options you've listed here are not.  We have thought talked adding it, but it's not bubbled up to the top of the plans yet.  However, we'd be more than happy to consider a PR or more from the community for it.
