### ISSUE TITLE
Document --pull and --pull-always

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1381]
Document/clarify the functionality of the `--pull` and `--pull-always` options.

--pull=true
Pull the image from the first registry it is found in as listed in registries.conf.  If it is not found in the registries use the local version of the image if available.  Raise an error if the image is not in any listed registry and is not present locally.

--pull=false
Do not pull the imge from the regsistry, use only the local version.  Raise an error if the image is not present locally.

--pull-always
Pull the image from the first registry it is found in as listed in registries.conf.  Raise an error if not found in the registries, even if the image is present locally.

**Comment by rhatdan** [comment]
How about:
--pull=true
Attempt to pull the latest image from the registries listed in registries.conf, if local image does not exist or the image is newer then the one in storage.  Raise an error if the image is not in any listed registry and is not present locally.

**Comment by TomSweeneyRedHat** [comment]
Happy to take any wording for any of these.  I just threw this issue together quickly after the meeting so I wouldn't forget about it and I'm not at all married to my first cut at it.

**Comment by rhatdan** [comment]
Open a PR with mine and your other two, and we can get it merged.  Then we will need the same for podman.

**Comment by TomSweeneyRedHat** [comment]
Going to reopen until I get this into Podman too.

**Comment by rhatdan** [comment]
Just got merged into podman so closing.
