### ISSUE TITLE
Need canonical registries.conf

### ISSUE THREAD

**Issue by KenYN** [containers/buildah#1385]
I'm creating a script to automatically install Buildah and a number of other tools on Ubuntu, but I need a `/etc/containers/registries.conf`. There's a [sample in tests](https://github.com/containers/buildah/blob/master/tests/registries.conf) and also references to [the Fedora version](https://src.fedoraproject.org/rpms/skopeo/blob/master/f/registries.conf), but it would be nice to have an official one, or have a suggested option documented. For now I am just doing:

    curl -sL https://raw.githubusercontent.com/containers/buildah/master/tests/registries.conf | \
          sudo tee /etc/containers/registries.conf

But it would feel more reliable if the directory was `sample/config` rather than `tests`.

**Comment by rhatdan** [comment]
We can make a sample config.  And add docker.io, quay.io to it?  Others?  Currently the distros are shipping their own version.
