### ISSUE TITLE
Take advantage of strings.Builder rather than `+=`

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1397]
As noted by @vrothberg in #1313, since we use GoLang 1.10 plus now, we should scrub instances of `+=` concatenation and replace them  with strings.Builder.  His main comment there is:

Performance nit: string concatenations are very slow. Starting with Go 1.10, there's a strings.Builder which is much faster. We could also use a var buf bytes.Buffer and buf.WriteString("...") which is still magnitudes faster than the + operator.

**Comment by vrothberg** [comment]
Thanks, @TomSweeneyRedHat :pray:

**Comment by rhatdan** [comment]
I don't see any += code left in Buildah other then some format commands on the CLI, no reason to complicate that code.

**Comment by rhatdan** [comment]
Reopen if you disagree.
