### ISSUE TITLE
Validate user storage.conf and report error if the configuration file is wrong

### ISSUE THREAD

**Issue by jkonecny12** [containers/buildah#1401]
**Description**

This issue is filed based on discussion in https://github.com/containers/buildah/issues/1286 . The problem is that user will get message about overlayfs but the real problem was incompatible configuration file. This happened to me by just updating existing version of the tools, however, thanks to the error I spent about an hour to find the cause. And I wasn't able to understand that even after I found the correct issue.

Based on my tests it looks that parser will do the basic checks but it is not able to find the problem here.

**Steps to reproduce the issue:**
1. Create  ~/.config/containers/storage.conf with this content:
```
RunRoot = "/run/user/1000"
GraphRoot = "/home/jkonecny/.local/share/containers/storage"
GraphDriverName = "overlay"
GraphDriverOptions = ["overlay.mount_program=/usr/bin/fuse-overlayfs"]
```
2. run buildah images (or any other command)

**Describe the results you received:**
Overlay FS error message.

**Describe the results you expected:**
Message that your configuration file is not compatible and how you can fix that.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.7-1.git873f001.fc29.x86_64
```

**Output of `buildah version`:**

```
buildah version 1.7 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
Fedora release 29 (Twenty Nine)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.20.14-200.fc29.x86_64 #1 SMP Tue Mar 5 19:55:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
I have found no decent go library for verifying a yaml file

**Comment by jkonecny12** [comment]
That's a shame. Is there a way how to check if the required values are set or something similar?

**Comment by rhatdan** [comment]
I would guess the question is what are the required values?

**Comment by TomSweeneyRedHat** [comment]
I'm not sure how we could validate the yaml.  Should we close this issue given that?  Any other bright ideas?

**Comment by jkonecny12** [comment]
Feel free to close this in case there is really no idea to solve it.
