### ISSUE TITLE
Multi-layered build-using-dockerfile builds create too many layers

### ISSUE THREAD

**Issue by nalind** [containers/buildah#1405]
When attempting to switch on multi-layered builds for openshift/builder (in [#35](https://github.com/openshift/builder/pull/35)), one of the tests that failed did so because we're creating more layers than `docker build` does for the test's Dockerfile.

The root cause is that we commit a new layer for every instruction that we process in a `Dockerfile`, when the more conformant behavior would be to do so only for `ADD`, `COPY`, and `RUN` instructions.

One point of reference is [buildkit's parser](https://github.com/moby/buildkit/blob/9faab2a616cde39d10b63f0351a987ac93915484/frontend/dockerfile/dockerfile2llb/convert.go), and calls that it makes to its local `commitToHistory()` function for various instructions.

Option 1: modify Commit() so that we can commit without creating a layer.  This... feels like it's going to lose someone's data at a bad time.
Option 2: use #1300's empty layer history entries to skip the expensive commits, while fixing the history for non-layered builds.  I'm working on this.

**Comment by rhatdan** [comment]
Since the patch for this is merged, I am closing.
