### ISSUE TITLE
--dns* flags would be nice to have

### ISSUE THREAD

**Issue by hainesbg** [containers/buildah#1438]
**Description**

`biuldah bud` should have `--dns`, `--dns-opt`, and `--dns-search` options just like `podman run` does (see also https://github.com/containers/libpod/issues/2755, requesting same for `podman build`).

My use case is trying to hit package repos as part of a build while using the systemd-resolved stub resolver (127.0.0.53) in my /etc/resolv.conf.

It's probably too much to ask at the moment for the better solution of somehow ultimately querying against the host's resolver library, This would be quite the boon for some situations, but the command line arg would be a workable substitute.

**Comment by rhatdan** [comment]
PR is being merged.
