### ISSUE TITLE
Image build failed on COPY, VOLUME, WORKDIR instruction use symlinks

### ISSUE THREAD

**Issue by Lagrang** [containers/buildah#1439]
(Edited just to make the buildah example be happy in md)
**Description**

`buildah bud` failed on Dockerfile with WORKDIR instruction: ensuring container path "/usr/local/hbase/bin": mkdir /var/lib/containers/storage/btrfs/subvolumes/8325b8065650778d4abbb211b130511525e668b8b45e0df0f1c3563646c4c674/usr/local/hbase: file exists

I find out, that root cause is symlinks: COPY, VOLUME, WORKDIR instructions cannot handle it.
COPY not support symlink as target and fails with error:
`
COPY --chown=hbase:hadoop conf/hbase-env.sh      conf/log4j.properties      conf/hadoop-metrics2-hbase.properties      conf/hbase-policy.xml      $HBASE_CONF_DIR/}: error creating directory "/var/lib/containers/storage/btrfs/subvolumes/8b473a99a4b0bcc89d0b3a70a25414431dd5063a0987c084c134efcd78be56cb/etc/hbase": chown /var/lib/containers/storage/btrfs/subvolumes/8b473a99a4b0bcc89d0b3a70a25414431dd5063a0987c084c134efcd78be56cb/etc/hbase: no such file or directory
`

VOLUME which point to symlink overwrite target folder permissions to root and cause folder inaccessible for container.

**Steps to reproduce the issue:**
1. Dockerfile from this [repo](https://gitlab.com/hutils/containers/tree/09121d3b7f85e6033b7354c903d209cd815d96d3/hbase/2.x)
2. Run 
```
    sudo buildah bud --no-cache \
             --build-arg HBASE_VERSION=2.1.2 \
             --build-arg HADOOP_VERSION=2.8.5 \
             -t hbase .
```
**Describe the results you received:**
`Command:workdir Args:[/usr/local/hbase/bin] Flags:[] Attrs:map[] Message:WORKDIR $BASE_INSTALL_PATH/hbase/bin Original:WORKDIR $BASE_INSTALL_PATH/hbase/bin}: error ensuring container path "/usr/local/hbase/bin": mkdir /var/lib/containers/storage/btrfs/subvolumes/8325b8065650778d4abbb211b130511525e668b8b45e0df0f1c3563646c4c674/usr/local/hbase: file exists`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/bionic,now 1.8-1~dev~ubuntu18.04~ppa8 amd64 [installed]
buildah/bionic 1.8-1~dev~ubuntu18.04~ppa8 i386
```

**Output of `buildah version`:**

```
Version:         1.8-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Mon Mar 25 02:03:14 2019
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

**Output of `uname -a`:**

```
Linux lagrang 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
#driver = "overlay"
driver="btrfs"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
@Lagrang I'm able to duplicate the issue using your Dockerfile and other related files.  My first immediate thought was something in the processing from the --no-cache flag was potentially causing the issue, but that doesn't appear to be the case.

I'm going to see if I can create a less intensive Dockerfile that  recreates the issue.  If you by chance have one, please let me know.

**Comment by karelyatin** [comment]
Also seeing similar issue(WORKDIR + symlink), more details https://bugs.launchpad.net/tripleo/+bug/1824952

**Comment by TomSweeneyRedHat** [comment]
OK it looks like the COPY is just writing to the specified location and not first checking to see if it's a symlink.  I've come up with a Dockerfile that reproduces the error below. 

```
# cat ~/Dockerfile.symtarget
FROM alpine

ENV HBASE_HOME="/usr/local/hbase"
ENV HBASE_CONF_DIR="/etc/hbase"

RUN mkdir $HBASE_HOME
RUN ln -s $HBASE_HOME $HBASE_CONF_DIR

COPY Dockerfile.symtarget $HBASE_CONF_DIR

```
