### ISSUE TITLE
"layer not known" when `podman inspect` an image built by buildah

### ISSUE THREAD

**Issue by dulek** [containers/buildah#1447]
**Description**

Using the latest buildah from Project Atomic PPA, I see the images come up corrupted. In this context I'm talking about kuryr-kubernetes images (github.com/openstack/kuryr-kubernetes).

**Steps to reproduce the issue:**
1. `sudo buildah bud -t docker.io/kuryr/controller -f controller.Dockerfile .`
2. `sudo podman inspect docker.io/kuryr/controller`

**Describe the results you received:**
```
stack@ubuntu:~$ sudo podman inspect 0ec695486886
Error: error parsing image data "0ec6954868868d717feffcdfa267f75555c28bbbbb333e5b0fc4380e57932271": error reading image "0ec6954868868d717feffcdfa267f75555c28bbbbb333e5b0fc4380e57932271": layer not known
```

**Describe the results you expected:**
Regular inspect content.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
stack@ubuntu:~$ apt list buildah
Listing... Done
buildah/bionic,now 1.8-1~dev~ubuntu18.04~ppa8 amd64 [installed]
```

**Output of `buildah version`:**

```
stack@ubuntu:~$ buildah version
Version:         1.8-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Sun Mar 24 23:03:14 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
stack@ubuntu:~$ podman version
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
stack@ubuntu:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
stack@ubuntu:~$ uname -a
Linux ubuntu 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
@dulek Thanks for the issue report.  Can you include the contents of the Dockerfile please?  If you do `buildah inspect docker.io/kuryr/controller` are you seeing a similar error or a different one?

**Comment by dulek** [comment]
@TomSweeneyRedHat: Ah, good idea, haven't tried `buildah inspect` and unfortunately it seems that my environment lost the ability to reproduce this. Tomorrow I'll try to run that on upstream kuryr-kubernetes CI, where we see it constantly.

Two Dockerfiles that we used are here:
- https://github.com/openstack/kuryr-kubernetes/blob/master/controller.Dockerfile
- https://github.com/openstack/kuryr-kubernetes/blob/master/cni.Dockerfile

**Comment by dulek** [comment]
@TomSweeneyRedHat: Okay, seems like `buildah inspect` [works fine](http://logs.openstack.org/67/644867/7/experimental/kuryr-kubernetes-tempest-containerized-crio/a269778/job-output.txt.gz#_2019-03-27_11_19_58_025202). Still crio (and most likely podman, but I haven't added a debug line to that gate run) [is complaining about "layer not known"](http://logs.openstack.org/67/644867/7/experimental/kuryr-kubernetes-tempest-containerized-crio/a269778/controller/logs/screen-container.txt.gz#_Mar_27_11_32_35_633594).

Does this mean that the issue is podman or crio not understanding what buildah built? It's either buildah or podman not following some standard?

**Comment by dulek** [comment]
Ah, I'm using [Project Atomic PPA](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa) with Ubuntu Bionic. Seems like the most recent buildah update to 1.8-1~dev~ubuntu18.04~ppa9 is included and still has the issue.

**Comment by TomSweeneyRedHat** [comment]
Thanks @dulek.  I've not had enough tea (yet), so need a bit of clarity.  So with the original Buildah that you'd installed on your machine, `buildah inspect {image}` worked fine.  But after upgrading the machine to the latest upstream version, then `buildah inspect {image}` failed in the same manner as `podman inspect`?

That's interesting if so.   Thanks for the tests and updates.

**Comment by dulek** [comment]
@TomSweeneyRedHat: No, not really. Let me elaborate here.

The logs I'm linking are from our (openstack/kuryr-kubernetes) CI jobs. Kuryr-Kubernetes is a CNI plugin that allows using OpenStack Neutron to network pods. So obviously our CI is starting a K8s cluster, deploys OpenStack Neutron and Kuryr-Kubernetes and runs various tests. For a long time that only run with Docker as K8s CRI. We started to test with cri-o, buildah and podman just a few months ago. To test our code changes the gate jobs are building the kuryr-kubernetes container images on the testing machine. Obviously when testing with cri-o/podman/buildah, we don't have docker binary there, so we build using podman/buildah. Due to #1206 `podman build` isn't working correctly, so we switched to use `buildah bud`. That worked well a while ago (e.g. I see successful run on Dec 5th), but now it seems broken. I don't really know the exact date when this stopped working as the job was broken for a while due to another reason.

The machines are fresh each time, so it's definitely not an upgrade issue. I tried reproducing this locally and was able to do it once, but seems like after I cleared /var/lib/containers (I couldn't delete images using podman due to "layer not known"; haven't thought of using buildah directly back then) it started working fine.

Anyway on fresh machines the error seems 100% reproducible.

**Comment by dulek** [comment]
It might be simple incompatibility between buildah and podman versions available in the PPA (we're using whatever installs when we do `apt install podman buildah cri-o-1.13`), but I'm a bit surprised that images format doesn't have backwards compatibility.

**Comment by TomSweeneyRedHat** [comment]
@dulek I tried quickly to reproduce, but I had a really weird error on my much abused test vm.  I think I'll try setting up a fresh one in the morning and see how it goes.

Not an error I've encountered before
```
STEP 5: COPY . /opt/kuryr-kubernetes
error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin UPPER_CONSTRAINTS_FILE=https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt] Command:copy Args:[. /opt/kuryr-kubernetes] Flags:[] Attrs:map[] Message:COPY . /opt/kuryr-kubernetes Original:COPY . /opt/kuryr-kubernetes}: error copying "/root/tsweeney/workspaces/buildah/src/github.com/containers/buildah/tmp/work/containers-storage/overlay/backingFsBlockDev" to "/var/lib/containers/storage/overlay/a0d103320dc13b0011ab52b188bf9b9e9567ac8a567ba2154df9e0130f005adb/merged/opt/kuryr-kubernetes": archive/tar: write too long
```

but I've been playing the space saving shuffle on this system, so perhaps I just ran out of disk space.

**Comment by dulek** [comment]
@TomSweeneyRedHat: Well, I haven't seen that either. And while I doubt it's related, at this point I don't trust my judgement as all this is really confusing.

**Comment by rhatdan** [comment]
I guess this still exists?

**Comment by TomSweeneyRedHat** [comment]
I just gave this a go and it worked fine for me.  We've had a number of changes in how podman and buildah handles images over the past year, especially focusing on making things happy between the two projects.  I just tried to duplicate without success using the latest upstream.  I'm going to close this now.  Please open a new issue if you find this is still a problem.
