### ISSUE TITLE
overlay2 is not supported overlayfs , storage-driver=overlay

### ISSUE THREAD

**Issue by chenliu1993** [containers/buildah#1448]
**Description**

I am trying to run docker in docker by using ctr on Photon linux kernel. The error is Devices "cgroup" is not mounted. The details are "overlay2 is not supported overlayfs , storage-driver=overlay" Anyone knows how to solve this problem
<img width="1108" alt="WechatIMG6" src="https://user-images.githubusercontent.com/13761170/55066949-ca9d7780-50b9-11e9-8f87-683484348888.png">

**Comment by rhatdan** [comment]
You need to volume mount in /var/lib/containers into the buildah container.  BTW have you thought about using podman for this?

**Comment by chenliu1993** [comment]
> You need to volume mount in /var/lib/containers into the buildah container. BTW have you thought about using podman for this?

Thanks! It works.
