### ISSUE TITLE
Buildah CI hard to reproduce locally

### ISSUE THREAD

**Issue by vrothberg** [containers/buildah#1453]
The Buildah CI heavily relies on the logic in the .travis file to set up a local registry along with credentials etc. This makes it incredibly hard to reproduce issues locally. At the moment, I ran into the situation where Travis seems to be stuck on a deadlock that I am unable to reproduce locally.

I think it is beneficial to be able to execute and reproduce the integration tests locally (maybe in a container). I guess this work will consume some time but we can use this issue a tracker.

Cc: @TomSweeneyRedHat @rhatdan @cevich @edsantiago

**Comment by cevich** [comment]
I agree this is a useful thing. Though I would recommend treading carefully with using containers, even if super-privileged.  Experience with `containers/storage` (repo. CI) has shown that it works fine for simple cases.  However, as needs grow deeper/more advanced (including debugging-ability), getting out from a container-setup can be a major headache.  There are simply certain resources inaccessible from containers, and if required for testing, demand a LOT of hoop-jumping.

In any case, some suggested first steps would be:

1. Move the commands from `.travis.yml` into dedicated scripts, then call those from the `yaml`.
2. After that's working, modify on each script, separating items specific to environment setup vs testing into their own scripts.
3. Decide/Define/Document a very specific "Supported Host Environment" for devel. and debugging.  Ideally this should match as closely as possible to the desired CI environment.
4. Make the separated environment-specific script's match the definition.
5. From the top-level scripts, make the ci-environment scripts configurable.  So they can be substituted for other calls when operating outside of Travis/CI.  For example (using `before_install`), maybe have a `before_install_ubuntu.sh` and `before_install_fedora.sh`
5. Forever maintain the set of environment scripts, such that they remain as identical and reproducible as possible.

**Comment by rhatdan** [comment]
Is anyone working on this?  Should we just break out the tests that rely on registries into a separate PR.  Is the move to Cirrus going to make this any easier?

**Comment by cevich** [comment]
I believe migrating from travis to cirrus-ci + a functional 'hack/get_ci_vm.sh' should take care of this.  Granted it doesn't completely fix the "reproduce locally" issue, but better codifies the environment in a reusable way.

**Comment by rhatdan** [comment]
As soon as we create the new Release we can merge this.  Please hold off until then.

**Comment by rhatdan** [comment]
We are now using cirrus, is that enough to close this PR?

**Comment by TomSweeneyRedHat** [comment]
I'm making the executive decision to close this given travis is no longer in the picture.  @vrothberg please reopen or create a new issue if you feel otherwise.
