### ISSUE TITLE
Official release package distribution

### ISSUE THREAD

**Issue by konrad-ohms** [containers/buildah#1454]
Hi,
I am sorry if the information is already present somewhere, but I could not find it on my own.

What is the recommended way to install buildah in production? I really like the features of buildah and would like to use it for our build environments, as the scripted build approach offers nice features over our current Dockerfile-based build. Currently we are building on Ubuntu (mostly because of a more current version of Docker) and I was quite surprised what versions of buildah I receive on different operating systems.
From the release notes I was expecting to get v1.7.1 consistently on all platforms, but depending on which platform I was following the instructions from the [installation notes](https://github.com/containers/buildah/blob/master/install.md) I get different versions of buildah, Ubuntu does even seem to get unreleased packages.
Could you please advise how I should install packages to obtain the production-ready version of buildah? Thanks for any help in advance.

**Steps to reproduce the issue:**
1. Get Ubuntu/CentOS/RHEL systems
2. Install buildah from repositories
3. Compare received buildah versions

**Describe the results you received:**
- Ubuntu 18.04 x86_64 -> 1.8-dev (unreleased?)
```
# buildah --version
buildah version 1.8-dev (image-spec 1.0.0, runtime-spec 1.0.0)

# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

# uname -a
Linux xxx 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Ubuntu 18.04 ppc64le -> 1.8-dev (unreleased?)
```
# buildah --version
buildah version 1.8-dev (image-spec 1.0.0, runtime-spec 1.0.0)

# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

# uname -a
Linux xxx 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:57:45 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
```

- CentOS 7 x86_64 -> 1.5.2 (executed inside a centos:7 docker container)
```
# buildah --version
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)

# yum --showduplicates list buildah
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.nublue.co.uk
 * extras: www.mirrorservice.org
 * updates: www.mirrorservice.org
Installed Packages
buildah.x86_64                                                                                 1.5-2.gite94b4f9.el7.centos                                                                                  @extras
Available Packages
buildah.x86_64                                                                                 1.2-2.gitbe87762.el7                                                                                         extras 
buildah.x86_64                                                                                 1.4-3.gitc8ed967.el7                                                                                         extras 
buildah.x86_64                                                                                 1.5-2.gite94b4f9.el7.centos                                                                                  extras

# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# uname -a
Linux 2f370933c7e3 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- RHEL 7 x86_64 -> 1.2 (might be caused by old repositories in our company, not sure about that one)
```
# buildah --version
buildah version 1.2 (image-spec 1.0.0, runtime-spec 1.0.0)

# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

# uname -a
Linux xxx 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- RHEL 7 ppc64le -> 1.5 (might be caused by old repositories in our company, not sure about that one, but I was surprised that the versions differ between architectures)
```
# buildah --version
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)

# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

# uname -a
Linux xxxx 3.10.0-957.5.1.el7.ppc64le #1 SMP Wed Dec 19 15:44:52 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
```

**Describe the results you expected:**
I would expect to receive the latest released code via the package manager (v1.7.1) on all platforms, at least on RHEL/CentOS/Ubuntu.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 thoughts or can you fill in the blanks for when/how things are updated on the different distros?

**Comment by rhatdan** [comment]
Perhaps the Dockerfile stuff you are working on can solve this issue.

**Comment by redbaron** [comment]
It would also be nice to have binaries published to github release.

**Comment by lsm5** [comment]
let me get back on this once the snap packages are done.

**Comment by rhatdan** [comment]
We now have supported container images for this on https://quay.io/buildah

**Comment by konrad-ohms** [comment]
Cool, thanks, looks quite good.
While trying out the container I noticed one minor thing in https://github.com/containers/buildah/blob/8e48a65d5b22366c2e4946d6e41788365acc7ae2/contrib/buildahimage/README.md#sample-usage, probably we should adjust the command to run in the loop.
When using the command as defined, the CPU load on a single core goes up to 100% usage: 
```
podman run \
  --detach \
  --name=buildahctr \
  --net=host \
  --security-opt label=disable \
  --security-opt seccomp=unconfined \
  --device /dev/fuse:rw \
  -v /var/lib/mycontainer:/var/lib/containers:Z \
  quay.io/buildah/stable sh -c 'while true ;do wait; done'
```
![Selection_574](https://user-images.githubusercontent.com/40577406/59265953-c7407380-8c46-11e9-8e02-83a8484c17a9.png)

When switched from `wait` to `sleep`, that problem disappeared, consumption is shown as 0%:
I used:
```
podman run \
  --detach \
  --name=buildahctr \
  --net=host \
  --security-opt label=disable \
  --security-opt seccomp=unconfined \
  --device /dev/fuse:rw \
  -v /var/lib/mycontainer:/var/lib/containers:Z \
  quay.io/buildah/stable sh -c 'while true ;do sleep 100000; done'
```
![Selection_575](https://user-images.githubusercontent.com/40577406/59265962-cd365480-8c46-11e9-81b7-168029a02b47.png)

**Comment by TomSweeneyRedHat** [comment]
@konrad-ohms do you have a suggested tweak in mind for the command?

**Comment by konrad-ohms** [comment]
I propose to change the command executed as start command in the container from
```
sh -c 'while true ;do wait; done'
```
to
```
sh -c 'while true ;do sleep 100000; done'
```

That should help resolving the high CPU load.

**Comment by TomSweeneyRedHat** [comment]
Thanks @konrad-ohms , I'll give that a whirl.  I've spun up #1665 to track it.

**Comment by konrad-ohms** [comment]
thanks

**Comment by lsm5** [comment]
@konrad-ohms are you still looking to install buildah on 18.04? 1.9.2 is available on the PPA. See: https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages

**Comment by konrad-ohms** [comment]
cool, thanks for the hint.

**Comment by TomSweeneyRedHat** [comment]
I don't believe there's further work for this issue.  Please spin up a new one if you've other questions or concerns.
