### ISSUE TITLE
BUG: tagging is broken for multistage builds

### ISSUE THREAD

**Issue by h-vetinari** [containers/buildah#1456]
[Now that I have access to the nightly ppa's (cf. containers/libpod#2250), I'm starting to file some issues against `podman` - and since the issue template there says that `podman build` issues should be filed for buildah, I'm starting here.]

Assume I have a toy dockerfile, say `podman_test.dockrf`:
```
FROM docker.io/library/ubuntu:bionic

RUN apt-get update && apt-get install curl -y

CMD ["bash"]
```

Then `sudo podman build -t podman_test -f podman_test.dockrf .` produces 
![buildah1](https://user-images.githubusercontent.com/33685575/55168014-51159000-5172-11e9-85a7-4704d1858b66.png)

So far so good. If I change the dockerfile slightly:
```diff
-FROM docker.io/library/ubuntu:bionic
+FROM docker.io/library/ubuntu:bionic as base

 RUN apt-get update && apt-get install curl -y

 CMD ["bash"]
```
then I get an untagged image (even though it successfully uses the cache):
![buildah2](https://user-images.githubusercontent.com/33685575/55168094-7dc9a780-5172-11e9-835c-e4f06e28c8f0.png)

Same for `sudo podman build -t podman_test --target=base -f podman_test.dockrf .`

This is quite basic functionality IMO - without tagging, many automation tasks are not possible.

**Comment by TomSweeneyRedHat** [comment]
@h-vetinari thanks for the issue.  This is definitely not acting correctly as you surmised.  I think the <none><none> is ok for image 21fe, but what I think should be happening is we should have another image there named podman_test with and id of d6ca... , the last line from the build output there.

There appears to be something going on with the --layers option that's not letting that complete successfuly, if I add `--layers=false` to the podman build command, then I see that image.

I'll have to dig more in the next day or too, and may need to check in with @nalind

**Comment by h-vetinari** [comment]
Thanks for the response!

> @TomSweeneyRedHat:  I think the `<none>` `<none>` is ok for image 21fe, but what I think should be happening is we should have another image there named podman_test with an id of d6ca... , the last line from the build output there.

Ideally (IMO) both dockerfiles should create exactly the same image, so that 21fe... is not untagged by the build, but stays the same. Builds not being idempotent is another issue I'm encountering (pending further tests).

**Comment by nalind** [comment]
I think #1473 will fix this.

**Comment by h-vetinari** [comment]
@nalind @TomSweeneyRedHat 
I just tested the newest nightly after I saw that #1473 had been merged - unfortunately, the issue persists (assuming `http://ppa.launchpad.net/projectatomic/ppa/ubuntu` is up-to-date).

**Comment by TomSweeneyRedHat** [comment]
@h-vetinari I'm not sure that's up to date.  @lsm5 can you confirm or deny please?

**Comment by lsm5** [comment]
@h-vetinari what version of ubuntu are you on? I see that 16.04 hasn't been updated in a long time. I'll fix that now. 18.04 was last built on 5th april. Travis auto-builds break often for buildah quite likely due to .travis.yml changes.

**Comment by h-vetinari** [comment]
@lsm5 
I'm on Ubuntu 18.04. Is the ppa-update not scheduled regularly (e.g. daily)? Can you say if https://github.com/containers/buildah/commit/29a6c812d924d04402b87c4487ed2d2e1c55a70b was already part of the last build?

@nalind @TomSweeneyRedHat 
Seems that the last build I tested above (and which fails the scenario laid out in the OP) includes at least #1473, but possibly not #1487.

**Comment by lsm5** [comment]
On Mon, Apr 08, 2019 at 01:32:52PM -0700, h-vetinari wrote:
> @lsm5 
> I'm on Ubuntu 18.04. Is the ppa-update not scheduled regularly (e.g. daily)? Can you say if https://github.com/containers/buildah/commit/29a6c812d924d04402b87c4487ed2d2e1c55a70b was already part of the last build?

The latest build for 18.04 includes all commits up to
https://github.com/containers/buildah/commit/610eb7a0b2d4d8dbbc9e5c694d3a448a4636e7b8
so I'll say yes.

RE: ppa update, it happens daily on my fork. But things tend to break often
cause rebases aren't always clean, and the debian build process makes it super
painful to upstream.

I have a TODO for snap builds which should be a lot easier to upstream. Soon as
I can find the time.

> 
> @nalind @TomSweeneyRedHat 
> Seems that the last build I tested above (and which fails the scenario laid out in the OP) includes at least #1473, but possibly not #1487.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/buildah/issues/1456#issuecomment-480996487

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by nalind** [comment]
> [Now that I have access to the nightly ppa's (cf. [containers/libpod#2250](https://github.com/containers/libpod/issues/2250)), I'm starting to file some issues against `podman` - and since the issue template there says that `podman build` issues should be filed for buildah, I'm starting here.]
> 
> Assume I have a toy dockerfile, say `podman_test.dockrf`:
> 
> ```
> FROM docker.io/library/ubuntu:bionic
> 
> RUN apt-get update && apt-get install curl -y
> 
> CMD ["bash"]
> ```
> 
> Then `sudo podman build -t podman_test -f podman_test.dockrf .` produces
> ![buildah1](https://user-images.githubusercontent.com/33685575/55168014-51159000-5172-11e9-85a7-4704d1858b66.png)
> 
> So far so good. If I change the dockerfile slightly:
> 
> ```diff
> -FROM docker.io/library/ubuntu:bionic
> +FROM docker.io/library/ubuntu:bionic as base
> 
>  RUN apt-get update && apt-get install curl -y
> 
>  CMD ["bash"]
> ```
> 
> then I get an untagged image (even though it successfully uses the cache):
> ![buildah2](https://user-images.githubusercontent.com/33685575/55168094-7dc9a780-5172-11e9-835c-e4f06e28c8f0.png)
> 
> Same for `sudo podman build -t podman_test --target=base -f podman_test.dockrf .`
> 
> This is quite basic functionality IMO - without tagging, many automation tasks are not possible.

I think what you're after would conventionally be accomplished by building only through that stage with the `--target` flag, and by using the `-t` flag to specify a tag to apply to the final image.

The name specified in a `FROM ... AS ...` instruction is not treated as a tag for the image built at that stage, as its main use is to avoid requiring that subsequent `COPY --from=` instructions specify stages by number, which can get hard to maintain if you find you need to add a stage to the middle of a multi-stage Dockerfile.

**Comment by h-vetinari** [comment]
> > @h-vetinari: [...]
Same for `sudo podman build -t podman_test --target=base -f podman_test.dockrf .`
[...]

> @nalind: I think what you're after would conventionally be accomplished by building only through that stage with the `--target` flag, and by using the `-t` flag to specify a tag to apply to the final image.

This is exactly what is *not* working, and what this issue is about, see self-quote from OP. Neither does it work to build the full image (no `--target`) - the final image currently ignores the `-t` tag.

**Comment by nalind** [comment]
Aargh, I missed that.  This appears to work correctly with buildah at least as of version ffd8d6a5de26e76f4446feadc837d55f9139dad8, though, so I expect we're looking at https://github.com/containers/libpod/pull/2931/ to incorporate those changes into podman.

**Comment by h-vetinari** [comment]
@nalind 
I've been trying to monitor the PRs and regularly tested with the most current nightly builds for podman/buildah. Seems that this specific commit hasn't made it to the PPA yet, so I can't verify. But thanks for fixing! :)

Yeah, would definitely need to update the version vendored by podman, as I'm planning to use this through podman.

**Comment by h-vetinari** [comment]
@nalind 
Never mind, I hadn't completely thought through the effects of the vendoring...

Using the latest PPA, it works correctly to do either of:
* `sudo buildah bud -t podman_test -f podman_test.dockrf .`
* `sudo buildah bud -t podman_test --target=base -f podman_test.dockrf .`

**Comment by h-vetinari** [comment]
Thanks!

**Comment by h-vetinari** [comment]
Just checked with the new PPA after containers/libpod#2931, and now it works with `podman build` too! :)
