### ISSUE TITLE
"man buildah" also needs to update "SEE ALSO" to have "containers-" prefix

### ISSUE THREAD

**Issue by rpjday** [containers/buildah#1460]
As with some of the other container-related man pages, "man buildah", the final "SEE ALSO" section, reads:

"podman(1), mounts.conf(5), registries.conf(5), storage.conf(5)"

some of which are clearly missing the proper "containers-" prefix that have been fixed elsewhere.

**Comment by rpjday** [comment]
I can submit a PR for this under the assumption that the above should read:

"podman(1), containers-mounts.conf(5), newuidmap(1), newgidmap(1), containers-registries.conf(5), containers-storage.conf(5)"

Does that sound about right?

**Comment by rhatdan** [comment]
Yes please do.

**Comment by rpjday** [comment]
Done.

**Comment by rhatdan** [comment]
Looks like this is in current buildah
