### ISSUE TITLE
BUG: --build-arg detection not working in multistage builds

### ISSUE THREAD

**Issue by h-vetinari** [containers/buildah#1463]
[Continuing from #1456; containers/libpod#2250]

Assume I have a toy dockerfile, say `podman_test.dockrf`:
```
FROM docker.io/library/ubuntu:bionic as base
# FROM docker.io/library/ubuntu:bionic as base2

ARG TEST_ARG

RUN if [ $TEST_ARG = "TRUE" ]; then \
    apt-get update ; \
    apt-get install curl -y ; \
    fi

CMD ["bash"]
```
then everything builds fine (aside from the tagging issue #1456) with
```
sudo podman build -t podman_test --build-arg TEST_ARG=TRUE -f podman_test.dockrf .
```

But if the second line is uncommented, I get a spurious warning about:
```
[Warning] One or more build-args [TEST_ARG] were not consumed
```

Starting to ignore this warning is obviously risky business, as it would be easily possible to miss cases where it is *actually* missing (in this case, leaving out `--build-arg TEST_ARG=TRUE` would result in a single line `/bin/sh: 1: [: =: unexpected operator`, that's easy to overlook in the build log).

**Comment by TomSweeneyRedHat** [comment]
@h-vetinari just to make sure we're on the same page, you said "But if the second line is uncommented, ..." and showed an error.  The error you received there you got from using the same 'sudo podman build...` command that you've illustrated?  I.e. you didn't tweak that any right?

**Comment by h-vetinari** [comment]
> @TomSweeneyRedHat: @h-vetinari just to make sure we're on the same page, you said "But if the second line is uncommented, ..." and showed an error. The error you received there you got from using the same 'sudo podman build...` command that you've illustrated? I.e. you didn't tweak that any right?

That's exactly right (sorry if I wasn't clear enough), with the sole exception that it does not error the build, but just yields a warning.

**Comment by nalind** [comment]
This should have been fixed by #1427.

**Comment by rhatdan** [comment]
@h-vetinari What version of buildah are you using?  Can you check it versus buildah in master?  Or buildah 1.7 if you are using an older version.

**Comment by h-vetinari** [comment]
@rhatdan @nalind 
I had been on the latest ppa:nightly when I filed this. I just updated that again and now it's fixed. Thanks for the prompt reaction!
