### ISSUE TITLE
buildah from --cpu-shares: not working, or test is misleading

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#1464]
`tests/from.bats:242` (the cpu-shares test) has code that does:
```
# cid=$(buildah from --cpu-shares=2 --pull alpine)
# buildah run $cid cat /sys/fs/cgroup/cpu/cpu.shares
```
...but all it does is check that the output contains '2'. It does: the output is actually `1024`.

If 1024 is the expected value, please correct the test.

If 2 is the expected value, please investigate buildah.

**Comment by rhatdan** [comment]
This looks like a bug in buildah
Podman works correctly
```
# podman run --rm --cpu-shares=2 fedora  cat /sys/fs/cgroup/cpu/cpu.shares
2
```
Versus
```
# buildah from --cpu-shares=2  alpine
#   cid=$(buildah from --cpu-shares=2 --pull --signature-policy ${TESTSDIR}/policy.json alpine)
# buildah run  $cid cat /sys/fs/cgroup/cpu/cpu.shares
1024
```
