### ISSUE TITLE
Does /var/lib/containers/storage/overlay/... end in "diff" or "merged"?

### ISSUE THREAD

**Issue by rpjday** [containers/buildah#1468]
In https://github.com/containers/buildah/blob/master/docs/tutorials/01-intro.md, partway down:
```
# echo $scratchmnt
/var/lib/containers/storage/overlay/b78d0e11957d15b5d1fe776293bd40a36c28825fb6cf76f407b4d0a95b2a200d/diff
```
That ends in "diff", but when I run it, it ends in "merged". Is there a distinction?

**Comment by rhatdan** [comment]
Correct it should be merged.

**Comment by rpjday** [comment]
So from where came the existing suffix of "diff"? Was that what it *used* to display? I have to assume that line was copy and paste so that string must have been printed under some conditions.

Pedantically yours.

**Comment by rhatdan** [comment]
I have no idea, but this is definitely a bug in the tutorial

**Comment by nalind** [comment]
(It would have been `diff` before https://github.com/containers/storage/pull/154 was merged.)

**Comment by rhatdan** [comment]
That explains it.
