### ISSUE TITLE
An "automatic" official "lightweight" container image

### ISSUE THREAD

**Issue by vdemeester** [containers/buildah#1483]
**Description**

It would awesome if users could try `buildah` using their container runtime, like `podman run -ti --rm buildah …`. Other image builder tend to have that (like `kaniko` with `gcr.io/kaniko-project/kaniko:latest`). This would also ease the use of `buildah` in users CI build (like using `knative/build` with [build-templates](https://github.com/knative/build-templates/blob/master/buildah/Dockerfile) or `tektoncd/pipeline`).

The ideal would it to be : 
- Automatically build and tagged (`latest` would target a released version, `:master` would be the current master build)
- Lightweight, using multi-stage like [here](https://github.com/knative/build-templates/blob/master/buildah/Dockerfile) (or something else), as long as it only contains what is required to run
- Tailored / configure to run inside containers, ideally as user (compatible with k8s and openshift, …)

cc @vbatts @vrothberg with whom I talked about it already

**Comment by vrothberg** [comment]
> Automatically build and tagged (latest would target a released version, :master would be the current master build)

@vdemeester, do you know how we could build them automatically? I *think* GitHub actions can help us but I have zero experience with that.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @nalind @cevich @edsantiago @rhatdan PTAL

**Comment by vdemeester** [comment]
> @vdemeester, do you know how we could build them automatically? I _think_ GitHub actions can help us but I have zero experience with that.

Right, could be using github action or the CI (which is travis right now ?).

**Comment by rhatdan** [comment]
We are actually working through some of this now for a locked down buildah container.   

@TomSweeneyRedHat Could you contribute the Dockerfile we have so far for building this?

The problem, I see is do we just go with strickly a locked down BuildahCtr or do we also go with a flexible Buildah container.

I always wanted to tell people multiple different ways you can run buildah inside of a container on top of CRI-O, Docker and Podman.

Getting this right and putting one or two buildahctrs out on quay.io seems like the right thing to do.

@TomSweeneyRedHat Can we get a quay.io/buildah/ repository?

**Comment by rhatdan** [comment]
The last question I would have is what distro should the container be using.  Fedora for latest, RHEL8 for supported?

**Comment by vdemeester** [comment]
> The last question I would have is what distro should the container be using. Fedora for latest, RHEL8 for supported?

That would be my guess too :angel:

**Comment by TomSweeneyRedHat** [comment]
@rhatdan ack on quay and the script

**Comment by TomSweeneyRedHat** [comment]
And if you want a sneak peak at the Dockerfile sooner, here's a Demo script that's a WIP to create it:
https://github.com/containers/Demos/pull/17

**Comment by cevich** [comment]
Not too sure about the question (a bit outside of my realm), but I think buildah/libpod may be too tightly coupled to make using an alternate engine possible?  Generally adding flexibility like that also brings in a lot of extra complexity.  As for building images, plenty of services can do that in addition to Quay.  [Cirrus-CI has a neat feature where you don't even need  a registry to store the image.  Just point it at a dockerfile, and a script and it will automatically mash the two together.](https://cirrus-ci.org/guide/docker-builder/#dockerfile-as-a-ci-environment)

*Not sure if Cirrus-CI is the right answer...it's just what I know.*

**Comment by phozzy** [comment]
Hi @vdemeester ! I try to create a gitlab-ci pipeline to build an image with buildah. Ofcourse it is not an oficial image, but it is also possible to trust to images created by your own. But I have an error at the last step (pushing image to a registry) when I use overlayfs storage drive. If it sounds interesting to you, you make take a look to the following issue: https://github.com/containers/buildah/issues/1496

**Comment by afbjorklund** [comment]
I have an image based on [tinycore](https://hub.docker.com/r/tatsushid/tinycore)... It's not updated very often (nor releases), though.
https://github.com/boot2podman/boot2podman/tree/master/containers/tinycore-buildah

```
REPOSITORY                                                  TAG           IMAGE ID       CREATED         SIZE
boot2podman-docker-tinycore.bintray.io/tinycore-buildah     1.6           9cbf9dee8f0d   2 months ago    90.5 MB
```

If there is enough interest, I could update it to Tiny Core Linux 10.x and Buildah 1.7.2.
Most of the hassle is around bintray.io packages defaulting to https, rather than http...

The current package used for the image above still uses the old release and no rootless.
Also there is no stand-alone packaging for buildah, it is built as part of boot2podman.iso

**Comment by vbatts** [comment]
The boot2podman update sounds useful too.

Back to the original intent here, we hoping for a landmark location for an always fresh buildah image, that can (will) be generally used as a canonical basis for folks to use.
Right now we've put a fair amount of work into https://github.com/knative/build-templates/blob/master/buildah/Dockerfile and are plumbing it up to have an always-fresh build on quay.io (my testing repo is `quay.io/ohman/buildah`).

ideally this kind of canonical base image would be provided by buildah itself, as a kind of common building block.

**Comment by rhatdan** [comment]
@vbatts @TomSweeneyRedHat is working on this also, in quay.io/buildah/  So I think we should combine our efforts.

**Comment by phozzy** [comment]
registry.gitlab.com/containertools/containertools:latest - allways fresh allinone image (with buildah, podman and skopeo).
it is supposed that you'll be able to run it from unprivileged user. (if not open issue :-) )
not oficial one, but if someone from someone from container-tools developers will join that group, I'll apreciate that.

**Comment by rhatdan** [comment]
@phozzy Ping me dwalsh@redhat.com with a link of where I should join.

**Comment by marshallford** [comment]
@vdemeester I've been working on something like this: https://github.com/marshallford/podman. The CI requirements you describe are quite similar to how I implemented a CircleCI pipeline.

I'm currently working on replacing the `fedora:30` base image with `alpine` and building podman and its dependencies from source (multi stage). As of late I have been trying to get `musl` to work when building `conmon`.

**Comment by rhatdan** [comment]
buildah images are now available at https://quay.io/buildah.
