### ISSUE TITLE
Buildah 1.7.2 fails to build against containers/image 1.5

### ISSUE THREAD

**Issue by siretart** [containers/buildah#1512]
Context of this inquiry is https://github.com/containers/libpod/issues/1742 - I'm working on getting buildah and podman packaged and integrated into the Debian software archive.

I'm trying to compile buildah version 1.7.2 against the latest release of github.com/containers/image (which is version 1.5 according to https://github.com/containers/image/releases), and containers/storage v1.12.1.

I'm getting this compilation error:

```
# github.com/containers/image/storage
src/github.com/containers/image/storage/storage_image.go:712:55: not enough arguments in call to s.imageRef.transport.store.SetImageBigData
	have (string, string, []byte)
	want (string, string, []byte, func([]byte) (digest.Digest, error))
src/github.com/containers/image/storage/storage_image.go:740:54: not enough arguments in call to s.imageRef.transport.store.SetImageBigData
	have (string, string, []byte)
	want (string, string, []byte, func([]byte) (digest.Digest, error))
src/github.com/containers/image/storage/storage_image.go:749:55: not enough arguments in call to s.imageRef.transport.store.SetImageBigData
	have (string, string, []byte)
	want (string, string, []byte, func([]byte) (digest.Digest, error))
src/github.com/containers/image/storage/storage_transport.go:184:10: options.UIDMap undefined (type func(bool, int) (storage.StoreOptions, error) has no field or method UIDMap)
src/github.com/containers/image/storage/storage_transport.go:185:10: options.GIDMap undefined (type func(bool, int) (storage.StoreOptions, error) has no field or method GIDMap)
src/github.com/containers/image/storage/storage_transport.go:186:33: cannot use options (type func(bool, int) (storage.StoreOptions, error)) as type storage.StoreOptions in argument to storage.GetStore
```

Please let me know if I need to upgrade containers/storage and or containers/image to a newer release.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
This API break is really hunting me :sob:

@siretart, the latest containers/image and containers/storage is not compatible with Buildah 1.7.2. API changes in c/storage are responsible for that. The changes have been propagated through the stack but did not make into a new release of Podman and Buildah. I recommend sticking with the versions of c/image and c/storage that Buildah/Podman vendor.

Things are still moving fast and, unfortunately, API breaks still happen (soon one coming from myself in c/image).

**Comment by siretart** [comment]
I see.

That's unfortunate, I was hoping that there were a (ideally small number of) commits to buildah that would unbreak things, but apparently buildah still needs to catch up with API changes. Let's track progress on that in this issue and see whether Debian's ftp-master (accepting the packages I upload from the stack) or you guys (catching up with API changes) win the race :-)

**Comment by rhatdan** [comment]
Well we have newer versions of buildah and containers/image so I guess I can close this.  Reopen if you disagree.
