### ISSUE TITLE
Packaging Buildah for Alpine Linux

### ISSUE THREAD

**Issue by azatsarynnyy** [containers/buildah#1513]
Hello!
If I understand right, there were some [efforts](https://github.com/containers/buildah/issues/466#issuecomment-373961930) in direction of packaging Buildah for Alpine Linux distribution but it's not finished yet. Am I right?
Are there any plans to proceed with it?

**Comment by rhatdan** [comment]
We rely on the community for that.  Engineers from Red Hat concentrate on packaging for Fedora, RHEL, Centos and Ubuntu.
Others are packaging for other distributions.  OpenSuse for example.

We have some effort started to get the container packages packaged for Debian as well.

We will fully support anyone who wants to package for any othed distribution including Alpine.

**Comment by azatsarynnyy** [comment]
I see. @rhatdan  thanks for your answer!

**Comment by kohnish** [comment]
My merge request for buildah, podman, and crun was merged. They are now in alpine edge testing repo. With manual configuration, they work fine.

Skopeo already exists in community repo, so with some polishing they can go to community soon probably.

**Comment by rhatdan** [comment]
Great news.  Thanks for your efforts, @kohnish
