### ISSUE TITLE
newgidmap: executable not found in $PATH on Ubuntu 18.04

### ISSUE THREAD

**Issue by benmoss** [containers/buildah#1518]
**Description**
I installed buildah via the Ubuntu PPA, following the instructions on https://github.com/containers/buildah/blob/master/install.md#ubuntu

It installed successfully, but when I run `buildah` i get this error:

```
Error: error running newgidmap: exec: "newgidmap": executable file not found in $PATH:
ERRO[0000] error running newgidmap: : exec: "newgidmap": executable file not found in $PATH
ERRO[0000] (unable to determine exit status)
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/bionic,now 1.8-1~dev~ubuntu18.04~ppa22 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.8-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Fri Apr 12 19:13:55 2019
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux halite 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
@lsm5 Do we need a recommends newgid?

**Comment by SpamapS** [comment]
The package is `uidmap`, and it's a dependency, not a recommends, because the bud command is non-functional without it.

**Comment by lsm5** [comment]
I'll make that change, btw, I'm working on snap packages for these tools, so hopefully the PPA can be abandoned soon.

**Comment by lsm5** [comment]
should be fixed in `buildah-1.8-1~dev~ubuntu18.04~ppa23`

**Comment by giuseppe** [comment]
this is required only for rootless builds, root still works without it.  Should it still be a dependency and not a recommends?

**Comment by SpamapS** [comment]
Thanks for the update! Also @giuseppe yes, a depends, because a major part of the program doesn't work without it on the local machine. Recommends are for things like a GUI that talks to the daemon, or a database server that the program can talk to, but also might exist on some other box.
