### ISSUE TITLE
Have problems building images, with caching turned on

### ISSUE THREAD

**Issue by afbjorklund** [containers/buildah#1523]
**Description**

Looks like building with podman/buildah doesn't work, with cache/layers turned on ?

This is for minikube, when running with cri-o rather than docker, and wanting to build.

It seems to work ok with `--no-cache`

Using the overlay graph driver, on ext4.

**Steps to reproduce the issue:**
1. `sudo -E podman build .`
2. _or_ `sudo -E buildah bud --layers .`
3. cat Dockerfile

``` Dockerfile
FROM busybox
RUN true
```

Note: I need to use -E, in order to propagate the required BUILDAH_NOPIVOT properly.

**Describe the results you received:**

```
STEP 1: FROM busybox
STEP 2: RUN true
error checking if cached image exists from a previous build: error getting top layer info: layer not known
```

**Describe the results you expected:**

```
STEP 1: FROM busybox
STEP 2: RUN true
--> 9c5ea0591112ff895c460c85a3c101526509764f02ac13cd520c01440991ca95
STEP 3: COMMIT 
--> 9c5ea0591112ff895c460c85a3c101526509764f02ac13cd520c01440991ca95
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
-bash: rpm: command not found
-bash: apt: command not found
```

**Output of `buildah version`:**

```
Version:         1.7.2
Go Version:      go1.10.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.10.2
Git Commit:         3bd528e583182b4249f3e6bbd8497a8831d89950
Built:              Tue Apr 16 19:22:31 2019
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"
NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"
```

**Output of `uname -a`:**

```
Linux minikube 4.15.0 #2 SMP Tue Apr 16 21:05:18 CEST 2019 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by afbjorklund** [comment]
Thinking that this must have been a temporary issue, corrupted `/var/lib/containers/storage` ?

Recreated the VM, and the same thing works fine:
``` console
$ sudo -E podman build .
STEP 1: FROM busybox
Getting image source signatures
Copying blob fc1a6b909f82 done
Copying config af2f74c517 done
Writing manifest to image destination
Storing signatures
STEP 2: RUN true
--> 93c716efcd9863106a7c6e7ee0ebf3418b6f973d37e4500364b72a7a204b9c27
STEP 3: COMMIT 
--> 93c716efcd9863106a7c6e7ee0ebf3418b6f973d37e4500364b72a7a204b9c27
```

So there doesn't seem to be anything to do here.

**Comment by afbjorklund** [comment]
Hmm, ran the commands again and now there is a new error.

``` console
$ sudo -E podman build .
STEP 1: FROM busybox
Error: error creating build container: error instantiating image for "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/busybox:latest": layer not known
$ sudo -E buildah bud --layers .
STEP 1: FROM busybox
error creating build container: error instantiating image for "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/busybox:latest": layer not known
```

So something seems unstable about layers in this environment.

**Comment by vbatts** [comment]
@nalind we're seeing something like this in https://github.com/tektoncd/pipeline/issues/887

**Comment by TomSweeneyRedHat** [comment]
@vbatts or @afbjorklund was there by chance a reboot on the vm/machine?  We were pinged on IRC this morning by "radiofree" that after a reboot, his build didn't work with a similar error.  It looks like the intermediate containers had been stored in /tmp and were gone after the reboot.  However the underlying storage code and/or runc had issues as it expected to fin d the layers  there.

**Comment by afbjorklund** [comment]
The VM was newly created/booted, but it seemed flaky. It was supposed to use /var/lib/containers

**Comment by afbjorklund** [comment]
Upgraded minikube to use podman 1.3.1 now, so could try again and see if issue remains...

``` console
$ sudo podman version
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.10.2
Git Commit:         7210727e205c333af9a2d0ed0bb66adcf92a6369
Built:              Mon May 20 20:27:45 2019
OS/Arch:            linux/amd64
$ cat Dockerfile
FROM busybox
RUN true
$ sudo -E podman build .
STEP 1: FROM busybox
Getting image source signatures
Copying blob 53071b97a884 done
Copying config 64f5d945ef done
Writing manifest to image destination
Storing signatures
STEP 2: RUN true
STEP 3: COMMIT
--> 1b998ed7c4d33c8dff0cfaef039b41b75f44015ac0b18e1045bd5a4255b91975
```

Think it was something temporary or with the old version, so going to close it... ?
