### ISSUE TITLE
doc fix: buildah does not require root

### ISSUE THREAD

**Issue by danmack** [containers/buildah#1572]
**Description**
The buildah manpage and .md file incorrectly state that the command must be run as the root user.  buildah works fine in rootless mode.

**Steps to reproduce the issue:**
1. view doc in md format for buildah
2. man buildah

**Describe the results you received:**

-This tool needs to be run as the root user.

**Describe the results you expected:**

<empty line>

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.7-18.git873f001.fc30.x86_64

```

**Output of `buildah version`:**

```
Version:         1.7
Go Version:      go1.12.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Wed Dec 31 18:00:00 1969
OS/Arch:         linux/amd64

```

**Comment by TomSweeneyRedHat** [comment]
Closing as this was fixed in #1573.  Thanks @danmack !
