### ISSUE TITLE
buildah manpage formatting fix in files section

### ISSUE THREAD

**Issue by danmack** [containers/buildah#1574]
**Description**

The buildah manage has un-filled/formatted paragraphs underneath each file reference in the Files section.

**Steps to reproduce the issue:**
1.man buildah
2.scroll to bottom
3. unformatted paragraphs for the file descriptions.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.7-18.git873f001.fc30.x86_64

```

**Output of `buildah version`:**

```
Version:         1.7
Go Version:      go1.12.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Wed Dec 31 18:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 30 (Thirty)
```

**Output of `uname -a`:**

```
Linux fano.parsec.lab 5.0.10-300.fc30.x86_64 #1 SMP Tue Apr 30 16:22:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TomSweeneyRedHat** [comment]
Closing as this was fixed in #1575, Thanks @danmack !
