### ISSUE TITLE
WORKDIR as symlink copy fails if it's part of the destination rather than fully specified

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1577]
**Description**

If the WORKDIR is a symlink and a COPY is invoked, it fails if a portion of the copy destination is the symlink.  ie. 'COPY file.txt ./file.txt'  

**Steps to reproduce the issue:**
1.  See results.

**Describe the results you received:**
Using this Dockerfile:

```
# cat Dockerfile-2
# No directory created for the target of the symlink
FROM alpine
RUN ln -sf /var/lib/tempest /tempest
WORKDIR /tempest
RUN touch /etc/notareal.conf
RUN chmod 664 /etc/notareal.conf
COPY Dockerfile-2 ./Dockerfile-2

# buildah bud -t myimage -f Dockerfile-2 .
```
The file is apparently copied, but it's not found in the container.

**Describe the results you expected:**
File should be copied as it is in Docker.

**Output of `buildah version`:**

```
1.9.0-dev
```

**Comment by rhatdan** [comment]
Looks like this has been fixed.
