### ISSUE TITLE
Support mounting directories with a `:` (colon) in their path

### ISSUE THREAD

**Issue by silviot** [containers/buildah#1597]
**Description**

Currently [there is no way to mount a directory with a colon in its name (e.g. `/tmp/aa:bb`) neither as source nor destination.
[This is the code that parses the mounts](https://github.com/containers/buildah/blob/59da11d4b4df6c9b51d06fc804f7a2e46be6c700/pkg/parse/parse.go#L154). 

**Steps to reproduce the issue:**
Try to mount a directory with a colon in its name.
```bash
buildah run -v /some:dir:/destination container-name
```

**Suggested solution**
Support the same syntax docker supports, with `--mount` in addition to `-v/--volume`.

**Comment by TomSweeneyRedHat** [comment]
@silviot thanks for the issue.  We'd a similar problem with envvars yesterday in Podman, this one might be a little bit more entertaining as we allow for the format `host-dir:ctr-dir[:option]`.   Should be fixable though, will take a look.

**Comment by rhatdan** [comment]
I am not sure how fixable this is.  Does Docker support this?

**Comment by silviot** [comment]
@rhatdan Docker supports it since version 1.13.0. For example to mount the directory `/tmp/aaa:bbb` on the host to `/cc:dd` in the container one could use something like this:
```
docker run --rm -ti --mount type=bind,src=/tmp/aa:bb,dst=/cc:dd alpine sh
```

This is the commit that introduced support for this option type: 
https://github.com/docker/cli/commit/3375ba2acd1176db7c2f2028f6b6910a52f6981f
And [this is the pull request that introduced the feature](https://github.com/moby/moby/pull/22373).

I thought it would be useful to dig these up and mention them in this issue, but I'm not 100% sure that's the right piece of code. In case it isn't please speak up and bear with me: I never used `go`.

**Comment by rhatdan** [comment]
If that does not work on Podman then that is an issue, but you were asking for 

podman run -v /tmp/aa:bb:/cc:dd alpine sh 
To work in the opening issue.

Does

docker run -v /tmp/aa:bb:/cc:dd alpine sh 

Work?

**Comment by silviot** [comment]
@rhatdan My first example under "Steps to reproduce the issue" shows what a user would do after reading the documentation to mount directory `/tmp/aa:bb`. I'm not advocating to make that syntax work.

I think a good solution to this problem would be to support an additional option besides `-v` as docker does.

```bash
docker run -v /tmp/aa:bb:/cc:dd alpine sh
```
will not work, but the example I gave with `--mount` will. Here it is again:
```bash
docker run --rm -ti --mount type=bind,src=/tmp/aa:bb,dst=/cc:dd alpine sh
```

I only see buildah lacking this feature, because I don't use podman. I imagine it might suffer from the same issue, but personally I only know about buildah.

**Comment by rhatdan** [comment]
```
podman version
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            linux/amd64
$ mkdir /tmp/aa:bb
$ podman run --rm -ti --mount type=bind,src=/tmp/aa:bb,dst=/cc:dd alpine sh
# id 
uid=0(root) gid=0(root)
# ls -l /cc:dd
total 0
```

Works now with Podman.

**Comment by silviot** [comment]
> ```
> podman version
> Version:            1.3.1
> RemoteAPI Version:  1
> Go Version:         go1.12.2
> OS/Arch:            linux/amd64
> $ mkdir /tmp/aa:bb
> $ podman run --rm -ti --mount type=bind,src=/tmp/aa:bb,dst=/cc:dd alpine sh
> # id 
> uid=0(root) gid=0(root)
> # ls -l /cc:dd
> total 0
> ```
> 
> Works now with Podman.

Please note I opened this ticket for a problem I had with buildah, and I never used podman: I'm currently using buildah to build containers that will run in a docker environment. I'm very happy about the features buildah offers over docker to build container images.
But I can't mount a directory with a colon in its path using buildah.

I understand now (I did not when I opened the ticket) that I can use [the workaround outlined here](https://github.com/containers/buildah/blob/03f62479b34ec5461c1b28cfb6f5ec75886f021e/troubleshooting.md#solution-2) to solve this problem, and I will use it for my immediate needs.
I still think it would be very nice for buildah to support the same `--mount` option podman supports.
