### ISSUE TITLE
COPY in Dockerfile fails on a symlink

### ISSUE THREAD

**Issue by jkryl** [containers/buildah#1598]
I have a problem when using Dockerfile to build an image.  It looks as if symlinks in COPY target were not processed properly. I get the following error message:

```
STEP 6: COPY moac /moac/
error building at STEP "COPY moac /moac/": error creating symbolic link to "../esprima/bin/esparse.js" at "/var/lib/containers/storage/overlay/f8c017fd9cb563cf10e1e4b7c0a3f5058fda0660375813cbb8381c78d77d94e7/merged/moac/node_modules/.bin/esparse": symlink ../esprima/bin/esparse.js /var/lib/containers/storage/overlay/f8c017fd9cb563cf10e1e4b7c0a3f5058fda0660375813cbb8381c78d77d94e7/merged/moac/node_modules/.bin/esparse: file exists
```
The situation on disk looks as follows. `node_modules/.bin` contains symlinks which are pointing to executable files inside node modules, so the target is something like `../npm-module/bin/cmd.js`. `docker build` works fine, but buildah fails on these symlinks. Does it ring a bell?

I'm using dockerfile:
```
FROM node:10

RUN mkdir /moac
WORKDIR /moac
COPY moac/package*.json ./
RUN npm install
COPY moac /moac/
RUN mkdir -p /mayastor-grpc/proto
COPY mayastor-grpc/proto /mayastor-grpc/proto

ENTRYPOINT ["/moac/main.js"]
```
buildah version:
```
Version:         1.9.0-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Tue May 14 23:36:19 2019
OS/Arch:         linux/amd64
```
uname -a:
```
Linux mayastor-dev 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TomSweeneyRedHat** [comment]
Thanks for the issue @jkryl , will take a look

**Comment by TomSweeneyRedHat** [comment]
@jkryl  I just ran I made it past that copy that you ran into an issue with.   It had an issue copying the local mayastor-grpc/proto file as I didn't have one.  Output below.  Can you try updating your sandbox and running make/make install again?  My Buildah was built on May 17, 3 or 4 days after yours and we'd a recent symlink fix that went in.  I'm hoping you just hadn't got it.

```
STEP 3: WORKDIR /moac
STEP 4: COPY moac/package*.json ./
STEP 5: RUN npm install
npm WARN saveError ENOENT: no such file or directory, open '/moac/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/moac/package.json'
npm WARN moac No description
npm WARN moac No repository field.
npm WARN moac No README data
npm WARN moac No license field.

up to date in 0.985s
found 0 vulnerabilities

STEP 6: COPY moac /moac/
STEP 7: RUN mkdir -p /mayastor-grpc/proto
STEP 8: COPY mayastor-grpc/proto /mayastor-grpc/proto
error building at STEP "COPY mayastor-grpc/proto /mayastor-grpc/proto": no files found matching "/root/tsweeney/workspaces/containers/buildah/src/github.com/containers/buildah/mayastor-grpc/proto": no such file or directory
```

**Comment by jkryl** [comment]
Hi @TomSweeneyRedHat , I still have the problem even with following version of the buildah which was built on 20th May:
```
$ buildah version
Version:         1.9.0-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Mon May 20 23:36:51 2019
OS/Arch:         linux/amd64
```
I'm not 100% sure it contains the latest bits but it appears it does according to the date. I will try to reproduce the problem with some easy setup so that you can use it when testing and share the details on this ticket. thanks.

**Comment by jkryl** [comment]
Hi Tom, so I was unable to reproduce the problem using a simple test environment with a symlink to target path. There must be something more to it. It seems easier to me to avoid having these symlinks in the docker image as I don't actually need them. Thanks for your time & help! I'm closing the issue. It can be reopened if someone else hits the same problem and is able to provide reproducible test case.
