### ISSUE TITLE
Release with binary in github please.

### ISSUE THREAD

**Issue by huapox** [containers/buildah#1599]
**Release with binary in github please.**

**Comment by TomSweeneyRedHat** [comment]
@huapox I'm not 100% sure what you're asking for.  Can you give me a pointer to a similar binary or a bit more explanation?

**Comment by rhatdan** [comment]
The binaries are available as containers on quay.io/buildah

**Comment by TomSweeneyRedHat** [comment]
Yes, if the quay.io container image is helpful, more info here: https://github.com/containers/buildah/tree/master/buildahimage

**Comment by huapox** [comment]
I'm just try to use buildah in container for Jenkins-CI, and got help by:
https://github.com/buildah/buildah

buildah satisfied my needs, thx. @rhatdan @TomSweeneyRedHat
