### ISSUE TITLE
Build fails on Centos / older kernel

### ISSUE THREAD

**Issue by epruesse** [containers/buildah#1600]
While building skopeo for conda-forge, the 0.1.36 pulling in the newest buildah fails with

```
unshare.c:6:10: fatal error: linux/memfd.h: No such file or directory
```

(See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=36049&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3)

Since `unshare.c` does not actually use the `MFG_HUGE` defines, it should in theory suffice to `#include <sys/mman.h>`?

**Comment by rhatdan** [comment]
Could you open a PR to fix this in Buildah.

**Comment by rhatdan** [comment]
Looks like this is fixed.
