### ISSUE TITLE
Buildah buildah config --label misbehaviour when label contains a comma

### ISSUE THREAD

**Issue by jtudelag** [containers/buildah#1603]
**Description**

When Building a container image and labelling it, if the label string contains a comma, the label is cut and not set properly in the image. This is a common scenario when setting the `run` label for example, and using multiples options for volume mounting, such as `rw,Z`.  But not only that, usually other labels such as `description` for example, contains large strings with commas included.

I would say the issues is happening the splitting the label string here:
https://github.com/containers/buildah/blob/v1.7/cmd/buildah/config.go#L180

Also, according to Docker docs (Only doc regarding label format I have found), It seems commas are a valid char: https://docs.docker.com/config/labels-custom-metadata/

**Steps to reproduce the issue:**
1. Run the Buildahfile pasted below:
```
#!/usr/bin/env bash

set -e

base_image="docker://quay.io/fedora/fedora:30-x86_64"
image_name="test-label-image"
container_name="test-label"

# Create a build container
container="$(buildah from --name ${container_name} ${base_image})"

buildah config --label name="${image_name}" "${container}"
buildah config --label ok="podman run --rm --name test -v \$PWD/:/data/:rw \$IMAGE \$OPT1" "${container}"                                                                                                         
buildah config --label ko="podman run --rm --name test -v \$PWD/:/data/:rw,Z \$IMAGE \$OPT1" "${container}"                                                                                                       
buildah config --label ok2="11111111111111111111111111122222222222222222222222222222222222" "${container}"                                                                                                        
buildah config --label ko2="111111111111111111111111111,22222222222222222222222222222222222" "${container}"                                                                                                       

# Finally saves the running container to an image
echo "==== Commit image ===="
buildah commit --rm "${container}" "${image_name}:label"
```

2. Run `podman container runlabel --display ko localhost/test-label-image:label` 

**Describe the results you received:**

When displaying the image label `ko`, I'm getting this result, where the label is cut  in half until the comma char:
```
$ podman container runlabel --display ko localhost/test-label-image:label
command: /proc/self/exe run --rm --name test -v /tmp/:/data/:rw
```

**Describe the results you expected:**

```
podman container runlabel --display ko localhost/test-label-image:label
command: /proc/self/exe run --rm --name test -v /tmp/:/data/:rw,Z localhost/test-label-image:label option1
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.7-3.git873f001.fc29.x86_64
```

**Output of `buildah version`:**

```
buildah version
Version:         1.7
Go Version:      go1.11.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
cat /etc/*release
Fedora release 29 (Twenty Nine)
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 29 (Twenty Nine)
Fedora release 29 (Twenty Nine)
```

**Output of `uname -a`:**

```
Linux XXXXX 5.0.13-200.fc29.x86_64 #1 SMP Mon May 6 00:49:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jtudelag** [comment]
This seems to be fixed in master. Just build it from master, and I can't reproduce the issue:

```
./buildah version  
Version:         1.9.0-dev
Go Version:      go1.11.7
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-rc2
Git Commit:      7793c51a
Built:           Sun May 19 12:23:52 2019
OS/Arch:         linux/amd64
```

**Comment by jtudelag** [comment]
Actually it seems to be fixed here: https://github.com/containers/buildah/pull/1467/files

**Comment by TomSweeneyRedHat** [comment]
@jtudelag thanks for the PR anyway, hope to see further contributions!

**Comment by jtudelag** [comment]
@TomSweeneyRedHat of course!! Actually that you mention it, It took me a while to set up my machine to build buildah... 

The [CONTRIBUTING](https://github.com/containers/buildah/blob/master/CONTRIBUTING.md) doc has room for improvements IMHO. Sth similar to what [openshift/origin has](https://github.com/openshift/origin/blob/master/CONTRIBUTING.adoc#openshift-development) would be great. I mean, a more detailed step by step guide, with dependencies, packages needed, etc. 

Just my 2 cents ;).
