### ISSUE TITLE
Multi-stage COPY: absolute symlinks resolved incorrectly

### ISSUE THREAD

**Issue by EricHripko** [containers/buildah#1610]
**Description**
I have a `Dockerfile` that consists of two stages: builder and runtime. Builder installs an executable that is then symlinked to `/bin` (using absolute path). `buildah` fails to resolve this symlink.

**Steps to reproduce the issue:**
1. Create the following `Dockerfile`
```dockerfile
FROM docker.io/ubuntu as builder
RUN touch /bin/myexe.1 && ln -s /bin/myexe.1 /bin/myexe

FROM docker.io/ubuntu
COPY --from=builder /bin/myexe /bin
```
2. Build an image: `buildah bud .`

**Describe the results you received:**
Image fails to build. See the log output below:
```
STEP 1: FROM docker.io/ubuntu AS builder
STEP 2: RUN touch /bin/myexe.1 && ln -s /bin/myexe.1 /bin/myexe
Getting image source signatures
Copying blob 02571d034293 skipped: already exists
Copying blob 270f934787ed skipped: already exists
Copying blob 8d267010480f skipped: already exists
Copying blob 14fe97b1d30f done
Copying config 576b6b1957 done
Writing manifest to image destination
Storing signatures
--> 576b6b195742d9194c1f60822800b9124e7b7c029eb80f3a9f7b31fa407a0eae
STEP 3: FROM docker.io/ubuntu
STEP 4: COPY --from=builder /bin/myexe /bin
error building at STEP "COPY --from=builder /bin/myexe /bin": error evaluating symlinks "/var/lib/containers/storage/overlay/09595cf2f7b33bdd7b40544a1fd09ee368de1c3652090e75108279accbbd2049/merged/bin/myexe": lstat /bin/myexe.1: no such file or directory

```

**Describe the results you expected:**
A successful build of the image. See `docker build` output for comparison:
```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM docker.io/ubuntu as builder
 ---> 94e814e2efa8
Step 2/4 : RUN touch /bin/myexe.1 && ln -s /bin/myexe.1 /bin/myexe
 ---> Running in 2df294013e4d
Removing intermediate container 2df294013e4d
 ---> ea8e5629aca5
Step 3/4 : FROM docker.io/ubuntu
 ---> 94e814e2efa8
Step 4/4 : COPY --from=builder /bin/myexe /bin
 ---> 42b12e40f392
Successfully built 42b12e40f392
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Listing... Done
buildah/xenial,now 1.8-1~dev~ubuntu16.04.2~ppa5 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.8-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Sat Apr 13 16:42:38 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
N/A
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Output of `uname -a`:**

```
Linux scw-35eb3f 4.5.7-docker-4 #1 SMP Tue Jul 12 09:41:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

```

**Comment by EricHripko** [comment]
I've also reproduced this on `master`. The culprit seems to be [filepath.EvalSymlinks](https://github.com/containers/buildah/blob/master/add.go#L247).

`buildah` evaluates symlinks on the host filesystem - which works fine when doing `COPY` from host. This, however, breaks down when copying from another container.

**Comment by EricHripko** [comment]
Unfortunately, I couldn't find a quick fix. `buildah` should do something akin to `docker` where it manually [resolves the symlinks and binds them to the root path](https://github.com/containerd/continuity/blob/master/fs/path.go#L230).

**Comment by EricHripko** [comment]
Made a quick-fix by modifying `imagebuildah/build.go` in the following way. It enabled me get past this error:
```go
// build.go:514
            if other, ok := s.executor.stages[copy.From]; ok && other.index < s.index {
                esrc, err := fs.RootPath(other.mountPoint, src)
                if err != nil {
                    return err
                }
                sources = append(sources, esrc)
            } else if builder, ok := s.executor.containerMap[copy.From]; ok {
                esrc, err := fs.RootPath(builder.MountPoint, src)
                if err != nil {
                    return err
                }
                sources = append(sources, esrc)
            } else {
// build.go:526
```
`fs` comes from `github.com/containerd/continuity/fs`. Would you accept this fix or is the dependency on `containerd` undersirable?

**Comment by EricHripko** [comment]
Round 2: found that there's lovely `securejoin` package already referenced by that file. This also lets me get past the error:
```
// build.go:514
        } else if len(copy.From) > 0 {
            if other, ok := s.executor.stages[copy.From]; ok && other.index < s.index {
                esrc, err := securejoin.SecureJoin(other.mountPoint, src)
                if err != nil {
                    return err
                }
                sources = append(sources, esrc)
            } else if builder, ok := s.executor.containerMap[copy.From]; ok {
                esrc, err := securejoin.SecureJoin(builder.MountPoint, src)
                if err != nil {
                    return err
                }
                sources = append(sources, esrc)
            } else {
// build.go:526
```
This seems like a good patch for this issue. Will you accept a PR for this?

**Comment by TomSweeneyRedHat** [comment]
Accept a patch from that @EricHripko ?  Always, and with a smile!  
Thanks so much!

**Comment by EricHripko** [comment]
Tested my patch and found a problem. Since `securejoin.SecureJoin` resolves full path to the file, `buildah` ends up copying the original filename (i.e., `myexe.1` instead of `myexe`). I can't think of a way to implement this with minimal intrusion to the codebase. Any ideas?

**Comment by TomSweeneyRedHat** [comment]
@EricHripko thanks for the testing update.  I missed this earlier, but I think we'd rather not add a dependency on containerd, but @rhatdan and @nalind would have the final say on that.  
I don't have a good quick thought on how to fix this atm and unfortunately won't have time for a bit to digest as I've other fires.  Hopefully I or someone else will get some cycles soon to chew on this.

**Comment by EricHripko** [comment]
`securejoin` is fine, there's no need for `containerd` now.

The problem is that `buildah` assumes that _source file name_ = _target file name_ when copying to folders. This is not the case for symlinks as `/bin/myexe.1` must be copied under `/bin/myexe` name. I am happy to contribute the fix - but I don't know which part of the pipeline I should fix it in.

**Comment by rhatdan** [comment]
@EricHripko Please Open a PR.

**Comment by rhatdan** [comment]
Thanks @EricHripko Lets get this merged.

**Comment by rhatdan** [comment]
Since this is merged, I am assuming I can close this issue.
