### ISSUE TITLE
Unprivileged net.ipv4.ping_group_range unavailable in older kernels

### ISSUE THREAD

**Issue by llchan** [containers/buildah#1618]
**Description**

It appears that rootless buildah runs try to access `net.ipv4.ping_group_range` which is unavailable to unprivileged users in older kernels.  I believe the cutoff is somewhere near ~3.13 based on some related information in https://github.com/lxc/lxc/issues/97, but I could be wrong.

**Steps to reproduce the issue:**
1. Use an older kernel, I think <3.13ish should exhibit this behavior. I'm on 3.10.0.
2. `ctrid="$(buildah from registry.access.redhat.com/ubi8/ubi-minimal:8.0-127)"`
3. `buildah run "$ctrid" -- echo himom`

**Describe the results you received:**
```
container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write sysctl key net.ipv4.ping_group_range: open /proc/sys/net/ipv4/ping_group_range: no such file or directory\""
error running container: error creating container for [/usr/bin/echo himom]: : exit status 1
error while running runtime: exit status 1
ERRO[0000] exit status 1
```

**Output of `buildah version`:**

```
Version:         1.8.1
Go Version:      go1.12.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-rc2
Git Commit:      57b4288
Built:           Mon May 13 17:38:53 2019
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
Red Hat Enterprise Linux Server release 7.5 (Maipo)
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```

**Output of `uname -a`:**

```
Linux hostname 3.10.0-862.2.3.el7.x86_64 #1 SMP Tue Jun 5 09:55:12 CDT 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @llchan! @giuseppe, can we make adding this sysctl conditional and depend on the kernel version? I am surprised we haven't seen this error yet.

**Comment by giuseppe** [comment]
I've added a check here: https://github.com/containers/buildah/pull/1619

If the sysctl doesn't exist we print a warning and ignore it

**Comment by giuseppe** [comment]
@llchan could you verify if it solves the issue for you?

**Comment by llchan** [comment]
Thanks for the quick action here. Unfortunately this didn't seem to fix it for me.

I wasn't very thorough in my quick-and-dirty research when filing the issue: upon further inspection, it looks like this sysctl is available to unprivileged users on the _host_, just not inside the container, so doing an existence check on the host is unfortunately not sufficient.

**Comment by rhatdan** [comment]
So this kernel did not namespace the setting.

**Comment by llchan** [comment]
It appears that way. Very possible that my initial guesswork is an incorrect lead, if that's what youre saying. I'm not too familiar with this stuff, so let me know if there's any other information that would be helpful.

**Comment by giuseppe** [comment]
in what cases do we need the `net.ipv4.ping_group_range` inside of the container?  Is it something we could drop?

**Comment by rhatdan** [comment]
I think you loose the ability to ping without it.

**Comment by llchan** [comment]
Can we re-open this ticket?  We need a way to detect that this sysctl will be unavailable inside the container, even if it's available on the host.  Apart from setting up a canary container or switching based on kernel version, is there anything else we can do?

**Comment by TomSweeneyRedHat** [comment]
I don't have any advice on what further can be done, will reopen this ticket so others can comment and in case there's a solution that might be worked.

**Comment by rhatdan** [comment]
@llchan Do you have any suggestions?  
What OS/Kernel are you using that is this old and supports rootless buildah?
I guess we could add a flag to not set sysctls for rootless use cases. @giuseppe WDYT?

**Comment by giuseppe** [comment]
this feature was added as part of `Allow ping command without NET_RAW Capabilities (commit 02f54e4b1e57a0f80a6a3cf87ee548550f138df1)`, so I wonder if we can just avoid setting it when NET_RAW is available to the container.  What do you think?

**Comment by rhatdan** [comment]
Seems reasonable, but the only case where NET_RAW would be present is in NON rootless mode (Well almost always)
So we definitely do not need to add it when !rootless and have NET_RAW.
@llchan Would that satisfy your needs or do you need this for Rootless?

**Comment by giuseppe** [comment]
is it happening only on the 7.5 kernel?  If it works on the 7.7 kernel then I think we should just suggest to upgrade.

For the rootless case, I don't think it will anyway work as it is relative to the user namespace, so we could probably just skip setting it.

**Comment by llchan** [comment]
I'm using rootless on RHEL 7.5 with a 3.10 kernel.  Unfortunately system upgrades are out of my hands, so upgrading to 7.7 is not really an option.  I'm okay with losing ping abilities until we're on a newer kernel.

As for ways to detect to this, I would probably just parse /proc/sys/kernel/osrelease and skip this sysctl if the kernel is older than X.  A config variable or flag would also work, but the user experience would be smoother for newcomers if they just received a warning and this was automatically disabled.

**Comment by giuseppe** [comment]
> As for ways to detect to this, I would probably just parse /proc/sys/kernel/osrelease and skip this sysctl if the kernel is older than X. A config variable or flag would also work, but the user experience would be smoother for newcomers if they just received a warning and this was automatically disabled.

I prefer we don't parse kernel versions.  Especially on RHEL kernels, we will miss features that are backported.

For this specific case, I'd just skip setting it for rootless containers as it won't anyway work.

**Comment by rhatdan** [comment]
I agree. Don't do it on rootless.

**Comment by llchan** [comment]
That's fine with me too.  If we want rootless ping support back we can figure something out later.

**Comment by rhatdan** [comment]
@giuseppe Could you open a PR to not set the sysctl if not running as root.

**Comment by llchan** [comment]
I've created #1663 with a naive check. Feel free to close if there's a better way to do it, but that appears to work for me.

**Comment by rhatdan** [comment]
Merging so closing.
