### ISSUE TITLE
Buildah 1.7.3 create on push DTR Failed

### ISSUE THREAD

**Issue by gregoryboue** [containers/buildah#1622]
**Description**

With buildah 1.7.3, I want to push an image to my enterprise registry (DTR 2.6.6).
If the repository doesn't exist before, it's created via [create on push](https://docs.docker.com/ee/dtr/admin/configure/allow-creation-on-push/) DTR functionnality.

It was **ok with buildah 1.6** but **it won't work anymore with buildah 1.7.3**

If a did a first buildah push, i have an error (see below) but the repository is created and empty, and if I do a second buildah push then it's ok (because the repository is ok).

I don't know if you can reproduce this, do you have some DTR ? Maybe it's reproducible with docker hub  ?

**Steps to reproduce the issue:**
1. buildah bud an image
2. buildah push to a DTR

**Describe the results you received:**

buildah push -q --creds=**** dtr-hprod.it.******/gpf.02608.dev/gradle_tu:0.0.85-SNAPSHOT
error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]dtr-hprod.it.******/gpf.02608.dev/gradle_tu:0.0.85-SNAPSHOT" to "docker://dtr-hprod.it.******/gpf.02608.dev/gradle_tu:0.0.85-SNAPSHOT": Error trying to reuse blob sha256:8f2151cb8c8214070e31a0d589e39f0d0d2bb8e98351c541a408d35509f0e8e1 at destination: Error checking whether a blob sha256:8f2151cb8c8214070e31a0d589e39f0d0d2bb8e98351c541a408d35509f0e8e1 exists in dtr-hprod.it******/gpf.02608.dev/gradle_tu: errors:
denied: requested access to the resource is denied
error parsing HTTP 401 response body: unexpected end of JSON input: ""

**Describe the results you expected:**

Buildah push ok.

**Output of `buildah version`:**

```
Version:         1.7.3
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-rc2
Git Commit:      2941f34
Built:           Thu Apr 18 12:02:21 2019
OS/Arch:         linux/amd64
```

**Comment by gregoryboue** [comment]
Hi,

Do you have any idea of the cause of the issue ?

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by mtrmac** [comment]
Please run the push with `buildah --debug push …` and provide the full output (redacting (only) credentials, if any).

My first impression, though, is that the create-on-push functionality is buggy; it should either consistently refuse to allow the presence check c/image is making, without creating the destination repository, or it should automatically create the destination repository and allow the check.

**Comment by mtrmac** [comment]
> Please run the push with `buildah --debug push …` and provide the full output (redacting (only) credentials, if any).
… for both the initial unsuccessful and the second successful push.

**Comment by vrothberg** [comment]
Ping. @gregoryboue, do you still see this issue?

**Comment by rhatdan** [comment]
Closing this since we never got feedback.  Feel free to reopen if this is still an issue.
