### ISSUE TITLE
Piping into `buildah run` never sends EOF on child stdin

### ISSUE THREAD

**Issue by jordemort** [containers/buildah#1650]
**Description**

When I pipe input into `buildah run`, it seems that stdin never reaches EOF in the child process. This problem appears to keep pipelining from working with Ansible's connection module for buildah.

**Steps to reproduce the issue:**
1. `buildah from docker.io/debian:stretch`
2. `echo "echo foo" | buildah run -- debian-working-container /bin/sh`

**Describe the results you received:**

`foo` is printed on my terminal, but `buildah run` never exits.

**Describe the results you expected:**

`foo` is printed on my terminal, and `buildah run` exits, as if I had run `echo "echo foo" | /bin/sh`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Listing... Done
buildah/stretch,now 1.8.2+github2 amd64 [installed]
N: There is 1 additional version. Please use the '-a' switch to see it
```

(I built this myself from the stretch-backport branch of https://github.com/jordemort/buildah)

**Output of `buildah version`:**

```
Version:         1.8.2
Go Version:      go1.11.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jun  6 22:33:30 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

(I built this myself from the stretch-backport branch of https://github.com/jordemort/libpod)

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux a0343e7ab207 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by jordemort** [comment]
FWIW, I think the bug is probably somewhere around https://github.com/containers/buildah/blob/master/run_linux.go#L1129-L1241

Also for the record, I should mention this that I'm doing this inside a container on Docker for Mac, although I don't think it's relevant to the problem. Both `podman run` and `docker run` seem to be working as expected, that is, they exit after echoing `foo` (as long as I pass `-i` to them):

```
root@a0343e7ab207:/app# echo "echo foo" | podman run -i docker.io/debian:stretch /bin/sh
foo
root@a0343e7ab207:/app# echo "echo foo" | docker run -i docker.io/debian:stretch /bin/sh
foo
root@a0343e7ab207:/app#
```

**Comment by TomSweeneyRedHat** [comment]
Interesting bug, thanks for the issue @jordemort !

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 do you have time to poke at this?

**Comment by QiWang19** [comment]
@TomSweeneyRedHat ACK

**Comment by rhatdan** [comment]
@mheon @giuseppe Does this sound like something we had to deal with in Podman?

**Comment by giuseppe** [comment]
> @mheon @giuseppe Does this sound like something we had to deal with in Podman?

this should work fine in Podman as we use a different mechanism for re-execing.

**Comment by rhatdan** [comment]
@giuseppe PTAL #1653
