### ISSUE TITLE
Providing script input to the buildah container

### ISSUE THREAD

**Issue by kameshsampath** [containers/buildah#1656]
It would be nice to have a entrypoint or script baked into the official image that can interpret each line as buildah command and execute the same.

e.g. https://github.com/redhat-developer-demos/quarkus-java-builder/blob/master/bin/buildah.sh#L23-L55

The example above uses the maven build but that can be ignored. 

thoughts ?

**Comment by TomSweeneyRedHat** [comment]
(Tom ducks from @rhatdan's wrath).  We decided to not include an entry point in the image to allow it to be more flexible.  That way people could start up the container and then get into it and play around freely.  You of course could do a Dockerfile like:

FROM quay.io/buildah/stable:latest
ENTRYPOINT /usr/bin/buildah

and use that to create an image with an entrypoint set.  
As far as a script is concerned, do you have one in particular in mind?  We might be able to add something like that to the images.

**Comment by rhatdan** [comment]
Yes the use of a Entrypoint was seen as more of a pain then a benefit. I guess if  you want to add an Entrypoint, just download the stable image and do

```
ctr=$(buildah from quay.io/buildah/stable)
buildah config --entrypoint /usr/bin/buildah $ctr
buildah commit $ctr buildah
```
Now you should be ready to do execute:

```
podman run --device=/dev/fuse -v PATHTOCONTEXTDIR:/context:Z -v PATHTOSTORAGE:/var/lib/containers:Z buildah bud /context
```

**Comment by kameshsampath** [comment]
yeah I agree Entrypoint is pain but safe bet when we want what user want to execute with a container. Having said that I was thinking more like set of instructions  a non-docker format being interpreted by buildah.  more like a simple shell script file  and we do `buildah <(cat myscript.sh)`.  

My intent was to reduce the Dockefile'sh syntax and make user feel more like writing shell script for building their containers. Not sure buildah DSL is the right word to explain ;)

@TomSweeneyRedHat  - an example of script like https://github.com/redhat-developer-demos/quarkus-java-builder/blob/master/bin/buildah.sh

**Comment by TomSweeneyRedHat** [comment]
I don't believe there's further work on this issue given the above discussions.  I'm closing it.  @kameshsampath thanks for the discussion, please open a new issue if you've further concerns.
