### ISSUE TITLE
Podman v1.4 Build with RUN in Dockerfile fails.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1679]
**Description**

As reported at the tail end of #1672, Podman v1.4.1 with Buildah v1.84 in it fails when a Dockerfile has a RUN command in it.  This issue was fixed recently with Buildah v1.9.0 and that is being vendored in Podman https://github.com/containers/libpod/pull/3361

**Steps to reproduce the issue:**
1.  Run `podman build .` with a Dockerfile containing a RUN command within it.

**Describe the results you received:**
Per #1672 
```
STEP 5: RUN chmod -R g=u /opt/{ansible,apb}
panic: runtime error: index out of range

goroutine 19 [running]:
github.com/containers/libpod/vendor/github.com/containers/buildah.runCopyStdio(0xc0008271d0, 0x2b00, 0xc0000c5900, 0x3, 0x3, 0x1, 0xc00083fb30, 0xc0008271e0, 0x2, 0x2, ...)
        /build/podman/src/src/github.com/containers/libpod/vendor/github.com/containers/buildah/run_linux.go:1137 +0x2502
created by github.com/containers/libpod/vendor/github.com/containers/buildah.runUsingRuntime
        /build/podman/src/src/github.com/containers/libpod/vendor/github.com/containers/buildah/run_linux.go:769 +0x10b9
Error: error building at STEP "RUN chmod -R g=u /opt/{ansible,apb}": error while running runtime: exit status 2

```

**Describe the results you expected:**
Successful build.

**Output of `buildah version`:**

```
Buildah v1.8.4
```

**Output of `podman version` if reporting a `podman build` issue:**

```
1.4.1
```

**Comment by TomSweeneyRedHat** [comment]
Quick Repo:
```
# cat ~/Dockerfile.mini
FROM alpine
RUN apk add nginx

# podman build -f ~/Dockerfile.mini .
```
Tested with v1.4.1 and see the error, with https://github.com/containers/libpod/pull/3361included, the error goes away.

**Comment by rhatdan** [comment]
This looks like it has been fixed.
