### ISSUE TITLE
Request: Buildah builds should show the total no of build steps

### ISSUE THREAD

**Issue by maysunfaisal** [containers/buildah#1681]
**Description**

It would be nice for buildah builds to have the total number of steps during a container build. Currently it is `STEP 1: FROM golang:latest` but can we have `STEP 1/10: FROM golang:latest`? This is purely an aesthetic request. :)

**Steps to reproduce the issue:**
1. Do a buildah container build

**Describe the results you received:**
`STEP 1: FROM golang:latest`

**Describe the results you expected:**
`STEP 1/10: FROM golang:latest`

**Output of `buildah version`:**

```
Version:         1.9.0-dev
Go Version:      go1.12.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @maysunfaisal. I like the idea. @johnmcollier has already opened a PR, so I suggest we move the discussion over at #1683.

**Comment by rhatdan** [comment]
This PR seems to be frozen in time...

**Comment by rhatdan** [comment]
Still would be interested in this.
