### ISSUE TITLE
[question] buildah version in stable:v1.9.0 image

### ISSUE THREAD

**Issue by azatsarynnyy** [containers/buildah#1687]
When I execute
`podman run quay.io/buildah/stable:v1.9.0 buildah version`
I get
```
Version:         1.8.2
Go Version:      go1.12.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

What is Buildah version in `buildah/stable:v1.9.0` image?

**Comment by rhatdan** [comment]
Looks like a bug.  @TomSweeneyRedHat PTAL

**Comment by azatsarynnyy** [comment]
The same issue for `buildah/stable:v1.8.3` and `buildah/stable:v1.8.4`

**Comment by rhatdan** [comment]
The problem is that buildah/stable is pulling from fedora updates, and buildah was not released at the time we released.  
buildah 1.9.0 was pushed to stable 16 hours ago, which might not have reached the REPO where buildah stable was released from.  It should be there soon.

```
I just used 
# podman run -ti buildah/stable:v1.9.0 sh
# dnf -y update buildah
```
And it installed buildah 1.9.0

So the next buildah/stable build should get it.

**Comment by TomSweeneyRedHat** [comment]
The quay.io/buildah/stable is built by using this [Dockerfile](https://github.com/containers/buildah/blob/master/contrib/buildahimage/stable/Dockerfile) which in summary does a `FROM fedora:latest` and then `RUN dnf -y install buildah`.   So it looks like the v1.9.0 hasn't yet been pushed to stable.

If you want to play with v1.9.0 before that happens, you can try the upstream image.

```
 podman run quay.io/buildah/upstream buildah version
Trying to pull quay.io/buildah/upstream...Getting image source signatures
{removed happy loading messages for brevity}
Writing manifest to image destination
Storing signatures
Version:         1.9.1-dev
```

**Comment by TomSweeneyRedHat** [comment]
and it looks like @rhatdan and I were typing at the same time.  I've just kicked off a new build for the stable image.  Hopefully, it will grab v1.9.0 this time.

**Comment by azatsarynnyy** [comment]
Thanks, Tom for starting a new build.
I'll check an image for 1.9.0 tomorrow and close the issue.

**Comment by azatsarynnyy** [comment]
Looks like the `buildah/stable:v1.9.0` image hasn't been updated yet. Last modification date is 6 days ago.
Anyway, I'm closing the issue since the proposed workaround works well for me.
Thank you guys for your help!

**Comment by rhatdan** [comment]
@TomSweeneyRedHat I think there might be an issue with the tagging.

```
 podman run -ti quay.io/buildah/stable:v1.9.0 buildah version
Version:         1.8.2
Go Version:      go1.12.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```
While if I run latest I get 
```
# podman run -ti quay.io/buildah/stable buildah version
Version:         1.9.0
Go Version:      go1.12.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Comment by TomSweeneyRedHat** [comment]
I only setup buildah/stable:latest, buildah/testing:latest, buildah/upstream:latest.  Honestly I'm not sure where/how the :1.9.0 images got in play  there.
I could add a new image for each stable release if you'd like, but it might get a bit fun keeping up over time as Fedora moves too.

**Comment by rhatdan** [comment]
Do you think Quay is automatically building those?  I wonder if a user would want a specific version?

**Comment by TomSweeneyRedHat** [comment]
It does look like quay.io is building these automagically for us.  I'm going to guess due to the GitHub commit trigger.  The problem that I see is it's triggering a "1.9.0" tag when we created that release, but the Dockerfile that's used pulls the bits from the latest stable kit which at the time v1.9.0 was created, the stable version was v1.8.2.  I'm not sure how to turn that off.  I like the idea of having a versioned tag but not when it's wrong like that.  A similar thing is happening with Podman.

**Comment by rhatdan** [comment]
Can you just pull the image, update it and then do a force push, to at least fix the version in 1.9.0, and then we can fix them going forward.

**Comment by rhatdan** [comment]
I guess the issue is the "stable" release from Github != Stable Release from Fedora.

**Comment by azatsarynnyy** [comment]
Thanks for updating the image for 1.9.0!
