### ISSUE TITLE
[RFC] how to have regression tests on the quay built images

### ISSUE THREAD

**Issue by vbatts** [containers/buildah#1693]
**Description**

OpenShift pipelines (and I'm sure others) will be downstream users of your https://quay.io/repository/buildah/stable?tab=info builds.
How best should we relay what is expected of this image?
i.e. the path to buildah binary? whether ENTRYPOINT is defined? 

For example, if you document that this image will _not_ set ENTRYPOINT, then downstream can expect to not be broken by it suddenly appearing.

**Comment by vbatts** [comment]
cc @TomSweeneyRedHat

**Comment by rhatdan** [comment]
I think that is what we decided on,  No Entrypoint, so we should document this.

**Comment by TomSweeneyRedHat** [comment]
Weird, no notice from GitHub fro me on this until @rhatdan replied.

**Comment by TomSweeneyRedHat** [comment]
I'll add a note to the docs for the noentrypoint bit.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Did you ever work on this?

**Comment by TomSweeneyRedHat** [comment]
I'm not sure, I'll run it down today.

**Comment by rhatdan** [comment]
I believe this is fixed.  Reopen if I am mistaken.
