### ISSUE TITLE
buildah bud --dns* flag may conflict with --network

### ISSUE THREAD

**Issue by QiWang19** [containers/buildah#1736]
**Description**
Mirror issue from libpod https://github.com/containers/libpod/issues/3553
Using `--dns*` and `--network` together can have conflicts if using --dns* with
--network 'container:<name|id>'
--network 'none'

**Steps to reproduce the issue:**
1. `buildah build-using-dockerfile` and `buildah from` have --dns* and --network flags. Will this have conflict?

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.9.0-1.git00eb895.fc30.x86_64
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.9.3-dev
Go Version:      go1.12.6
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.0-rc2
Git Commit:      555b5a50
Built:           Mon Jul 22 15:27:19 2019
OS/Arch:         linux/amd64
```

**Comment by mheon** [comment]
Background here: we noticed this one while doing some updates to Podman's `--network` flag. Podman matches Docker's syntax (`none`, `bridge`, `host`, `container:$ID`). Buildah, however, does not support this syntax - most notable, `buildah bud --network container` doesn't point to another container, but instead seems to just set up a CNI network for the container.

It's sort of confusing that we have two tools with mostly identical CLI syntax disagreeing completely on this flag.

**Comment by rhatdan** [comment]
@nalind WDYT?
