### ISSUE TITLE
Buildah equivalent to docker save

### ISSUE THREAD

**Issue by gregoryboue** [containers/buildah#1738]
Hello,

I want to export an image to tar.gz format as it's possible with [docker save](https://docs.docker.com/engine/reference/commandline/save/) command.

I browsed buildah documentation and i didn't find anything about this, is there any way to export image to tar.gz format in buildah ?

**Comment by vrothberg** [comment]
Hi @gregoryboue, thanks for opening the issue.

> I browsed buildah documentation and i didn't find anything about this, is there any way to export image to tar.gz format in buildah ?

Yes, that's possible. Buildah understands various formats (e.g., docker, oci, dir, docker-archive, etc.). You can see a full list [here](https://github.com/containers/image/blob/master/docs/containers-transports.5.md). There are two transports to generate a tar archive:

* docker-archive: `buildah push $image docker-archive:/path/to/file.tar`
* oci-archive: `buildah push $image oci-archive:/path/to/file.tar`

You can also import them via `buildah pull {docker,oci}-archive:/path/to/file.tar`. Alternatively, you can use `podman save` and `podman import` (which essentially do the same).

**Comment by rhatdan** [comment]
You could also use podman save, which works with buildah images, if you want similar syntax.
