### ISSUE TITLE
rootless overlay mount option 'O'

### ISSUE THREAD

**Issue by jamescassell** [containers/buildah#1741]
**Description**

The `O` mount option is not available in rootless mode.  This option can be used to greatly speed up building containers by pre-loading `yum` or other caches.  When attempting to use the option in rootless mode, an error is received.

**Steps to reproduce the issue:**
1. c=$(buildah from ubi8)
2. buildah run $c yum makecache
3. m=$(buildah mount $c)
4. d=$(buildah from -v $m/var/cache/dnf:/var/cache/dnf:O ubi8)

**Describe the results you received:**
`invalid options "O", overlay mounts not supported in rootless mode`

**Describe the results you expected:**
container created as normal without error

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.9.2-2.fc29.x86_64
```

**Output of `buildah version`:**

```
Version:         1.9.2
Go Version:      go1.11.12
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 5.1.16-202.fc29.x86_64 #1 SMP Fri Jul 5 13:34:31 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ cat ~/.config/containers/storage.conf 
[storage]
  driver = "overlay"
  runroot = "/tmp/1000"
  graphroot = "/home/user/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    remap-user = ""
    remap-group = ""
    ostree_repo = ""
    skip_mount_home = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""
```

**Comment by rhatdan** [comment]
The problem is you are not allowed to mount overlay mounts when not running as root.
@giuseppe Could we make this work with fuse-overlay mount?

**Comment by giuseppe** [comment]
yes, I think we could use fuse-overlayfs here to mount the overlay when running in rootless mode

**Comment by giuseppe** [comment]
I've opened a PR here: https://github.com/containers/buildah/pull/1743
