### ISSUE TITLE
pushing to a registry has `//` prefix

### ISSUE THREAD

**Issue by vrothberg** [containers/buildah#1742]
`StringWithinTransport()` from docker is prefixed with `//`. It must have been like this for a long time but I just realized it now. I would love to not print the prefix as Podman does.

```
Successfully pushed //localhost:5000/test:image@sha256:34384895c5fee4805650509e460891bec04571290f73509c08a8fa47aaae4219 
```

**Comment by rhatdan** [comment]
@QiWang19 PTAL
