### ISSUE TITLE
RFE: Support array format for config --cmd

### ISSUE THREAD

**Issue by computator** [containers/buildah#1746]
`buildah config` does not support the more precise array format for `--cmd` that it does for `entrypoint`, however both [docker](https://docs.docker.com/engine/reference/builder/#cmd) and the OCI [spec](https://github.com/opencontainers/image-spec/blob/master/config.md) support, and even encourage the more explicit array syntax. It would be nice if we could use all the various format combinations for both `--cmd` and for `--entrypoint`.

**Comment by TomSweeneyRedHat** [comment]
@computator thanks for the issue.  Just to make sure we're on the same page, can you expound a bit with an example or two please?

**Comment by computator** [comment]
String format leaves word splitting up to buildah and works with both `--entrypoint` and `--cmd`:
- `--entrypoint /entrypoint.sh`
- `--entrypoint '/entrypoint.sh arg1 "arg two"'`

The more precise array syntax does not do word splitting, instead using the parameters exactly as specified. This format works with both `CMD` and `ENTRYPOINT` in Dockerfiles but buildah only supports it for `--entrypoint`:
- `--entrypoint '[ "/entrypoint.sh" ]'`
- `--entrypoint '[ "/entrypoint.sh", "arg1", "arg two" ]'`

In addition to providing more precision, the array format for `--cmd` potentially has other ramifications. From the Docker `CMD` docs:
> Note: If CMD is used to provide default arguments for the ENTRYPOINT instruction, both the CMD and ENTRYPOINT instructions should be specified with the JSON array format.
>
>Note: The exec form is parsed as a JSON array, which means that you must use double-quotes (“) around words not single-quotes (‘).
>
>Note: Unlike the shell form, the exec form does not invoke a command shell. This means that normal shell processing does not happen. For example, `CMD [ "echo", "$HOME" ]` will not do variable substitution on $HOME. If you want shell processing then either use the shell form or execute a shell directly, for example: `CMD [ "sh", "-c", "echo $HOME" ]`. When using the exec form and executing a shell directly, as in the case for the shell form, it is the shell that is doing the environment variable expansion, not docker.

Entrypoint in particular has extra ramifications based on the format: https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Wasn't this just fixed in libpod?  Can we back port the fix from their or better yet share the code?

**Comment by TomSweeneyRedHat** [comment]
@computator thanks a bunch for the very thorough follow up.
@rhatdan I don't recall that this was fixed in libpod recently, but so many PR's as of late it could well have been.

**Comment by computator** [comment]
I just ran into this again and thought I would check to see if there was any news on the possible backport, or if there was any other news.

**Comment by TomSweeneyRedHat** [comment]
@computator I'm afraid no further news, this ones admitedly been suffering some bit rot.

**Comment by rhatdan** [comment]
@ashley-cui PTAL, I am not sure if this is fixed or not.

**Comment by TerraTech** [comment]
I just hit this tonight while converting a Dockerfile into buildah command script.

Does buildah repo have a 30-day nag bot?

**Comment by rhatdan** [comment]
Nope, but we have one for Podman, would be nice to get one here.

**Comment by rhatdan** [comment]
@umohnani8 PTAL
@vrothberg Since you setup the nag bot for Podman could you take a look at doing one for Buildah?

**Comment by vrothberg** [comment]
Added to my list

**Comment by TerraTech** [comment]
@vrothberg As an aside, does **Skopeo** have one too?  This would cover the flagship core trio of base tools for working with podman et al.

**Comment by vrothberg** [comment]
> @umohnani8 PTAL
> @vrothberg Since you setup the nag bot for Podman could you take a look at doing one for Buildah?

https://github.com/containers/buildah/pull/3003

**Comment by vrothberg** [comment]
> @vrothberg As an aside, does **Skopeo** have one too? This would cover the flagship core trio of base tools for working with podman et al.

https://github.com/containers/skopeo/pull/1194

**Comment by umohnani8** [comment]
Looks like @rhatdan fixed this a few months ago https://github.com/containers/buildah/commit/154417fe74a3be9c8cf82ed4b076384d208df678.
@TerraTech please check if you are still hitting the issue in buildah 1.18 or later and reopen if so.
