### ISSUE TITLE
Feature request: `buildah unshare` is a redundant command and should be removed

### ISSUE THREAD

**Issue by hholst80** [containers/buildah#1750]
The `buildah unshare` command is redundant and should probably be deprecated from the CLI UI.

The `unshare` command is part of the `util-linux` package and is available from https://www.kernel.org/pub/linux/utils/util-linux/. It is indeed included in most if not all major Linux distributions.

![Perfection](https://i.kinja-img.com/gawker-media/image/upload/185xbqdcr7fgmjpg.jpg)

**Comment by hholst80** [comment]
An ugly workaround appears also by doing so. The use of `BUILDAH_ISOLATION=rootless` to detect if the tool should be running as root and read /etc/.. for config, or if we should read from $HOME/.config/... I have another bug report open about that on podman.

**Comment by hholst80** [comment]
I think that this also exposes that the rootless configuration indeed does not work as intended.

Setting these environment variables are clearly a workaround to a problem with the configuration

```
BUILDAH_ISOLATION=rootless
_CONTAINERS_ROOTLESS_GID=1001
_CONTAINERS_ROOTLESS_UID=1001
_CONTAINERS_USERNS_CONFIGURED=done
```

**Comment by rhatdan** [comment]
@hholst80 why do you think buildah unshare is redundant?  It is quite helpful in us debugging issues when users do not have their user namespace setup properly.  Also we use it for demonstrating user namespace and how it works. Lastly we are starting to see users playing around with user namespace.

In the next version of buildah unshare we have added a --mount $CONTAINERID which allows users to experiment around the container mount point and create content in rootless environments via scripts.
```
  buildah unshare --mount containerID sh -c 'cat ${containerID}/etc/os-release'
```

**Comment by rhatdan** [comment]
@giuseppe FYI

**Comment by giuseppe** [comment]
Un share doesn't support multiple IDs assigned into the user name space, in facts you can get just your user mapped to root, or write the IDs map separately so it is not a replacement for `buildah unshare`.

**Comment by rhatdan** [comment]
Right unshare does not understnad /etc/subuid and /etc/subgid.
