### ISSUE TITLE
gofmt module changes needed

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1753]
Go module changes are needed.  Buildah should emulate the changes done in https://github.com/cri-o/cri-o/pull/2682/files

**Comment by TomSweeneyRedHat** [comment]
FYI @vrothberg

**Comment by vrothberg** [comment]
:+1:

**Comment by saschagrunert** [comment]
I guess this issue can be closed, right @TomSweeneyRedHat ?

**Comment by rhatdan** [comment]
I believe so.

**Comment by TomSweeneyRedHat** [comment]
ditto what @rhatdan said, thx again @saschagrunert
