### ISSUE TITLE
Binary for buildah

### ISSUE THREAD

**Issue by theexplorist** [containers/buildah#1755]
I need binary for buildah. So any pointers about it? I see buildah does not provides it.

**Comment by TomSweeneyRedHat** [comment]
Would a container image suffice?  If so quay.io/buildah:stable, quay.io/buildah:upstream, quay.io/buildah:stable

**Comment by rhatdan** [comment]
What distribution do you want it on?

**Comment by theexplorist** [comment]
I use Ubuntu(Bionic Beaver). I am new in this container business, so if binaries are available at quay.io, kindly give me some pointers regarding it after pulling the image.
Thank you.

**Comment by vrothberg** [comment]
You can install Buildah on Ubuntu via a ppa as explained in the docs: https://github.com/containers/buildah/blob/master/install.md#ubuntu

**Comment by theexplorist** [comment]
So I think I will get binary in usr/local/bin after installation!

**Comment by rhatdan** [comment]
@theexplorist The one on quay.io is buildah within a container image, so you could run this buildah via Podman or Docker.
Most likely the one from the PPA is what you were after.

**Comment by theexplorist** [comment]
@rhatdan  Is it possible to download and extract the tar file and extract the binary by compiling it?

**Comment by vrothberg** [comment]
@theexplorist, yes. You can find the details in the docs: https://github.com/containers/buildah/blob/master/install.md#building-from-scratch

**Comment by theexplorist** [comment]
@vrothberg  the ppa installs the latest dev versions, are those dev versions stable? If not I think ppa should only provide the stable buildah and runc versions.

**Comment by vrothberg** [comment]
@lsm5 will know what's going on with the Ubuntu packages.

**Comment by lsm5** [comment]
@theexplorist the ppa will currently get you buildah 1.10.1-1~ubuntu18.04~ppa1 which is not dev. The only dev versions are for cri-o which are built using the release-1.x branches which AFAIK are considered stable for use.
