### ISSUE TITLE
Question: Logging in to OpenShift Internal Registry Using buildah push --creds with Service Account

### ISSUE THREAD

**Issue by danielhelfand** [containers/buildah#1757]
I am trying to push an image built by buildah to an OpenShift internal registry using a `buildah push` with the `--creds` option for authentication. I am using a service account and am trying the following combination to log into the internal registry: `default:$(oc whoami -t)`.

`oc whoami -t` returns the service account token for authentication and `default` is traditionally how to specify a username in the event you are using a token for authentication.

I can successfully login with podman using the credentials just mentioned, but I get the following error when using `buildah push` as described above:

```
error pushing image "image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/spring-petcl
inic" to "docker://image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/spring-petclinic": error copying layers
and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/
lib/shared,overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev,metacopy=on]image-registry.openshift-image-regi
stry.svc:5000/pipelines-tutorial/spring-petclinic:latest" to "docker://image-registry.openshift-image-registry.svc:5000/pipelin
es-tutorial/spring-petclinic:latest": Error trying to reuse blob sha256:aae092d5556503430e83c6676c82a20d90f5fdf4f2b02389d21be3d
0b8175f63 at destination: unable to retrieve auth token: invalid username/password
```

**Steps to reproduce the issue:**
I am using an OpenShift Pipelines (i.e., Tekton) CI/CD pipeline that runs each task step of the pipeline in its own container on a pod. 

The step of a task I am using is [here](https://github.com/openshift-labs/lab-openshift-pipelines-with-tekton/blob/master/code/tektontasks/s2i-java-8-task.yaml#L56). 

I have not pushed up the `--creds` changes yet so that is why it is not currently in the Task definition shown here.

**Describe the results you expected:**

I expect the service account to be properly authenticated and the image to be successfully pushed to the internal registry.

**Output of `buildah version`:**

```
Version:         1.9.0
```

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 I might be misremembering, but this sounds like a bug you worked on recently?
@danielhelfand I see the stable buildah image from quay.io in your yaml, are you running this push command from a container built from that image?

**Comment by danielhelfand** [comment]
@TomSweeneyRedHat You're correct. The image used is found the line above the command [here](https://github.com/openshift-labs/lab-openshift-pipelines-with-tekton/blob/master/code/tektontasks/s2i-java-8-task.yaml#L55) (i.e., `quay.io/buildah/stable`).

**Comment by QiWang19** [comment]
@TomSweeneyRedHat no, haven't seen this bug before. looks like the creds has been checked but it returns http StatusUnauthorized 401

**Comment by danielhelfand** [comment]
@QiWang19 @TomSweeneyRedHat Apologies, I think the issue here was a problem with the registry namespace/permissions assigned to the service account. We were dynamically generating namespaces but weren't taking that into account with the registry name. For permissions, the service account just needed edit access to the repo (i.e., `oc adm policy add-role-to-user edit -z pipeline`). This is a non buildah issue, and thanks for your help!
