### ISSUE TITLE
Building images with labels can be slow

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1764]
Moving https://github.com/containers/libpod/issues/3303 to this issue.

**Comment by TomSweeneyRedHat** [comment]
@bmaupin FYI, moving the issue here.

**Comment by rhatdan** [comment]
I ran a tests on this with buildah in master, and I see it taking 
real	0m2.027s

Docker is taking
real	0m4.020s

podman build --layers=false --no-cache /tmp
real	0m5.315s

time podman build --layers=false --no-cache /tmp
real	0m3.960s

@nalind Is this creating an image when we specify --layers=true?

**Comment by nalind** [comment]
It has to create a new image record in order to store an updated configuration blob with updated label information.  Preparing a working container for the next instruction, in case we don't get a cache hit, is probably costing us when using vfs.

**Comment by TomSweeneyRedHat** [comment]
We've cut the time by almost 2/3'rds, but still not as much as Docker.
```
First run:
real	0m22.173s
user	0m0.075s
sys	0m0.072s

Second Run:
real	0m18.363s
user	0m0.075s
sys	0m0.037s
```
