### ISSUE TITLE
Feature: add "--squash-older-than DATE" argument to buildah commit

### ISSUE THREAD

**Issue by TristanCacqueray** [containers/buildah#1778]
Buildah commit currently only support a `--squash` argument to produce an image with one layer. This issue is about a feature to implement a `--squash-older-than AGE` or `--squash-max-layers N` argument to produce an image that only keeps recent layers.

The use-case is for using an image similarly to a regular fedora workstation runtime:

Initialization:
```bash
ctx = $(buildah from fedora)
buildah commit $ctx local-fedora
buildah delete $ctx
```

Package installation: `layer(intermediate-base)`
```bash
ctx = $(buildah from local-fedora)
buildah run $ctx dnf install -y firefox
buildah commit $ctx local-fedora
buildah delete $ctx
```

Then periodically update the image: `layer(intermediate-base)` + (N-1) * `layer(update)` + `layer(update)`
```bash
ctx = $(buildah from local-fedora)
buildah run $ctx dnf update -y
buildah commit $ctx local-fedora:$(date "+%Y-%m-%d")
buildah delete $ctx
buildah tag local-fedora:$(date "+%Y-%m-%d") local-fedora:latest
```

The issue with that approach is that the layers are never removed and passing a certain numbers, things start to get slower and slower. Using a `--squash-older-than` argument would enable a more efficient image while keeping the regular dnf update in-place workflow.

Another solution discussed on IRC is that the `layer(update)` is never re-used and instead produced each time from `layer(intermediate-base)`. This can be optimized using `-v /var/cache/dnf:/var/cache/dnf` when updating.
Though there is a performance cost because daily update may update the same package over and over until the `layer(intermediate-base)` is rebuilt cleanly

**Comment by rhatdan** [comment]
@nalind @vrothberg @TomSweeneyRedHat WDYT?

**Comment by TomSweeneyRedHat** [comment]
I like the thought, I'm just not sure how well squishing some but not all layers will work code wise.

**Comment by TristanCacqueray** [comment]
@Hendrik-H yes, this is also mentioned in https://github.com/containers/buildah/pull/1790#issuecomment-534579845

**Comment by rhatdan** [comment]
Ok lets see about moving forward on this.

**Comment by rhatdan** [comment]
Is anyone going to work on this in the community, if not I will close in a month.
