### ISSUE TITLE
`buildah commit --squash` is using /tmp to build images

### ISSUE THREAD

**Issue by oblitum** [containers/buildah#1815]
**Description**

I have a larger than `/tmp` image that I want to apply `buildah commit --squash` to attempt creating a squashed duplicate, but the command is using `/tmp` for the task, and there's no space left for it (which can be [circumvented by resizing](https://github.com/containers/libpod/issues/3871#issuecomment-524098810) or remounting `/tmp`, e.g. `sudo mount -o remount,size=12G /tmp`).

**Steps to reproduce the issue:**
1. `buildah from larger-than-tmp-image`
2. `buildah commit --squash`

**Describe the results you received:**

```
[I] ➜ buildah commit --squash archlinux-working-container archlinux2
ERRO[0119] Can't add file /home/francisco/.local/share/containers/storage/overlay/693ecb17fb10858eaea0aa7eb529c6f1a12bd8f9d991de7623f5c51371679da0/merged/usr/share/texmf-dist/fonts/tfm/adobe/sourceserifpro/SourceSerifPro-SemiboldIt-tosf-t1.tfm to tar: io: read/write on closed pipe
ERRO[0119] Can't close tar writer: io: read/write on closed pipe
error committing container "archlinux-working-container" to "archlinux2": error copying layers and metadata for container "d3a78dc6abc9fbb00bb720dfe6c5320b469f88916e93240c95269412d4e920fc": Error initializing source containers-storage:archlinux-working-container: error storing container "d3a78dc6abc9fbb00bb720dfe6c5320b469f88916e93240c95269412d4e920fc" to file: write /tmp/buildah262364539/layer: no space left on device
ERRO[0120] exit status 1
```

**Describe the results you expected:**

I'm fine that it uses `/tmp` by default, not sure whether it's actually good idea though. I'd like to at least have/know an option to set a different location. Or the command could be smart enough to check the image to be committed is larger than the default `/tmp` mount point, so it should use another one or cancel before trying.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
[I] ➜ pacman -Qi buildah
Name            : buildah
Version         : 1.10.1-1
Description     : A tool which facilitates building OCI images
Architecture    : x86_64
URL             : https://github.com/containers/buildah
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : ostree  runc  skopeo
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 24.99 MiB
Packager        : Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Sat 17 Aug 2019 04:40:34 PM -03
Install Date    : Mon 19 Aug 2019 10:17:08 PM -03
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Output of `buildah version`:**

```
[I] ➜ buildah version
Version:         1.10.1
Go Version:      go1.12.8
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.1
Git Commit:      8c1c2c58
Built:           Sat Aug 17 16:41:23 2019
OS/Arch:         linux/amd64
```

**Output of `buildah info`:**

```
[I] ➜ buildah info
{
    "host": {
        "Distribution": {
            "distribution": "arch",
            "version": "unknown"
        },
        "MemTotal": 16747802624,
        "MenFree": 10541654016,
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 8,
        "hostname": "leibniz",
        "kernel": "5.2.9-arch1-1-ARCH",
        "os": "linux",
        "rootless": true,
        "uptime": "1h 9m 40.36s (Approximately 0.04 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay.mount_program=/usr/bin/fuse-overlayfs"
        ],
        "GraphRoot": "/home/francisco/.local/share/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 3
        },
        "RunRoot": "/run/user/1000"
    }
}
```

**Output of `cat /etc/*release`:**

```
[I] ➜ cat /etc/*release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**Output of `uname -a`:**

```
[I] ➜ uname -a
Linux leibniz 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[I] ➜ cat ~/.config/containers/storage.conf
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/francisco/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    ignore_chown_errors = ""
    remap-user = ""
    remap-group = ""
    ostree_repo = ""
    skip_mount_home = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""
```

**Related issues:** [containers/libpod#3871](https://github.com/containers/libpod/issues/3871#issuecomment-523974696), #1806, #1810.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Can we move this to /var/tmp?  Or allow the user to specify the location?

**Comment by TomSweeneyRedHat** [comment]
@oblitum  can you define the environment variable TMPDIR to /var/tmp or a larger area with something like:
`export TMPDIR=/var/tmp`

and then rerun the commit?   

I took a very quick look at the code and we could potentially add an argument to squash or come up with another option for commit to specify the tmpdir to use, but we'd have to pass that info down to c/storage and then potentially a number of other places that make calls down there.

**Comment by oblitum** [comment]
Hi @TomSweeneyRedHat.

Yes, I just test with a simple archlinux/base image from DockerHub and the following makes to command use a local directory instead of `/tmp`:

```
TMPDIR=$PWD/tmp buildah commit --squash base-working-container base2
```

**Comment by oblitum** [comment]
Feel free to close the issue. I'm not sure whether a flag is needed of the `TMPDIR` variable should be documented for that task.

**Comment by TomSweeneyRedHat** [comment]
@oblitum glad to hear that worked and thanks for the update!  I'm going to keep this issue open for the moment to remind myself to think about a doc solution somewhere.

**Comment by sergeiwaigant** [comment]
Hi all,
I am still facing this issue with Buildah.

```
error copying layers and metadata for container "874ca4d3d2a1f4ed4dd1a749432ce3afd61724e963933c497e12e017218a9139": Error writing blob: error storing blob to file "/var/tmp/storage335083697/1": write /var/tmp/storage335083697/1: no space left on device
```

Even with `export TMPDIR=/mnt/sdb/` or giving TMPDIR right before buildah command it is still using /var/tmp

Regards
Sergei

**Comment by TomSweeneyRedHat** [comment]
@sergeiwaigant which version of Buildah are you using?

**Comment by sergeiwaigant** [comment]
> @sergeiwaigant which version of Buildah are you using?
Latest provided by RedHat since we are on RHEL 7.7

```
buildah --version
buildah version 1.9.0 (image-spec 1.0.0, runtime-spec 1.0.0)

```

**Comment by rhatdan** [comment]
This was being worked on in containers/image @mtrmac @vrothberg Has the fix been merged there?

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/747 was merged; up to Buildah to set the `SystemContext` option as it wants.

(I don’t think `TMPDIR`, which points to a tmpfs by default, is a good default, but IIRC using that would be consistent with the rest of Buildah, e.g. as discussed here.)

**Comment by mtrmac** [comment]
> (I don’t think `TMPDIR`, which points to a tmpfs by default …

Or actually `TMPDIR` tends to be unset by default? To be more precise, defaulting to `/tmp` is the problem on systemd Linuxes at least, regardless of mechanism.

**Comment by TomSweeneyRedHat** [comment]
As we now use TMPDIR and set it to /var/tmp if the user had not via #2022, I'm going to close this issue.
