### ISSUE TITLE
Missing libdevmapper dependency in apt package

### ISSUE THREAD

**Issue by matpen** [containers/buildah#1817]
**Description**

Installing buildah on Ubuntu via PPA does not work, because one library dependency does not get installed.

**Steps to reproduce the issue:**
1. We can reproduce the error in a container with the following script:
```bash
container="$(buildah from docker.io/library/ubuntu:18.04)"
buildah run "$container" -- bash -e <<- EOF
    apt-get update -qq
    apt-get install -yqq software-properties-common uidmap
    add-apt-repository -y ppa:projectatomic/ppa
    apt-get update -qq
    apt-get install -yqq buildah slirp4netns

    buildah version
EOF
```
Which fails with message
```
buildah: error while loading shared libraries: libdevmapper.so.1.02.1: cannot open shared object file: No such file or directory
```

2. The problem can be fixed by installing `libdevmapper` manually using
```
apt-get install -yqq libdevmapper1.02.1
```

**Describe the results you received:**

After installation of the package `buildah` does not work: one dependency must be manually installed.

**Describe the results you expected:**

The apt package should automatically install all required dependencies.

**Output of `rpm -q buildah` or `apt list buildah`:**

Note: both host and container are Ubuntu 18.04 and run the same version of buildah.
```
buildah/bionic,now 1.10.1-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Output of `buildah version`:**

Note: both host and container are Ubuntu 18.04 and run the same version of buildah.
```
Version:         1.10.1
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Aug  8 22:29:48 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

n/a

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux matteo-laptop 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/home/matteo/MyData/data/podman/root"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by matpen** [comment]
I just found that the package also does not install `runc`: since the two issues are related, I thought to add this information to this already open issue. Reproduce with:

```bash
container="$(buildah from docker.io/library/ubuntu:18.04)"
buildah run "$container" -- bash -e <<- EOF
    apt-get update -qq
    apt-get install -yqq software-properties-common uidmap
    add-apt-repository -y ppa:projectatomic/ppa
    apt-get update -qq
    apt-get install -yqq buildah slirp4netns libdevmapper1.02.1 # Note the fix discussed earlier

    buildah version # Success: 1.10.1

    container="$(buildah from docker.io/library/ubuntu:18.04)"
    buildah run "$container" whoami
EOF
```

which fails with message
```
error running container: error creating container for [/usr/bin/whoami]: : exec: "runc": executable file not found in $PATH
```

workaround: manually install `runc`
```
apt-get -yqq install runc
```

**Comment by TomSweeneyRedHat** [comment]
@lsm5 PTAL

**Comment by rhatdan** [comment]
We should not be building with libdevmapper support.  This should be omitted.

**Comment by AndydeCleyre** [comment]
@rhatdan Please note that as-is, when installing `buildah` on Ubuntu Bionic as per the instructions and PPA, one cannot even run `buildah --help`, let alone `buildah from`. The package is broken.

And I'm not sure if you caught the `runc` note in this discussion -- the docs specifically say installing via `apt-get` will bring in `runc`, but that's untrue.

This issue is especially relevant as GitHub rolls out its Actions feature, which, for Linux, offers only Ubuntu 16.04 and 18.04, and no other distros. Once this issue is properly resolved (and not before), I recommend a team member to open an [issue here](https://github.com/actions/virtual-environments/issues) requesting that `buildah` be included in as many of their VMs as `buildah` supports.

**Comment by lsm5** [comment]
I got distracted on this one. @AndydeCleyre @matpen does this issue persist with the latest buildah / newer Ubuntu?

**Comment by caemate** [comment]
@lsm5 I just re-tested on Ubuntu 18.04 LTS with the [original instructions](https://github.com/containers/buildah/issues/1817#issue-484589556) and got the exact same error.

Furthermore, I noticed that the buildah version in the [PPA](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa) is `1.10.1`, uploaded one year ago, and which has not changed since this issue was open.

**Comment by matpen** [comment]
@lsm5 I just re-tested on Ubuntu 18.04 LTS with the [original instructions](https://github.com/containers/buildah/issues/1817#issue-484589556) and got the exact same error.

Furthermore, I noticed that the buildah version in the [PPA](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa) is `1.10.1`, uploaded one year ago, and which has not changed since this issue was open.

**Comment by lsm5** [comment]
@matpen So, the PPA is dead. I guess what I meant was do you see this issue with the latest buildah from OBS? If you do, then I guess we should re-include the devmapper dependency. @rhatdan wdyt?

**Comment by rhatdan** [comment]
We should not be building with devmapper support.
