### ISSUE TITLE
buildah bud step fails on openshift as root user is expected

### ISSUE THREAD

**Issue by cmoulliard** [containers/buildah#1835]
## Issue

When I use the latest buildah image, I cant perform a s2i build using the command
```
Image:      "quay.io/buildah/stable",
WorkingDir: "/sources",
Command: []string{
	"buildah",
},
Args: []string{
	"bud",
	"--tls-verify=${inputs.params.verifyTLS}",
	"--layers",
	"-f",
	"/sources/Dockerfile.gen",
	"-t",
	"${outputs.resources.image.url}",
	"."},
VolumeMounts: []corev1.VolumeMount{
	{
		Name:      "libcontainers",
		MountPath: "/var/lib/containers",
	},
	{
		Name:      "generatedsources",
		MountPath: "/sources",
	},
},
SecurityContext: &corev1.SecurityContext{
	Privileged: util.NewTrue(),
},
```

as we will get this error
```
error building at STEP "COPY upload/src /tmp/src": error determining run uid: user: unknown user error looking up user "root"
```

**Remark**: This problem don't exist using image version: v1.9.0

**Comment by TomSweeneyRedHat** [comment]
@cmoulliard I've only played with s2i a few times.  Can you share the actual command that you invoked?  I think there may have been a bad cut/paste in your description as I'm not seeing as many starting braces `{` as ending braces `}` and think your example command and some of your xml/yaml was inadvertently not included.

**Comment by cmoulliard** [comment]
Here is the command executed from the Tekton Task definition within the initcontainer
using the image : `quay.io/buildah/stable`

```
buildah bud --tls-verify=false --layers -f /sources/Dockerfile.gen -t docker-registry.default.svc:5000/test/fruit-backend-sb .
```

**Comment by TomSweeneyRedHat** [comment]
@cmoulliard, I'm probably dealing with late Friday afternoon brain, but I'm not able to make your example command work?  Is Dockefile.gen the file that you copied in the description above?  Did you run that command inside a container based on the stable image?  Can you also share the command(s) you used to run that container if applicable?

**Comment by cmoulliard** [comment]
> Is Dockefile.gen the file that you copied in the description above?

No. Here is the dockerfile which is generated by Tekton's task

```
sh-5.0# cat /sources/Dockerfile.gen
FROM quay.io/halkyonio/spring-boot-maven-s2i
LABEL "io.openshift.s2i.build.image"="quay.io/halkyonio/spring-boot-maven-s2i" \
      "io.openshift.s2i.build.source-location"="/workspace/git/demo/"
ENV MAVEN_ARGS_APPEND="-pl fruit-backend-sb" \
    MAVEN_S2I_ARTIFACT_DIRS="fruit-backend-sb/target" \
    S2I_SOURCE_DEPLOYMENTS_FILTER="*.jar"
USER root
# Copying in source code
COPY upload/src /tmp/src
# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/src
USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN /usr/local/s2i/assemble
# Run script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
CMD /usr/local/s2i/run
```

**Comment by cmoulliard** [comment]
> Can you also share the command(s) you used to run that container if applicable?

Here is the pod definition created by Tekton which contains the command executed to call `buildah bud`

https://gist.github.com/cmoulliard/58b668e65afc6fbaeeaab7cef6379303#file-gistfile1-txt-L162-L209

**Comment by rhatdan** [comment]
I don't believe we have this issue any longer, reopen if I am mistaken.

**Comment by KarstenSiemer** [comment]
Still happens as far as I can see
```
❯ docker run -it -u 1001:0 quay.io/containers/buildah:latest buildah manifest create test:1.1.1

ERRO error determining current user: user: unknown userid 1001
``

**Comment by UmutAlihan** [comment]
similar issue here any solutions?

```
09:53:32  STEP 2: WORKDIR ${APP_DIR_HOME}
09:53:32  STEP 3: RUN 	chgrp -R 0 $APP_DIR_HOME && chmod -R g+rx $APP_DIR_HOME
09:53:32  error building at STEP "RUN chgrp -R 0 $APP_DIR_HOME && chmod -R g+rx $APP_DIR_HOME": error determining run uid: user: unknown user error looking up user "root"
```
