### ISSUE TITLE
Use `Buildah` in Ubuntu 16

### ISSUE THREAD

**Issue by atefBB** [containers/buildah#1837]
**Description**

I've installed `buildah` in `Ubuntu Linux 16.04.3` following the `installation` instructions in the docs, when I run `buildah images` (e.g) I got the error: `kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver` !

**Steps to reproduce the issue:**
1. Install buildah in ubuntu 16
2. Run any buildah command

**Describe the results you received:**
The result: `kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver`.

**Describe the results you expected:**
Success !

**Output of `apt list buildah`:**

```
Listing... Done
buildah/xenial,now 1.10.1-1~ubuntu16.04~ppa1 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.10.1
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Sat Aug 10 21:04:44 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

I've not installed podman !

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Output of `uname -a`:**

```
Linux vps*****.inmotionhosting.com 4.4.0-042stab138.1 #1 SMP Wed May 15 09:33:10 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
@lsm5 any thoughts?

**Comment by lsm5** [comment]
@nalind @rhatdan overlay driver is dependent on newer kernel, yes? What's the right driver for older ones?

**Comment by rhatdan** [comment]
I would use the VFS driver,  BTRFS and XFS might work.  But we have not done a lot of testing on this.

**Comment by lsm5** [comment]
@atefBB I can send you a one-off deb file with this change if you'd be willing to test it

**Comment by atefBB** [comment]
@lsm5 Yes ! I can test it.

**Comment by lsm5** [comment]
> I would use the VFS driver, BTRFS and XFS might work. But we have not done a lot of testing on this.

@rhatdan so is it just `driver = "vfs"` in this case?

**Comment by lsm5** [comment]
@atefBB can you try installing the containers-common deb file at https://lsm5.fedorapeople.org/containers-common_0.1.39-1~ubuntu16.04~ppa2_all.deb . That should install a new storage.conf with `driver = "vfs"` ... or better still, please make the change manually in your storage.conf first and check if that works

**Comment by rhatdan** [comment]
export STORAGE_DRIVER=vfs

Or --storage-driver vfs

**Comment by atefBB** [comment]
@lsm5 I'll try it !

**Comment by lsm5** [comment]
@atefBB any luck?

**Comment by atefBB** [comment]
I got this:
<pre>~# dpkg -i containers-common_0.1.39-1~ubuntu16.04~ppa2_all.deb 
=> Selecting previously unselected package containers-common.
(Reading database ... 133004 files and directories currently installed.)
Preparing to unpack containers-common_0.1.39-1~ubuntu16.04~ppa2_all.deb ...
Unpacking containers-common (0.1.39-1~ubuntu16.04~ppa2) ...
dpkg: dependency problems prevent configuration of containers-common:
 containers-common depends on containers-golang; however:
  Package containers-golang is not installed.
 containers-common depends on containers-image (>= 3.0.0); however:
  Package containers-image is not installed.

dpkg: error processing package containers-common (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 containers-common</pre>

**Comment by TomSweeneyRedHat** [comment]
@atefBB I know @lsm5 has been doing a lot of work in the packaging department in terms of overlayfs.  Is this still an issue with the latest versions of Buildah?

**Comment by lsm5** [comment]
> @atefBB I know @lsm5 has been doing a lot of work in the packaging department in terms of overlayfs. Is this still an issue with the latest versions of Buildah?

Getting our tools to build on 16.04 on OBS is a huge pain because of a very old golang. I'm hoping people can move to a newer Ubuntu version (18.04+), and a new LTS should be coming out soon as well.

**Comment by lsm5** [comment]
@atefBB have you had the chance to move to a newer Ubuntu? Can we close this?

**Comment by lsm5** [comment]
closing. @atefBB please re-open if need be.
