### ISSUE TITLE
Proposition: Support a more open Containerfile in addition to Dockerfile

### ISSUE THREAD

**Issue by aric49** [containers/buildah#1853]
Hi everyone,

Not sure if this issue is a good one for `buildah` or for podman proper repo. Please let me know if I should open this in libpod instead. 

In the spirit of removing dependencies on Docker and fostering a spirit of more a open environment for building OCI-compatible container images, have we given any thought to automatically supporting other file names for container build instructions other than `Dockerfile`?  If not, I would suggest using `Containerfile` as a recognized file name for building images.   I gave thought to `Podfile` or `Podmanfile`, but I am tempted to think that would ultimately create the same confusion among users and tie the containers back to single project. I wouldn't want users thinking that they couldn't build a Podmanfile, if they aren't using Podman, or to think we are creating a new format for container images.  I think supporting both `Dockerfile` and `Containerfile` file names may  be a step in the right direction for backward compatibility with Docker-based projects as well as be good to seperate the concept of OCI container images away from Docker and make it more general. 

Just my two cents. Thoughts?

**Comment by afbjorklund** [comment]
Sounds like a good idea, I also like the "Containerfile" - rather than something like Podmanfile.

Currently using a Makefile to build it, where the `$(DOCKER)` can be replaced with `sudo podman`.

```make
all: build

build:
	$(DOCKER) build -t $(IMAGE_NAME):$(IMAGE_TAG) .
```

Renaming the "Dockerfile" would be a natural fit for this...

Wonder what a better name for the make variable would be ?

**Comment by aric49** [comment]
@afbjorklund  -- since it's a variable,  could  it be `CONTAINER_BUILD_INTERFACE`  or just `CONTAINER_INTERFACE` ?

**Comment by afbjorklund** [comment]
> @afbjorklund -- since it's a variable, could it be `CONTAINER_BUILD_INTERFACE` or just `CONTAINER_INTERFACE` ?

Well, those are better than `$(CONTAINER)`. But maybe I will just go with BUILD instead.

i.e. put the abstraction at "docker build" rather than just docker, with all the connotations.

**Comment by aric49** [comment]
I'm also going to open an issue, potentially a PR on podman-compose to try and get a similar functionality there:  `container-compose.yml`

**Comment by TomSweeneyRedHat** [comment]
@aric49 @afbjorklund  FYI https://github.com/containers/buildah/pull/1860

**Comment by aric49** [comment]
I also opened a PR against `podman-compose`:  https://github.com/containers/podman-compose/pull/46

**Comment by TomSweeneyRedHat** [comment]
Closing with #1860
