### ISSUE TITLE
Question about Copying BLOB

### ISSUE THREAD

**Issue by cmoulliard** [containers/buildah#1863]
## Question

If we use the following command within a k8s's pod created on ocp where there is an internal docker registry  :
```
buildah bud --tls-verify=false --layers=true -f /sources/Dockerfile.gen -t my_image .					
```
then, buildah will first copy several BLOBs as showed [hereafter](https://gist.github.com/cmoulliard/997e6c54c9d65706fa6bb814db005d01#file-gistfile1-txt-L1-L48)
```
STEP 1: FROM quay.io/halkyonio/spring-boot-maven AS build
Getting image source signatures
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
...
Copying blob sha256:ff8ac3e49cc3563f74393fad808af6ac408d93051a0550dd2f1b9ed40c3c590d
Copying blob sha256:0844417df80ada5069fbd0d6171ec342b5516bc62779a18ea6a803b964b44fa6
Copying blob sha256:5c7a60c41bcb70cf187aac9905a77021fcf59d56b35b3459ef31beca80a7e940
Writing manifest to image destination
Storing signatures
```
As such a process could take time, slow down the s2i build process, I would like to ask you what we could do to avoid : 
- to have to copy so many BLOBs, 
- to write the manifests to the destination image and 
- to store signatures to **speed** the build process ?

FYI: here is the dockerfile [processed](https://gist.github.com/cmoulliard/eb808de806b1c04929fbe870719447ed)

**Comment by rhatdan** [comment]
Does this help?
https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/

**Comment by cmoulliard** [comment]
> Does this help?

I think so. I will have a look. Many thanks
