### ISSUE TITLE
allow a per-user registries.conf option

### ISSUE THREAD

**Issue by elerch** [containers/buildah#1865]
I've been using podman to run containers without an /etc/containers directory at all. This is made possible in part due to @giuseppe's change to allow a per-user registries.conf option (https://github.com/containers/libpod/commit/c737d01937fc3644bdabbe50df71a455aa3b1f8b). This works great for ``podman run``, but ``podman build`` then has a different (unexpected) behavior of only looking for configuration in /etc/containers.

For example, without a /etc/containers directory I can happily execute ``podman run node:10.16.3-buster-slim``, but ``podman build .`` with a Dockerfile using the same image in a FROM line will result in:

> Error: error creating build container: (image name "node:10.16.3-buster-slim" is a short name and no search registries are defined in /etc/containers/registries.conf)

I prefer that buildah add $HOME/.config/containers to the search path and match podman's behavior, but in either case, I believe the behavior between podman and buildah should be consistent as podman uses buildah by default.

**Comment by TomSweeneyRedHat** [comment]
@elerch TYVM for raising this issue.  I think you're spot on with this thought.  WDYT @giuseppe ?

**Comment by giuseppe** [comment]
yes, I think we should make sure Buildah follows the same behaviour as Podman and it honors the user file

**Comment by giuseppe** [comment]
I am out of office this week.  If nobody beats me at it, I can take a look at it once I am back

**Comment by kevinlmadison** [comment]
Any updates on this or perhaps a workaround?

**Comment by rhatdan** [comment]
Sorry no one has worked on this, @TomSweeneyRedHat Can you look into this?

**Comment by rhatdan** [comment]
Of course if @kevinlmadison wanted to open a PR, that would be appreciated as well.

**Comment by vrothberg** [comment]
I think this should go into containers/image/pkg/sysregistriesv2 to make it available for all consumers of c/image.

**Comment by rhatdan** [comment]
Makes sense.

**Comment by kevinlmadison** [comment]
Hey guys, forgive me if this is a silly question but I'm looking at this file `vendor/github.com/containers/image/v5/pkg/sysregistriesv2/system_registries_v2.go` and I'm seeing this line:
`var systemRegistriesConfPath = builtinRegistriesConfPath`
before this line:
`const builtinRegistriesConfPath = "/etc/containers/registries.conf"`

it seems like the second line immediately overrides the first thus making this path not override-able. Is my understanding correct on this?

**Comment by vrothberg** [comment]
> Hey guys, forgive me if this is a silly question but I'm looking at this file `vendor/github.com/containers/image/v5/pkg/sysregistriesv2/system_registries_v2.go` and I'm seeing this line:
> `var systemRegistriesConfPath = builtinRegistriesConfPath`
> before this line:
> `const builtinRegistriesConfPath = "/etc/containers/registries.conf"`
> 
> it seems like the second line immediately overrides the first thus making this path not override-able. Is my understanding correct on this?

That's correct. We do this for easier unit testing. I don't think we need to change this part, but the `ConfigPath` function (see https://github.com/containers/image/blob/master/pkg/sysregistriesv2/system_registries_v2.go#L306). There we can add the semantics to set a different path for rootless (unless the SystemContext explicitly overwrites it).

**Comment by rhatdan** [comment]
It should be a failover, try in homedir first and if no file exists, use the system default.

**Comment by kevinlmadison** [comment]
Hey I'm working on this whenever I get free time in case anyone comes here and needs this.

**Comment by rhatdan** [comment]
@QiWang19 I believe this is fixed now, Reopen if I am mistaken.
