### ISSUE TITLE
With Dockerfile ADD .tar.xz reuses cache even when files changed

### ISSUE THREAD

**Issue by shaicoleman** [containers/buildah#1906]
**Description**

Dockerfile ADD command reuses cache even when files have changed

**Steps to reproduce the issue:**
1. On Ubuntu 18.04, install podman 1.6.1 from PPA (Buildah 1.11.2)
2. Create the following `Dockerfile`
```
FROM docker.io/busybox

ADD test.tar.xz /
```
3. Build a test archive, and run podman build
```
$ date>test; tar cJf - test > test.tar.xz; md5sum test.tar.xz
158a9e025b54fe66713a443504821a8a  test.tar.xz
$ sudo podman build --file Dockerfile -t podman-test .
STEP 1: FROM docker.io/busybox
STEP 2: ADD test.tar.xz /
STEP 3: COMMIT podman-test
0f7320b3df37c68a91455477f27ec042b832eb589a44bc98365e85449c92cff5
```
4. Create a new test archive,  run podman build again
```
$ date>test; tar cJf - test > test.tar.xz; md5sum test.tar.xz
cd07d63afd4136c141d49b74f92e1247  test.tar.xz
$ sudo podman build --file Dockerfile -t podman-test .
STEP 1: FROM docker.io/busybox
STEP 2: ADD test.tar.xz /
--> Using cache 2cab1dafa7b9b6bb91760fd2325da32df0d7846e02798739049026d3ba92e2de
STEP 3: COMMIT podman-test
2cab1dafa7b9b6bb91760fd2325da32df0d7846e02798739049026d3ba92e2de
```

**Describe the results you expected:**
It is expected not to reuse the cache if the files have changed.

**Version:**
```
podman/bionic,now 1.6.1-1~ubuntu18.04~ppa3 amd64 [installed]
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
BuildahVersion: 1.11.2
kernel: 5.0.0-31-generic
arch: amd64
runc version 1.0.0-rc8+dev
```

**Comment by TomSweeneyRedHat** [comment]
First reported in https://github.com/containers/libpod/issues/3920.  See that issue for further background information.  We'll track the issue here going forward though.

**Comment by TomSweeneyRedHat** [comment]
@shaicoleman I'm replicating now with upstream and latest.  As you noted it should not cache.  As a work around, you can add the `--no-cache` option to the second build command, that should work as you expect.
```
$ sudo podman build --no-cache --file Dockerfile -t podman-test .
```
In the meantime I'll see if I can figure out why the build process isn't nog

**Comment by edsantiago** [comment]
FWIW this is a regression from podman 1.5.0 (`buildah v1.10.1`, according to podman's `go.mod`). That is: running this reproducer on v1.5.0 will correctly pick up the new tarfile.

Also FWIW I was never able to reproduce https://github.com/containers/libpod/issues/3920 in v1.5.0, no matter what Dockerfile incantations I used.

**Comment by TomSweeneyRedHat** [comment]
@edsantiago do you have cycles to look at this and test?

**Comment by rhatdan** [comment]
I believe this is fixed in current buildah, reopen if I am mistaken

**Comment by seperman** [comment]
I suddenly started having this issue with `podman build`

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by rhatdan** [comment]
Could you try with podman 3.4

**Comment by seperman** [comment]
Ok I'm waiting for 3.4 to appear on https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman
It it takes a few more days, I will go down the pass of building podman locally.
For now I have to delete the previous images when building new images to avoid using caches.
