### ISSUE TITLE
Support a command similar to docker prune

### ISSUE THREAD

**Issue by talonx** [containers/buildah#1912]
**Description**

This is an enhancement request.

docker has an option called image prune which deletes unused images, containers, networks etc. It would be nice to have this in buildah. Running builds often creates many intermediate images which stick around, especially for failed builds. I understand that the purpose of keeping the failed build images is to be able to debug it later. However, while using buildah from tools like ansible-bender, the cause of failure is often readily apparent from the console output and can be resolved without the help of the failed image. Deleting the failed images needs to be done manually, by listing them first and passing them to the buildah rmi command. Having something similar to prune would reduce this effort.

**Steps to reproduce the issue:**
Please see description.

**Describe the results you received:**
Please see description.

**Describe the results you expected:**
Please see description.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/bionic,now 1.10.1-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.10.1
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Fri Aug  9 01:59:48 2019
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64

```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

**Output of `uname -a`:**

```
Linux <snipped> 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
Can you use `podman image prune`?

**Comment by XVilka** [comment]
Related issues are https://github.com/containers/libpod/issues/4410, https://github.com/containers/libpod/issues/4411, https://github.com/containers/libpod/issues/3799

And, I think, this one should be closed.
