### ISSUE TITLE
OpenShift Prow onboarding: Create OWNERS file to use

### ISSUE THREAD

**Issue by cgwalters** [containers/buildah#1915]
This repository currently uses [PAPR](https://github.com/projectatomic/papr/) which is in the process of being decomissioned.

There is no one successor to PAPR; Github has a powerful pluggable API for CI, and you can use multiple.

However, the CoreOS group is [increasingly using OpenShift Prow](https://github.com/coreos/fedora-coreos-tracker/issues/263).

If you wish to use the OpenShift Prow instance, please [create an `OWNERS` file](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md) in this repository to indicate agreement.  

[Here's an example](https://github.com/containers/libpod/blob/master/OWNERS) from this Github organization.

If you do not wish to have this repository onboarded to OpenShift Prow, simply close this issue.

**Comment by jlebon** [comment]
WIP to move towards Cirrus CI in https://github.com/containers/buildah/pull/1848.

**Comment by cgwalters** [comment]
OK, submitted https://github.com/openshift/release/pull/5477

However to really make things work more nicely, I think you want Prow to execute at least one job.  A good start is a simple `make`.  I tend to like having `ci/build.sh` wrapper scripts that can be shared between CI systems.

**Comment by vrothberg** [comment]
Closed by #1926
