### ISSUE TITLE
Publish version 1.11.0 to Ubuntu 18.04 and 19.04 repositories

### ISSUE THREAD

**Issue by Davio** [containers/buildah#1918]
Looking at [https://launchpad.net/~projectatomic/+archive/ubuntu/ppa](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa) it seems version 1.11.0 has only been released for Ubuntu 16.04.

Will Buildah be published for 18.04 and 19.04 as well?

**Comment by lsm5** [comment]
@Davio yes, it will, but some rebase issues in autobuilder. Handling it now..

@TomSweeneyRedHat could you please give me access to assign issues to myself and set labels?

**Comment by rhatdan** [comment]
@lsm5 I think you should be able to do that now.

**Comment by bromaniac** [comment]
Any progress on this?

**Comment by FooBarWidget** [comment]
I would also like to know, would be great if my next project can use Buildah instead of Docker.

**Comment by wwilson** [comment]
Can we get an update on this?

**Comment by TomSweeneyRedHat** [comment]
@lsm5 ping!

**Comment by wwilson** [comment]
It's been ~2 months since _anything_ was published to the Project Atomic PPA. Is there something going wrong behind the scenes that me/others in the community can help out with?

**Comment by TomSweeneyRedHat** [comment]
The main issue is the person who handles this @lsm5 had a crunch of other high priority work that he undertook before a very long and very well deserved vacation/PTO that started in early December and will be wrapping up in at the end of this month.  He's been monitoring mail/GitHub, but hasn't had time to do chunks of work during that time period.  

If other folks are able to lend @lsm5 a hand, I'm sure he'd love to take this off his plate.

**Comment by lsm5** [comment]
apologies for the delay everyone, going forward, updates will be going to the [Kubic project on OBS](https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable) instead of PPA.

**Comment by jayaddison** [comment]
@lsm5 Thanks for the link to the Kubic project builds on https://build.opensuse.org and updating the README documentation to list the Kubic `apt` repo.

It'd be good to have visibility into changes in `buildah`'s binary packaging; I discovered the spec file here: https://build.opensuse.org/package/view_file/devel:kubic:libcontainers:stable/buildah/_service:obs_scm:buildah.spec?expand=1

Do you know how long it typically takes for diffs to become accessible?  It'd be useful for debugging and issue diagnosis to see the change history.  Currently there's an error when I try to retrieve a revision diff: https://build.opensuse.org/package/rdiff/devel:kubic:libcontainers:stable/buildah?linkrev=base&rev=246

![diff-error](https://user-images.githubusercontent.com/55152140/78283698-12997a80-7516-11ea-9fd3-4308c8163280.png)

**Comment by jayaddison** [comment]
Thank you for the detailed and thoughtful response with references; I'm glad to see this is all more transparent than I originally realized (if involving one or two more steps, perhaps).

> I can include this info on the OBS page and maybe somewhere in the buildah source as well.

That'd be much appreciated when you can; please don't let me distract you from any other priority work though.

We can put a lot of this down to my lack of familiarity with OBS (I've spent more time reading Ubuntu, Debian and Alpine package source builds recently) - but anything to make the package builds easier to discover and trust would help.

> Not sure about the diff for spec file since the _service file just fetches the latest spec on every push to dist-git. So, I guess it's best to check the git logs for the repos mentioned above.

Got it, thanks.  Some of this may be feedback that I should provide on the OBS project itself, since it may be down to issues rendering empty diffs.  I'll do that as soon as I can :)
