### ISSUE TITLE
Query on running process via buildah run command

### ISSUE THREAD

**Issue by aggarwalShivani** [containers/buildah#1927]
**Description**

I have a query regarding buildah. I need to run a shell script while building the image (and not at docker-entrypoint). 
It needs to start a process in background.

In Dockerfile, I run it via RUN command. It looks like this:
`  RUN /usr/local/kibana-docker &>/tmp/kibana & `
( I am running the process in background using **'&'**)

In buildah, I am unable to run the same using buildah run.
`  buildah run $container -- sh -c "/usr/local/kibana-docker &>/tmp/kibana &"`

**Describe the results you received:**
Even after executing the script, the kibana-docker process does not get started. When I run ps next, it does not list the process.
( UID        PID  PPID  C STIME TTY          TIME CMD
kibana       1     0  0 12:05 pts/0    00:00:00 /bin/sh -c /usr/local/kibana-docker &>/tmp/kibana & 
kibana     311     1  0 12:05 pts/0    00:00:00 ps -aef)

**Describe the results you expected:**
I expected to be able to start this process while building the image.
My intention is to start the process, wait for some-condition & then kill it. Finally, configure the entrypoint script for the image. which would run when a container is created.

Can we not start processes/services (while building the image) using ‘buildah run’ this way? Is this a limitation on buildah tool?
Is there any other way to solve my issue?
Any inputs will be greatly appreciated.

**Output of `rpm -q buildah` or `apt list buildah`:**
```
buildah-1.9.0-2.el7.x86_64
```

**Output of `buildah version`:**

```
Version:         1.9.0
Go Version:      go1.10.8
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64

```

**Comment by rhatdan** [comment]
Does the command work if you run it inside of a Dockerfile, executed by buildah?
If yes then this is probably a shell escaping issue.
You might need to escape the & to get the buildah command to see it, otherwise bash will just run the buildah command in background

**Comment by TomSweeneyRedHat** [comment]
@aggarwalShivani my first guess is the the same as @rhatdan 's.  Can you try:
```
buildah run bash -c '$container /usr/local/kibana-docker &>/tmp/kibana &'
```
Those are single quotes and not back ticks.

**Comment by rhatdan** [comment]
Since this is a shell escaping issue, closing.
