### ISSUE TITLE
buildah bud: stdout vanishes if filehandle is not a tty

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#1928]
When redirecting stdout, output of `buildah bud` disappears:
```
# cat Dockerfile
FROM busybox
RUN date
# buildah bud -q .
Wed Oct 16 19:19:33 UTC 2019
31547007ca71711c2179165b101e6b1f423efc3e056a314a91be551d49655693
# !! | cat
c7842e28a0c64cba7436c9651f0b648c383877a38888d40f1b35dfcfb8083a0e
```
That is: adding `| cat` (or redirecting to a file, whatever) loses the output of `date` (or any other command run). The `-q` isn't necessary, I just added it here for a clean bug report.

buildah-1.12.0-0.40.dev.git389d49b.fc32.x86_64 on rawhide.

**Comment by rhatdan** [comment]
I would guess we have some kind of isterminal check happening and don't output from buidlah if their is no TTY?
@nalind @TomSweeneyRedHat PTAL

**Comment by edsantiago** [comment]
It's something to do with rawhide: perhaps runc/crun, perhaps cgroups v2. Problem present on all rawhide builds of buildah, down to and including `buildah-1.11.0-0.34.dev.git689f8ed.fc32.x86_64.rpm` (2019-08-28) which is the first one that actually seems to run on rawhide.

**Comment by edsantiago** [comment]
Fails on f31 too. Seems to work on f30. Maybe it's a crun thing?

**Comment by TomSweeneyRedHat** [comment]
@edsantiago Can you give this a quick spin again please?  It's working for me at this point on F31 and Buildah upstream.  IDK if that's just coincidence or not.

Also the -q output above showing the date was a bug.  That should not have been shown prior and has been corrected.

**Comment by edsantiago** [comment]
With `buildah-1.14.0-0.31.dev.git82ff48a.fc32.x86_64` I no longer see the difference in behavior:
```console
# buildah bud .
STEP 1: FROM busybox
STEP 2: RUN date
Mon Feb 17 15:11:27 UTC 2020
STEP 3: COMMIT
Getting image source signatures
Copying blob 195be5f8be1d skipped: already exists
Copying blob e9e06e76d756 done
Copying config 19e0f4f23a [======================================] 725.0b / 725.0b
Writing manifest to image destination
Storing signatures
19e0f4f23a1e8eac71842cd63d61641e46db1ca803fd782fd5814fbc61524089
19e0f4f23a1e8eac71842cd63d61641e46db1ca803fd782fd5814fbc61524089

# buildah bud . | cat
STEP 1: FROM busybox
STEP 2: RUN date
Mon Feb 17 15:11:35 UTC 2020
STEP 3: COMMIT
Getting image source signatures
Copying blob 195be5f8be1d skipped: already exists
Copying blob 78916c357221 [======================================] 1.4MiB / 1.4MiB
Copying config 82c42fd5be [======================================] 725.0b / 725.0b
Writing manifest to image destination
Storing signatures
82c42fd5be01e05a1cb78409550b31e722381bca2624dd836ed1ddbcb455a1f9
82c42fd5be01e05a1cb78409550b31e722381bca2624dd836ed1ddbcb455a1f9
```
What surprises me is the duplicate duplicate SHA at the end; do I remember correctly that this was reported and fixed earlier? Am I just running a build that doesn't include that fix?

Anyhow, closing, since it does seem to be fixed. Thanks.

**Comment by TomSweeneyRedHat** [comment]
Thanks @edsantiago The double id there was just recently fixed.  It will be in 1.14.1 or 1.15.0 which ever goes out next.
