### ISSUE TITLE
Can't build an image in a rootless user 

### ISSUE THREAD

**Issue by galitker** [containers/buildah#1940]
**Description**
When trying to buildah n image using a Dockerfile under jenkins user, buildah throws the following error:

kernel does not support overlay fs: 'overlay' is not supported over xfs at "/data/jenkins/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver

**Steps to reproduce the issue:**
1. su - jenkins
2. buildah bud --storage-driver=overlay --debug --creds=******:'*****' --format docker -f ./Dockerfile .

**Describe the results you received:**

DEBU[0000] running [buildah-in-a-user-namespace bud --storage-driver=overlay --debug --creds=devops-prod-deployer:dnVkT?1:4z<2PH --format docker -f ./Dockerfile .] with environment [XDG_SESSION_ID=636 HOSTNAME=ilptdmlv-jkss02.cyberng.com SHELL=/bin/bash TERM=xterm HISTSIZE=1000 USER=jenkins LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36: MAIL=/var/spool/mail/jenkins PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin PWD=/data/jenkins LANG=en_US.UTF-8 HISTCONTROL=ignoredups SHLVL=1 HOME=/data/jenkins LOGNAME=jenkins LESSOPEN=||/usr/bin/lesspipe.sh %s _=/bin/buildah _CONTAINERS_USERNS_CONFIGURED=1 BUILDAH_ISOLATION=rootless], UID map [{HostID:1001 ContainerID:0 Size:1} {HostID:100000 ContainerID:1 Size:65536}], and GID map [{HostID:1001 ContainerID:0 Size:1} {HostID:100000 ContainerID:1 Size:65536}]
DEBU[0000] umask value too restrictive.  Forcing it to 022
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay test mount with multiple lowers failed mountfrom re-exec error: exit status 1: output: operation not permitted
DEBU[0000] overlay test mount with a single lower failed mountfrom re-exec error: exit status 1: output: operation not permitted
ERRO[0000] 'overlay' is not supported over xfs at "/data/jenkins/.local/share/containers/storage/overlay"
kernel does not support overlay fs: 'overlay' is not supported over xfs at "/data/jenkins/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver
ERRO[0000] exit status 1

**Describe the results you expected:**

Image built successfully

**Output of `rpm -q buildah` or `apt list buildah`:**

buildah-1.9.0-2.el7.centos.x86_64

**Output of `buildah version`:**

Version:         1.9.0
Go Version:      go1.10.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:         1.9.0
Go Version:      go1.10.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
-bash-4.2$ podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.7.1908 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.7.1908 (Core)
CentOS Linux release 7.7.1908 (Core)

```

**Output of `uname -a`:**

```
Linux ilptdmlv-jkss02.cyberng.com 5.3.6-1.el7.elrepo.x86_64 #1 SMP Fri Oct 11 17:24:39 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/1001/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

mount_program = "/usr/bin/fuse-overlayfs"
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# mountopt specifies extra mount options used when mounting the thin devices.
# mountopt = ""

# use_deferred_removal Marking device for deferred removal
# use_deferred_removal = "True"

# use_deferred_deletion Marking device for deferred deletion
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"

```
**Output of `cat /data/jenkins/.config/containers/storage.conf`:**

```
[storage]
  driver = "overlay"
  runroot = "/run/user/1001"
  graphroot = "/data/jenkins/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    remap-user = ""
    remap-group = ""
    ostree_repo = ""
    skip_mount_home = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""

```

**Comment by rhatdan** [comment]
overlayfs is not support for RHEL7 rootless users yet.  Should be fixed in RHEL7.8.
You could try this on RHEL8 until then or use the vfs driver on rhel7 rootless.

**Comment by galitker** [comment]
Thanks for the quick reply. vfs driver is not an option as it's too slow and a storage consumer.
Can I run an dockerized container with ubuntu 18.04 and build using buildah inside?
for e.g.
1. docker run -it --user jenkins -v /var/lib/containers/:/var/lib/containers/ --privileged 11649cadba1e bash 
2. buildah bud --storage-driver=overlay --debug --creds=*:'' --format docker -f ./Dockerfile .

**Comment by galitker** [comment]
Can you answer my second question

**Comment by rhatdan** [comment]
That should work. 

You can do this with Podman right now on a locked down container, and use quay.io/buildah/stable container images

https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/

**Comment by galitker** [comment]
Thanks, @rhatdan .
Can I do this with docker rather than podman as I am using the jenkins docker plugin?

**Comment by rhatdan** [comment]
The issue with Docker is that it uses a slightly stricter seccomp.json file that blocks the abiltity to mount and unshare.  If you could get Docker in Jenkens to use an alternate seccomp profile, then this should work.  But I would prefer to get a Podman plugin to Jenkens...

**Comment by rhatdan** [comment]
Not that I know of, but if you ask on Jenkens, maybe someone will get motivated.
