### ISSUE TITLE
buildah login command does not work - version 1.5.3

### ISSUE THREAD

**Issue by shyam-biradar** [containers/buildah#1942]
[root@localhost ~]# buildah login docker.io
No help topic for 'login'
[root@localhost ~]# cat /etc/*-release
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"
Red Hat Enterprise Linux release 8.0 (Ootpa)
Red Hat Enterprise Linux release 8.0 (Ootpa)
[root@localhost ~]# buildah --version
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)
[root@localhost ~]#

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 PTAL

**Comment by rhatdan** [comment]
Buildah login/logout was added in v1.8.2  So this is fixed in master and should show up in your distribution soon. Hopefully 8.1.

**Comment by shyam-biradar** [comment]
Okay, thanks.
