### ISSUE TITLE
Question: is buildah/stable:v1.11.3 removed permanently on quay.io?

### ISSUE THREAD

**Issue by azatsarynnyy** [containers/buildah#1943]
We've just noticed that `quay.io/buildah/stable:v1.11.3` has been removed.
Is there a reason for this?

**Comment by TomSweeneyRedHat** [comment]
Yes, if you looked under the covers, it was really mislabeled.  The Buildah version inside that image was really v1.11.2.

I'd hoped to update/fix it this morning, but bohdi was down and I wasn't able to pull a Buildah v1.11.3 from there.  I hope to do so later today, internet gremlins permitting.

**Comment by azatsarynnyy** [comment]
Thanks @TomSweeneyRedHat for the answer!

**Comment by TomSweeneyRedHat** [comment]
@azatsarynnyy I've just pushed a new v1.11.3 image out to quay.io/buildah/stable:v1.11.3, now with the appropriate version inside of it.

I'll try to remember to replace the images going forward rather than remove and update.
