### ISSUE TITLE
buildah pull failing, however podman pull working fine

### ISSUE THREAD

**Issue by shyam-biradar** [containers/buildah#1944]
[root@localhost trilio-datamover-api]# buildah pull registry.redhat.io/rhosp15-rhel8/openstack-nova-api
Error determining manifest MIME type for docker://registry.redhat.io/rhosp15-rhel8/openstack-nova-api:latest: unable to retrieve auth token: invalid username/password
[root@localhost trilio-datamover-api]# podman pull registry.redhat.io/rhosp15-rhel8/openstack-nova-api
Trying to pull registry.redhat.io/rhosp15-rhel8/openstack-nova-api...Getting image source signatures
Skipping blob 0f39907dc9f0 (already present): 40.13 MiB / 40.13 MiB [=======] 0s
Skipping blob c65691897a4d (already present): 67.74 MiB / 67.74 MiB [=======] 0s
Skipping blob 641d7cc5cbc4 (already present): 1.48 KiB / 1.48 KiB [=========] 0s
Skipping blob f87dfcac8eff (already present): 41.96 MiB / 41.96 MiB [=======] 0s
Skipping blob 88ae1403b98e (already present): 75.29 MiB / 75.29 MiB [=======] 0s
Skipping blob a27f33f8dbda (already present): 93.15 MiB / 93.15 MiB [=======] 0s
Skipping blob c65691897a4d (already present): 67.74 MiB / 67.74 MiB [=======] 0s
Skipping blob 641d7cc5cbc4 (already present): 1.48 KiB / 1.48 KiB [=========] 0s
Skipping blob f87dfcac8eff (already present): 41.96 MiB / 41.96 MiB [=======] 0s
Skipping blob 88ae1403b98e (already present): 75.29 MiB / 75.29 MiB [=======] 0s
Skipping blob a27f33f8dbda (already present): 93.15 MiB / 93.15 MiB [=======] 0s
Skipping blob 0f39907dc9f0 (already present): 40.13 MiB / 40.13 MiB [=======] 0s
Copying config 13ac76a8f700: 4.34 KiB / 4.34 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
13ac76a8f700dbffe1905fa0d18fe37788655f75bb757d9a6cb21386e7b62ee8

**Comment by shyam-biradar** [comment]
Logged in to redhat registry using 'podman login' command. I learnt that 'buildah' should fetch registry credentials from podman.

**Comment by shyam-biradar** [comment]
[root@localhost trilio-datamover-api]# podman info
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.5-1.gitf604175.module+el8.0.0+4017+bbba319f.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 6ee5ad0285ca12e6c8d0b663d7a8db5323812ef6-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "8.0"
  MemFree: 118317056
  MemTotal: 1918386176
  OCIRuntime:
    package: runc-1.0.0-56.rc8.dev.git425e105.module+el8.0.0+4017+bbba319f.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2205032448
  SwapTotal: 2222977024
  arch: amd64
  cpus: 1
  hostname: localhost.localdomain
  kernel: 4.18.0-80.11.2.el8_0.x86_64
  os: linux
  rootless: false
  uptime: 21h 25m 13.19s (Approximately 0.88 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.redhat.io
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /var/run/containers/storage

**Comment by shyam-biradar** [comment]
[root@localhost trilio-datamover-api]# buildah info
No help topic for 'info'
[root@localhost trilio-datamover-api]# buildah --version
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)
[root@localhost trilio-datamover-api]#

**Comment by TomSweeneyRedHat** [comment]
@shyam-biradar thanks for the issue report.  Both the Podman and Buildah versions that you're using are very old.  We're currently at Buildah v1.11.3 and Podman 1.6.2 as the newest.  I know that since the versions that you're using, we've done a number of changes to the authentication process.  Would it be possible for you to update the software and try again?

**Comment by shyam-biradar** [comment]
@TomSweeneyRedHat  Thanks. I will upgrade both and will try pull commands again.

**Comment by shyam-biradar** [comment]
@TomSweeneyRedHat : I have installed both podman and buildah with default yum install commands.
I think both packages came from rhel8 distro. How can I upgrade them? Do we have any special yum repo rhel8?

**Comment by rhatdan** [comment]
RHEL8 version will not be updated until RHEL8.1 (Next month),  After that we should be updating every three months.  There was release problems, which have prevented us from updating sooner.  As you can imaginge Podman and Buildah are moving very fast...

**Comment by shyam-biradar** [comment]
@rhatdan : Thank you for this information. Any other way to install latest podman and buildah on rhel?
Manual way from github?

**Comment by rhatdan** [comment]
@lsm5 @jnovy Do you know of a way?

**Comment by TomSweeneyRedHat** [comment]
reping @lsm5 @jnovy

**Comment by rhatdan** [comment]
This is fixed in latest rhel8 content.
