### ISSUE TITLE
Mirror usage, how to config please

### ISSUE THREAD

**Issue by huapox** [containers/buildah#1962]
#1634
As this shows, mrrior is supported, but how to config? 

I've searched github and `buildah.io` for docs but got none.

**Comment by vrothberg** [comment]
Hi @huapox, thanks for reaching out. You can find the documentation how to configure mirroring in the [containers-registries.conf](https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md) man page.

**Comment by huapox** [comment]
@vrothberg Thx, And I got this here.
https://github.com/containers/image/pull/617/files#diff-fbfdafdf3fb8cd848f925272125d7c15L70-R128

**Comment by rhatdan** [comment]
Would probably be worth a quick blog  as well, to make this information easier to find.
