### ISSUE TITLE
Build and publish Ubuntu Eoan (19.10) builds on PPA

### ISSUE THREAD

**Issue by gjasny** [containers/buildah#1969]
Hello,

in the projectatomic PPA, could you please enable building for Ubuntu Eoan (19.10)?

Thanks,
Gregor

**Comment by TomSweeneyRedHat** [comment]
WDYT @lsm5 ?

**Comment by akospinter** [comment]
Hi,

when can we expect a release for Ubuntu Eoan (19.10) ?

Thanks,
Ákos

**Comment by TomSweeneyRedHat** [comment]
@lsm5 any input?

**Comment by akospinter** [comment]
Hi,

I can see an updated installation method for Ubuntu 19.10 at this page: https://github.com/containers/buildah/blob/master/install.md . Thanks for that.

I have tried it, the installation was successful, but buildah doesn't work from the command line, I am getting this error: "buildah: command not found"

Is there something that is missing from the installation script?

Thanks,
Ákos

**Comment by lsm5** [comment]
err .. I'll check and get back..

**Comment by lsm5** [comment]
should be fixed with 1.12.0~3  https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/buildah . Should be available in a bit.

Please re-open the issue if it persists..

**Comment by akospinter** [comment]
It works properly now, thanks for that :)

Just one small comment: I needed to install the runc package manually. I think it would be beneficial if it was installed in the same step with buildah.

**Comment by lsm5** [comment]
@akospinter ack, I guess buildah must've installed a `cri-o-runc` package by default. If the distro's `runc` package works well for you, I'll update the dependencies. I'd really like to not ship a `cri-o-runc`. Please let me know..

**Comment by akospinter** [comment]
It seems it works well. But after I installed runc (`sudo apt-get install runc`), I used buildah only for the following: building an image from a dockerfile, tagging, pushing it to a registry. So I haven't tried out all of the available functionalities.

**Comment by lsm5** [comment]
just sent `1.12.0~4` to OBS, it will pickup runc by default. HTH.

**Comment by akospinter** [comment]
I received the update and it still works, thanks :)

**Comment by akospinter** [comment]
Hi @lsm5 ,

will `buildah` be available on Ubuntu 20.04? According to the [installation instructions](https://github.com/containers/buildah/blob/master/install.md) it is not yet available.

Many thanks,
Ákos

**Comment by lsm5** [comment]
@akospinter it's available now.

@TomSweeneyRedHat is it better to remove the distro version numbers from the ubuntu section, or would you prefer I send PR whenever a new version appears?

**Comment by TomSweeneyRedHat** [comment]
@lsm5 I'm missing context or lacking in tea.  Which "ubuntu section"?  I'm thinking the install guide, if so I'd be fine with removing from there as long as the instructions hold for the latest/greatest Ubuntu version.

**Comment by lsm5** [comment]
> @lsm5 I'm missing context or lacking in tea. Which "ubuntu section"? I'm thinking the install guide, if so I'd be fine with removing from there as long as the instructions hold for the latest/greatest Ubuntu version.

@TomSweeneyRedHat yes, the ubuntu section in the install guide where it currently says `18.04, 19.04 and 19.10`. So, once 20.04 got released, it took OBS admins a few days to enable 20.04 build environments. I gotta check with them if they can do this ahead of time going forward and I'll update the docs based on what they say..
