### ISSUE TITLE
podman: tar too many levels of symbolic links

### ISSUE THREAD

**Issue by tuan-hoang1** [containers/buildah#1979]
**Description**

**Steps to reproduce the issue:**
1. git clone https://github.com/coreos/coreos-assembler
2. podman build -t fcos/cosa -f $PWD/coreos-assembler/Dockerfile

**Describe the results you received:**
```
STEP 7: COPY ./ /root/containerbuild/
Error: error building at STEP "COPY ./ /root/containerbuild/": error copying "/home/tmhoang/coreos/github.com/tuan-hoang1/coreos-assembler" to "/home/tmhoang/.local/share/containers/storage/overlay/b44c478bd93416d784ff646e9c2a1e2d008dcefb8491177af0b75aff91d7bc88/merged/root/containerbuild": Error processing tar file(exit status 1): too many levels of symbolic links
```

In `coreos-assembler` directory there are a couple of symlink files ending in `.txt` that links to `src/*.txt`. I think they are the cause, because 
`
for i in vmdeps*.txt deps*.txt; do rm $i; cp src/$i $i; done ` works.

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 1.6.2

```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
NAME=Fedora
VERSION="31 (Server Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux xzkvm32 5.3.9-300.fc31.x86_64 #1 SMP Wed Nov 6 16:13:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
It's default, I have never touched it.
```

**Comment by tuan-hoang1** [comment]
Downstream issue : https://github.com/coreos/coreos-assembler/issues/880

**Comment by dustymabe** [comment]
I do see the problem here locally on Silverblue (`31.20191102.0`, `podman-1.6.2-2.fc31.x86_64`) using unprivileged podman.

**Comment by nalind** [comment]
Since I get past step 7 (failing at step 9) by forcing use of the `vfs` driver as an unprivileged user, or by using the kernel overlay driver by building as root, I'm thinking this is either specific to fuse-overlayfs, but I can't rule out a buildah bug that we only notice when using fuse-overlayfs.  I think we need @giuseppe's help here.

**Comment by giuseppe** [comment]
@dustymabe @tuan-hoang1 could you please try if 
https://bodhi.fedoraproject.org/updates/FEDORA-2019-b71b08d561 solves the issue you are seeing?

**Comment by dustymabe** [comment]
> @dustymabe @tuan-hoang1 could you please try if
> https://bodhi.fedoraproject.org/updates/FEDORA-2019-b71b08d561 solves the issue you are seeing?

works for me!

**Comment by TomSweeneyRedHat** [comment]
@tuan-hoang1 can you confirm the update that @giuseppe fixes the issue for you and if we can then close this?

**Comment by rhatdan** [comment]
Reopen if this issue is not fixed.

**Comment by tuan-hoang1** [comment]
Confirm fixed on both platforms. Thanks @giuseppe !
