### ISSUE TITLE
docker hub

### ISSUE THREAD

**Issue by isomorphisms** [containers/buildah#1981]
How do I `buildah from docker://hub.docker.com`? After a few blog posts, tutorials, and man pages, I’m not clear on this.

Using github.com/scrapinghub/splash, their Dockerfile starts with

```
FROM byrnedo/alpine-curl as qt-downloader
COPY dockerfiles/splash/download-qt-installer.sh /tmp/download-qt-installer.sh
RUN /tmp/download-qt-installer.sh /tmp/qt-installer.run
```

Of course, who knows what `byrnedo/alpine-curl` is. But I bet `docker` has a default that does know where to find it.

It would be helpful for `man buildah-from` to mention this probably common use case.

**Comment by TomasTomecek** [comment]
```
$ buildah pull docker.io/byrnedo/alpine-curl
Getting image source signatures
Copying blob c975b7455e06 done
Copying blob 89d9c30c1d48 done
Copying config 621496cef4 done
Writing manifest to image destination
Storing signatures
621496cef4f8cdf5a9b44cd538d4a23c7546b9b86bbb041f50032c5dd3c9c444

$ buildah from docker.io/byrnedo/alpine-curl
alpine-curl-working-container
```

This `buildah-pull(1)` manpage part is what you were likely looking for:
```
       docker://docker-reference (Default)
         An image in a registry implementing the "Docker Registry HTTP API V2". By default, uses the  authorization  state  in  $XDG\_RUNTIME\_DIR/containers/auth.json,
       which is set using (buildah login). If the authorization state is not found there, $HOME/.docker/config.json is checked, which is set using (docker login).
         If docker-reference does not include a registry name, localhost will be consulted first, followed by any registries named in the registries configuration.
```

**Comment by TomSweeneyRedHat** [comment]
Thanks @TomasTomecek , he's spot on as usual  @isomorphisms .  I'll try to add a clarification in the tutorials about this, but the shor answer is you need to add 'docker.io/' to your image name in the FROM line in the Dockerfile.  If that doesn't cure it, please let us know.

**Comment by rhatdan** [comment]
I believe the documentation is good now, reopen if I am mistaken.
