### ISSUE TITLE
Why does buildah pull print info output to stderr?

### ISSUE THREAD

**Issue by TomasTomecek** [containers/buildah#1988]
**Description**

`buildah pull` prints output to stderr which should actually be in stdout

I just got this bug report in ansible-bender: https://github.com/ansible-community/ansible-bender/issues/193

This behaviour makes it hard to integrate buildah into a project since stderr contains text which is not composed of errors and hence makes it confusing to users.

**Steps to reproduce the issue:**

```
$ buildah pull alpine >./stdout 2>./stderr

$ cat stdout
965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652

$ cat stderr
Getting image source signatures
Copying blob sha256:89d9c30c1d48bac627e5c6cb0d1ed1eec28e7dbdfbcc04712e4c79c0f83faf17
Copying config sha256:965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652
Writing manifest to image destination
Storing signatures
```

**Describe the results you expected:**

```
$ buildah pull alpine >./stdout 2>./stderr

$ cat stdout
Getting image source signatures
Copying blob sha256:89d9c30c1d48bac627e5c6cb0d1ed1eec28e7dbdfbcc04712e4c79c0f83faf17
Copying config sha256:965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652
Writing manifest to image destination
Storing signatures
965ea09ff2ebd2b9eeec88cd822ce156f6674c7e99be082c7efac3c62f3ff652

$ cat stderr  # read as "nothing"
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.11.4-2.fc30.x86_64
```

**Comment by rhatdan** [comment]
I believe this is following the Docker behavior.  allowing users to just grab the image id from stdout and all of the progress information goes to stderr.

**Comment by TomasTomecek** [comment]
Got it, thank you. We were able to figure a nice fix this on our end, so we can close:

https://github.com/ansible-community/ansible-bender/issues/193#issuecomment-555528054
