### ISSUE TITLE
podman crashes with invalid arguments

### ISSUE THREAD

**Issue by Jakuje** [containers/buildah#1990]
**Description**

As an human error, I tried to build my (almost) first container using podman and I forgot one switch, which lead to the podman crash. 

**Steps to reproduce the issue:**
1. Create any `Dockerfile`
2. run `podman build ./Dockerfile` (note the missing `-f`)

**Describe the results you received:**
Podman crashes and dumps backtraces:
```
Process 421161 (podman) of user 1000 dumped core.

Stack trace of thread 421169:
#0  0x0000560406936491 runtime.raise (podman)
#1  0x000056040691c4dd runtime.sigfwdgo (podman)
#2  0x000056040691b620 runtime.sigtrampgo (podman)
#3  0x0000560406936783 runtime.sigtramp (podman)
#4  0x00007f5ea58beb20 __restore_rt (libpthread.so.0)
#5  0x0000560406936491 runtime.raise (podman)
#6  0x000056040691c0ea runtime.crash (podman)
#7  0x0000560406906776 runtime.fatalpanic (podman)
#8  0x0000560406906136 runtime.gopanic (podman)
#9  0x000056040691be70 runtime.sigpanic (podman)
#10 0x0000560407a709aa main.checkIfFileExists (podman)
#11 0x0000560407a20c1c main.buildCmd (podman)
#12 0x0000560407a76500 main.glob..func2 (podman)
#13 0x0000560406ad1af2 github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute (podman)
#14 0x0000560406ad254d github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC (podman)
#15 0x0000560407a3e482 main.main (podman)
#16 0x0000560406907ea6 runtime.main (podman)
#17 0x000000c00004e060 n/a (n/a)
#18 0x0000000000000000 n/a (n/a)
```

**Describe the results you expected:**
Normal error about invalid arguments should be returned

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.11.4-2.fc31.x86_64
```

**Output of `buildah version`:**

```
Version:         1.11.4
Go Version:      go1.13.1
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux hostname 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TomSweeneyRedHat** [comment]
Well that's exceptionally ugly.  Thanks for the issue report @Jakuje .  This should be a good "first time" bug for someone.  I'll mark it so and will run it down in the near future if someone doesn't grab it.

**Comment by rhatdan** [comment]
I believe this is already fixed in the master branch

./bin/podman build ./Dockerfile
Error: context must be a directory: /home/dwalsh/libpod/Dockerfile

**Comment by Jakuje** [comment]
It looks like somebody was faster. Thanks.
