### ISSUE TITLE
buildah config --env takes only one envvar

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#1993]
In a Dockerfile with a line like:
```
# isolate the filesystem with chroot.
ENV _BUILDAH_STARTED_IN_USERNS="" BUILDAH_ISOLATION=chroot
```
both environment variables are set as requested.  However, if you do

```
buildah config --env _BUILDAH_STARTED_IN_USERNS="" BUILDAH_ISOLATION=chroot
```
They are not.  I'm not sure if some kind of bash chicanery is going on here, but thought I'd raise the issue in case it's not and the config command needs to be changed to accept multiple arguments.  This is going on with Buildah v1.11.5.

**Comment by rhatdan** [comment]
You need to use the --env for each environment variable.
```
buildah config --env _BUILDAH_STARTED_IN_USERNS="" --env BUILDAH_ISOLATION=chroot
```

**Comment by TomSweeneyRedHat** [comment]
Yeah that does work, but I was hoping to see if we could do so without the second `--env` thrown in there.

**Comment by rhatdan** [comment]
Not really the way command line parsing works.

**Comment by rhatdan** [comment]
We could do something like
buildah config --env _BUILDAH_STARTED_IN_USERNS="",BUILDAH_ISOLATION=chroot

But not sure this would work easily with command parsing and does not really match what you expected.
