### ISSUE TITLE
wrong $HOME var when run with chroot isolation

### ISSUE THREAD

**Issue by TeNNoX** [containers/buildah#2005]
**Description**
Here's what I found:  
When running a buildah step with chroot isolation, the $HOME var is wrongly set to **`/`** - as opposed to e.g. `/root` with OCI isolation.

This happened to me when I tried to build an image inside the **quay.io/buildah** container, but testing shows this is also happening on host when setting --isolation=chroot explicitly.

**Steps to reproduce the issue:**
### HOST (set isolation mode explicitly)
1. `a=$(buildah from docker.io/alpine)`
2. `buildah run $a sh -c export` -> `HOME='/root'`
3. `buildah run --isolation=chroot $a sh -c export` -> `HOME='/'` **(should be /root)**

### inside container (how I encountered it)
1. `sudo podman run --rm -v /var/lib/containers:/var/lib/containers -v .:/app --privileged -it quay.io/buildah/upstream`  
(tried with **docker run** - same result)  
(mounting `/var/lib/containers` to be able to use overlayfs)
2. `a=$(buildah from docker.io/alpine)`
3. `buildah run $a sh -c export` -> `HOME='/'` **(should be /root)**
4. `buildah run --isolation=oci $a sh -c export` -> `HOME='/root'`

**Describe the results you received:**
I got a problem with meteor trying to install itself again, as `/.meteor` didn't exist.

**Describe the results you expected:**
`$HOME` would be correctly set to `/root` in all cases.

**Output of `rpm -q buildah` or `apt list buildah`:**
**Docker**: `quay.io
```
buildah/bionic,now 1.10.1-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Output of `buildah version`:**
```
Version:         1.10.1
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Aug  8 21:29:48 2019
OS/Arch:         linux/amd64
```
Inside docker:
```
Version:         1.12.0-dev
Go Version:      go1.13.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.1
image Version:   5.0.0
Git Commit:      1ff7043e
Built:           Wed Oct 30 19:06:18 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**
```
DISTRIB_ID=elementary
DISTRIB_RELEASE=5.0
DISTRIB_CODENAME=juno
DISTRIB_DESCRIPTION="elementary OS 5.0 Juno"
NAME="elementary OS"
VERSION="5.0 Juno"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.0 Juno"
LOGO=distributor-logo
VERSION_ID="5.0"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/appcenter/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=juno
UBUNTU_CODENAME=bionic
cat: /etc/upstream-release: Is a directory
```

**Output of `uname -a`:**
```
Linux manuel-lap 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
Thanks for the issue @TeNNoX .  I think this might be a good first issue for someone.  I'll mark it so and will see if it gets grabbed.

**Comment by rhatdan** [comment]
Perhaps @TeNNoX you could open a PR for this?

**Comment by boaz0** [comment]
I think we can close this issue - #2057 fixes it
