### ISSUE TITLE
buildah bud --layers does not add labels to existing image

### ISSUE THREAD

**Issue by mraszplewicz** [containers/buildah#2041]
**Description**

I am not sure if this is a bug. When I run buildah bud --layers on the same Dockerfile multiple times with different labels, only the first one is visible using buildah inspect.

**Steps to reproduce the issue:**
1. Use this Dockerfile:
```
FROM alpine:3.11

RUN echo "test" > test.txt
```
2. Run build with first label:
```buildah bud --layers -t test --label foo=bar .```
3. Check image labels:
```buildah inspect b44cb95968d9e8e2af75d1bf6f08150c4148d898dc237bc8d3d7d8b7eff58347 | jq '.OCIv1.config.Labels'```
4. Build with different label:
```buildah bud --layers -t test --label foo2=bar2 .```
5. Check image labels again:
```buildah inspect b44cb95968d9e8e2af75d1bf6f08150c4148d898dc237bc8d3d7d8b7eff58347 | jq '.OCIv1.config.Labels'```

**Describe the results you received:**

I can see only labels from the first build.

**Describe the results you expected:**

I expected both labels or only from the latest build.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Listing... Done
buildah/disco,now 1.10.1-1~ubuntu19.04~ppa1 amd64 [installed]
buildah/disco 1.10.1-1~ubuntu19.04~ppa1 i386

```

**Output of `buildah version`:**

```
Version:         1.10.1
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Aug  8 22:30:06 2019
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```

**Output of `uname -a`:**

```
Linux baltazar 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
The second inspect is inspecting the first image, which is why it only shows the first label.
Try
```
buildah inspect test |  jq '.OCIv1.config.Labels'
```

**Comment by mraszplewicz** [comment]
Hi @rhatdan,

Thanks for your answer. Actually there is only one image. I run buildah twice on the same Dockerfile:
```
maciek@baltazar:~/src/buildah-bugs/label-test$ buildah bud --layers -t test --label foo=bar .
STEP 1: FROM alpine:3.11
STEP 2: RUN echo "test" > test.txt
--> Using cache b44cb95968d9e8e2af75d1bf6f08150c4148d898dc237bc8d3d7d8b7eff58347
STEP 3: COMMIT test
b44cb95968d9e8e2af75d1bf6f08150c4148d898dc237bc8d3d7d8b7eff58347
maciek@baltazar:~/src/buildah-bugs/label-test$ buildah bud --layers -t test --label foo2=bar2 .
STEP 1: FROM alpine:3.11
STEP 2: RUN echo "test" > test.txt
--> Using cache b44cb95968d9e8e2af75d1bf6f08150c4148d898dc237bc8d3d7d8b7eff58347
STEP 3: COMMIT test
b44cb95968d9e8e2af75d1bf6f08150c4148d898dc237bc8d3d7d8b7eff58347
maciek@baltazar:~/src/buildah-bugs/label-test$ buildah images
REPOSITORY                 TAG      IMAGE ID       CREATED        SIZE
localhost/test             latest   b44cb95968d9   21 hours ago   5.86 MB
docker.io/library/alpine   3.11     c85b8f829d1f   3 days ago     5.86 MB
maciek@baltazar:~/src/buildah-bugs/label-test$ buildah inspect test |  jq '.OCIv1.config.Labels'
{
  "foo": "bar"
}
```

**Comment by rhatdan** [comment]
Ok this works if the container is built without the --layers flag.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat 
Looks like the layers optimization is not seeing that their is a difference in the command so it is not saving the layer.

**Comment by rhatdan** [comment]
@mraszplewicz Any interest in attempting a fix for this.  A PR would get it fixed quicker.

**Comment by mraszplewicz** [comment]
@rhatdan I can try but I have zero experience in golang. Maybe it is time to learn it...

I have checked how docker build does it. It looks like it is adding a new layer:
```
maciek@baltazar:~/src/buildah-bugs/label-test$ docker build -t test --label foo=bar .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine:3.11
3.11: Pulling from library/alpine
e6b0cf9c0882: Pull complete 
Digest: sha256:2171658620155679240babee0a7714f6509fae66898db422ad803b951257db78
Status: Downloaded newer image for alpine:3.11
 ---> cc0abc535e36
Step 2/3 : RUN echo "test" > test.txt
 ---> Running in b464b7527033
Removing intermediate container b464b7527033
 ---> 48f172bb83b9
Step 3/3 : LABEL foo=bar
 ---> Running in 8aa55c0e2fda
Removing intermediate container 8aa55c0e2fda
 ---> c76cda27bc0e
Successfully built c76cda27bc0e
Successfully tagged test:latest

maciek@baltazar:~/src/buildah-bugs/label-test$ docker build -t test --label foo2=bar2 .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine:3.11
 ---> cc0abc535e36
Step 2/3 : RUN echo "test" > test.txt
 ---> Using cache
 ---> 48f172bb83b9
Step 3/3 : LABEL foo2=bar2
 ---> Running in 5885823b37ec
Removing intermediate container 5885823b37ec
 ---> 06fa7b20a652
Successfully built 06fa7b20a652
Successfully tagged test:latest

maciek@baltazar:~/src/buildah-bugs/label-test$ docker inspect c76cda27bc0e | jq '.[].Config.Labels'
{
  "foo": "bar"
}

maciek@baltazar:~/src/buildah-bugs/label-test$ docker inspect 06fa7b20a652 | jq '.[].Config.Labels'
{
  "foo2": "bar2"
}
```

**Comment by mraszplewicz** [comment]
Hi,

I finally had enough time to learn some go basics and tried to implement a bugfix. I have some doubts:
1. If I implement what docker does - adding a new LABEL layer, it will invalidate my use case of using labels. I wanted to use them to find an image when build failed. I actually already implemented it and it looks a little bit "clever" or hacky - I am adding new parser.Nodes in stage_executor.go and it is breaking the current behaviour.
2. Current implementation adds labels to every layer but doesn't change them. Changing will cause problems with cache - new label added will always create new layers and cache will not be used. It is not an option for me - I want to use layers to avoid rebuilding things many time. 
3. Maybe failed build should also store iidfile? That would solve my problem without labels. 

Thanks for help!

**Comment by rhatdan** [comment]
@mraszplewicz Can we close this issue?

**Comment by mraszplewicz** [comment]
You can close it if you want. I really wanted to help, but my questions are still unanswered. The issue still exists.

I have switched back to building with docker build.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, let's not close this.  Hopefully we can around to it and take a look at some point in the future.

**Comment by jskovjyskebankdk** [comment]
Is this the same problem I see with podman, I wonder?

A label from the command line is ignored, if there are statements in the Containerfile:

```console
$ cat > Containerfile <<EOF
FROM docker.io/alpine:3.12.3
RUN echo "Hello World"
EOF

$ podman build --label dk.test=foo -f Containerfile 
STEP 1: FROM docker.io/alpine:3.12.3
STEP 2: RUN echo "Hello World"
Hello World
STEP 3: COMMIT
--> 5aa1705c33a
5aa1705c33a265cc21d18d457fa7b3eccd31be06b1a289e247886d2d5d37fbe3

$ podman build --label dk.test=bar -f Containerfile 
STEP 1: FROM docker.io/alpine:3.12.3
STEP 2: RUN echo "Hello World"
--> Using cache 5aa1705c33a265cc21d18d457fa7b3eccd31be06b1a289e247886d2d5d37fbe3
--> 5aa1705c33a
5aa1705c33a265cc21d18d457fa7b3eccd31be06b1a289e247886d2d5d37fbe3

```





Curiously, if there are no (RUN?) statements in the Containerfile, new images are created.
Each time - regardless of the label:


```console
$ cat > Containerfile.ok <<EOF
FROM docker.io/alpine:3.12.3
EOF

$ podman build --label dk.test=foobar -f Containerfile.ok
STEP 1: FROM docker.io/alpine:3.12.3
STEP 2: COMMIT
--> 4f70b9d0caf
4f70b9d0cafbfd642a101218df6a2e480edaf96935bc6f1c8a76619bc568d65f

$ podman build --label dk.test=foobar -f Containerfile.ok
STEP 1: FROM docker.io/alpine:3.12.3
STEP 2: COMMIT
--> 2bb0d8a1c9e
2bb0d8a1c9e8a3bc2e63b4d658b34a01aebef868163c987675534906d127e5f5
```

These differ by their "Created" timestamp.

**Comment by rhatdan** [comment]
@nalind This seems similar to the issue with no new layer being created. Ideas?

**Comment by nalind** [comment]
The exception that makes sure we commit an image when there are no instructions in the Dockerfile, but there are still labels or annotations are passed in from the CLI, doesn't take into account caching, since the cache evaluation logic expects to compare the instruction that's "currently" being processed with entries in a candidate image's history.

**Comment by rhatdan** [comment]
How do we fix this?

**Comment by rhatdan** [comment]
@nalind Any chance you could look at this?

**Comment by rhatdan** [comment]
@flouthoc didn't you get something in for this one?

**Comment by flouthoc** [comment]
This is resolved by https://github.com/containers/buildah/pull/3517

**Comment by flouthoc** [comment]
Closing this. Please re-open if this still persists.
