### ISSUE TITLE
List image contents without running it

### ISSUE THREAD

**Issue by abitrolly** [containers/buildah#2046]
Is there a way to list contents of an image downloaded from Docker Hub without running it?

I am looking for an alternative to `podman export` which works on images.

**Comment by rhatdan** [comment]
You can create a container and then mount it.

ctr=$(buildah from IMAGE)
mnt=$(buildah mount $ctr)
cd $mnt
and start looking at the image.

**Comment by abitrolly** [comment]
@rhatdan which means to run the container, right?

**Comment by rhatdan** [comment]
No the image is just mounted and you can go to the rootfs of the image and examine it with commands from the host.
For example
rpm -qa --root $mnt

To list all of the rpms on the system

find $mnt 

To list all of the files.

But you don't need to actually execute any code in the image.

**Comment by abitrolly** [comment]
Is it possible to work with the image without Linux kernel?

**Comment by rhatdan** [comment]
You could pull the image with skopeo as a tar ball, and then untar the layers.  
Containers/storage has some windows support also, so maybe you could pull an image onto Windows storage. 
Since I don't use non linux systems, I am not an expert in this.

**Comment by TomSweeneyRedHat** [comment]
I believe the questions have been answered, so I'm closing this PR.

**Comment by svenstaro** [comment]
I think frankly this should be reopened as the suggested method is too inconvenient and should not be accepted as-is. I think podman could easily provide a more developer-friendly alternative here.

**Comment by abitrolly** [comment]
@svenstaro [use `crane`](https://github.com/google/go-containerregistry/pull/1274).

```sh
brew install crane
crane export ubuntu - | tar -tvf -
```

Maybe `podman` can actually compile it it. I don't know.

**Comment by abitrolly** [comment]
Took me just 2.5 years of going without a job to scratch this itch. :D

**Comment by svenstaro** [comment]
Thanks but it's still a crutch. Podman should support it directly.

**Comment by rhatdan** [comment]
Podman does this too.

podman image mount
and
podman container mount

**Comment by svenstaro** [comment]
Huh didn't find that before. I guess that's good enough for me.
