### ISSUE TITLE
rootless podman build tries to use system-wide policy

### ISSUE THREAD

**Issue by mat8913** [containers/buildah#2054]
**Description**

Rootless podman supports reading policy from "~/.config/containers/policy.json", since non-root users cannot write to the system-wide policy file. `podman build` still tries to read the system-wide policy though.

**Steps to reproduce the issue:**
1. Don't have a system-wide policy
2. Run `podman build .` as a non-root user in a directory with a Dockerfile that you haven't already built (since otherwise, podman will just use the cached result)

**Describe the results you received:**

```
STEP 1: FROM docker.io/httpd:alpine
STEP 2: RUN echo AllowEncodedSlashes On >> /usr/local/apache2/conf/httpd.conf
STEP 3: COMMIT
Error: error committing container for step {Env:[PATH=/usr/local/apache2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HTTPD_PREFIX=/usr/local/apache2 HTTPD_VERSION=2.4.41 HTTPD_SHA256=133d48298fe5315ae9366a0ec66282fa4040efa5d566174481077ade7d18ea40 HTTPD_PATCHES=] Command:run Args:[echo AllowEncodedSlashes On >> /usr/local/apache2/conf/httpd.conf] Flags:[] Attrs:map[] Message:RUN echo AllowEncodedSlashes On >> /usr/local/apache2/conf/httpd.conf Original:RUN echo AllowEncodedSlashes On >> /usr/local/apache2/conf/httpd.conf}: error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
```

**Describe the results you expected:**

`podman build` should just use the policy from "~/.config/containers/policy.json" like every other podman command does.

**Output of `rpm -q buildah` or `apt list buildah`:**

I don't have rpm or apt

**Output of `buildah version`:**

I don't have buildah

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.6.3
RemoteAPI Version:  1
Go Version:         go1.13.5
Built:              Thu Jan  1 10:00:01 1970
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME=NixOS
ID=nixos
VERSION="20.03pre206137.f5bb6c02071 (Markhor)"
VERSION_CODENAME=markhor
VERSION_ID="20.03pre206137.f5bb6c02071"
PRETTY_NAME="NixOS 20.03 (Markhor)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/nixos/manual/index.html"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

**Output of `uname -a`:**

```
Linux gallium 5.4.5 #1-NixOS SMP Wed Dec 18 15:09:17 UTC 2019 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by rhatdan** [comment]
@QiWang19 Is this fixed now in podman build?  Will it read the local policy, I believe it does? Close if I am correct.

**Comment by QiWang19** [comment]
It's fixed. The policy.json under $HOME is used here https://github.com/containers/image/blob/7810876ebe28eb6ed405dbe825159b22781cf813/signature/policy_config.go#L64
