### ISSUE TITLE
"podman build" does not default to "." as context

### ISSUE THREAD

**Issue by rpjday** [containers/buildah#2056]
podman 1.6.2 on Fedora 31, even when there is a Dockerfile/Containerfile in the current directory, you need to specify the context directory ("."), otherwise:

$ podman build
Error: no context directory specified, and no containerfile specified
$

**Comment by rhatdan** [comment]
This is not a buildah issue.  `buildah bud` works correctly. It should be opened in libpod(podman).

Although I already fixed this in master, and I believe it is fixed in podman 1.7.0.

https://github.com/containers/libpod/pull/4697
