### ISSUE TITLE
Documentation - installing an image/container dev/runtime environment

### ISSUE THREAD

**Issue by devlocalca** [containers/buildah#2069]
**Description**

I am looking for documentation that lists a set of commands for RHEL 8, using `dnf` to:
```
1. install any RHEL 8 repos that have image/container tools
2. install those image/container tools
3. use and understand those image/container tools
```
I'm not sure that one exists, I have searched everywhere.

**Describe the results you expected:**

I am seeking a guide/documentation that can be easily found that is specific to my environment:  RHEL 8, using the `dnf` command.

---

This document does not work for me:

  https://github.com/containers/buildah/blob/master/install.md

as when I substitute `dnf` for `yum`, I get failures and packages not found.

It seems extremely outdated, referencing `RHEL 8 Beta`, which was released like a decade ago (2019), way back in the teens.

I read an article in a journal, then heard it on the radio, that the latest studies show that using `yum` on RHEL 8 causes cancer and wish to avoid it.

---

I would be happy to help update this document, given the correct information.

I am seeking to install a full image/container dev environment with all the bells and whistles using: buildah, podman, skopeo as the base, and anything else that is needed.

**Comment by rhatdan** [comment]
Does
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index 

Cover what you need? 

This is an upstream site,  we don't tend to document downstream distros.

**Comment by TomSweeneyRedHat** [comment]
@chrisnegus any other thoughts?

**Comment by chrisnegus** [comment]
@TomSweeneyRedHat The link that @rhatdan references is where I have consolidated documentation related to RHEL 8 container tools. Here are links to the specific features you are looking for:

1. install any RHEL 8 repos that have image/container tools

[Getting container tools](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#getting-container-tools_building-running-and-managing-containers)  Tells how to register and subscribe RHEL 8. No special repos are needed to get container tools for RHEL 8.

2. install those image/container tools
That same section tells how to install the basic set of container tools by installing the container-tools module. It uses the yum command, but actually calls dnf, so either would work. It doesn't install buildah, but I describe that later the the buildah section.

3. use and understand those image/container tools
Well, that would be the rest of the book. :-)

Let me know if there are specific features you are missing. I think most of the basics are there, but it's a bit thick and perhaps we should think about a quick start guide or similar.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Perhaps we should add a link to install.md to this document.

**Comment by devlocalca** [comment]
Thank you very much for the information.  I have seen this document before I believe.

One question/problem I have, is that the first action item is **Section 1.3** in running the subscription-manager.

I am running RHEL 8 on GCP (Compute Engine VM), paying the RHEL 8 license fees through a GCP/Red Hat license agreement.

On the VM - subscription-manager is not installed.

```
#which subscription-manager
/usr/bin/which: no subscription-manager in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

```
If I install subscription-manager,
`#dnf -y install subscription-manager`

then what login/password do I use?

I can create a developer account on RHEL, but what it really wants is a login/password for an account that has not a developer license, but a paid RHEL license.

I'm not sure how to navigate that, or attach my VM using subscription-manager to a license (not having purchased it through Red Hat, but through GCP).

That's on the host VM side, and the same questions exist now for the UBI container:

**In the container, when I do:**

`#dnf -y update`

I get:

```
Updating Subscription Management repositories.

Unable to read consumer identity

Subscription Manager is operating in container mode.

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 10:54:55 ago on Wed Jan  8 07:23:55 2020.

Dependencies resolved.

Nothing to do.

Complete!
```

How do I get my GCP VM - RHEL 8 installed with the right repos, subscribed/registered with the subscription manager, and the same for UBI containers?
---

**Comment by chrisnegus** [comment]
Unless there is a special way to use Red Hat repos through GCP, you get subscriptions through places like the [Red Hat Enterprise LInux](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux) subscription page. There are free trials available. All container tools should be ready to install at that point, without additional repos. Likewise, nothing special is needed to download and update UBI images since those images and related repos are fully available. Just "podman pull <path-to-UBI-image>" should get it.

**Comment by chrisnegus** [comment]
With the subscription, you will get a user name and password. You can use those credentials to get on to the [Red Hat customer portal ](https://access.redhat.com)as well.

**Comment by rhatdan** [comment]
I believe we are all set on this one.  Reopen if I am mistaken.
