### ISSUE TITLE
image digest in output when executing buildah inspect

### ISSUE THREAD

**Issue by artbegolli** [containers/buildah#2074]
**Description**

Running `docker image inspect <imageId>` returns metadata on the image, including the image digest.

In buildah, executing the (similarly) equivalent cmd `buildah inspect --type image <imageId>` equally returns metadata on the image, however without the image digest

This issue proposes adding an images' digest to a buildah inspect command as it is relevant image metadata - open to any thoughts as to why this would not be a good idea.

Below is an example of a few fields from running `docker image inspect`, including the image digest.
```
    {
        "Id": "sha256:1ea38172de324861326680a9316d56ba1f175833e049d58668ff9df5be6dbebe",
        "RepoTags": [
            "golang:1.6-alpine"
        ],
        "RepoDigests": [
            "golang@sha256:269d188232cd9a6194f71650780cb2e903a76958182def1008cc7255f6f457d6"
        ],
    }
```

If this is available in a later Buildah version feel free to close this issue.

**Steps to reproduce the issue:**
1. Run `buildah inspect --type image <imageId>`

**Describe the results you received:**
Json output of image metadata

**Describe the results you expected:**
Json output of image metadata including the image digest

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/xenial 0.12-2~ubuntu16.04.2~ppa1 amd64
```

**Output of `buildah version`:**

```
Version:       0.15
Go Version:    go1.8.7
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    9ff37b0
Built:         Mon Mar  5 11:14:16 2018
OS/Arch:       linux/amd64
```

**Comment by boaz0** [comment]
This is fixed in newer versions of buildah.
```
$ ./buildah inspect --type image golang:1.6-alpine                                                                                                                                 
{                                                                                                                                                                                              
    "Type": "buildah 0.0.1",                                                                                                                                                                   
    "FromImage": "docker.io/library/golang:1.6-alpine",                                                                                                                                        
    "FromImageID": "1ea38172de324861326680a9316d56ba1f175833e049d58668ff9df5be6dbebe",                                                                                                         
    "FromImageDigest": "sha256:269d188232cd9a6194f71650780cb2e903a76958182def1008cc7255f6f457d6",                                                                                              
```

version:
```
buildah version 1.14.0-dev (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)
```

**Comment by vrothberg** [comment]
Closing as Buildah v1.12 includes this information.
