### ISSUE TITLE
buildah Question

### ISSUE THREAD

**Issue by sjkeerthi** [containers/buildah#2083]
Hi Team,

It a Kind of Question.

1) Will my existing Dockerfile works without any changes in buildah

2) Is the as build-env will work for example
`FROM node:10.18.0-alpine3.11 as build-env

MAINTAINER sjkeerthi@xxxx.io

# Update the apk repo
RUN apk add --no-cache git

# Copy the local package files to the container's workspace.
COPY ./source /opt/portal

# Build the application using the npm install
RUN npm config set unsafe-perm true
RUN cd /opt/portal && npm install -g @angular/cli@6.1.4
RUN cd /opt/portal && npm install && ng build --base-href=/portal/ -c stage
RUN mv /opt/portal/dist/src /portal

# Distributed image
FROM nginx:alpine

MAINTAINER sjkeerthi@xxxx.io

RUN apk add --no-cache ca-certificates

# Copy angular build file to nginx folder
WORKDIR /usr/share/nginx/html/portal

COPY --from=build-env /portal /usr/share/nginx/html/portal

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
`
Will this dockerfile works without any changes. 

3) Where can I find the Doc of what are the Commands that available in 
buildah file

**Comment by TomSweeneyRedHat** [comment]
@sjkeerthi thanks for the interest in Buildah!

In theory, if the Dockerfile works with Docker, than it should also work with Buildah.  If you find that it does not, please feel free to raise an issue here on GitHub.    

Just a note, when you're building with Buildah and want to match the Docker build process, use the `--layers` option, ala `buildah bud --layers ...`.  Or if you want to be able to use more Docker like commands, then try out Podman (https://github.com/containers/libpod).  Podman calls Buildah to do it's `podman build` command.  That particular command uses the `--layers` option by default.

There's no documentation of the contents of the Dockerfile on the Buildah GitHub repo.  We just use the industry standard for Dockerfiles.

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this issue.  @sjkeerthi please feel free to open another issue if you have further questions or problems.
