### ISSUE TITLE
Copying executable to mounted filesystem doesn't work

### ISSUE THREAD

**Issue by georgek** [containers/buildah#2091]
If I mount a new container and copy in an executable, it is not available in the subsequent image. It does, however, work when using `buildah copy` instead.

**Steps to reproduce the issue:**
1. `container=$(buildah from scratch)`
2. `scratchmnt=$(buildah unshare buildah mount $container)`
3. `cp some_static_executable $scratchmnt/some_static_executable`
4. `buildah run $container ./some_static_executable` (works),
5. `buildah config --cmd ./some_static_executable $container`
6. `buildah commit $container image`
7. `podman run --rm image`

**Describe the results you received:**

`./some_static_executable: no such file or directory`

**Describe the results you expected:**

The static executable is found and run.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/bionic,now 1.10.1-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.10.1
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Thu Aug  8 21:29:48 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux local 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
Did you run your script as root or non-root?

**Comment by georgek** [comment]
All non-root.

**Comment by rhatdan** [comment]
Can you try to run your script under `buildah unshare`

**Comment by georgek** [comment]
It works if I run the whole script under `buildah unshare`. I thought it was only necessary when issuing the `buildah mount` command.

Is it recommended to always run scripts under `buildah unshare` when building without root? Maybe this should be added to the README section about rootless operation? The name "unshare" doesn't seem very intuitive (why is it called that?).

**Comment by rhatdan** [comment]
Any use of the mounted file system, requires the `buildah unshare`.
So at least
```
scratchmnt=$(buildah unshare buildah mount $container)
cp some_static_executable $scratchmnt/some_static_executable
```
Has to be done in the user namespace via `buildah unshare`

**Comment by jamescassell** [comment]
probably can solve this one by updating the docs to say that if your build process includes `buildah mount`, you must run the entire build process under a `buildah unshare` session for rootless.

**Comment by rhatdan** [comment]
Please open a PR to change the docs the way you would like.

**Comment by rhatdan** [comment]
Now if you run buildah mount $CID in rootless mode without the unshare it says

$ buildah mount working-container
cannot mount using driver overlay in rootless mode. You need to run it in a `buildah unshare` session

Man page also documents this.

```
buildah-mount(1)                                                                                         General Commands Manual                                                                                        buildah-mount(1)

NAME
       buildah-mount - Mount a working container's root filesystem.

SYNOPSIS
       buildah mount [container ...]

DESCRIPTION
       Mounts the specified container's root file system in a location which can be accessed from the host, and returns its location.

       If the mount command is invoked without any arguments, the tool will list all of the currently mounted containers.

       When  running  in  rootless mode, mount runs in a different namespace so that the mounted volume might not be accessible from the host when using a driver different than vfs.  To be able to access the file system mounted, you
       might need to create the mount namespace separately as part of buildah unshare.  In the environment created with buildah unshare you can then use buildah mount and have access to the mounted file system.

```

**Comment by jamescassell** [comment]
I'm curious whether it'd be possible to do a some sort of unprivileged fuse-mount for non-VFS drivers, but it probably should be its own feature...

**Comment by georgek** [comment]
Would this actually affect the commands in my bug report? Notice that I used: `scratchmnt=$(buildah unshare buildah mount $container)`.

**Comment by rhatdan** [comment]
scratchmnt=$(buildah unshare buildah mount $container).
As soon as the buildah unshare process finishes, the mount namespace that you mounted the buildah container within will exit and unmount the file system.
All interaction with the mount point has to happen while in a buildah unshare shell.

**Comment by georgek** [comment]
Yeah, I understand that, just pointing out that the additional warning for `buildah-mount` won't help someone who makes the same mistake as me.

**Comment by rhatdan** [comment]
Sure, do you have a suggestion, on how we could allow them not to make this mistake?
