### ISSUE TITLE
Cannot copy builder artifacts from amd64 image to arm32v7 image

### ISSUE THREAD

**Issue by djhworld** [containers/buildah#2093]
**Description**

I have a Dockerfile that looks like this 

```
FROM golang:1.13 as builder
RUN apt-get update -y && apt-get install -y binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf && mkdir -p /build

COPY ./ /build/
WORKDIR /build/

RUN env CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-cpp \
        CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 go build -ldflags "-linkmode external -extldflags -static" --tags fts5 -o dist/cmd .

FROM arm32v7/alpine:latest

COPY --from=builder /build/dist /app

WORKDIR /app/
ENTRYPOINT ["./cmd", "--content-dir", "/content"]
```
I've previously been able to build a Docker imagine in this way fine but since upgrading podman it's broken and refuses to work with the error

```
 Image architecture mismatch: image uses "arm", expecting "amd64"
```

**Steps to reproduce the issue:**
1. `podman build -t`

**Describe the results you received:**

Error

```
STEP 7: COPY --from=builder /build/dist /app
Error: error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[/build/dist /app] Flags
:[--from=builder] Attrs:map[] Message:COPY --from=builder /build/dist /app Original:COPY --from=builder /build/dist /app}: error copying layers and metadata f
or container "e751a826baceab1d6ebde47a9094d76d7fc6b070cead757137e4a2a41510d381": Image architecture mismatch: image uses "arm", expecting "amd64"
```

**Describe the results you expected:**

Image builds fine as it did before (`<= 1.7.0`)

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 1.7.0
```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
NAME=Fedora
VERSION="31 (Server Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Server Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux nuc1 5.4.8-200.fc31.x86_64 #1 SMP Mon Jan 6 16:44:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vrothberg** [comment]
@djhworld, thanks for taking the time to open the issue.

>  Image architecture mismatch: image uses "arm", expecting "amd64"

The containers/image library is now doing some more rigorous checks of the os and architecture of a given image. As you're running an amd64 machine, Podman defaults to expecting amd64 images. If you want to force a non-native architecture, we can use `FROM --architecture=$ARCH $IMAGE` in the Dockerfile.

Unfortunately the `--architecture` part doesn't seem to work in Buildah.
```Dockerfile
FROM --architecture=arm arm32v7/alpine:latest
RUN echo "FOOO" > /foo.txt
```
```
$ podman build -f Dockerfile .
... Image architecture mismatch: image uses "arm", expecting "amd64"
```
@TomSweeneyRedHat @nalind @rhatdan PTAL

**Comment by rhatdan** [comment]
Is this being worked on here? https://github.com/containers/buildah/pull/2097

**Comment by vrothberg** [comment]
> Is this being worked on here? #2097

No, that's another issue. #2097 relates to building an image and setting the os/arch here.

In this issue here the problem is that we are ignoring flags passed to the `FROM` stage, so we cannot control which image (os/arch) is being pulled.

**Comment by vrothberg** [comment]
I skimmed the `imagebuildah` code and it seems straight-forward to support parsing the flags but there is quite a number of internal maps used to cache and map images (and IDs), so I prefer @TomSweeneyRedHat and/or @nalind to have a look.

**Comment by rhatdan** [comment]
@vrothberg Wasn't the containers/image verify the arches loosened?

**Comment by vrothberg** [comment]
Yes, that's working now :+1:
