### ISSUE TITLE
digest test: needs a complete rewrite

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2147]
`tests/digest.bats` is confusing, misleading, and unreliable.

First, per Nalin, the goal of this test:

>We're checking that a given image can be pulled, used as a base image for a build, and that a new image that we build using that pulled image as a base can successfully be pushed to somewhere other than local storage, when the image is:
>
 >  * a v2s1 image referenced using its digest
 >  * a v2s1 image where one of the entries is a duplicate that gets discarded when it's converted to v2s2
> * a v2s1 image referenced using its tag
> * a v2s2 image referenced using its digest (incorrectly - this is also a v2s1 image, alpine@sha256:25fd8fc1aefcc8ae46aae23daefcd7dcb97f676fa0bc72bb0bf7cfb75df4f22e is a better candidate)
> * a v2s2 image referenced using its tag (incorrectly - this is the same v2s1 image, alpine:3.1 is a better candidate, though it's a manifest list now, so the test won't pass on non-amd64 systems without tweaks.
> * a v2s2 image referenced using its repository name, with neither a tag nor a digest. It's a manifest list, so the test won't pass on non-amd64 systems without tweaks.

The problems I see:

* as admitted above, the actual tests are wrong: several of the tests labeled "s2" are actually s1. This took me __far__ too long today to actually figure out.
* In addition, the current test script does not actually confirm `schemaVersion`. If a test is labeled "s2", it should darn well confirm that it is testing what it should be testing.
* Nor does the test script confirm that the image it's testing as "duplicate layers" actually has duplicate layers
* Some of the images are fetched by SHA, but others by name, making them moving targets
* And they're fetched from all sorts of different registries, some of which are unreliable, which gives us flaky tests
* And at least one of the images is HUGE, a monster, which of course slows everything down
* ~~Oh, I forgot: Nalin says "somewhere other than local storage" but the test doesn't actually test that: it only pushes to local storage.~~ Sorry, my misunderstanding. Per @nalind, `dir:XXX` exercises all the desired code paths - I misunderstood "local storage".

I believe that all images used in this test should be consistent, constant, guaranteed immutable, under our control, and from one and only one registry (presumably quay.io) (which, yes, is unreliable but SPOF is better than MPOF).

To that end, I propose something like this: a git-committed script that generates the desired images and pushes them to a repo. This script would be run only manually and only if/when the `digest.bats` test needs a new example image. The example below tries to create an image suitable for the `from-by-digest-s1-a-discarded-layer` test:
```bash
# Create a v2s1 image. We can't actually do that with buildah; the only way
# seems to be to create a v2s2, dir-push it as v2s1, then reload it.
cid=$(buildah from scratch)
buildah commit $cid foo1

# Same thing (duplicate layer)
cid2=$(buildah from foo1)
buildah commit $cid2 foo2

cid3=$(buildah from foo2)
mp=$(buildah mount $cid3)
touch $mp/file1
buildah umount $cid3

buildah commit $cid3 foo3

TMPDIR=$(mktemp --tmpdir -d $(basename $0).XXXXXXX)

buildah push --format v2s1 foo3 dir:${TMPDIR}/foo3

# Clean up
buildah rm -a
buildah rmi foo3 foo2 foo1

# Reload the image
(cd $TMPDIR && buildah pull dir:foo3)

# We should now have a 'localhost/foo3' image with SchemaVersion 1
echo "The following number should be '1':"
buildah-imgtype -expected-manifest-type '*' -show-manifest  localhost/foo3 | jq .schemaVersion

# FIXME: we should also check that there are two duplicate fsLayers
buildah-imgtype -expected-manifest-type '*' -show-manifest  localhost/foo3 | jq .fsLayers|grep blobSum|sort|uniq -c

# Assuming the two tests above pass, we could then push this image to quay.io

# Clean up
rm -rf ${TMPDIR}
```
Yes, it can (and should) be cleaned up. This is a simple checkpoint before I wrap up for the week, to (a) remind me when I pick this up again, and (b) offer an early chance for everyone to comment or shoot down as appropriate.

**Comment by edsantiago** [comment]
@nalind @cevich @TomSweeneyRedHat  comments/feedback welcome

**Comment by cevich** [comment]
@edsantiago your bullet-points in the description are all on-the-money.  Please feel free to do what's needed with libpod repositories on quay.  Historically it's been far more reliable than either fedoraproject.org or docker.io (whatever the cause).

There's also local registry available.  After #2115 merges, it is [setup here](https://github.com/containers/buildah/blob/master/contrib/cirrus/lib.sh#L259) and [populated/validate here](https://github.com/containers/buildah/blob/master/contrib/cirrus/lib.sh#L235).  Failure of that service will quickly fail tests, so it's even "safer" than quay.

The tests are executed from [the 'integration' case here](https://github.com/containers/buildah/blob/master/contrib/cirrus/test.sh#L44), feel free to export any variables/values needed for automation -> test communication.  For example querying and passing in an image digest value which could change if your build script is re-run (assuming that's still needed in the tests).

HTH
