### ISSUE TITLE
make install.cni.sudo fails

### ISSUE THREAD

**Issue by mythi** [containers/buildah#2153]
**Description**
The CNI git tree has no `build.sh` anymore so `make install.cni.sudo` fails.

**Steps to reproduce the issue:**
1.  `make install.cni.sudo` 

**Workaround:**
1.  `sed -i -e 's/build\.sh/build_linux\.sh/' Makefile`
2. `make install.cni.sudo`

**Comment by rhatdan** [comment]
Please open a PR to fix?

**Comment by mythi** [comment]
Done.
