### ISSUE TITLE
PATH being reset

### ISSUE THREAD

**Issue by astronouth7303** [containers/buildah#2158]
**Description**

`$PATH` is being reset from the image and container config.

This is possibly related to https://github.com/containers/libpod/issues/4812

**Steps to reproduce the issubuildae:**
1. `buildah from rust:buster`
2. `buildah config $c` (Notice `Config.config.Env` and `Config.container_config.Env`)
3. `buildah run $c -- env`

The config lists:
 `PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` 
but `env` shows: 
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`. 

No other environment changes were found. 
(The host was 
`PATH=/home/astraluma/.cargo/bin:/home/astraluma/.poetry/bin:/home/astraluma/.local/bin:/home/astraluma/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/astraluma/.local/xonsh/bin:/home/astraluma/.cargo/bin:/usr/sbin`)

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/unknown,now 1.13.2~1 amd64 [installed]
buildah/unknown 1.13.2~1 arm64
buildah/unknown 1.12.0-6 armhf
buildah/testing 1.10.1-5 i386
buildah/unknown 1.13.2~1 ppc64el
```

**Output of `buildah version`:**

```
Version:         1.13.2
Go Version:      go1.13.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.1.0
Git Commit:      
Built:           Sat Feb  1 11:04:36 2020
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux cayde7 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
Seems to work with 1.12.0 on fedora 31

$ buildah --version
buildah version 1.12.0 (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)

$ buildah run $c env
PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by rhatdan** [comment]
Broken in master.
 ./buildah --version
buildah version 1.15.0-dev (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)
[dwalsh@localhost buildah]$ ./buildah run $c env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by TomSweeneyRedHat** [comment]
It's probably end of day brain, but just want to check what I'm seeing.
When I do:

```
buildah from rust:buster
buildah run rust-working-container -- env

buildah config rust-working-container
buildah run rust-working-container -- env
```

The path I'm seeing does not have `/usr/local/cargo/bin` either before or after the config is run.  However, if I do : `buildah inspect rust-working-container | grep PATH`  I see `/usr/local/cargo/bin` in that output.  

Is that what you two are seeing?  Based on the description, I thought `cargo/bin` would be shown before the `buildah config` call, but not after.

**Comment by TomSweeneyRedHat** [comment]
I should have said if I do the inspect command before or after the config, I'm seeing `cargo/bin`

**Comment by astronouth7303** [comment]
I think you got some end of the day brain. I did not mean "the right invocation of commands will change PATH". I did mean "depending on how you ask, PATH will have different values".

**Comment by nalind** [comment]
Bisecting points to #2011 as the point where this breaks.  @TomSweeneyRedHat mind if I take this one?

**Comment by rhatdan** [comment]
It's yours.

**Comment by astronouth7303** [comment]
I just want to thank you for fixing this because I keep bumping into it and I cannot wait for a release.

**Comment by astronouth7303** [comment]
That PR also fixes this case, right?

```
🐚 c=`buildah from rust:buster`
🐚 buildah config --env PATH=spam:eggs $c
🐚 buildah run $c /usr/bin/env
RUSTUP_HOME=/usr/local/rustup
CARGO_HOME=/usr/local/cargo
RUST_VERSION=1.41.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=
HOME=/root
```
