### ISSUE TITLE
Please use /tmp instead of /run/user/${uid} as runtime or temp path

### ISSUE THREAD

**Issue by andrew-aladev** [containers/buildah#2165]
Hello. It is not possible today to use rootless `buildah` with `screen` or `tmux`.

1. Make login using `ssh host`.
2. `mount | grep /run/user`:
`none on /run/user/1000 type tmpfs (rw,relatime,mode=700,uid=1000)`
3. `sudo umount /run/user/1000`.
4. `exit`.
5. Make login using `ssh host` once again.
6. `mount | grep /run/user`:
`none on /run/user/1000 type tmpfs (rw,relatime,mode=700,uid=1000)`

We can see that `/run/user/1000` will be just re-mounted after user re-login. It makes impossible to use (at least rootless) `buildah`. I will write here how to reproduce it in details:

1. Make login using `ssh host`.
2. Run `tmux` session.
3. Run `buildah unshare something` inside `tmux` session.
4. Detach from `tmux` sesion and `exit` from `host`.
5. Go to another computer.
6. Make re-login using `ssh host`.
7. Attach to the existing `tmux` session.

```
ERRO[0000] mkdir /var/run/user/1000: permission denied
```

You may see other strong errors related to `/run/user/1000`, but it is not important. This folder was just re-mounted and all previous content was lost. Please do not use `/run/user` anywhere, use `/tmp` instead.

**Output of `buildah version`:**

```
buildah version 1.14.0 (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)
```

**Output of `uname -a`:**

```
Linux mini 5.5.4-gentoo #1 SMP Sat Feb 15 15:38:00 +03 2020 x86_64 AMD Ryzen 5 3400G with Radeon Vega Graphics AuthenticAMD GNU/Linux
```

**Comment by andrew-aladev** [comment]
I am proposing the following patch https://gist.github.com/andrew-aladev/ff07c2ce331fba96918b0a8af62f6afd

**Comment by rhatdan** [comment]
Please open an issue in github.com:/containers/storage 
The buildah name will get rejected there.
