### ISSUE TITLE
Crash on custom TMPDIR env var

### ISSUE THREAD

**Issue by offbynull** [containers/buildah#2166]
**Description**

Running the following buildah with a custom TMPDIR env var leads to buildah erroring out with a strange error...

```
buildah --root /home/user/markdown-notes/.cache/container_env_8a2b91a604b181956571d112b518f256/root --runroot /home/user/markdown-notes/.cache/container_env_8a2b91a604b181956571d112b518f256/runroot --registries-conf /home/user/markdown-notes/.cache/container_env_8a2b91a604b181956571d112b518f256/conf/registries.conf --registries-conf-dir /home/user/markdown-notes/.cache/container_env_8a2b91a604b181956571d112b518f256/conf/registries.d containers --noheading --notruncate --format {{.ContainerName}}
```

it fails with the following error...

```
Error loading container config cannot stat /root/.config/containers/storage.conf: stat /root/.config/containers/storage.conf: permission denied
```

All the directories referenced in the arguments were created prior to the command running. It's my understanding that Buildah shouldn't be accessing `/root` at all given that I'm setting both the --root and --runroot options to a subdir in my home dir.

**Steps to reproduce the issue:**
1. Set TMPDIR env var to a custom subdirectory under /tmp (e.g. /tmp/test123)
2. Run a buildah containers command isolated to a specific root / runroot / conf directory

**Describe the results you received:**

See error in description. /root shouldn't be getting accessed.

**Describe the results you expected:**

A successful run.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Listing... Done
buildah/disco,now 1.10.1-1~ubuntu19.04~ppa1 amd64 [installed]
buildah/disco 1.10.1-1~ubuntu19.04~ppa1 i386
```

**Output of `buildah version`:**

```
buildah version 1.10.1 (image-spec 1.0.1, runtime-spec 1.0.1-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```

**Output of `uname -a`:**

```
Linux user-VirtualBox 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by nalind** [comment]
I'm not sure `$TMPDIR` is involved here, since it isn't used when computing the path of the `storage.conf` configuration file.  Usually that's going to be affected by `$HOME`.  If changing `$HOME` to point to a directory that you have access to doesn't prevent the error, can you paste the output of `env` so that I can hopefully more easily reproduce the problem?

**Comment by offbynull** [comment]
Ahhh I think you're correct. It seems other than TMPDIR, my environment variables were getting thrown away.

Apologies for the faulty report and thank you for the quick response.
