### ISSUE TITLE
Podman 1.6.4 complains about systemd cgroup flag (1.4.2 worked)

### ISSUE THREAD

**Issue by mathstuf** [containers/buildah#2171]
**Description**

`podman build` now fails where it used to succeed.

Build script: https://gitlab.kitware.com/cmb/cmb-superbuild/blob/master/.gitlab/ci/build-cmb-image.sh
Dockerfile being used: https://gitlab.kitware.com/cmb/cmb/tree/master/.gitlab/ci/docker/fedora31
Working build: https://gitlab.kitware.com/cmb/cmb-superbuild/-/jobs/4804800 (podman 1.4.2)
Broken build: https://gitlab.kitware.com/cmb/cmb-superbuild/-/jobs/4813943 (podman 1.6.4)

**Steps to reproduce the issue:**
1. Building an image inside gitlab-ci container (using Docker and --privileged)

**Describe the results you received:**

```
 error running container: error creating container for [/bin/sh -c sh /root/install_deps.sh]: time="2020-02-17T22:38:05Z" level=error msg="systemd cgroup flag passed, but systemd support for managing cgroups is not available"
systemd cgroup flag passed, but systemd support for managing cgroups is not available
: exit status 1
```

**Describe the results you expected:**

A build image :) .

**Output of `podman version` if reporting a `podman build` issue:**

Package version:

```
podman-1.6.4-2.module_el8.1.0+272+3e64ee36.x86_64
```

**Output of `cat /etc/*release`:**

CentOS 8 container (`centos:8`)

**Output of `uname -a`:**

CentOS 8 in the container, host has `5.4.18-100.fc30.x86_64`

**Output of `cat /etc/containers/storage.conf`:**

CentOS 8 defaults.

**Comment by mathstuf** [comment]
If I use Fedora 30 which has podman 1.7.0 I get this problem as well. I don't know if #2175 is masking this issue or it has been fixed in 1.8.0 and that issue is its next roadblock.

**Comment by TomSweeneyRedHat** [comment]
Please see the suggestions in #2175

**Comment by rhatdan** [comment]
Newer versions of podman and Buildah are available for RHEL/CentOS Closing.
