### ISSUE TITLE
TODO: Fix & Re-enable unit-testing

### ISSUE THREAD

**Issue by cevich** [containers/buildah#2193]
**Description**

Unit-testing is currently forced-passing since they constantly fail, for example:
https://cirrus-ci.com/task/4798516614660096?command=unit_test#L30

**Steps to make unit-testing result count:**
1. Edit `.cirrus.yml`
2. Remove `|| true` from `unit_test_script`

**Describe the results you received:**

[unit_test.log](https://github.com/containers/buildah/files/4268477/unit_test.log)

**Describe the results you expected:**

All tests should pass, or Cirrus-CI task should be marked as a failure.

**Comment by rhatdan** [comment]
@cevich I don't see this in the cirrus.yml file so I am going to assume that this is fixed.  Reopen if I am mistaken.

**Comment by cevich** [comment]
Confirming...actually yes, I see they're running and passing on master.
