### ISSUE TITLE
Kubic Repository Broken

### ISSUE THREAD

**Issue by computator** [containers/buildah#2195]
I'm not exactly sure where to report this, but I know I have seen several packaging related bugs here before.

I've been using the Kubic repository mentioned in the instructions for awhile, but it seems to be stuck on version 1.13.2. I am using Ubuntu 18.04 and the build seems to be [successful](https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/buildah), it's just outdated.

It looks like the build might be being maintained by @lsm5?

**Comment by lsm5** [comment]
@computator right place to report this, and I just built 1.14.1 https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/buildah . Sorry about the delay.
