### ISSUE TITLE
[question] Alternative runtimes

### ISSUE THREAD

**Issue by astronouth7303** [containers/buildah#2207]
Ok, this is strictly a question, not a change request. (Of course, all such questions can be considered a bug in documentation.)

I'm currently building a service that uses buildah as part of its work. As part of beefing up security, I would like to replace a basic container-based approach with something hypervisor-based. [The OCI runtime spec](https://github.com/opencontainers/runtime-spec/blob/master/implementations.md) list several hypervisor-base implementations. (Although gVisor might use userspace linux instead of strictly being a hypervisor.)

Is buildah strictly OCI-compliant with regards to how it calls its runtime? On a scale of "Tested to work" to "I'm pretty sure it won't work", would buildah work with hypervisor-based runtimes?

**Comment by rhatdan** [comment]
Theoretically it would work, but I think a smarter idea would be to run buildah within a container for highest security.
Running buildah within a Kata container for example.

**Comment by astronouth7303** [comment]
Oh kata might be able to do that.

I'm used to "containers in containers" needing privileged containers, which is the security equivalent of asking politely.

I will read up on that.

**Comment by rhatdan** [comment]
I wrote a lot on buildah inside of a container here.
https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/

**Comment by rhatdan** [comment]
Since blog has been posted, closing.
