### ISSUE TITLE
buildah shows build-arg values in final image of multi-stage build

### ISSUE THREAD

**Issue by mlinnalampi** [containers/buildah#2210]
**Description**

When doing multi-stage builds, Buildah shows the build-arg -variable values it has received in the final image. This is not the behaviour docker build has. The use case was passing build time credentials from Jenkins to buildah and hiding them from the final image, so this is undesired.

I simplified the dockerfile to minimum to demonstrate the issue. Overwriting the value with ENV in builder -stage does not change the output in second stage, so I guess this is probably due to build-arg -handling.

Dockerfile used:

```
from alpine:latest as builder

ARG SECRET

RUN touch /tmp/file

from alpine:latest

COPY --from=builder /tmp/file /tmp/file

RUN apk update
```
Docker build command
`docker build -t simple-docker --build-arg SECRET="kissa123" .`

Buildah build command
`buildah build-using-dockerfile  -t simple-buildah --build-arg SECRET="kissa123" .`

**Describe the results you received:**
```
[vagrant@localhost simple]$ podman history --no-trunc localhost/simple-buildah --format="{{.CreatedBy }}"
|1 SECRET=kissa123 /bin/sh -c apk update
/bin/sh -c #(nop) COPY file:baccd90931c4c200e3cb7453974fe6e01dbe45e47b6754b8a540d6eca976cfba in /tmp/file
/bin/sh -c #(nop) CMD ["/bin/sh"]
/bin/sh -c #(nop) ADD file:e69d441d729412d24675dcd33e04580885df99981cec43de8c9b24015313ff8e in /

```

**Describe the results you expected:**
```
[vagrant@localhost simple]$ docker history --no-trunc simple-docker --format="{{.CreatedBy }}"
/bin/sh -c apk update
/bin/sh -c #(nop) COPY file:e29d5c9f00a7d18d5705c28f95d7aaa320cc846ec833f9ab00036f292a30f637 in /tmp/file 
/bin/sh -c #(nop)  CMD ["/bin/sh"]
/bin/sh -c #(nop) ADD file:e69d441d729412d24675dcd33e04580885df99981cec43de8c9b24015313ff8e in / 
```

**Output of `rpm -q buildah`**

```
buildah-1.14.0-1.1.el8.x86_64
```

**Output of `buildah version`:**

```
Version:         1.14.0
Go Version:      go1.12.12
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.2.0
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64

```

**Output of `cat /etc/*release`:**

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

CentOS Linux release 8.1.1911 (Core) 
CentOS Linux release 8.1.1911 (Core) 

```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

Omitting all comments, this file has not been changed from defaults
```
[storage]

driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"

[storage.options.thinpool]
ostree_repo = ""

skip_mount_home = "false"
```

**Output of `docker --version` for reproducing**
`Docker version 19.03.7, build 7141c199a2`

**Comment by TomSweeneyRedHat** [comment]
@mlinnalampi thanks for the problem report.  
To fully emulate a `docker build` command, you need to add the `--layers` option to `buildah bud` command.  Are you seeing the same behavior if you do `bulidah bud --layers ...`?

**Comment by mlinnalampi** [comment]
@TomSweeneyRedHat Thanks for your reply! I deleted the image, built it with --layers option and saw the same behavior:

```
[vagrant@localhost simple]$ buildah bud --layers -t simple-buildah --build-arg SECRET="kissa123" .
...
[vagrant@localhost simple]$ podman history --no-trunc localhost/simple-buildah --format="{{.CreatedBy }}"
|1 SECRET=kissa123 /bin/sh -c apk update
/bin/sh -c #(nop) COPY file:c66dad98ef5c1ac4c94cfc584483d667ba4306d435e649f4fe8bfb4da4b08552 in /tmp/file
/bin/sh -c #(nop) CMD ["/bin/sh"]
/bin/sh -c #(nop) ADD file:e69d441d729412d24675dcd33e04580885df99981cec43de8c9b24015313ff8e in /

```

**Comment by TomSweeneyRedHat** [comment]
Well drats, so much for the quick easy fix.

**Comment by carbonin** [comment]
So I took a look at this as this is also an issue for me and it looks like args are actually usable across stages with `buildah`

Here's an example that removes the complexity of querying the image history:
```bash
$ cat Dockerfile 
FROM alpine
ARG THING

FROM alpine
RUN echo "$THING" > things
$ docker build --no-cache --build-arg THING=things .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM alpine
 ---> e7d92cdc71fe
Step 2/4 : ARG THING
 ---> Running in 54f1cea71a2a
Removing intermediate container 54f1cea71a2a
 ---> daa356eb264d
Step 3/4 : FROM alpine
 ---> e7d92cdc71fe
Step 4/4 : RUN echo "$THING" > things
 ---> Running in 40bbce12a352
Removing intermediate container 40bbce12a352
 ---> 00f291586fef
Successfully built 00f291586fef
$ docker run --rm 00f291586fef cat things
                      
$ buildah bud --layers --build-arg THING=things
STEP 1: FROM alpine
STEP 2: ARG THING
--> Using cache 232af6ca4a94e52dbef13f6da08c62b4172eaff7ee2e93cab08aceb4b00e6f81
STEP 3: FROM alpine
STEP 4: RUN echo "$THING" > things
--> Using cache fad9788d65a3062cc823516c8fff73b39e914463c709149a2855cbea61a10abe
fad9788d65a3062cc823516c8fff73b39e914463c709149a2855cbea61a10abe
$ podman run --rm fad9788d65a3062cc823516c8fff73b39e914463c709149a2855cbea61a10abe cat things
things
```

I suspect the issue is actually [here](https://github.com/openshift/imagebuilder/blob/22563141c8d69c0112fa3a4a055952c985c2c31a/builder.go#L213) in the `imagebuilder` library. That line seems to be pushing the args from the command line down to every stage's builder object.

Thoughts @TomSweeneyRedHat ?
I noticed you're in the history of that file as well.

Looks like it was added in https://github.com/openshift/imagebuilder/pull/59

**Comment by rhatdan** [comment]
If you remove that line, does your build work properly?

**Comment by carbonin** [comment]
Actually @rhatdan I might have been able to fix it.

Opened https://github.com/containers/buildah/pull/2220 with a test case and a small patch to the vendored `openshift/imagebuilder` library that I think will do the job.

I'm curious if that change will fail any other tests.

**Comment by carbonin** [comment]
Also, just for the record here's a snippet from the Docker docs about this behavior:

https://docs.docker.com/engine/reference/builder/#scope
> An ARG instruction goes out of scope at the end of the build stage where it was defined. To use an arg in multiple stages, each stage must include the ARG instruction.

**Comment by rhatdan** [comment]
Nice let's open the PR in imagebuilder and we can get this moving along.

**Comment by carbonin** [comment]
Opened https://github.com/openshift/imagebuilder/pull/151
