### ISSUE TITLE
buildah unshare failing with  "exec format error"

### ISSUE THREAD

**Issue by kushalagrawal** [containers/buildah#2218]
Hi,

I wanted to create a nonroot user while creating container image, therefore i was trying the example given at below link.
https://github.com/containers/buildah/blob/master/docs/buildah-unshare.md

At first it failed with ** executable file not found in $PATH**

```
ERRO[0000] exec: "buildah-script.sh": executable file not found in $PATH
ERRO[0000] (unable to determine exit status)
ERRO[0000] exit status 1
```

Later when I added current directory in path using PATH=$PATH:`pwd`. it went to next step but it failed again with below error:

```
buildah unshare buildah-script.sh
ERRO[0000] fork/exec /root/kushal/buildah/buildah-script.sh: exec format error
ERRO[0000] (unable to determine exit status)
ERRO[0000] exit status 1

```

this is my buildah version details:

```
buildah version
Version:         1.9.0
Go Version:      go1.10.3
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

I am using CentOS Linux release 7.6.1810 (Core).
https://github.com/containers/buildah/issues/475 had the same issue but it was resolved by using the different systems.

**Comment by kushalagrawal** [comment]
one more thing. if I execute the same thing under `buildah unshare` command prompt it works.

**Comment by rhatdan** [comment]
is this buildah-script.sh set as an executable?
Does it have `#!/bin/sh` inside of it?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan That's indeed the problem.  Also due to a change in the recent past, "IMAGENAME" needs to be changed to "imagename".

I'll work up a PR shortly.
