### ISSUE TITLE
buildah unable to push image loaded from tar file to AWS ECR 

### ISSUE THREAD

**Issue by bartdenotte** [containers/buildah#2234]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Trying to push docker image to AWS ECR. The Image is loaded via buildah pull docker-archive and pushed via buildah push after tagging.

**Steps to reproduce the issue:**
0. create repo via aws ecr cli
1. docker pull alpine:latest (from docker.io)
2. docker save alpine:latest -o /tmp/alpine.tar
3. buildah login -u AWS -p .... _aws_repo_url_
4. buildah pull docker-archive:/tmp/alpine.tar
5. buildah tag alpine:latest _aws_repo_url_/repo/alpine:latest
6. buildah push --format=docker docker://_aws_repo_url_/repo/alpine:latest

**Describe the results you received:**
Copying blob 5216338b40a7 done
error pushing image "e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a" to "docker://9999999999.dkr.ecr.eu-central-1.amazonaws.com/tst-company-image-file/test:0.1": error copying layers and metadata from "containers-storage:[vfs@/opt/ansible/var/lib/containers/storage+/opt/ansible/var/run/containers/storage]@e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a" to "docker://9999999999.dkr.ecr.eu-central-1.amazonaws.com/tst-company-image-file/test:0.1": Error writing blob: Error determining upload URL: http: no Location header in response

**Describe the results you expected:**
Image stored in AWS ECR repo

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `buildah version`:**
Version:         1.11.6
Go Version:      go1.12.12
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
**Output of `buildah info --debug`:**
{
    "debug": {
        "buildah version": "1.11.6",
        "compiler": "gc",
        "git commit": "",
        "go version": "go1.12.12"
    },
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "\"rhel\"",
            "version": "8.1"
        },
        "MemTotal": 8257527808,
        "MenFree": 956706816,
        "OCIRuntime": "runc",
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 2,
        "hostname": "bluebench-7685c546c8-4spbl",
        "kernel": "4.14.154-128.181.amzn2.x86_64",
        "os": "linux",
        "rootless": true,
        "uptime": "178h 40m 3.7s (Approximately 7.42 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "vfs",
        "GraphOptions": null,
        "GraphRoot": "/opt/ansible/var/lib/containers/storage",
        "GraphStatus": {},
        "ImageStore": {
            "number": 1
        },
        "RunRoot": "/opt/ansible/var/run/containers/storage"
    }
}

**Package info (e.g. output of `rpm -q buildah` or `apt list podman`):**
buildah-1.11.6-4.module_el8.1.0+272+3e64ee36.x86_64
**Additional environment details (AWS, VirtualBox, physical, etc.):**
kubernetes pod running on AWS EKS

**Comment by TomSweeneyRedHat** [comment]
@bartdenotte thanks for the issue!
@mtrmac is this related to https://github.com/containers/skopeo/issues/851?

**Comment by nalind** [comment]
This looks like an error encountered while attempting to upload a layer blob to an already-created repository, whereas https://github.com/containers/skopeo/issues/851 was about getting a `The repository with name '{{ NEW REPO NAME }}' does not exist in the registry with id '{{ AWS ACCOUNT}}'` error while attempting to push to a repository that hasn't been created yet.

When I try copying an image to a scratch registry that I created using the AWS console (with buildah, or with skopeo with `docker://busybox` as the source reference), I don't hit an error.  I do get the `The repository with name '{{ NEW REPO NAME }}' does not exist in the registry with id '{{ AWS ACCOUNT}}'` error when I don't create the repository first, or in my case, if I delete the repository and then try to push an image to it.

**Comment by mtrmac** [comment]
Yeah, the is clearly different from containers/skopeo#851, and I can’t remember seeing such a failure. It does not make much sense for the status to be “success” without a `Location` header, the client is required keep using fresh values of that header.

Is this reproducible at will? Any proxy on the path to ECR?

**Comment by bartdenotte** [comment]
Case closed, was a ECR permission issue

**Comment by tkant** [comment]
what permission were you missing?  @bartdenotte
