### ISSUE TITLE
2216 broke gating tests

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2235]
Gating tests are broken on [f31](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-f31-build-pipeline/detail/fedora-f31-build-pipeline/1064/pipeline/#step-247-log-882) and [f32](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-f32-build-pipeline/detail/fedora-f32-build-pipeline/138/pipeline/#step-248-log-888):
```
not ok 63 bud-volume-ownership
...
exec container process (missing dynamic library?) `/usr/bin/test-ownership`: No such file or directory
```
The bud-volume-ownership test is new, added in #2216. @carbonin PTAL.

**Comment by rhatdan** [comment]
Any idea what library it is erroring out on?

**Comment by edsantiago** [comment]
I couldn't figure it out, but I didn't spend much time on it. It's just a shell script running `stat`.

**Comment by rhatdan** [comment]
yes, very strange.

**Comment by carbonin** [comment]
I could change the test so that it's not using a script added to the container. Other tests that pass seem to be doing that, but they all pass for me (and on CI) so I'm not sure how to verify a fix for your environment.

I'll make that PR and maybe you can test that directly @edsantiago ?

**Comment by edsantiago** [comment]
@carbonin this isn't "my" environment, or one I have any control over: this is the universal Fedora gating-test setup, which is essentially a Fedora VM with the `buildah-tests` RPM installed. Could you try running your test on f31 and f32, and seeing if you can reproduce the failure? Then if you can reproduce the failure, you can work toward solving it.

**Comment by rhatdan** [comment]
You could eliminate script altogether by executing
podman run ... stat -c "%U %G"  /vol/subvol
And comparing it to "testuser testgroup"

**Comment by carbonin** [comment]
Yeah, that was the plan @rhatdan 

@edsantiago sure. I'm developing on f30, and it works there, but I can spin up some vms to test on the others.

**Comment by carbonin** [comment]
Opeend https://github.com/containers/buildah/pull/2236

**Comment by edsantiago** [comment]
>I'm developing on f30

This might be an indicator of a real `crun` problem, then; I'm just surprised that no other tests failed (except for one of the usual flakes). I'll try to take a look.

**Comment by edsantiago** [comment]
RCA: this might be an RPM packaging problem. In the `buildah-tests-1.14.3-1.fc31.x86_64` rpm:
```console
# head -1 /usr/share/buildah/test/system/bud/volume-ownership/test-ownership
#!/usr/bin/sh
```
I've seen this before, and my recollection is that RPM packaging "helpfully" fixes shebang paths. I can't find a source reference right now, or take much more time to verify. I just want to leave this here because it will almost definitely come back to bite us some day.

**Comment by edsantiago** [comment]
@lsm5 ^^^ does that ring a bell? Do you recall seeing this with `rpmbuild`, and/or do you know if there's a way to disable it?

**Comment by carbonin** [comment]
@edsantiago things seem to be working for me in a newly deployed f31 vm.

I'm not sure how to use the buildah-test rpm, so I cloned the repo and ran the tests from there, which worked for me.

**Comment by carbonin** [comment]
@edsantiago did #2236 solve this?

**Comment by edsantiago** [comment]
Yes, thank you! Closing. (FYI for next time: I think you can add 'Fixes: #XXXX' in your PR commit message and github will auto-close on PR merge.)
