### ISSUE TITLE
buildah push should have a --sign-by

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#2269]
podman push and skopeo copy can do this.  But it would make sense that after I build a container image, that I could then push the image and sign it using buildah.

**Comment by rhatdan** [comment]
This is something customers are asking for.

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
Buildah push has --sign-by, implemented by commit https://github.com/containers/buildah/commit/a925f79cc32c28643cdde607cd38be06e5a11645
