### ISSUE TITLE
RFE: Handle Etag for caching ADD downloads

### ISSUE THREAD

**Issue by abitrolly** [containers/buildah#2276]
/kind feature

**Description**

My image includes file that is being downloaded, and the process is very unstable. The image build time is long and it just failed 4 times in a row over past two days.

`podman` doesn't cache URL resources fetched with ADD command. It would be nice of him to take note of `ETag` headers and cache them.

**Steps to reproduce the issue:**

1. `ADD https://url/file.tar.gz` from server that returns ETag headers.

2. Build and build again.

**Describe the results you received:**

File is downloaded again on a second build while ETag in server headers didn't change.

**Describe the results you expected:**

File is cached while ETag in server headers didn't change.

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Comment by giuseppe** [comment]
moved to buildah

**Comment by abitrolly** [comment]
I am running this with `podman build .`. Is that `buildah` under the hood?

**Comment by rhatdan** [comment]
Yes, Podman vendors in Buildah to do its Dockerfile/Containerfile builds.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Is this something we could handle in Containers/image?

**Comment by mtrmac** [comment]
The download from `ADD` is internal to Buildah.

(From a minimal glance, it’s unclear to me _where_ the download would be cached; it would probably require some ADD+ETag specific layer cache mechanism. I’m also not immediately 100% sure that trusting the server to provide consistent ETags does not introduce security vulnerabilities, but I’m not at all an expert in this area.)

**Comment by abitrolly** [comment]
My specific case is caching download of these two files. https://github.com/owid/owid-grapher/blob/f7ddaabec394c6a81ef9775a81007d155c1601e9/Dockerfile#L7

Without remote caching mechanism for ADD the image rebuild takes 17 minutes, and unnecessary loads the free server. I see no reason not to trust Etag. It is no different than any other server header.

**Comment by rhatdan** [comment]
I would suggest you create a PR, and then we can argue about location of the cache.  :^)
@nalind WDYT?

**Comment by abitrolly** [comment]
@rhatdan given recent events in Minsk it is hard to concentrate on anything.

**Comment by rhatdan** [comment]
@abitrolly Your comment triggered me to look at what is going on in Minsk.  Good luck and hopefully this turmoil gets settled.

**Comment by abitrolly** [comment]
@rhatdan there is no turmoil. It is just another story of power addiction, of the man who doesn't want to give up being the president 26 years in a row, and goes as far in his addiction as terrorizing citizens with force and violence. I spent a week home after elections afraid that I will be beaten by the riot police near my house, just because I was a witness of falsifications. Two of my younger friends who are talented coders are in psychiatric hospital, because they could not bear with the pressure. At least one other coding community member was detained and beaten while detained.

Two days ago a peaceful crowd of 200k+ people met to urge the old guy to leave. All, each and every alternative voting showed much less support for him, that for other candidate, who is a woman. And yesterday the guy told that he won't voluntary step down, told that we have to kill him if we want him to leave. I better stop here. Detaining candidates and offending people for the sake of "national security", urging youth to leave as soon as they can get out. It is absolutely crazy how far one person can go in playing [the king of the hill](https://en.wikipedia.org/wiki/King_of_the_Hill_(game)).

**Comment by rhatdan** [comment]
@abitrolly Were you ever able to get to look at this?

**Comment by abitrolly** [comment]
@rhatdan no, and I won't be able. (

**Comment by rhatdan** [comment]
@nalind what are you thoughts on this?

**Comment by nalind** [comment]
I'd basically echo [@mtrmac's comments](https://github.com/containers/buildah/issues/2276#issuecomment-669281443).

**Comment by rhatdan** [comment]
The maintainers have agreed that this might not be a good idea, so they are not going to be working on it.  I see this as best being scripted outside of buildah to download the files then add them locally.
If a community member wants to open a PR on this, we would look at it, but otherwise this issue is closed.
