### ISSUE TITLE
Ansible Role for Buildah

### ISSUE THREAD

**Issue by hswong3i** [containers/buildah#2294]
I am now maintenance an Ansible Role for Buildah installation (https://github.com/alvistack/ansible-role-buildah), by building the source code manually and install for following OS:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we also introduce this as an alternative installation method, e.g. under https://github.com/containers/buildah/blob/master/install.md#installation-instructions section?

**Comment by rhatdan** [comment]
If you want it there then open a PR.
