### ISSUE TITLE
Static Binary for Github Release?

### ISSUE THREAD

**Issue by hswong3i** [containers/buildah#2295]
Refer to #2294, now we could only install buildah from source build, in order to provide a synchronized user experience for installation under follow OS combination:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we reference how runc/conmon/cri-o/kubectl/kubeadm/kubelet Github release works (e.g. https://github.com/cri-o/cri-o/releases/tag/v1.17.3), therefore also provide an static binary archive for download with each release?

**Comment by rhatdan** [comment]
We are not crazy about releasing a static version of any of our tools on Linux.  But will not prevent the community from doing it. 
The problem is Ubuntu, Centos, RHEL, OpenSUSE and many other distros have packaged versions of buildah what work correctly with shared libraries and follow rules like FIPS-MODE.

**Comment by TomSweeneyRedHat** [comment]
@hswong3i If you're suggesting a "How To" document for the static version and want to add the document to our GitHub repo (or leave it elsewhere) and then add a link to the doc on our install.md file, I'd be more than willing to consider that.

**Comment by rhatdan** [comment]
I believe we now have a nix static build.

**Comment by TomSweeneyRedHat** [comment]
We do indeed have a nix static build now.

**Comment by vrothberg** [comment]
If we start distributing static binaries, please add a note similar to the one in [Podman](https://github.com/containers/podman#static-binary-builds).
