### ISSUE TITLE
RFE - provide a Dockerfile 'FROM' override option for 'bud' 

### ISSUE THREAD

**Issue by nnachefski** [containers/buildah#2301]
Hello,

When doing 'buildah bud' builds in tekton/OCP pipelines, there arises a need to be able to override the 'FROM' image in the supplied Dockerfile.  For instance, if i want to point my build at a git repo that uses 'FROM ubi8:latest' but, i would like to use a local image called 'ubi8-custom:latest'.  I still want to use the Dockerfile from the repo, but i simply want to use my own ubi8 image instead of what's given in the Dockerfile.    

This would be similar behavior to a:
`oc new-build https://github.com/foo -i ubi8-custom`

**Comment by rhatdan** [comment]
This should work now.

buildah bud --help | grep build-arg
      --build-arg argument=value      argument=value to supply to the builder

**Comment by nnachefski** [comment]
oh ok.  So 
`--build-arg FROM="ubi8-custom:latest" ` ?

**Comment by nnachefski** [comment]
closing in lieu of other issue opened
