### ISSUE TITLE
For RHEL: tests need to be updated to use FQINs

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2303]
All the buildah tests use shortnames: alpine, busybox, fedora. This is not going to work on RHEL any more. This is going to be super-tedious to fix.

**Comment by rhatdan** [comment]
Why are they not going to work.  Docker.io was added back to registries.conf.

**Comment by edsantiago** [comment]
I'm seeing gating-test failures. Perhaps the re-addition of docker.io hasn't made its way into this particular build. Will close this but keep an eye on future builds.
