### ISSUE TITLE
error: close exec fds: open /proc/self/fd: no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2315]
Error in RHEL8 gating tests. I'm guessing it's a flake but it needs resolution regardless:
```
not ok 50 bud-preserve-subvolumes
# (from function `buildah' in file ./helpers.bash, line 47,
#  in test file ./bud.bats, line 494)
#   `buildah bud --signature-policy ${TESTSDIR}/policy.json -t ${target} ${TESTSDIR}/bud/preserve-volumes' failed
# STEP 1: FROM alpine
# Getting image source signatures
# Copying blob sha256:aad63a9339440e7c3e1fff2b988991b9bfb81280042fa7f39a5e327023056819
# Copying config sha256:a187dde48cd289ac374ad8539930628314bc581a481cdb41409c9289419ddb72
# Writing manifest to image destination
# Storing signatures
# STEP 2: RUN mkdir -p /vol/subvol/subsubvol
# error running container: error creating container for [/bin/sh -c mkdir -p /vol/subvol/subsubvol]: time="2020-04-20T18:46:01Z" level=error msg="container_linux.go:349: starting container process caused \"close exec fds: open /proc/self/fd: no such file or directory\""
# container_linux.go:349: starting container process caused "close exec fds: open /proc/self/fd: no such file or directory"
# : exit status 1
# error building at STEP "RUN mkdir -p /vol/subvol/subsubvol": error while running runtime: exit status 1
```
I was not able to reproduce on a test VM.

buildah-1.11.6-7, runc-1.0.0-64.rc10. (MB 6373).

**Comment by edsantiago** [comment]
Ping, this is still happening

**Comment by rhatdan** [comment]
@edsantiago still happening?

**Comment by edsantiago** [comment]
I don't know. I no longer monitor RHEL gating test failures except on special request. There are dozens of gating-test failures since my May 14 comment, but there's no way (that I know of) to search or grep all those logs.

I'm not really fond of closing issues just because "we haven't seen it in a while" but without an actual understanding of the problem, so I'll leave this open but will understand if someone else wishes to close.

**Comment by edsantiago** [comment]
Yes, it's still happening. Log is internal though.

**Comment by rhatdan** [comment]
@jnovy @edsantiago Is this still an issue?

**Comment by edsantiago** [comment]
Again, I don't know, since I can no longer look at RHEL gating tests (it would be a full-time job). I didn't see this failure while reading test logs for [bz1914884](https://bugzilla.redhat.com/show_bug.cgi?id=1914884), so I'll assume it's gone. At least for that particular RHEL and stream.
