### ISSUE TITLE
buildah .dockerignore bang

### ISSUE THREAD

**Issue by pnnlrck8sstatus** [containers/buildah#2318]
I was trying to build mlflow with buildah bud but its .dockerignore file uses don't ignore option like this:
```
travis
# required for Docker build
!travis/small-requirements.txt
!travis/large-requirements.txt
!travis/lint-requirements.txt
```
buildah should add support for ! for including files that were ignored with previous options

**Comment by rhatdan** [comment]
What version did you test this against?  I thought we had support for this?

**Comment by pnnlrck8sstatus** [comment]
buildah --version
buildah version 1.11.6 (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)

Newest when I did a yum upgrade.

Maybe there is a newer version?

**Comment by QiWang19** [comment]
@pnnlrck8sstatus  #2238 has fixed this issue. Buildah v1.14.4 should work.
