### ISSUE TITLE
Two issues with .dockerignore handling (PR opened in containers/storage)

### ISSUE THREAD

**Issue by yann-soubeyrand** [containers/buildah#2347]
Some .dockerignore patterns are not handled correctly:

- `dir\` incorrectly matches `dir$`
- `**/dir` doesn't match `dir/file`

I've opened a PR in containers/storage to fix it: https://github.com/containers/storage/pull/618.

**Comment by rhatdan** [comment]
Awesome thanks.

**Comment by yann-soubeyrand** [comment]
I believe this issue has been fixed in https://github.com/containers/buildah/commit/cc4586890f33bcb1a1f2ce4c6c281c6119cdbf5f which upgrades github.com/containers/storage from v1.19.2 to v1.20.1 (which includes the fix https://github.com/containers/storage/commit/20dbd4e2eb5ec14200e2ebff0c46fa66f477073c).
