### ISSUE TITLE
Builds don't fail when ARG is not provided

### ISSUE THREAD

**Issue by redbaron** [containers/buildah#2349]
**Description**

If Dockerfile has ARG with no default, then build should fail if it wasn't provided on a command line.

**Steps to reproduce the issue:**
1. ```
   FROM busybox
   
   ARG MYARG

   ENTRYPOINT [${MYARG}]
    ```
2. podman build 

**Describe the results you received:**

Image builds with empty arg value.

**Describe the results you expected:**

If `ARG` has no default value in dockerfile, `podman build` should fail, instead of implicitly defaulting to empty value.

**Output of `rpm -q buildah` or `apt list buildah`:**
```
buildah-1.14.8-1.fc31.x86_64
```


**Output of `buildah version`:**

```
buildah version 1.14.8 (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 1.9.0
```
**Output of `cat /etc/*release`:**

```
 cat /etc/*release
Fedora release 31 (Thirty One)
NAME=Fedora
VERSION="31.20200509.0 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31.20200509.0 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
OSTREE_VERSION='31.20200509.0'
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux Lenovo.lan 5.6.8-200.fc31.x86_64 #1 SMP Wed Apr 29 19:10:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "vfs"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
[storage.options.thinpool]
ostree_repo = ""
skip_mount_home = "false"
```

**Comment by TomSweeneyRedHat** [comment]
@redbaron thanks for the issue, we'll take a look.

**Comment by QiWang19** [comment]
I have checked with docker, it doesn't return an error either. Podman and Buildah are compatible with docker now. Should just leave it as is?

**Comment by rhatdan** [comment]
@redbaron Are you testing with Master?  @QiWang19 ^^ reports that it works correctly in the latest version?

**Comment by QiWang19** [comment]
>  @QiWang19 ^^ reports that it works correctly in the latest version?

@rhatdan  I confirmed we are compatible with docker,  so it's not an error if `bud` doesn’t provide value to expected `ARG` variables. But if want to satisfy the requirement in this issue, Buildah should return an error like `ARG value hasn't been specified`. Does Buildah need this change?

**Comment by boaz0** [comment]
Sorry I didn't see this issue had some discussion until now.
Another option could be adding a flag to fail if not all build arguments are set.

**Comment by redbaron** [comment]
Yeah, my memory didn't serve me well, it seems that docker was never failing builds on missing args :(
