### ISSUE TITLE
Multi-stage build: shell script

### ISSUE THREAD

**Issue by sycured** [containers/buildah#2351]
Hi,
I'm looking to create a multi-stage build script (shell) using buildah but I would like to know if you've an example or best practices.
Using Dockerfile, it's not a solution.
Regards

**Comment by TomSweeneyRedHat** [comment]
I think the closest example we have is in this article, I don't think it's handling multistage builds like you're looking for, but you might be able to extrapolate from it.  If you've particular questions along the way, feel free to reply here and we'll see what we can figure out.

**Comment by TomSweeneyRedHat** [comment]
well that link to the article didn't work out so well, we'll try again with [this](https://www.redhat.com/sysadmin/building-buildah).

**Comment by sycured** [comment]
Hi @TomSweeneyRedHat thanks but it's not related to multi-stage build…

My question is more about how can I migrate a Dockerfile with multi-stage to buildah shell script.

Example:
```
FROM golang:1.7.3 AS builder
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html  
COPY app.go    .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]  
```

It's about efficiency and optimization… I optimize my containers but I need to do this multi-stage.

Do you have a recommended workflow for complex build like with 3-4 intermediate stages before the ready to push for prod?

Regards

**Comment by rhatdan** [comment]
You want this rewritten using a bash mechanism rather then using Dockerfile?

**Comment by sycured** [comment]
I remove Dockerfile to back to Shell Script or Python script…
In this case, my problem is about `COPY --from=builder /go/src/github.com/alexellis/href-counter/app .`

Do I need to start and mount the container builder to copy out the file or not?

It's the missing step in the doc to have a multi-stage build with buildah

**Comment by rhatdan** [comment]
Totally untested, but something like this should work.

```
ctr=$(buildah from golang:1.7.3)
buildah config --workdir=/go/src/github.com/alexellis/href-counter/ ${ctr}
buildah run ${ctr} go get -d -v golang.org/x/net/html  
buildah copy ${ctr} app.go .
buildah run ${ctr} CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
mnt=$(buildah mount ${ctr})

ctr1=$(FROM alpine:latest)
buildah run ${ctr1} apk --no-cache add ca-certificates
buildah config --workdir=/root/ ${ctr1}
mnt1=$(buildah mount {ctr1})
cp ${mnt}/go/src/github.com/alexellis/href-counter/app ${mnt1}
buildah config --cmd='["./app"]' ${ctr1}
buildah umount ${ctr}
buildah rm -f ${ctr}
buildah commit ${ctr1} MYIMAGENAME
buildah umount ${ctr1}
buildah rm -f ${ctr1}
```

**Comment by sycured** [comment]
Thank you and you answered my question about mounting container and copy file to the new in creation.
Thanks
