### ISSUE TITLE
storage-driver btrfs not supported in Ubuntu packages from OSBS

### ISSUE THREAD

**Issue by ioanrogers** [containers/buildah#2358]
This is basically containers/libpod#5043, but for buildah. I'm using the Ubuntu Focal packages from OSBS.  The latest podman package from OSBS works with btrfs, including `podman build`. `buildah` used to work with the old PPA packages.

**Steps to reproduce the issue:**
1. Set `driver = "btrfs"` in ~/.config/containers/storage.conf
2. Run `buildah info`

```
$ buildah info
ERRO Failed to GetDriver graph btrfs /home/ioan/.local/share/containers/storage 
failed to GetDriver graph btrfs /home/ioan/.local/share/containers/storage: driver not supported
ERRO exit status 1 
```
Expected to see same output as podman:
```
$ podman info --format=json | jq .store      
{
  "configFile": "/home/ioan/.config/containers/storage.conf",
  "containerStore": {
    "number": 0,
    "paused": 0,
    "running": 0,
    "stopped": 0
  },
  "graphDriverName": "btrfs",
  "graphOptions": {},
  "graphRoot": "/home/ioan/.local/share/containers/storage",
  "graphStatus": {
    "Build Version": "Btrfs v5.4.1 ",
    "Library Version": "102"
  },
  "imageStore": {
    "number": 2
  },
  "runRoot": "/run/user/1001/containers",
  "volumePath": "/home/ioan/.local/share/containers/storage/volumes"
}

```
**Output of `rpm -q buildah` or `apt list buildah`:**
`buildah/unknown,now 1.14.8~1 amd64 [installed]`
`podman/unknown,now 1.9.1~1 amd64 [installed]`

**Output of `buildah version`:**

```
buildah version 1.14.8 (image-spec 1.0.1-dev, runtime-spec 1.0.1-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.13.8
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@nalind @TomSweeneyRedHat any idea what's missing here?

**Comment by nalind** [comment]
Is this the package from the repository at https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_20.04/?  When I run `buildah --storage-driver btrfs info` with that version, and a btrfs filesystem mounted on `/var/lib/containers/storage`, it succeeds.

**Comment by lsm5** [comment]
> Is this the package from the repository at https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_20.04/? When I run `buildah --storage-driver btrfs info` with that version, and a btrfs filesystem mounted on `/var/lib/containers/storage`, it succeeds.

@ioanrogers could you confirm? ^

**Comment by ioanrogers** [comment]
Oh, weird.  That package is has the same version but is not the same. It has different build time. I wonder if apt just didn't upgrade it when I updated to focal because the version was the same?

Previous package:
```
$ buildah version
Version:         1.14.8
Go Version:      go1.13.8
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Mon Apr 27 07:31:23 2020
OS/Arch:         linux/amd64

$ buildah --storage-driver btrfs info
ERRO Failed to GetDriver graph btrfs /home/ioan/.local/share/containers/storage 
failed to GetDriver graph btrfs /home/ioan/.local/share/containers/storage: driver not supported
ERRO exit status 1      
```
Download https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_20.04/amd64/buildah_1.14.8~1_amd64.deb

```
$ sudo dpkg -i ~/Downloads/buildah_1.14.8_1_amd64.deb 
(Reading database ... 185361 files and directories currently installed.)
Preparing to unpack .../buildah_1.14.8_1_amd64.deb ...
Unpacking buildah (1.14.8~1) over (1.14.8~1) ...
Setting up buildah (1.14.8~1) ...
Processing triggers for man-db (2.9.1-1) ...
```

New version:
```
$ buildah version                                    
Version:         1.14.8
Go Version:      go1.13.8
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Mon Apr 27 07:30:37 2020
OS/Arch:         linux/amd64

$ buildah --storage-driver btrfs info
[...works...]
```

**Comment by ioanrogers** [comment]
Oh, my apt source has this: `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/` - `stable` not `testing`

**Comment by lsm5** [comment]
> Oh, my apt source has this: `http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/` - `stable` not `testing`

that shouldn't make a difference, it was built from the same source.

**Comment by lsm5** [comment]
I'll build 1.14.9 now for both testing and stable. Let's verify it works well with the new build.

**Comment by ioanrogers** [comment]
I let apt "upgrade" back to the one from `stable` and it's back to failing.

**Comment by lsm5** [comment]
> I let apt "upgrade" back to the one from `stable` and it's back to failing.

ack, might've been a mess-up on my part. Sorry about that, let's check after 1.14.9 is available on OBS. I'll update this issue once it's ready.

**Comment by ioanrogers** [comment]
No worries. And thanks for your work on the packaging!

**Comment by lsm5** [comment]
@ioanrogers 1.14.9 has been published for testing, and should be published in less than an hour for stable. This time I can be certain it's the same build as I built them using the same debian branch. Let me know how that goes...

**Comment by ioanrogers** [comment]
Updated and working, thanks!

```
$ buildah version                    
Version:         1.14.9
Go Version:      go1.13.8
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Wed May 13 11:53:48 2020
OS/Arch:         linux/amd64
```

```
$ buildah info --format={{".store"}}
map[ContainerStore:map[number:14] GraphDriverName:btrfs GraphOptions:[] GraphRoot:/home/ioan/.local/share/containers/storage GraphStatus:map[Build Version:Btrfs v5.4.1  Library Version:102] ImageStore:map[number:14] RunRoot:/run/user/1001/containers]
```

**Comment by lsm5** [comment]
@ioanrogers thanks a lot!
