### ISSUE TITLE
ARG and ENV variables in Containerfile with the same name fail

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#2372]
This issue was first discussed in this imagebuilder PR: https://github.com/openshift/imagebuilder/pull/159.  Capturing it here so we can track down the problem, I believe it's really an imagebuilder issue.

Using this Dockerfile:

```
FROM ubuntu:18.04
ARG TOM=Problem_child
ARG USER_NAME=my_user_arg
ENV USER_NAME=my_user_env
RUN useradd -r -s /bin/false -m -d /home/${USER_NAME} ${USER_NAME}
USER ${USER_NAME}
COPY --chown=${USER_NAME} ./prdel/some_file /home/${USER_NAME} 
WORKDIR /home/${USER_NAME}
```
The RUN creates both `/home/my_user_arg` and `/home/my_user_env`.  Then USER gets set to `my_user_arg` and the only user that gets into `/etc/passwd` via `useradd` is of course `my_user_arg`.  Due to that the build breaks on the `--chown` as `my_user_env` doesn't exsist.

Sample Run: 

```
# buildah bud -f ~/Dockerfile.copychown3 -t tom .
STEP 1: FROM ubuntu:18.04
Getting image source signatures
Copying blob 2910811b6c42 done  
Copying blob 23884877105a [======================================] 25.5MiB / 25.5MiB
Copying blob 36505266dcc6 done  
Copying blob bc38caa0f5b9 done  
Copying config c3c304cb4f done  
Writing manifest to image destination
Storing signatures
STEP 2: ARG TOM=Problem_child
STEP 3: ARG USER_NAME=my_user_arg
STEP 4: ENV USER_NAME=my_user_env
STEP 5: RUN useradd -r -s /bin/false -m -d /home/${USER_NAME} ${USER_NAME}
STEP 6: USER ${USER_NAME}
STEP 7: COPY --chown=${USER_NAME} ./prdel/some_file /home/${USER_NAME} 
Builder [&{{  my_user_env 0 0 0 0 0  [] map[]   0 [USER_NAME=my_user_env] [/bin/bash] [] <nil> [] ubuntu:18.04 map[]    [] [] [] [] map[] false false false false false false false false } [USER_NAME=my_user_env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] map[TOM:Problem_child USER_NAME:my_user_arg] map[] map[] false  map[FTP_PROXY:true HTTPS_PROXY:true HTTP_PROXY:true NO_PROXY:true TOM:true USER_NAME:true ftp_proxy:true http_proxy:true https_proxy:true no_proxy:true] [] [] [] [] [] []}]
 args [[./prdel/some_file /home/my_user_env]]
 attributes [map[]]
 flagArgs [[--chown=${USER_NAME}]]
 original [COPY --chown=${USER_NAME} ./prdel/some_file /home/${USER_NAME} ]
TOM: duplicate key [USER_NAME]
error building at STEP "COPY --chown=${USER_NAME} ./prdel/some_file /home/${USER_NAME}": error determining run uid: user: unknown user error looking up user "my_user_env"
```

**Comment by carbonin** [comment]
@TomSweeneyRedHat I was actually looking into this a bit a while back after noticing [this issue](https://github.com/containers/buildah/issues/1936#issuecomment-605285921) related to ARG/ENV handling.

I noticed that all the existing ENVs and ARGs are getting thrown into the step env here https://github.com/openshift/imagebuilder/blob/e307568568533c4afccdf7b56df7b4493e4e9a7b/builder.go#L336-L338. My thought was to add deduplication and priority there, but I never got the chance to implement it.

Hope this helps!

**Comment by TomSweeneyRedHat** [comment]
Thanks @carbonin !  From a very quick glance, it looks good, I'll need some time to play and digest.

**Comment by TomSweeneyRedHat** [comment]
Going to reopen this, I made another change to this neck of the code in imagebuilder yesterday and I want to get some new tests added to Buildah.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat What is the latest on this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, I've added the tests and neglected to close this.  Going to get one in my tally sheet today!
