### ISSUE TITLE
buildah bud pushing wrong mediaType for compressed layers 

### ISSUE THREAD

**Issue by pablofsf** [containers/buildah#2374]
I have setup a local docker registry to distribute some personal images. Executing buildah bud and buildah push runs fine. However, when downloading the image with skopeo copy and extracting it with umoci unpack (these two steps are necessary for me, as I am using lxc for containerization), umoci reports: invalid tar header. 

I investigated further into the issue, and came to the conclusion that buildah is writing the manifest wrongly while pushing. Because:

 * After running skopeo copy docker://sr oci:tmp:latest, manual inspection of the digest inside tmp directory reported:
  * {"schemaVersion":2,"config":{"mediaType":"application/vnd.oci.image.config.v1+json","digest":"sha256:4c7391d2a055f493256426ac190711d9652beadd3394e0bb9949896f6f011334","size":11018},"layers":[{"mediaType":"application/vnd.oci.image.layer.v1.tar","digest":"sha256:d1a81ca518e2c8d1be74782160c39917dc5434136380e2caa7a2a02f568c69bd","size":28376575},....

  * What catched my attention was that "mediaType":"application/vnd.oci.image.layer.v1.tar" is missing the +gzip. However, file detects the files as "gzip compressed data" and skopeo copy with --debug detects the blobs as compressed.

In addition, podman build does not have this issue.

Strangely enough, if a RUN statement is not present in the Containerfile (which has a FROM, RUN and a couple of ENV instructions), then buildah pushes the right mediaType for the layer

**Steps to reproduce the issue:**
1. buildah bud (for a Containerfile with at least a RUN instruction)
2. buildah push docker://host/container
3. skopeo copy docker://host/container oci:tmp:latest
4. umoci unpack --image tmp:latest root

umoci: create runtime bundle: unpack rootfs: unpack layer: read next entry: archive/tar: invalid tar header

The reason is most likely that the digest is describing the media type of the layers as "application/vnd.oci.image.layer.vi.tar", when the images are actually compressed and readable by tar.

The layers downloaded and passed to umoci should be of mediaType "application/vnd.oci.image.layer.vi.tar+gzip". This is the behavior when doing podman build && podman push

**Output of `rpm -q buildah` or `apt list buildah`:**

buildah/unknown,now 1.14.9~1 amd64 [installed]

**Output of `buildah version`:**

Version:         1.14.9
Go Version:      go1.11.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Sun May 17 18:14:52 2020
OS/Arch:         linux/amd64

**Output of `podman version` if reporting a `podman build` issue:**

Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/amd64

**Output of `cat /etc/*release`:**

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Output of `uname -a`:**

Linux kgpe-d16 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

**Output of `cat /etc/containers/storage.conf`:**

\# This file is is the configuration file for all tools
\# that use the containers/storage library.
\# See man 5 containers-storage.conf for more information
\# The "container storage" table contains all of the server options.
[storage]

\# Default Storage Driver
driver = ""

\# Temporary storage location
runroot = "/var/run/containers/storage"
 
\# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"
 
\# Storage path for rootless users
\#
\# rootless_storage_path = "$HOME/.local/share/containers/storage"
 
[storage.options]
\# Storage options to be passed to underlying storage drivers
 
\# AdditionalImageStores is used to pass paths to additional Read/Only image stores
\# Must be comma separated list.
additionalimagestores = [
]
 
\# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
\# a container, to the UIDs/GIDs as they should appear outside of the container,
\# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
\# listed and will be heeded by libraries, but there are limits to the number of
\# mappings which the kernel will allow when you later attempt to run a
\# container.
\#
\# remap-uids = 0:1668442479:65536
\# remap-gids = 0:1668442479:65536
 
\# Remap-User/Group is a user name which can be used to look up one or more UID/GID
\# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
\# with an in-container ID of 0 and then a host-level ID taken from the lowest
\# range that matches the specified name, and using the length of that range.
\# Additional ranges are then assigned, using the ranges which specify the
\# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
\# until all of the entries have been used for maps.
\#
\# remap-user = "containers"
\# remap-group = "containers"

\# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
\# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partioned
\# to containers configured to create automatically a user namespace.  Containers
\# configured to automatically create a user namespace can still overlap with containers
\# having an explicit mapping set.
\# This setting is ignored when running as rootless.
\# root-auto-userns-user = "storage"
\#
\# Auto-userns-min-size is the minimum size for a user namespace created automatically.
\# auto-userns-min-size=1024
\#
\# Auto-userns-max-size is the minimum size for a user namespace created automatically.
\# auto-userns-max-size=65536

[storage.options.overlay]
\# ignore_chown_errors can be set to allow a non privileged user running with
\# a single UID within a user namespace to run containers. The user can pull
\# and use any image even those with multiple uids.  Note multiple UIDs will be
\# squashed down to the default uid in the container.  These images will have no
\# separation between the users in the container. Only supported for the overlay
\# and vfs drivers.
\#ignore_chown_errors = false

\# Path to an helper program to use for mounting the file system instead of mounting it
\# directly.
\#mount_program = "/usr/bin/fuse-overlayfs"

\# mountopt specifies comma separated list of extra mount options
mountopt = "nodev"

\# Size is used to set a maximum size of the container image.
\# size = ""

[storage.options.thinpool]
\# Storage Options for thinpool

\# autoextend_percent determines the amount by which pool needs to be
\# grown. This is specified in terms of % of pool size. So a value of 20 means
\# that when threshold is hit, pool will be grown by 20% of existing
\# pool size.
\# autoextend_percent = "20"

\# autoextend_threshold determines the pool extension threshold in terms
\# of percentage of pool size. For example, if threshold is 60, that means when
\# pool is 60% full, threshold has been hit.
\# autoextend_threshold = "80"

\# basesize specifies the size to use when creating the base device, which
\# limits the size of images and containers.
\# basesize = "10G"

\# blocksize specifies a custom blocksize to use for the thin pool.
\# blocksize="64k"

\# directlvm_device specifies a custom block storage device to use for the
\# thin pool. Required if you setup devicemapper.
\# directlvm_device = ""

\# directlvm_device_force wipes device even if device already has a filesystem.
\# directlvm_device_force = "True"

\# fs specifies the filesystem type to use for the base device.
\# fs="xfs"

\# log_level sets the log level of devicemapper.
\# 0: LogLevelSuppress 0 (Default)
\# 2: LogLevelFatal
\# 3: LogLevelErr
\# 4: LogLevelWarn
\# 5: LogLevelNotice
\# 6: LogLevelInfo
\# 7: LogLevelDebug
\# log_level = "7"

\# min_free_space specifies the min free space percent in a thin pool require for
\# new device creation to succeed. Valid values are from 0% - 99%.
\# Value 0% disables
\# min_free_space = "10%"

\# mkfsarg specifies extra mkfs arguments to be used when creating the base
\# device.
\# mkfsarg = ""

\# Size is used to set a maximum size of the container image.
\# size = ""

\# use_deferred_removal marks devicemapper block device for deferred removal.
\# If the thinpool is in use when the driver attempts to remove it, the driver
\# tells the kernel to remove it as soon as possible. Note this does not free
\# up the disk space, use deferred deletion to fully remove the thinpool.
\# use_deferred_removal = "True"

\# use_deferred_deletion marks thinpool device for deferred deletion.
\# If the device is busy when the driver attempts to delete it, the driver
\# will attempt to delete device every 30 seconds until successful.
\# If the program using the driver exits, the driver will continue attempting
\# to cleanup the next time the driver is used. Deferred deletion permanently
\# deletes the device and all data stored in device will be lost.
\# use_deferred_deletion = "True"

\# xfs_nospace_max_retries specifies the maximum number of retries XFS should
\# attempt to complete IO when ENOSPC (no space) error is returned by
\# underlying storage device.
\# xfs_nospace_max_retries = "0"

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
This is very likely https://github.com/containers/image/issues/733 ; I’d be surprised if the RUN made a difference, it’s more of a matter of “has the layer ever been pulled or pushed to that location on this computer?”.

**Comment by pablofsf** [comment]
Yes, it looks exactly like that problem. In addition, I had been doing repeated tests with the registry to which I was pushing, so it fits perfectly. I am sorry I hadn't seen the other bug before. Should this one be closed or be kept as reference?

**Comment by mtrmac** [comment]
Keeping this open is useful for tracking when the fix lands in Buildah, and for allowing other users that encounter this to see how it manifests.

**Comment by rhatdan** [comment]
@mtrmac no updates in a while on this one.

**Comment by rhatdan** [comment]
This is fixed in main branch and the current release.
