### ISSUE TITLE
Request: Override location for policy.json

### ISSUE THREAD

**Issue by christophermaier** [containers/buildah#2379]
**Description**

I would like to be able to override the location of the `policy.json` file that Buildah consults in order to use something other than `/etc/containers/policy.json`.

**Steps to reproduce the issue:**
1. Run a (e.g.) `buildah bud` command on a system without `/etc/containers/policy.json` file.

**Describe the results you received:**
```
error committing container for step {Env:[ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:env Args:[PATH /bin] Flags:[] Attrs:map[] Message:ENV PATH /bin Original:ENV PATH /bin}: error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory
```
**Describe the results you expected:**
Given the current behavior, this _is_ the behavior I would expect. However, it would be nice to have an option similar to `--registries-conf` and `--registries-conf-dir` to point to another path. (An environment variable for this would also work just fine.)

**Comment by boaz0** [comment]
Did you try `--signature-policy`?

**Comment by rhatdan** [comment]
I believe buildah will also look in $HOME/.config/containers/policy.json

**Comment by christophermaier** [comment]
@boaz0 That does appear to work... not sure how I missed that :man_facepalming: 

Thank you for the pointer!
