### ISSUE TITLE
buildah copy should suport filepermission as an argument .

### ISSUE THREAD

**Issue by kushalagrawal** [containers/buildah#2384]
When I am copy few executable scripts in the container image, I have to execute two buildah command,
1. buildah copy
2. change file permissions using builah run.

IMO, It can be done in a single command with buildah copy --chown <user> **--chnod <file_permission>** <containerID> files location

It would be nice if such option can be implemented.

**Comment by TomSweeneyRedHat** [comment]
@kushalagrawal thanks for the request/issue.  Sounds like a good one to me, just to triple check I think you meant `--chmod` above and not `--chnod`.

**Comment by kushalagrawal** [comment]
Hi @TomSweeneyRedHat , Sorry my bad. Yes it is `--chmod`.

**Comment by rhatdan** [comment]
My only concern would be that this is a breaking change on Dockerfile, which would make the Dockerfile not work with other implementations.

**Comment by kushalagrawal** [comment]
Yes, that would be a complexity. Should we raise an issue with docker as well...

**Comment by rhatdan** [comment]
Yes, although I believe this has in the past, and been ignored or never done.  I would just google around for it.

**Comment by rhatdan** [comment]
Can not change this until Dockerfile upstream supports it.
