### ISSUE TITLE
Buildah silently fails to include non-OCI directives

### ISSUE THREAD

**Issue by penn5** [containers/buildah#2388]
**Description**

When running `podman build .` or `buildah bud` on a Dockerfile containing a HEALTHCHECK instruction, the healthcheck is silently ignored because it is not OCI-supported. It took me 4 hours to work out that I had to specify --format=docker, so am proposing that a warning is issued in this case

**Steps to reproduce the issue:**
1. Create a Dockerfile containing a HEALTHCHECK
2. Build it with `buildah bud`
3. Observe that the Healthcheck is not included in the output of `podman image inspect <image>`

**Describe the results you received:**
Healthcheck is not included in the results

**Describe the results you expected:**
A warning is issued explaining why healthcheck is not included in the results and how to fix it (--format=docker)

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah.x86_64            1.14.8-1.fc31                    updates
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.14.8
Go Version:      go1.13.9
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
NAME=Fedora
VERSION="31 (KDE Plasma)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux toto 5.6.13-200.fc31.x86_64 #1 SMP Thu May 14 23:26:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

https://del.dog/amirirfude

**Comment by TomSweeneyRedHat** [comment]
@penn5 Thanks for the issue.  That's a good thought.
