### ISSUE TITLE
Build caching between --format changes is broken

### ISSUE THREAD

**Issue by penn5** [containers/buildah#2389]
**Description**

When building an image where a cache is available but the --format=... parameter does not match the cache, the cache is used anyway, resulting in an invalid cache. 

**Steps to reproduce the issue:**
1. Clean all cached images
2. Create a dockerfile with an OCI-unsupported directive
3. Build the dockerfile with `buildah bud --images=true`
4. Build the same dockerfile with `buildah bud --images=true --format=docker`

**Describe the results you received:**
The OCI-unsupported directive is ignored and the cache is used in step 4

**Describe the results you expected:**
Caches are invalidated due to changed format (or at least caches for the commands that have different meaning)

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah.x86_64            1.14.8-1.fc31                    updates
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.14.8
Go Version:      go1.13.9
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.4.3
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
NAME=Fedora
VERSION="31 (KDE Plasma)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux toto 5.6.13-200.fc31.x86_64 #1 SMP Thu May 14 23:26:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

https://del.dog/amirirfude

**Comment by TomSweeneyRedHat** [comment]
@penn5 Thanks for the issue report.  We'll take a look.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat DId you ever take a look?

**Comment by TomSweeneyRedHat** [comment]
Not yet, how bout we spin this one to @ashley-cui ?

**Comment by 3sky** [comment]
Hi, @TomSweeneyRedHat can I take it? I need to learn more about OCP related ecosystem :)

**Comment by ashley-cui** [comment]
@3sky Feel free to take it :)

**Comment by 3sky** [comment]
@ashley-cui I need some help, If I want to reproduce an error it's correct way? 

1. make dockerfile with non-oci instruction
```bash
; Dockerfile.nonoci
ROM alpine
HEALTHCHECK CMD curl --fail http://localhost:7070 || exit 1  
COPY ./main.go /
```
2. run `buildah`
```bash
buildah bud --layers=true -f Dockerfile.nonoci --format oci -t oci-app . 
# and 
buildah bud --layers=true -f Dockerfile.nonoci --format docker -t docker-app .
```
3. The expected output is to get two different caching layers sets for both cases? Now we get something like this: 
```console
$ buildah bud --layers=true -f Dockerfile.nonoci --format oci -t oci-app .    
STEP 1: FROM alpine
STEP 2: HEALTHCHECK CMD curl --fail http://localhost:7070 || exit 1  
--> Using cache ba5abbefc258a3713363999cbc283c033c6002926ae1da56f485692180fcd21f
STEP 3: COPY ./main.go /
--> Using cache f88994b81e22f1c58545e37978a455d7837eddb104207869716c8509c728a03f
STEP 4: COMMIT oci-app
--> f88994b81e2
f88994b81e22f1c58545e37978a455d7837eddb104207869716c8509c728a03f

$ buildah bud --layers=true -f Dockerfile.nonoci --format docker -t docker-app . 
STEP 1: FROM alpine
STEP 2: HEALTHCHECK CMD curl --fail http://localhost:7070 || exit 1  
--> Using cache ba5abbefc258a3713363999cbc283c033c6002926ae1da56f485692180fcd21f
STEP 3: COPY ./main.go /
--> Using cache f88994b81e22f1c58545e37978a455d7837eddb104207869716c8509c728a03f
STEP 4: COMMIT docker-app
--> f88994b81e2
f88994b81e22f1c58545e37978a455d7837eddb104207869716c8509c728a03
```

**Comment by ashley-cui** [comment]
Hmm, I'm not too familiar but what I think needs to happen is that we shouldn't be using the cache for STEP 2 healthcheck because its unsupported in --format oci.
