### ISSUE TITLE
Include the FROM directive in Docker history

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#2391]
Pulling this from https://bugzilla.redhat.com/show_bug.cgi?id=1649044 and @control-d

```
In the customer's own words:

---
"Please include the FROM directive in docker image information.  Nice to know what base image was used.  Docker history often lists <missing> on base image layers when pushed/pulled from a repository."
---



Just based on this I think what they would like to see, at a minimum, is:


# cat Dockerfile 
FROM fedora:latest
MAINTAINER http://fedoraproject.org/wiki/Cloud

RUN dnf -y update && dnf clean all
RUN dnf -y install nginx && dnf clean all
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html


# podman build -t test:bz1649044 .
STEP 1: FROM fedora:latest
Getting image source signatures
Skipping blob 01eb078129a0 (already present): 85.81 MiB / 85.81 MiB [=======] 0s
Copying config d09302f77cfc: 1.97 KiB / 1.97 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: MAINTAINER http://fedoraproject.org/wiki/Cloud
--> ff18bdd9b520b02fb3fc2ad26eb6ddc8e802b8496421902ea629801041aa8cb4
STEP 3: FROM ff18bdd9b520b02fb3fc2ad26eb6ddc8e802b8496421902ea629801041aa8cb4
STEP 4: RUN dnf -y update && dnf clean all
Fedora Modular 29 - x86_64                      388 kB/s | 1.5 MB     00:03    
{...]
--> e9fd39dc40f530626de0139e941faa5a7169f1722ac51dd135f5d6d6dcd50fe9
STEP 5: FROM e9fd39dc40f530626de0139e941faa5a7169f1722ac51dd135f5d6d6dcd50fe9
STEP 6: RUN dnf -y install nginx && dnf clean all
Fedora Modular 29 - x86_64                      2.4 MB/s | 1.5 MB     00:00    
[...]
--> b58279a3e1239bdfc870cf75cd3c4346346e40f84a999c7093b2fe948e2fdcd9
STEP 7: FROM b58279a3e1239bdfc870cf75cd3c4346346e40f84a999c7093b2fe948e2fdcd9
STEP 8: RUN echo "daemon off;" >> /etc/nginx/nginx.conf
--> 6823c19ecc131820aa2e6cbd43025b2038ac1c8f0fdef158481f3138e8816456
STEP 9: FROM 6823c19ecc131820aa2e6cbd43025b2038ac1c8f0fdef158481f3138e8816456
STEP 10: RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html
--> a75cd222709a12ba0e42d56f37988a3663c65c612a0d04e9f6ea8afdbd7f0327
STEP 11: COMMIT test:bz1649044


<start of hypothetical output>

# podman history test:bz1649044
ID             CREATED         CREATED BY                                      SIZE      COMMENT
a75cd222709a   3 minutes ago   /bin/sh -c echo "nginx on Fedora" > /usr/s...   252B      
6823c19ecc13   3 minutes ago   /bin/sh -c echo "daemon off;" >> /etc/ngin...   5.12kB    
b58279a3e123   3 minutes ago   /bin/sh -c dnf -y install nginx && dnf cle...   19.91MB   
e9fd39dc40f5   4 minutes ago   /bin/sh -c dnf -y update && dnf clean all       117MB     
ff18bdd9b520   8 minutes ago   /bin/sh -c #(nop) FROM fedora:latest            1.024kB   
d09302f77cfc   2 months ago    /bin/sh -c #(nop) CMD ["/bin/bash"]             1.024kB   
<missing>      2 months ago    /bin/sh -c #(nop) ADD file:508fcc9342ae817...   283MB     
<missing>      2 months ago    /bin/sh -c #(nop) ENV DISTTAG=fcontainer F...   283MB     
<missing>      4 months ago    /bin/sh -c #(nop) LABEL maintainer=Clement...   283MB     


OR

# podman history test:bz1649044
ID             CREATED          CREATED BY                                      SIZE      COMMENT
a75cd222709a   4 minutes ago    /bin/sh -c echo "nginx on Fedora" > /usr/s...   252B      
6823c19ecc13   4 minutes ago    /bin/sh -c echo "daemon off;" >> /etc/ngin...   5.12kB    
b58279a3e123   4 minutes ago    /bin/sh -c dnf -y install nginx && dnf cle...   19.91MB   
e9fd39dc40f5   6 minutes ago    /bin/sh -c dnf -y update && dnf clean all       117MB     
ff18bdd9b520   10 minutes ago   /bin/sh -c #(nop) MAINTAINER http://fedora...   1.024kB   FROM fedora:latest
d09302f77cfc   2 months ago     /bin/sh -c #(nop) CMD ["/bin/bash"]             1.024kB   
<missing>      2 months ago     /bin/sh -c #(nop) ADD file:508fcc9342ae817...   283MB     
<missing>      2 months ago     /bin/sh -c #(nop) ENV DISTTAG=fcontainer F...   283MB     
<missing>      4 months ago     /bin/sh -c #(nop) LABEL maintainer=Clement...   283MB     


It might even be better to record:

  FROM docker.io/library/fedora@sha256:787bce7f4d2dafd8c4923dd5c43fb2e4b8473b57ea52f6d12be9bb27bc8f1a85


As is, I don't think this fulfills the customer's request.  I apologize if the initial request was not clear enough.
```

**Comment by ironknight78** [comment]
Hi @TomSweeneyRedHat ! I'm new to OSS community and I'd like to help #investigate this! Can you point me in the right direction?

**Comment by TomSweeneyRedHat** [comment]
Hola @ironknight78 y bienvenido!  The first thing you'll need to do is setup your development environment.  I'm not sure if you've done that or not for other GitHub projects, so I'll point you at the [Building from scratch](https://github.com/containers/buildah/blob/master/install.md#building-from-scratch) instructions.  However, the runc can be either runc or crun with a preference for crun these days.  (Note to self, install guide needs some updates)

Once you have that setup,  I'd make a small change [here](https://github.com/containers/buildah/blob/master/cmd/buildah/images.go#L122) just adding a small fmt.Printf() like `fmt.Printf("Diego was here\n")` and then `make`, `make install`, `buildah images` and you should see your output there.  That's just a quick test to make sure everything is all set.

After that, you'll need to get the output of the FROM that you see in a build to be added to the history of the image.  So for instance I just had `FROM centos:8` in my Containerfile and when I do `buildah bud -t diego .` and then `buildah inspect diego` I should be able to see that FROM statement in the history.

I don't have a quick pointer for where to add the code but, the bud code starts [here](https://github.com/containers/buildah/blob/master/cmd/buildah/bud.go) and the `STEP` that you see in the output of the build comes from [here](https://github.com/containers/buildah/blob/master/imagebuildah/executor.go#L220) .  Somewhere below that the history is getting written, I don't have a quick pointer, @nalind may, but searching might be a good exercise.

Looking at this further, this may prove to be a strong first issue.  I hope you'll pursue it and thanks for the interest!

**Comment by ironknight78** [comment]
Hey @TomSweeneyRedHat !! :D awesome, thank you for the warm welcome!! I'll start investigating this right away.

**Comment by ironknight78** [comment]
Nice, I got the dev environment all set and ready to go, I'll start digging into the problem now :)

`ironknight78@kube-devel:~/buildah/src/github.com/containers/buildah$ buildah images
Hey, what's up Tom.
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
`

**Comment by ironknight78** [comment]
Sir, may I call #dibs on this issue? I think I'm getting close.

**Comment by rhatdan** [comment]
Go for it.

**Comment by TomSweeneyRedHat** [comment]
Indeed and assigned.  You're stuck now @ironknight78 !

**Comment by ironknight78** [comment]
Hey @TomSweeneyRedHat .. I think I finally got it!! It was kind of hard walking through the code.. can you help me doing the PR for testing? I'm not really sure how to do it

**Comment by ironknight78** [comment]
I think I got it.. Hope it passes the tests! :)

**Comment by ironknight78** [comment]
I opened a new PR since it was getting kind of messy @TomSweeneyRedHat @rhatdan

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@umohnani8 Did you end up merging this?

**Comment by umohnani8** [comment]
@rhatdan just opened a PR with the fix

**Comment by rhatdan** [comment]
Great.
