### ISSUE TITLE
buildah bud --layers=false / does not handle WORKDIR correctly.

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#2402]
If I have a Dockerfile that looks like:

```
FROM fedora
WORKDIR /test
```
And then run `buildah bud -t workdir --layers=false .` on it multiple times.  The second time, it will not create the /test directory in the image.
```
podman run workdir pwd
Error: chdir: No such file or directory: OCI runtime command not found error
```
If I run `buildah bud -t workdir --layers=true .`
 ```
podman run workdir pwd
/test
```

**Comment by nalind** [comment]
This'll overlap with changes to `imagebuildah.StageExecutor.Execute()` that I'm working on, so I'll take this one.

**Comment by TomSweeneyRedHat** [comment]
Does https://github.com/containers/podman/pull/7239 help/solve this?

**Comment by rhatdan** [comment]
@nalind did you ever make any headway with this?

**Comment by rhatdan** [comment]
@vrothberg I think you had a similar issue?

**Comment by vrothberg** [comment]
It's addressed on the Podman-side where the workdir from an image is guaranteed to be created by Podman in case it doesn't exist on the root FS of the image.

**Comment by rhatdan** [comment]
@nalind Did you ever complete this?

**Comment by rhatdan** [comment]
This seems to work now.
