### ISSUE TITLE
cache bypassed when COPY'ing into empty image, such as "scratch"

### ISSUE THREAD

**Issue by jamescassell** [containers/buildah#2403]
**Description**
Currently, when doing a multi-stage bulid and using `FROM scratch` in a later stage, buildah creates a different `scratch` image every time and therefore gets zero caching, causing much slowed builds an greatly increased disk usage.  I've been able to workaround it by `c=$(buildah from scratch) ; buildah commit $c myscratch` then using `FROM myscratch` instead of `FROM scratch`.

**Steps to reproduce the issue:**
1. `podman build -f Dockerfile`
2. do it again
3. observe multiple images even though no changes to the `Dockerfile`
```
FROM fedora as build

FROM scratch
COPY --from=build / /
```

**Describe the results you received:**
Every run creates the image again with a different hash, and there is no caching.

**Describe the results you expected:**
Cache used for `scratch` images.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
podman-1.9.3-1.fc32.x86_64
buildah-1.14.9-1.fc32.x86_64

```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
completely stock
```
(paste your output here)
```

**Comment by jamescassell** [comment]
simpler reproducer:
scratch.Dockerfile:
```
FROM scratch as myscratch
```
the build it using
`podman build -f scratch.Dockerfile`

and build it again, and observe it not using the previous image, but creating a new one.

Further, it seems buildah special cases any image whose name is `scratch` and doesn't actually use it, but instead generates an internal version

**Comment by jamescassell** [comment]
Did some further digging, and it's not whether there's a real image or not. it's whether there's a non-empty layer in it or not.  quay.io refuses to build a non-empty layer without any files in it, so I made one with just a single `/root` directory in it. (see my `quay.io/cassell/scratch` image)

**Comment by jamescassell** [comment]
I've decided this is a bug, and has nothing to do with the scratch image, but an issue w/ buildah not caching copies into scratch images. Changed the title as such.

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by nalind** [comment]
I'm already poking around in this area.  Self-assigning.

**Comment by rhatdan** [comment]
Adding the the great COPY Slow label.
