### ISSUE TITLE
Alternative path for storage.conf , containers.conf

### ISSUE THREAD

**Issue by mrinaldhillon** [containers/buildah#2464]
buildah expects storage.conf, container.conf from /use/share/containers, /etc/containers, $HOME/.config/containers and XDG_CONFIG_HOME. Can we add an option to specify alternate path to user configs from command line or through environment variables . This will be useful for automated  builds as unprivileged user.

CONTAINERS_CONFIG_DIR=/mydir
Or
buildah/podman  --containers-conf=/mydir

**Comment by rhatdan** [comment]
CONTAINERS_CONF=/mydir works now, but only for containers.conf, not storage.conf, registries.conf ...

I would guess XDG_CONFIG_DIR, would be the way to handle this, but I don't believe we do this now.

**Comment by rhatdan** [comment]
HOME=/mydir podman ...
Would also cause us to look for the files in /mydir/.config/containers/*

**Comment by mrinaldhillon** [comment]
Will HOME=/mydir pickup storage.conf as well?

**Comment by rhatdan** [comment]
Yes, I believe it will.

**Comment by rhatdan** [comment]
in storage/store.go
```
// DefaultConfigFile returns the path to the storage config file used
func DefaultConfigFile(rootless bool) (string, error) {
	if rootless {
		if configHome := os.Getenv("XDG_CONFIG_HOME"); configHome != "" {
			return filepath.Join(configHome, "containers/storage.conf"), nil
		}
		home := homedir.Get()
		if home == "" {
			return "", errors.New("cannot determine user's homedir")
		}
		return filepath.Join(home, ".config/containers/storage.conf"), nil
	}
	return defaultConfigFile, nil
}
```
