### ISSUE TITLE
buildah container in podman pod?

### ISSUE THREAD

**Issue by astronouth7303** [containers/buildah#2491]
Is it possible to create a buildah container (`buildah from`) that exists inside of (or at least is networked with) a podman pod?

**Comment by rhatdan** [comment]
You should be able to do this.
I would suggest using quay.io/buildah/stable.  This image is configured to run within a locked down container.

**Comment by TomSweeneyRedHat** [comment]
If you play around with it and get it working to your satisfaction, a little blog post for buildah.io would be gratefully accepted.  If you've problems or more detailed questions along the way, please holler!

**Comment by astronouth7303** [comment]
Oh, I'll try that.

I initially meant "Can a container managed by buildah exist in a podman pod network"? But I guess running buildah from inside a podman container would accomplish that.
