### ISSUE TITLE
Unable to build container in container with storage vfs

### ISSUE THREAD

**Issue by jamesregis** [containers/buildah#2504]
**Description**

**Steps to reproduce the issue:**
1. Deploy AWX in docker container 
2. Install podman (with dnf install)
3. clone https://github.com/openshift/golang-ex
4. try to build golang-ex

**Describe the results you received:**

I have a permission error : 

```
(home) bash-4.4# podman build . -t registry.home.lan/dev/golang-ex
STEP 1: FROM golang:1.11
Getting image source signatures
Copying blob bbab4ec87ac4 done  
Copying blob 4ae16bd47783 done  
Copying blob 2ea1f7804402 done  
Copying blob 96465440c208 done  
Copying blob 16a3d8aca6cd done  
Copying blob 3a62db25bdbe done  
Copying blob 8c47c6b16c60 done  
Copying config 43a154fee7 done  
Writing manifest to image destination
Storing signatures
STEP 2: USER nobody
--> c08556a5fc6
STEP 3: RUN mkdir -p /go/src/github.com/openshift/golang-ex
error running container: error creating new mount namespace for [/bin/sh -c mkdir -p /go/src/github.com/openshift/golang-ex]: operation 
not permitted
Error: error building at STEP "RUN mkdir -p /go/src/github.com/openshift/golang-ex": error while running runtime: exit status 1
```

**Describe the results you expected:**
The container should be build

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.15.1-1.el8.x86_64
```

**Output of `buildah version`:**

```
(home) bash-4.4# buildah version
Version:         1.15.1
Go Version:      go1.13.4
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.1
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(home) bash-4.4# podman version
Version:      2.0.3
API Version:  1
Go Version:   go1.13.4
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 8.2.2004 (Core) 
```

**Output of `uname -a`:**

```
Linux awx 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "vfs"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
override_kernel_check = "true"
[storage.options.thinpool]
ostree_repo = ""
skip_mount_home = "false"
```

**Comment by rhatdan** [comment]
This worked for me with buildah bud
```
golang-ex (master) $ buildah bud -t registry.home.lan/dev/golang-ex .
STEP 1: FROM golang:1.11
Getting image source signatures
Copying blob bbab4ec87ac4 done  
Copying blob 4ae16bd47783 done  
Copying blob 2ea1f7804402 done  
Copying blob 96465440c208 done  
Copying blob 16a3d8aca6cd done  
Copying blob 3a62db25bdbe done  
Copying blob 8c47c6b16c60 done  
Copying config 43a154fee7 done  
Writing manifest to image destination
Storing signatures
STEP 2: USER nobody
STEP 3: RUN mkdir -p /go/src/github.com/openshift/golang-ex
STEP 4: WORKDIR /go/src/github.com/openshift/golang-ex
STEP 5: COPY . /go/src/github.com/openshift/golang-ex
STEP 6: RUN go build
go: disabling cache (/nonexistent/.cache/go-build) due to initialization failure: mkdir /nonexistent: permission denied
STEP 7: CMD ["./golang-ex"]
STEP 8: COMMIT registry.home.lan/dev/golang-ex
Getting image source signatures
Copying blob 660314270d76 skipped: already exists  
Copying blob 6d5a64ea8f37 skipped: already exists  
Copying blob 74e2ede3b29c skipped: already exists  
Copying blob 97e8dd85db4e skipped: already exists  
Copying blob 39a8c34bbaf3 skipped: already exists  
Copying blob 7ffca9f27ea7 skipped: already exists  
Copying blob 18dccb3264f2 skipped: already exists  
Copying blob e4785ff544c0 done  
Copying config f9bb65c4e7 done  
Writing manifest to image destination
Storing signatures
--> f9bb65c4e71
f9bb65c4e715e453b9eb56dae44234b93f6f6cedeb2afe2b9a5999ec549aaf99
golang-ex (master) $ buildah -v
buildah version 1.15.0 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Comment by rhatdan** [comment]
Also worked with podman
```
golang-ex (master) $ podman build -t registry.home.lan/dev/golang-ex .
STEP 1: FROM golang:1.11
STEP 2: USER nobody
--> 20ca01b7525
STEP 3: RUN mkdir -p /go/src/github.com/openshift/golang-ex
--> 3c769b1a867
STEP 4: WORKDIR /go/src/github.com/openshift/golang-ex
--> b9be6676d36
STEP 5: COPY . /go/src/github.com/openshift/golang-ex
--> 6ba45a12c5f
STEP 6: RUN go build
go: disabling cache (/nonexistent/.cache/go-build) due to initialization failure: mkdir /nonexistent: permission denied
--> 377e761ef8a
STEP 7: CMD ["./golang-ex"]
STEP 8: COMMIT registry.home.lan/dev/golang-ex
--> 4d33d53387f
4d33d53387f88d334999b82d32325e25f167f544bae4acd3bcebe32cd201a1d3
golang-ex (master) $ podman --version
podman version 2.1.0-dev
```

**Comment by jamesregis** [comment]
@rhatdan Thank you.
Are you building from AWX tasks container or another container ?

**Comment by rhatdan** [comment]
Well I did not use the vfs storage, which would be one difference, that I am just now noticing?  I use overlay (fuse-overlayfs to be exact)
Any reason  you are using vfs?

Are you doing this build as root or non root?  I did my tests as non-root. 

I also did
$ git clone git@github.com:openshift/golang-ex.git
$ cd golang-ex
$ buildah bud  -t registry.home.lan/dev/golang-ex .

**Comment by jamesregis** [comment]
I am using vfs, because with overlay my playbook failed.
I am root on my container :+1: 

> uid=0(root) gid=0(root) groups=0(root)

**Comment by jamesregis** [comment]
I can see I have no user namespace available : 

```
(home) bash-4.4# sysctl -A | grep namespace
user.max_ipc_namespaces = 127848
user.max_mnt_namespaces = 127848
user.max_net_namespaces = 127848
user.max_pid_namespaces = 127848
user.max_user_namespaces = 0
user.max_uts_namespaces = 127848
(home) bash-4.4# sysctl user.max_user_namespaces=1500
sysctl: setting key "user.max_user_namespaces": Read-only file system
(home) bash-4.4# sudo bash -c 'echo 10000 > /proc/sys/user/max_user_namespaces'
bash: /proc/sys/user/max_user_namespaces: Read-only file system

```

**Comment by jamesregis** [comment]
> Well I did not use the vfs storage, which would be one difference, that I am just now noticing? I use overlay (fuse-overlayfs to be exact)
> Any reason you are using vfs?
> 
> Are you doing this build as root or non root? I did my tests as non-root.
> 
> I also did
> $ git clone [git@github.com](mailto:git@github.com):openshift/golang-ex.git
> $ cd golang-ex
> $ buildah bud -t registry.home.lan/dev/golang-ex .

With overlay I've got this error : 

`[root@64ec7f5be887 golang-ex]# podman build . -t golang-ex
Error: could not get runtime: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
[root@64ec7f5be887 golang-ex]# 
`

**Comment by rhatdan** [comment]
You need to install fuse-overlay on your system and then reset your storage.
This will allow you to use rootless overlay.

**Comment by rhatdan** [comment]
rpm -q fuse-overlayfs
fuse-overlayfs-1.1.2-1.fc32.x86_64

**Comment by jamesregis** [comment]
@rhatdan : can you run this command and show me the result :

`sysctl -A | grep namespacesysctl -A | grep namespace`

**Comment by rhatdan** [comment]
```
# sysctl -A | grep namespace
user.max_cgroup_namespaces = 62468
user.max_ipc_namespaces = 62468
user.max_mnt_namespaces = 62468
user.max_net_namespaces = 62468
user.max_pid_namespaces = 62468
user.max_time_namespaces = 62468
user.max_user_namespaces = 62468
user.max_uts_namespaces = 62468

$  sysctl -A | grep namespace
sysctl: permission denied on key 'fs.protected_fifos'
sysctl: permission denied on key 'fs.protected_hardlinks'
sysctl: permission denied on key 'fs.protected_regular'
sysctl: permission denied on key 'fs.protected_symlinks'
sysctl: permission denied on key 'kernel.cad_pid'
sysctl: permission denied on key 'kernel.usermodehelper.bset'
sysctl: permission denied on key 'kernel.usermodehelper.inheritable'
sysctl: permission denied on key 'net.core.bpf_jit_harden'
sysctl: permission denied on key 'net.core.bpf_jit_kallsyms'
sysctl: permission denied on key 'net.core.bpf_jit_limit'
sysctl: permission denied on key 'net.ipv4.tcp_fastopen_key'
sysctl: permission denied on key 'net.ipv6.conf.all.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.cni-podman0.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.default.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.enp0s20f0u3u4u4.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.enp0s31f6.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.lo.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.tun0.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.veth79524956.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.virbr0.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.virbr0-nic.stable_secret'
sysctl: permission denied on key 'net.ipv6.conf.wlp2s0.stable_secret'
sysctl: permission denied on key 'vm.mmap_rnd_bits'
sysctl: permission denied on key 'vm.mmap_rnd_compat_bits'
user.max_cgroup_namespaces = 62468
user.max_ipc_namespaces = 62468
user.max_mnt_namespaces = 62468
user.max_net_namespaces = 62468
user.max_pid_namespaces = 62468
user.max_time_namespaces = 62468
user.max_user_namespaces = 62468
user.max_uts_namespaces = 62468
sysctl: permission denied on key 'vm.stat_refresh'
```

**Comment by rhatdan** [comment]
I am on Fedora 32

**Comment by jamesregis** [comment]
I had to reinstall my server. I am now on Centos 8.2 and I will try to use fuse-overlayfs.

**Comment by jamesregis** [comment]
Hi @rhatdan, 

I was able to compile golang-ex (with fuse-overlayfs) in my server :

`[root@server golang-ex]# podman build . -t golang-ex
STEP 1: FROM golang:1.11
Getting image source signatures
Copying blob 96465440c208 done
Copying blob 3a62db25bdbe done
Copying blob 16a3d8aca6cd done
Copying blob bbab4ec87ac4 done
Copying blob 2ea1f7804402 done
Copying blob 4ae16bd47783 done
Copying blob 8c47c6b16c60 done
Copying config 43a154fee7 done
Writing manifest to image destination
Storing signatures
STEP 2: USER nobody
e0358379e7846fde15c8e8b8d7d724fe42fec4ad5294ea22b97b74c977863284
STEP 3: RUN mkdir -p /go/src/github.com/openshift/golang-ex
028be9f0fd44fcca245b654ed0c89f0d5c12175a59978ae2815a5bc0ebe47cbc
STEP 4: WORKDIR /go/src/github.com/openshift/golang-ex
f7afeb297ab5a64647ed2795d4f7e62baf8bcc9aa8b62570f80e6856e3c8f245
STEP 5: COPY . /go/src/github.com/openshift/golang-ex
61efdaefc44fd10bfd2f93d072c79c1634d8f5e81562be000fd556b0945f6c20
STEP 6: RUN go build
go: disabling cache (/nonexistent/.cache/go-build) due to initialization failure: mkdir /nonexistent: permission denied
d7dcecbeed3248855b05f335cc7cca9dad265cee75abed1456c9135ccef39492
STEP 7: CMD ["./golang-ex"]
STEP 8: COMMIT golang-ex
0c6412e381a8ab272935fbfe88cb1d3f4fc6f8a429ba98cf445e29d9ddd75ba3
[root@server golang-ex]# podman images
REPOSITORY                                     TAG      IMAGE ID       CREATED          SIZE
localhost/golang-ex                            latest   0c6412e381a8   34 seconds ago   833 MB
localhost/centos8-bash                         latest   95c1762f2180   2 days ago       212 MB
<none>                                         <none>   40988c5c6e25   2 days ago       212 MB
registry.centos.org/centos                     latest   c46009597289   2 months ago     212 MB
registry.svc.ci.openshift.org/origin/release   4.3      ba2b359a1b1a   5 months ago     301 MB
docker.io/sebp/lighttpd                        latest   a645c934688e   6 months ago     14.1 MB
docker.io/library/golang                       1.11     43a154fee764   11 months ago    817 MB
`
but in awx container I've got this error :

`(home) bash-4.4# podman build . -t golang-ex
Error: could not get runtime: operation not permitted
`

**Comment by jamesregis** [comment]
This is my configuration : 





                            +-------------------server+
                            |                         |
                            |                         |          containers
                            |   +----------awx_task   |             +
    I am trying to run      |   |                |    |             |
    podman in awx_task--------------+          v--------------------+
    container, to build     |   +----------------+    |             |
    golang-ex               |                         |             |
                            |   +---------awx_web+    |             |
                            |   |                |    |             |
                            |   |             v---------------------+
                            |   +----------------+    |             |
                            |                         |             |
                            |   +---------redis--+    |             |
                            |   |                |    |             |
                            |   |             v---------------------+
                            |   +----------------+    |             |
                            |                         |             |
                            |   +----------postgres   |             |
                            |   |                |    |             |
                            |   |               v-------------------+
                            |   +----------------+    |
                            |                         |
                            |                   v-------------+  docker runtine
                            +-------------------------+


I have a baremetal server named server and I am running 4 containers with docker as runtime (with docker-compose).
I want to run podman from awx_task.

**Comment by rhatdan** [comment]
Running a container within a container is not supported without running a privileged container.

**Comment by jamesregis** [comment]
**server** is a baremetal server running awx containers.
in awx_task I don't want to run a container. I just want to build a container and push the image in a registry.

**Comment by rhatdan** [comment]
Only way to do this is with buildah directly and --isolation=chroot.
