### ISSUE TITLE
Support named volumes in buildah run

### ISSUE THREAD

**Issue by dominic-p** [containers/buildah#2512]
**Description**

I apologize if this has been requested before, but I didn't see any related issues. It would be handy for me to be able to mount a named volume when building a container. From the man page it looks like buildah run supports --mount and --volume, but only physical host paths and tmpfs seem to be supported currently.

My use case is kind of convoluted (and maybe there's a better way), but basically I want to create a named volume for my node_modules folder that's populated at build time that I can mount later when running the container in development.

**Steps to reproduce the issue:**
1. buildah run --volume namedvol:/path/in/container containerID sh

**Describe the results you received:**
An error saying the source path is not a valid path on the host.

**Describe the results you expected:**
A named volume is mounted (and created if necessary)

**Comment by TomSweeneyRedHat** [comment]
@dominic-p thanks for the issue.  I'm not a volume heavy person, can you also include the commands that you used to create your volume and on what Operating System?  I'm also assuming this using Buildah 1.15 or greater, please let us know if not.

**Comment by dominic-p** [comment]
Thanks for following up. I'm using Pop OS 20 (it's a flavor of Ubuntu). I'm sorry I don't have the machine in front of me at the moment, but it's running the latest buildah release from the Ubuntu PPA.

As for the command to create the volume, I pretty much just use a --volume flag when I run `podman run`. That will create the named volume if it doesn't exist already. It works great with podman. I was just hoping for similar functionality with buildah. Does that make sense, or am I misunderstanding your question?

**Comment by TomSweeneyRedHat** [comment]
Thanks @dominic-p , that makes sense.  I just wasn't sure if you'd done any pre-setup for the volumes before hand and wanted to verify.

**Comment by rhatdan** [comment]
Are you planning on running the buildah and podman on same box?  IE You want  named volume populated while building and then later run podman and have access to the data.
This would be simple to do using regular volumes

buildah bud -t test -v ~/.mydata:/vol1:z .
podman run -v ~/mydata:/vol1:z test

**Comment by dominic-p** [comment]
Thanks for the suggestion. I hadn't thought of creating a dedicated path on this host for this. I'll give it a try, and see if I can make it work.

**Comment by dominic-p** [comment]
It looks like just using a host path will work for this. It's not as portable as I would like (you have to create the path on the host beforehand), but that should be fine for now. I really appreciate the help.
