### ISSUE TITLE
xz package missing in quay.io/buildah/stable

### ISSUE THREAD

**Issue by jobcespedes** [containers/buildah#2525]
**Description**
xz package missing in quay.io/buildah/stable

**Steps to reproduce the issue:**
1. Clone https://github.com/krestomatio/centos8-minimal
2. Build inside quay.io/buildah/stable
3. Run the container

**Describe the results you received:**
No build error. After build, trying to run something from centos8-minimal gives:
```
Error: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": OCI runtime command not found error
```

After `dnf install xz` inside the buildah container and building it again, container runs succesfully

**Describe the results you expected:**
Run container succesfully

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.15.0-1.fc32.x86_64
```

**Output of `buildah version`:**

```
Version:         1.15.0
Go Version:      go1.14.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.1
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```
**Output of `cat /etc/*release`:**

```
Fedora release 32 (Thirty Two)
NAME=Fedora
VERSION="32 (Container Image)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Container Image)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
Fedora release 32 (Thirty Two)
Fedora release 32 (Thirty Two)
```

**Output of `uname -a`:**

```
Linux krestomatio-container-builder-m-nlj26-47-build-containers-dblz8 4.19.112+ #1 SMP Thu May 21 12:32:38 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
"/var/lib/shared",
]
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0"
[storage.options.thinpool]
```

**Comment by rhatdan** [comment]
Could you open a PR to fix this?

**Comment by jobcespedes** [comment]
Sure

**Comment by jobcespedes** [comment]
I was thinking in adding it to the Dockerfile. Would it be better to add it as a dependency of buildah and podman rpms?

**Comment by TomSweeneyRedHat** [comment]
@jobcespedes For the short term, I'd add it to the Dockerfiles.  However, it would probably make sense to add it as at least a recommended install with the rpm.  i.e. the install won't fail if xz isn't installable for whatever reason.  @lsm5 thoughts?

**Comment by jobcespedes** [comment]
One more thing: shouldn't be a error or failure handling in place when adding a tar.xz during building and it cannot be uncompressed? I'm assuming uncompressed happens during building and not while running the container. I'm not sure.

**Comment by rhatdan** [comment]
Could you update this requirement in  contrib/spec/podman.spec.in

**Comment by jobcespedes** [comment]
> Could you update this requirement in contrib/spec/podman.spec.in

Added as recommeded.

Should I modified this pull request to only add xz in contrib/rpm/buildah.spec?
