### ISSUE TITLE
dns-option ignored if dns-search is not set

### ISSUE THREAD

**Issue by jasinner** [containers/buildah#2541]
**Description**

setting --dns-option is ignored if dns-search is not also set

**Output of `buildah version`:**

```
master branch
```

[This line](https://github.com/containers/buildah/blob/3fc7c4bc2bd3c5c105487e160b20356a0e8de46c/pkg/parse/parse.go#L104) seems to incorrectly check the default for --dns-search instead of dns-option. Found via coverity scan of OpenShift 4.6

**Comment by rhatdan** [comment]
Thanks I will open a PR.

Next time just open a PR to fix rather then an issue, if you feel comfortable.

**Comment by rhatdan** [comment]
This has been fixed.
