### ISSUE TITLE
insecureRegistries from BUILD_REGISTRY_SOURCES ignored

### ISSUE THREAD

**Issue by stephen-dexda** [containers/buildah#2586]
**Description**

`insecureRegistries` from the `BUILD_REGISTRY_SOURCES` env. var. is ignored.

There's nothing in the source that actually handles this key AFAICS - the only reference is https://github.com/containers/buildah/blob/master/commit.go#L186.

The `insecureRegistries` key is mentioned in e.g. `man buildah-pull` and `man buildah-push`. At a minimum the documentation should mention that the key is currently non-functional.

**Steps to reproduce the issue:**

```
BUILD_REGISTRY_SOURCES='{"insecureRegistries": ["<registry>"]}' buildah push <img> <registry>/<img>
```

**Describe the results you received:**

```
Get "https://<registry>/v2/": http: server gave HTTP response to HTTPS client
ERRO exit status 125
```

**Describe the results you expected:**

Successful push to registry.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.15.1-1.fc32.x86_64
```

**Comment by QiWang19** [comment]
The error seems unrelated with the `BUILD_REGISTRY_SOURCES` env, https://github.com/containers/buildah/blob/438046e88d5cd17c9b7c22e076bf5f0cbeece85a/commit.go#L474 does'not deny the registry by default.

**Comment by stephen-dexda** [comment]
Buildah is not treating the registry as insecure when connecting, and is instead (only) attempting to connect via HTTPS, hence the error (since TLS is not enabled).

In contrast, if the registry is configured as insecure via the following in `/etc/containers/registries.conf`, push/pull commands succeed.

```toml
[[registry]]
location = "<registry>"
insecure = true
```

I would expect the env. var. JSON to have the same effect.
