### ISSUE TITLE
V1.16.0 -> v1.16.0

### ISSUE THREAD

**Issue by hswong3i** [containers/buildah#2587]
**Description**

Should https://github.com/containers/buildah/releases/tag/V1.16.0 be tagged as https://github.com/containers/buildah/releases/tag/v1.16.0 (regex friendly as previous version)?

**Comment by vrothberg** [comment]
Thanks for catching it, @hswong3i!

@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
Fixed.

**Comment by graywolf-at-work** [comment]
If possible, if this happens again, could you keep the old (wrong) tag as well? It broke our builds since we have already started to use the `V` version.

I know that the fix is trivial, but still...

**Comment by vrothberg** [comment]
Thanks for reaching out, and apologies for breaking!

Absolutely. We'll be careful next time. The GitHub interface seems to really rename the tag. Next time, we'll do it manually and keep the old tag around :+1:

**Comment by TomSweeneyRedHat** [comment]
@graywolf-at-work I'll echo what @vrothberg said and also thank you for leting us know.  That was not something I'd on my radar as a possible problem with that change.  I'll keep that in back of mind going forward.
