### ISSUE TITLE
Wrong history dates when using --timestamp

### ISSUE THREAD

**Issue by tensor5** [containers/buildah#2589]
**Description**

Creating an image with `buildah bud --timestamp 0` produces wrong history timestamps. It could be even useful to have an option to skip history generation altogether.

**Steps to reproduce the issue:**
1. `echo hello > hello`
2. 
```shell-session
$ cat << EOF > Containerfile
FROM scratch

COPY hello /

LABEL com.example=foo

ENV foo=bar

ENTRYPOINT ["hello"]
EOF
```
3. `buildah bud --timestamp 0 .`
4. `podman history <resulting hash>`

**Describe the results you received:**

Only the first (last) history entry has creation timestamp equal to 0.

**Describe the results you expected:**

All history timestamps should be zero.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah 1.16.0-1
```

**Output of `buildah version`:**

```
Version:         1.16.0
Go Version:      go1.15.1
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.2-0.20190904153231-83439463f784
image Version:   5.5.2
Git Commit:      295b825c
Built:           Sun Sep  6 20:46:22 2020
OS/Arch:         linux/amd64
```

**Comment by rhatdan** [comment]
This is fixed in main branch.
