### ISSUE TITLE
build a large image with buildah use more time than docker a lot

### ISSUE THREAD

**Issue by zvier** [containers/buildah#2600]
My Dockerfile is as flows and the output image size is 523M
```Dockerfile
FROM alpine AS buildc
RUN apk add --no-cache build-base
RUN echo -e "#include <stdio.h>\nint main(int ac, char *av[]){printf(\"hello c\\\\n\");return 0;}" | tee /hello.c
COPY . /foo
RUN gcc -o /a.out /hello.c

# the COPY above SHOULD NOT invalidate the cache for the buildgo stage.

FROM alpine AS buildgo
RUN apk add --no-cache build-base
RUN apk add --no-cache go
RUN echo -e "package main\nfunc main(){println(\"hello go\")}" | tee /hello.go
RUN go build -o /a.out /hello.go
```

# builadh
```
 time builadh bud -f Dockerfile
```
It cost 1m28s with buildah.

# docker
```
time docker build --no-cache -f Dockerfile .
```
It cost 39s with docker.

We also analysize the buildah with pprof and find it cost a lot of time call io.Copy and sha256.Write. Statistics indicate that it call sha256.Write more than one hundred thousand in the build. For build a large image, may be use io.CopyBuffer with a reasonable buffer can relieve this problem.

![profile001](https://user-images.githubusercontent.com/39317604/92576563-41cdc800-f2bc-11ea-9bfe-97418258b7aa.png)

**Comment by TomSweeneyRedHat** [comment]
@zvier thanks very much for the very thorough problem report.  I know @nalind has been working feverishly on making the builds faster, so I'll ask him to comment on that status.

**Comment by jingxiaolu** [comment]
@TomSweeneyRedHat @nalind 
could you please share your updates here? many thanks~

**Comment by rhatdan** [comment]
@jingxiaolu There has been a full rewrite of the COPY code, we would love to have you run your analysys on the master branch or v1.16.2 to see how much it has improved.

**Comment by jingxiaolu** [comment]
@rhatdan thanks very much for your update!
@zvier please~

**Comment by zvier** [comment]
> @jingxiaolu There has been a full rewrite of the COPY code, we would love to have you run your analysys on the master branch or v1.16.2 to see how much it has improved.

Fantastic job ，20s in my environment with this new version, about 19s more faster than docker.

**Comment by TomSweeneyRedHat** [comment]
@zvier thanks very much for the follow-up.  I'm so glad the changes were successful for your environment.
