### ISSUE TITLE
Parallel builds can fail with shared bind mount

### ISSUE THREAD

**Issue by daveisfera** [containers/buildah#2602]
**Description**
When using a bind mount to share a cache, some uses require a lock (like `apt-get`), so there needs do be a way to lock the use of the bind mount.

**Steps to reproduce the issue:**
Trying to switch from docker/buildkit and noticed that this is a problem
See https://github.com/moby/buildkit/issues/1662

**Describe the results you received:**
Build can fail because lock isn't available

**Describe the results you expected:**
Parallel builds can be run without issue

**Output of `rpm -q buildah` or `apt list buildah`:**
```
buildah-1.15.1-1.el7.x86_64
```

**Output of `buildah version`:**
```
buildah version 1.15.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `cat /etc/*release`:**
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```

**Output of `uname -a`:**
```
Linux ip-172-31-8-131.us-west-2.compute.internal 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage" 
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```
(I removed all of the comments)

**Comment by rhatdan** [comment]
Sorry this seems to have gotten lost in the weeds.  Could you give us a Containerfile with a simple reproducer to see what is going on here?

**Comment by daveisfera** [comment]
Any use of `apt-get` should cause the problem. The tricky part is running two in parallel and having the layers that use `apt-get` run at the same time and run into the conflict (which isn't common on our build server, but does occasionally happen when multiple builds are continuously happening throughout the day)

**Comment by rhatdan** [comment]
Could you give me an idea of the podman/buildah command that you are using to get this to happen?  Are you talking about a volume mount, or additional stores or just simply sharing the same base images?  Are you running into problems on rootfull or rootless?

**Comment by daveisfera** [comment]
We'd like to switch to `buildah` but this is a blocker when using a shared cache between the builds to keep images smaller and minimize network traffic. Basically, we haven't yet switched (and have given up on plans to do so) because it would cause failed builds. For example, build this image ( https://github.com/rethinkdb/rethinkdb-dockerfiles/blob/444f7754822cb3e96cb2b66042d8e87d2227be0b/buster/2.4.0/Dockerfile ) which calls `apt-get` in one of its layers at the same time as building another image that also calls `apt-get` at the same time and if both of those layers are built at the same time, then the second will fail when trying to get the lock. `docker` has a mechanism to prevent multiple uses of a shared cache at the same time and that's what's needed with `buildah`

**Comment by rhatdan** [comment]
Could you try this with an overlay mount?
Basically and overlay mount is like a writable bind mount where only the containers see the writes, the other container will not see any changes caused by the second container, but they can both read the lower layer.  Would this solve the problem?

I talk about overlay mounts here:

https://www.redhat.com/sysadmin/overlay-mounts

**Comment by daveisfera** [comment]
How is a shared cache supposed to work if nothing can write to it?

**Comment by rhatdan** [comment]
Yes, I talked to @nalind on a different channel and he pointed this out.  What it seems to need is a way to coordinate a lock on the directory so any use of it requires the lock.  If Buildah could not get the lock, it would wait until the lock frees up.
Not sure what the easiest way to do this would be.

**Comment by daveisfera** [comment]
Yes, I would agree that that's the requirement I was trying to describe in the original comment. Basically, shared mounts are great for caching, but some use cases need exclusive access, so a lock or some other way to handle that is available in `docker` and would be needed to be able to reliably replace it in an environment that's doing multiple builds in parallel (like a build server).

**Comment by rhatdan** [comment]
We have made no progress on this.

**Comment by flouthoc** [comment]
Locking support and with mount=type=cache is implemented here hence closing this issue: https://github.com/containers/buildah/pull/3820
