### ISSUE TITLE
Unshare (non-root): Buildah Script Example in MAN page does not work

### ISSUE THREAD

**Issue by SwitchedToGitlab** [containers/buildah#2612]
`buildah unshare` man page script example does not work. I take the script example, I save it as a .sh file, I even make it +x, I get an error message when attempting to run it.

You might also want to note I'm using ZSH, which appears to affect not only how the here doc works, but also seems to make any variables created in a sub-shell not work as expected either.

Not sure if I should create another bug here, as I don't understand sub-shell that buildah is doing with the unshare command, but the only usage of this command that has worked for me is `cnt=$(buildah from scratch); buildah unshare --mount FOO=$cnt`

FRUSTRATED USER COMMENT:

This probably isn't the place for this, but the `unshare` command is exceptionally frustrating and really negates the value of `buildah` in lot of ways, as you can't easily mount your container's filesystem *in a script* without having to jump through the `unshare` hoop and deal with all the sub-shell madness. A great example is that this *DOES NOT* work with Make. 

It's super, super disappointing and another example of how the podman/buildah suite of tools falls flat when faced with root/rootless issues. I just cannot understand why the development team can't account for the tool being run as non-root and why it continues to make users pull their hair out trying to tease the myriad of functional differences between the two. I have to say I've spent waaaay more time on these kinds of issues than I should have and it's frankly silly to even expect users to understand the differences. Just a quick peek at the buildah/podman issue tracker should tell you it's a problem.

For me it represents yet another day's worth of work wasted trying to make the switch to Podman/Buildah, as this Makefile just isn't going to work like this, and I'm not running it as root. I kind of can't believe that in 2020 root vs non-root is even still a thing to be quite frank. 

**Steps to reproduce the issue:**
1. Follow the man page to create a script file
2. `buildah unshare buildah-script.sh`
3. cry

**Describe the results you received:**
```
⌬ cat buildah-script.sh 
#!/bin/sh
ctr=$(buildah from scratch)
mnt=$(buildah mount $ctr)
zypper --non-interactive install --installroot=$mnt zsh
buildah config --entrypoint="/bin/zsh"
buildah commit $mnt
buildah unmount

⌬ buildah unshare buildah-script.sh
ERRO exec: "buildah-script.sh": executable file not found in $PATH 
ERRO (unable to determine exit status)            
ERRO exit status 1 
```

**Describe the results you expected:**
An image created as documented in the MAN page.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
⌬ rpm -q buildah
buildah-1.15.1-1.2.x86_64
```

**Output of `buildah version`:**

```
⌬ buildah version
Version:         1.15.1
Go Version:      go1.14.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.2-0.20190904153231-83439463f784
image Version:   5.5.1
Git Commit:      unknown
Built:           Sun Aug  2 18:00:00 2020
OS/Arch:         linux/amd6
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
⌬ cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20200909"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20200909"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20200909"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

```

**Output of `uname -a`:**

```
⌬ uname -a
Linux rocinante 5.8.7-1-default #1 SMP Sun Sep 6 07:39:46 UTC 2020 (7fc52c0) x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
⌬ cat ~/.config/containers/storage.conf 
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/user/1000/containers"

# Primary Read/Write location of container storage
graphroot = "/home/sbrady/.local/share/containers/storage/"

[storage.options]

# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
# additionalimagestores = [
# ]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
# size = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
mount_program = "/usr/bin/fuse-overlayfs"

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
# override_kernel_check = "false"

# mountopt specifies comma separated list of extra mount options
# mountopt = "user_subvol_rm_allowed"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

# If specified, use OSTree to deduplicate files with the overlay backend
# ostree_repo = ""

# Set to skip a PRIVATE bind mount on the storage home directory.  Only supported by
# certain container storage drivers
# skip_mount_home = "false"

# [storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base.
# device.
# mkfsarg = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by smac89** [comment]
Try `buildah unshare ./buildah-script.sh`

**Comment by rhatdan** [comment]
@SwitchedToGitlab Sorry about your fustration with Rootless Buildah and to a smaller degree Podman. With rootless mode we are pushing the boundaries of what a non privileged user can do.  One of the requirements is to use the user namespace. A normal user is not allowed to mount file system, unless they are in a user namespace along with their own mount namespace.  Then they are allowed to mount different types of file systems.  When the exit the user namespace then they go back to the host mount namespace and the mount point no does not exists in this mount namespace.

So would could make 
buildah mount $ctr 

Enter the usernamespace and mount namespace and mount the file system fine.  BUT when the command ends the user is back in the host mount namespace and does not see the mount. so they can not copy to it directly,without reentering the user namespace/mount namespace.  This is why running the script as rootless does not give you what you would expect.

If you do `buildah unshare` first and then run the script, everything will happen inside of the user namespace and you would get what you want.

If you build the script and execute it like @smac89 suggests, then everything would work.

Sadly we can not get everything fixed within the Kernel to give you the experience you would like, mainly because of security concerns.  But we can get you pretty close.  Whether that is bad enough to force you back to always using root for your containers, which is what happens when you run Docker containers, I wish we could do better.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Want to make this into a Blog?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan sure!

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Did we ever blog this?

**Comment by TomSweeneyRedHat** [comment]
No blog post yet.

**Comment by rhatdan** [comment]
Ok I will throw one together.

**Comment by rhatdan** [comment]
Sadly I wrote the blog a month ago and then forgot to get it published.  Working on this now.

**Comment by rhatdan** [comment]
@edsantiago Could you check what is going on with zsh here? I think we missed the original problem.

**Comment by edsantiago** [comment]
I'm sorry, what am I supposed to look at? The only problem I see in the original post is that OP forgot the `./`, so of course it will fail. @smac89 helpfully pointed this out, and I see no response from OP. Am I missing a real problem somewhere?

**Comment by rhatdan** [comment]
Ok , if that is all there is, we can close this issue once we publish the blog.

**Comment by rhatdan** [comment]
Blog was published.

https://www.redhat.com/sysadmin/buildah-unshare-command
