### ISSUE TITLE
buildah add fails to resolve path

### ISSUE THREAD

**Issue by Obirvalger** [containers/buildah#2619]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
Either buildah add fails to resolve path or it writes a wrong error message. In an error message is said that the passed path could not be resolved relative to `/` even if the path is a rigth absolute path but without starting `/`.  Also, it seems unusual that buildah add resolvs relative path relative to `/` instead of the current working directory.

**Steps to reproduce the issue:**
1. Create a container: `buildah from alt`
2. Get the container id: `buildah containers`
3. Create a file: `touch /root/test.txt`
4. Try to add the file to the container: `buildah add a6ed3927b913 root/test.txt /tmp`

**Describe the results you received:**
Failing with the following error message:
`error adding content to container "alt-working-container": error computing path of "root/test.txt": Rel: can't make root/test.txt relative to /`

**Describe the results you expected:**
Resolving the file root/test.txt relative to `/` as `/root/txt` and adding the file to the container. 

**Output of `rpm -q buildah` or `apt list buildah`:**

```
# rpm -q buildah
buildah-1.16.0-alt1.x86_64
```

**Output of `buildah version`:**

```
Version:         1.16.0
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.2-0.20190904153231-83439463f784
image Version:   5.5.2
Git Commit:      295b825cdc0795f7e60349b901880e40e9850f5a
Built:           Wed Sep  9 19:21:15 2020
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
ALT Sisyphus Sisyphus (unstable) (sisyphus)
ALT Sisyphus Sisyphus (unstable) (sisyphus)
NAME="Sisyphus"
VERSION="20191026/unstable"
ID=altlinux
VERSION_ID=20191026
PRETTY_NAME="ALT Regular"
ANSI_COLOR="1;33"
CPE_NAME="cpe:/o:alt:sisyphus:20191026"
HOME_URL="http://en.altlinux.org"
BUG_REPORT_URL="https://bugs.altlinux.org/"
ALT Sisyphus Sisyphus (unstable) (sisyphus)
ALT Sisyphus Sisyphus (unstable) (sisyphus)
```

**Output of `uname -a`:**

```
Linux mainvm 5.4.40-std-def-alt2 #1 SMP Tue May 12 09:06:57 UTC 2020 x86_64 GNU/Linux
```

**Comment by amakeenk** [comment]
I am faced with similarly problem:
```
# pwd
/root

# touch ./testfile

# buildah add 00195cc76eb0 ./testfile /tmp
error adding content to container "alt-working-container": error checking on source ./testfile under "/": Rel: can't make ./testfile relative to /; copier: stat: "/testfile": no such file or directory

# buildah add 00195cc76eb0 /root/testfile /tmp
ae5d539e414db61f1333cc0e975a81084e344505af20f29d5a0676d86d2fab2d
```
Version of buildah:
```
# rpm -q buildah 
buildah-1.16.0-alt1.x86_64

# buildah version
Version:         1.16.0
Go Version:      go1.14.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.2-0.20190904153231-83439463f784
image Version:   5.5.2
Git Commit:      295b825cdc0795f7e60349b901880e40e9850f5a
Built:           Wed Sep  9 22:38:47 2020
OS/Arch:         linux/amd64
```

System:
```
NAME="ALT Workstation"
VERSION="9.1"
ID=altlinux
VERSION_ID=9.1
PRETTY_NAME="ALT Workstation 9.1 (Laertes)"
ANSI_COLOR="1;33"
CPE_NAME="cpe:/o:alt:workstation:9.1"
HOME_URL="https://basealt.ru/"
BUG_REPORT_URL="https://bugs.altlinux.org/"
```

**Comment by TomSweeneyRedHat** [comment]
The code that's hanging up here is in add.go at this [line](https://github.com/containers/buildah/blob/master/add.go#L358).  It's triggered because the `filepath.Rel(contextDir, glob)` call a few lines up is failing as it designed.  The value for contextDir is `/` and the glob is `root/test.txt`.  As the Rel() function just looks at those two strings that are given it, the glob is not relative to the contextDir in this instance. 

If you pass in `/root/test.txt` instead to the add command, then it works.  Similar comment for @amakeenk , but in a different section of add.go.

@nalind @rhatdan, I can change the code to work around this by joining the contextdir and the file and retrying rel again like this:  

```
# git diff
diff --git a/add.go b/add.go
index 1c1f116d..01a06899 100644
--- a/add.go
+++ b/add.go
@@ -355,7 +355,11 @@ func (b *Builder) Add(destination string, extract bool, options AddAndCopyOption
                for _, glob := range localSourceStat.Globbed {
                        rel, err := filepath.Rel(contextDir, glob)
                        if err != nil {
-                               return errors.Wrapf(err, "error computing path of %q", glob)
+                               localFile := filepath.Join(contextDir, glob)
+                               rel, err = filepath.Rel(contextDir, localFile)
+                               if err != nil {
+                                       return errors.Wrapf(err, "error computing path of %q", localFile)
+                               }
                        }
                        if strings.HasPrefix(rel, ".."+string(os.PathSeparator)) {
                                return errors.Errorf("possible escaping context directory error: %q is outside of %q", glob, contextDir)
```
But I'm not sure if that's the approach to take or not.  Thoughts?

**Comment by nalind** [comment]
I'm not sure that using `Join()` and `Rel()` in that way does what we want, since `Rel()` is specified to return something that could be passed to Join to get the originally-passed path.  It looks like I completely missed the "ContextDir is not set" case during the recent overhaul.  Self-assigning.

**Comment by Obirvalger** [comment]
This patch also fixes work with relative paths. But I don't know why deleting code was added and what this change could break.

diff --git a/add.go b/add.go
index 1c1f116d..c3914b67 100644
--- a/add.go
+++ b/add.go
@@ -151,9 +151,6 @@ func (b *Builder) Add(destination string, extract bool, options AddAndCopyOption
        }()
 
        contextDir := options.ContextDir
-       if contextDir == "" {
-               contextDir = string(os.PathSeparator)
-       }
 
        // Figure out what sorts of sources we have.
        var localSources, remoteSources []string
