### ISSUE TITLE
flake? Gating tests: failed to make veth pair

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2628]
Source: gating tests for [buildah-1.17.0-0.13.dev.git552cbd3.fc34](https://bodhi.fedoraproject.org/updates/FEDORA-2020-f7d94d6bcf) (but I've also seen it in other recent builds).  ([log](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/16053/pipeline/#step-177-log-1788)).
```
not ok 371 combination-namespaces
[...lots and lots  and lots of messages...]
# buildah from --signature-policy /usr/share/buildah/test/system/policy.json --ipc=container --net=private --pid=host --userns=host --uts=private alpine
# $ /usr/bin/buildah from --signature-policy /usr/share/buildah/test/system/policy.json --quiet --ipc=container --net=private --pid=host --userns=host --uts=private alpine
# alpine-working-container-77
# $ /usr/bin/buildah run alpine-working-container-77 pwd
# /
# $ /usr/bin/buildah run --tty=true alpine-working-container-77 pwd
# the container `buildah-buildah749027279` is not in 'stopped' state
# error running container: error configuring network list if0 for [/bin/pwd]: failed to make veth pair: operation not permitted
# error while running runtime: exit status 1
# [ rc=1 (** EXPECTED 0 **) ]
```

**Comment by edsantiago** [comment]
[Another one](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/16245/pipeline/#step-177-log-1525)

**Comment by edsantiago** [comment]
And [again in latest build](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/16267/pipeline/#step-177-log-1506). This is starting to look less and less like a flake.

**Comment by edsantiago** [comment]
Yeah, definitely [not a flake](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/16278/pipeline/#step-177-log-1478)

**Comment by rhatdan** [comment]
@edsantiago Is this still valid?  Or can we close?

**Comment by edsantiago** [comment]
@rhatdan I haven't even looked at Fedorah Buildah gating tests in months, because there are so many builds and so many failures.

Looking at the last few f33 builds -- [1.19.4-1.fc33](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/18169/testReport/(root)/tests/root_test/) and [1.19.0-1.fc33](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/9953/testReport/(root)/tests/root_test/) -- and a recent f34 -- [1.20.0-0.12.dev.git7f340f9.fc34](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/14861/testReport/(root)/tests/root_test/) -- I don't find a `veth` failure, so I'll just close and hope for the best.

**Comment by edsantiago** [comment]
Bummer. This just failed on a manual run (f33):
```
 ✗ combination-namespaces
   (from function `die' in file /usr/share/buildah/test/system/helpers.bash, line 196,
    from function `run_buildah' in file /usr/share/buildah/test/system/helpers.bash, line 183,
    in test file /usr/share/buildah/test/system/namespaces.bats, line 342)
     `run_buildah run --tty=true  $ctr pwd' failed
   ....
   lots and lots of stuff
   ...
   $ /usr/bin/buildah from --signature-policy /usr/share/buildah/test/system/policy.json --quiet --ipc=host --net=container --pid=container --userns=host --uts=host alpine
   alpine-working-container-18
   $ /usr/bin/buildah run alpine-working-container-18 pwd
   /
   $ /usr/bin/buildah run --tty=true alpine-working-container-18 pwd
   the container `buildah-buildah516995620` is not in 'stopped' state
   error running container: error configuring network list if0 for [/bin/pwd]: failed to make veth pair: operation not permitted
   error while running runtime: exit status 1
   [ rc=1 (** EXPECTED 0 **) ]
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #| FAIL: exit code is 1; expected 0
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I have no idea where `buildah-buildah516995620` comes from. It appears only in that one line above, nowhere else in the full log. 

buildah-1.19.6-1.fc33

I'm going to rerun the tests, and fully expect them to pass.

**Comment by edsantiago** [comment]
Nope. Failed again, at a different number:
```
$ /usr/bin/buildah from --signature-policy /usr/share/buildah/test/system/policy.json --quiet --ipc=host --net=container --pid=private --userns=container --uts=container alpine
alpine-working-container-28
$ /usr/bin/buildah run alpine-working-container-28 pwd
/
$ /usr/bin/buildah run --tty=true alpine-working-container-28 pwd
the container `buildah-buildah999213996` is not in 'stopped' state
error running container: error configuring network list if0 for [/bin/pwd]: failed to make veth pair: operation not permitted
error while running runtime: exit status 1
[ rc=1 (** EXPECTED 0 **) ]
```

**Comment by edsantiago** [comment]
And again
```
   $ /usr/bin/buildah from --signature-policy /usr/share/buildah/test/system/policy.json --quiet --ipc=host --net=private --pid=private --userns=container --uts=host alpine
   alpine-working-container-42
   $ /usr/bin/buildah run alpine-working-container-42 pwd
   /
   $ /usr/bin/buildah run --tty=true alpine-working-container-42 pwd
   the container `buildah-buildah157082686` is not in 'stopped' state
   error running container: error configuring network list if0 for [/bin/pwd]: failed to make veth pair: operation not permitted
   error while running runtime: exit status 1
```
...but I'm done for the evening.

Reproducer: get a 1minutetip f33 VM, install recent buildah-tests, then
```console
# export BUILDAH_BINARY=/usr/bin/buildah
# bats /usr/share/buildah/test/system/namespaces.bats
```

**Comment by edsantiago** [comment]
And again, blocking release #3103: [log](https://api.cirrus-ci.com/v1/task/5656299426807808/logs/integration_test.log)

**Comment by rhatdan** [comment]
@edsantiago Better now?

**Comment by rhatdan** [comment]
SGTM

**Comment by edsantiago** [comment]
OK. I'll reopen if/when I see it again.

**Comment by jayaddison** [comment]
See also:

- https://bugzilla.redhat.com/show_bug.cgi?id=1956309 (OpenShift CI failures; from inspection of at least one full build log containing the `failed to make veth pair` message, `buildah` was in use)
- https://github.com/cri-o/cri-o/issues/4878 (the same error message appearing during creation of pods in a CRI-O backed Kubernetes cluster)
