### ISSUE TITLE
buildah-1.16.1 installation error on CentOS 7.7

### ISSUE THREAD

**Issue by mshaikh786** [containers/buildah#2639]
**Description**
While trying to install buildah from devel_kubic_libcontainers_stable repository, I am getting the following errors. 

**Steps to reproduce the issue:**
1.
 `curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo `

2. `sudo yum install -y buildah`

**Describe the results you received:**
Investigating [https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/buildah-1.16.1-2.el7.x86_64.rpm.mirrorlist](repository), I could not find libseccomp and crun RPMs in there for CentoOS7. Any suggestions? 
buildah-1.15.2 I had installed before September 16th and it worked perfectly. Not sure how to access that repository/rpms 

**Describe the results you expected:**

**Output of `cat /etc/*release`:**
submitted as snapshot attached.

**Output of `uname -a`:**
submitted as snapshot attached

![Screen Shot 2020-09-21 at 10 41 15 AM](https://user-images.githubusercontent.com/3212475/93743890-8c730c80-fbf9-11ea-98e7-195a838f8822.png)
![Screen Shot 2020-09-21 at 10 57 26 AM](https://user-images.githubusercontent.com/3212475/93743897-8f6dfd00-fbf9-11ea-9852-d4135c044226.png)

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
should be fixed with 1.16.1-3 available on OBS now.

Closing. Please reopen if issue persists.
