### ISSUE TITLE
Minor: faster releases for Ubuntu?

### ISSUE THREAD

**Issue by dominic-p** [containers/buildah#2658]
This isn't that big of a deal, but I was wondering if anything could be done to shorten the time from when a release is made on GitHub to when the update hits the Ubuntu PPA on the Kubic build system.

I'm currently blocked on a project by #2619. That issue was fixed super fast and the fix was included in 1.16.2 which was released about a week ago, but the Ubuntu PPA still only has 1.16.1. I know that if I really need to I can/should just compile for source. But, I've had trouble getting reliable results that way in the past (entirely my issues there).

Anyway, it's not a huge deal, but if there's some kind of automation that could be used to get Kubic building/releasing faster, I would appreciate it. :)

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@dominic-p ack, let me check and fix it.

There's some automation in place for sending the package builds to OBS, but I've been seeing problems with the OBS client tool on gitlab, so it's been kinda flaky. I'll look into that as well when I get the chance.

**Comment by lsm5** [comment]
@dominic-p 1.16.2 available now. Sorry about the delay.

**Comment by dominic-p** [comment]
Thanks @lsm5 I really appreciate it.
