### ISSUE TITLE
Remove bors from CI

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#2666]
This one is pointed at @cevich.  @baude has given us the ability to do LGTM/lgtm style merges and that seems to be working.
Chris can you remove the bors pieces, please?  We thank you for the efforts there, but bors just didn't live up to its billing.

**Comment by cevich** [comment]
> We thank you for the efforts there, but bors just didn't live up to its billing.

No worries, I don't take it personally :smile_cat:
