### ISSUE TITLE
Could buildah support build multiple images concurrently, and the images are using 2 differenet dockerhub acccount. 

### ISSUE THREAD

**Issue by zhcf** [containers/buildah#2680]
I have 2 dockerhub accounts: user1, user2.  And there is one private docker image test under every user account.
I want to build one new docker image image1 which will use the private docker image test under user1
I want to build another docker image image2 which will use the private docker image test under user2

I tried, it really can build image1 and image2 concurrently.
buildah bud --creds user1:user1Passw0rd --tag image1:latest  --no-cache -f Dockerfile1
buildah bud --creds user2:user2Passw0rd --tag image2:latest  --no-cache -f Dockerfile2

But, I am just wondering whether buildah have any risk to use like this way, such as whether there is the lock to make sure download the same base image from dockerhub once? whether  user1 creds and user2 cred have impact with each other.

**Comment by rhatdan** [comment]
Not sure what you are worried about.  If both Dockerfiles pull the same image then both will pull, I believe. There was work to fix this, but has not made it into the tools yet. If they are pulling different images, then there will be no problem.

**Comment by zhcf** [comment]
@rhatdan when we pull the same docker image in 2 different process simutaneously. we will find the 2 processes have the same download pertentage for every layer, so I guess, docker has the mechanism to ensure one unique layer can just be downloaded once by the docker daemon, the docker client just get the layer downloading status.

**Comment by rhatdan** [comment]
Well we end up in the same state, each layer is shared between both buildah, the one that gets downloaded first.
@vrothberg PTAL

**Comment by zhcf** [comment]
ok, got it, thank you, will close it.
