### ISSUE TITLE
buildah copy. error checking on source. no such file or directory

### ISSUE THREAD

**Issue by jandroav** [containers/buildah#2685]
**Description**
After upgrading Buildah from v1.15.2, when trying to copy .jar files to the destination container directory it throws the error:

> error adding content to container "b-builder-b-base-ubuntu-adoptopenjdk11-working-container-8": error checking on source target/akira-rest-2.2.1-SNAPSHOT.jar under "/": Rel: can't make target/akira-rest-2.2.1-SNAPSHOT.jar relative to /; copier: stat: "/target/akira-rest-2.2.1-SNAPSHOT.jar": no such file or directory

**Steps to reproduce the issue:**
1. Execute 
`buildah copy b-builder-b-base-ubuntu-adoptopenjdk11-working-container-8 target/akira-rest-2.2.1-SNAPSHOT.jar /deployments`

**Describe the results you received:**
error adding content to container "b-builder-b-base-ubuntu-adoptopenjdk11-working-container-8": error checking on source target/akira-rest-2.2.1-SNAPSHOT.jar under "/": Rel: can't make target/akira-rest-2.2.1-SNAPSHOT.jar relative to /; copier: stat: "/target/akira-rest-2.2.1-SNAPSHOT.jar": no such file or directory

**Output of `buildah version`:**

```
Version:         1.16.1
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.2
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux kpt-agent-maven-small-11-3whzm 4.18.0-193.14.3.el8_2.x86_64 #1 SMP Mon Jul 20 15:02:29 UTC 2020 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
driver = 'vfs'
graphroot = '/var/lib/containers/storage'
runroot = '/var/run/containers/storage'
[storage.options]
override_kernel_check = 'true'
size = ''
```

**Describe the results you expected:**

```
buildah copy b-builder-b-base-ubuntu-adoptopenjdk11-working-container-8 target/akira-rest-2.2.1-SNAPSHOT.jar /deployments
c20db3989096e6433e43fed387fdfa80ab4d76b3553c258c26bf726bafdd2d67
```

**Comment by jandroav** [comment]
fixed using absolute path

**Comment by Otmane-Guo** [comment]
Hi @jandroav I faced the same issue while building my Dockerfile, can you please tell me how you fixed the problem ! 
this is my error message 

STEP 7: COPY ./target/dat-app-backend-1.0-SNAPSHOT.jar app.jar
error building at STEP "COPY ./target/dat-app-backend-1.0-SNAPSHOT.jar app.jar": error adding sources [/workspace/source/target/dat-app-backend-1.0-SNAPSHOT.jar]: error checking on source /workspace/source/target/dat-app-backend-1.0-SNAPSHOT.jar under "/workspace/source": copier: stat: "/target/dat-app-backend-1.0-SNAPSHOT.jar": no such file or directory

**Comment by jandroav** [comment]
You will need to use the absolute path, the whole path

**Comment by Otmane-Guo** [comment]
Thank you for your reply, you mean update the path for my first argument './target/dat-app-backend-1.0-SNAPSHOT.jar' to 'workspace/source/target/dat-app-backend-1.0-SNAPSHOT.jar' ?
