### ISSUE TITLE
Running 'buildah images' is much slower than running 'podman images'

### ISSUE THREAD

**Issue by larsks** [containers/buildah#2691]
**Description**

Running `buildah images` is around 10 times slower than running `podman image`.

For example, `podman`

```
$ time sh -c 'for i in {1..10}; do  podman images > /dev/null; done'

real    0m2.785s
user    0m3.296s
sys     0m0.649s
```

Vs `buildah`:

```
$ time sh -c 'for i in {1..10}; do  buildah images > /dev/null; done'

real    0m38.670s
user    0m33.674s
sys     0m16.143s
```

**Steps to reproduce the issue:**
1. Run `time podman images`
2. Run `time buildah images`
3. Compare the results

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.16.4-1.fc31.x86_64
```

**Output of `buildah version`:**

```
Version:         1.16.4
Go Version:      go1.13.15
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.2
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman-2.1.1-3.fc31.x86_64
```

**Output of `cat /etc/*release`:**

```
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
Linux madhatter 5.8.13-100.fc31.x86_64 #1 SMP Thu Oct 1 21:46:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

I'm running rootless, so this is `~/.config/containers/storage.conf`.

```
[storage]
  driver = "overlay"
  runroot = "/run/user/1000/containers"
  graphroot = "/home/lars/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    ignore_chown_errors = ""
    remap-user = ""
    remap-group = ""
    skip_mount_home = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.aufs]
      mountopt = ""
    [storage.options.btrfs]
      min_space = ""
      size = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      size = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""
    [storage.options.overlay]
      ignore_chown_errors = ""
      mountopt = ""
      mount_program = ""
      size = ""
      skip_mount_home = ""
    [storage.options.vfs]
      ignore_chown_errors = ""
    [storage.options.zfs]
      mountopt = ""
      fsname = ""
      size = ""
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @larsks!

We recently did some major improvements to Podman's image code. Podman and Buildah don't share that code, unfortunately. However, we plan to create a high-level image library that Podman, Buildah and also CRI-O can share.

@rhatdan, @baude, can we raise priority for that? It's a building block for the CRI-O/libpod work but went under the radar.

**Comment by rhatdan** [comment]
Sure, SGTM.

**Comment by rhatdan** [comment]
@vrothberg Reminder that this is still an issue.  I think we need to get moving on this, as soon as we get out of Bug fix mode.

**Comment by rhatdan** [comment]
Since the hanlding of podman images was moved to libimage, buildah now shares the code.
