### ISSUE TITLE
buildah bud is gobbling stdin

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2705]
buildah bud is gobbling stdin that does not belong to it. This makes it impossible to pipe script commands to a shell.

```console
$ printf "echo hi\r\nbuildah bud -t foo .\necho bye\n" | bash
hi
STEP 1: ...
...
<sha>
```
Note that the 'echo bye' is gobbled up by buildah. If you redirect stdin on the buildah command, it works as expected:
```console
$ printf "echo hi\r\nbuildah bud -t foo . </dev/null\necho bye\n" | bash
hi
...
bye
```
See also: https://github.com/containers/podman/issues/8066

**Comment by rhatdan** [comment]
I am not seeing this happen on the main branch of Podman, BTW.  But opened a PR anyways,

**Comment by rhatdan** [comment]
This is fixed in master branch.
