### ISSUE TITLE
Installation fails on Centos 8 with network errors about invalid Content-Length

### ISSUE THREAD

**Issue by weskerfoot** [containers/buildah#2712]
**Description**

**Steps to reproduce the issue:**
1. Run `docker build -f buildah buildah.dockerfile` with the attached example dockerfile
2. Get the error message `[MIRROR] containers-common-1.2.0-2.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 79780 but expected size is: 79772` which causes the installation to fail.

**Describe the results you received:**
Installation failed with network errors. Potentially related to https://github.com/containers/podman/issues/7440

**Describe the results you expected:**
Installation succeeded and buildah got installed.

**Output of `cat /etc/*release`:**

```
CentOS Linux release 8.2.2004 (Core) 
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

CentOS Linux release 8.2.2004 (Core) 
CentOS Linux release 8.2.2004 (Core) 
```

**Output of `uname -a`:**

```
Linux d192c12e396a 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 x86_64 x86_64 GNU/Linux
```

Example dockerfile:

```
FROM centos:centos8

RUN dnf install -y wget

# Install buildah, as instructed by https://github.com/containers/buildah/blob/master/install.md#centos
RUN dnf -y module disable container-tools && \
    dnf -y install 'dnf-command(copr)' && \
    dnf -y copr enable rhcontainerbot/container-selinux && \
    cd /etc/yum.repos.d && \
    wget https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo

RUN dnf -y install buildah
```

**Comment by weskerfoot** [comment]
Looks like it's working now, any idea what was the issue?

**Comment by TomSweeneyRedHat** [comment]
@weskerfoot , never question success!  IDK for sure, but my guess would be some kind of network hiccup that cleared itself up between tests.
