### ISSUE TITLE
chown error when the gid does not match user's primary group

### ISSUE THREAD

**Issue by dkliban** [containers/buildah#2716]
**Description**
When running `buildah bud` inside a Python process started using systemd with username `vagrant` and group `pulp` the following `chown` error is emitted:

```
error creating build container: error creating container: error creating read-write layer with ID "c4b29610e53808c294e23e6bb7d6fd682b8745b27d2cd745ad94e9cafe09fc1c": there might not be enough IDs available in the namespace (requested 0:65534 for /home/vagrant/.local/share/containers/storage/overlay/c4b29610e53808c294e23e6bb7d6fd682b8745b27d2cd745ad94e9cafe09fc1c): chown /home/vagrant/.local/share/containers/storage/overlay/c4b29610e53808c294e23e6bb7d6fd682b8745b27d2cd745ad94e9cafe09fc1c: invalid argument\nlevel=error msg="exit status 125"
```

Changing the ownership of `/home/vagrant/.local/share/containers/` to `vagrant:pulp` fixes the problem. 

Either the chown should use the user's primary gid or a better error message should be emitted. 

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.15.1-1.fc32.x86_64
```

**Output of `buildah version`:**

```
Version:         1.15.1
Go Version:      go1.14.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.1
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
Fedora release 32 (Thirty Two)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
What was the ownership of /home/vagrant/.local/share/containers/  before you did the chown?

**Comment by dkliban** [comment]
ownership of /home/vagrant/.local/share/containers/ was `vagrant:vagrant`.

**Comment by rhatdan** [comment]
And if your user does
$ id
What is the default group?

**Comment by dkliban** [comment]
```
[vagrant@pulp3-source-fedora32 site-packages]$ id
uid=1000(vagrant) gid=1000(vagrant) groups=1000(vagrant),190(systemd-journal),991(pulp) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

**Comment by rhatdan** [comment]
Ok, but pulp(991) should not be mapped into your containers user namespace.
The only uids imappen into it should be 1000.

$ buildah unshare cat /proc/self/gid_map

**Comment by dkliban** [comment]
```
[vagrant@pulp3-source-fedora32 ~]$ buildah unshare cat /proc/self/gid_map
         0       1000          1
         1     100000      65536
```

**Comment by rhatdan** [comment]
Which means if you have a file that is owned by 190(systemd-journal),991(pulp) and group accessible to the user, it still will not be usable inside of the container.

crun has some ability to handle these GIDs, but I am not sure we have this in buildah yet.

**Comment by rhatdan** [comment]
@nalind @giuseppe should we have buildah "run" attributes to be set for the OCI Runtimes that do not get stored into the image?

**Comment by nalind** [comment]
Content owned by unmapped UIDs and GIDs is still readable if it's world-readable.  The kernel reports items owned by IDs that aren't mapped as having owner IDs with the values set in the `fs.overflowuid` and `fs.overflowgid` settings.  That's confusing when those values are ones that for which we've set up mappings, but the kernel knows the difference.

I thought the question was whether we should be defaulting to mapping the user's primary group as listed in /etc/passwd to GID 0 when setting up the namespace, or whether we should be trying to use the primary group that we're started with?

**Comment by rhatdan** [comment]
I think is explained, so I will close.  Reopen if more information is required.
