### ISSUE TITLE
ERRO[...] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -c] will be ignored. Must use `docker` format

### ISSUE THREAD

**Issue by vorburger** [containers/buildah#2741]
**Description**

Running `podman build .` on https://github.com/openMF/community-app I'm seeing a lot of:

    ERRO[...] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -c] will be ignored. Must use `docker` format

**Output of `rpm -q buildah` or `apt list buildah`:**

N/A

**Output of `buildah version`:**

N/A

**Output of `podman version` if reporting a `podman build` issue:**

```
$ podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 21:31:11 2020
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
... Fedora 32 ...
```

**Output of `uname -a`:**

```
Linux ... 5.8.15-201.fc32.x86_64 #1 SMP Thu Oct 15 15:56:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nalind** [comment]
By default, we produce images using the OCI format, and the part of the Docker image format that the SHELL instruction affects isn't in the OCI format.  Try building with `--format docker` to produce an image using the Docker format.
