### ISSUE TITLE
buildah panics on incorrect label syntax when filtering images

### ISSUE THREAD

**Issue by cmacq2** [containers/buildah#2763]
**Description**

When using `--filter` with the `label` keyword, an incorrect syntax causes `buildah` to panic. 

**Steps to reproduce the issue:**
1. Execute `buildah images --filter label foo=bar`
2. Observe output

**Describe the results you received:**

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.parseFilter(0x11e6aa0, 0xc000036158, 0x120c780, 0xc0005a2600, 0xc000538300, 0x3, 0x3, 0x7ffe2bbad23c, 0x5, 0x0, ...)
        github.com/containers/buildah/cmd/buildah/images.go:194 +0x9da
main.imagesCmd(0xc00025a840, 0xc0002ac300, 0x1, 0x3, 0xc0001c1050, 0x0, 0x0)
        github.com/containers/buildah/cmd/buildah/images.go:172 +0x339
main.init.7.func1(0xc00025a840, 0xc0002ac300, 0x1, 0x3, 0x0, 0x0)
        github.com/containers/buildah/cmd/buildah/images.go:97 +0x52
github.com/spf13/cobra.(*Command).execute(0xc00025a840, 0xc0002ac2a0, 0x3, 0x3, 0xc00025a840, 0xc0002ac2a0)
        github.com/spf13/cobra/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x188e160, 0x6, 0xc000036127, 0x8)
        github.com/spf13/cobra/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:883
main.main()
        github.com/containers/buildah/cmd/buildah/main.go:182 +0xe1
ERRO exit status 2
```

**Describe the results you expected:**

I'd expect one of two outcomes:

 1. `buildah` detects that an argument of `label` by itself is incorrect syntax, prints an appropriate error message and exits with some non-zero status code instead of trying to walk over the component parts of the `label` predicate. 
 2. `buildah` supports a distinct two-arg syntax for filtering by label, therefore it would accept a two-arg syntax like  `label foo=bar` and interpret such predicates correctly

In either case I do not expect `buildah` to choke on invalid input like this and spill its guts in a panic on stderr :)

Additionally I suspect the `ERRO` bit in the output (which is highlighted in red in the terminal) is a truncated `ERROR`. In that case, I also do not expect the `ERROR` label to be truncated either...

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/unstable,testing,now 1.15.2-1 amd64 [installed]
```

**Output of `buildah version`:**

```
buildah version 1.15.2 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux Psyche 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by TomSweeneyRedHat** [comment]
@cmacq2 thanks for the issue report.

**Comment by rhatdan** [comment]
@cmacq2 interested in taking a stab at fixing this?
