### ISSUE TITLE
Race condition in tests

### ISSUE THREAD

**Issue by vrothberg** [containers/buildah#2779]
There is a race condition:

The short-names PR (https://github.com/containers/buildah/pull/2695) changed the semantics from pull-if-newer to not look at the time stamps but to compare digests. If the digests differ, the remote one is considered to "newer" than the local one we pull the remote one. Previously, we were comparing the time stamps ... if they were different, the image is pulled. But as shown below (and discussed this week), that's not accurate.

The corrected pull-if-newer semantics can lead to failing tests as shown below:

```
[+0214s] # #| FAIL: buildah images -a
[+0214s] # #| Expected 8 lines of output, got 9
[+0214s] # #| Output was:
[+0214s] # #| >REPOSITORY                 TAG      IMAGE ID       CREATED                  SIZE
...
[+0214s] # #| >localhost/alpine           latest   9785808968ba   3 weeks ago              5.84 MB
[+0214s] # #| >docker.io/library/alpine   latest   d6e46aa2470d   3 weeks ago              5.85 MB
```

`localhost/alpine` comes from the built-in `_prefetch` where we're loading a prefetched image. If the `alpine` image is updated _after_ (i.e., while tests run), a `buildah bud` would download the new image from the repository. In that case, we have two alpines and don't meet the expected image counter.

I suggest to go through the tests and look for the pattern below. In case of `buildah bud`, we could add `--pull-never` so we'll always use the local image.
```
run_buildah images -a 
expect_line_count XXX 
```

@edsantiago @TomSweeneyRedHat @nalind @rhatdan WDYT?

**Comment by vrothberg** [comment]
Could it be that the images are prefetched on the VM images? I again hit the issue but cannot reproduce locally.

**Comment by vrothberg** [comment]
I reverted that part in the short-names PR. Fixing the issue here turned out to be more work and I don't want to mix that with short names so we're not blocked.

**Comment by rhatdan** [comment]
@vrothberg So this is still an issue where we should change all tests to --pull-never?

**Comment by vrothberg** [comment]
> @vrothberg So this is still an issue where we should change all tests to --pull-never?

Yes, that would be a solution or `pull if missing`.
