### ISSUE TITLE
podman-build network fails DNS lookups; podman-run works

### ISSUE THREAD

**Issue by mathstuf** [containers/buildah#2780]
**Description**

When using a VPN (OpenVPN), DNS lookups fail inside of `podman build`, but work inside of `podman run`. Routing works (`dig` outside of the container and use that IP inside), so I think some UDP tables might not be hooked up properly?

**Steps to reproduce the issue:**
1. Set up a VPN in a network namespace (so it is the only available connection)
2. `podman build` fails DNS lookups
3. `podman run -it $previous_image_cache` works just fine

**Describe the results you received:**

DNS lookup failure (timeout)

**Describe the results you expected:**

DNS lookup success.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.16.2-1.fc33.x86_64
```

**Output of `buildah version`:**

```
Version:         1.16.2
Go Version:      go1.15
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.2
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 12:21:20 2020
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 33 (Thirty Three)
NAME=Fedora
VERSION="33 (Thirty Three)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Thirty Three)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
Fedora release 33 (Thirty Three)
Fedora release 33 (Thirty Three)
```

**Output of `uname -a`:**

```
Linux erythro 5.8.16-300.fc33.x86_64 #1 SMP Mon Oct 19 13:18:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
<Fedora default>
```

**Comment by rhatdan** [comment]
@nalind Are we using the same CNI network in podman build as we do with podman run?  Could this be a disconnect there?

**Comment by nalind** [comment]
With `--network private`, we should.  Contrary to the "buildah run" man page (which refers to podman's host network, confusing), we appear to default to "host" mode for "buildah run", and I expect that default carries through to RUN instructions in builds, too.

**Comment by rhatdan** [comment]
https://github.com/containers/buildah/pull/2813

**Comment by rhatdan** [comment]
@nalind Should we change to --network=private for buildah run and buildah bud then?

**Comment by nalind** [comment]
If it's reliable enough, sure - I want to avoid debugging networking during build if that's possible.  To that end, I'm concerned that "host" networking doesn't work, since we're intentionally not doing much there.

**Comment by rhatdan** [comment]
@mathstuf If you do podman build --net=private does it work correctly?

**Comment by mathstuf** [comment]
Nope.

```
2021-02-10T21:44:55.000165303Z: the container `buildah-buildah554465755` is not in 'stopped' state
error running container: error configuring network list if0 for [/bin/sh -c bash blah blah blah]: failed to create bridge "cni-podman0": could not add "cni-podman0": operation not permitted
Error: error building at STEP "RUN blah blah blah: error while running runtime: exit status 1
```

Still just stalls without the flag.

```
buildah-1.18.0-2.fc33.x86_64
podman-2.2.1-1.fc33.x86_64
```

**Comment by rhatdan** [comment]
Ok so this would only work with rootfull at this point.  Buildah does not have the integration with slirp4netns currently.

**Comment by mathstuf** [comment]
Any status update on Buildah + slirp4netns integration?

**Comment by rhatdan** [comment]
No movement on this.

**Comment by rhatdan** [comment]
@nalind @mheon Can you think of an easy way to get this to work?

**Comment by 884756834** [comment]
My podman is experiencing similar symptoms; `podman build` has a DNS error (on a `RUN yum install` command) but if I build without that and then run the container and execute the command manually it works.

I am not using OpenVPN, but this is a corporate environment so I'm not sure if some combination of networking/firewall is causing this. Host is a RHEL8 server.

**Comment by rhatdan** [comment]
Could you add a 

RUN cat /etc/resolv.conf

From a Containerfile/Dockerfile and see if the settings are messed up when compared to a podman run IMAGE cat /etc/resolv.conf?

**Comment by 884756834** [comment]
@rhatdan Just tried that. With that RUN command I can see something like this:

```
search example.com abc.example.com xyz.example.com
```

Inside the running container we have:
```
search example.com abc.example.com xyz.example.com
nameserver 10.0.2.3
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
```

On the host machine we have:
```
search example.com abc.example.com xyz.example.com
nameserver <internal IP>
nameserver <internal IP>
nameserver <internal IP>
nameserver <internal IP>
```

In all 3 snippets example.com is actually a corporate domain, and in the 3rd snippet the internal IPs are valid internal DNS servers.

I don't know enough to say that the first snippet is messed up or not.

**Comment by mheon** [comment]
By "the running container" - is that a Podman container, or inside a build container via a `RUN` instruction?

**Comment by 884756834** [comment]
> By "the running container" - is that a Podman container, or inside a build container via a `RUN` instruction?

That refers to the former. I updated my comment to include the commands to make it clearer.

**Comment by rhatdan** [comment]
@Luap99 @mheon Any update on this?

**Comment by Luap99** [comment]
I take a look.
