### ISSUE TITLE
[--layers] Parallel buildah bud builds do not seemingly benefit from the cache of images

### ISSUE THREAD

**Issue by bogdando** [containers/buildah#2781]
/kind bug

**Description**

**Steps to reproduce the issue:**
1. Run concurrent ``buildah bud --layers --rm=false`` builds for multiple containers that share some common base layer
2. Compare the time it takes to the same operation executed without ``--layers --rm=false``
3. (probably expected behavior) If specifying only ``--layers`` without ``--rm=false``, it likely fails some builds with errors like ``error checking if cached image exists from a previous build: error getting history of "<id>": error creating new image from reference to image "<id>": error locating item named "manifest" for image with ID``

**Describe the results you received:**
The time it takes to build ~40 quite fat and multi-layered containers is roughly 30 minutes for the above scenarios 1 and 2.
I have the same results with buildah built from trunk master (v1.11.6-830-g31b0c5db).

See more of the similar results [0]
```
2020-11-12 20:05:44.891116 | TASK [build-containers : Run image build as ansible user > /home/zuul/workspace/build.log]
2020-11-12 20:36:24.390268 | primary | ok: Runtime: 0:30:38.402444
```
vs --layers enabled [1]
```
2020-11-10 01:33:15.162933 | TASK [build-containers : Run image build as ansible user > /home/zuul/workspace/build.log]
2020-11-10 01:58:09.258823 | primary | ok: Runtime: 0:24:53.062323
```

**Describe the results you expected:**
With --layers it should complete faster because of the image cache benefits.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
N/A (built locally from trunk)
```

**Output of `buildah version`:**

```
buildah version 1.18.0-dev (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux thinkpad 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

[0] https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_e62/762561/1/check/tripleo-build-containers-ubi-8/e621705/job-output.txt

[1] https://storage.bhs.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_b36/761996/1/check/tripleo-build-containers-ubi-8/b364a30/job-output.txt

**Comment by TomSweeneyRedHat** [comment]
@vrothberg @nalind any thoughts?

**Comment by rhatdan** [comment]
@bogdando I see in your Logging PR, that  you are attempting to diagnose this.  What have you found?

**Comment by rhatdan** [comment]
@bogdando Any update on this?

**Comment by rhatdan** [comment]
Since no response, I am going to close, reopen if you get more information.

**Comment by kaushalyap** [comment]
@rhatdan Is parallel build supported in Buildah just like [Buildkit](https://github.com/moby/buildkit)?

**Comment by nalind** [comment]
You can run multiple commands in parallel, or build with `--jobs` to build stages in parallel when they don't depend on each other.
