### ISSUE TITLE
Buildah bud --layers does not provide shorter time for parallel builds of consequent containers that share some common base

### ISSUE THREAD

**Issue by bogdando** [containers/buildah#2782]
/kind bug

**Description**

The ``--layers`` option is only useful when building *exactly the same* containers but using different target directories.
Consequent container builds that share some common base could not benefit from that layers cache. Which is quite suboptimal.

**Steps to reproduce the issue:**
1. Run concurrent ``buildah bud --layers --rm=false`` builds for multiple containers that share some common base layer
2. Compare the time it takes to the same operation executed without ``--layers --rm=false``
3. (probably expected behavior) If specifying only ``--layers`` without ``--rm=false``, it likely fails some builds with errors like ``error checking if cached image exists from a previous build: error getting history of "<id>": error creating new image from reference to image "<id>": error locating item named "manifest" for image with ID``

**Describe the results you received:**
The time it takes to build ~40 quite fat and multi-layered containers is roughly 30 minutes for the above scenarios 1 and 2.
I have the same results with buildah built from trunk master (v1.11.6-830-g31b0c5db).

See more of the similar results with using ``--layers --rm=false`` [0]
```
2020-11-12 20:05:44.891116 | TASK [build-containers : Run image build as ansible user > /home/zuul/workspace/build.log]
2020-11-12 20:36:24.390268 | primary | ok: Runtime: 0:30:38.402444
```
without ``--layers`` [1]
```
2020-11-10 01:33:15.162933 | TASK [build-containers : Run image build as ansible user > /home/zuul/workspace/build.log]
2020-11-10 01:58:09.258823 | primary | ok: Runtime: 0:24:53.062323
```

**Describe the results you expected:**
With --layers it should complete faster because of the image cache benefits.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
N/A (built locally from trunk)
```

**Output of `buildah version`:**

```
buildah version 1.18.0-dev (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux thinkpad 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

[0] https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_e62/762561/1/check/tripleo-build-containers-ubi-8/e621705/job-output.txt

[1] https://storage.bhs.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_b36/761996/1/check/tripleo-build-containers-ubi-8/b364a30/job-output.txt

**Comment by bogdando** [comment]
Note that with that (not well working yet) extra debug info, I can see that there is 0 "found image .* in cache" events produced.
Which maybe a bug in my extra logger, or in the caching logic as well.

**Comment by rhatdan** [comment]
Are you seeing the layers being removed when --rm=false is set?

If you do 
```
# buildah bud --layers --rm=false /tmp/test1
# buildah bud --layers --rm=false /tmp/test2
```
Where test1 and test2 share the same first couple of command 
layers 
Does the second cont show that it is using cache?

**Comment by bogdando** [comment]
@rhatdan I'm not figured out yet how layers got removed and how things get logged for that. But using that linked above debug patch https://github.com/containers/buildah/pull/2785, I noticed another thing: the image cache info struct "changes" it keys on fly. Is that expected to happen? E.g.: https://pastebin.com/zfjLEewA

**Comment by bogdando** [comment]
Update: when I see some "Using cache foo" in logs and then search for it, it finds such layers:

```
sudo find /var -name '*foo*'
/var/lib/containers/storage/overlay-images/foo
```
So that part of the pusszle should be fine. Would be nice to modify my patch to have the removals of layers logged as well

**Comment by bogdando** [comment]
So, If I do

# buildah bud --layers --rm=false /tmp/test1
# buildah bud --layers --rm=false /tmp/test2

Where test1 and test2 share the same first couple of command
layers
The second cont shows that it is using cache.

But when I build another image based on that test1, just adding extra layers on top, there is no any use of cache.
This bug is exactly about the latter.

**Comment by rhatdan** [comment]
I am not seeing it, here is my simple test

```
# cat /tmp/test1/Containerfile 
from alpine
RUN echo hello
RUN echo goodbye
RUN echo test1

# cat /tmp/test2/Containerfile 
from alpine
RUN echo hello
RUN echo goodbye
RUN echo test2
```

```
# buildah bud --layers /tmp/test1
STEP 1: FROM alpine
STEP 2: RUN echo hello
hello
--> bc83efda254
STEP 3: RUN echo goodbye
goodbye
--> 62a07f2418f
STEP 4: RUN echo test1
test1
STEP 5: COMMIT
--> 2db664a4bae
2db664a4bae419db1dc80a432f1f48bd5808845a6aac55b559bb2222ee93fe9b

# buildah bud --layers /tmp/test2
STEP 1: FROM alpine
STEP 2: RUN echo hello
--> Using cache bc83efda2548b646db0ff7c607150e53ee785c96b2285a274618a5ef1316aaa7
--> bc83efda254
STEP 3: RUN echo goodbye
--> Using cache 62a07f2418f8b560e74ca9322a67dbd1e9b6e319b7ddda6361792f5ab36fdddf
--> 62a07f2418f
STEP 4: RUN echo test2
test2
STEP 5: COMMIT
--> 144f7c78655
144f7c78655563fe6f1ca1bbc4bc1082d384fbc926aa5cf58409e7b885b52737

# buildah bud --layers /tmp/test1
STEP 1: FROM alpine
STEP 2: RUN echo hello
--> Using cache bc83efda2548b646db0ff7c607150e53ee785c96b2285a274618a5ef1316aaa7
--> bc83efda254
STEP 3: RUN echo goodbye
--> Using cache 62a07f2418f8b560e74ca9322a67dbd1e9b6e319b7ddda6361792f5ab36fdddf
--> 62a07f2418f
STEP 4: RUN echo test1
--> Using cache 2db664a4bae419db1dc80a432f1f48bd5808845a6aac55b559bb2222ee93fe9b
--> 2db664a4bae
2db664a4bae419db1dc80a432f1f48bd5808845a6aac55b559bb2222ee93fe9b
```

**Comment by bogdando** [comment]
Ok thank you, I can confirm that also works the same way for me.
The confusion was in how --layers could help with builds test2...N containers that depend on test1. It seems it cannot. So I'm closing this with a conclusion that --layers works as designed. And is only useful when building *exactly the same containers* but using different targets.

**Comment by bogdando** [comment]
My testing in tripleo for openstack builds was using older version of buildah where was no use of cache, hence this issue.
While retesting it with latest build, I can see there is use of cache in the same scenario. So this bug is invalid, so is my comment as well that layers cache is only efficient when building *exactly the same* images as different targets. Testing shows it is efficient even when building images that use other layers, like COPY foo, on top of the common base.

**Comment by rhatdan** [comment]
Great.
