### ISSUE TITLE
Mentioned in Podman build Documentation CPP(1) is not documented and not found in my Ubuntu installation 

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/buildah#2787]
**Description**
CPP(1) utility for processing #INCLUDE directive in the Docker.in or Container.in doesn't exist in my Podman installation on Ubuntu 20.04 WSL distro and has no documentation. 

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**

which cpp
  nothing
**Describe the results you expected:**
cpp exists and documented
Actually, I didn't find anything about this feature except git commit comment "Now include is possible"
**Output of `rpm -q buildah` or `apt list buildah`:**

```
apt list buildah
Listing... Done
buildah/now 1.16.4~1 amd64 [installed,local]
```

**Output of `buildah version`:**

```
buildah --version
buildah version 1.16.4 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
pavel@MSI:/mnt/c/Users/Pavel$ podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/amd64

**Comment by TomSweeneyRedHat** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
We should add this as a "suggests" for buildah and podman in the spec files.

**Comment by vrothberg** [comment]
Thanks for reaching out @praiskup! You need to install `cpp` for it to work. That's usually part of any base system but apparently not in the WSL image.

@lsm5 PTAL

**Comment by lsm5** [comment]
@PavelSosin-320 buildah 1.18.0~1 now has a `Suggests: cpp` . Let me know if that helps.

**Comment by PavelSosin-320** [comment]
Not 100% yet. 
After upgrade of my CentOS8.2 distro I got
buildah --version
buildah version 1.18.0 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
and cpp --version
cpp (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
But after upgrade  of Ubuntu-20.04 distro I got only 
buildah version
Version:         1.16.4
CNI Spec:        0.4.0
libcni Version:
image Version:   5.5.2
OS/Arch:         linux/amd64
i.e. very old
When I try to call CPP Ubuntu suggests installing C++ compiler.
Do you mean that everybody needs to have full C++ installed to use Podman?
The discussion that Dockerfile like any content-type must have a formal grammar started 5 years ago and it is published:
[Dockerfile grammar](https://pub.dev/documentation/highlight/latest/languages_dockerfile/dockerfile.html).
Indeed, I don't see "Include" directive their.
But I found [ANTLR4 Golang target](https://github.com/antlr/antlr4/blob/master/doc/go-target.md) so, I suppose C++ is redundant.

**Comment by rhatdan** [comment]
cpp is the C Pre-Procesor, no need for c++

**Comment by lsm5** [comment]
> @lsm5 Not 100% yet.
> But after upgrade of Ubuntu-20.04 distro I got only
> buildah version
> Version: 1.16.4
> CNI Spec: 0.4.0
> libcni Version:
> image Version: 5.5.2
> OS/Arch: linux/amd64


@PavelSosin-320 where are you getting this buildah from ? Is it from kubic/obs, or ubuntu's default repos?
