### ISSUE TITLE
1.18 release not found in quay.io

### ISSUE THREAD

**Issue by tuananh** [containers/buildah#2798]
It's not a bug report. I just wonder can we keep `quay.io/buildah/upstream` or maybe testing in sync with latest release from github?

**Comment by TomSweeneyRedHat** [comment]
@tuananh This is a two-part problem.  First, we need to wait for the release to get through Fedora testing and be marked as [stable](https://bodhi.fedoraproject.org/updates/FEDORA-2020-b18837a581) before we can build an image..  Secondly, we recently had an issue creating images that used the v2 schema.  That issue has been solved and I need to get a recent release or two worths of images posted.

If by chance you want to try v1.18.0 before it becomes stable, the latest version in test should bein in the testing repo:

```
]# podman run quay.io/buildah/testing:latest  buildah version
Trying to pull quay.io/buildah/testing:latest...
Getting image source signatures
Copying blob a3ed95caeb02 done  
Copying blob f944d8bab87f done  
Copying blob 8b10d34517b1 done  
Copying blob 328230210bf7 done  
Copying blob b3227b79d9b6 done  
Copying blob 1129ab56fd9b done  
Writing manifest to image destination
Storing signatures
Version:         1.18.0
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.8.0
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64

```

IDK if that helps or not.

**Comment by tuananh** [comment]
Thanks Tom. 1.15 works for me for now.

**Comment by TomSweeneyRedHat** [comment]
FWIW, I posted v1.16 and v1.17 over the weekend.  V1.18 has not reached stable yet, so that will be posted after that happens, probably early next week.
