### ISSUE TITLE
man buildah-copy does not tell anything about symbolic links

### ISSUE THREAD

**Issue by veita** [containers/buildah#2802]
`man buildah-copy` does not tell anything about symbolic links

**Steps to reproduce the issue:**
1. run `man buildah-copy`
2. Look for documentation about how symbolic links are handled.

The man page does not provide information about how symbolic links are handled.

**Describe the results you expected:**
It should be documented how different kinds of symbolic links are handled. When the content of the linked resource or resources are copied, when the symbolic link itself is copied,...

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/unknown,now 1.17.0~1 amd64 [installed]
buildah/unknown 1.17.0~1 arm64
buildah/unknown 1.17.0~1 armhf
buildah/unknown 1.17.0~1 ppc64el
```

**Output of `buildah version`:**

```
Version:         1.17.0
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.7.0
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux helium 5.3.0-0.bpo.2-amd64 #1 SMP Debian 5.3.9-2~bpo10+1 (2019-11-13) x86_64 GNU/Linux
```

**Comment by TomSweeneyRedHat** [comment]
@veita Good insight/suggestion.  Will see if we can get some explanatory text added.

**Comment by rhatdan** [comment]
@veita Interested in opening a PR to describe how buildah handles symbolic links?

**Comment by veita** [comment]
@rhatdan I actually ran `man buildah-copy` in order to find out how symbolic links are supposed to be handled by `buildah copy`. Since I found nothing I did not try to make use of them. So I'm probably not the ideal person to create such a pull request. ;-)

Maybe it would make sense to restore symbolic links (or relative symbolic links only?) with targets inside the copied tree as symbolic links in the copy, and otherwise copy the contents of linked targets that lie outside the copied tree (much like `rsync --links --copy-unsafe-links`).

**Comment by rhatdan** [comment]
@veita Could you check if this is still an issue in buildah 1.19.*?

**Comment by veita** [comment]
@rhatdan There's a new section about the `--contextdir` option:
```
Build context directory. Specifying a context directory causes Buildah to chroot
into a the context directory. This means copying files pointed at by symbolic links
outside of the chroot will fail.
```
So the issue seems to be resolved for now.

**Comment by TomSweeneyRedHat** [comment]
Thanks for the verification @Veita, I'll close this now.
