### ISSUE TITLE
docker build in buildah/contrib/docker/Dockerfile fails 

### ISSUE THREAD

**Issue by omichels** [containers/buildah#2809]
**Description**

cd  buildah/contrib/docker && docker build . -t buildah:latest

fails with

 => [4/7] COPY . /go/src/github.com/containers/buildah                                                                                            0.0s
 => ERROR [5/7] RUN env GOPATH=/go make -C /go/src/github.com/containers/buildah clean all install                                                0.3s
------
 > [5/7] RUN env GOPATH=/go make -C /go/src/github.com/containers/buildah clean all install:
#9 0.224 make: Entering directory '/go/src/github.com/containers/buildah'
#9 0.224 make: Leaving directory '/go/src/github.com/containers/buildah'
#9 0.224 make: *** No rule to make target 'clean'.  Stop.

Some background, i was just looking for a good starting point to create a
docker image based on fedora with buildah, podman and ansible-bender

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
I think this will work.

cd buildah
podman build -v $PWD:/go/src/github.com/containers/buildah:O -t buildah:latest  contrib/docker/

Or if you want to use old technology

docker build -v $PWD:/go/src/github.com/containers/buildah -t buildah:latest  contrib/docker/
