### ISSUE TITLE
Buildah error committing finished image - Not enough ID's available in namespace

### ISSUE THREAD

**Issue by daisleyj** [containers/buildah#2810]
**Description**
I am running buildah in a Centos 8.2 container on Openshift 4.3 

Pulling an image with `buildah from` (or indeed running most other buildah commands) results in the error: 
```shell
Error committing the finished image: error adding layer with blob "sha256:852e50cd189dfeb54d97680d9fa6bed21a6d7d18cfb56d6abfe2de9d7f173795": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:42 for /etc/gshadow): lchown /etc/gshadow: invalid argument
```
Executing the same command with the option `--isolation=chroot` produces an identical error.

fuse-overlayfs is installed and configured with the option `mount_program = "/usr/bin/fuse-overlayfs"`

Our ultimate aim is to be able to run buildah using Jenkins in a Centos 8.2 container running in Openshift but this throws  lot of permissions issues which we are trying to work through one by one!

**Steps to reproduce the issue:**
1. Build a centos container the image jenkins/jenkins:lts-centos (This is centos 8.2 with Jenkins installed). Our image was built with the following dockerfile: 
```yaml
FROM jenkins/jenkins:lts-centos

USER root
RUN dnf install buildah slirp4netns fuse-overlayfs shadow-utils wget -y && \
    dnf update -y && \
    dnf clean all

# Adjust storage.conf to enable Fuse storage.
RUN sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' /etc/containers/storage.conf

# Create directories required by buildah and open up permissions as buildah complains without them
RUN mkdir /.config /.local /run/containers && \
    chmod -R 777 /.config /.local /run/containers 

RUN echo '1000640000:100000:65536' >> /etc/subgid && \
    echo '1000640000:100000:65536' >> /etc/subuid

USER jenkins

# Set up environment variables as this is
# not starting with user namespace so default to
# isolate the filesystem with chroot.
ENV _BUILDAH_STARTED_IN_USERNS="" BUILDAH_ISOLATION=chroot
# Skip initial setup
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# Expose ports
EXPOSE 8080
EXPOSE 50000

# Configure volumes - In OCP we'll map this to a PVC
VOLUME /var/jenkins_home

# Copy default-user.groovy to create the default user
COPY default-user.groovy /usr/share/jenkins/ref/init.groovy.d/

# Copy and install some plugins
COPY plugins.txt /usr/share/jenkins/ref/
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

ENTRYPOINT ["/usr/local/bin/jenkins.sh"]
```
2. Deploy the container to Openshift using the image 
3. Open an interactive session into the container
4. Attempt to pull an image with the command `buildah from docker.io/library/nginx`

**Describe the results you received:**

Image cannot add layer. Output from command:
```shell
sh-4.4$ buildah from --pull docker.io/library/nginx 
Getting image source signatures
Copying blob 852e50cd189d done
Copying blob b3ddf1fa5595 done
Copying blob a29b129f4109 done
Copying blob c5df295936d3 done
Copying blob 232bf38931fc done
Copying config daee903b4e done
Writing manifest to image destination
Storing signatures
Error committing the finished image: error adding layer with blob "sha256:852e50cd189dfeb54d97680d9fa6bed21a6d7d18cfb56d6abfe2de9d7f173795": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:42 for /etc/gshadow): lchown /etc/gshadow: invalid argument
ERRO exit status 1 
```

**Describe the results you expected:**

Image successfully pulled from docker.io

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.11.6-7.module_el8.2.0+305+5e198a41.x86_64
```

**Output of `buildah version`:**

```
Version:         1.11.6
Go Version:      go1.13.4
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 8.2.2004 (Core) 
```

**Output of `uname -a`:**

```
Linux jenkins-9-86lmt 4.18.0-193.23.1.el8_2.x86_64 #1 SMP Thu Sep 17 15:34:16 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
  # This file is is the configuration file for all tools
  # that use the containers/storage library.
  # See man 5 containers-storage.conf for more information
  # The "container storage" table contains all of the server options.
  [storage]

  # Default Storage Driver
  driver = "overlay"

  # Temporary storage location
  runroot = "/var/run/containers/storage"

  # Primary Read/Write location of container storage
  graphroot = "/var/lib/containers/storage"

  [storage.options]
  # Storage options to be passed to underlying storage drivers

  # AdditionalImageStores is used to pass paths to additional Read/Only image stores
  # Must be comma separated list.
  additionalimagestores = [
  "/var/lib/shared",
  ]

  # Size is used to set a maximum size of the container image.  Only supported by
  # certain container storage drivers.
  size = ""

  # Path to an helper program to use for mounting the file system instead of mounting it
  # directly.
  mount_program = "/usr/bin/fuse-overlayfs"

  # OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
  override_kernel_check = "true"

  # mountopt specifies comma separated list of extra mount options
  # mountopt = "nodev,metacopy=on"

  # Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
  # a container, to UIDs/GIDs as they should appear outside of the container, and
  # the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
  # and will be heeded by libraries, but there are limits to the number of
  # mappings which the kernel will allow when you later attempt to run a
  # container.
  #
  # remap-uids = 0:1668442479:65536
  # remap-gids = 0:1668442479:65536

  # Remap-User/Group is a name which can be used to look up one or more UID/GID
  # ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
  # with an in-container ID of 0 and the a host-level ID taken from the lowest
  # range that matches the specified name, and using the length of that range.
  # Additional ranges are then assigned, using the ranges which specify the
  # lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
  # until all of the entries have been used for maps.
  #
  # remap-user = "storage"
  # remap-group = "storage"

  [storage.options.thinpool]
  # Storage Options for thinpool

  # autoextend_percent determines the amount by which pool needs to be
  # grown. This is specified in terms of % of pool size. So a value of 20 means
  # that when threshold is hit, pool will be grown by 20% of existing
  # pool size.
  # autoextend_percent = "20"

  # autoextend_threshold determines the pool extension threshold in terms
  # of percentage of pool size. For example, if threshold is 60, that means when
  # pool is 60% full, threshold has been hit.
  # autoextend_threshold = "80"

  # basesize specifies the size to use when creating the base device, which
  # limits the size of images and containers.
  # basesize = "10G"

  # blocksize specifies a custom blocksize to use for the thin pool.
  # blocksize="64k"

  # directlvm_device specifies a custom block storage device to use for the
  # thin pool. Required if you setup devicemapper.
  # directlvm_device = ""

  # directlvm_device_force wipes device even if device already has a filesystem.
  # directlvm_device_force = "True"

  # fs specifies the filesystem type to use for the base device.
  # fs="xfs"

  # log_level sets the log level of devicemapper.
  # 0: LogLevelSuppress 0 (Default)
  # 2: LogLevelFatal
  # 3: LogLevelErr
  # 4: LogLevelWarn
  # 5: LogLevelNotice
  # 6: LogLevelInfo
  # 7: LogLevelDebug
  # log_level = "7"

  # min_free_space specifies the min free space percent in a thin pool require for
  # new device creation to succeed. Valid values are from 0% - 99%.
  # Value 0% disables
  # min_free_space = "10%"

  # mkfsarg specifies extra mkfs arguments to be used when creating the base.
  # device.
  # mkfsarg = ""

  # use_deferred_removal marks devicemapper block device for deferred removal.
  # If the thinpool is in use when the driver attempts to remove it, the driver 
  # tells the kernel to remove it as soon as possible. Note this does not free
  # up the disk space, use deferred deletion to fully remove the thinpool.
  # use_deferred_removal = "True"

  # use_deferred_deletion marks thinpool device for deferred deletion.
  # If the device is busy when the driver attempts to delete it, the driver
  # will attempt to delete device every 30 seconds until successful.
  # If the program using the driver exits, the driver will continue attempting
  # to cleanup the next time the driver is used. Deferred deletion permanently
  # deletes the device and all data stored in device will be lost.
  # use_deferred_deletion = "True"

  # xfs_nospace_max_retries specifies the maximum number of retries XFS should
  # attempt to complete IO when ENOSPC (no space) error is returned by
  # underlying storage device.
  # xfs_nospace_max_retries = "0"

  # If specified, use OSTree to deduplicate files with the overlay backend
  ostree_repo = ""

  # Set to skip a PRIVATE bind mount on the storage home directory.  Only supported by
  # certain container storage drivers
  skip_mount_home = "false"
```

**Comment by FaridHub** [comment]
Facing the same issue, **any help from anyone.**

The output of > `buildah debug`

`
>.
.
.
DEBU Detected compression format gzip
DEBU Using original blob without modification
DEBU Detected compression format gzip
DEBU Using original blob without modification
DEBU Detected compression format gzip
DEBU Using original blob without modification
DEBU Detected compression format gzip
DEBU Using original blob without modification
Copying blob 2a753f899477 done
Copying blob 273f398fb3af done
Copying blob 2149b6b9884d done
Copying blob 70e99e6e856b done
DEBU No compression detected
DEBU Using original blob without modification
Copying config 30089a2cc5 done
Writing manifest to image destination
Storing signatures
DEBU Applying tar in /var/lib/containers/storage/overlay/1d6ce12e7f66e2ea2f7ab267d49c3a94dc8dace14395e77be21496f06b366426/diff`
`
>**DEBU error copying src image ["docker://dtr2.mycompany.com/myuser/hadoop-baseline:2"] to dest image ["dtr2.mycompany.com/myuser/hadoop-baseline:2"] err: Error committing the finished image: error adding layer with blob "sha256:2149b6b9884d85929f5afcaf4ab065be38a0838f864d11d22eee36b229b08ece": Error processing tar file(exit status 1): operation not permitted
DEBU error pulling image "docker://dtr2.mycompany.com/myuser/hadoop-baseline:2": Error committing the finished image: error adding layer with blob "sha256:2149b6b9884d85929f5afcaf4ab065be38a0838f864d11d22eee36b229b08ece": Error processing tar file(exit status 1): operation not permitted**
DEBU unable to pull and read image "dtr2.mycompany.com/myuser/hadoop-baseline:2": Error committing the finished image: error adding layer with blob "sha256:2149b6b9884d85929f5afcaf4ab065be38a0838f864d11d22eee36b229b08ece": Error processing tar file(exit status 1): operation not permitted
error creating build container: Error committing the finished image: error adding layer with blob "sha256:2149b6b9884d85929f5afcaf4ab065be38a0838f864d11d22eee36b229b08ece": Error processing tar file(exit status 1): operation not permitted
DEBU shutting down the store
ERRO exit status 125`

**Comment by TomSweeneyRedHat** [comment]
@nalind any thoughts?

**Comment by rhatdan** [comment]
What does `buildah unshare cat /proc/self/uid_map` show?

**Comment by rhatdan** [comment]
Actually this looks like you are attempting to run buildah within openshift?  Does the container get launched as a privileged container or at least as root with CAP_SETUID and CAP_SETGID?

**Comment by tuananh** [comment]
> Actually this looks like you are attempting to run buildah within openshift? Does the container get launched as a privileged container or at least as root with CAP_SETUID and CAP_SETGID?

is it required? with privileged, it works but i would prefer not.

what's the alternative?

**Comment by rhatdan** [comment]
Why not just use the OpenShift builder, which runs buildah inside?

Bottom line, In order to build an image, you need to have more then one UID, including root.  You can do this with privileged or with user namespaces.  You can not do this with a single UID container, which is the locked down default for OpenShift.

I wrote this article a while back on using buildah inside of a container.  https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/
You need to get OpenShift to launch a CRI-O container which matches these charateristics.

This is not a buildah issue, so I am going to close, although we can continue the conversation.
