### ISSUE TITLE
buildah commit the whole rootfs in rootless mode with a read-only base image

### ISSUE THREAD

**Issue by gzm55** [containers/buildah#2811]
**Description**

When build from a read-only base image in rootless mode (fuse-overlay -o nodev,fsync=0,metacopy=on),
buildah commit will mark all the rootfs as changed and the last squashed layer contains the whole rootfs.
In the mean while, with a read-write base image, the last layer only containers really changed files.

**Steps to reproduce the issue:**
1. prepare rootless environment with fuse-overlay, mount option seems irrelevant, here we use "nodev,fsync=0,metacopy=on"
2. kernel is 3.10.0-1127.19.1.el7.x86_64
3. prepare shared readonly storage with alpine:3.11, and `podman pull alpine:3.12` into local writable storage.

```bash
b83e06950dcb:/$ podman images
REPOSITORY                TAG         IMAGE ID      CREATED        SIZE     ReadOnly
docker.io/library/alpine  3.12        d6e46aa2470d  4 weeks ago    5.85 MB  false
docker.io/library/alpine  3.11        f70734b6a266  7 months ago   5.88 MB  true
```

4. build two images:

```
printf 'from alpine:3.11\nrun true\n' | buildah bud -f - -t bud:3.11 ## from read-only image
printf 'from alpine:3.12\nrun true\n' | buildah bud -f - -t bud:3.12  ## from writable image
```

5. compare the result size

```
b83e06950dcb:/$ podman images
REPOSITORY                TAG         IMAGE ID      CREATED        SIZE     ReadOnly
localhost/bud             3.12        c72f3be6e251  3 minutes ago  5.85 MB  false
localhost/bud             3.11        5fc5251fe3d3  4 minutes ago  11.8 MB  false

b83e06950dcb:/$ podman history bud:3.11
ID            CREATED        CREATED BY                                     SIZE     COMMENT
5fc5251fe3d3  6 minutes ago  /bin/sh -c true                                5.88 MB
f70734b6a266  7 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B
<missing>     7 months ago   /bin/sh -c #(nop) ADD file:b91adb67b670d3a...  5.88 MB

b83e06950dcb:/$ podman history bud:3.12
ID            CREATED        CREATED BY                                     SIZE     COMMENT
c72f3be6e251  6 minutes ago  /bin/sh -c true                                3.07 kB
d6e46aa2470d  4 weeks ago    /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B
<missing>     4 weeks ago    /bin/sh -c #(nop) ADD file:f17f65714f703db...  5.84 MB
```

**Describe the results you received:**

The new layer from read-only base images contains the whole rootfs (5.88 MB).

**Describe the results you expected:**

The last layers of both images (bud:3.11, bud:3.12) are all with size 3.07 kB.

**Output of ` apk list buildah`:**

```
buildah-1.17.0-r0 x86_64 {buildah} (Apache-2.0) [installed]
```

**Output of `buildah version`:**

```
Version:         1.17.0
Go Version:      go1.15.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.7.2-0.20190904153231-83439463f784
image Version:   5.7.0
Git Commit:      1.17.0
Built:           Sat Oct 31 21:18:30 2020
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Git Commit:   5738f6337c7e3cd1d25b58943d3c481612b5901a
Built:        Mon Sep 28 05:14:26 2020
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
3.12.1
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.1
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Output of `uname -a`:**

```
Linux b83e06950dcb 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
[storage.options]
additionalimagestores = [
"/var/lib/containers/shared-readonly",
]
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0,metacopy=on"
[storage.options.thinpool]
```

`~/.config/containers/storage.conf` is linked to `/etc/containers/storage.conf`

**Comment by gzm55** [comment]
the read-only fs is mounted via fuse-overlayfs.

**Comment by giuseppe** [comment]
what version of fuse-overlayfs are you using?

It seems to work well on Fedora 33:

```
$ podman history bud:3.11
ID            CREATED        CREATED BY                                     SIZE     COMMENT
0d7d7b4de40d  3 minutes ago  /bin/sh -c true                                3.58 kB  
f70734b6a266  7 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B      
<missing>     7 months ago   /bin/sh -c #(nop) ADD file:b91adb67b670d3a...  5.88 MB  

$ podman history bud:3.12
ID            CREATED        CREATED BY                                     SIZE     COMMENT
5690cd8d3481  2 minutes ago  /bin/sh -c true                                3.58 kB  
d6e46aa2470d  4 weeks ago    /bin/sh -c #(nop)  CMD ["/bin/sh"]             0 B      
<missing>     4 weeks ago    /bin/sh -c #(nop) ADD file:f17f65714f703db...  5.84 MB  
```

On what file system is the read-only storage?

**Comment by gzm55** [comment]
fuse-overlayfs: version 1.1.0
FUSE library version 3.9.1
using FUSE kernel interface version 7.31
fusermount3 version: 3.9.1

**Comment by giuseppe** [comment]
is the read-only storage on the same file system as the writeable storage?

**Comment by gzm55** [comment]
`/host-dir` --(bind mount rw into container A)--> `/volume-rw-in-container` --(fuse-overlay mount ro)--> `/volume-ro-in-container`

The shared storage of buildah is set to `[ /volume-ro-in-container ]`. With the base images in `/volume-ro-in-container`, I got this issue.

**Comment by rhatdan** [comment]
@giuseppe Reminder on this one.  
@gzm55 Still have this issue?

**Comment by giuseppe** [comment]
the issue seems to happen on 3.10.0-1127.19.1.el7.x86_64

On Fedora it works fine

**Comment by rhatdan** [comment]
RHEL 7 is not longer getting updates. Closing.
