### ISSUE TITLE
Example scripts use non-portable shebang (i.e., #!/usr/bin/env bash -x)

### ISSUE THREAD

**Issue by slewsys** [containers/buildah#2812]
**Description**
The [example scripts](https://github.com/containers/buildah/tree/master/examples) use a non-portable shebang: `#!/usr/bin/env bash -x`

Linux [execve(2)](https://man7.org/linux/man-pages/man2/execve.2.html) treats all arguments after the first as a single string, consequently a script using the above shebang will exit with the error `bash -x: No such file or directory`.  If GNU coreutils 8.30 is available, the shebang can be written as:  `#!/usr/bin/env -S bash -x`. The `-S` option to `env` tells it to split its arguments.

**Steps to reproduce the issue:**
1. Run any script on Linux.

**Describe the results you received:**
/usr/bin/env: ‘bash -x’: No such file or directory

**Describe the results you expected:**
Script commands printed as they're executed.

**Output of `buildah version`:**

```
buildah version 1.18.0-dev (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `cat /etc/*release`:**

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Output of `uname -a`:**

```
Linux diva 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
"/var/lib/shared",
]
...
# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev"
```

**Comment by rhatdan** [comment]
Interested in opening a PR to fix the example?

Either eliminate the -x altogether or follow the command with a
set -x
