### ISSUE TITLE
[question] how to setup dev env on macOS?

### ISSUE THREAD

**Issue by tuananh** [containers/buildah#2817]
It seems it's only supported on Linux. How does one setup dev env on macOS?

I got this error below 

```
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: 'gpgme.h' file not found
```

**Comment by TomSweeneyRedHat** [comment]
Short of running a VM on the mac, I don't think it's yet possible to compile Buildah on a mac at this point.  It would be great if it did and we'd happily take changes to name it work.

**Comment by rhatdan** [comment]
You can install and use podman on a MAC and use `podman build` Which is using buildah under the covers. We don't have any plans to make buildah run directly on a MAC, since buildah does not support remote protocols to talk to a Linux box.
