### ISSUE TITLE
(buildah run $registry) to start local registry does not work

### ISSUE THREAD

**Issue by vishnuvibronyx** [containers/buildah#2825]
**Description**

**Steps to reproduce the issue:**
1.  Followed instructions in [https://www.projectatomic.io/blog/2018/01/using-image-registries-with-buildah/](https://www.projectatomic.io/blog/2018/01/using-image-registries-with-buildah/)
2.  `registry=(buildah from registry)` runs fine
3. Registry container is running 
![image](https://user-images.githubusercontent.com/66801209/100387566-618ca680-2ff6-11eb-917e-b7851a480da6.png)
4. `# buildah run $registry` gives the following error: `command must be specified`

**Describe the results you received:**
 `# buildah run $registry` gives the following error: `command must be specified`

**Describe the results you expected:**
A running local registry server

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Listing... Done
buildah/groovy,now 1.15.2-1ubuntu2 amd64 [installed]
```

**Output of `buildah version`:**

```
buildah version 1.15.2 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
NOT a podman issue
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy

```

**Output of `uname -a`:**

```
Linux li1034-227 5.8.0-25-generic #26-Ubuntu SMP Thu Oct 15 10:30:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by rhatdan** [comment]
The article is wrong, we now require users to specify the command to run, we don't just use the command defined in the image.

buildah run $CTR /entrypint.sh /etc/docker/registry/config.yml

Would get the results you want.

@ipbabble Could you see about updating your blog?
