### ISSUE TITLE
SSH agent socket mount support while building images

### ISSUE THREAD

**Issue by angelCzar** [containers/buildah#2835]
/kind feature

**Description**
I have some dockerfiles where one of the steps requires to download a private git repository. I have been able to build the image using buildkit, by using some of their experimental features. Specifically, I have needed "--ssh" build argument and a small modification on the RUN step downloading the private repo, to make it have the following experimental syntax: "RUN --mount=type=ssh". From my limited knowledge, this is mainly exposing host's ssh agent socket to the build process so that it can be used on the needed RUN step. 

I have tried to replicate that procedure with podman, but I have not found any documentation whether podman supports these buildkit's experimental features/syntaxes or not. So, I would like to know if podman already supports it or if there is any plan to support it. In case it is already supported, I would like to know, if possible, where can I find the instructions to make it work.

I'm completely newbie with podman, so sorry for any inconvenience.

**Comment by Xerkus** [comment]
`RUN --mount` are moved to stable in dockerfile 1.2.0 https://github.com/moby/buildkit/releases/tag/dockerfile%2F1.2.0

**Comment by seperman** [comment]
@angelCzar curious what you ended up doing? I'm in the same boat. I don't want to install docker just to use the mount feature.

**Comment by rhatdan** [comment]
@seperman What exactly do you need from the --mount feature?

**Comment by seperman** [comment]
@rhatdan I was gonna use it for passing the github creds while building using buildah. Example:

```
RUN --mount=type=ssh,id=my_key pip install --no-cache-dir -r requirements.txt
```

**Comment by mth-cbc** [comment]
We are currently investigating alternatives to the Docker build process which works rootless. Buildah looks promising as a "drop in replacement", but we heavily rely on the `RUN --monut=type=ssh` flag to be able to authenticate via SSH during the build process with the guarantee that the ssh-keys cannot end up in the image by accident.

Is there any update if this feature will be supported or is there maybe another mechanism I am not aware of which solves this problem in Buildah.

**Comment by TomSweeneyRedHat** [comment]
@mth-cbc thanks for the request.   I thought the `podman run --mount` command handled that, but I'm not seeing it.  I've pinged @baude as I know he's poked around in this area and might have some thoughts.  In addition, podman secrets is just landing, I don't know if that would fit or not too.

**Comment by mth-cbc** [comment]
@TomSweeneyRedHat thanks for your answer but I think we're talking about two different things. The `podman` option would be during run-time, but I need to handle credentials properly during the build step which would be in the `buildah` domain.

**Comment by rhatdan** [comment]
What exactly does the RUN -monut=type=ssh do?  Or did you meam RUN --mount=type=ssh?

**Comment by rhatdan** [comment]
```Using SSH to access private data in builds
Acknowledgment

Please see Build secrets and SSH forwarding in Docker 18.09 for more information and examples.

The docker build has a --ssh option to allow the Docker Engine to forward SSH agent connections. For more information on SSH agent, see the OpenSSH man page.

Only the commands in the Dockerfile that have explicitly requested the SSH access by defining type=ssh mount have access to SSH agent connections. The other commands have no knowledge of any SSH agent being available.

To request SSH access for a RUN command in the Dockerfile, define a mount with type ssh. This will set up the SSH_AUTH_SOCK environment variable to make programs relying on SSH automatically use that socket.

Here is an example Dockerfile using SSH in the container:


FROM alpine


RUN apk add --no-cache openssh-client git


RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts


RUN --mount=type=ssh git clone git@github.com:myorg/myproject.git myproject
Once the Dockerfile is created, use the --ssh option for connectivity with the SSH agent.

$ docker build --ssh default .
You may need to run ssh-add to add private key identities to the authentication agent first for this to work.

```

**Comment by mth-cbc** [comment]
@rhatdan sorry for not beeing clear from the beginning, but the example you copied from the docs is exactly what we use it for.

**Comment by rhatdan** [comment]
@giuseppe Would this be possible with crun and runc now?

**Comment by giuseppe** [comment]
isn't it just about setting a bind mount in the OCI specs or what is the OCI runtime expected to do?

**Comment by nalind** [comment]
If the socket's on the filesystem, that would probably be enough, give or take permissions.  Otherwise I guess we'd have to act as a proxy.

**Comment by rhatdan** [comment]
I think we have to pass in the environment variable as well?

**Comment by nalind** [comment]
$SSH_AUTH_SOCK would need to point to where it, or a proxy, was mounted, yes.

**Comment by rhatdan** [comment]
And not be part of the container image.

**Comment by nalind** [comment]
Yes.  https://github.com/openshift/imagebuilder/pull/193 looks like a prerequisite.

**Comment by rhatdan** [comment]
@ashley-cui is starting to work on this.
