### ISSUE TITLE
Leave storage.conf alone

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2857]
There's a block of code in cirrus setup that seems to have cost people a good chunk of time in #2842:

 https://github.com/containers/buildah/blob/d69f76ab1741c834303b9dfc8d03813fe3a59577/contrib/cirrus/lib.sh#L181-L194

#1945 has been closed for over a year. It might be time to remove this workaround.

**Comment by rhatdan** [comment]
Could you open the PR ad see if it passes tests?

**Comment by rhatdan** [comment]
Seems like this is done.
