### ISSUE TITLE
Trouble removing ExposedPorts configuration

### ISSUE THREAD

**Issue by brenton** [containers/buildah#2859]
**Description**
Similar to https://github.com/containers/buildah/issues/1399, I'm struggling to find the proper way to remove incorrect values from ExposedPorts.  I don't doubt I'm doing something wrong but I'm failing to find documentation on how to remove values from ExposedPorts.

**Steps to reproduce the issue:**
1. buildah config --port="3838" $ctr
2. buildah config --port="3839" $ctr
3. buildah config --port="3838-" $ctr
4. buildah config --port="[]" $ctr
 

**Describe the results you received:**
```
    "OCIv1": {
        "config": {
            "ExposedPorts": {
                "3838": {},
                "3839": {},
                "3838-": {},
                "[]": {}
            },
```

**Describe the results you expected:**

    "OCIv1": {
        "config": {
            "ExposedPorts": {
            },

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.18.0-1.fc32.x86_64
```

**Output of `buildah version`:**

```
Version:         1.18.0
Go Version:      go1.14.10
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.8.0
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64

```

**Output of `cat /etc/*release`:**

```
Fedora release 32 (Thirty Two)
```

**Output of `uname -a`:**

```
Linux unknown0050B6B57B28 5.9.11-100.fc32.x86_64 #1 SMP Tue Nov 24 19:16:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]

[storage.options.overlay]
mountopt = "nodev,metacopy=on"

[storage.options.thinpool]
```

**Comment by rhatdan** [comment]
I don't believe we have a way to remove, would a syntax of leading with a minus sign make sense?buildah config --port="3838" $ctr
buildah config --port="3839" $ctr
buildah config --port="-3839" $ctr

Be what you would expect?

**Comment by brenton** [comment]
That would work for me!  A additional nice to have would be a way to completely empty all set values.  I'll be happy with simply a way to remove misconfigured ports. :)
