### ISSUE TITLE
buildah bud can no longer accept user input.

### ISSUE THREAD

**Issue by hansborr** [containers/buildah#2863]
**Description**

Buildah bud can no longer accept user input at all.
Prior to https://github.com/containers/buildah/pull/2708 -- it was possible to provide user input to commands during the RUN phase.

This is useful in some contexts, such as inputting a password, or accepting a confirmation prompt.

This was done to fix https://github.com/containers/podman/issues/8066 -- but there was no option added to allow for user input to be accepted.

**Steps to reproduce the issue:**
1. Create a dockerfile with the following contents (rust dev tool container):
```
FROM registry.fedoraproject.org/fedora:latest
RUN \
dnf -y upgrade && \
dnf -y install gcc vim git gdb lynx tmux openssh-server && \
useradd -m rusty && \
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo -u rusty sh && \
sudo -u rusty git clone https://github.com/rust-lang/rust.vim /home/rusty/.vim/pack/plugins/start/rust.vim && \
sudo -u rusty git config --global user.email 'rusty@example.com' && \
sudo -u rusty git config --global user.name "rusty"
```
2. Use "buildah bud" to build a container based on that dockerfile.
3. Note that the rustup installer prompts for user input (proceed with defaults / customize / cancel).
4. Attempt to proceed with the installation (option "1"). Note that even if you type "1" and hit enter, your input is not accepted.

**Describe the results you received:**

It is not possible to provide user input to the rustup command. 
The build gets stuck until you kill it.

**Describe the results you expected:**

I expected to be able to provide a response to the prompt.
On prior versions of buildah, you could just type "1", hit "enter", and it would proceed.

It's fine if I need to pass some sort of command line flag to buildah to allow this.
However, I did not see an option for this.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.18.0-1.fc33.x86_64
```

**Output of `buildah version`:**

```
Version:         1.18.0
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.8.0
Git Commit:      
Built:           Wed Dec 31 18:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 08:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `cat /etc/os-release`:**

```
NAME=Fedora
VERSION="33.20201219.0 (Silverblue)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33.20201219.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='33.20201219.0'
```

**Output of `uname -a`:**

```
Linux redacted 5.9.14-200.fc33.x86_64 #1 SMP Fri Dec 11 14:30:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

**Comment by rhatdan** [comment]
I owned a PR to add --stdin flag to allow this older behaviour.

**Comment by rhatdan** [comment]
buildah bud --stdin is now in the buildah 1.19 release.
