### ISSUE TITLE
Is buildah support to push images of oci format to registry that supports oci format like harbor ?

### ISSUE THREAD

**Issue by meilier** [containers/buildah#2872]
**Description**
I want to directly push an image in oci format to harbor. Now, I achieve this using --format options when pushing images. But, I notice that` --fomat` only use when saving image using the 'dir' trarnsport?
`-f, --format string                 manifest type (oci, v2s1, or v2s2) to use when saving image using the 'dir:' transport (default is manifest type of source)`
Is there a way for me using buildah to push an image in oci format to harbor? Does -f oci options works all correctly？

**Steps to reproduce the issue:**
1. Download an arbitrary image and tag with harbor domain
2. buildah push -f oci my.harbor.com/library/image:test
3. skopeo inpsect docker://my.harbor.com/library/image:test --raw | python3 -m json.tool

**Describe the results you received:**
result from buildah
```
Getting image source signatures
Copying blob ed0c36ccfcbe [--------------------------------------] 0.0b / 0.0b
Copying config 7985d34067 [======================================] 1014.0b / 1014.0b
Writing manifest to image destination
Storing signatures

```
result from skopeo
```
{
    "schemaVersion": 2,
    "config": {
        "mediaType": "application/vnd.oci.image.config.v1+json",
        "digest": "sha256:7985d34067bd28b227af1d8f168258312a7ec837f9bfedbcfdde7435df0dac3f",
        "size": 1014
    },
    "layers": [
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:f7d533b818f3f206040c5363f906d512566476c13565cd2bf881d398dc97bb0d",
            "size": 67077670
        }
    ]
}
```

**Describe the results you expected:**
Is this the right way for buildah push oci format images to harbor?

**Output of `rpm -q buildah` or `apt list buildah`:**

```
build from source commit 5b867f2d21429b4db278dd41f04b15d50ebc0004 Date:   Wed Dec 9 19:03:04 2020 -050
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.19.140-2009.4.0.0048.oe1.x86_64 #1 SMP Thu Sep 24 09:39:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
Does this work for you
```
ctr=$(buildah from docker://my.harbor.com/library/image:test)
buildah commit --format oci $ctr my.harbor.com/library/image:test
buildah push ...
```

**Comment by meilier** [comment]
Maybe I just switch from docker to deal with buildah. Getting used to build and push without an intermediate process. Does all these from, commit and push processes have the same result as push with options "-f oci"? It seems to me they are. If they have the same behaviour, why dir transport limites added to the option. Thanks @rhatdan

**Comment by rhatdan** [comment]
@nalind @mtrmac Do you know why?

**Comment by mtrmac** [comment]
The description is rather confusing to me, there seems to be quite a bit of context left out.

If the question is about the `skopeo copy --format` option, with current documentation
> MANIFEST TYPE (oci, v2s1, or v2s2) to use when saving image to directory using the 'dir:' transport (default is manifest type of source)

that’s a documentation bug; this affects all destinations. Care to provide a PR?

---

WRT
> **Describe the results you expected:**
> Is this the right way for buildah push oci format images to harbor?

Well, that’s not an answer to the “results you expected” question, but yes, that does look like an OCI manifest. So I’m not sure  why you are asking — is there something that actually breaks?

**Comment by rhatdan** [comment]
Since we have had no response, I am closing, Reopen if you have more information.
