### ISSUE TITLE
`arch: arm` instead of `arch: arm32v7` implies official images need to be referenced by archtecture explicitely

### ISSUE THREAD

**Issue by enedil** [containers/buildah#2873]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm running Podman on Raspberry Pi:
```
$ uname -a
Linux raspberrypi 5.4.51-v7l+ containers/podman#1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
```

The problem is, that `podman info` tells that my architecture is
```
  arch: arm
```

However official docker.io images have architectures named a bit differently, for instance `arm32v7`. This is caused by using `runtime.GOARCH` (`libpod/info.go`, function `hostInfo`), which defines the name as `arm`. In order to pull images fropm docker.io, I need to reference them by hand, for instance `FROM arm32v7/fedora`.

**Steps to reproduce the issue:**

1. Get Raspberry Pi and install Raspberry Pi OS.

2. Install podman, as detailed in installation instructions on podman.io.

3. Try building `FROM fedora`

**Describe the results you received:**

Error I get:
```
* "docker.io/library/fedora:latest": Error choosing an image from manifest list docker://fedora:latest: no image found in manifest list for architecture arm, variant "", OS linux
```

**Describe the results you expected:**

I expected that my architecture is recognized correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
pi@raspberrypi ~> podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
host:
  arch: arm
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: raspbian
    version: "10"
  eventLogger: journald
  hostname: raspberrypi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.51-v7l+
  linkmode: dynamic
  memFree: 5561524224
  memTotal: 8258523136
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 55832576
  swapTotal: 104853504
  uptime: 6h 52m 41.83s (Approximately 0.25 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/pi/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/pi/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/pi/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 armhf [residual-config]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

I didn't try, but I inspected latest GitHub source to confirm it.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

As mentioned, Raspberry Pi 4.

**Comment by firesoft-de** [comment]
Same problem for me. Trying to get a python image on a rpi3. Arch is correctly set to arm but the variant is emtpy and therefore no matching image can be found

Pulling is possible manually with podman using 
`podman pull python:3.8.7-slim-buster --override-variant v7`

With `buildah bud` there is no possibilty to override or enforcing the variant.

**Comment by rhatdan** [comment]
https://github.com/containers/buildah/pull/2868 should help fix this.

**Comment by rhatdan** [comment]
Do you know if there is a way to figure out what the variant should be?  IE Should we have a table that states
if arch=arm and variant=="" then force it to v7 by default?
Similar rules for other Arches?

**Comment by mtrmac** [comment]
https://github.com/containers/image/blob/master/internal/pkg/platform/platform_matcher.go has some internal tables, but the code should just pull the right image by default, without every caller having to care. Does that fail?

**Comment by umohnani8** [comment]
@rhatdan did #2868 fix this or is something else needed?

**Comment by rhatdan** [comment]
@jameseck @firesoft-de @jameseck Could you test against the main branch, I believe this is fixed.  Reopen if I am mistaken.
