### ISSUE TITLE
How to change ulimit on a working-container?

### ISSUE THREAD

**Issue by kawing-chiu** [containers/buildah#2880]
I notice that there is a `--ulimit` option in `buildah from` that lets you set the ulimits. However, now I have a working container that forgot to use that option on `buildah from`. How can I change the ulimits on the working container without rebuilding it? I can't seem to find this option in `buildah config` or `buildah run`.

**Comment by rhatdan** [comment]
Sadly this can only be done at container creation time, and should only effect the container, so you could commit your container and create a new container off the image with the correct ulimits.
