### ISSUE TITLE
mounts.conf doesn't support Overlay

### ISSUE THREAD

**Issue by jamescassell** [containers/buildah#2882]
**Description**

I'd like to automatically overlay-mount my DNF cache into my container.  `mounts.conf` appears to allow this, but also seems to be a misnomer since it doesn't do any kind of mount at all; it instead copies in the directory, wasting time and disk space.  This fills up my disk and makes the container start very slow when I have a fully-populated cache.

For both podman and buildah, this seems to be implemented via the `subscriptions.MountsWithUIDGID()` function

**Steps to reproduce the issue:**
1. Add `/var/cache/dnf:/var/cache/dnf` to `~/.config/containers/mounts.conf`
2. On the (Fedora 33) host, `sudo yum -y --downloadonly reinstall '*' ; sudo yum -y --downloadonly install @workstation-product-environment`
3. `df -h /home`
4. `podman run fedora:33 yum repolist`
5. `df -h /home`

**Describe the results you received:**
Observe that multiple GB of disk have been used by the fedora container, due to the copies.

**Describe the results you expected:**
`mounts.conf` should be implemented as an overlay mount, not a copy.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.18.0-2.fc33.x86_64
```

**Comment by rhatdan** [comment]
Can you do this in containers.conf?

**Comment by rhatdan** [comment]
This is a job for containers.conf not mounts.conf.  So I am going to close, since containers.conf should support this.
