### ISSUE TITLE
mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied

### ISSUE THREAD

**Issue by twolffpiggott** [containers/buildah#2899]
**Description**
Building images using the `quay.io/buildah/stable` container doesn't work on Ubuntu 18.04 with Docker 20.10.2.

**Steps to reproduce the issue:**

```sh
# pull the latest stable buildah image
docker pull quay.io/buildah/stable
docker image tag quay.io/buildah/stable buildah

# start a buildah container interactively
docker run -it --device /dev/fuse:rw --security-opt seccomp=unconfined buildah bash

# attempt to list images from within the container results in the error
buildah images

# same issue if you try to build an image from a basic dockerfile
echo "FROM registry.fedoraproject.org/fedora:latest" > Dockerfile
buildah bud -f Dockerfile .
```

Leads to the following error:

```
mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied
WARN failed to shutdown storage: "mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: permission denied"
ERRO exit status 125
```

The following variants of the docker run command produce the same issue:
1. Modifying `--device /dev/fuse:rw` to `--device /dev/fuse`
2. Adding `-v /tmp/test:/var/lib/containers/storage:Z`

This seems like a possible regression of the issue: https://github.com/containers/buildah/issues/2328

Modifying the `buildah images` command to use the vfs storage driver (`buildah images --storage-driver vfs`) results in a successful call, however the `buildah bud` call using the trivial Dockerfile (`buildah bud --storage-driver vfs -f Dockerfile .`) then fails:

```
STEP 1: FROM registry.fedoraproject.org/fedora:latest
Getting image source signatures
Copying blob 8fde7942e775 done
Copying config 79fd58dc76 done
Writing manifest to image destination
Storing signatures
ERRO Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: remount /, flags: 0x44000: permission denied
error creating build container: Error committing the finished image: error adding layer with blob "sha256:8fde7942e775327f2d6ddaf08f45fda74201a7769951b0413860e21b59b4bf82": ApplyLayer exit status 1 stdout:  stderr: remount /, flags: 0x44000: permission denied
ERRO exit status 125
```

This latter issue seems to tie in with the open issue: https://github.com/containers/buildah/issues/2554

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.18.0-1.fc33.x86_64
```

**Output of `buildah version`:**

```
Version:         1.18.0
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.8.0
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `dpkg -l |grep docker`**:

```
ii  docker-ce                        5:20.10.2~3-0~ubuntu-bionic         amd64        Docker: the open-source application container engine
ii  docker-ce-cli                    5:20.10.2~3-0~ubuntu-bionic         amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras        5:20.10.2~3-0~ubuntu-bionic         amd64        Rootless support for Docker.
```

**Comment by rhatdan** [comment]
Could this be apparmor complaining?

**Comment by twolffpiggott** [comment]
> Could this be apparmor complaining?

Thanks Daniel, yes, setting `--security-opt apparmor=unconfined` resolves the above with `buildah bud`.

I'd like to keep the container as isolated as possible from the host– I suppose that one should then set a custom apparmor profile to be maximally restrictive while not disallowing mounts.

**Comment by rhatdan** [comment]
Could you look in the audit log to see what apparmor is complaining about?  I have having a very similar conversation in a different issue.  Of course I concentrate mainly on SELinux so I am no AppArmor expert.

**Comment by twolffpiggott** [comment]
Yes, so the `buildah bud` call results in 3 apparmor denials with the `docker-default` profile:

```
type=AVC msg=audit(1610377241.326:236): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="docker-default" name="/tmp/containers.0n9yFg" pid=8405 comm="exe" srcname="/usr/bin/buildah" flags="rw, bind"
type=AVC msg=audit(1610377241.438:237): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="docker-default" name="/var/lib/containers/storage/overlay/" pid=8405 comm="4" srcname="/var/lib/containers/storage/overlay/" flags="rw, bind"
type=AVC msg=audit(1610377241.438:238): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="docker-default" name="/var/lib/containers/storage/overlay/" pid=8405 comm="4" srcname="/var/lib/containers/storage/overlay/" flags="rw, bind"
```

Did some looking around and this seems to refer to an almost identical apparmor issue (albeit with k8s and podman)

https://flavio.castelli.me/2020/09/16/build-multi-architecture-container-images-using-kubernetes/

**Comment by rhatdan** [comment]
I guess you just take the docker-default apparmor model and add mount. Sadly I don't think Podman ships an external apparmor file that would be easy to edit.

**Comment by twolffpiggott** [comment]
Thanks Daniel, agreed. It's solved by having a mount-permissive apparmor profile.

I'm happy to close this issue since it's not an `buildah` bug. If you think it's of enough interest to document in the troubleshooting guide or similar I'd be happy to contribute, otherwise thanks for the help!

**Comment by rhatdan** [comment]
I would love to have it added to a README, or better yet blogged about.

I think we should add an issue to podman to start shipping the apparmor file to make it easier for users to edit and experiment with.

**Comment by twolffpiggott** [comment]
I think @flavio 's blog https://flavio.castelli.me/2020/09/16/build-multi-architecture-container-images-using-kubernetes/ is an excellent example!

He opened this related issue on podman to dump the default apparmor profile https://github.com/containers/podman/pull/7599

which was closed based on this PR https://github.com/moby/moby/pull/41442 which adds the ability to customise apparmor profiles. This would then need to be ported to podman.

Do you think it's worthwhile to add an issue on podman to just expose the current apparmor file via the repo in the interim?

**Comment by radupopa2010** [comment]
As described in this stackoverflow answer: https://stackoverflow.com/questions/48402218/fuse-inside-docker
and inspired by reading https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/

Something like this works
```
podman run \
      --volume .:/build  \
      --volume /var/lib/containers/:/var/lib/containers  \
      --device /dev/fuse \
      --privileged   \
      quay.io/buildah/stable \
          buildah bud  \
            --layers=true  \
            --cache-from  IMAGE:TAG  \
            --tag         IMAGE:TAG \
            /build  
```

**Comment by twolffpiggott** [comment]
One of the goals in this thread is keeping the container isolated from the host, so we need to avoid using the `privileged` flag.

The custom apparmor profile solves this by allowing only a minimal set of extra operations.

**Comment by rhatdan** [comment]
SGTM
