### ISSUE TITLE
buildah version in upstream is showing the wrong version

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#2917]
If you build the buildah available in upstream GitHub and run `buildah version`, it shows it's version as `v1.19.1`.  It should instead show `1.20.0-dev`

This needs to changes in the files buildah.go and contrib/rpm/buildah.spec, and the 1.19.1 entries in changelog.txt and CHANGELOG.md should be removed too.

**Comment by rhatdan** [comment]
This is now fixed in main branch.
