### ISSUE TITLE
A few hiccups with tutorial #4

### ISSUE THREAD

**Issue by tvendelin** [containers/buildah#2922]
I've experienced a few hiccups going through the tutorial https://github.com/containers/buildah/blob/master/docs/tutorials/04-include-in-your-build-tool.md 

Adding Buildah as a Go dependency "as-is" fails with errors:

```
# github.com/containers/storage/drivers/btrfs
../go/pkg/mod/github.com/containers/storage@v1.24.5/drivers/btrfs/btrfs.go:8:10: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
# pkg-config --cflags  -- devmapper
Package devmapper was not found in the pkg-config search path.
Perhaps you should add the directory containing `devmapper.pc'
to the PKG_CONFIG_PATH environment variable
No package 'devmapper' found
pkg-config: exit status 1
# github.com/mtrmac/gpgme
../go/pkg/mod/github.com/mtrmac/gpgme@v0.1.2/data.go:4:11: fatal error: gpgme.h: No such file or directory
 // #include <gpgme.h>
           ^~~~~~~~~
compilation terminated.
```
This is fixed by installing the following packages:
```
zypper in libbtrfs-devel libgpgme-devel device-mapper-devel
```
I believe, mentioning the required packages/libraries would make the tutorial more welcoming for new users.

Some context: I'm using a VitualBox VM with
```
OS: openSUSE Leap 15.2
go version go1.15.6 linux/amd64
```

**Comment by rhatdan** [comment]
Interested in opening a PR to fix the tutorial?

**Comment by tvendelin** [comment]
> Interested in opening a PR to fix the tutorial?

With pleasure.

**Comment by tvendelin** [comment]
PR sent.

**Comment by rhatdan** [comment]
Thanks.

**Comment by Alanthur** [comment]
My  system is Ubuntu 20.04.2 LTS
How can I fix this error？

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
> My system is Ubuntu 20.04.2 LTS How can I fix this error？ I can not use `zypper in libbtrfs-devel libgpgme-devel device-mapper-devel`

@Alanthur `sudo apt install libbtrfs-dev libgpgme-dev libdevmapper-dev`

**Comment by lsm5** [comment]
@rhatdan guess we should also include ^ for ubuntu users. I'll PR for it.

**Comment by lsm5** [comment]
@rhatdan btw, should we be building buildah without btrfs support? Our fedora package so far only has `exclude_graphdriver_devicemapper`.

**Comment by rhatdan** [comment]
No there are actual users of the btrfs storage driver.  But it is not necessary for any random people building buildah.
