### ISSUE TITLE
leading-/-entries in .dockerignore have no effect

### ISSUE THREAD

**Issue by patrickbkr** [containers/buildah#2936]
**Description**

`podman build` seems to disregard patterns starting with a `/` in `.dockerignore`.

**Steps to reproduce the issue:**

```
$ ls -a *
Containerfile  file-a  file-b  file-c

dir-x:
.  ..  file-f

dir-y:
.  ..  file-d

dir-z:
.  ..  file-e
```

```
$ cat Containerfile 
FROM alpine:latest
RUN mkdir /app
WORKDIR /app
COPY . /app
```

```
$ cat .dockerignore 
/file-b
file-c
/dir-x
/dir-y/
dir-z
```

`$ podman build -t test .`
`$ podman run -it test /bin/sh`

`$ ls *`

**Describe the results you received:**

```
Containerfile  file-a         file-b

dir-x:
file-f

dir-y:
file-d
```

**Describe the results you expected:**

```
Containerfile  file-a
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ rpm -q buildah
package buildah is not installed
```

**Output of `buildah version`:**

```
$ buildah version
bash: buildah: command not found
```

**Output of `podman version` if reporting a `podman build` issue:**

```
$ podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Wed Sep 30 21:51:15 2020
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
$ cat /etc/*release
Fedora release 31 (Thirty One)
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Thirty One)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
Fedora release 31 (Thirty One)
Fedora release 31 (Thirty One)
```

**Output of `uname -a`:**

```
$ uname -a
Linux localhost.localdomain 5.8.18-100.fc31.x86_64 #1 SMP Mon Nov 2 20:32:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ cat /etc/containers/storage.conf | egrep -v '^(#.*)?$'
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

I can reproduce the error with the latest Podman.  Note that Fedora 31 already hit end of life.  You may consider updating to get updates.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @nalind PTAL

**Comment by nalind** [comment]
Looks like `imagebuilder` suffers from the same incompatibility with `docker build`.  Changing either imagebuilder's `ParseDockerignore()` or `github.com/containers/storage/pkg/fileutils.NewPatternMatcher()` to strip leading or trailing path separators should fix both imagebuilder and buildah.

**Comment by rhatdan** [comment]
Are you going to open a PR to fix?

**Comment by nalind** [comment]
Unless someone else gets to it before I can carve out the time to write the tests for it, yes.  Self-assigning.

**Comment by rhatdan** [comment]
I added this to my https://github.com/openshift/imagebuilder/pull/183 PR, which we will vendor into Podman as soon as it merges.
