### ISSUE TITLE
Replace/Implement alternative to .dockerignore as a standard name convention.

### ISSUE THREAD

**Issue by htcosta** [containers/buildah#2944]
To further abstract docker from a standard OCI model, would be possible to replace the .dockerignore with a .containerignore ?

**Comment by vrothberg** [comment]
After our chat in IRC, I think you meant to desribe ".dockerignore", correct?

**Comment by htcosta** [comment]
> dockerfile

> After our chat in IRC, I think you meant to desribe ".dockerignore", correct?

@vrothberg , that is correct.

**Comment by rhatdan** [comment]
We don't support .containerignore.  Just .dockerignore thus far.

**Comment by rhatdan** [comment]
We do support --ignorefile now.

**Comment by rhatdan** [comment]
We now support .containerfile.
