### ISSUE TITLE
v1.19.4 on Fedora 33 - gating test failure [4] [NOT SURE IF UPSTREAM ISSUE]

### ISSUE THREAD

**Issue by lsm5** [containers/buildah#3013]
**Description**

From @nalind on IRC: 431 is testing that we can push an image to a docker daemon on the same host. is there one running and available?

**Describe the results you received:**

See: https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/19549/testReport/(root)/tests/root_test/

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.19.4-2.fc33.x86_64
```

**Output of `buildah version`:**

```
Version:         1.19.4
Go Version:      go1.15.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.1
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

rpms involved in gating test: https://bodhi.fedoraproject.org/updates/FEDORA-2021-fb466fb623

```
buildah-1.19.4-2.fc33
containernetworking-plugins-0.9.1-2.fc33
containers-common-1-4.fc33
podman-3.0.0-1.fc33  
skopeo-1.2.1-1.fc33
```

**Comment by lsm5** [comment]
> From @nalind on IRC: 431 is testing that we can push an image to a docker daemon on the same host. is there one running and available?

@edsantiago Any idea? ^

**Comment by edsantiago** [comment]
Docker daemon: no. Is this a new requirement? We run a local registry, but I've never heard of needing docker itself. That will be tricky on Fedora, and obviously impossible on RHEL.

**Comment by nalind** [comment]
The `buildah push image to docker and docker registry` test is skipped if there's no `docker` command, but I'm guessing the presence of the `podman-docker` package would confuse things.

**Comment by rhatdan** [comment]
This looks like we are testing with different tests then are in tests/bud.bats?  I see the following in our tests.

```
@test "bud capabilities test" {
  _prefetch busybox
  # --cap-add necessary b/c https://github.com/containers/common/pull/319
  # removed cap_net_raw, cap_mknod, and cap_audit_write
  run_buildah bud --cap-add cap_net_raw,cap_mknod,cap_audit_write -t testcap --signature-policy ${TESTSDIR}/policy.json -f ${TESTSDIR}/bud/capabilities/Dockerfile
  expect_output --substring "uid=3267"
  expect_output --substring "CapBnd:	00000000a80425fb"
  expect_output --substring "CapEff:	0000000000000000"
}
```

But the test you are running is doing:

  run_buildah bud  -t testcap --signature-policy ${TESTSDIR}/policy.json -f ${TESTSDIR}/bud/capabilities/Dockerfile

IE Does not have the capabilities added back in?
