### ISSUE TITLE
Overwriting storage options with STORAGE_OPTS and --storage-opt fails

### ISSUE THREAD

**Issue by r10r** [containers/buildah#3019]
Hi @buildah devs,

I noticed some strange behaviour when trying to overwrite the storage driver options using
the environment variable `STORAGE_OPTS` or the cmdline flag `--storage-opt`.

Note: Maybe `--storage-opt` should be renamed to `--storage-opts` to match up with the environment variable.

The storage driver is set to `overlay` by default:

```
[root@k8s-cluster8-controller container]# cat /etc/containers/storage.conf
[storage]
driver = "overlay"

[storage.options.overlay]
mountopt = "nodev,redirect_dir=on,metacopy=off,index=on,xino=auto"
```

```
buildah version 1.19.4 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

## Unexpected Behaviour

`man buildah`

> The STORAGE_OPTS environment variable overrides the default. The --storage-opt  specified  options  overrides all.

Trying to overwrite the default storage options from `/etc/containers/storage.conf`  fails:

```
buildah --storage-opt 'redirect_dir=off' from ubuntu:20.04
overlay: Unknown option redirect_dir
WARN failed to shutdown storage: "overlay: Unknown option redirect_dir" 
```

```
export STORAGE_OPTS='redirect_dir=off'
buildah from ubuntu:20.04
overlay: Unknown option redirect_dir
WARN failed to shutdown storage: "overlay: Unknown option redirect_dir" 
```

```
export STORAGE_OPTS='redirect_dir=off'
STORAGE_DRIVER='overlay'
buildah from ubuntu:20.04
overlay: Unknown option redirect_dir
WARN failed to shutdown storage: "overlay: Unknown option redirect_dir" 
```

```
buildah --storage-driver overlay --storage-opt 'redirect_dir=off' from ubuntu:20.04
overlay: Unknown option redirect_dir
WARN failed to shutdown storage: "overlay: Unknown option redirect_dir" 
```

kinda strange that this does not raise an error:
```
export STORAGE_OPTS='redirect_dir=off,foo=bar'
buildah --storage-driver overlay from ubuntu:20.04
```

**Comment by r10r** [comment]
I just noticed that the value from `STORAGE_OPTS` gets appended to the default value in the help output:

```
export STORAGE_OPTS='foo=bar'
buildah --help | grep storage-opt | grep -o '(default.*$'
(default ["overlay.mountopt=nodev,redirect_dir=off,metacopy=off,index=on,xino=auto",foo=bar])
```

**Comment by rhatdan** [comment]
This worked for me:

sudo buildah --storage-opt 'overlay.mountopt=redirect_dir=off' from ubuntu:20.04
sudo buildah --storage-opt 'mountopt=redirect_dir=off' from ubuntu:20.04
sudo buildah --storage-opt 'redirect_dir=off' from ubuntu:20.04
overlay: Unknown option redirect_dir
WARN failed to shutdown storage: "overlay: Unknown option redirect_dir"

**Comment by r10r** [comment]
@rhatdan Thanks to your comment I realized that `--storage-opt` is for passing all options supported by the selected storage driver to `containers/storage` ...  i assumed it was just for passing the mount options -  sorry for not reading the docs thoroughly
