### ISSUE TITLE
`podman build` incorrectly issues 'missing build arguments' warnings for multi-stage builds

### ISSUE THREAD

**Issue by srcshelton** [containers/buildah#3020]
**Description**

With `podman-3.0.0` I'm getting warnings such as:

```
time="2021-02-18T10:12:37Z" level=warning msg="missing \"ROOT\" build argument. Try adding \"--build-arg ROOT=<VALUE>\" to the command line"
time="2021-02-18T10:12:37Z" level=warning msg="missing \"env_name\" build argument. Try adding \"--build-arg env_name=<VALUE>\" to the command line"
time="2021-02-18T10:12:37Z" level=warning msg="missing \"ROOT\" build argument. Try adding \"--build-arg ROOT=<VALUE>\" to the command line"
time="2021-02-18T10:12:37Z" level=warning msg="missing \"SYSROOT\" build argument. Try adding \"--build-arg SYSROOT=<VALUE>\" to the command line"
```

... from multi-stage Dockerfile files containing, e.g.:

```
ARG ROOT="/some/value"
...

FROM image1
ARG ROOT
...

FROM image2
ARG ROOT
```

... which is, by my understanding, the correct means by which multi-stage builds should inherit (Dockerfile) global arguments, in a Don't Repeat Yourself manner.

The warning in this case appears spurious - the values are present and inherited from the global scope.

**Output of `buildah version`:**

```
Version:         1.19.4
Go Version:      go1.15.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.10.1
Git Commit:      175c3e87390ee999b6fd55243bb314af1f7607a0
Built:           Tue Feb  9 14:03:11 2021
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.7
Git Commit:   5b2585f5e91ca148f068cefa647c23f8b1ade622
Built:        Sun Feb 14 20:44:18 2021
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Gentoo Base System release 2.7
DISTRIB_ID="Gentoo"
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

**Output of `uname -a`:**

```
Linux dellr330 5.10.16-gentoo #19 SMP Wed Feb 17 01:23:31 GMT 2021 x86_64 Intel(R) Xeon(R) CPU E3-1240L v5 @ 2.10GHz GenuineIntel GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/space/podman/run"
graphroot = "/space/podman/storage"
rootless_storage_path = "/space/podman/user/$USER"

[storage.options]

[storage.options.aufs]
mountopt = ""

[storage.options.btrfs]
min_space = ""
size = ""

[storage.options.thinpool]
autoextend_percent = ""
autoextend_threshold = ""
basesize = ""
blocksize = ""
directlvm_device = ""
directlvm_device_force = ""
fs = ""
log_level = ""
min_free_space = ""
mkfsarg = ""
mountopt = ""
size = ""
use_deferred_deletion = ""
use_deferred_removal = ""
xfs_nospace_max_retries = ""

[storage.options.overlay]
ignore_chown_errors = "false"
mount_program = ""
mountopt = ""
size = ""

[storage.options.vfs]
ignore_chown_errors = "false"

[storage.options.zfs]
fsname = ""
mountopt = ""
size = ""
```

**Comment by rhatdan** [comment]
Are you saying that the arguments are working, you just see bad warnings?

**Comment by srcshelton** [comment]
Yes - the build completes successfully regardless.

But it feels as if we shouldn't be generating dubious warnings for legitimate configuration, even though it's largely a cosmetic issue.

**Comment by rhatdan** [comment]
Yes I agree.  It might be best if these WARNINGS should be INFO.

**Comment by srcshelton** [comment]
Should they even be 'INFO'?

'DEBUG' at best?  It is, after all, simply confirming that a stage in a multi-stage build has inherited a global variable... is that sufficiently 'INFO' worthy?

(Now, inheriting an *unset* global variable, that's a different thing!)

**Comment by srcshelton** [comment]
(It's a legitimate warning for single-stage builds, of course)

Does this break down to "We should warn when an argument without a value _at the point of reference_ is encountered"?

**Comment by rhatdan** [comment]
Yes we should only call this function on the first stage of a multi stage build, sadly I don't know this part of the code that well.

	warnOnUnsetBuildArgs(mainNode, options.Args)

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @nalind is there an easy way in the imagebuilder code to check if you are in the fist stage of a multi-stage build?

**Comment by TomSweeneyRedHat** [comment]
When I looked into the problem of showing how many stages a build would have before the build started, I could determine the first stage, but not the total if I recall correctly.

**Comment by srcshelton** [comment]
Are the possible situations here:
* Global ARG declared, never referenced => Warn unused;
* Global ARG declared, referenced => okay;
* Global ARG declared without value, referenced => Warn no default;
* Global ARG declared with value, referenced => okay.

**Comment by TomSweeneyRedHat** [comment]
We definitely don't want to downgrade those warnings as if there wasn't a global definition made, they'd hold. I think we also warn already on when an ARG is unused at the moment, but could be proved wrong.  I think the one spot that should be concentrated on in the short term is not throwing the error if it's a global and already defined arg.

I don't have a quick fix for that, will need to dive through code.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @srcshelton Could one of you open a PR to not warn if the ARG is set.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @srcshelton Any time to work on this?

**Comment by TomSweeneyRedHat** [comment]
On my list, but hasn't bubbled up.
