### ISSUE TITLE
podman 3.0.0 - seccomp: config provided but seccomp not supported"

### ISSUE THREAD

**Issue by 42wim** [containers/buildah#3023]
**Description**

Since podman 3.0.0 using a groupadd or useradd command in Dockerfile fails the build with seccomp: config provided but seccomp not supported" (worked fine in older podman releases)

**Steps to reproduce the issue:**
1. Create a simple Dockerfile

```
FROM centos:8
RUN useradd something
```

2. Run `podman build .` (this is run as a user, not root)

3. Failure:
```
STEP 1: FROM centos:8
STEP 2: RUN useradd
error running container: error creating container for [/bin/sh -c useradd]: time="2021-02-19T12:01:50+01:00" level=error msg="container_linux.go:367: starting container process caused: seccomp: config provided but seccomp not supported"
: exit status 1
Error: error building at STEP "RUN useradd": error while running runtime: exit status 1
``` 

Also tried to build with `podman build --security-opt=seccomp=unconfined .` same result

**Describe the results you received:**

Image fails to build

**Describe the results you expected:**

Image builds :)

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Wed Feb 17 14:46:47 2021
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Stream release 8
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
CentOS Stream release 8
CentOS Stream release 8
```

**Output of `uname -a`:**

```
Linux devbuild-3 4.18.0-277.el8.x86_64 #1 SMP Wed Feb 3 20:35:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
rootless_storage_path = "/home/local-u/$USER/.local/share/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
[storage.options.thinpool]
```

**Comment by 42wim** [comment]
Building this Dockerfile with buildah works fine though.

Using the buildah from centos 8 stream: buildah-1.19.4-3.el8.x86_64

```
Version:         1.19.4
Go Version:      go1.15.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.1
Git Commit:
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

Can you share the output of `runc --version`?  It looks like runc in Stream isn't compiled with seccomp.

**Comment by 42wim** [comment]
```
runc version spec: 1.0.2-dev
go: go1.15.7
```

**Comment by vrothberg** [comment]
@jnovy do you know who maintains runc in Stream?

**Comment by vrothberg** [comment]
@containers/podman-maintainers FYI

**Comment by vrothberg** [comment]
@rhatdan do you whether that's fixed with v3.0.1?

**Comment by 42wim** [comment]
I'm using the podman/runc etc from the kubic centos 8 stream repo

**Comment by 42wim** [comment]
@vrothberg I downgraded to a older runc runc-1.0.0-145.rc91.git24a3cf8.el8.x86_64.rpm and now it works.

**Comment by rhatdan** [comment]
Can't be fixed in podman, the version of runc in stream is built incorrectly.  runc should definitely support seccomp.  need to make sure the runc in RHEL8.4 does as well.

**Comment by lsm5** [comment]
@vrothberg the podman and buildah that @42wim is using do not depend on runc at all. On the kubic repo, only centos7 builds depend on runc, all else depend on crun.

**Comment by lsm5** [comment]
> @vrothberg the podman and buildah that @42wim is using do not depend on runc at all. On the kubic repo, only centos7 builds depend on runc, all else depend on crun.

At least that's how it is in the spec file dependencies list. If buildah and podman still depend on runc, then we gotta account for that I guess. The runc package that is present on the kubic repo mentioned by @42wim is only used by centos 7.

**Comment by lsm5** [comment]
> At least that's how it is in the spec file dependencies list. If buildah and podman still depend on runc, then we gotta account for that I guess. The runc package that is present on the kubic repo mentioned by @42wim is only used by centos 7.


Correction, it was there because I forgot to disable it from the build list. Neither CentOS 8 nor CentOS 8 Stream depend on it atm. CentOS 7 still depends on the runc package, but it doesn't pull the runc from Kubic. 

Let me know if any of that needs to be changed.

**Comment by 42wim** [comment]
I've did some more debugging

podman actually uses `crun` when running containers, but .. when building them using buildah, it uses runc..

```
DEBU[0000] Running ["/usr/bin/runc" "create" "--bundle" "/var/tmp/buildah085589552" "--pid-file" "/var/tmp/buildah085589552/pid" "--no-new-keyring" "buildah-buildah085589552"] 
```

That's why it worked when downgrading runc.

I've got btw `crun-0.17-3.el8.x86_64` installed

```
crun version 0.17
commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
```

**Comment by vrothberg** [comment]
@42wim, thanks!  We fixed that recently so that `podman build` would use `crun` as well.

**Comment by lsm5** [comment]
> @42wim, thanks! We fixed that recently so that `podman build` would use `crun` as well.

@vrothberg is this yet to land in a podman release?

**Comment by vrothberg** [comment]
It should be in v3.0.1 but I _think_ there are other corner cases where Buildah and Podman may chose differently.

**Comment by rhatdan** [comment]
Fixed in current case, I believe.
