### ISSUE TITLE
global config not readed in rootless mode.

### ISSUE THREAD

**Issue by CzBiX** [containers/buildah#3024]
**Description**
global config `/etc/containers/containers.conf` will not used when user config not exists in rootless mode.
Which is inconsistent with podman.

**Steps to reproduce the issue:**
1. change `engine.runtime` to `crun` in `/etc/containers/containers.conf`
2. run `podman info` and `buildah info`

**Describe the results you received:**
`ociRuntime.name` in `podman info` is `crun`
`OCIRuntime` in `buildah info` still is `runc`

**Describe the results you expected:**
`OCIRuntime` in `buildah info` is `crun`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/kali-rolling,now 1.16.6+dfsg1-2 amd64
```

**Output of `buildah version`:**

```
buildah version 1.16.6 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.6
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64
```

**Comment by rhatdan** [comment]
This should be fixed in podman 3.0

**Comment by rhatdan** [comment]
```
system (master) $ grep ^runtime ~/.config/containers/containers.conf
runtime = "runc"
system (master) $ podman info | grep runc
    name: runc
    path: /usr/bin/runc
      runc version 1.0.0-rc92
system (master) $ vi ~/.config/containers/containers.conf
system (master) $ grep ^runtime ~/.config/containers/containers.conf
runtime = "crun"
system (master) $ podman info | grep crun
    name: crun
    package: crun-0.17-1.fc33.x86_64
    path: /usr/bin/crun
      crun version 0.17
```

**Comment by CzBiX** [comment]
Just upgraded buildah to `Version: 1.19.3`, issue resolved.
