### ISSUE TITLE
possible to make version specification similar to podman ??

### ISSUE THREAD

**Issue by lsm5** [containers/buildah#3048]
This change combined with my autobuilder messed up the rpm version on rawhide :D https://bugzilla.redhat.com/show_bug.cgi?id=1933039 . This should hopefully get fixed whenever we have the packit automation in place I guess. 

But anyway, just wondering if it would help to have version specification done the same way in all of podman, buildah and skopeo.

https://github.com/containers/buildah/blob/0ade935ec426d768eacf040a2e45afaf12c66d12/define/types.go#L13

@rhatdan @nalind @baude @vrothberg @TomSweeneyRedHat

**Comment by vrothberg** [comment]
Looks like @rhatdan's recent changes didn't forward the `Version`?

**Comment by lsm5** [comment]
I'll close this for now. Will re-open when I'm ready to send patches.
