### ISSUE TITLE
rootless: overlay mounts broken with 1.19

### ISSUE THREAD

**Issue by jamescassell** [containers/buildah#3051]
**Description**

Rootless overlay mounts broke for buildah 1.19 and podman 3.0.

**Steps to reproduce the issue:**
```
user1@localhost ~]$ c=$(buildah from --pull=false -v /var/cache/dnf:/var/cache/dnf:O ubi8)
[user1@localhost ~]$ buildah run $c bash --login
2021-03-02T17:08:24.000472807Z: invalid mount type for ``
error running container: error creating container for [/usr/bin/bash --login]: : exit status 1
error while running runtime: exit status 1
ERRO exit status 1
```
podman broken:
```
[user1@localhost mybtrfs]$ podman run -it --rm -v /var/cache/dnf:/var/cache/dnf:O ubi8
Error: OCI runtime error: invalid mount type for ``
```

**Describe the results you received:**

**Describe the results you expected:**
works w/ buildah 1.18 or podman 2.2.1

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ rpm -q buildah podman
buildah-1.19.6-2.fc33.x86_64
podman-3.0.1-1.fc33.x86_64
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by TomSweeneyRedHat** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
closing as it seems to be fixed upstream both for buildah and podman
