### ISSUE TITLE
buildah-from: Unable to provide paths containing ':' characters via --volume

### ISSUE THREAD

**Issue by vaibhav92** [containers/buildah#3073]
When creating bind mount via 'buildah from' command, passing host-dir or container-dir as paths containing ':' will trigger an error of the form below:

>  $ readlink -f rpm
/home/vaibhav/2021-03-10-06:10/rpm
$ buildah from --name myimage  --volume /home/vaibhav/2021-03-10-06:10/rpm:/rpms:ro oci-archive:/data/images/mybaseimage
error checking path "/home/vaibhav/2021-03-10-06": stat /home/vaibhav//2021-03-10-06: no such file or directory
ERRO exit status 125            

Looking at the code it seems to be caused by 
https://github.com/containers/buildah/blob/30ed95a73483ad389aabb8545fdee2f74cac0874/pkg/parse/parse.go#L198
Where argument to ```--volume``` is split into 3 components with ':' as delimiter.

Is there any other way with which such bind mounts can be defined with buildah-from ?

**Output of  ```buildah version:```**
```
Version:         1.19.6
Go Version:      go1.15.8
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.2
Git Commit:      
Built:           Thu Jan  1 05:30:00 1970
OS/Arch:         linux/amd64
```

**Output of ```podman version``` if reporting a podman build issue:**
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 22:26:17 2021
OS/Arch:      linux/amd64
```

**Output of ```cat /etc/*release```**
```
Linux Client for e-business (Fedora) 33 (Daily)
Fedora release 33 (Thirty Three)
Open Client Fedora 33 (Daily)
NAME=Fedora
VERSION="33 (KDE Plasma)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde
Fedora release 33 (Thirty Three)
Fedora release 33 (Thirty Three)
```
**Output of ```uname -a```**
```
Linux <snip> 5.10.19-200.fc33.x86_64 #1 SMP Fri Feb 26 16:21:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
I have a feeling this is going to break any container engine.  The `:` is a reserved character, and it would difficult for us to code around this.
A hacky away around this might be to set up a symbolic link and mount that link, which might work.

**Comment by rhatdan** [comment]
Won't fix.  Because of issues described above.
