### ISSUE TITLE
Generated image altered when using --squash option

### ISSUE THREAD

**Issue by nlach-tehtris** [containers/buildah#3074]
**Description**

Squashing the layers into one during build seems to fail when there is a socket present on the filesystem, resulting in a corrupted image generated (missing folders and binaries)

**Steps to reproduce the issue:**

1. Use the following dockerfile for building the image

```
FROM docker.io/library/ubuntu:18.04

RUN apt-get update \
    ; apt-get install -y netcat-openbsd \
    ; nc -lkU /test.socket & sleep 1

RUN ls /
```

2. Build image using _squash_ parameter
3. Compare the result of "__ls /__" command during image building and after image building

**Describe the results you received:**

During image building, the ls command output is :

```
STEP 3: RUN ls /
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  test.socket  tmp  usr  var
```

We now have 2 images, __docker.io/library/ubuntu:18.04__ and __localhost/test:latest__ with a strange size difference (new image is smaller when adding new packages ?)

```
user@local $ buildah images
REPOSITORY                   TAG      IMAGE ID       CREATED         SIZE
localhost/test               latest   cda0f11ca4de   6 minutes ago   21.6 MB
docker.io/library/ubuntu     18.04    329ed837d508   7 days ago      65.6 MB
```

When running "__ls /__" inside our new image, we obtain a different result than during building

```
user@local $ podman run -it --rm --entrypoint '["/bin/ls", "/"]' test:latest
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys
```

**Describe the results you expected:**

Having the filesystem not altered after squashing all layers into one

Same problem seems to happend with `podman image build` command

**Output of `rpm -q buildah` or `apt list buildah`:**

Buildah binary compiled from source, @tag/v1.19.6

**Output of `buildah version`:**

```
Version:         1.19.6
Go Version:      go1.13.4
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.10.2
Git Commit:      7aedb164
Built:           Mon Mar  1 14:58:58 2021
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.13.4
Git Commit:   c640670e85c4aaaff92741691d6a854a90229d8d
Built:        Thu Mar 11 11:50:34 2021
OS/Arch:      linux/amd64
```

**Output of `uname -a`:**

```
Linux local 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
  driver = "overlay"
  runroot = "/path/to/run/"
  graphroot = "/path/to/containers/storage"
  [storage.options]
    mount_program = "/path/to/fuse-overlayfs"
```

**Comment by rhatdan** [comment]
First don't do that. put your sockets on a tmpfs.  :^)

What was the buildah command you were using to build with? Was this done rootless?  Does it work better if rootfull?  Might be a fuse-overlay issue.

@nalind @giuseppe PTAL

**Comment by giuseppe** [comment]
I can reproduce locally, both rootless with fuse-overlayfs and as root with native overlay.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/buildah/pull/3075
