### ISSUE TITLE
podman build expects Dockerfile instead of Containerfile

### ISSUE THREAD

**Issue by p3lim** [containers/buildah#3078]
**Description**

Using the `-f` flag to target a directory containing a Containerfile with `podman build` expects a Dockerfile, yet running `podman build` by itself within that directory detects the Containerfile just fine.

**Steps to reproduce the issue:**
1. `ls -l foo/`:

        Containerfile

2. `cat foo/Containerfile`:

        FROM scratch

3. `cd foo; podman build .`:

        STEP 1: FROM scratch
        STEP 2: COMMIT
        --> da73610c980
        da73610c980b8c8b185a721fcfcdd09dd1d0c3101315d97b362cf96b991a8760

4. `cd ..; podman build -f foo/ .`:

        Error: open foo/Dockerfile: no such file or directory

**Describe the results you received:**

`Error: open foo/Dockerfile: no such file or directory`

**Describe the results you expected:**

The image to be built, like in step 3.

**Output of `rpm -q buildah` or `apt list buildah`:**

`rpm -q podman` (I don't have buildah installed)
```
podman-2.2.1-1.fc33.x86_64
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5                                          
Built:        Tue Dec  8 15:37:50 2020           
OS/Arch:      linux/amd64
```

**Output of `cat /etc/osrelease`:**

```
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Output of `uname -a`:**

```
Linux ws 5.10.15-200.fc33.x86_64 #1 SMP Wed Feb 10 17:46:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
```

**Comment by rhatdan** [comment]
From the man page definition you are supposed to specify a file not a directory.  I did not know the directory would work this way.

```
   --file, -f=Containerfile
       Specifies a Containerfile which contains instructions for building the image, either a local file or an http or https URL.  If more than one Containerfile is specified, FROM instructions
       will only be accepted from the first specified file.

       If a build context is not specified, and at least one Containerfile is a local file, the directory in which it resides will be used as the build context.

       If you specify -f -, the Containerfile contents will be read from stdin.
```

**Comment by p3lim** [comment]
Thanks for the quick fix!
