### ISSUE TITLE
Confusing output when multiple --tag invocations used.

### ISSUE THREAD

**Issue by mikepurvis** [containers/buildah#3084]
**Description**

I'm experimenting with `buildah bud`, and overall it is awesome! One nit is that although specifying the `--tag` argument multiple times does the expected thing, the console output only indicates a single tagging taking place.

**Steps to reproduce the issue:**

```
buildah bud --layers=true --tag foo --tag bar .
```

**Describe the results you received:**

```
$ buildah bud --layers=true --tag foo --tag bar .
...
STEP 8: COMMIT foo
--> 81279655a91
81279655a91807dabd26cead86ae03536b03a62fb8d2d5a4a0f903e0bad15fc0

$ buildah images
REPOSITORY                    TAG      IMAGE ID       CREATED          SIZE
localhost/foo                 latest   81279655a918   11 minutes ago   118 MB
localhost/bar                 latest   81279655a918   11 minutes ago   118 MB
```

**Describe the results you expected:**

```
STEP 8: COMMIT foo, bar
```
or 
```
STEP 8: COMMIT foo
STEP 9: COMMIT bar
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ apt list buildah
buildah/focal,unknown,now 100:1.19.6-2 amd64 [installed]
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.19.6
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.2
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
$ lsb_release -d
Description:    Ubuntu 20.04.1 LTS
```

**Output of `uname -a`:**

```
$ uname -a
Linux fs-mpurvis-01 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

I'm running rootless, and it is using `fuse-overlayfs`:

```
$ ls ~/.local/share/containers/storage/
mounts  overlay  overlay-containers  overlay-images  overlay-layers  storage.lock  tmp  userns.lock
```

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by mikepurvis** [comment]
I'm not at all a golang person, but I'd be happy to look. Seems like those messages come from here:

https://github.com/containers/buildah/blob/915de2e2b50af1ef30808d87e4e715142385b780/imagebuildah/stage_executor.go#L1302-L1307

Do we have a preference for one or the other of the proposed styles? If not, I would probably leave it as a single `COMMIT` which lists all the tags separated by commas. Or if we're worried about long image/tag names looking sloppy but don't want to insert separately numbered `STEP` instances for multiple tags, something like this might do the thing:

```
STEP 8: COMMIT
--> 81279655a91 tagged as foo
--> 81279655a91 tagged as bar
```

**Comment by TomSweeneyRedHat** [comment]
@mikepurvis As Docker does:
```
# docker build -f ./Dockerfile.alpine -t tom -t more .
Sending build context to Docker daemon  3.072kB
Step 1/1 : FROM alpine
 ---> e50c909a8df2
Successfully built e50c909a8df2
Successfully tagged tom:latest
Successfully tagged more:latest
```

I'd vote for 
```
STEP 8: COMMIT
--> 81279655a91 tagged as foo
--> 81279655a91 tagged as bar
81279655a91
```
I think the neighborhood that you'd want to fix is this.  The final image id is getting written here: hhttps://github.com/containers/buildah/blob/master/imagebuildah/executor.go#L691

So at that point, you'd have to look in at the variable img.Names and get the names/tags for the image and change what was being written there.  We've scripts that rely on the imageID being the last line printed, so we need to retain that.  Also if the user asked for '--quiet', we would print only the imageID, not the tag info in that instance.

HTH
