### ISSUE TITLE
Podman 3.0.1 with docker-compose segfaults when files with wildcard don't exist - buildah bud issue

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#3087]
This issue is a two-parter that was reported in Podman at: https://github.com/containers/podman/issues/9594 has been fixed on the Podman side, but a fix is also needed in buildah bud too.

**Comment by rhatdan** [comment]
Other then a lot of stuttering,  Buildah looks good on this one.

buildah bud /tmp
STEP 1: FROM alpine
STEP 2: copy *.txt /tmp
error building at STEP "COPY *.txt /tmp": error adding sources [/tmp/*.txt]: error checking on source /tmp/*.txt under "/tmp": copier: stat: "/*.txt": no such file or directory

**Comment by rhatdan** [comment]
Oops I am mistaken we do not match docker on this.

**Comment by rhatdan** [comment]
I merged a fix for this on April 19
37e9d254ccef0c2f719fa458205f04ea0db7058e
