### ISSUE TITLE
Broken link in demos/buildah_multi_stage.sh

### ISSUE THREAD

**Issue by zturtleman** [containers/buildah#3107]
A [spelling correction change](https://github.com/containers/buildah/commit/c7963db36944a914e554830ea4ab5e703968386a#diff-99c1c5b6d9759bba159e9fcaf02ef3c1cadb32f4a1f05f73bf8fa28acabcc36c) broke a link in `demos/buildah_multi_stage.sh`. It now links to a 404 error page.

```diff
-# Based on Alex Ellis blog (https://blog.alexellis.io/mutli-stage-docker-builds)
+# Based on Alex Ellis blog (https://blog.alexellis.io/multi-stage-docker-builds)
```

The actual URL has a typo "mutli" in it.

**Comment by rhatdan** [comment]
Please open a PR to fix this, along with a comment explaining the name is correct.
