### ISSUE TITLE
Update uid/gid mapping in rootless user case for buildah images.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#3119]
There's a lack of documentation for running the buildahimages on quay.io when running as a rootless user.  Add docs to clarify what's needed.  More information in #3053 and specifically from @aaabdallah https://github.com/containers/buildah/issues/3053#issuecomment-811182759

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Any chance you can tackle this?
