### ISSUE TITLE
[question] Multi-stage builds

### ISSUE THREAD

**Issue by o-alquimista** [containers/buildah#3127]
How do you perform a multi-stage build using the `buildah` command? I was expecting to find this:
```sh
container1=$(buildah from image1:tag)
container2=$(buildah from image2:tag)

buildah copy --from=$container2 /example/file.txt /file/destination $container1
```

But the --help information does not mention anything like this. I wonder if buildah really supports multi-stage builds.

**Comment by TomSweeneyRedHat** [comment]
@o-alquimista you could do something like this, I'm not sure if it's sufficient for you or if @nalind has other thoughts.
```
container1=$(buildah from image1:tag)
container2=$(buildah from image2:tag)
mntctr2=$(buildah mount container2)
buildah copy container1 mntctr2:/example/file.txt /file/destination
```
As I'm sure you're aware, you could also use a Containerfile with the bud command to do the functionality that you listed.
Adding a `--from` option might be doable longer term for the copy command if that would be of interest/use?

**Comment by o-alquimista** [comment]
Thanks! I'll give that a try.

As a Docker user migrating to Podman/Buildah, I think it would be nice to have that `--from=$container` syntax one day. I have no other complaints about Buildah so far - the commands are very familiar.

**Comment by nalind** [comment]
@TomSweeneyRedHat feel free to assign this one to me if you're not already working on it.

**Comment by rhatdan** [comment]
@nalind you got it.
