### ISSUE TITLE
buildah run breaks stdin by setting `O_NONBLOCK`

### ISSUE THREAD

**Issue by Vogtinator** [containers/buildah#3152]
Sometimes after running `buildah run` in a terminal, commands executed afterwards which try to read from `stdin` fail with `EAGAIN`. This is because it sets `O_NONBLOCK` on the FD:

```
f241:~ # grep flags /proc/self/fdinfo/0; while ! grep 'flags.*4002$' /proc/self/fdinfo/0; do buildah run sle15-working-container /bin/true; echo -n .; done; cat -
flags:  02
....................flags:      04002
cat: -: Resource temporarily unavailable
```

`strace -k` shows that this is caused by the `runCopyStdio` function: https://github.com/containers/buildah/blob/c891ebe41e8e33732c4bb8ca23004e7b4f857cc8/run_linux.go#L1236

For some reason this doesn't happen all the time and the `O_NONBLOCK` flag also disappears after some time, even after `buildah` exited. I suspect that the interactive shell is fixing that up at some point.

**Comment by rhatdan** [comment]
Is this something buildah could easily change back on exit?

**Comment by Vogtinator** [comment]
It could just restore the previous descriptor flags, I suppose.

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by Vogtinator** [comment]
Interested yes, but I unfortunately don't have the time to get familiar with the code and Go, at least not in the near future...

**Comment by rhatdan** [comment]
We have talked about this, and we are not sure there is an easy way to fix.
