### ISSUE TITLE
Documentation of Containerfile format

### ISSUE THREAD

**Issue by isavl** [containers/buildah#3166]
Where i can find documentation for Containerfile format using in podman and buildah?
What different in Dockerfile and Containerfile?

**Comment by rhatdan** [comment]
Nothing, they are exactly the same.  They are just that Podman/Buildah will look for Containerfile name by default and then Dockerfile.    Is the documentation on this need to be improved in podman build and buildah bud?

**Comment by isavl** [comment]
No thanks for the explanations.
