### ISSUE TITLE
COPY docker command is very slow for a very large build context

### ISSUE THREAD

**Issue by mwakaba2** [containers/buildah#3180]
Hi there! 

I'm not sure if I should be raising this issue here or https://github.com/distribution/distribution, but I noticed the COPY docker command takes around 8 hours to copy over a build context of ~14GB during an image build. I was able to significantly reduce the build time by doing the following:

* Create a tar archive of the build context 
* Use `ADD` to copy the archive file and untar. 

Untar took 16 minutes. Is this the recommended way for copying over a very large build context or can the `COPY` command be improved? 

# System information
OS Platform: Centos-7
Buildah version: 
```bash
$ buildah --version
buildah version 1.9.0 (image-spec 1.0.0, runtime-spec 1.0.0)
```

# Code / logs
Docker image build command
```bash
$ buildah bud --format=docker --file Dockerfile --tag <TAG> <Dockerfile location>
```

**Before**
```dockerfile
COPY . /home/sandbox/. 
```

**After**
```dockerfile
ADD ./docker_build_context.tar.gz /home/sandbox
```

```bash
$ du -sh sandbox
14G     sandbox
```

**Comment by TomSweeneyRedHat** [comment]
Ping @nalind @vrothberg

**Comment by rhatdan** [comment]
Could you try the same command as root and see if it performs better.  This could be an issue with fuse-overlayfs.

**Comment by mwakaba2** [comment]
Hi @rhatdan, just to clarify, do I run the command as root like this?
```bash
$ sudo buildah bud --format=docker --file Dockerfile --tag <TAG> <Dockerfile location>
```

**Comment by nalind** [comment]
1.9 predates a lot of the work that went in to making things faster when there's a `.dockerignore` file in the build context, so if your build context has one of those, I highly recommend updating to at least 1.16.

**Comment by mwakaba2** [comment]
thanks, that's good to know. I don't have a .dockerignore file, so it may be worth looking into that.

**Comment by rhatdan** [comment]
I am going to close this as we believe it is fixed in the newer releases.

**Comment by mwakaba2** [comment]
@nalind Will the performance be the same without the .dockerignore in the latest version? I can also test this out.

**Comment by nalind** [comment]
Yes, the impact from having or not having a `.dockerignore` file should be minimal at this point.

**Comment by mwakaba2** [comment]
Cool, got it. Thanks for the help!
