### ISSUE TITLE
`buildah rmi` removes parent images: expected behavior?

### ISSUE THREAD

**Issue by kwshi** [containers/buildah#3202]
**Description**

`buildah rmi <img>` appears to remove not only `<img>` but all of its parent layers/images if the parent layers are untagged ("dangling"?).  It's possible that this is the intended behavior, but it was unexpected to me and also not clearly documented, which I think is a bit confusing.

**Steps to reproduce the issue:**
1. Create a parent image: `ctr=$(buildah from docker.io/library/alpine)` (some arbitrary base, doesn't matter), `parent=$(buildah commit $ctr)`
2. Create a child image: `ctr=$(buildah from $parent)`, `child=$(buildah commit $ctr)`
3. Check to see both images exist: `buildah images -a`
4. Remove child image: `buildah rmi $child`
5. Check again: `buildah images -a`--the parent ID has also disappeared!

**Describe the results you received:**

The parent image gets deleted along with the child image.

**Describe the results you expected:**

I expected that `buildah rmi` only deletes the child image, leaving the parent image present.  If the reported behavior is intended/correct, then I expect the [`buildah rmi` docs](https://github.com/containers/buildah/blob/master/docs/buildah-rmi.md) to say a sentence or so clarifying the mechanics of `rmi`--namely, that it deletes the given image _as well as all dangling parent layers_ (up to the last non-dangling parent).

It's worth noting that the parent doesn't get deleted if the parent image is tagged with a name, so the behavior is specific to _dangling_ parents.

**Output of `rpm -q buildah` or `apt list buildah`:** (not on either of those platforms, I'm on Void, so `xbps-query -R buildah`)

```
architecture: x86_64
changelog: https://github.com/containers/buildah/blob/master/CHANGELOG.md
filename-sha256: 25806183e98deae0653cf8c2faa61e61426343e5cb50fb3ca6f3088e61d2d6a3
filename-size: 13MB
homepage: https://github.com/containers/buildah
installed_size: 29MB
license: Apache-2.0
maintainer: Cameron Nemo <cnemo@tutanota.com>
pkgname: buildah
pkgver: buildah-1.20.1_1
repository: https://alpha.us.repo.voidlinux.org/current
run_depends:
	runc>=0
	containers.image>=0
	glibc>=2.32_1
	libgpgme>=1.12.0_2
	libassuan>=2.0.1_1
	libgpg-error>=1.6_1
	device-mapper>=2.02.110_1
shlib-requires:
	libpthread.so.0
	libgpgme.so.11
	libassuan.so.0
	libgpg-error.so.0
	libdl.so.2
	libdevmapper.so.1.02
	libc.so.6
short_desc: Dockerfile compatible OCI image building tool
source-revisions: buildah:b177108fa1
```

**Output of `buildah version`:**

```
Version:         1.20.1
Go Version:      go1.16.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.5
Git Commit:
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

**Output of `uname -a`:**

```
Linux vic 5.11.12_1 #1 SMP 1617903641 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:** No such file, so whatever the defaults are.  Here's `buildah info`, in case it's relevant:

```
{
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "\"void\"",
            "version": "unknown"
        },
        "MemFree": 2156302336,
        "MemTotal": 67415830528,
        "OCIRuntime": "runc",
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 12,
        "hostname": "vic",
        "kernel": "5.11.12_1",
        "os": "linux",
        "rootless": true,
        "uptime": "349h 5m 18.31s (Approximately 14.54 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 9
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay.mount_program=/usr/bin/fuse-overlayfs"
        ],
        "GraphRoot": "/home/kshi/.local/share/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 9
        },
        "RunRoot": "/var/tmp/containers-user-1000/containers"
    }
}
```

**Comment by kwshi** [comment]
Possibly related to #133?

**Comment by vrothberg** [comment]
Thanks for reaching out, @kwshi!

It is expected behavior to remove dangling parent images; Podman and Docker have the same behavior.

Are you interested in opening a PR and change the man pages?

**Comment by kwshi** [comment]
Cool, thanks for the answer!  I am interested in helping with the man pages.  Is this markdown page (https://github.com/containers/buildah/blob/master/docs/buildah-rmi.md) the only thing that needs to be updated, or are there other files that should be touched?

**Comment by TomSweeneyRedHat** [comment]
@kwshi that is indeed the md file that would need to be changed and should be the only one that needs a change.
Thanks!

**Comment by rhatdan** [comment]
@kwshi Are you working on this?

**Comment by kwshi** [comment]
@rhatdan sorry, yes I'm working on this--I just got carried away and this fell off my radar.  I will get a PR in in the next couple days.

**Comment by vrothberg** [comment]
This has been fixed in the meantime. Thanks again!
