### ISSUE TITLE
Please rename the master branch to the main branch.

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#3227]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by cevich** [comment]
***Supporting/Required changes:***

- [ ] Update `$DEST_BRANCH` in `.cirrus.yml`
- [ ] Remove comment referencing `master` in podman repo. (it's obsolete)
- [ ] Update `CHANGELOG.md`, `CONTRIBUTING.md`, `developmentplan.md`, `install.md`, and `README.md` logo link
- [ ] Update many *master* references in `install.md`
- [ ] Update *master* reference in `release.sh`

(I'll update this comment as/if I find more)

**Comment by TomSweeneyRedHat** [comment]
Almost every *.md file that we have scattered across the site will need attention.

` grep -R master .  | grep -v tests | grep -v vendor | grep -v pkg | grep master`

**Comment by rhatdan** [comment]
Done
