### ISSUE TITLE
Bud argument `--default-mounts-file` is not working

### ISSUE THREAD

**Issue by floryut** [containers/buildah#3233]
**Description**
I'm trying to load mounts from another file than `/usr/share/containers/mounts.conf` using the [hidden flag](https://github.com/containers/buildah/blob/v1.11.6/cmd/buildah/main.go#L88) `--default-mounts-file` 
But as far as I've tested it doesn't work.

**Steps to reproduce the issue:**
1. Move the `/usr/share/containers/mounts.conf` elsewhere (like `/usr/share/containers/mountz.conf`)
2. Build the image using ` buildah bud --default-mounts-file /usr/share/containers/mountz.conf .`
3. Using `RUN ls -l` I can see that nothing is mounted.

**Describe the results you received:**
```
# ls -l /tmp/flo
-rw-r--r--    1 root     root            50 May 18 08:43 Dockerfile
# cat /usr/share/containers/mountz.conf
/tmp/flo:/tmp/flo
# buildah bud --default-mounts-file /usr/share/containers/mountz.conf .
STEP 1: FROM docker.io/busybox:latest
STEP 2: RUN ls -l /tmp/flo
total 0
```

**Describe the results you expected:**
When the `mountz.conf` is at its correct location
```
# ls -l /tmp/flo
-rw-r--r--    1 root     root            50 May 18 08:43 Dockerfile
# cat /usr/share/containers/mounts.conf
/tmp/flo:/tmp/flo
# buildah bud .
STEP 1: FROM docker.io/busybox:latest
STEP 2: RUN ls -l /tmp/flo
-rw-r--r--    1 root     root            50 May 18 08:43 Dockerfile
```

**Output of `rpm -q buildah` or `apt list buildah`:**
```
# rpm -q buildah
buildah/testing,now 1.19.6+dfsg1-1+b2 amd64 [installed]
```

**Output of `buildah version`:**
```
# buildah version
Version:         1.19.6
Go Version:      go1.15.9
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.3
Git Commit:
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**
```
# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by floryut** [comment]
We found that the name is wrong in bud.go https://github.com/containers/buildah/blob/2ab877eb79e8d521262bfdc6afc0b0cc6954bbed/cmd/buildah/bud.go#L302

Could this cause the flag to not work ?

**Comment by rhatdan** [comment]
Curios, could you try
buildah --default-mounts-file bud /usr/share/containers/mountz.conf .

Just to see if this changes anything.

**Comment by floryut** [comment]
Thanks for the reply, I tried (I think you meant `buildah --default-mounts-file /usr/share/containers/mountz.conf bud .`) but no luck
```
root@DESKTOP-7IHJ3QD:/home/floryut/Projects/buildah/buildme# buildah --default-mounts-file /usr/share/containers/mountz.conf bud .
STEP 1: FROM docker.io/busybox:latest
STEP 2: RUN ls -l /tmp/test
total 0
```
