### ISSUE TITLE
Arguments in FROM line bypass prior multi-stage build stage names

### ISSUE THREAD

**Issue by mikepurvis** [containers/buildah#3238]
Admittedly, this is a bit of a noodly use-case, and I'm right on the cusp of generating this `Containerfile` from a template, but I gave this approach a go and noticed it didn't work, but it does under Docker, so here's a report if the project is interested.

**Steps to reproduce the issue:**
1. Follow the "conditional copy" example [proposed here](https://stackoverflow.com/a/54245466/109517).
2. Build it with `buildah bud`

**Describe the results you received:**

I get prompted for where to download the image from:

```
$ sudo buildah bud
STEP 1: FROM alpine AS build_copy
STEP 2: COPY file /file
STEP 3: FROM alpine AS build_no_copy
STEP 4: RUN echo "I don't copy"
I don't copy
STEP 5: FROM build_copy
? Please select an image:
  ▸ docker.io/library/build_copy:latest
    quay.io/build_copy:latest
    prod-vm-docker-registry-01.clearpath.ai/build_copy:latest
```

**Describe the results you expected:**

It should use `build_copy` as defined as an earlier stage in the multi-stage build. Indeed, this works fine if the arg usage is removed and `build_copy` is hard-coded.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/focal,unknown,now 100:1.20.1-1 amd64 [installed]
```

**Output of `buildah version`:**

```
buildah --version
buildah version 1.20.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Comment by rhatdan** [comment]
```
$ /bin/buildah bud /tmp/test
STEP 1: FROM alpine AS build_copy
STEP 2: COPY file /file
Getting image source signatures
Copying blob b2d5eeeaba3a skipped: already exists  
Copying blob eed489b0034e done  
Copying config 0f8281f8a0 done  
Writing manifest to image destination
Storing signatures
--> 0f8281f8a09
STEP 3: FROM alpine AS build_no_copy
STEP 4: RUN echo "I don't copy"
I don't copy
STEP 5: FROM 0f8281f8a09628e7912dac24c1809081afacd32afa5b3c327e1ab7b1f781b8a0
STEP 6: COMMIT
--> 0f8281f8a09
0f8281f8a09628e7912dac24c1809081afacd32afa5b3c327e1ab7b1f781b8a0
$ buildah --version
buildah version 1.21.0 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)

```

**Comment by rhatdan** [comment]
Seems to work with the current (Soon to be current) release.
