### ISSUE TITLE
Debian package missing dependency on libcap2

### ISSUE THREAD

**Issue by mikepurvis** [containers/buildah#3239]
**Description**

When running `buildah bud` in a privileged Kubernetes container that started from a bare-minimum Ubuntu 20.04 image + buildah installed from the Kubic apt repo, I get this error:

```
STEP 1: FROM scratch
STEP 2: ARG series
STEP 3: ARG DEBIAN_FRONTEND=noninteractive
STEP 4: COPY "bootstrap-${series}" /
STEP 5: COPY apt-config etc/apt/apt.conf.d/99apt-config
STEP 6: RUN echo "abc abc/location string xyz" | debconf-set-selections
error running container: error creating container for [/bin/sh -c echo "abc abc/location string xyz" | debconf-set-selections]: crun: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory
```

Manually installing the `libcap2` package resolves the issue. I don't know where the Debian metadata is stored for the Kubic packages, but it should be updated to include this dependency.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ apt list buildah
Listing...
buildah/focal,unknown,now 100:1.20.1-1 amd64 [installed]
```

**Output of `buildah version`:**

```
$ /usr/bin/buildah version
Version:         1.20.1
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.5
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

@lsm5 PTAL

**Comment by lsm5** [comment]
Thanks @mikepurvis . This should be resolved with v1.21.0 available on kubic now. Please reopen if any issues.

**Comment by mikepurvis** [comment]
@lsm5 Such prompt service, thank you so much! I can confirm the fix.

**Comment by ankit-db** [comment]
@lsm5 - I'm currently installing buildah by doing:

```
RUN sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
RUN wget -nv http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key -O Release.key
RUN apt-key add - < Release.key
RUN apt-get update -qq -y && apt-get -qq -y install buildah
```

I'm getting this for the 18.04 distribution in kubic that I'm pointing to as well - was it fixed for that version?

**Comment by lsm5** [comment]
@ankit-db hi, I don't think we ever enabled kubic for 18.04. Anyway, I recommend switching to ubuntu 21.10 or newer if possible which will have buildah in the default repos. If you want to stay on 18.04, your only option at this point would be to build from source.

**Comment by ankit-db** [comment]
@lsm5 - thanks for replying! Do you know how my current installation is working then? I am currently able to install buildah this way (the way I posted in previous comment). Unfortunately, I have to stick with Ubuntu 18.04 for compliance reasons.
