### ISSUE TITLE
bud: Only squash final image when using --layers 

### ISSUE THREAD

**Issue by r10r** [containers/buildah#3240]
Hi there,

I'm currently playing with buildah to build a multi-stage image and noticed that 
`buildah bud --layers --squash` does not work as expected (by me).

Using `--layers` together with `--squash` will squash every layer - 
this takes a lot of time and exhaust disk space quite fast.
I think that only the final image should be squashed.

How do you think about changing the current behaviour ?

```
[root@k8s-cluster8-controller ruben]# buildah --version
buildah version 1.20.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Comment by rhatdan** [comment]
@mikepurvis is correct.

**Comment by r10r** [comment]
@mikepurvis Thanks for sharing your view. 

> My pattern has been to use --layers when debugging a build where I want to skip expensive upfront steps and shorten the  testing cycle ...

You're right - that's my primary goal too.  

I know it's possible to squash the build manually:

```bash
c=$(buildah from $image)
buildah commit --squash $c $squashed_image
buildah delete $c
buildah rmi $image
```

But I wonder if there is a good reason to use `--layers`  together with `--squash`?
My first step when using buildah was to enable both options, but the build took a long time
and finally aborted because the disk was full.

I think they should be either mutually exclusive or play together nicely.
Maybe a `--squash-final` flag is an option ?

**Comment by TomSweeneyRedHat** [comment]
@r10r one of @rhatdan 's favorite things to do is to close issues.  I'll reopen and we can continue the discussion.  Please close it once we wrap up.

So just taking a step back.  `buildah bud --squash` squashes all layers into one layer. Note this differs from `podman build --squash`.  The `podman build --squash` option only squashes the new layers created during the build.  If an image was used that had pre-existing layers, those layers would not be squashed.

`--layers` caches intermediate images during the builds.

So doing both `--squash` and `--layers` is probably not something you want to do outside of a CPU/disk write test.  :smile:  It should get everything down into one layer but may take it's time depending on the images/layers involved.    Others might have a good use case for doing both at the same time, but I'm drawing a blank at the time.  I know we have tests for both being used at the same time so there must have been a reason to not prevent that.

Finally, there is also a `podman build --squash-all` option.  That option does that same thing as `buildah bud --squash`, it squashes everything down to one layer.

Clear as mud?

**Comment by mikepurvis** [comment]
FWIW, I really like the `buildah` flags for this— IMO the defaults make a lot more sense than the Docker ones, and in particular, they encourage `Containerfile`s to be written for readability rather than with an obsession over what is or isn't going to generate a new layer.

**Comment by r10r** [comment]
@ TomSweeneyRedHat Clear as water!  Thanks for this good explanation and for taking your time!

**Comment by r10r** [comment]
@mikepurvis  Yes that makes sense.  Thanks for sharing your thoughts.

I realized that it's easy to avoid squashing altogether when using `COPY --from={image}` to copy build artifacts from other stages in the build. This allows a clean build setup, and even allows using the `--jobs` flag to parallelize the build.

I know it's out of scope  - but I'd like to share a shortened version of the Dockerfile finally.  

```Dockerfile
# About: Build of the `exim` mailserver for a legacy debian (sqeeze).
# This involves building several static libraries from upstream (including openssl) and some more customization. 

# common build image
FROM debian/eol:squeeze AS build-base
RUN apt-get update
RUN apt-get install -yy build-essential

# build each static library in a separate stage
FROM build-base AS libidn
ARG LIBIDN_SRC
RUN mkdir /tmp/build
WORKDIR /tmp/build
COPY $LIBIDN_SRC .
RUN tar -xf $(basename $LIBIDN_SRC) --strip-components=1
RUN ./configure
RUN make
RUN make install

FROM build-base AS libunistring
# [...]

FROM build-base AS libidn2
# [...]

FROM build-base AS openssl
# [...]


# build exim with static libraries
FROM build-base AS exim-build
RUN apt-get install -yy libpcre3-dev libdb4.8-dev libspf2-dev libsasl2-dev \
libpam0g-dev libpq-dev libsqlite3-dev libldap2-dev libperl-dev ca-certificates git

# copy libraries from previous stages
COPY --from=libidn /usr/local/ /usr/local/
COPY --from=libidn2 /usr/local/ /usr/local/
COPY --from=libunistring /usr/local/ /usr/local/
COPY --from=openssl /usr/local/ /usr/local/

RUN mkdir /tmp/exim-src
WORKDIR /tmp/exim-src
COPY $EXIM_SRC .
RUN tar -xf $(basename $EXIM_SRC) --strip-components 1
COPY exim.Makefile Local/Makefile
RUN make makefile
RUN make

# install exim runtime dependencies, cleanup and copy binary from exim-build stage
FROM debian/eol:squeeze
RUN apt-get update
RUN apt-get install -yy libpcre3 libdb4.8 libspf2-2 libsasl2-2 libpam0g libpq5 libsqlite3-0 libldap-2.4-2
RUN apt-get clean -qq
RUN rm -rf /var/lib/apt/lists/*
COPY --from=exim-build /tmp/exim-src/build-Linux-x86_64/exim /usr/sbin
