### ISSUE TITLE
Ubuntu build (at least) requires dependency on uidmap

### ISSUE THREAD

**Issue by dmick** [containers/buildah#3251]
Installing from the launchpad PPA, buildah won't run:

$ buildah images
Error: error running newgidmap: exec: "newgidmap": executable file not
found in $PATH:
ERRO[0000] error running newgidmap: : exec: "newgidmap": executable file
not found in $PATH
ERRO[0000] (unable to determine exit status)

newgidmap is contained in the 'uidmap' package, which should be a Depends: for the buildah package, I guess.

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by dmick** [comment]
note the age on this; it was misfiled for a few years.  For all I know the situation is resolved.

**Comment by rhatdan** [comment]
Ok I will close, reopen if we are mistaken.
