### ISSUE TITLE
buildah commit --squash leaves references to parent image

### ISSUE THREAD

**Issue by dmick** [containers/buildah#3253]
buildah v1.20.1
podman v3.1.2

I inherited a build procedure that uses buildah to construct an image starting FROM docker.io/centos:8, adds a bunch of things, and then does 

```buildah commit --squash --format docker <container> <tag>```

to create the final, intended-to-be-independent, image.  However, some record of the ancestry remains, and podman push mentions it in the config blob for a v2s2-format push, causing the repo server (quay.io) to reject the push, as it can't find the blob for "docker.io/centos:8", which of course it shouldn't need to.

podman inspect on the image shows a blank "Parent" field, and the only mention of the parent image is in a "History" section:

```
        "History": [
            {
                "created": "2021-05-17T20:49:55.561254531Z",
                "created_by": "/bin/sh",
                "comment": "FROM docker.io/library/centos:8"
            }
        ],
```
but somehow that's enough to allow push to form a reference to the image (captured from the http packet and formatted):
```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 2646,
    "digest": "sha256:55815f5b8e9c3fce1e7855c73aa8adc9eb8111797659f6c6840857480d16a9de"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 224790428,
      "digest": "sha256:1cedb6d23e21ca650ff098273d219f9875a2baa08281d576a93d4bfc109a5412"
    }
  ]
}
```
@nalind helped me understand that that config blob is stored locally in /var/lib/containers/storage/overlay-images/55815f5b8e9c3fce1e7855c73aa8adc9eb8111797659f6c6840857480d16a9de/=c2hhMjU2OjU1ODE1ZjViOGU5YzNmY2UxZTc4NTVjNzNhYThhZGM5ZWI4MTExNzk3NjU5ZjZjNjg0MDg1NzQ4MGQxNmE5ZGU=, which contains:
```
  "architecture": "amd64",
  "os": "linux",
  "parent": "sha256:300e315adb2f96afe5f0b2780b87f28ae95231fe3bdd1e16b9ba606307728f55",
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:2b987497190f0eb7b5ddbaade7acad2f9f60df58c2c04fb7d01b9ad91fcc600a"
    ]
  },
  "history": [
    {
      "created": "2021-05-21T00:09:54.387702796Z",
      "created_by": "/bin/sh",
      "comment": "FROM docker.io/library/centos:8"
    }
  ]
```
so, like the 'inspect' output of the image, the "history" section, but unlike the inspect output, also an explicit "parent" reference to the intended-to-be-squashed-out image.

**Comment by rhatdan** [comment]
Looks like the PR merged so this is fixed in the main branch.

**Comment by dmick** [comment]
Is there a tool that would allow me to apply this image info edit before I can access a new release of buildah, to ameliorate the problem early?

**Comment by nalind** [comment]
If you're not using any features that are specific to the docker format (HEALTHCHECK, ONBUILD, SHELL, HOSTNAME, DOMAINNAME, COMMENT), converting to OCI format somewhere along the way to drop things that the OCI format omits should work, since OCI also doesn't have a "parent" field in its config blob.
One option for doing that is to push to a `dir:` location using `--format oci`, and then to pus  from there to a registry using `skopeo copy`, or by pulling from that location using `buildah` and then pushing the just-pulled image.

**Comment by dmick** [comment]
push dir:, pull, tag, push remote with --format v2s2 worked.  I guess I have a workaround.
