### ISSUE TITLE
copy big files' performance buildah vs docker

### ISSUE THREAD

**Issue by meilier** [containers/buildah#3256]
I try to analysis the performance when building images with big files copied to image, and comparing the result with docker.
All the result was carried on my test cloud server 1 cpu 2g.

As a test example, files were generated by command below:
```
dd if=/dev/zero of=test200.img bs=1M count=200
dd if=/dev/zero of=test500.img bs=1M count=500
```
My dockerfile:
```
FROM centos:latest
COPY test200.img /

FROM centos:latest
COPY test500.img /

```

Below is the script to test the performance of buildah, change command buildah to docker to get docker build performance result.
```
total_time=0
buildah rmi test:v1
for i in {1..5};
do
    { time buildah bud -f Dockerfile -t test:v1 .; } 2> time.txt
    time=$(cat time.txt  |grep real|awk '{print $2}')
    minutes=${time%m*}
    seconds=${time#*m}
    seconds=${seconds%s}
    echo "build time" $i using $(echo "scale=3; $minutes * 60 + $seconds" | bc -l ) seconds
    total_time=$(echo "$minutes * 60 + $seconds + $total_time"| bc -l)
    buildah rmi test:v1
done
avg_time=$(echo "scale=3; $total_time / 5" | bc -l)
echo avg_time is $avg_time
```

The final result:
1. For 200MB file:

- buildah bud is 12.764s
- docer build  is 4.872s

2. For 500MB file:

- buildah bud is  28.619s
- docker build is 14.467s

Go in depth a little more, I found buildah copying the large file when exec COPY command in dockerfile first, then calling cp.Image() function provided by containers/image, which moving the large file another double times before committing to the final layer location. **Totally, buildah needs four copy times, and docker needs two instead.**

Is there any plan to improve the performance of buildah when building images with big files? Thanks~

**Comment by rhatdan** [comment]
What version of Buildah are you using?

@mtrmac @vrothberg @nalind PTAL

**Comment by meilier** [comment]
I build buildah from master on my ubuntu18.04 cloud server. @rhatdan 
```
root@VM-12-13-ubuntu:~# uname -a
Linux VM-12-13-ubuntu 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@VM-12-13-ubuntu:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@VM-12-13-ubuntu:~# buildah --version
buildah version 1.21.1-dev (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
root@VM-12-13-ubuntu:~#
```

**Comment by meilier** [comment]
Hi @rhatdan , I try to implement a new "NewImageSource GetBlob" pipe read from container layer, and then pipe write in "NewImageDestination PutBlob" to the final committed layer during buildah bud process, similar to docker build. And there may need  containers/storage switch from locking entire layer store to locking needed layer.[Allow GetStore() in read-only mode](https://github.com/containers/storage/issues/420)

As a result, we could cut down the copied times to only two.

Would it be all right? Is there any system design consideration I missed？

**Comment by rhatdan** [comment]
SGTM
Nalin what do  you think?

**Comment by rhatdan** [comment]
@nalind ^^

**Comment by mtrmac** [comment]
I’m not 100% sure what the exact situation is, or what the proposal is, just some hopefully relevant things to consider:

- If I understand the proposal, I think this will run into problems with deduplication. c/storage deduplicates on input, based on caller-provided ID, not _after_ creating the layer; so the container’s data must be converted to a tarball just to compute a digest and to see whether the layer already exists or whether we need to create a copy; I can’t see that it’s possible to just fully stream data from a container overlay to a layer on-disk, right now.
- Similarly the “copy” requires the source to create a manifest with a digest of the layer.
- Locking is certainly a worry, but I’m not an expert in this area.

These design concerns can probably be overcome with enough effort (and some undesirable API breakage?), but it doesn’t look quite trivial.

**Comment by meilier** [comment]
May be I should have put my issue in [containers/image](https://github.com/containers/image) which could make the issue clearer to understand.

As far as I konw, without flag "--layers" buildah build images without cache. But use or not use cache will not affect the behavior when first build with containers/image and containers/storage, in which case, cp.Image() function together with the methods of interface "ImageReference", NewImageSource and NewImageDestination, will create another two "temps" before commit containers' layer to final layer storage.

As a result, in some scenarios create bigger images more than 1G,  time use is longer obviously than docker.

**Comment by rhatdan** [comment]
There has been a couple of PRs that went in recently, and one pending in containers/storage that have shown great improvements in speed for builds, especially around committing layers.

**Comment by mtrmac** [comment]
To be explicit, https://github.com/containers/podman/issues/11236 is the other one tracking some work. But I haven’t taken the time to actually analyze either of them in detail myself; the two might be exact duplicates, or the same issue but different suggestions for improvement, or perhaps even quite different issues.

**Comment by kurt-google** [comment]
I can say that in containers/podman#11236 for my performance numbers time spent copying data is very small, about 10-20s of the profile as it was tested on a NVMe disk. On slower disks there may be different bottlenecks then what I was notcing.

**Comment by rhatdan** [comment]
I believe this one is fixed now, so I am going to close, reopen if I am mistaken.
