### ISSUE TITLE
`buildah` fails when `REGISTRY_AUTH_FILE` doesn't exist

### ISSUE THREAD

**Issue by rcny** [containers/buildah#3259]
Hello!

Setting `REGISTRY_AUTH_FILE` to a non-existent file will result in `buildah` failing to operate with public registries:

```
[root@dd836c415cc3 /]# env REGISTRY_AUTH_FILE=/tmp/non_existent_creds.json buildah pull docker.io/library/hello-world
error checking authfile path /tmp/non_existent_creds.json: stat /tmp/non_existent_creds.json: no such file or directory
```

Is this a feature or a bug?

Currently I resolve it with e.g. `env REGISTRY_AUTH_FILE= buildah pull docker.io/library/hello-world` for specific commands. Can't remove `REGISTRY_AUTH_FILE` at all because of #3216.

Running `1.20.1` from current `quay.io/buildah/stable` image.

**Comment by rhatdan** [comment]
I am thinking this is a bug.

**Comment by vrothberg** [comment]
I consider setting the env var as user-specified input (i.e., the counterpart of `--authfile`).

**Comment by rhatdan** [comment]
The thing is we do not need to fail until the user actually attempts to use the file, in that case.

**Comment by rhatdan** [comment]
For example the use case that this user was hitting was having it set within a container image, and only used when needed.  We would fail all the time.

**Comment by TriplEight** [comment]
I'm having the same issue with `buildah logout`, even when it wasn't logged in anywhere:
```
buildah logout --all
error checking authfile path /tmp/registry_auth.json: stat /tmp/registry_auth.json: no such file or directory
```

**Comment by TriplEight** [comment]
and with the workaround I'm getting the other misleading output:
```
env REGISTRY_AUTH_FILE= buildah logout docker.io
Not logged into docker.io
```

**Comment by rhatdan** [comment]
Why is this misleading?

**Comment by TomSweeneyRedHat** [comment]
I think the logout error is misleading as it doesn't indicate that the file doesn't exist.  From reading the message, I'd think the authfile existed, I just didn't have an entry in the authfile.

**Comment by rhatdan** [comment]
We treat REGISTRY_AUTH_FILE="" the same as we do not being set at all.
