### ISSUE TITLE
Changing architecture uses previous architecture for base image

### ISSUE THREAD

**Issue by Xenopathic** [containers/buildah#3271]
**Description**

I'm trying to create a cross-arch image using a base image pulled from Docker (`debian`), but I made a mistake with the architecture the first time round. I changed the architecture used in `buildah from`, but the cached image (with the wrong architecture) is used.

**Steps to reproduce the issue:**
1. `buildah from --arch arm64 debian`, confirm that the working container is arm64.
2. `buildah from --arch 386 debian`, the working container is still arm64 (and no image pull occurred).

**Describe the results you received:**

Incorrect architecture of subsequent working containers, in this example it is still arm64

**Describe the results you expected:**

Buildah should notice that the cached image has the wrong architecture and should fetch the right one.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/glinux-rodete-base-20210518.01.00,now 1.19.6+dfsg1-1 amd64 [installed,automatic]
buildah/glinux-rodete-base-20210518.01.00 1.19.6+dfsg1-1 i386
```

**Output of `buildah version`:**

```
Version:         1.19.6
Go Version:      go1.15.8
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.3
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_CODENAME=rodete
DISTRIB_DESCRIPTION="Debian GNU/Linux rodete"
DISTRIB_ID=Debian
DISTRIB_RELEASE=rodete
GOOGLE_CODENAME=rodete
GOOGLE_ID=Goobuntu
GOOGLE_RELEASE="rodete 20210518.01.00RL"
GOOGLE_ROLE=laptop
GOOGLE_TRACK=stable
PRETTY_NAME="Debian GNU/Linux rodete"
NAME="Debian GNU/Linux"
ID=debian
VERSION_CODENAME=rodete
VERSION_ID=rodete
HOME_URL="https://go/glinux"
SUPPORT_URL="https://go/techstop"
BUG_REPORT_URL="https://go/techstop"
```

**Output of `uname -a`:**

```
Linux rmccorkell 5.10.28-1rodete1-amd64 #1 SMP Debian 5.10.28-1rodete1 (2021-04-30) x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
<no such file>
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

I can't reproduce with Buildah v1.21.0.  We had some bigger changes in the image code which seems to have fixed that issue.

**Comment by Xenopathic** [comment]
Thanks for confirming! I'll wait for my distro to update to 1.12, in the meantime the workaround is to delete the existing cached image before running `buildah from` with a different arch.
