### ISSUE TITLE
New "copy" helper is going to wreak havoc

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3297]
The new `copy` helper added in #3220 is going to cause a huge number of problems:
* buildah-bud tests under podman will no longer work, because they don't build or know about this tool
* Fedora and RHEL gating tests are all going to fail, because the tool is not packaged in RPMs

If the benefits of the new tool outweigh these costs, someone will need to fix all of the above:
* podman: I have no idea how to fix that. And I'm going to be on PTO, so I leave this as SEP (Someone Else's Problem)
* gating tests:
  * need to eliminate hardcoded references to `copy` in `helpers.bash`, in favor of redirection via envariable; see sample diff below
  * need to fix specfiles (Fedora, RHEL, Centos, etc) to include `buildah-copy-helper` (or some other nonconflicting name) in the `buildah-tests` subpackage
  * need to fix `tests/test-buildah.yml` (again in Fedora, RHEL, Centos) to define the magic new envariable

```diff
diff --git a/tests/helpers.bash b/tests/helpers.bash
index 2179926a..24b52a38 100644
--- a/tests/helpers.bash
+++ b/tests/helpers.bash
@@ -2,6 +2,7 @@

 BUILDAH_BINARY=${BUILDAH_BINARY:-$(dirname ${BASH_SOURCE})/../bin/buildah}
 IMGTYPE_BINARY=${IMGTYPE_BINARY:-$(dirname ${BASH_SOURCE})/../bin/imgtype}
+BUILDAH_COPY_HELPER=${BUILDAH_COPY_HELPER:-$(dirname ${BASH_SOURCE})/../bin/copy}
 TESTSDIR=${TESTSDIR:-$(dirname ${BASH_SOURCE})}
 STORAGE_DRIVER=${STORAGE_DRIVER:-vfs}
 PATH=$(dirname ${BASH_SOURCE})/../bin:${PATH}
@@ -96,18 +97,18 @@ function _prefetch() {
         fname=$(tr -c a-zA-Z0-9.- - <<< "$img")
         if [ -d $_BUILDAH_IMAGE_CACHEDIR/$fname ]; then
             echo "# [restoring from cache: $_BUILDAH_IMAGE_CACHEDIR / $img]" >&2
-            copy $COPY_OPTS dir:$_BUILDAH_IMAGE_CACHEDIR/$fname containers-storage:"$img"
+            ${BUILDAH_COPY_HELPER} $COPY_OPTS dir:$_BUILDAH_IMAGE_CACHEDIR/$fname containers-storage:"$img"
         else
             rm -fr $_BUILDAH_IMAGE_CACHEDIR/$fname
             echo "# [copy $COPY_OPTS docker://$img dir:$_BUILDAH_IMAGE_CACHEDIR/$fname]" >&2
             for attempt in $(seq 3) ; do
-                if copy $COPY_OPTS docker://"$img" dir:$_BUILDAH_IMAGE_CACHEDIR/$fname ; then
+                if ${BUILDAH_COPY_HELPER} $COPY_OPTS docker://"$img" dir:$_BUILDAH_IMAGE_CACHEDIR/$fname ; then
                     break
                 fi
                 sleep 5
             done
             echo "# [copy $COPY_OPTS dir:$_BUILDAH_IMAGE_CACHEDIR/$fname containers-storage:$img]" >&2
-            copy $COPY_OPTS dir:$_BUILDAH_IMAGE_CACHEDIR/$fname containers-storage:"$img"
+            ${BUILDAH_COPY_HELPER} $COPY_OPTS dir:$_BUILDAH_IMAGE_CACHEDIR/$fname containers-storage:"$img"
         fi
     done
 }
```

**Comment by rhatdan** [comment]
@edsantiago do we still need a fix here?

**Comment by edsantiago** [comment]
Oh hell yes. One of my bullet points is addressed (hardcoded "copy") but specfile and gating-test changes are super-critical right now. Then, later, if you ever want to vendor this into podman, fixes for the buildah-bud-under-podman tests. I can look into this on my return, June 28. Until then, or until someone fixes all of those, all gating tests are going to fail.

**Comment by rhatdan** [comment]
Could you create a PR to fix the changes you want?

**Comment by edsantiago** [comment]
AFAIK this is still not fixed in RHEL; leaving open so I can refer to it as a guideline when the time comes to fix it in RHEL
