### ISSUE TITLE
Copy slow where it really shouldn't be

### ISSUE THREAD

**Issue by deltarod** [containers/buildah#3299]
**Description**

I am currently using Podman to build my web application [https://github.com/PeakLearner/PeakLearner/tree/2.0refactor](https://github.com/PeakLearner/PeakLearner/tree/2.0refactor). I am having copy steps take 10-15 minutes on a lot of smaller files. I have tried using .dockerignore to speed up the process to no avail. These copy steps could be changed to a git clone (same files regardless) which speeds up the whole process by quite a bit but isn't really optimal.

**Steps to reproduce the issue:**
1. `git clone --branch 2.0refactor https://github.com/PeakLearner/PeakLearner.git`
2. `cd PeakLearner`
3. `podman build .`

**Describe the results you received:**

Slow Copy Step for step 17 (COPY ./jbrowse/)

**Describe the results you expected:**

Fast Copy Step

**Output of `rpm -q buildah` or `apt list buildah`:**

```
tristan@tlinux:~/Research/PL2.0$ apt list buildah
Listing... Done
buildah/groovy-updates,now 1.15.2-1ubuntu2.2 amd64 [installed,automatic]
N: There is 1 additional version. Please use the '-a' switch to see it
```

**Output of `buildah version`:**

```
Version:         1.15.2
Go Version:      go1.14.7
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.5.2
Git Commit:      
Built:           Wed Dec 31 17:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.7
Built:        Wed Dec 31 17:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
tristan@tlinux:~/Research/PL2.0$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

**Output of `uname -a`:**

```
Linux tlinux 5.8.0-55-generic #62-Ubuntu SMP Tue Jun 1 08:21:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
N/A
```

**Comment by deltarod** [comment]
Seems I forgot to exclude some files, Sorry about this!

**Comment by nalind** [comment]
I'm glad it's working better.  Before 1.16.x, we were much slower handling COPY with `.dockerignore` files than without them, so when you get to a later version you should hopefully see additional improvements.
