### ISSUE TITLE
buildah add ignores the implicit .containerignore

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/buildah#3303]
I do
`strace -fs2048 buildah add --contextdir /home/d/chroot abc / /`

The documentation of [buildah add](https://github.com/containers/buildah/blob/master/docs/buildah-add.md) says:
```
--ignorefile

Path to an alternative .containerignore (.dockerignore) file. Requires --contextdir be specified.
```

My reading of the above text is, that the aforementioned call will try to open the default `.containerignore` file: contextdir is provided and the default `.containerignore` file is not overwritten.

strace shows that neither .dockerignore nor .containerignore are opened in any directory, when --ignorefile is skipped.

I guess the same happens for `buildah copy`.

**buildah version 1.21.0 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)**

**Comment by rhatdan** [comment]
Since PR Merged, I am going to close.
