### ISSUE TITLE
Document that buildah add --contextdir requires parameter

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/buildah#3304]
The documentation of [buildah add](https://github.com/containers/buildah/blob/master/docs/buildah-add.md) and [buildah copy](https://github.com/containers/buildah/blob/master/docs/buildah-copy.md) suggests, that the options **--chmod**, **--chown**, and **--from** require parameter.  But at the same time, the documentation implies, that the options **--add-history**, **--contextdir**, **--ignorefile** and **--quiet** do not require parameter.  This implication is not correct.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix the documentation?

**Comment by dilyanpalauzov** [comment]
The **--add-history** description in unclear, as the current wording suggests that the default is `--add-history false` and the opposite is `--add-history true`. This does not make sense.

**Comment by rhatdan** [comment]
That is the way all boolean options work.

You can specify --add-history or --add-history=false or --add-history=true.

**Comment by rhatdan** [comment]
Since https://github.com/containers/buildah/pull/3319 merged I am going to close .
