### ISSUE TITLE
push: export .zstd per command line option

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/buildah#3321]
`buildah push imagename oci-arichive:zzz.tar` produces a tar file. The tar file contans a blobs/sha256 directory. One of the files in that directory has the content
```json
{
  "schemaVersion":2,
  "config":{
    "mediaType":"application/vnd.oci.image.config.v1+json", 
    "digest":"sha256:68558a5fe468cfc20b609e3bbb0ab4a93570fb193efe0f66b0672c2c8efe3181",
    "size":1120
  },
  "layers":[{
    "mediaType":"application/vnd.oci.image.layer.v1.tar+gzip",
    "digest":"sha256:478ae127a53387d119b5d2c1f64f05ee3d1693efc2ea7bc2b68fd7f68f2b2233",
    "size":40198040
  }]
}
```

The blobs/sha256/478ae127a53387d119b5d2c1f64f05ee3d1693efc2ea7bc2b68fd7f68f2b2233 file is in .tar.gz format.

• Add support for the other [valid layer formats](https://github.com/opencontainers/image-spec/blob/master/layer.md): `application/vnd.oci.image.layer.v1.tar` and `application/vnd.oci.image.layer.v1.tar+zstd` per command line option.

Exporting the image as uncompressed blob has the advantage, that the resulting tar file can be compressed e.g. by xz, which is better than gz and moreover, compressing it only with xz is better than first gz compressing and then compressing the result with xz.

Likewise for the `buildah push oci:.` export

**Comment by dilyanpalauzov** [comment]
`buldah push -D oci(-archive)` does skip the gzip compression.  So I am asking just to add ZSTD compression per command-line option.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
have you tried `skopeo copy`?  Would that work for you?

**Comment by dilyanpalauzov** [comment]
`scopeo copy` does it, but I am not impressed:

`skopeo copy --dest-compress-format=zstd --dest-compress-level=20 containers-storage:localhost/abc oci-archive:t.tar` produces in my case a 21470400bytes file.

The manual page of skopeo-copy says:
```
       --dest-compress-level  format  Specifies  the compression level to use.  The value is specific to the compression algorithm used, e.g. for zstd the accepted values are in the range 1-20 (inclusive), while for gzip it is 1-9 (inclusive).
```
`zstd --help` prints:
```
 -#     : # compression level (1-19, default: 3)
```
So for whatever reason the one tool has a compression parameter range [1,19], the other has range [1,20].

`skopeo copy --dest-compress-format=zstd --dest-compress-level=19 containers-storage:localhost/abc oci-archive:t19.tar` and `skopeo copy --dest-compress-format=zstd --dest-compress-level=20 containers-storage:localhost/abc oci-archive:t.tar` produce images of the same size: 30382080bytes.


`buildah push localhost/abc oci-archive:r.tar` produces 40186880bytes file.  `buildah push -D localhost/abc oci-archive:m.tar` produces 95563776bytes file.  `xz -9k m.tar` produces 21470400bytes file.

The t.tar is already compressed by zstd and produces 30382080bytes.  Compressing it again with `zstd -19 -k t.tar` reduces it to 30065692 bytes.

Finally compressing with zstd the uncompressed export `zstd -19 -k m.tar ` produces m.tar.zstd of 25127680 bytes.

To sum up:
`skopeo copy --dest-compress-format=zstd --dest-compress-level=20 containers-storage:localhost/abc oci-archive:t.tar` produces 30382080 bytes file.

`buildah push -D localhost/abc oci-archive:m.tar && zstd -19 -k m.tar` produces a 25127576bytes file. (the last number is different from the zstd export number mentioned previously, apparently zstd like brotli produce for the same input slightly different outputs).

In any case, all forms of image exports in buildah, podman and skopeo shall support the same options.

There are many, many ways to export the same image, cf. `podman save` and `podman pull` serve in this regard the same purpose.  If one wants to export an image to a file /oci-directory and finds a way to do so, that person will not explore if different command serve the same purpose, but are more feature-rich.

**Comment by vrothberg** [comment]
> In any case, all forms of image exports in buildah, podman and skopeo shall support the same options.

I understand the desire but exposing _all_ these options in _all_ tools is not how they were meant to be used.  The main problem I see is decreased usability by pure information overload by all the options.  `skopeo copy` until now is the Swiss Army Knife for such kinds of tassks.

**Comment by rhatdan** [comment]
I am going to close this, and basically say use skopeo.
