### ISSUE TITLE
arm builds: architecture includes variant

### ISSUE THREAD

**Issue by vrothberg** [containers/buildah#3344]
As discussed in https://github.com/containers/podman/issues/10648, images built on ARM using Buildah may mix the variant and architecture in one field:
```
# podman inspect test-image | grep arch
                "io.balena.architecture": "armv7hf",
            "io.balena.architecture": "armv7hf",
```

Mixing the two into the architecture instead of using the variant field is leaving OCI compliance. The [image specification](https://github.com/opencontainers/image-spec/blob/859973e32ccae7b7fc76b40b762c9fff6e912f9e/config.md#properties) states that the mentioned architecture of an image should adhere to the [GOARCH](https://golang.org/doc/install/source#environment) values.  `armv7l` is _not_ a valid value.

Note that most container engines don't care, and `libimage` has since relaxed the arch checks significantly.

**Comment by nalind** [comment]
Where does `io.balena.architecture` come from?  Is it a label?  What does the image's config blob say at every step of the process that gets us from the base image to this one?

**Comment by rhatdan** [comment]
Since the question was never answered I am going to close.  Reopen if you want us to continue working on this issue and want to provide feedback.
