### ISSUE TITLE
apt-get not working with buildah in a container with id and group 1000:1000 (rootless mode)

### ISSUE THREAD

**Issue by jomeier** [containers/buildah#3345]
Hi,

we use Buildah (v1.21.0) in a container with user id 1000 and group id 1000.

Our Dockerfile tries to install a package with apt-get and that fails with this error message:

```
$ buildah --authfile=/mnt/dockerfile/.dockerconfigjson --storage-driver=vfs bud --format=docker --tls-verify=false --no-cache -f Dockerfile -t ${IMAGE} .
STEP 1: FROM ubuntu:18.04
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:18.04...
Getting image source signatures
Copying blob sha256:25fa05cd42bd8fabb25d2a6f3f8c9f7ab34637903d00fd2ed1c1d0fa980427dd
Copying config sha256:7d0d8fa372249c6a1de9868ad62af9a14aaae2a2b17da867d8fad099a637fd0f
Writing manifest to image destination
Storing signatures
STEP 2: RUN id
uid=0(root) gid=0(root) groups=0(root)
STEP 3: RUN apt-get update
E: setgroups 65534 failed - setgroups (22: Invalid argument)
E: setegid 65534 failed - setegid (22: Invalid argument)
Reading package lists...
E: setgroups 65534 failed - setgroups (22: Invalid argument)
E: setegid 65534 failed - setegid (22: Invalid argument)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (22: Invalid argument)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (22: Invalid argument)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
subprocess exited with status 100
subprocess exited with status 100
error building at STEP "RUN apt-get update": exit status 100
time="2021-06-27T20:49:11Z" level=error msg="exit status 100"
```

```
cat /etc/subuid
build:2000:50000

cat /etc/subgid
build:2000:50000
```

What happens here? How can we fix that?

Thank you and greetings,

Josef

**Comment by jomeier** [comment]
https://askubuntu.com/questions/755329/lxc-unprivileged-container-apt-get-fails-to-download-anything-inside

Should we set /etc/subuid and /etc/subgid to

```
build:2000:65535
```

instead to include the gid of _apt (65534) ?

**Comment by jomeier** [comment]
I patched buildah stable image with the extended subuid and subgid and now it works.

This should land in buildah stable if possible. What do you think @TomSweeneyRedHat ?

**Comment by rhatdan** [comment]
No the issue is users attempting to use buildah without root only have 65k UIDs to use.  It would probably be better to use something like

$ echo build:2000:65536 > subuid
$ podman run -v $PWD/subuid:/etc/subuid:ro -v $PWD/subUID:/etc/subgid:ro ...

**Comment by jomeier** [comment]
I use Buildah not Podman.

The default is 50000 uids. For apt we need uid 65534 therefore 64k uids should be the default in the buildah image.

**Comment by rhatdan** [comment]
Sure, but this will not allow you to run by default in rootless users. Since they are only assigned 64k by default.  You would need 65k + 2000 for a user to run your container in a rootless mode.

I think someone should talk to apt about why they need that big UID.

**Comment by rhatdan** [comment]
Since this is something you can fix in your build image, I am going to close.

**Comment by jomeier** [comment]
I don't unterstand why you accept that users can't use apt-get (Debian/Ubuntu Package manager) in Buildah builds with the recent images.

It simply breaks builds on OKD 4.

I can't believe that we are the only ones with this problem.

**Comment by rhatdan** [comment]
Buildah does not break build on any package builder.  The Buildah image example in quay.io/buildah/stable has limitations for rootless containers.  When run in a non-privileged locked down container.

Rootless users by default only have 64k UIDS, if running so there is no way to run a container that wants to reserve another 64k UIDs in rootless mode.

Now maybe we could create two users in the buildah image, buildah and buildahfull, where buildahfull has 64k UIDs available but will only work as rootfull  podman.

**Comment by jomeier** [comment]
You mean I can't run more than one rootless container that reserves 64k UIDs on a single Kubernetes Node?

Currently there are already 50k UIDs reserved in latest rootless buildah images. Because of that I don't understand, where this 50k come from and why the UID count is not simply increased to 64k.

Do you have a link for me that describes this problem?

**Comment by rhatdan** [comment]
You can have 4294967295 UIDS on a linux system, so you can go to town. no problem.  This is where I am getting confused.  I built the podman image to be able to run with rootless users. Nothing to do with k8s.  A rootless user is give 64k, by default.  If the Podman image requires 64k to run, then it can not be run by a rootless user.

If you run a privileged container with k8s then it can use as many UIDs as it wants up to 4294967295.

The podman image in stable is just an example, not the end all an be all.  I would recommend that you change the /etc/subuid and /etc/subgid file in it if you want to run rootless podman.

You can also run rootfull podman in a container, which would not use the user namespace and would thus be able to use as many UIDs as you want.
