### ISSUE TITLE
Running sudo podman build fails with error running container: error creating container for in Travis CI with registry.fedoraproject.org/fedora:34 image

### ISSUE THREAD

**Issue by adelton** [containers/buildah#3371]
/kind bug

**Description**

Running `sudo podman build` fails with `error running container: error creating container for ...` in Travis CI.

**Steps to reproduce the issue:**

1. Have Dockerfile.fedora-34 which says
```
FROM registry.fedoraproject.org/fedora:34
RUN dnf install -y --setopt=install_weak_deps=False /usr/sbin/init
```
2. In .travis.yml, install podman 3.1.2-1 with
```
. /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman containernetworking-plugins
```
and run
```
- sudo podman build -t systemd -f Dockerfile.fedora-34 .
```

**Describe the results you received:**

https://travis-ci.com/github/adelton/freeipa-container/jobs/501611053
```
STEP 2: RUN dnf install -y --setopt=install_weak_deps=False /usr/sbin/init
error running container: error creating container for [/bin/sh -c dnf install -y --setopt=install_weak_deps=False /usr/sbin/init]: sd-bus call: Connection reset by peer
: exit status 1
Error: error building at STEP "RUN dnf install -y --setopt=install_weak_deps=False /usr/sbin/init": error while running runtime: exit status 1
The command "$docker build -t systemd -f Dockerfile.$dockerfile ." exited with 125.
```

**Describe the results you expected:**

No failure, image built fine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

I did not run it but it's podman 3.1.2-1 installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04.

**Output of `podman info --debug`:**

I did not run it but it's podman 3.1.2-1 installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

I did not run it but it's podman 3.1.2-1 installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is Travis CI Ubuntu 20.04 VM.

**Comment by rhatdan** [comment]
Since we have had no futher input, closing, reopen if more input is available.
