### ISSUE TITLE
Dockerfile spec?

### ISSUE THREAD

**Issue by vsoch** [containers/buildah#3376]
Heyo! Someone on the OCI list mentioned that there might have been an effort here (alongside the buildah project) to create a Dockerfile spec. Is that true? I was thinking it would be useful to have a vendor neutral spec for the Dockerfile (and associated things like a caching strategy).

**Comment by vrothberg** [comment]
Thanks for reaching out, @vsoch!

I am not aware of such an effort.

>  I was thinking it would be useful to have a vendor neutral spec for the Dockerfile (and associated things like a caching strategy).

A shared caching strategy sounds interesting and it makes sense to have a spec before such a strategy.

@rhatdan PTAL

**Comment by rhatdan** [comment]
I am aware of no such effort, although it would be nice.  I am not sure if Docker would go along with this though.

**Comment by vsoch** [comment]
Ah ok, thanks for looking into it! I'll bring discussion back to the OCI list and see if maybe this was somewhere else. If you do hear anything please let me know.

**Comment by vrothberg** [comment]
@vsoch, thanks for pushing this forward.  I'll keep an eye on the OCI lists since I am interested in helping getting a spec on that.
