### ISSUE TITLE
Efficient building for CI with distributed cache and direct registry tagging

### ISSUE THREAD

**Issue by george-harness** [containers/buildah#3382]
Building images in the context of CI build execution are very often completely fully or partially repetitive. Unlike a development environment where every next execution is in the same environment from where already cached layers could be obtained - in CI the cache to works, it needs to be distributed.

What can be done better (assuming that --cache-from is already implemented):
1. Store the layers in remote object storage to obtain from multiple environments.
2. Avoid obtaining layers that are not needed when the command was changed. If we download the cache images in advance we will download layers that might not be used during the build if the command changed.
2. Avoid the need of tracking predecessor images. That is actually not a trivial task as it might seem. In the context of a PR-based development process (non-linear execution) and/or multi-stage image build pushing and maintaining a list of all images that will provide a comprehensive list of layers for cache purposes is a tedious problem to solve.
3. In CI is common to build images to push to a registry without local use. If the image has no changes at all, it will be great optimization this to result in no downloading at all, but simply tagging the image accordingly directly in the registry.

**Comment by TomSweeneyRedHat** [comment]
Ping @rhatdan @nalind @fatherlinux @mtrmac @vrothberg

**Comment by nalind** [comment]
Hi!  Thanks for reaching out.

At the moment, we don't have any form of `--cache-from` implemented; a first attempt would probably pull the specified image, at which point we can reuse its layers, but not much else.  The cache evaluation logic currently uses the history in a candidate image's config blob as the main point of comparison to what we think we're about to do the work of creating, and pulling the indicated image only gives us the config blob for the image produced by the final instruction in the build that produced it.  If the indicated cache image is the result of where we are plus a dozen steps, the current logic doesn't have a candidate for every intermediate step to match against, so it's unlikely to ever match the indicated cache image.

I like the idea of being able to use a distributed cache, whether for layer contents or images as a notional whole.  How we'd wire one in through our dependencies which handle most of our image reading/writing/pulling/pushing is not something I've personally sat down and tried to figure out, so I'd welcome any insights you can share.

**Comment by george-harness** [comment]
The usual approach for a cache is to abstract the problem to a (key, value) storage. That is even more true when we have distributed cache.

Say this is available from the interface like:
```
LayerProvider {
 Layer get(key);
 void set(key, value);
}
```

We need to find a reliable way to create a key for every layer that we would like to add to/obtain from the cache. It seems to me that it would be relatively easy to come up with the key for the layer by simply hashing the base layer sha and the current command.

Using this approach will eliminate the need for iterating over layers belonging to images that could be expensive in the context of distributed cache. It also will eliminate the need to track predecessor images, which in the context of CI could be non-trivial.

Note that we can implement the LayerProvider interface on top of the container registry repo and any S3 object storage etc allowing for flexibility for the users. For the local cache it might require some adaptation, but would be as easy as creating a map between the key and the local layers to implement the same interface for it.

I have no clear idea about how 4. (the noop tagging) can be solved. Calculating a complete image key without obtaining involved layers seems significantly harder. Maybe if we extend the provider interface with

```
LayerProvider {
  LayerMeta getMeta(key);
 ...
}
```

We might be able to store enough detail to evaluate if the commands will produce the same layer - say hash for the files that are copied for a copy command for example.

**Comment by george-harness** [comment]
@nalind, @TomSweeneyRedHat, team

I put a very raw (it works) implementation of phase 1 of the approach I proposed above: https://github.com/harness/buildah/commit/0d11da9b7c4caec21d358637282b7a7f00ad0fb1

It essentially creates a LayerProvider object that creates a map between layerKey and cacheID. When the cacheID is needed it calculates in a symmetrical way the key for the layer that needs to be built and looks up in the map.

I need to put the manifest and a few other properties before we make this distributed, as I said this is very raw just to give you an idea and opportunity for early feedback.

Thanks in advance

**Comment by george-harness** [comment]
For my second phase of distributed cache, I need to be able to "package" the layer for storing and I also should be able to load this package and install it in the local store. I will appreciate some starting pointers.

**Comment by george-harness** [comment]
@nalind @TomSweeneyRedHat @rhatdan @fatherlinux @mtrmac @vrothberg

I start working on phase 2 - creating file_layer_provider - it supposes to store the layers (layer image) into a file location. It will be helpful mostly for testing, but also it will allow for distributed cache through shared volumes.

my current state is in https://github.com/harness/buildah/tree/file_local_layer_provider

I would really appreciate it if someone with experience gives me some more detailed guidance on how to build that.

policyContext, destinationRef, options, that is a lot to wrap my head around by myself.

P.S. Can we finalize the previous PR.

**Comment by george-harness** [comment]
the BlobCache (pkg/blobcache/blobcache.go) seems like a great idea and combining it with the directory can do exactly what I need to create distribute file system cache.

Unfortunately, line 509 makes a call back to the base destination (I assume to obtain the BlobInfo).

newBlobInfo, err := d.destination.PutBlob(ctx, stream, inputInfo, cache, isConfig)

This seems to completely invalidate the point of having cache for the blobs, because the original will make its own copy as well.

What can be done to eliminate that issue?

**Comment by mtrmac** [comment]
Are you differentiating between cache of build products, as layers (expanded filesystems), and cache of compressed blobs?

**Comment by george-harness** [comment]
No. I am storing all intermittent images in a separate file system location that could have external volume. As part of this though I copy a lot of images that share a lot of layers and other blobs. This is why deduplication of the blobs is critically important.

**Comment by george-harness** [comment]
@mtrmac you can check what I am doing at https://github.com/harness/buildah/tree/file_local_layer_provider.

I just merged the latest code I have.

**Comment by mtrmac** [comment]
@george-harness I’m afraid I’m unfamiliar with these parts of the codebase and for the most part not the one to discuss the design with. I’m just somewhat familiar with the blob cache, and the point of that is to avoid re-pushing layers of parent images to a registry (no FS scan, no tarball creation, no compression and the relevant CPU usage), even if the built product is pushed to a registry different from the parent. But pushing the image to the registry is the essential part; it’s not at all a mistake that that does happen.

Quickly skimming `FileLayerProvider`, I suppose that could work for a prototype, but for a production version it seems way too expensive to copy _full images_ using the `dir:` transport’s format, every time, with no deduplication.

**Comment by george-harness** [comment]
@mtrmac Let me know if I understood this correctly.

The blob cache is not there to be an alternative of the final storage, but to preserve an intermittent state of the blob, this way the next time the same blob is requested these work is not done again? The same blob cache can be added on top of multiple destinations and the work will be saved if the preparation work is the same?

I have the several options:
1. Extend the blob cache to support alternative scenario. Essentially not making the call to the original destination. Relatively easy to do with a flag. 
   1.a Calculate the blobInfo in the blob cache
   1.b. Extending the Description interface to provide BlobInfo independently of the PutBlob - seems a big change in a lot of libraries.
2. Change the directory transport to be noop for a PutBlob.
   2.a. It also coming from containers/image it seems a big change.
   2.b. I can create a copy/paste version of it to accommodate for the noop behavior.
3. Create a my own destination that combines the functionality from directory and blob cache - a lot of copy/paste

In this context I see a lot of the same people in the containers/image, i hope you own it as well.

Team @nalind @TomSweeneyRedHat @rhatdan @fatherlinux @mtrmac @vrothberg, please advice.

**Comment by flouthoc** [comment]
> Building images in the context of CI build execution are very often completely fully or partially repetitive. Unlike a development environment where every next execution is in the same environment from where already cached layers could be obtained - in CI the cache to works, it needs to be distributed.

`--cache-from` is now implemented with contemporary `--cache-to` which allows end users to distribute expensive cache intermediate to different sources and re-use them in CI builds here: https://github.com/containers/buildah/pull/4118

I'm closing this issue but we can always re-open if something is unresolved :) 

Also issue heavily overlaps with https://github.com/containers/buildah/issues/620

Thanks
