### ISSUE TITLE
Matrix / IRC room

### ISSUE THREAD

**Issue by lsm5** [containers/buildah#3386]
Not an upstream issue

The matrix room `#buildah:matrix.org` seems to be bridged to the freenode #buildah channel. It has an outdated version mentioned in the description and AFAICT, it's a ghost town.

`#podman:matrix.org` has alternate addresses `#skopeo:matrix.org` and `#crun:matrix.org`, so if people join those alternate addresses, they reach `#podman:matrix.org`. We could add `#buildah:matrix.org` as an additional alternate address.

@TomSweeneyRedHat @nalind @rhatdan @umohnani8 @vrothberg if this is ok with you, please give this a :+1: and then I will check with matrix support to have that matrix room deleted, and use `#buildah:matrix.org` to redirect to `#podman:matrix.org`.

**Comment by vrothberg** [comment]
:+1:

**Comment by nalind** [comment]
:+1:

**Comment by lsm5** [comment]
`#buildah:matrix.org` now points to `#podman:matrix.org` :) . Closing..
