### ISSUE TITLE
Add aliases "destination" and "dst" for "target" mount argument

### ISSUE THREAD

**Issue by mixedCase** [containers/buildah#3396]
Docker's BuildKit [allows using](https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag) the words `dst` and `destination` as alternatives to the word `target` for specifying a path when mounting a secret. What's more, `dst` is the one used in one of their most visible documentation pages for BuildKit: https://docs.docker.com/develop/develop-images/build_enhancements/

Buildah/Podman currently only allows `target`, resulting in the following error when running Dockerfiles with the alternatives:

```
error building at STEP "RUN --mount=type=secret,id=npmrc,dst=/app/.npmrc,uid=1000 npm ci": error resolving mountpoints for container "c1a3d8d6db85aa69adb3be297114dd0dbd8aa67f25a519c3ef7f688f292f3fd6": secret should have syntax id=id[,target=path,required=bool,mode=uint,uid=uint,gid=uint
```

For compatibility purposes, it'd be nice to have these alternatives available in Buildah/Podman.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?

**Comment by mixedCase** [comment]
@rhatdan Just tried to, but I was put off by the wall of text of requirements in the PR boilerplate.

Here's the patch:

```
diff --git a/run_linux.go b/run_linux.go
index 4a435255..81af8ee6 100644
--- a/run_linux.go
+++ b/run_linux.go
@@ -2334,7 +2334,7 @@ func getSecretMount(tokens []string, secrets map[string]string, mountlabel strin
                switch kv[0] {
                case "id":
                        id = kv[1]
-               case "target":
+               case "target", "dst", "destination":
                        target = kv[1]
                case "required":
                        required, err = strconv.ParseBool(kv[1])
```

**Comment by rhatdan** [comment]
Chicken, thanks.
