### ISSUE TITLE
buildah fails under centos-7 when run inside official container

### ISSUE THREAD

**Issue by drawks** [containers/buildah#3405]
**Description**

When attempting to build a very trivial container using the official container image `quay.io/buildah/stable` being run under docker on centos-7 I always get an error like:
```
error building at STEP "ADD helloworld /usr/local/bin": error mounting build container "f58c0633d87dfdebd9d148a5d6007d0578bb435693217ff7e0c69022282b7d6f": failed to canonicalise path for "/var/lib/containers/storage/overlay/b6f95078d6c6477a9f2a93e3adc05e186696444d4969a9f496cfd3a072c6d80d/merged": lstat /var/lib/containers/storage/overlay/b6f95078d6c6477a9f2a93e3adc05e186696444d4969a9f496cfd3a072c6d80d/merged: invalid argument
```
I've read through all the existing issues that mention an error like this and I've been unable to resolve the problem. I've attempted to replicate the exact setup on a debian buster box and it works fine. I see plenty of comments online that indicate that centos-7 should be a supported platform for running the buildah container. This failure apparently has something to do with the overlay storage drive as running with `--storage-driver vfs` everything works, but with a big performance penalty.

**Steps to reproduce the issue:**
1. Create a fresh centos-7 VM (I used vagrant)
2. Update all packages on the centos-7 vm and reboot to ensure you have latest kernel
3. Install `docker-ce` from official docker yum repository
4. run `echo 15000 |sudo tee /proc/sys/user/max_user_namespaces` to enable use namespaces
5. create a basic `Dockerfile` like
```
from alpine
ADD helloworld /usr/local/bin
ENTRYPOINT "/usr/local/bin/helloworld"
```
6. create `helloworld`
```
#!/bin/bash
echo "hello world"
```
7.  Attempt to build the container like:
```
docker run -ti --security-opt seccomp=unconfined -w /build -v $PWD:/build --device /dev/fuse:rw -v$PWD:/mnt -w /mnt --rm quay.io/buildah/stable buildah bud .
```

**Describe the results you received:**

```
[vagrant@localhost ~]$ docker run -ti --security-opt seccomp=unconfined  -w /build -v $PWD:/build --device /dev/fuse:rw -v$PWD:/mnt -w /mnt --rm quay.io/buildah/stable buildah bud .
STEP 1: FROM alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 5843afab3874 done
Copying config d4ff818577 done
Writing manifest to image destination
Storing signatures
STEP 2: ADD helloworld /usr/local/bin
error building at STEP "ADD helloworld /usr/local/bin": error mounting build container "fadb31259b92248b68a36310fbaa5094ddba85471a19d70152f4f03eeb7df2dc": failed to canonicalise path for "/var/lib/containers/storage/overlay/6cdc9b328baff6ee8a09d6845d2d44075da27446c434d5a64fd73fe33f8138ed/merged": lstat /var/lib/containers/storage/overlay/6cdc9b328baff6ee8a09d6845d2d44075da27446c434d5a64fd73fe33f8138ed/merged: invalid argument
```

**Describe the results you expected:**

I would expect a successful container built on top of alpine with a single basic shellscript as it's entrypoint.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.21.0-1.fc34.x86_64
```

**Output of `buildah version`:**

```
Version:         1.21.0
Go Version:      go1.16.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.12.0
Git Commit:
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.9.2009 (Core)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
"/var/lib/shared",
]
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0"
[storage.options.thinpool]
```

**Comment by drawks** [comment]
After trying all sorts of non-sense trying to make this work I've come to the conclusion that some feature in the kernel is missing in centos-7 that breaks however buildah/podman is trying to use the fuse-overlay filesystem. Ultimately upgrading my test vm to use the fedora-32 kernel (5.6 something) made everything miraculously start working. 

It would be good if the dependency on the kernel version/features was spelled out explicitly somewhere prominent, RHEL/centos 7.x is still a major enterprise distro in heavy use.

Thanks

**Comment by rhatdan** [comment]
I have no idea where we would document this?  I realize that RHEL7/Centos7 are still out there.  But we have stopped updating packages on these distros since podman 1.9 release.  We have moved on to RHEL8/Centos 8/Centos Stream.
We recommend for using advanced features of container tools to use the latest versions of the OS, so we can take advantage of newer kernel features.

**Comment by drawks** [comment]
> I have no idea where we would document this?

Perhaps an assertion and a sensible error message? Anything is better than wasting time trying to make something work which will never work.

Actually while trying to locate a good place to document a warning, I did find a warning! At the bottom of the following page... https://github.com/containers/buildah/tree/main/contrib/buildahimage

And sure enough, when I build the container based on centos-7 instead of f32 it does work as intended/described. So I guess this issue can be marked as resolved. It would be nice if the github ci also triggered build/staging of the centos-7 based container into quay/redhat registries and perhaps the description field at https://quay.io/repository/buildah/stable could include a note about it not working with rhel/centos 7.x kernels along with a pointer to the correct container that does work.

**Comment by rhatdan** [comment]
Please open PRs where you would like the documentation changed.
