### ISSUE TITLE
podman build fails as rootless user if VOLUME >1 or <4 sub directories

### ISSUE THREAD

**Issue by Aight25** [containers/buildah#3408]
**Description**

podman build fails when running as a rootless user and trying to create volumes with a mount point of >1 or <4 sub directories. Example:
VOLUME /test01/test02

or
VOLUME /test01/test02/test03

It works with
VOLUME /test01
or
VOLUME /test01/test02/test03/test04

Note
With a rootfull user (root), this works

**Steps to reproduce the issue:**
1. Run as rootless podman user
2. Create Dockerfile / Containerfile with the following information:

FROM registry.fedoraproject.org/fedora:latest

VOLUME /bempa/arne
RUN mount

2. podman build -t whatever .

**Describe the results you received:**

STEP 1/3: FROM registry.fedoraproject.org/fedora:latest
STEP 2/3: VOLUME /bempa/arne
--> Using cache c63de2de1f11830c62621a64bbad35af25777d101991ee5a5e1981a663c4aac6
--> c63de2de1f1
STEP 3/3: RUN mount
error running container: error from /usr/bin/crun creating container for [/bin/sh -c mount]: mount `/var/lib/containers/storage/overlay-containers/7ccd5caeb83e532e858f3f16f5a9f36affb3d766337e216e871b242de5dcede7/userdata/overlay/246250828/merge` to `/bempa/arne`: Operation not permitted
: exit status 1
Error: error building at STEP "RUN mount": error while running runtime: exit status 1

**Describe the results you expected:**
[root@podmanvi01 build]# podman build -t whatever .
STEP 1/3: FROM registry.fedoraproject.org/fedora:latest
STEP 2/3: VOLUME /bempa/arne
--> 0c6c31d2c8e
STEP 3/3: RUN mount
fuse-overlayfs on / type fuse.fuse-overlayfs (rw,noatime,user_id=0,group_id=0,default_permissions,allow_other)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
tmpfs on /dev type tmpfs (rw,nosuid,seclabel,size=65536k,mode=755,uid=1003,gid=1003)
/dev/mapper/rhel_rhel8host01-root on /run/secrets type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)
fuse-overlayfs on /etc/hosts type fuse.fuse-overlayfs (rw,noatime,user_id=0,group_id=0,default_permissions,allow_other)
fuse-overlayfs on /etc/resolv.conf type fuse.fuse-overlayfs (rw,noatime,user_id=0,group_id=0,default_permissions,allow_other)
fuse-overlayfs on /run/.containerenv type fuse.fuse-overlayfs (rw,noatime,user_id=0,group_id=0,default_permissions,allow_other)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=231076,mode=620,ptmxmode=666)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=65536k,uid=1003,gid=1003)
cgroup2 on /sys/fs/cgroup type cgroup2 (ro,nosuid,nodev,noexec,relatime,seclabel,nsdelegate)
/dev/mapper/rhel_rhel8host01-root on /bempa/arne type xfs (rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota)
devtmpfs on /dev/null type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /dev/zero type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /dev/full type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /dev/tty type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /dev/random type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /dev/urandom type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
tmpfs on /proc/acpi type tmpfs (ro,relatime,seclabel,size=0k,uid=1003,gid=1003)
devtmpfs on /proc/kcore type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /proc/keys type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /proc/timer_list type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
devtmpfs on /proc/sched_debug type devtmpfs (rw,nosuid,seclabel,size=3960712k,nr_inodes=990178,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime,seclabel,size=0k,uid=1003,gid=1003)
tmpfs on /sys/firmware type tmpfs (ro,relatime,seclabel,size=0k,uid=1003,gid=1003)
tmpfs on /sys/fs/selinux type tmpfs (ro,relatime,seclabel,size=0k,uid=1003,gid=1003)
tmpfs on /sys/dev type tmpfs (ro,relatime,seclabel,size=0k,uid=1003,gid=1003)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
COMMIT whatever
--> 30a020909ad
Successfully tagged localhost/whatever:latest
30a020909ad42dd3c88e974fbf125b9c0ea918b63852f491e73e9bcb78d204f4

**Output of `rpm -q buildah` or `apt list buildah`:**

```

```

**Output of `buildah version`:**

```

```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 3.3.0-dev
```

**Output of `cat /etc/*release`:**

```
Fedora release 35 (Rawhide)
```

**Output of `uname -a`:**

```
Linux podmanvi01 4.18.0-305.10.2.el8_4.x86_64 #1 SMP Mon Jul 12 04:43:18 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
"/var/lib/shared",
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partitioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = "false"

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev,fsync=0"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

# ForceMask specifies the permissions mask that is used for new files and
# directories.
#
# The values "shared" and "private" are accepted.
# Octal permission masks are also accepted.
#
#  "": No value specified.
#     All files/directories, get set with the permissions identified within the
#     image.
#  "private": it is equivalent to 0700.
#     All files/directories get set with 0700 permissions.  The owner has rwx
#     access to the files. No other users on the system can access the files.
#     This setting could be used with networked based homedirs.
#  "shared": it is equivalent to 0755.
#     The owner has rwx access to the files and everyone else can read, access
#     and execute them. This setting is useful for sharing containers storage
#     with other users.  For instance have a storage owned by root but shared
#     to rootless users as an additional store.
#     NOTE:  All files within the image are made readable and executable by any
#     user on the system. Even /etc/shadow within your image is now readable by
#     any user.
#
#   OCTAL: Users can experiment with other OCTAL Permissions.
#
#  Note: The force_mask Flag is an experimental feature, it could change in the
#  future.  When "force_mask" is set the original permission mask is stored in
#  the "user.containers.override_stat" xattr and the "mount_program" option must
#  be specified. Mount programs like "/usr/bin/fuse-overlayfs" present the
#  extended attribute permissions to processes within containers rather then the
#  "force_mask"  permissions.
#
# force_mask = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# metadata_size is used to set the `pvcreate --metadatasize` options when
# creating thin devices. Default is 128k
# metadata_size = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by rhatdan** [comment]
This works for me on podman-3.3.0-1.fc34.x86_64
Reopen if you think this is still an issue.
