### ISSUE TITLE
set annotations for base images

### ISSUE THREAD

**Issue by vrothberg** [containers/buildah#3415]
The OCI image-spec now supports two annotations to set the name and the digest of the base image. I think that Buildah should set the two annotations. For more background please refer to the nice summary by @ImJasonH: https://github.com/ImJasonH/ImJasonH/tree/main/articles/oci-base-image-annotations

* **org.opencontainers.image.base.name**: the mutable reference to the image (e.g., docker.io/alpine:3.14)
* **org.opencontainers.image.base.digest**: the immutable digest of the base image at the time the image was built on it (e.g., sha256:adab384...)

@nalind @rhatdan WDYT?

**Comment by nalind** [comment]
Yes, of course.

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
@vrothberg Are you going to open a PR or do  you want someone from the Buildah team to do it?

**Comment by vrothberg** [comment]
> @vrothberg Are you going to open a PR or do you want someone from the Buildah team to do it?

I can do it. Always fun to get my hands dirty in Buildah land.

**Comment by vrothberg** [comment]
Fixed by https://github.com/containers/buildah/pull/3423.
