### ISSUE TITLE
Validate input for the --platform parameter

### ISSUE THREAD

**Issue by afbjorklund** [containers/buildah#3433]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

There is no validation on the syntax of the --platform parameter to build

Like when using the multi-arch syntax from `buildx build`, by mistake.

**Steps to reproduce the issue:**

1. podman build --platform=linux/amd64,linux/arm64 multiarch

2.

3.

**Describe the results you received:**

podman build --platform=linux/amd64,linux/arm64 multiarch

```
       "Architecture": "amd64,linux",
        "Os": "linux",
```

Running with podman4 gives a different error:

`Error: error creating build container: choosing an image from manifest list docker://busybox:latest: no image found in manifest list for architecture amd64,linux, variant "arm64", OS linux`

**Describe the results you expected:**

docker build --platform=linux/amd64,linux/arm64 multiarch

`Error response from daemon: "amd64,linux" is an invalid component of "linux/amd64,linux/arm64": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.2.3
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.2.3-1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by rhatdan** [comment]
@nalind is working on a PR to allow this syntax.

https://github.com/containers/buildah/pull/3402

But how should we verify the platform.  I guess we could make sure the OS is either Linux or WIndows.  But arch is potentially a moving target and same with variant.

**Comment by nalind** [comment]
`--platform` doesn't currently take a list, so it's probably parsing "linux/amd64,linux/arm64" as os="linux", arch="amd64,linux", variant="arm64".  Like @rhatdan mentioned, multiple `--platform` values is something buildah's development branch just started recognizing, and podman 3.2.3 used a recent release version that wouldn't have that feature.

**Comment by afbjorklund** [comment]
It is indeed parsing it as you say. If comma is a valid character in a platform, I guess there would be a problem...
I was just wondering if you should make it fail (with the comma), until it can parse the value as an array instead ?

**Comment by rhatdan** [comment]
Since the upstream handle's the "," I think we are ok in the main branch correct?

**Comment by nalind** [comment]
It landed on the buildah "main" branch after it branched for v1.22, so the podman "main" branch, which is currently using buildah v1.22.0, doesn't include it yet.

**Comment by afbjorklund** [comment]
If multi-arch will be handled properly (through buildah) in podman4, then it is only a (parsing) problem for podman3

**Comment by nalind** [comment]
> If multi-arch will be handled properly (through buildah) in podman4, then it is only a (parsing) problem for podman3
> 
> EDIT: Confirmed, it's working OK with `buildah bud`. Only remaining feature is to create a multi-arch manifest (for both).

Using the `--manifest` flag instead of the `-t` flag should take care of this.  `-t` can commit directly to a registry or other non-`containers-storage:` location, while the logic behind `--manifest` can't, so the CLI front end doesn't automatically try to substitute one for the other.

**Comment by afbjorklund** [comment]
Thanks, that makes sense (and Docker has the same limitation of course, have to use BuildKit and Registry)

**Comment by rhatdan** [comment]
I believe we can close this issue, since it is fixed in Main.  If you want to have validation back ported to older versions then open a PR.  Personally I would just move forward, we can push out a new version of Buildah soon with the new feature.
