### ISSUE TITLE
How to install buildah latest version based on centos7

### ISSUE THREAD

**Issue by chlins** [containers/buildah#3453]
**Description**

https://github.com/containers/buildah/tree/main/contrib/buildahimage/centos7, kernel version of 3.10.0 needs use centos7 as base image to install buildah, but the latest buildah version of centos7 is 1.11.6(old), but currently the latest version of buildah is 1.22, how can i install buildah v1.22 base on centos7 image ?  

**Steps to reproduce the issue:**
1.  pull centos:7 image and run it
2.  yum install -y buildah
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by rhatdan** [comment]
This is not an upstream issue. Centos:7 is very old, and does not have updated buildah builds.  You could use podman or docker to run newer versions of buildah in a --privileged container.  Or you could attempt to build from github.

**Comment by chlins** [comment]
@rhatdan But if my host with old kernel 3.10.0,  the newer version buildah in a --privileged container also can not run. So i need upgrade my host kernel version?

**Comment by rhatdan** [comment]
Well I would say you need to move to Centos 8 or RHEL 8.
