### ISSUE TITLE
how do I login to docker.io tekton buildah

### ISSUE THREAD

**Issue by johnlongo** [containers/buildah#3469]
Running under OKD  4.7.0-0.okd-2021-08-07-063045 and have tekton installed.
Using buildah to build my images using a dockerfile and sometimes I cant access docker.io becuse of not able to login.
Question: how do I login to docker.io when I run a tekton pipeline that uses buildah to do the build (dockerfile)?

**Comment by TomSweeneyRedHat** [comment]
@johnlongo You should be able to do `buildah login docker.io {username}` and then supply your password and you should be good to go.

**Comment by johnlongo** [comment]
buildah is running as task in my tekton pipeline (see attached example), how do I define a task to do the login first?

![image](https://user-images.githubusercontent.com/23619505/130298370-b2396f6d-9a89-49bd-8696-e554435b7e12.png)

**Comment by TomSweeneyRedHat** [comment]
@johnlongo I barely know how to spell tekton pipeline, but wonder if something like this would work?

Before running the pipeline, create an authfile at a location of your choosing.  If you put it into `/run`, it will be wiped at every reboot for you.

```
buildah login --authfile /run/myauthfiledir/myauthfile.json
```

Then add the `--authfile' option to the pipeline, something like this?

```
- name: AUTHFILE
 value: /run/myauthfiledir/myauthfile.json
```
