### ISSUE TITLE
Buildah Prints Containerfile STEPs with log level set to "warn" or higher

### ISSUE THREAD

**Issue by adambkaplan** [containers/buildah#3473]
**Description**

When setting buildah's log level to a more limited setting (`warn`, `error`, etc.), the `bud` command will continue to print all STEPs in a Containerfile. This is a concern when a Containerfile contains ENV declarations that contain sensitive information.

On OpenShift this is a common occurrence because an ENV value can be injected from a Kubernetes Secret.

**Steps to reproduce the issue:**

1. Create a simple Containerfile that has an ENV statement

```
FROM registry.redhat.io/ubi8/ubi:latest
ENV SECRET_DATA="hello-world"
RUN echo "Hello world!"
```

2. Build an image with the Containerfile above, with log level set to "error"

```
$ buildah --log-level=error bud -t hello-world:latest -f Containerfile .
```

**Describe the results you received:**

Step ENV is printed.

**Describe the results you expected:**

No steps are printed, because no error occurred.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.22.0-2.fc34.x86_64
```

**Output of `buildah version`:**

```
Version:         1.22.0
Go Version:      go1.16.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.15.0
Git Commit:      
Built:           Thu Aug  5 15:03:31 2021
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 34 (Thirty Four)
NAME=Fedora
VERSION="34.20210815.0 (Silverblue)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34.20210815.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='34.20210815.0'
Fedora release 34 (Thirty Four)
Fedora release 34 (Thirty Four)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 5.13.9-200.fc34.x86_64 #1 SMP Sun Aug 8 14:34:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]

driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]

[storage.options.overlay]

mountopt = "nodev,metacopy=on"

[storage.options.thinpool]

```

**Comment by TomSweeneyRedHat** [comment]
FWIW, the same behavior in Docker too.  Can I sell you on the `--quiet` option?  Just to be sure I know your expectations, what output would show if `--log-level=error` was used in your view?  Would it emulate `--quiet` completely or just not show some steps?

**Comment by nalind** [comment]
@adambkaplan, to confirm, is this in the context of us using the equivalent of `s2i build --as-dockerfile` followed by a buildah-as-a-library build in OpenShift?

What I'm realizing now is that with an instruction like this one:
```
ENV SECRET_DATA="hello-world"
```
even if we didn't log the instruction, that variable and its value are also going to be baked into the image, so we might need to take a closer look at a specific example.

**Comment by adambkaplan** [comment]
> to confirm, is this in the context of us using the equivalent of s2i build --as-dockerfile followed by a buildah-as-a-library build in OpenShift?

Correct

> that variable and its value are also going to be baked into the image, so we might need to take a closer look at a specific example.

True, and this may or may not be a concern for the issue that spawned this request.

> Can I sell you on the --quiet option?

@TomSweeneyRedHat that might be a path we can pursue for OpenShift builds. I assume this exposed through the `Quiet` option. We already have logic that sets the logrus level so those deeper logs are surfaced.

**Comment by rhatdan** [comment]
@adambkaplan Where are we with this?  Is this still an open issue, or is setting --quiet enough.  We have talked about potentially setting secret environment variables from the API as well as from the mount secrets.

**Comment by adambkaplan** [comment]
--quiet is enough for us. We are able to set that option within openshift/builder - I am OK closing this issue.
