### ISSUE TITLE
Feature Request: Building an Image using a Template File

### ISSUE THREAD

**Issue by stellarpower** [containers/buildah#3479]
## **Description**
Provide a third build option (in addition to `buildah from; buildh run; ...` and the `bud` system) to support building a containerfile/image recipe using a template and provided variables. The mix of ARG and ENV and interpolation of these in the build process versus handing off to the image would be removed, utilising a more powerful, flexible, and unambiguous language with dedicated support for these structures, whilst retaining the single-file recipe advantages of Dockerfiles. Support for multiple architectures, build or deployment configurations (I am thinking in terms of compose and include for context, even though this is outwith the remit of buildah itself) would be facilitated by instantiating a build recipe from the template, creating an unambiguous reference to the build for *a single image*. Templates would then serve as the master reference for representing classes of builds of the same project. Appropriate use of an existing templating mechanism would be recommended.

### Existing Issue
- Dockerfiles (and compose files) provide a unique advantage for system administrators - (almost...) the entire state of the system/build process/cluster/whatever is provided in a single text file, and thus, backing up and editing the recipe used is vastly superior to working on a metal system with scripts and commands from memory.
  - However, the syntax, lack of "language" support, handling of variables, etc., leads to a variety of issues and subtle mistakes that cost a significant amount of time. See [this blog post](https://ryandaniels.ca/blog/docker-dockerfile-arg-from-arg-trouble/) for a representative example of how strenuous one has to be to produce a clean docker build the right way
  - We don't want to repeat oursevlves, yet the existing Dockerfile format isn't sufficient to provide for anything but simple usecases of variations in builds, and so manual work results. Multi-architecture builds are a good example of an increasingly common use-case that isn't served well by the existing syntax, and as such, multiple files result and changes are propagated with updates.
- Buildah solves this problem by moving the build logic and variation out of the build instructions itself and into the wrapper script. This makes sense, not least because we may well (need to) write a small wrapper script for building a large project anyway. I have even observed examples of placing the docker build and run process into a Makefile, both to remove some of these wrappers and tune some options. The handling of variables, values dependent on machine and runtime, and the output of commands, is removed from the build instructions and instead left where it better belongs, in an enclosing language with support for these things
  - However, there is a certain neatness to having all the instructions to create this image in a single file, that can be viewed more intuitively and rapidly to see what is going on. Jumping in and out of `buildah` from a script offers far more flexibility, but for me, the separation and power of being able to set up and install an application and supporting OS and ecosystem form a single selc-contained (almost...) file is not to be understated.
  - Whilst a shell scirpt offers much better support for variables and runtime values, this naturally comes at the detriment of being able to pick up a containerfile and see exactly what was built. Reproducing upstream images in order to modify them can contain a certain amount of guesswork, if the build arguments it was run with aren't provided, for example.
- Also, version controlling of files is a useful place to aim for, but in reality, we must acknowlegde that especially in builds and deployment, sometimes situations change on a temporary basis in a way that we don't want to record. If a server goes down or a domain has to be changed at the last minute, or equally if an update introduces a breaking change that we don't currently know how to resolve, the most sensible option may be to have several build/deployment recipes present in a directory and select between them as to which we will bring up in the moment. In this sense, the changing nature of our environment seems ideally suited to templates - I don't necessarily want to have to make edits to a repository-controlled build file in order to build/deploy for an unforeseen situation, yet also, I don't want the onus of having to specify every variable to the command line for each normal update. The reality of the situation is that I often have several parallel Dockerfiles (or build scripts, composes, ansible scripts, etc.) sitting around and I duplicate and edit as needed to make small changes when I need my system up ASAP. These files would ideally be produced by a templating system, such that I don't forget important details to change as can often happen.

## Proposal
I would be interested in seeing a third option (to native buildah and bud), a containerfile somewhat similar to a dockerfile (in format, such that it involves a recipe of individual steps line-by-line that each commit a layer onto the image, but I would happily diverge from the Dockerfile syntax if beneficial), except that it is used as a template to create the actual recipe used for building the image.

One thing that was drilled into me by the C++ books I have read is that a template class (or more formally, class template) is not itself a class. It's instructions on how to stamp out a class. I think this can be a really beneficial approach to take for various problems in the field, from low-level programming all the way through to devops. Crystal has gained popular support for its macro system, because these explicitly work with source code text and AST nodes, and are separate from the program text itself - macros aren't code, they make code. But, not uncommonly, languages and systems blend these two together and the boundary is messy. This leads to a lot of poor practices becoming commonplace, because one must be really thorough in setting about things the right way to maintain a clean use of the tool. It makes sense to introduce build arguments into your Dockerfile... until it doesn't.

In this case, I believe a lot of the messiness comes in both Dockerfiles and Compose files from a mixture of internal and external handling of variables and values. ARG variables have to be specified in certain positions in a Dockerfile to be properly interpreted, and are thrown away at each FROM clause, which makes multi-stage builds very precarious. Compose files take a mix of environment variables from the existing environment, the command line, environment files, and the source image, making it hard to reproduce a situation exactly - it works fine for fixed setups, but commonly one ends up creating several compose files for different scenarios anyway. Missing values are rarely captured and the deployment fails late rather than failing early when something that should implicitly be present is missing. In both cases, it also places onus on defining these variables at the site of use, again meaning that we often have to place another wrapper around docker or docker-compose for including everything required for building or running.

A logical solution (to me) for these cases would be to separate the variation in the build/deployment from the steps needed to produce a particular setup, and templating mechanisms à la jinja2, JSonnet, or FrontMatter and Liquid (as in Jekyll) would be used strictly to inject variations into the common work done for producing the file then used to build a particular image. 

## Usecase Examples

For simple setups, where we want to change basic values such as environment variables, image tags (e.g. regulat updates), port ranges, etc., if these are introduced as variables in a template, we could pass this template to buildah and have it create the specific build file for this image, and thus provide a clear separation, enhancing reproducability. Unlike buildah, docker doesn't dereference symlinks when passed into the build context, and an argument for this decision is that the ability to reproduce the build is lost - if a folder is present on your machine, it should be on mine. However, when taking into account environment variables and build arguments, this concept is lost almost entirely. If the template is produced into a build file, where not only the variable names, but also the values they take are hard-coded into the file text, or e.g. specified at the header of a file in (some format), this would enable easy reading of the main body, highlighting where variables are used, and provide an unambiguous reference as to the exact values they took at build-time. Thus, producing a template may vary depending on environment, but the file output by this step would reproduce exactly across two machines (subject to pulling the same version of dependent images)

Taking multiple architectures as an example, at the least, we are likely to need to pull a different source image. We may have custom build steps, and values that will change. A template system could offer the option of simple hashes, in order to look-up 
values dependent on the current architecture. Conditionals could enable or disable architecture-specific stages of the build, and including basic looping into the template (as in Ansible or liquid) may even permit iterating over all the architectures in one file - whether the logic for template variation should be passed explicitly on the command line, or could be specified inside the build file, or some other ocmbination (e.g. template + variables file containing an array of different configurations) would remain to be seen.

## **Proposed Options**
- I'll leave this open to debate now as others may have quite different opinions, just wanted to float the idea. If there is any interest, I will take some of the above and crystallise here
- An important point for me is that I believe this would be best as an extra method - I don't think any of this should introduce breaking changes with the existing build methods; I think buildah's native mode of operation has many unique advantages and providing compatible docker support is clearly a sensible move. I would like to consider this as an alternative to the other two methods, in a way that does not force anything upon the user, and would only be used by those who want to do so, in a situation where it is the right tool for the job. Should something like this be implemented, native building and `bud` shouldn't be effected by this unless it uncovers issues that it is decided are really significant to resolve. 
- Having typed all this, it only now hits me that potentially a cleaner way of doing this is to keep the templates separate from buildah altogether, and simply use a templating tool to create a Dockerfile with no environment variables that buildah can then use to create a single image. If this is desireable, then it may be there would be some small issues or corner cases where it would be beyond the templater on its own to create the setup without having the context of the image and building system, and as such some minor changes to buildah might be warranted. This idea comes to me as I have used a templating system before for docker-based setups of my machine, and implementing this wasn't trivial. A number of the issue I mention are based off personal or second-hand experience.

Cheers :)

**Output of `buildah version`:**

```
Version:         1.21.1
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.12.0
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64

```
## Related Issues/PRs/etc.
- #851

**Comment by stellarpower** [comment]
Don't blame you, I did ramble rather a bit! 

I think YAML is precisely what was coming to mind, I visualised it a bit like a modified containerfile. This is the first third or so of a multi-stage build I was using about 3 months ago:

```
#############################################################
# Multi-stage ARGS must occur before first FROM:
# 
ARG BaseImage="waypipe:kde"
ARG InstallationName="registry.gitlab.com/foo/bar"
ARG InstallationCheckout
ARG IT=${InstallationName}:install-${InstallationCheckout}

#############################################################
FROM $BaseImage
ARG InstallationCheckout
ARG IT
# And now we have to specify it again as [FROM nukes the arguments](https://i.ytimg.com/vi/4IUxK_0WLbg/mqdefault.jpg)

# The only way to bail if a variable is not defined is to use it in a RUN statement and fail
# To that end, we need to be using a base image with a shell
RUN test -n "$InstallationCheckout" || (echo '`InstallationCheckout` must be supplied as a build argument to the Deploy stage.\n' \
    'It refers to the image you created in the installation phase and should usually be the same as the version you checked out.' \
    'The prefix -install is added automatically: --build-arg "InstallationCheckout=test" --build-arg "InstallationName=aruco-image"=> "aruco-image:install-test" '>&2; false)
RUN echo "Installing from $IT" >&2

#############################################################
FROM ${IT} as supplied_installation
# `COPY --from` does not support variables, so we have to pull in here and name
# https://github.com/docker/for-mac/issues/2155

#############################################################
ARG BaseImage="waypipe:kde"
FROM $BaseImage AS installed_as_in_gitlab_container

USER root

ARG ProjectName="MyGraphicalProject"
ARG InstallationDirectory="/usr/local/" # Watch the trailing slash
ARG InstallationTag

ARG DEBIAN_FRONTEND=noninteractive

## Runtime Dependencies, if required
RUN apt update
RUN apt install --yes bodger badger #Finally actually start working

```
I think I took my dev container, built, installed, copied out the binaries, and then copied these back into a runtime container that had the dependencies without build-deps. Relatively standard, but this was a larger build so it became more complicated. Hope this is a good example to the lengths I had to go to just to parameterise some things nicely - I had forgotten that we only pulled the BaseImage at the top so we have the shell to test that the variables are defined, I didn't find any way to get docker to require them and bail if not provided, it'll just substitute them in empty. There may well be a better way to do this but I did spend plenty of time searching, and I think unless you have the formula exactly right, projects either take the view that they'll just knock up a new Dockerfile and leave everything hard-coded to reduce risks, or they have a very well thought-out strategy and don't ever deviate. 

One main thing is the number of lines we need to have that don't do anything, they're just there to support variables properly, which interleave in and out of the build environment (again, something buildah serves to remove). 

So back to the YAML, the first thing I pictured it in my head was with liquid-style braces. All of the above could basically collapse to the following:

```
# Have the template process require that some variables be defined
FROM {{ BaseImage }} as build_stage
# Have the template process set the name of the project and the VCS checkout to build.
# Have the template process set the debian non-interactive stuff
USER root
RUN apt update
RUN apt install --yes bodger badger
WORKDIR 
```
I've left a couple of lines out but if variables are all passed in then we don't need them. I then later realised we could potentially use front-matter like Jekyll does (and many others):
```
---
BaseImage:            "waypipe:kde"
InstallationName:     "my_graphical_project"
InstallationCheckout: "rev19"
---

FROM {{ BaseImage }} as build_stage

RUN apt update
RUN apt install --yes bodger badger
...
```
So yes, I'd certainly say that's similar lines.

There are advantages and disadvantages, but I think some scope to think about. If producing a strict containerfile format from a template, then the front matter may not make so much sense, whilst if buildah took a new file format that did both in one, then it would. As mentioned, I think the former is possibly cleaner, it seems from past experience when we start to mix things is when down the line it gets messy as requirements change, or doesn't quite work as users expect.

Would certainly be nice to join the meeting in principle, would it be best to have a few slides or notes, or is it more of a verbal discussion? I've not got a great amount of free time at the moment and I know I wrote a lot but the idea is pretty half-baked in my mind, so if they're on a fortnightly basis am wondering if would be better with a bit more time to prepare. Could also dig through and see if I can find some examples of my own Dockerfiles, as I'm sure it'll refresh my mind a bit to look at my own use-cases. But I am free at that time on the 16th.

**Comment by mtrmac** [comment]
I think a necessary starting point is articulating precisely what _feature_ is missing or hard to do.

Only after that it is useful to discuss whether it would be best implemented a trivial addition to something that already exists, a new templating language directly in Buildah, use of an existing templating mechanism in something that invokes Buildah, a separate prototype for a new language likely targeted at eventual inclusion in Buildah if proven, or some other solution entirely. Introducing a new language is somewhat of a big deal, so we should be fairly confident that it’s necessary, and that it solves a specific problem. “Let’s do the same thing as the previous language, but not so ugly” also feels like something that’s easy to want but hard to achieve, because every language needs to evolve in unanticipated ways over time.

**Comment by TomSweeneyRedHat** [comment]
@stellarpower the Podman Community Cabal meetings happen on the third Thursday of the month.   So the next one is September 16, the following one is October 21.  I think 2 or 3 slides would probably be helpful, just to sketch out the basis of your idea, and then discuss from there.  Some of those slides might be pseudo syntax for what you're envisioning as you have in some of the comments here.  I'd be happy to have you do this talk at either date, just let me know which you think would work best.

**Comment by stellarpower** [comment]
Okay, I think probably best if I spend a bit more time thinking about it, so I have some concrete points and hopefully some use cases. I'll try and knock together a few slides too and aim for the October meeting; I'll keep you posted. And maybe there are others here who want to add some thoughts. Thanks for the invitation!

**Comment by mtrmac** [comment]
BTW note https://github.com/containers/buildah/blob/5b056ee652bb6165a462305a2ce47745265ba122/docs/buildah-build.md : 
> Containerfiles ending with a ".in" suffix will be preprocessed via cpp(1)

**Comment by stellarpower** [comment]
I didn't know that. Something like that sounds workable, although I think using specifically the C Preprocessor as a templating engine is... well possibly substituting a headache for nausea, but a good start.

If any of you have ever seen the infamous [wat talk](https://www.destroyallsoftware.com/talks/wat), I am wondering if tihs would be a way to present some motivating examples. I think I have come across enough `docker wat` cases over the last 18 months I can try to collect the issues, specifically as to how they might be resolved by a templating system.

**Comment by rhatdan** [comment]
Since we have .in support, I think that requires the requirement.
