### ISSUE TITLE
Optimization: use smaller images in tests

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3494]
The `bud with copy-from in Dockerfile no prior FROM` test is causing flakes in podman testing because image pulls take over two minutes:

https://github.com/containers/buildah/blob/e1f747152caa112fbc476c5440fdcfe5bef15c01/tests/bud.bats#L1568-L1574

`php` and `composer` are huge: 400MB and 185MB respectively. Does this test explicitly require something that can only be provided by these images? If not, could we rewrite it (and other tests that use huge images) to use the standard alpine/busybox small images?

### 121 bud with copy-from in Dockerfile no prior FROM
* fedora-34 : bud podman fedora-34 root host
  * PR #11368
    * [08-31 08:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5885546078666752/html/bud-podman-fedora-34-root-host.log.html)
  * PR #11330
    * [08-26 10:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6238256804134912/html/bud-podman-fedora-34-root-host.log.html)
  * PR #11009
    * [08-30 17:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6554996012482560/html/bud-podman-fedora-34-root-host.log.html)
* fedora-34 : bud remote fedora-34 root host [remote]
  * PR #11368
    * [08-31 08:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5322596125245440/html/bud-remote-fedora-34-root-host.log.html)
  * PR #11330
    * [08-26 10:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4830881920581632/html/bud-remote-fedora-34-root-host.log.html)

**Comment by nalind** [comment]
I don't think it does.  The test looks like it was modeled after the original report in https://github.com/containers/buildah/issues/1175.  Copying any file which we know is present in a different image should be sufficient - the important thing is that the argument of the `--from=` is not a reference to a previous stage (either by name or number) of the multi-stage build, so we treat the argument value it as the name of an image.

**Comment by edsantiago** [comment]
Thank you! I've self-assigned.

**Comment by rhatdan** [comment]
@edsantiago still working on this.
