### ISSUE TITLE
Is there any way to install it on ubuntu 20.04?

### ISSUE THREAD

**Issue by kwon14** [containers/buildah#3505]
Hello. I am trying to install buildah with dockerfile.
The OS I am using is ubuntu 20.04.

As shown below, both methods of case 1 and 2 cannot be installed in ubuntu 20.04.
If you know how to install it, please share.

We always appreciate your hard work.
thank you.

case 1:
Step 28/55 : RUN wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
 ---> Running in 937e23264463
[91mhttps://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x_/Release.key:
2021-09-08 05:10:39 ERROR 404: Not Found.
[0mThe command '/bin/bash -o pipefail -c wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key' returned a non-zero code: 8

case 2: 
Step 26/55 : RUN apt-get -y update  &&     apt-get -y install buildah
 ---> Running in e62bbb9d4e73
Get:1 https://download.docker.com/linux/ubuntu focal InRelease [52.1 kB]
Get:2 https://download.docker.com/linux/ubuntu focal/stable amd64 Packages [11.6 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Get:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,070 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [30.1 kB]
Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [790 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [525 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [575 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,514 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [33.3 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,069 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [6,324 B]
Fetched 6,006 kB in 4s (1,524 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
[91mE: Unable to locate package buildah
[0mThe command '/bin/bash -o pipefail -c apt-get -y update  &&     apt-get -y install buildah' returned a non-zero code: 100

**Comment by flouthoc** [comment]
@kwon14 could you try this https://gist.github.com/sebastianwebber/2c1e9c7df97e05479f22a0d13c00aeca

**Comment by kwon14** [comment]
@flouthoc Thank you so much!!
It works for me!!
