### ISSUE TITLE
bud: Do not assume implicit ENV PATH=… in Containerfile

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/buildah#3512]
```
$ buildah version
Version:         1.22.3
Go Version:      go1.16.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.15.2
Git Commit:      
Built:           Wed Aug 25 18:36:22 2021
OS/Arch:         linux/amd64

$ echo "FROM scratch" > Containerfile
$ buildah bud
STEP 1/1: FROM scratch
COMMIT
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config 75c4176381 done  
Writing manifest to image destination
Storing signatures
--> 75c4176381a
75c4176381a53c0845d32c89f23e1c27b2f55f2d42e6ecfaaf8f571053b88ae6

$ skopeo copy containers-storage:75c4176381a5 oci-archive:zzz.tar
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config 75c4176381 done  
Writing manifest to image destination
Storing signatures
```
zzz.tar:blobs/sha256/75c4176381a53c0845d32c89f23e1c27b2f55f2d42e6ecfaaf8f571053b88ae6 is
> {"created":"2021-09-12T10:04:51.528630784Z","architecture":"amd64","os":"linux","config":{"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Labels":{"io.buildah.version":"1.22.3"}},"rootfs":{"type":"layers","diff_ids":["sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"]},"history":[{"created":"2021-09-12T10:04:51.529415181Z","created_by":"/bin/sh"}]}

```
$ echo "ENV PATH=/abc" >> Containerfile
$ buildah bud 
STEP 1/2: FROM scratch
STEP 2/2: ENV PATH=/abc
COMMIT
Getting image source signatures
Copying blob 5f70bf18a086 [--------------------------------------] 0.0b / 0.0b
Copying config 25bc4e9ec6 done  
Writing manifest to image destination
Storing signatures
--> 25bc4e9ec6e
25bc4e9ec6ed2cd0f0220c7600996d2c1d428b080b30aff0700548b722bfe414
$ skopeo copy containers-storage:25bc4e9ec6e oci-archive:yyy.tar
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config 25bc4e9ec6 done  
Writing manifest to image destination
Storing signatures
```

yyy.tar:blobs/sha256/25bc4e9ec6ed2cd0f0220c7600996d2c1d428b080b30aff0700548b722bfe414 is
> {"created":"2021-09-12T10:16:19.546280413Z","architecture":"amd64","os":"linux","config":{"Env":["PATH=/abc"],"Labels":{"io.buildah.version":"1.22.3"}},"rootfs":{"type":"layers","diff_ids":["sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"]},"history":[{"created":"2021-09-12T10:16:19.546974015Z","created_by":"/bin/sh -c #(nop) ENV PATH=/abc"}]}

Apparently `buildah build-using-dockerfile` inserts ENV (PATH), even if there is no ENV in the Dockerfile.  For OCI images, which contain a single binary, this does not make sense.

**Comment by rhatdan** [comment]
This follows the standard that Docker set. If  you build an empty image with Docker it will also insert a default PATH environment.

**Comment by dilyanpalauzov** [comment]
The Dockerfile reference specification - https://docs.docker.com/engine/reference/builder/ - does not describe this implicit behaviour.  It also does not describe, how to turn it off.

**Comment by dilyanpalauzov** [comment]
The newly added documentation for Containerfile - https://github.com/containers/buildah/pull/3549/  - does not state, that there is default PATH environment variable, if nothing is specitied.

**Comment by flouthoc** [comment]
@dilyanpalauzov I think `PATH` variable is explicitly configured to maintain parity with `docker` but I think yes this needs to be added into documentation. Would you like to open a PR ? If not I can do it.

**Comment by dilyanpalauzov** [comment]
Since the Dockerfile reference also does not state, that there is implicit PATH variable, and there is no way to remove that variable, only to replace it, I am against documenting the behaviour.  I would like if the bahaviour is adjusted to the documentation.  Or: for Dockerfile there is implicit PATH, for Containerfile there is no explicit env. PATH.

**Comment by rhatdan** [comment]
We don't differentiate between the two at this point.
I think we just document that this field gets added.

**Comment by rhatdan** [comment]
I think adding an unsetenv might be usefull
