### ISSUE TITLE
ignorefile: wildcard behaves differently depending on unrelated ignore lines

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3520]
Weird and unexpected side effect of #3486 : actually specifying `!subdir/foo` makes `!*/bar` suddenly work:
```console
$ mkdir ttt;cd ttt
$ cat >Containerfile <<EOF
FROM quay.io/libpod/alpine:latest
COPY ./ /newdir
EOF
$ cat >.containerignore <<EOF
subdir
!*/sub1*
!subdir/sub3*
EOF
$ mkdir subdir
$ touch subdir/sub{1,2,3}.txt
$ ../bin/buildah bud -t foo .
...
$ podman run --rm foo ls -lR /newdir
/newdir:
total 4
-rw-rw-r--    1 root     root            28 Sep 15 15:19 Containerfile
drwxr-xr-x    1 root     root            48 Sep 15 15:20 subdir

/newdir/subdir:
total 0
-rw-rw-r--    1 root     root             0 Sep 15 15:20 sub1.txt
-rw-rw-r--    1 root     root             0 Sep 15 15:20 sub3.txt
```
Removing the last line (the `sub3` one) from `.containerignore` makes `sub1.txt`, and all of `subdir`, go away:
```console
$ podman run --rm foo ls -lR /newdir
/newdir:
total 4
-rw-rw-r--    1 root     root            28 Sep 15 15:19 Containerfile
```

This violates POLA, because a wildcard behaves differently depending on completely unrelated lines in the ignorefile. I think I understand why it's happening, and my honest opinion is that #3486 should've been fixed by ignoring EPERM instead of deferring traversal (but what do I know). I do think this new behavior is surprising and may warrant careful thought.

**Comment by nalind** [comment]
Yes, this is compatible how `docker build` behaves.  I'm not thrilled about the behavior, myself.

**Comment by edsantiago** [comment]
Oh, ouch. I no longer have any way to run docker, but if this is a compatibility issue I guess we have to live with it. Thanks for the explanation. Feel free to close.

**Comment by nalind** [comment]
Going ahead and turning this into a pair of conformance tests.

**Comment by nalind** [comment]
Tests are merged, closing this one.
