### ISSUE TITLE
Dockerfile SHELL instruction seems to be ignored

### ISSUE THREAD

**Issue by bbannier** [containers/buildah#3537]
**Description**

I would like to use Bash in Dockerfile `RUN` instructions, but when I use a [`SHELL`](https://docs.docker.com/engine/reference/builder/#shell) instruction  to change the default shell Buildah seems to silently ignore my request.

**Steps to reproduce the issue:**
1. Create a `Dockerfile` containing a `SHELL` instruction and try to use Bash features in `RUN` instructions, e.g.,

    ```
    FROM docker.io/debian:bullseye-slim

    ENV FOO=bar
    SHELL ["bin/bash"]

    RUN [[ "${FOO}" == b* ]]
    ```
2.  The `RUN` instruction fails since it is using `/bin/sh`, not the requested `SHELL`

     ```
     $ buildah bud .
    STEP 1/4: FROM docker.io/debian:bullseye-slim
    Trying to pull docker.io/library/debian:bullseye-slim...
    Getting image source signatures
    Copying blob f8416d8bac72 done
    Copying config 7beb0248fd done
    Writing manifest to image destination
    Storing signatures
    STEP 2/4: ENV FOO=bar
    STEP 3/4: SHELL ["bin/bash"]
    STEP 4/4: RUN [[ "${FOO}" == b* ]]
    /bin/sh: 1: [[: not found
    error building at STEP "RUN [[ "${FOO}" == b* ]]": error while running runtime: exit status 127
    ```

**Describe the results you received:**

The `SHELL` instruction seems to be ignored silently. 

**Describe the results you expected:**

I would have expect that either the `SHELL` instruction has the expected effect of changing the shell used for `RUN` instruction, or that it would have been rejected with a diagnostic message.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ rpm -q buildah
buildah-1.23.0-1.fc34.x86_64
```

**Output of `buildah version`:**

```
Version:         1.23.0
Go Version:      go1.16.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.16.0
Git Commit:
Built:           Tue Sep 14 14:56:43 2021
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 34 (Thirty Four)
NAME=Fedora
VERSION="34 (Cloud Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Cloud Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cloud Edition"
VARIANT_ID=cloud
Fedora release 34 (Thirty Four)
Fedora release 34 (Thirty Four)
```

**Output of `uname -a`:**

```
Linux fedora 5.11.12-300.fc34.x86_64 #1 SMP Wed Apr 7 16:31:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"


[storage.options]
additionalimagestores = []

[storage.options.overlay]
mountopt = "nodev,metacopy=on"

[storage.options.thinpool]
```

**Comment by flouthoc** [comment]
@bbannier try with `buildah build --format=docker`  i dont think this is supported for OCI.

**Comment by bbannier** [comment]
That does work @flouthoc, thanks a lot.

This solves my immediate issue, but I think it would still be great to add a diagnostic for this when using unsupported constructs.

**Comment by flouthoc** [comment]
@bbannier I think it spits a warning could you check your build log please, it should show something like.

```bash
WARN[0005] SHELL is not supported for OCI image format, [/bin/bash -c] will be ignored. Must use `docker` format
```

**Comment by bbannier** [comment]
Ah interesting, you are right, I see the warning when building directly with `buildah` on that Fedora system I described above.

What I originally did was to build via `Podman` from macos (e.g., `podman build .`). For that setup the diagnostic doesn't seem to propagate to the macos host. Should I create a new issue somewhere in [containers/podman](https://github.com/containers/podman/) for that?

**Comment by rhatdan** [comment]
If you don't see this message when building on a MAC that too is a bug.
