### ISSUE TITLE
buildah not actually stopping on SIGTERM

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3544]
```console
$ printf "FROM alpine\nRUN sleep 30\n" | timeout -v --foreground 5 /usr/bin/buildah bud -t foo -
STEP 1/2: FROM alpine
STEP 2/2: RUN sleep 30
timeout: sending signal TERM to command ‘/usr/bin/buildah’
$ [back at prompt]
```
Looks good ... except that, 25 seconds later (when `sleep` finishes), this spews out on my terminal:
```console
$ COMMIT foo
Getting image source signatures
Copying blob e2eb06d8af82 skipped: already exists
Copying blob 8bca338d16ce done
Copying config c5c07e0d36 done
Writing manifest to image destination
Storing signatures
--> c5c07e0d36e
Successfully tagged localhost/foo:latest
c5c07e0d36e0124944e114aefad25e8fa6ad170d4377703fffab5980bf1bde03
```
During those 25 seconds:
```console
$ ps auxww|grep buildah
esm      3804916  0.9  0.1 1492444 39456 pts/14  Sl   12:45   0:00 /usr/bin/buildah-in-a-user-namespace bud -t foo -
esm      3804985  2.0  0.1 1639908 37764 pts/14  Sl   12:45   0:00 buildah-oci-runtime
esm      3805583  0.0  0.0 221400   856 pts/31   S+   12:45   0:00 grep --color buildah
```
Appending `| cat` to the reproducer changes the behavior: instead of getting a prompt, the command pauses for those full 30 seconds, then spits out the build log stuff, then returns to command-line prompt.

In both cases, after 30 seconds, `buildah images` shows the newly-built `foo` image.

I believe this is a bug. I believe SIGTERM should kill buildah and all child processes; and I believe that the image `foo` should never get created.

**Comment by rhatdan** [comment]
@nalind PTAL.
Basically buildah needs to catch sigterm and then kill any runs correct?

**Comment by vrothberg** [comment]
> @nalind PTAL.
> Basically buildah needs to catch sigterm and then kill any runs correct?

And possibly clean up/remove  the build containers?

**Comment by nalind** [comment]
As an unprivileged user, the reproducer kills the originally-started process, but leaves the child that's running as root in a user namespace untouched.

**Comment by rhatdan** [comment]
@nalind should we catch the SIGTERM and then attempt to kill the child before exiting?
