### ISSUE TITLE
Buildah to connect to remote podman

### ISSUE THREAD

**Issue by TomasTomecek** [containers/buildah#3552]
**Description**

Would it be possible for buildah to connect to remote podman which would handle execution and management of the containers?

This way we could have container support where container execution is not available (e.g. Windows)

Context: https://github.com/ansible-community/ansible-bender/issues/259

**Comment by rhatdan** [comment]
No. This will not happen, podman-remote build does pretty much what you want, though.  
Or you could just tar up the context directory and Containerfiles and send them to the host and execute buildah there.

**Comment by TomasTomecek** [comment]
Okay, that makes sense. I think then ansible-bender should also be able to work with podman and especially talk to the REST API so people don't need to run containers on their workstations if the technology is not available there.

Overall I'd still prefer if buildah did the remote execution for me but I understand the design decision.
