### ISSUE TITLE
Rootless user can't build modified image based on Shared Image

### ISSUE THREAD

**Issue by mfblair** [containers/buildah#3553]
I created a shared OCI image using the instructions in this great article (https://www.redhat.com/sysadmin/image-stores-podman). This works well for starting containers based on a shared image. However, it seems that when a rootless user tries to create a new image based on an image in the shared area, and makes any changes as part of building the new image, this will trigger an error similar to the following.

`error copying layers and metadata for container "ec75ba443567a5d2673f54474704b3198c9e7a820d7bc83c3e1dbf653326006b": Error initializing source containers-storage:fedora-working-container: error extracting layer "e27dcbf8b9e467a69b5f1d9cae79f91a70c1845714f1adf154d38580f4eb16d7": chown /var/lib/mycontainers/overlay/0203e243f1ca4b6bb49371ecd21363212467ec6d7d3fa9f324cd4e78cc6b5fa2/diff: operation not permitted`

This seems to suggest that buildah is trying to make changes in the read only shared directory?

Notes. 
- These steps work without issue for root user, or if the Dockerfile shown in step 6. below does not include the COPY line.
- I've noticed that closed issues 2161 and 2359 are somewhat similar, but don't exactly match the symptoms or error

**Steps to reproduce the issue:**
1. Create intended shared image directory as root
	`mkdir /var/lib/mycontainers`

2. Pull fedora image using --root option
	`# podman --root /var/lib/mycontainers pull fedora`
	
3. Ensure shared directory contents are world-readable
	`sudo chmod -R a+rx /var/lib/mycontainers`
	
4. Confirm non-root user "support" set up for rootless access
	`[root@localhost github_2161_exper]# cat /etc/subuid`
	`support:100000:65536`
	`user1:165536:65536`
	`[root@localhost github_2161_exper]# cat /etc/subgid`
	`support:100000:65536`
	`user1:165536:65536`
	
5. Create a text file, to be added to newly created image (just to represent any change to image)
	`[support@localhost github_2161_exper]$ cat this.txt`
	`thistext`
	
6. As non-root user, create Dockerfile to clone and modify fedora image
	`[support@localhost [github_2161_exper]$ cat Dockerfile_fedora_withCOPY` 
	`FROM registry.fedoraproject.org/fedora:latest as build-env`
	`COPY this.txt /tmp/this.txt`

6.5. (**Edit Oct 13 '21 - missed this step when originally posting bug**) Create storage.conf in rootless user's home directory with:
	`$ cat ~/.config/containers/storage.conf`
	`[storage]`
	`driver = "overlay"`
	` `
	`[storage.options]`
	`additionalimagestores = [ "/var/lib/mycontainers",]`
	` `
	`[storage.options.overlay]`
	`mount_program = "/usr/bin/fuse-overlayfs"	`

7. Run Dockerfile
	`[support@localhost github_2161_exper]$ podman build -t fedora_fr_podman:latest -f Dockerfile_fedora_withCOPY`

**Describe the results you received:**

`STEP 1: FROM registry.fedoraproject.org/fedora:latest AS build-env`
`STEP 2: COPY this.txt /tmp/this.txt`
`STEP 3: COMMIT fedora_fr_podman:latest`
`Error: error committing container for step {Env:[DISTTAG=f34container FGC=f34 container=oci PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[this.txt /tmp/this.txt] Flags:[] Attrs:map[] Message:COPY this.txt /tmp/this.txt Original:COPY this.txt /tmp/this.txt}: error copying layers and metadata for container "ec75ba443567a5d2673f54474704b3198c9e7a820d7bc83c3e1dbf653326006b": Error initializing source containers-storage:fedora-working-container: error extracting layer "e27dcbf8b9e467a69b5f1d9cae79f91a70c1845714f1adf154d38580f4eb16d7": chown /var/lib/mycontainers/overlay/0203e243f1ca4b6bb49371ecd21363212467ec6d7d3fa9f324cd4e78cc6b5fa2/diff: operation not permitted`
	

**Describe the results you expected:**
	
New image created successfully

**Output of `rpm -q buildah` or `apt list buildah`:**

```
[support@localhost github_2161_exper]$ rpm -q buildah
buildah-1.21.4-1.module+el8.4.0+11989+6676f7ad.x86_64

```

**Output of `buildah version`:**

```
[support@localhost github_2161_exper]$ buildah version
Version:         1.21.4
Go Version:      go1.15.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.12.0
Git Commit:      
Built:           Tue Jul 27 03:29:47 2021
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
[support@localhost github_2161_exper]$ podman version
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        Tue Jul 27 03:29:39 2021
OS/Arch:      linux/amd64

```

**Output of `cat /etc/*release`:**

```
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
Red Hat Enterprise Linux release 8.4 (Ootpa)
Red Hat Enterprise Linux release 8.4 (Ootpa)

```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Tue Sep 7 07:07:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partitioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = "false"

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev,metacopy=on"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

# ForceMask specifies the permissions mask that is used for new files and
# directories.
#
# The values "shared" and "private" are accepted.
# Octal permission masks are also accepted.
#
#  "": No value specified.
#     All files/directories, get set with the permissions identified within the
#     image.
#  "private": it is equivalent to 0700.
#     All files/directories get set with 0700 permissions.  The owner has rwx
#     access to the files. No other users on the system can access the files.
#     This setting could be used with networked based homedirs.
#  "shared": it is equivalent to 0755.
#     The owner has rwx access to the files and everyone else can read, access
#     and execute them. This setting is useful for sharing containers storage
#     with other users.  For instance have a storage owned by root but shared
#     to rootless users as an additional store.
#     NOTE:  All files within the image are made readable and executable by any
#     user on the system. Even /etc/shadow within your image is now readable by
#     any user.
#
#   OCTAL: Users can experiment with other OCTAL Permissions.
#
#  Note: The force_mask Flag is an experimental feature, it could change in the
#  future.  When "force_mask" is set the original permission mask is stored in
#  the "user.containers.override_stat" xattr and the "mount_program" option must
#  be specified. Mount programs like "/usr/bin/fuse-overlayfs" present the
#  extended attribute permissions to processes within containers rather then the
#  "force_mask"  permissions.
#
# force_mask = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# metadata_size is used to set the `pvcreate --metadatasize` options when
# creating thin devices. Default is 128k
# metadata_size = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"

```

**Output of rootless user's storage.conf - `cat ~/.config/containers/storage.conf`:**

[storage]
driver = "overlay"
[storage.options]
additionalimagestores = [ "/var/lib/mycontainers",]
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"`

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
it seems to work well with podman 3.3.1.

Could you try again with an updated version?

**Comment by rhatdan** [comment]
Looks like this is fixed in the main branch.  Closing. Continue the conversation here, if you have issues.

**Comment by mfblair** [comment]
Thank you Dan and Giuseppe!

I know this is probably a rookie question, but how can I get podman 3.3.1 into RHEL 8.4? Everything I'm finding seems to show that podman 3.2.3 is the latest version available from Red Hat. Is there an alternate repository I'd need to configure to pull the newer version from?

Oh, and one more, since buildah 1.21.4 has the same issue, is there a version of buildah that corresponds to the code in podman 3.3.1?

Thanks again,
Blair

**Comment by rhatdan** [comment]
podman 3.3 should be showing up in RHEL8.5 which should be coming out soon. buildah 1.23.0 will be there also.

**Comment by mfblair** [comment]
Thanks Dan.

**Comment by rhatdan** [comment]
You need to change the SELinux labeling on the directory. I recently added comments to storage.conf

https://github.com/containers/storage/pull/1038

```
  When changing the graphroot location on an SELINUX system, ensure
  the labeling matches the default locations labels with the
  following commands:

  # semanage fcontext -a -e /var/lib/containers/storage /NEWSTORAGEPATH
  # restorecon -R -v /NEWSTORAGEPATH
```
Would this have helped you out?

**Comment by mfblair** [comment]
Hi Dan,

Thanks, but if I've executed them correctly, those commands do not seem to have helped. 

As root, I tried
	- removing and re-creating the shared area /var/lib/mycontainers
	- pulling an image into it
	- making it world readable
	
Then I tried executing the commands you referenced in those comments:

[root@localhost containers]# **semanage fcontext -a -e /var/lib/containers/storage /var/lib/mycontainers**
[root@localhost containers]# **restorecon -R -v /var/lib/mycontainers/** 

After doing this, I still receive the same error when trying (as the rootless user) to launch a container from the shared image:

[support@localhost containers]$ **podman images**
REPOSITORY                         TAG         IMAGE ID      CREATED      SIZE        R/O
registry.fedoraproject.org/fedora  latest      191682d67252  13 days ago  184 MB      true

[support@localhost containers]$ **podman run -ti registry.fedoraproject.org/fedora:latest**
Error: error creating mtab directory: chown /home/support/.local/share/containers/storage/overlay/d6dcfe2fdf2525ee704607652e1fde962bcdf8d5a87c137e98a836d93a146e54/merged/etc: operation not permitted

Also, if I've entered the **semanage** and **restorecon** commands correctly, I'm confused about their intent. They seem to relate to changing permissions on files in the shared area /var/lib/mycontainers/, but the actual error message I'm receiving above is referencing an error creating a directory (mtab) under the rootless user's home:

/home/support/.local/share/containers/storage/overlay/d6dcfe2fdf2525ee704607652e1fde962bcdf8d5a87c137e98a836d93a146e54/merged/etc

Have I misunderstood something about the suggestion? Or is this a situation where the error message does not reflect the directory where the actual error occurred?

Thanks,
Blair

**Comment by mfblair** [comment]
Hi @rhatdan,

I've been experimenting with changing the labels as you suggested, but I haven't been able to work around the problem. When using native overlay, the rootless user always gets this error trying to launch a container from the shared image:

`[support@localhost containers]$ podman images`
`REPOSITORY                         TAG         IMAGE ID      CREATED      SIZE        R/O`
`registry.fedoraproject.org/fedora  latest      191682d67252  2 weeks ago  184 MB      true`
`[support@localhost containers]$ podman run -ti registry.fedoraproject.org/fedora:latest`
`Error: error creating mtab directory: chown` `/home/support/.local/share/containers/storage/overlay/1d1ba4dc89822ec745201b420c8a37c4e291788adfddcf143346dbb3876330fb/merged/etc: operation not permitted`

I thought it might help to better understand the intent of the labelling with semanage, and exactly when in the process this should be done.

You said:

> You labeled it for system containers. You need to do
> semanage fcontext -a -e $HOME/.local/share/containers /var/lib/mycontainers
	
From what I can follow, this would copy SELinux labels onto /var/lib/mycontainers to match the _containers directory under the rootless user's home_. **Do I have that right?**

Also, given the following sequence, when do the **semanage** and **restorecon** commands need to be done?
	
	1) Root creates /var/lib/mycontainers
	2) Root pulls image into /var/lib/mycontainers
	3) Root makes /var/lib/mycontainers world readable
	4) Rootless user creates storage.conf under their user home, **with** reference to /var/lib/mycontainers, but **without** reference to fuse overlay (so that we use native overlay)
	5) Rootless user confirms visibility to image with "podman images"
	6) Rootless user tries to launch container from image

Thanks,
Blair

**Comment by rhatdan** [comment]
Sorry I lost this message in the flood. Your ideas look correct.

**Comment by rhatdan** [comment]
Did you get any AVC messages when you ran your container?

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
with what Podman version is the issue happening?

**Comment by mfblair** [comment]
> Did you get any AVC messages when you ran your container?

No, from what I tell I haven't had any AVC messages:

[root@localhost ~]# grep -c "SELinux is preventing" /var/log/messages
0
[root@localhost ~]# grep -c "SELinux is preventing" /var/log/audit/audit.log
0

**Comment by mfblair** [comment]
> with what Podman version is the issue happening?

[root@localhost ~]# podman -v
podman version 3.3.1

**Comment by rhatdan** [comment]
You need to search for avc not "SELinux is preventing"

grep -i avc ...

**Comment by mfblair** [comment]
Here is the complete output of checking for "avc" in those log files:

```
[root@localhost ~]# grep -i avc /var/log/messages
[root@localhost ~]# grep -i avc /var/log/audit/audit.log
type=USER_AVC msg=audit(1634059868.849:168): pid=931 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_call interface=org.freedesktop.DBus.Properties member=GetAll dest=:1.197 spid=6639 tpid=6658 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=system_u:system_r:timedatex_t:s0 tclass=dbus permissive=0  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'UID="dbus" AUID="unset" SAUID="dbus"
type=USER_AVC msg=audit(1634059869.752:169): pid=931 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_call interface=org.freedesktop.timedate1 member=SetTimezone dest=:1.197 spid=6639 tpid=6658 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=system_u:system_r:timedatex_t:s0 tclass=dbus permissive=0  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'UID="dbus" AUID="unset" SAUID="dbus"
[root@localhost ~]# 
```

**Comment by mfblair** [comment]
Confirmed. **setenforce 0** made no difference...


```
[support3@localhost ~]$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED       SIZE        R/O
registry.fedoraproject.org/fedora  myversion   191682d67252  2 months ago  184 MB      false
registry.fedoraproject.org/fedora  latest      191682d67252  2 months ago  184 MB      true
[support3@localhost ~]$ podman run -ti registry.fedoraproject.org/fedora:latest
Error: error creating mtab directory: chown /home/support3/.local/share/containers/storage/overlay/7833dd47a373b3ee0ead8c1f01d9a0edfc79dc16bb5fc406f0e789a1f7a4e9a3/merged/etc: operation not permitted
[support3@localhost ~]$ su -
Password: 
[root@localhost ~]# setenforce 0
[root@localhost ~]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
[root@localhost ~]# exit
logout
[support3@localhost ~]$ podman run -ti registry.fedoraproject.org/fedora:latest
Error: error creating mtab directory: chown /home/support3/.local/share/containers/storage/overlay/d3673089a628880951962876f93ce03130737ab032afbc8132ef7f4145dc08e9/merged/etc: operation not permitted
```

**Comment by rhatdan** [comment]
Then most likely this is User Namespace.

$ podman unshare cat /proc/self/uid_map

I think there is something failing when you attempt to join user namespace and chown the mtab file to some other owner.

**Comment by rhatdan** [comment]
Since we got no futher info, I am closing.  Continue the conversation here, if you have more info.
