### ISSUE TITLE
Containerfile man page says FROM "must be first command"

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#3555]
The man page for the Containerfile says the `FROM` instruction MUST be the first instruction in the file.  Generally, that is the case, but one or more `ARG` instructions can also be the first instruction in the Containerfile.  The `FROM` stanza in the Containerfile man page just needs to be adjusted for this.

**Comment by derkoe** [comment]
ARG before FROM does not work with podman/buildah

**Comment by nalind** [comment]
Heading `ARG`s (those defined before the first `FROM` instruction) should be usable in the `FROM` instructions for any of the build's stages.

**Comment by derkoe** [comment]
Yes but only if the `ARG` is used in the `FROM`. When used after `FROM` the argument is undefined.

Here is the part from the Docker docs:
 > FROM may only be preceded by one or more ARG instructions, which declare arguments that are used in FROM lines in the Dockerfile.

**Comment by TomSweeneyRedHat** [comment]
@derkoe I think we're in violent agreement.  The problem is the man page now says that FROM "must" be the first line.  That's true for most cases, but not all.  I just want to tweak it with a note similar to your comment.

**Comment by rhatdan** [comment]
Lets add the line from Docker documentation.
