### ISSUE TITLE
Implement cache-from that is currently a NOOP

### ISSUE THREAD

**Issue by mitchellmaler** [containers/buildah#3584]
/kind feature

**Description**

Today when running docker build we make use of the cache-from flag to speed up builds that has layers that didn't change.

**Describe the results you expected:**

--cache-from to use an existing image to speed up build by using it as a cache.

**Comment by rhatdan** [comment]
This would need to be implemented in Buildah first, I believe so I moved it over here.
@flouthoc PTAL

**Comment by flouthoc** [comment]
This is already here as a dandling PR https://github.com/containers/buildah/pull/3574 , support for `from` will show up in a different PR for bunch of mount options.

**Comment by flouthoc** [comment]
I think this issue can be transferred to buildah.
