### ISSUE TITLE
buildah from --pull-never ignored when --arch specified

### ISSUE THREAD

**Issue by jawnsy** [containers/buildah#3596]
**Description**

Running buildah with --pull-never as well as an --arch causes images to be pulled.

**Steps to reproduce the issue:**
1. Ensure that all images are deleted
2. Run `buildah from --pull-never ubuntu`, a "image not known" error is returned
3. Run `buildah from --pull-never --arch=amd64 ubuntu`, the image is pulled :upside_down_face: 

**Describe the results you received:**

```shell-session
$ buildah images --all
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
$ buildah from --pull-never ubuntu:latest
ubuntu:latest: image not known
ERRO[0000] exit status 125                              
$ buildah from --pull-never ubuntu
ubuntu: image not known
ERRO[0000] exit status 125                              
$ buildah from --pull-never --arch=amd64 ubuntu
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob 7b1a6ab2e44d done  
Copying config ba6acccedd done  
Writing manifest to image destination
Storing signatures
ubuntu-working-container
```

**Describe the results you expected:**

I expected a similar error even with `--arch` - we shouldn't try to pull in that case.

**Output of `rpm -q buildah` or `apt list buildah`:**

```shell-session
$ apt list buildah
Listing... Done
buildah/testing,now 1.22.3+ds1-2 amd64 [installed]
buildah/testing 1.22.3+ds1-2 i386
```

**Output of `buildah version`:**

```shell-session
$ buildah version
Version:         1.22.3
Go Version:      go1.15.15
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.15.2
Git Commit:      
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

n/a

**Output of `cat /etc/*release`:**

```shell-session
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```shell-session
$ uname -a
Linux pattern 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```shell-session
$ cat /etc/containers/storage.conf
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by rhatdan** [comment]
@vrothberg is this something that you need to fix in containers/image or is this really a buildah issue?

**Comment by vrothberg** [comment]
> @vrothberg is this something that you need to fix in containers/image or is this really a buildah issue?

This rang a bell and I was sure we already fixed the issue but it seems we lost your PR (https://github.com/containers/common/pull/816) from the radar.  Could you revive it?
