### ISSUE TITLE
buildah login or pull does not work with esoteric usernames in HTTP_PROXY

### ISSUE THREAD

**Issue by lenox-joseph** [containers/buildah#3616]
/kind bug

**Description**

Podman/Buildah does not interact well with authenticated proxies that have a username of the format `domain\username` when reading from HTTP_PROXY or HTTPS_PROXY variables when performing `pull` or `login` operations. Depending on how the `\` is escaped or quoted, there is either an i/o timeout or a DNS issue where the url 'http' is attempted to be resolved. Other applications (such as `pip` are fine with the same HTTP_PROXY setting.

**Steps to reproduce the issue:**

1. Set proxy settings that have a username where the full username is `domain\username` via HTTPS_PROXY such that `env` shows 
`HTTPS_PROXY=http://domain\username:password@proxy.example.com` or 
`HTTPS_PROXY='http://domain\username:password@proxy.example.com'`

2. Attempt a `pull` or `login` command

**Describe the results you received:**
```bash
buildah login registry.access.redhat.com
Username: ....
Password:
authenticating creds for "registry.access.redhat.com": error pinging docker registry registry.access.redhat.com: Get "https://registry.access.redhat.com/v2/": proxyconnect tcp: dial tcp: lookup http on <dns server>:53: no such host
```

**Describe the results you expected:**
Login completes with no error.

**Output of `podman version`:**

```
Version:         1.21.1
Go Version:      go1.15.14
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.12.0
Git Commit:
Built:           Wed Dec 31 18:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `buildah info --debug`:**

```
{
    "debug": {
        "buildah version": "1.21.1",
        "compiler": "gc",
        "git commit": "",
        "go version": "go1.15.14"
    },
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "\"centos\"",
            "version": "8"
        },
        "MemFree": 48795283456,
        "MemTotal": 66982174720,
        "OCIRuntime": "crun",
        "SwapFree": 15770865664,
        "SwapTotal": 24008192000,
        "arch": "amd64",
        "cpus": 20,
        "hostname": "deathstar.tti",
        "kernel": "4.18.0-147.8.1.el8_1.x86_64",
        "os": "linux",
        "rootless": true,
        "uptime": "6690h 22m 26.36s (Approximately 278.75 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 93
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay.mount_program=/usr/bin/fuse-overlayfs",
            "overlay.mount_program=/usr/bin/fuse-overlayfs"
        ],
        "GraphRoot": "<redacted>",
        "GraphStatus": {
            "Backing Filesystem": "zfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 258
        },
        "RunRoot": "/run/user/1000"
    }
}

```

**Package info **

```
podman-3.2.3-1.el8.1.7.x86_64
buildah-1.21.1-1.el8.1.15.x86_64
```

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
https://github.com/containers/podman/issues/8032

**Comment by lenox-joseph** [comment]
Note that I could pull from behind an authenticated proxy when the username was `username@domain`, but something changed upstream of me. 

Other tooling I have (yum, elinks, etc) do play nice with the new username arrangement, but those have distinct username fields.

**Comment by rhatdan** [comment]
The issue is we don;t control how HTTP_PROXY environment variables are handled in golang.  Golang does.

**Comment by lenox-joseph** [comment]
Workaround: encode as %5C and yell at Golang.

**Comment by mtrmac** [comment]
Well, that’s not a workaround, `\` isn’t valid in that location in the first place, per RFC 3986.

Per the analysis in that other bug, I wouldn’t object to yelling at Golang :)

**Comment by lenox-joseph** [comment]
FWIW I've also yelled at my IT department.
