### ISSUE TITLE
bud: create non-existent WORKDIR with USER permissions

### ISSUE THREAD

**Issue by r10r** [containers/buildah#3620]
Hi there,

I just want to cross reference a docker issue which seems to  affect `buildah bud` to
See also https://github.com/docker/cli/issues/3346

```
buildah --version
buildah version 1.23.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

Building the following Dockerfile with `buildah bud`

````Dockerfile
FROM docker.io/library/alpine:latest
RUN adduser -D http -h /home/http
USER http
RUN id
WORKDIR /home/http/public
RUN ls -ld $PWD
RUN touch foobar
````

fails with the following output

```bash
[ruben@k8s-cluster9-controller test]$ buildah bud
STEP 1/7: FROM docker.io/library/alpine:latest
STEP 2/7: RUN adduser -D http -h /home/http
STEP 3/7: USER http
STEP 4/7: RUN id
uid=1000(http) gid=1000(http)
STEP 5/7: WORKDIR /home/http/public
STEP 6/7: RUN ls -ld $PWD
drwxr-xr-x    2 root     root          4096 Nov  9 06:44 /home/http/public
STEP 7/7: RUN touch foobar
touch: foobar: Permission denied
error building at STEP "RUN touch foobar": error while running runtime: exit status 1
ERRO[0005] exit status 1 
```

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
@r10r Interested in opening a PR to fix?

**Comment by flouthoc** [comment]
I'll check this thanks.

**Comment by r10r** [comment]
@rhatdan Yes, I can take a look at it and send a PR. 
I'll wait for @flouthoc to confirm the issue.

**Comment by flouthoc** [comment]
@r10r Sure its yours :)

**Comment by rhatdan** [comment]
@r10r you got it.

**Comment by flouthoc** [comment]
@r10r Just a friendly ping

**Comment by r10r** [comment]
Sorry for the high round-trip time ;) I'll look at it between the next two weeks.

**Comment by rhatdan** [comment]
@r10r Did you ever look into it?

**Comment by r10r** [comment]
@rhatdan Sorry no. I'll try to send a pull request by the end of the week.
Can you please give me a hint where I can find the test suite for the bud command.

**Comment by flouthoc** [comment]
@r10r this should help https://github.com/containers/buildah/blob/main/tests/bud.bats

**Comment by r10r** [comment]
Thanks.

**Comment by rhatdan** [comment]
I have been playing with this and have been debating with @nalind about whether or not we should do it. The issue is whether or not Docker compatibility versus docker buildkit compatibility.
Second thing to understand it this is more complicated then I first thought and  I have been working on a potential fix.

**Comment by Kai-Chen** [comment]
Ran into the same issue and was about to file a new ticket if I hadn't checked here.
Currently limping along with a `RUN mkdir -p` layer before WORKDIR.

@rhatdan @nalind I'm curious: what are the pros for keeping backward compatibility with a bug?  -- in this particular case, I find it hard to imagine that anyone is relying on the bug's behavior such that a fix would break currently running systems.

**Comment by giuseppe** [comment]
something like the following patch seems to solve the issue for me:

```diff
diff --git a/run_linux.go b/run_linux.go
index d2420b91..66ac5da1 100644
--- a/run_linux.go
+++ b/run_linux.go
@@ -198,9 +198,19 @@ func (b *Builder) Run(command []string, options RunOptions) error {
 	}
 	rootIDPair := &idtools.IDPair{UID: int(rootUID), GID: int(rootGID)}
 
+	uid, gid := spec.Process.User.UID, spec.Process.User.GID
+	if spec.Linux != nil {
+		uid, gid, err = util.GetHostIDs(spec.Linux.UIDMappings, spec.Linux.GIDMappings, uid, gid)
+		if err != nil {
+			return err
+		}
+	}
+
+	idPair := &idtools.IDPair{UID: int(uid), GID: int(gid)}
+
 	mode := os.FileMode(0755)
 	coptions := copier.MkdirOptions{
-		ChownNew: rootIDPair,
+		ChownNew: idPair,
 		ChmodNew: &mode,
 	}
 	if err := copier.Mkdir(mountPoint, filepath.Join(mountPoint, spec.Process.Cwd), coptions); err != nil {
diff --git a/vendor/github.com/openshift/imagebuilder/builder.go b/vendor/github.com/openshift/imagebuilder/builder.go
index b0e9d4f5..f9a586b4 100644
--- a/vendor/github.com/openshift/imagebuilder/builder.go
+++ b/vendor/github.com/openshift/imagebuilder/builder.go
@@ -377,12 +377,6 @@ func (b *Builder) Run(step *Step, exec Executor, noRunsRemaining bool) error {
 		return err
 	}
 
-	if len(b.RunConfig.WorkingDir) > 0 {
-		if err := exec.EnsureContainerPath(b.RunConfig.WorkingDir); err != nil {
-			return err
-		}
-	}
-
 	for _, run := range runs {
 		config := b.Config()
 		config.Env = step.Env
```

@rhatdan @nalind if you are fine with this approach, I will clean it up and add some tests

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/buildah/pull/3840
