### ISSUE TITLE
GLib-ERROR ... gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'

### ISSUE THREAD

**Issue by cevich** [containers/buildah#3633]
**Description**

The daily Cirrus-cron runs on the `release-1.22` and `release-1.23` are consistently failing the F33 `copy-preserving-extended-attributes` test beginning on November 16th.  No runs prior to this date produced this error.  The tests pass under F34.  The issue does not appear to affect tests run on the `main` branch.

**Steps to reproduce the issue:**
1. In a PR or directly on one of the affected branches
2. Run ***Integration fedora-33 w/ vfs*** -and/or- ***Integration fedora-33 w/ overly***

**Describe the results you received:**

([source task log](https://cirrus-ci.com/task/5995611200684032?logs=integration_test#L1114))

```
[+1118s] not ok 335 copy-preserving-extended-attributes
...cut...
[+1118s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah from --quiet --signature-policy /var/tmp/go/src/github.com/containers/buildah/tests/./policy.json registry.fedoraproject.org/fedora-minimal
[+1118s] # fedora-minimal-working-container
[+1118s] # $ /var/tmp/go/src/github.com/containers/buildah/tests/./../bin/buildah run fedora-minimal-working-container microdnf -y install /usr/bin/getfattr /usr/bin/setfattr /usr/sbin/setcap
[+1118s] # 
[+1118s] # (microdnf:1): GLib-ERROR **: 17:08:59.317: file ../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
[+1118s] # container exited on trace/breakpoint trap
[+1118s] # error while running runtime: exit status 1
...cut...
```

**Describe the results you expected:**

Prior to Nov. 16th this test was passing on these branches.

**Output of `rpm -q buildah` or `apt list buildah`:**

Built from source

**Output of `buildah version`:**

```
Version:         1.22.4-dev
Go Version:      go1.15.13
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.15.2
Git Commit:      e4e12ca
Built:           Wed Nov 17 10:48:44 2021
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

N/A

**Output of `uname -a`:**

N/A

**Output of `cat /etc/containers/storage.conf`:**

N/A

**Podman system info**

```
podman system info  # /var/tmp/go/src/github.com/containers/buildah/./contrib/cirrus/logcollector.sh:19 in main()
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 2
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: cirrus-task-5995611200684032
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.12.14-200.fc33.x86_64
  linkmode: dynamic
  memFree: 2889281536
  memTotal: 4115738624
  ociRuntime:
    name: crun
    package: crun-0.19.1-3.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 36m 16.97s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1620741227
  BuiltTime: Tue May 11 08:53:47 2021
  GitCommit: ""
  GoVersion: go1.15.11
  OsArch: linux/amd64
  Version: 3.1.2
```

**Installed packages**

```
conmon-2.0.27-2.fc33-x86_64
containernetworking-plugins-1.0.0-0.1.rc1.fc33-x86_64
containers-common-1-16.fc33-noarch
container-selinux-2.160.2-1.fc33-noarch
crun-0.19.1-3.fc33-x86_64
libseccomp-2.5.0-3.fc33-x86_64
package cri-o-runc is not installed
package libseccomp2 is not installed
podman-3.1.2-2.fc33-x86_64
runc-1.0.0-378.rc95.fc33-x86_64
skopeo-1.3.0-1.fc33-x86_64
slirp4netns-1.1.9-1.fc33-x86_64
```

**Comment by nalind** [comment]
Please update the version of containers-common in the VM to get an updated version of the default seccomp filter configuration (`/usr/share/containers/seccomp.json`).  The current version for Fedora 33 is `containers-common-1-20.fc33`.

**Comment by rhatdan** [comment]
Can we just drop Fedora 33 testing?

**Comment by cevich** [comment]
Reminder: This is only an issue (some how suddenly) on the two release branches, it doesn't affect `main`.

> Please update the version of containers-common in the VM 

I really hate to do that on release branches, those environments are suppose to be long-term stable in order to support any future backport work.

> Can we just drop Fedora 33 testing?

Maybe?  Again these are release branches, so it probably depends on their age...which seems is "not that old".  Though it's really up to you.  Is the risk of a disabled-test missing something on a backport worth the effort to maintain the daily runs?

In any case...this all begs the question: How the heck did these tests start spewing this error suddenly, on (supposedly) unchanging release branch CI environments?  That's what's got my eyebrows in a bunch (and one ear raised).

**Comment by rhatdan** [comment]
F33 is dead, drop it from the tests.

**Comment by nalind** [comment]
... as of 30 November.  This is a general problem of images using syscalls that we didn't know we'd need to allow in the default seccomp profile when the profile was last revised for an earlier release.

**Comment by cevich** [comment]
okay, those are the magic words :smile:

**Comment by cevich** [comment]
> This is a general problem of images using syscalls that we didn't know we'd need

BTW, @nalind testing really should only depend on static/fixed/unchanging inputs, including container images.  For example, tests should avoid using `latest` images, use a version tag instead unless the image is known to be kept static (like the ones we maintain copies of in quay).  That's how this problem can be avoided (in the future).

There's an exception case I'm aware of with `quay.io/libpod/fedora-minimal:latest` that needs taking care of.  I'll open a separate PR for that.

**Comment by cevich** [comment]
https://github.com/containers/buildah/pull/3640
