### ISSUE TITLE
Building using the docker image *without* privileged mode

### ISSUE THREAD

**Issue by dg424** [containers/buildah#3661]
Hi,

I'm unable to build using the official image here - https://quay.io/repository/containers/buildah - without using the --privileged flag. Does buildah work without having root/system-level privileges ?

$ docker run --rm -it quay.io/containers/buildah:latest bash
Unable to find image 'quay.io/containers/buildah:latest' locally
latest: Pulling from containers/buildah
4545346f2a49: Pull complete 
a14e2cbf1395: Pull complete 
45f226666774: Pull complete 
d9b379f55b51: Pull complete 
1c43bac99d23: Pull complete 
9defd66bd597: Pull complete 
Digest: sha256:478a131c9f61168b039607ee5e8290fcac2119200ea61a61bfc9dd9f1eb956f1
Status: Downloaded newer image for quay.io/containers/buildah:latest
[root@fe92df20d1f2 /]# buildah from alpine
Error during unshare(CLONE_NEWUSER): Operation not permitted
ERRO[0000] error parsing PID "": strconv.Atoi: parsing "": invalid syntax 
ERRO[0000] (unable to determine exit status)            
[root@fe92df20d1f2 /]# exit

$ docker version
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by Hello71** [comment]
>  Error during unshare(CLONE_NEWUSER): Operation not permitted

you need to allow nested containers

**Comment by dg424** [comment]
But to allow nested containers means that I will need to run buildah with the --privileged flag. Is there a unprivileged/rootless way to build images using buildah ?

**Comment by rhatdan** [comment]
I talk a lot about this in this article.
https://www.redhat.com/sysadmin/podman-inside-container
This is about podman build but buildah has similar features.
