### ISSUE TITLE
Building with "--squash" doesn't have any caching mechanism

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/buildah#3665]
**Description**

When building with podman --squash, there is no caching mechanism that would allow to not re-run long running operations (like dnf install -y some-package). One would expect that the squashed version of all layers might be cached if re-run with the exact same input.

**Steps to reproduce the issue:**
1. Start a podman in podman, using the very latest podman version available:
```
rgeissler@NCEOBERHEL80009.rnd.amadeus.net[dev]:~$ podman run -t -i --rm --privileged --pull=always docker://quay.io/podman/upstream:latest
Trying to pull quay.io/podman/upstream:latest...
Getting image source signatures
Copying blob 6ffc5b8308c8 skipped: already exists
Copying blob c49946d7b2bc skipped: already exists
Copying blob ebee3d32ce92 skipped: already exists
Copying blob dd53b67b4cc9 skipped: already exists
Copying blob 6785b0eb3e35 skipped: already exists
Copying blob 4545346f2a49 skipped: already exists
Copying blob 33939db6ec56 skipped: already exists
Copying blob 71f578d778fe [--------------------------------------] 0.0b / 0.0b
Copying config 2f32afa5f3 done
Writing manifest to image destination
Storing signatures
[root@3a163a7c92e3 /]# podman version
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.16.11
Git Commit:   3b21ba2f623da5a4228a6236c684d1d0b245f240
Built:        Wed Dec  8 08:07:16 2021
OS/Arch:      linux/amd64
```
2. Prepare some dummy Dockerfile:
```
[root@3a163a7c92e3 /]# mkdir src
[root@3a163a7c92e3 /]# cd /src
[root@3a163a7c92e3 src]# cat >Dockerfile <<END_OF_FILE
FROM fedora:latest
RUN touch /file1
RUN touch /file2
END_OF_FILE
```
3. Build it once with --squash, it gets built as expected:
```
[root@3a163a7c92e3 src]# podman build --squash .
STEP 1/3: FROM fedora:latest
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 4545346f2a49 done
Copying config 3059bef432 done
Writing manifest to image destination
Storing signatures
STEP 2/3: RUN touch /file1
STEP 3/3: RUN touch /file2
COMMIT
Getting image source signatures
Copying blob 80f516d0e5a8 skipped: already exists
Copying blob 8de9f1e3f0e5 done
Copying config 5475839599 done
Writing manifest to image destination
Storing signatures
--> 54758395999
5475839599913860f52731df6828e8829fa3f749998a515d9ada62cc06e7d989
```
4. Build it a second time, still with --squash: it get's fully re-built, without any caching mechanism:
```
[root@3a163a7c92e3 src]# podman build --squash .
STEP 1/3: FROM fedora:latest
STEP 2/3: RUN touch /file1
STEP 3/3: RUN touch /file2
COMMIT
Getting image source signatures
Copying blob 80f516d0e5a8 skipped: already exists
Copying blob 9a3cd17ebddd done
Copying config 8d052016ea done
Writing manifest to image destination
Storing signatures
--> 8d052016ea7
8d052016ea77063f42034ffda84358244d20c3cca4d97d5e0bee776e6701ae04
```

**Describe the results you received:**

The second build is not cached, it is re-run fully.

**Describe the results you expected:**
One might expect that the second build is cached from the first one. The same way that layers are being cached when "--squash" is not used. I do understand that by definition --squash *CANNOT* use layer caching, still would it be possible to consider caching on the set of all the squashed-layers and cache the whole squashed result ?

I definitely expect that implementing this might not be trivial at all, if at all possible. In which case I would expect that this impossibility to have both caching and --squash for now is somehow mentioned in the man page of podman-build, in the --squash flag description: https://docs.podman.io/en/latest/markdown/podman-build.1.html#squash

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
Thanks I'll check this. @Romain-Geissler-1A does `docker` supports it ? I'll try to verify it with `docker`.

**Comment by Romain-Geissler-1A** [comment]
Mmmmh actually I have not even tried. I am trying to stop using Docker as much as possible and encourage everyone in my company to do so ;)

**Comment by rhatdan** [comment]
SGTM

**Comment by flouthoc** [comment]
@Romain-Geissler-1A Thanks for reporting this. So `buildkit` indeed performs caching while `docker experimental` and `docker` does not. But anyways I think we should provide caching for `squash` i am checking this.

**Comment by Romain-Geissler-1A** [comment]
I tried to change a bit podman here: https://github.com/containers/podman/compare/main...Romain-Geissler-1A:main but actually the behavior of buildah seems strange. It seems it's impossible to squash only the newly created layers *AND* keep the intermediate layers (in other words, buildah has flag `--squash` which correspond to podman `--squash-all` but buildah seems to have no counterpart to podman's `--squash`.

So, should the behavior of buildah's `--squash` flag to be modified (ie only act on newly created layers) and a new `--squash-all` flag be introduced, in order to behave like podman ?
