### ISSUE TITLE
New buildkit-mount tests: fail in gating

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3667]
There's a bunch of new tests in bud.bats, all of them referring to `tests/bud/buildkit-mount`. These are failing in gating:
```
not ok 276 bud-with-mount-like-buildkit
...
# STEP 3/3: RUN --mount=type=bind,source=.,target=/test,z cat /test/input_file
# error building at STEP "RUN --mount=type=bind,source=.,target=/test,z cat /test/input_file": error resolving mountpoints for container "57c3e5eb268e14a8b8bca356504082f5869e66133319cbfeb75533d3d4f26c82": relabeling content in /usr is not allowed
# [ rc=125 (** EXPECTED 0 **) ]
```
Reason: in gating, tests are installed via RPM into `/usr/share/buildah/tests/system`.

I'm well past my done-for-the-week point, and can't fix this today or tomorrow. I would be oh-so-grateful if someone were to fix this soon, but if not I'll take a stab at it on Monday.

**Comment by flouthoc** [comment]
@edsantiago Most of these tests were added by me. This looks like `selinux` issue to me but not why it passes in our CI and not on gating tests.

**Comment by rhatdan** [comment]
Someone added a function to selinux that does.
```
// Prevent users from relabeling system files
func badPrefix(fpath string) error {
	if fpath == "" {
		return ErrEmptyPath
	}

	badPrefixes := []string{"/usr"}
	for _, prefix := range badPrefixes {
		if strings.HasPrefix(fpath, prefix) {
			return fmt.Errorf("relabeling content in %s is not allowed", prefix)
		}
	}
	return nil
}
```
Which is throwing this error.  Can we move the gating tests to /var/tmp?

**Comment by rhatdan** [comment]
I agree what that.

**Comment by flouthoc** [comment]
@edsantiago I agree with you, I'll rectify these tests to do testing in a tmp dir.

**Comment by flouthoc** [comment]
I think above PR would close the issue.
