### ISSUE TITLE
Invalid value for memory-swap: invalid size: '-1'

### ISSUE THREAD

**Issue by ripta** [containers/buildah#3675]
**Description**

`podman build` in the latest release of podman (v3.4.4) rejects the `--memory-swap` value of `-1`. Minimal reproduction:

```
❯ cat Dockerfile
FROM ubuntu:20.04
WORKDIR /moo

❯ podman build --memory-swap -1 .
Error: invalid value for memory-swap: invalid size: '-1'
```

**Describe the results you received:**
The flag value `-1` is rejected. I tried other values, including `1024M` and `1G` seem to work as expected.

**Describe the results you expected:**
I expected the flag value `-1` to mean unlimited, as documented on `podman build --help`:

```
      --memory-swap string                           swap limit equal to memory plus swap: '-1' to enable unlimited swap
```

**Output of `podman version` if reporting a `podman build` issue:**

```
❯ podman version
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Git Commit:   f6526ada1025c2e3f88745ba83b8b461ca659933
Built:        Wed Dec  8 13:13:57 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 12:25:37 2021
OS/Arch:      linux/amd64

❯ podman machine list
NAME                     VM TYPE     CREATED         LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        40 minutes ago  Currently running  2           4.295GB     10.74GB
```

Thanks!

**Comment by flouthoc** [comment]
@ripta We use `docker` helpers to parse human readable value for `swap` which is ok for `memory` but `swap` also accepts exception of `-1` which is not honored by the same helper. So above PR handlers that.
