### ISSUE TITLE
changed storage driver from overlay to overlay2

### ISSUE THREAD

**Issue by 321sp** [containers/buildah#3682]
**Description**

**Steps to reproduce the issue:**
1. change storage driver to overlay2 from overlay creating symlink between overlay and overlay2 on /var/lib/containers/storage/
2.
3.

**Describe the results you received:**
Error: error creating build container: error creating container: error creating read-write layer with ID "fe39354233f80b7a594f9cd1e7a2b 873ea2ed8d0eec64f2b3be8ebbab5be06b1": Stat /var/lib/containers/storage/overlay2/72e830a4dff5f0d5225cdc0a320e85ab1ce06ea5673acfe8d83a764 5cbd0e9cf: no such file or directory

facing this issue when changed storage driver to overlay2 and also created symlink between overlay and overlay2

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
buildah-1.19.7-1.module+el8.4.0+11818+341460ad.x86_64
```

**Output of `buildah version`:**

```
(paste your output here)
Version:         1.19.8
Go Version:      go1.15.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.5
Git Commit:
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        Fri Oct  8 13:26:46 2021
OS/Arch:      linux/amd64

```

**Output of `cat /etc/*release`:**

```
(paste your output here)

NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
Red Hat Enterprise Linux release 8.4 (Ootpa)
Red Hat Enterprise Linux release 8.4 (Ootpa)

```

**Output of `uname -a`:**

```
(paste your output here)
Linux k0011935 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Mon Oct 18 14:34:11 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
[storage]
driver = "overlay2"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]

```

**Comment by rhatdan** [comment]
Don't use overlay2, it is the same as overlay, they are just aliases and we are trying to get rid of overlay2 support.

**Comment by rhatdan** [comment]
Overlay2 is not set to error out in current release.
