### ISSUE TITLE
podman build --cpuset-cpus= is not working

### ISSUE THREAD

**Issue by vans163** [containers/buildah#3700]
/kind bug

**Description**

using `podman build` with `--cpuset-cpus=` does not bind the threads to the physical cores. `podman run` works fine.

**Steps to reproduce the issue:**

```dockerfile
FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y stress
RUN stress --cpu 32
CMD ["/bin/bash"
```
```
podman build --cpuset-cpus=0 --tag test .
```
Observe as all CPUs are flooded at 100% with work.

```
podman run --cpuset-cpus=0 --tag test .
```
Observe as only CPU 0 is flooded at 100% with work.

**Describe the results you expected:**

Expect `podman build` to work equivalent to `podman run`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.4.4
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 32
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: video2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.13.0-19-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 129869611008
  memTotal: 135063539712
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.1-0ubuntu3
      spec: 1.0.2-dev
      go: go1.17.3
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 86h 30m 54.14s (Approximately 3.58 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 28
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1641839038
  BuiltTime: Mon Jan 10 18:23:58 2022
  GitCommit: f6526ada1025c2e3f88745ba83b8b461ca659933
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/jammy,now 3.2.1+ds1-2ubuntu3 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 
 It would be nice to also have `--cpus` available to podman build instead of just podman run.

**Comment by rhatdan** [comment]
Looks like this is a podman issue.

**Comment by rhatdan** [comment]
I am trying to scan down through the code and it looks like both pass the same spec to crun. So not sure why you are seeing differences.

**Comment by rhatdan** [comment]
Please check if Buildah has the same problem.

**Comment by vans163** [comment]
> Please check if Buildah has the same problem.
I can confirm buildah has the same problem
```
buildah build --cpuset-cpus=0,1 --tag test_ping .
```

**Comment by rhatdan** [comment]
Weird since Podman and Buildah seem to use the exact setup the OCI runtime the same.

@giuseppe Thoughts?

**Comment by vans163** [comment]
> Weird since Podman and Buildah seem to use the exact setup the OCI runtime the same.
> 
> @giuseppe Thoughts?

Im wondering if anyone else runs that exact same code does it happen for them?  I am on Jammy Dailies, 22.04 Ubuntu. With 5.13 kernel and cgroupsV2, maybe something is misconfigured. Though.. for podman `--cpuset-cpus=0` correctly works, maybe buildah is not playing nice with latest releases?

**Comment by giuseppe** [comment]
> Weird since Podman and Buildah seem to use the exact setup the OCI runtime the same.
> 
> @giuseppe Thoughts?

are we using the systemd cgroup manager with buildah?

If we are using cgroupfs, then it works only for root

**Comment by rhatdan** [comment]
Since lack of response, I am going to close.  Reopen if this is still an issue.

**Comment by vans163** [comment]
This is an issue. No one replied to it

**Comment by giuseppe** [comment]
yes I think this is an issue in buildah that is not using systemd for the cgroup backend

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/buildah/pull/3780
