### ISSUE TITLE
remove git-validation, add DCO

### ISSUE THREAD

**Issue by kolyshkin** [containers/buildah#3722]
Currently, this repo uses a cirrus-ci job which installs and runs vbatts/git-validation to check
 - whether commit line subject is not too long
 - whether commit has signed-off-by

I suggest to drop git-validation and replace it with a GHA CI job (as implemented in PR #3723 ). It already does subject length check, but does not do a DCO check, thus this issue :)

One thing that needs to be added is https://github.com/apps/dco (this should be trivial to add if you are repo admin). Once enabled, this adds a DCO check to commit PRs.

**Comment by kolyshkin** [comment]
Would be nice if the above (adding https://github.com/apps/dco) can be implemented before merging #3723

**Comment by TomSweeneyRedHat** [comment]
@cevich WDYT?

**Comment by kolyshkin** [comment]
So, now when #3723 is merged, I guess we have no DCI check in place.

Here's a PR to demonstrate it: https://github.com/containers/buildah/pull/3730

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
Oh yeah, I'm totally in favor of this.  It's much easier to use than vbatts/git-validation.  I'll add the app. so all containers repos can use it.

**Comment by cevich** [comment]
App added.

**Comment by cevich** [comment]
So this does work, my only gripe is it includes a button for "Set DCO to pass" - permitting folks to manually bypass a failure.  I'd be in favor of disabling this feature, assuming it's quick/easy to do.  I just don't have time to investigate ATM.
