### ISSUE TITLE
test failure: run --network should override build --network: error while running runtime

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3771]
New failure in [f36 CI](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/108095/testReport/(root)/tests/root_test/):
```
not ok 603 run --network should override build --network
# (from function `die' in file /usr/share/buildah/test/system/helpers.bash, line 250,
#  from function `run_buildah' in file /usr/share/buildah/test/system/helpers.bash, line 237,
#  in test file /usr/share/buildah/test/system/run.bats, line 698)
#   `run_buildah run --network=private $cid wget google.com' failed
# /usr/share/buildah/test/system /var/str
# $ /usr/bin/buildah from --network=none --quiet --pull=false --signature-policy /usr/share/buildah/test/system/policy.json alpine
# alpine-working-container
# $ /usr/bin/buildah run alpine-working-container wget google.com
# wget: bad address 'google.com'
# error while running runtime: exit status 1
# [ rc=1 (expected) ]
# $ /usr/bin/buildah run --network=private alpine-working-container wget google.com
# wget: bad address 'google.com'
# error while running runtime: exit status 1
# [ rc=1 (** EXPECTED 0 **) ]
```
Easily reproduces on my f35 laptop with main @ 08de1f95cbaca3d7664a9157dffba022e2bb8ed7 ... but it also fails on my laptop using `/usr/bin/buildah` (1.23.1-1.fc35) ??? I configured my laptop to use netavark (for podman), could that have anything to do with it?

**Comment by Luap99** [comment]
I cannot reproduce on my laptop, is it possible that you mixed cni and netavark on your laptop?
Does f36 runs the test with netvark or cni?

**Comment by edsantiago** [comment]
I can't reproduce on f37 rawhide. podman is using netavark, I have no idea what buildah is using. There are no recent buildah runs in bodhi. I'll keep this open until the next bodhi run, at which time I'll see if this is still a problem in gating tests.

**Comment by edsantiago** [comment]
Test passes on [buildah-1.25.1-1.fc37 bodhi](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/127187/testReport/(root)/tests/root_test/):
```
ok 612 run --network should override build --network
```
...so I guess this is resolved.
