### ISSUE TITLE
buildah run: error opening "/etc/cni/net.d/cni.lock": creating locker directory: mkdir /etc/cni: permission denied

### ISSUE THREAD

**Issue by enku** [containers/buildah#3783]
**Description**

I've built containers with buildah <= 1.23.1 (in a systemd container, if that matters). The containers were built with `--cap-add=CAP_SYS_PTRACE` and they are root-less containers.  With buildah <= 1.23.1 I have been able to `buildah run` these containers just fine.  However since upgrading to 1.24.1 I cannot run these containers.  I get errors like:

```
$ buildah run testing-root python --version
error reading build container "testing-root": error opening "/etc/cni/net.d/cni.lock": creating locker directory: mkdir /etc/cni: permission denied
```

Is this a bug or something extra I need to do now that I've upgraded to 1.24?

**Steps to reproduce the issue:**
With buildah 1.24.1:
1. As non-root. Create a container with `CAP_SYS_PTRACE`: `c=$(buildah from <image> --cap-add=CAP_SYS_PTRACE ...)`
2. Attempt to run the container: `buildah run $c -- <command>`

**Describe the results you received:**

Error message as describe above and buildah exists with status 125.

**Describe the results you expected:**

buildah runs the given command in the given container

**Output of `rpm -q buildah` or `apt list buildah`:**

This is Gentoo Linux (should I report the issue there?) but

```
$ equery l buildah
 * Searching for buildah ...
[IP-] [  ] app-containers/buildah-1.24.1:0
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.24.1
Go Version:      go1.17.7
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.0.1
image Version:   5.19.1
Git Commit:      28f7884b
Built:           Tue Feb 15 13:32:48 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

```
Gentoo Base System release 2.7
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
```

**Output of `uname -a`:**

```
Linux jenkins 5.16.9-gentoo #1 SMP Fri Feb 11 18:28:15 UTC 2022 x86_64 Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz GenuineIntel GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by Luap99** [comment]
If you create a new container with buildah from does it work?

**Comment by enku** [comment]
> If you create a new container with buildah from does it work?

Yes, that appears to work:

```
$ c1=`buildah from python:3.10`                       
$ buildah run $c1 -- python --version
Python 3.10.2
$ c2=`buildah from --cap-add=CAP_SYS_PTRACE python:3.10`
$ buildah run $c2 -- python --version
Python 3.10.2
$ buildah run lighthouse-root -- python --version
error reading build container "lighthouse-root": error opening "/etc/cni/net.d/cni.lock": creating locker directory: mkdir /etc/cni: permission denied
ERRO[0000] exit status 125                              
```

`lighthouse-root` is a container that was built from an earlier version of buildah.

**Comment by Luap99** [comment]
I don't think this will work with existing container since they effectively contain a invalid config. They have a cni config dir set to a path which can only be used by root.
Previous version would never use cni path as rootless but this now changed with 1.24.

**Comment by Luap99** [comment]
This will not work when you run rootless since you cannot change /etc as rootless user. I recommend to recreate your containers. I am not sure if we support backwards compat, @rhatdan @nalind WDYT?

**Comment by flouthoc** [comment]
@enku I also think a container recreate is easier here. Would there be any issue of you just recreate the container since you already have the image ? Could you let us know if there is any problem with recreating the containers so we could provide a possible solution there ?

**Comment by enku** [comment]
That's going to be a lot of containers to recreate.  Also `buildah rm` of the existing containers results in the same error.

I have the base image but the containers are wildly different than the ones from which they are based.  Is there a way I can dump the container to a new image (commit I think gives me the same error).  Oh I think I could go back to 1.23 and create images but would that work?

**Comment by flouthoc** [comment]
@enku Does `buildah commit` works for you as of now ? If not then sure you could commit your containers to images and then migrate.

**Comment by flouthoc** [comment]
@enku Try `buildah commit containerID newImageName` from `1.24.1` first and see if it throws error otherwise , you could commit images from `1.23` and then migrate to a newer version.

**Comment by enku** [comment]
FYI, with 1.24.1:
```
$ buildah commit base-root base-root-new
error reading build container "base-root": error opening "/etc/cni/net.d/cni.lock": permission denied
ERRO[0000] exit status 125           
```

**Comment by enku** [comment]
> @enku Try `buildah commit containerID newImageName` from `1.24.1` first and see if it throws error otherwise , you could commit images from `1.23` and then migrate to a newer version.

Commiting with 1.23 then removing the container with 1.23 and then re-creating with 1.24 works, though it's slow.

**Comment by enku** [comment]
I've been able to get the containers running again by doing the following:

1. Downgrade to `buildah-1.23`
2. `buildah commit <container> <image>`
3. `buildah rm <container>`
4. Upgrade to `buildah-1.24.1`
5. `buildah --name <container> --from --cap-add=CAP_SYS_PTRACE <image>`

My issue no longer exists, however is this something likely to happen to others or am I unique here. I never explicitly set a cni directory when installing buildah a long ways back and never know about this problem until updating. Might the newer versions be able to give a more helpful error message?  I did try searching the web for a solution before posting here but I found nothing helpful.

**Comment by flouthoc** [comment]
@enku I think others can face this issue as well if they try to reuse the container which was created with older version but also I am not sure if its a good idea to treat build containers as stateful items so I am not sure if there's gonna be lot of cases like these.

But lets see maybe we can add this in troubleshooting docs. Interested in opening a PR for adding this into troubleshooting docs ?

I am closing this issue since problem is resolved for you.  But feel free to reopen if you see any issues again or continue discussion below.

**Comment by guystreeter** [comment]
I just upgraded my system to Fedora 36. I can't remove a container built on Fedora 35 because of this error. I do not have an older version of buildah to downgrade to. What do I do?

**Comment by TomSweeneyRedHat** [comment]
@guystreeter if you have podman on board too, you could use the big hammer `podman system reset --force`.  Or the other big hammers:
`rm -rf /var/lib/containers/*` # for rootful
`rm -rf $HOME/.local/share/containers/*` # for rootless

**Comment by jistr** [comment]
I faced the same issue with rootless buildah after upgrading to Fedora 36, i've been able to remove rootless buildah containers without affecting other rootless container storage, by temporarily changing the permissions on `cni.lock` file:

```
sudo chmod a+w /etc/cni/net.d/cni.lock
buildah rm -a
sudo chmod go-w /etc/cni/net.d/cni.lock
```

**Comment by nalind** [comment]
I think #3697 only fixed things for build containers at create-time.

**Comment by Luap99** [comment]
Well I never got an answer on https://github.com/containers/buildah/issues/3783#issuecomment-1040430231 so I didn't look further into it.
Rootless buildah does not use the network backend so we could just add a rootless check and set the interface to nil and not initialize it.

**Comment by arizvisa** [comment]
> This is strange rootless buildah should not be touch /etc directory.

Yeah, I thought it was super weird too.
Anyways, I tracked it down and it resulted in a CVE (https://access.redhat.com/errata/RHSA-2022:8431). It's just a lock file and probably just a remnant, but the commit that introduced it was https://github.com/containers/podman/commit/fe3faa517e1bbc3b2e82afaae32d8712c844fdae which was then fixed by https://github.com/containers/podman/commit/836fa4c493c3809da4bbcbbec0bf5ceb954e7410.

**Comment by Luap99** [comment]
@arizvisa This bug is not related to any CVE. Your link a errata contains security fixes and normal bug fixes. You can check the CVE numbers for their context. It has nothing to do with this here. Also your linked podman commits have nothing to do with it.
