### ISSUE TITLE
buildah always inserts /bin/sh -c

### ISSUE THREAD

**Issue by fboerman** [containers/buildah#3787]
**Description**
when I build a container image and change the entrypoint buildah wil always insert /bin/sh -c in front of it

**Steps to reproduce the issue:**
1. create buildah image
2. set entrypoint to for example /go/bin/foo ie ```buildah config --entrypoint "/go/bin/foo" imgname```
3. set a cmd ie ```buildah config --cmd "serve" imgname```
4. commit the image
5. create a container with this image
6. observe with inspect that /bin/sh -c is in front of /go/bin/foo and it wont go away

**Describe the results you received:**
incorrect entrypoint

**Describe the results you expected:**
entrypoint exactly as I specified

**Output of `rpm -q buildah` or `apt list buildah`:**
I run Arch

**Output of `buildah version`:**

```
buildah version 1.24.1 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

**Output of `cat /etc/*release`:**
```
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo

```

**Output of `uname -a`:**

```
Linux Horus 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
Try
 buildah config --entrypoint '["/go/bin/foo"]'  imgname

**Comment by flouthoc** [comment]
> Try buildah config --entrypoint '["/go/bin/foo"]' imgname

Passing a valid json array is the right way to achieve this as mentioned in the above comment. 

@fboerman I'm closing this issue but feel free to re-open if anything is unresolved.
