### ISSUE TITLE
Where did the Containerfile.5.md go?

### ISSUE THREAD

**Issue by FilBot3** [containers/buildah#3802]
Was going to reference someone to the man page for it, but it's not here.

I expected to see it in `docs/Containerfile.5.md` but I don't see it.

**Comment by flouthoc** [comment]
Hi @FilBot3 , Thanks for creating the issue i think it was moved to c/common https://github.com/containers/common/blob/main/docs/Containerfile.5.md See https://github.com/containers/buildah/pull/3746 for more details.

**Comment by flouthoc** [comment]
I'm going to close this issue since most of the context is on the PR itself but feel free to discuss below.
