### ISSUE TITLE
[FEATURE REQUEST] define preprocesser macros in the CLI

### ISSUE THREAD

**Issue by Basti-D** [containers/buildah#3816]
# Status quo

Currently cpp(1) is invoked for ".in" files by using bud. See #851 .
This was implemented in order to include other files.
Since the C Preprocessor is being used, we have the complete C Preprocessor functionality, e.g. #ifdef could be used to have "conditional Dockerfiles".
Currently using #include and defining the macros inside a file works as expected.

# Proposal
In order to simplify the usage (and not using "some hacks") a clean CLI where the macro definitions can be done via  [-Dmacro[=defn]...] (similiar to cpp) would be useful.

# Examples
## minimal example

Dockerfile.hello_wolrd.in
```
FROM ubuntu:20.04
RUN echo "hello " NAME
```

building via:
`buildah bud -f  Dockerfile.hello_wolrd.in`

results in
`hello`

proposal: building via:
`buildah bud -f  Dockerfile.hello_wolrd.in -DNAME=world`

results in
`hello world`

proposal: building via:
`buildah bud -f  Dockerfile.hello_wolrd.in -DNAME=buildah`

results in
`hello buildah`

## example in OpenShift CI/CD context
Dockerfile.openshift.in
```
#ifdef OpenShift
#define REGISTRY image-registry.openshift-image-registry.svc:5000
#else
#define REGISTRY default-route-openshift-image-registry.test.de
#endif

FROM REGISTRY/internalImage
```

building via:
`buildah bud -f  Dockerfile.openshift.in`
uses the external route for the image stream.

on the CI/CD server one would run via
`buildah bud -f  Dockerfile.openshift.in -DOpenShift`
which would use the internal route for the image stream.

Yes, there are other possibilities to solve this issue, e.g. using build args.

## example conditional Dockerfile

Dockerfile.conditional.in
```
FROM ubuntu:20.04

// Install backend
#ifdef backend1
// install python 3.10
// pip install backend from private repo
// adapt env vars
// etc. (possible put into separate include file to make it more readable)
#define BACKEND /backends/backend1
#elif backend2
// install conan
// retrieve backend2 from conan
// install backend2
// adapt path
// etc.
// probably more logic
#define BACKEND /backends/backend2
#else
#error No backend was chosen
#endif

// compile project against the BACKEND from above.
...
// starter server with installed BACKEND from above.
...
```

building via
`buildah bud -f  Dockerfile.conditional.in -Dbackend1`
will build everything with the first backend.

building via
`buildah bud -f  Dockerfile.conditional.in -Dbackend2`
will build everything with the second backend.

building via
`buildah bud -f  Dockerfile.conditional.in`
will throw an error.

other possible solutions:
* if statements using the shell directly are probably not portable. Syntax is a matter of taste. But it's not a Dockerfile feature per se.
* Define multiple FROMs and choose the appropriate via build args. Seems quite complex when having multiple if statements.

# Effort and required Changes
Taking a look at the source code the required changes seem quite small and the implementation effort seems quite small as well.
This seems not to break anything existing.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @Basti-D!

@rhatdan @nalind PTAL

I am totally fine adding such a feature.  However, I would generalize the new option from `-D` to `--cpp-flags` which would allow for passing the specified flags directly to `cpp`.  In the upper example `-Dbackend2` would be turned into `--cpp-flags "-Dbackend2"`.

**Comment by rhatdan** [comment]
Should we support an environment variable for this as well.  BUILDAH_CPPFLAGS?
Or something like that?

**Comment by vrothberg** [comment]
Sounds good to me.
