### ISSUE TITLE
preprocessing not working with stable buildah Image 

### ISSUE THREAD

**Issue by Basti-D** [containers/buildah#3822]
**Description**

`buildah bud Dockerfile.in . `
using the prebuilt stable Dockerimage 
results in 
`exec: "cpp": executable file not found in $PATH`

**Steps to reproduce the issue:**
1. checkout buildah repo
2. `cd buildah/tests/bud/preprocess`
3.  create test Dockerfile 
```
echo 'FROM quay.io/buildah/stable' > test.dockerfile
echo 'COPY . .' >> test.dockerfile
echo 'RUN buildah bud  -f Decomposed.in .' >> test.dockerfile
```
4. check whether the normal decomposed test works: 
```
buildah bud  -f Decomposed.in .
STEP 1: FROM alpine:latest
STEP 2: RUN touch /etc/hello-world.txt
STEP 3: RUN echo "Hello world!"
Hello world!
STEP 4: RUN apk update
^C
```
-> yes, works perfectly fine.
5. check whether the buildah stable image works as intended
```
buildah bud  -f test.dockerfile .
STEP 1: FROM quay.io/buildah/stable
STEP 2: COPY . .
STEP 3: RUN buildah bud  -f Decomposed.in .
exec: "cpp": executable file not found in $PATH
time="2022-03-15T09:29:54Z" level=error msg="exit status 125"
error building at STEP "RUN buildah bud  -f Decomposed.in .": error while running runtime: exit status 125
ERRO[0003] exit status 125
```
-> broken, since cpp not found.

**Describe the results you received:**
The image was not built, because cpp(1) is not installed (or missing in the PATH environment variable).
`exec: "cpp": executable file not found in $PATH`

**Describe the results you expected:**
I expect that the image would have been built using the stable buildah image as a builder image.

**possible solutions**
Installing cpp inside the image should solve the issue.
Drawback: The imagesize will be increased.

**Comment by Basti-D** [comment]
@flouthoc this is our current approach which solves the issue.
But generally speaking I assume that if there exists an image, all functionality should be available. If some functionality is not available it should be documented somewhere.
Probably an additional image, which is larger but has all functionality, could make sense?

**Comment by rhatdan** [comment]
```
$ rpm -q buildah --suggests
cpp
qemu-user-static
```
It is under suggests for RPM packaging. We could make the error message a little more clear.


`exec: "cpp": executable file not found in $PATH, please install the cpp package.`

**Comment by vrothberg** [comment]
> I'm not sure if its a good idea to install cpp by default, since its not mandatory for builds and not sure if lot of users are using it.

I think it's a bad user experience if a supported and documented feature of Buildah does not work with the official Buildah image.

It's _our_ responsibility not the users' to make that work. I am not worried at all about binary size as it's less than 900K.

We just need to update the Dockerfiles in https://github.com/containers/buildah/tree/main/contrib/buildahimage and install `cpp` along with the other packages.

**Comment by vrothberg** [comment]
> ```
> $ rpm -q buildah --suggests
> cpp
> qemu-user-static
> ```
> 
> It is under suggests for RPM packaging. We could make the error message a little more clear.
> 
> `exec: "cpp": executable file not found in $PATH, please install the cpp package.`

Opened a PR to also address the error message: https://github.com/containers/buildah/pull/3825
