### ISSUE TITLE
Feature request: option to suppress io.buildah.version labels

### ISSUE THREAD

**Issue by csmith** [containers/buildah#3826]
It would be nice if there were an option to suppress the `io.buildah.version` labels that buildah applies to all built images.

I'm trying to make images that are reproducible, but at present you need to exactly match the version of buildah to be able to successfully reproduce an image. Comparing images built by buildah 1.21.3 and 1.24.2, it seems that they would be perfectly identical if not for the `io.buildah.version` labels.

**Comment by flouthoc** [comment]
Hi @csmith , Thanks for creating the issue. I think you can override `io.buildah.version` but I also agree that there must be option to suppress default labels. Above PR adds a new flag `--remove-identity-labels` which adds the following requested feature.
