### ISSUE TITLE
Building the podman multi-arch example on openSUSE Tumbleweed errors out with 255: possibly incomplete binfmt setup?

### ISSUE THREAD

**Issue by johanneskastl** [containers/buildah#3827]
**Description**

I wanted to try the multi-arch container builds on openSUSE Tumbleweed, but the builds end with error 255
https://podman.io/blogs/2021/10/11/multiarch.html

Is there a way to check if the binfmt setup is fully working? I have no clue where the error is, my limited knowledge on binfmt, errors in buildah/podman, errors in the packaging, errors in systemd, etc. pp.

The `Containerfile` from the example:
```
FROM registry.access.redhat.com/ubi8:latest
RUN uname -a
```

**Steps to reproduce the issue:**
0. Tumbleweed installation on latest snapshot (also tested in new virtual machine)
1. Running the build command without any binfmt setup returns error 1 
2. Enable binfmt by running `/sbin/qemu-binfmt-conf.sh --persistent yes --systemd ALL` and `systemctl start systemd-binfmt`
3. Check there are new files in `/proc/sys/fs/binfmt_misc/`
4. Try building again and I get error 255 (see below)
5. Try building using podman => same error 255

**Describe the results you received:**

Error message **WITHOUT** binfmt:
```
$ buildah bud --arch arm64 .
STEP 1/2: FROM registry.access.redhat.com/ubi8:latest
STEP 2/2: RUN uname -a
exec /bin/sh: no such file or directory
error building at STEP "RUN uname -a": error while running runtime: exit status 1
ERRO[0003] exit status 1
```

Error message **WITH** binftm enabled:
```
$ buildah bud --arch arm64 . 
STEP 1/2: FROM registry.access.redhat.com/ubi8:latest
STEP 2/2: RUN uname -a
error building at STEP "RUN uname -a": error while running runtime: exit status 255
ERRO[0003] exit status 255
```

**Describe the results you expected:**

A working "build" without errors as in the example.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.24.2-1.1.x86_64
```

**Output of `buildah version`:**

```
buildah version 1.24.2 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 3.4.4
```

**Output of `cat /etc/*release`:**

```
NAME="openSUSE Tumbleweed"
# VERSION="20220311"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20220311"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20220311"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

**Output of `uname -a`:**

```
Linux laptop 5.16.11-1-default #1 SMP PREEMPT Thu Feb 24 05:07:05 UTC 2022 (90630c5) x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ grep -v "#" /etc/containers/storage.conf | grep -v "^$" | uniq
[storage]
driver = "btrfs"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
[storage.options.thinpool]
```

**Comment by TomSweeneyRedHat** [comment]
@cevich Thoughts?

**Comment by nalind** [comment]
The interpreters in the `qemu-linux-user` package in tumbleweed appear to be dynamically linked, so they're not suitable for this use case.
You're probably going to need to use the alternate approach of registering static interpreters provided by a container image, e.g. by running `podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset --persistent yes` the first time, and again after each reboot.

**Comment by cevich** [comment]
Hmmm, ya I bet @nalind is right.  This isn't a problem I have any experience with.  When I screwed up binfmt-misc, I always got some error about an unrecognized binary format, so this is new to me.

**Comment by johanneskastl** [comment]
> The interpreters in the `qemu-linux-user` package in tumbleweed appear to be dynamically linked, so they're not suitable for this use case. You're probably going to need to use the alternate approach of registering static interpreters provided by a container image, e.g. by running `podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset --persistent yes` the first time, and again after each reboot.

Thanks for the quick reply. I'll try to verify this in a Tumbleweed VM tomorrow.

If this is indeed the case, then I would reach out (again) to the openSUSE lists to see if we can have an additional package with statically-linked binaries.


For my original question: Is there a way to test whether or not binfmt is properly setup? Or would this small example build be the actual testcase for this?

**Comment by johanneskastl** [comment]
> > The interpreters in the `qemu-linux-user` package in tumbleweed appear to be dynamically linked, so they're not suitable for this use case. You're probably going to need to use the alternate approach of registering static interpreters provided by a container image, e.g. by running `podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset --persistent yes` the first time, and again after each reboot.
> 
> Thanks for the quick reply. I'll try to verify this in a Tumbleweed VM tomorrow.

OK, I had to know. I just spun up a new tumbleweed VM, installed podman and buildah and ran the command that @nalind gave.
I could see lots of things appear in `/proc/sys/fs/binfmt_misc/`.

# And I can confirm that this works, I could "build" the s390x and arm64/aarch64 examples without issues. 

```
kastl-tumbleweed:~/Podman_Example $ cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20220317"
[...]
kastl-tumbleweed:~/Podman_Example $ buildah bud --arch arm64 .
STEP 1/2: FROM registry.access.redhat.com/ubi8:latest
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Copying blob fea832e2f312 done
Copying blob 24639a74db0e done
Copying config b670559163 done
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN uname -a
Linux b6cf349902ad 5.16.14-1-default #1 SMP PREEMPT Fri Mar 11 12:33:34 UTC 2022 (80acc65) aarch64 aarch64 aarch64 GNU/Linux
COMMIT
Getting image source signatures
Copying blob 8ce5fefd85ad skipped: already exists
Copying blob 51c5c556ef65 skipped: already exists
Copying blob 2c01d9613374 done
Copying config 5e754732cf done
Writing manifest to image destination
Storing signatures
--> 5e754732cf9
5e754732cf94b4ebf32ee7ef2538d3b7a7a4e8be2b84be5bec29dbdfed2176c9
kastl-tumbleweed:~/Podman_Example $ buildah bud --arch s390x .
STEP 1/2: FROM registry.access.redhat.com/ubi8:latest
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Copying blob bdee7855ef43 done
Copying blob df8985aa78d6 done
Copying config 83e347d667 done
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN uname -a
Linux f0fb39f5ce91 5.16.14-1-default #1 SMP PREEMPT Fri Mar 11 12:33:34 UTC 2022 (80acc65) s390x s390x s390x GNU/Linux
COMMIT
Getting image source signatures
Copying blob 7f49cad5b96b skipped: already exists
Copying blob 68cb789c9df5 skipped: already exists
Copying blob bd5ed9be5f60 done
Copying config 6216c93017 done
Writing manifest to image destination
Storing signatures
--> 6216c930173
6216c930173c85aa776b49e1d116093e9f0f75df20f483481b389febc4c39d09
kastl-tumbleweed:~/Podman_Example $
```

**Comment by nalind** [comment]
The check generally involves verifying that that `/proc/sys/fs/binfmt_misc` exists, that there's an entry for each interpreter under it, that the entries in `/proc/sys/fs/binfmt_misc` include `F` in their flags, and that the binary it names as the interpreter is statically linked (`file` will know).

The `qemu-linux-user` package installs a statically linked `/usr/bin/qemu-binfmt` which tries to exec the interpreter named in its `argv[0]`, which is passed to it because it's been registered with the `P` flag, but at the point it's called, it's already in the container's mount namespace, so it fails to find the binary it's attempting to `exec()`.

If you've got a copy of the rootfs for an image for a foreign architecture (you can create one by creating a container with `podman create --arch arm64` and then copying its contents somewhere with `podman cp ${containerNameOrID}:/ ${chrootDirectory}/`), a simpler check is probably `unshare -fm -R ${chrootDirectory} /bin/sh`.

**Comment by johanneskastl** [comment]
Thanks @nalind  for the explanation!

IMHO this would be a good addition for the buildah/podman docs, so people can verify if the underlying "infrastructure" is already in place for building multi-arch containers.

Especially as there seem to be only few tutorials that are very platform-specific.

**Comment by johanneskastl** [comment]
> The check generally involves verifying that that `/proc/sys/fs/binfmt_misc` exists, that there's an entry for each interpreter under it, that the entries in `/proc/sys/fs/binfmt_misc` include `F` in their flags, and that the binary it names as the interpreter is statically linked (`file` will know).

The binaries on my Tumbleweed machine are shown as `statically linked`, unfortunately.

```
$ file /usr/bin/qemu-aarch64
/usr/bin/qemu-aarch64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=d3a5c94482ac87e6a8b36cfb163164e79c5d199e, for GNU/Linux 3.2.0, stripped
$ ls -lh /usr/bin/qemu-aarch64-binfmt
lrwxrwxrwx 1 root root 11 16. Mär 21:45 /usr/bin/qemu-aarch64-binfmt -> qemu-binfmt*
$ file /usr/bin/qemu-binfmt 
/usr/bin/qemu-binfmt: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=b94f8217eb3cc20c03b12f6b9fffc7818ee808ca, for GNU/Linux 3.2.0, stripped
$
```
So, this leaves me puzzled again...

**Comment by johanneskastl** [comment]
In the meantime Fabian was kindly replying in the openSUSE Bug report that the (apparent) real cause is a patch introduced in the openSUSE qemu package, that breaks this feature:
https://bugzilla.opensuse.org/show_bug.cgi?id=1197298

I would like to keep **this bug** open until it is fully solved, as it seems there might be some more back and forth until the puzzle is solved.

Thanks all for your help!

**Comment by rhatdan** [comment]
Since this is not an upstream issue, I am going to close.

**Comment by johanneskastl** [comment]
> Since this is not an upstream issue, I am going to close.

Sorry, forgot to close this...
