### ISSUE TITLE
Allow combination of `--no-cache` and `--layers=true`

### ISSUE THREAD

**Issue by bendem** [containers/buildah#3861]
Currently, combining `--no-cache` and `--layers=true` results in 
```
can only set one of 'layers' or 'no-cache'
ERRO[0000] exit status 125
```

There are valid use cases where we want `buildah` to produce layers (speed up next builds, provide more layers to improve push/pull operations) while not using currently available layers. One such case for us is weekly rebuild: we want the weekly rebuild to ignore existing layers while still providing build cache and separate layers for future builds.

**Comment by bendem** [comment]
The restriction was added here, not sure why.
https://github.com/containers/buildah/commit/fc438bb932e891cbe04109cfae1dfbe3c99307a5

**Comment by rhatdan** [comment]
That makes some sense to me.  Not sure why this was blocked, but it might have been a mistaken thought.

**Comment by rhatdan** [comment]
Please open a PR to remove the check.

**Comment by flouthoc** [comment]
I agree use-case makes sense @bendem would you like to take a stab at this ? For starting point I think check is only at cli and some part might be in `imagebuildah/stage_executor.go`.

**Comment by flouthoc** [comment]
This seemed fairly simple above PR should close this.
