### ISSUE TITLE
pull=missing is missing?

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#3921]
We just had a fix go into Podman to allow for the value `missing` to be passed into the `--pull` option for build.  I just looked here, and that is not a documented value for the pull option.

It should do the same thing as `--pull=false`, that is pull the image from the registry if it is missing from local storage.  I'm not sure if it should pull if the image is newer on the registry if it is also present locally.  I think not, but need to dig deeper.

**Comment by vrothberg** [comment]
See https://github.com/containers/podman/pull/13952

**Comment by flouthoc** [comment]
I think `--pull=missing` can be aliased to `--pull=false` in this case.

**Comment by vrothberg** [comment]
I understand it more as a documentation issue.

**Comment by flouthoc** [comment]
@vrothberg Ah i see then should we add a small note that in docs `--pull=false` is equivalent to `--pull=missing`.

**Comment by vrothberg** [comment]
> @vrothberg Ah i see then should we add a small note that in docs `--pull=false` is equivalent to `--pull=missing`.

They are not the same (see https://github.com/containers/podman/pull/13952). `--pull=false` is equal to `--pull=never`. `missing` will only pull if there's no matching local image.

**Comment by flouthoc** [comment]
@vrothberg I think some confusion here but `--pull=false` in buildah means that it will `pull` image if not present on local otherwise it will not pull the image it does not seems to be equal to `--pull=never`.

This is the definition from buildah man page says `--pull string[="true"]          pull the image from the registry if newer or not present in store, if false, only pull the image if not present, if always, pull the image even if the named image is present in store, if never, only use the image present in store if available (default "true")`

**Comment by vrothberg** [comment]
Where do you get that from? `man buildah-build` states

> If the flag is disabled (with --pull=false), do not pull the image from the registry,
use only the local version. Raise an error if the image is not present locally.

**Comment by flouthoc** [comment]
@vrothberg Its written in `buildah build --help` and also I think actual behavior is like that.

**Comment by vrothberg** [comment]
That is curious! Looks like it requires some thorough look at the code and the docs / help messages.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat I remember you working on this a while back.

**Comment by TomSweeneyRedHat** [comment]
Yeah, and there's a minor difference in behavior between Podman and Buildah.  I don't recall exactly, but I think false acts a bit differently.  I need to dig up my notes, and spend some time playing.  The noggin is not remembering the nuances quickly.

**Comment by rhatdan** [comment]
Can we just get the man page fixed and close this or should we add --pull=missing support, to be compatible with Podman?

**Comment by flouthoc** [comment]
I'll update the docs for this.

**Comment by rhatdan** [comment]
@flouthoc did you ever update the docs?
