### ISSUE TITLE
[v.low pri] CI: status reporting: order of successful/queued/etc

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#3930]
While monitoring two in-flight PRs I noticed that Buildah and Podman report Cirrus status in different order:
```
   [green-and-dark-yellow circle] Some checks haven’t completed yet
   podman:   15 queued, 6 in progress, 4 neutral, and 30 successful checks
   buildah:  7 successful, 1 queued, and 13 in progress checks
```
For dumbos like me who don't actually read but simply look at the numbers, this inconsistency is confusing: since I'm more used to podman, I just look at the left-hand number and expect to see how much longer I have to wait.

For whoever knows how this status is reported: is it easy to make these consistent among our projects? I don't care which order gets chosen, I'd just like consistency.

**Comment by rhatdan** [comment]
@cevich PTAL

**Comment by cevich** [comment]
> For whoever knows how this status is reported: is it easy to make these consistent among our projects? I don't care which order gets chosen, I'd just like consistency.

Whoa, that's really weird.  I'm see the status lines you mention, they're part of github, right above the list of CI individual jobs (tasks) - assuming "hide all checks" isn't active.

Based on what I understand of how services and Github interact, there may not be much we can do to control the formatting here.  It's likely related to using/not certain Cirrus features; like, manually triggered tasks and "ignore_failure" tasks.  Even if that gets fixed, somebody adding a new service (e.g. some new github actions check) will potentially come with it's own statuses, and muck it all up (vs other repos. w/o that service).

I'd hate to add something ugly to force the cirrus-side, like adding `IGNORE ME` dummy tasks that use features, just to affect status formatting.  Alternatively, I'd suggest we find and open an issue against github.  However (based on experience) I have basically zero confidence they care or would even consider touching the "working" code :disappointed: 

Let's think on this, maybe it's something we can ask Cirrus for (always report all status codes, even if the count is `0`).  It won't perfectly solve the order problem, but it may improve it.
