### ISSUE TITLE
FR: `--logfile` seperated file for each platform

### ISSUE THREAD

**Issue by Dexus** [containers/buildah#3960]
**Description**
I would like to get for each platform I build, have a own logfile.

when I run:
```shell
buildah build -f "example-debian.Dockerfile" \
  --manifest example-debian \
  --jobs 3 --layers \
  --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/mips64le,linux/s390x \
  --uts private --pull \
  --userns container --isolation oci \
  --network private \
  --logfile buildlog_example-debian.log \
  --squash \
  --build-arg DEMO=1 .
```

**Describe the results you received:**

The logfile looks very mixed :(

**Describe the results you expected:**
The logfile not mixed the steps in the output from multiple platforms. Or even better would be, for each platform have a own logfile, maybe with a placeholder in the `filename-%(platform_normalized).log` or with a argument that accepts a directory where all logs are placed.

**Output of `buildah version`:**

```
1.25.1
```

**Comment by flouthoc** [comment]
Hi @Dexus Thanks for opening the issue looks like a nice feature request just curious does `docker or buildkit` already supports this ? If yes we might wanna choose their format for compat but if not I think we can choose any one of the requested above.

**Comment by Dexus** [comment]
Hi @flouthoc, no both don't support this currently, but buildkit (`docker buildx build`) support `--progress plain` which will output with prefix, but don't mix up the output from multiple arch builds on the same time - there it is a clean output.

**Comment by Dexus** [comment]
Well, so far I haven't seen any CLI that can build multiple architectures simultaneously and provide logfiles. Therefore, I am not currently aware of any precedent where this feature is available. There is just nothing at the moment where you can get a logfile for an architecture. Would at least be a super unique selling point for buildah.

**Comment by rhatdan** [comment]
I wonder if we just added logdir option and had it create an arch directory with buildah.log in it would be best.

--logdir=/tmp/foobar and /tmp/foobar/lamd64/buildah.log,arm64/buildah.log,ppc64le/buildah.log, mips64le/buildah.log,s390x/buildah.log.  Perhaps a /tmpfoobar/buildah.log which would log the manifest log entries.

**Comment by Dexus** [comment]
I like the idea of that.
But would prefer the format of the platform for the children directories.

`--logdir=/tmp/foobar --platform=windows/amd64,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v5...` 

should result in something like the same or with a dash instead of a slash

```
/tmp/foobar/windows/amd64/buildah.log
/tmp/foobar/linux/amd64/buildah.log
/tmp/foobar/linux/arm64/buildah.log
/tmp/foobar/linux/arm/v7/buildah.log
/tmp/foobar/linux/arm/v5/buildah.log
...

# or 

/tmp/foobar/windows-amd64/buildah.log
/tmp/foobar/linux-amd64/buildah.log
/tmp/foobar/linux-arm64/buildah.log
/tmp/foobar/linux-arm-v7/buildah.log
/tmp/foobar/linux-arm-v5/buildah.log
...
```

**Comment by rhatdan** [comment]
That works for me, I  was thinking that but figured the chance of someone actually building a Windows image on a Linux box was just about nil.  I think from a user point of view the linux-amd64 one is better.

**Comment by Dexus** [comment]
Or one more style variant:

```
/tmp/foobar/buildah_manifest.log
/tmp/foobar/buildah_windows-amd64.log
/tmp/foobar/buildah_linux-amd64.log
/tmp/foobar/buildah_linux-arm64.log
/tmp/foobar/buildah_linux-arm-v7.log
/tmp/foobar/buildah_linux-arm-v5.log
```

**Comment by rhatdan** [comment]
That is fine also. 
@flouthoc something you can throw together?

**Comment by flouthoc** [comment]
SGTM. I'll take this.

**Comment by vrothberg** [comment]
Wouldn't that be a breaking change?  Some users may already depend on the current behavior.

Consider using a boolean flag to switch the behavior on.

**Comment by flouthoc** [comment]
@vrothberg Ack'd this can be enabled on `--logfile` otherwise everything just stays as the original behavior.

**Comment by Dexus** [comment]
When can I expect this integration? It is really annoying currently with the mixed logs from all concurrent builds.

**Comment by flouthoc** [comment]
@Dexus I'll start on this today :).

**Comment by flouthoc** [comment]
Above PR https://github.com/containers/buildah/pull/4034 should close this.
