### ISSUE TITLE
compilation terminated.

### ISSUE THREAD

**Issue by yyf1986** [containers/buildah#3976]
**Description**

**Steps to reproduce the issue:**
1.git clone ****
2.cd buildah/cmd/buildah
3.go build -mod=vendor

**Describe the results you received:**
```
# github.com/proglottis/gpgme
../../vendor/github.com/proglottis/gpgme/data.go:4:11: fatal error: gpgme.h: No such file or directory
 // #include <gpgme.h>
           ^~~~~~~~~
compilation terminated.
```

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by flouthoc** [comment]
Hi @yyf1986 , Thanks for creating the issue.

It seems you are missing development headers and libraries for gpgme. Please download for `libgpgme-dev` for debian or `gpgme-devel` for fedora/centos. I am closing this issue but feel free to re-open is something is unresolved :)
