### ISSUE TITLE
Canceling `buildah bud` during layer pull causes `layer not known` with unclear resolution

### ISSUE THREAD

**Issue by komish** [containers/buildah#3979]
**Steps to reproduce the issue:**
1. Run `buildah bud`. Unconfirmed whether the containerfile must contain a builder stage.
2. Cancel (Ctrl+c) the execution immediately after it starts, as one might do when they realize they did not provide sufficient arguments.
3. Try to run `buildah images`. I observed this by running `buildah bud` again, seeing similar errors, and then running `images` afterwards to try and resolve.

Previously reported: #2727 

> I have this issue on buildah `1.21.1`. I suspect it is because I sigterm'd `buildah build` while it was pulling a dependency image so it is in some broken intermediate state.
From: https://github.com/containers/buildah/issues/2727#issuecomment-875561608

Confirmed, I also canceled a build and ran into this issue. 

Buildah gave me the layer information, but `podman image list` gave me image to delete. Running `buildah rmi <image>` after podman gave me the identifier seemed to clean this up for me.

**Describe the results you received:**

```
$ buildah images
error locating layer with ID "e43ed8991bb22154245f5e359ce6a8e794f8342472435723a770771b928db1e9": layer not known
```

**Describe the results you expected:**

At minimum, to not have seen the above error due to cancelation, or have been provided some remediation context. The referenced issue describes clean up steps, but I'm wondering if the layer cleanup should have been handled by `buildah` on cancel. In other words, I wonder if there's an opportunity to improve the UX here on cancel?

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ rpm -qa buildah
buildah-1.23.3-2.fc35.x86_64
```

**Output of `buildah version`:**

```
$ buildah version
Version:         1.23.3
Go Version:      go1.16.15
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.16.0
Git Commit:      
Built:           Wed Mar 30 14:03:25 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
$ podman version
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.16.15
Built:        Fri Apr  1 13:21:14 2022
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35 (Server Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Server Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
```

**Output of `uname -a`:**

```
Linux powerlab 5.17.5-200.fc35.x86_64 #1 SMP PREEMPT Thu Apr 28 15:41:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ grep -v "^#" /etc/containers/storage.conf  | awk 'NF'
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

**Comment by flouthoc** [comment]
Hi @komish , Thanks for creating the issue. I think this happens because buildah uses a component called `containers/storage` which commits layers to storage but if a layer gets corrupted and is commit-ed into storage we see all sorts of side effects ( like when you cancel `pull` in-flight ).

Usually cleaning of storage manually should fix this or `podman system reset` should also fix this as well as a workaround.

But issue still persists and its a clone of https://github.com/containers/podman/issues/14003 and can be better tracker here: https://github.com/containers/storage/issues/1136

I'm closing this issue due to its redundant nature. I'd request you to follow the issues listed above but feel free to re-open if something is unresolved.
