### ISSUE TITLE
buildah in tekton task deployed via tekton-operator fails on OKD

### ISSUE THREAD

**Issue by ibotty** [containers/buildah#3987]
I am not sure that's the right forum for this bug.  It might well be a configuration issue and thus should be filed in tektoncd/catalog or tektoncd/operator.  But I saw similar bugs here, so.  Please point me to the right issue tracker if that's the wrong one.

Running the `buildah`-ClusterTask I always get the following error.

```
Error: error writing "0 0 4294967295\n" to /proc/30/uid_map: write /proc/30/uid_map: operation not permitted
time="2022-05-12T14:09:11Z" level=error msg="error writing \"0 0 4294967295\\n\" to /proc/30/uid_map: write /proc/30/uid_map: operation not permitted"
time="2022-05-12T14:09:11Z" level=error msg="(unable to determine exit status)"
```

The pod is running as root with the following security config.
```
  securityContext:
    fsGroup: 1001140000
    seLinuxOptions:
      level: s0:c34,c9
  serviceAccount: pipeline
```

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `skopeo inspect docker://quay.io/buildah/stable:latest`**
```
    "Labels": {
        "license": "MIT",
        "name": "fedora",
        "org.opencontainers.image.created": "2022-05-12T08:34:38+00:00",
        "org.opencontainers.image.revision": "f671e53ee5646d2f2e3626cf1337bfcc0440a8eb",
        "org.opencontainers.image.source": "https://github.com/containers/buildah.git",
        "org.opencontainers.image.version": "1.23.3",
        "vendor": "Fedora Project",
        "version": "35"
    },
```

**Comment by flouthoc** [comment]
@ibotty Does it work if you disable selinux and just make it priviledged ?  I would like you to try securityContext below in both in `Pod` and Tekton `Task` step to just check. But also issue is missing a bit of context is the log shared belongs to the output of Tekton Task running buildah ?

```console
      securityContext:
        privileged: true
```

**Comment by nalind** [comment]
Is the node running kernel 5.12 or later?  If so, I think you'll need to arrange for the container to have the CAP_SETFCAP capability.

**Comment by ibotty** [comment]
I finally got around to testing with `CAP_SETFCAP` capability.  Yes, that works!  Thank you for your help.  Now I'll have to raise issues to propagate the required capabilities.
