### ISSUE TITLE
Secret cannot be used more than once in a Containerfile

### ISSUE THREAD

**Issue by teojgo** [containers/buildah#3993]
**Description**
Using the `--secret` option of `buildah bud` does not allow the same secret to be used more than once in a Containerfile

**Steps to reproduce the issue:**
1. Create a simple Containerfile with the following contents:
```
FROM ubuntu:latest

RUN --mount=type=secret,id=mysecret,dst=/home/root/mysecret cat /home/root/mysecret

RUN --mount=type=secret,id=mysecret,dst=/home/root/mysecret2 cat /home/root/mysecret2
```
2. Create a `mysecret.dat` text file with some random contents within the same directory
3. Try building the image using: `buildah bud  --secret=id=mysecret,src=./mysecret.dat`. You should get the following error:
```
cat: /home/root/mysecret2: No such file or directory
```
in the 3rd Containerfile step
4. Making a small change to the Containerfile (changing the id of the secret in the 3rd step):
```
FROM ubuntu:latest

RUN --mount=type=secret,id=mysecret,dst=/home/root/mysecret cat /home/root/mysecret

RUN --mount=type=secret,id=mysecret2,dst=/home/root/mysecret2 cat /home/root/mysecret2
```
and using `buildah bud  --secret=id=mysecret,src=./mysecret.dat  --secret=id=mysecret2,src=./mysecret.dat` to build, succeeds

**Describe the results you received:**
The secret with a particular id cannot be used more than once

**Describe the results you expected:**
The secret should be used as many times as needed

**Output of `rpm -q buildah` or `apt list buildah`:**
Installed from source

**Output of `buildah version`:**

```
Version:         1.24.4
Go Version:      go1.18.1
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.0.1
image Version:   5.19.3
Git Commit:      c1bdaba5
Built:           Fri May 13 15:21:02 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Linux Mint"
VERSION="19 (Tara)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19"
VERSION_ID="19"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tara
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux desktopPC 4.15.0-176-generic #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
Empty, but used `crun` as the runtime via `export BUILDAH_RUNTIME=/usr/local/bin/crun`

**Comment by Dexus** [comment]
Good Catch! It saves me some time, and I can first switch with other Images, that don't need secrets to buildah.

**Comment by flouthoc** [comment]
We had explicit check which was blocking re-using secret artifacts from host. Above PR should fix it and added a test to confirm that.

**Comment by bconn98** [comment]
Has this fix not been rolled back to Podman? I'm seeing the same issue on v4.5

**Comment by bconn98** [comment]
Our build is occurring within `quay.io/podman/stable:v4.5.0`. The first use of the secret is successful, but the second attempt to use it does not find the file.
