### ISSUE TITLE
Building with "--squash" doesn't have any caching mechanism (again)

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/buildah#4011]
Hi,

Following the upgrade to RHEL 8.6 and podman 4.0.2 in my company, it seems we still facing the issue #3665 with this version.

When I tried to re-run the reproducing steps described in #3665 with image `docker://quay.io/podman/upstream:latest` (`podman version 4.2.0-dev`) it seems the exact same reproduction steps still expose the bug.

When this will be fixed, would it be possible to push the fix to the podman packages found in RHEL 8/9 ?

Cheers,
Romain

**Comment by Romain-Geissler-1A** [comment]
Note: back then, when I validated https://github.com/containers/buildah/pull/3674 back then, I did it using buildah and flags 
`--squash --layers`. In my above reproduction steps, I am using podman and flag `--squash` (looks like `--layers` is true by default in podman).  So maybe the bug is in podman, in the way podman calls buildah ?

**Comment by Romain-Geissler-1A** [comment]
I tried to change a bit podman here: https://github.com/containers/podman/compare/main...Romain-Geissler-1A:main but actually the behavior of buildah seems strange. It seems it's impossible to squash only the newly created layers in cache *AND* keep the intermediate layers (in other words, buildah has flag `--squash` which correspond to podman `--squash-all` but buildah seems to have no counterpart to podman's `--squash`).

So, should the behavior of buildah's `--squash` flag to be modified (ie only act on newly created layers) and a new `--squash-all` flag be introduced, in order to behave like podman ?

**Comment by flouthoc** [comment]
Hi @Romain-Geissler-1A Thanks for creating the issue. Since buildah already supports this we can have `podman --squash-all` support this feature. We cannot alter `podman --sqaush` due to its compat nature with docker. But above PR allows you to achieve similar functionality in `--squash-all`

Thanks.

**Comment by nalind** [comment]
> I tried to change a bit podman here: [containers/podman@main...Romain-Geissler-1A:main](https://github.com/containers/podman/compare/main...Romain-Geissler-1A:main) but actually the behavior of buildah seems strange. It seems it's impossible to squash only the newly created layers in cache _AND_ keep the intermediate layers (in other words, buildah has flag `--squash` which correspond to podman `--squash-all` but buildah seems to have no counterpart to podman's `--squash`).

Podman's `--squash` corresponds to buildah's `--layers=false`, which is the default in `buildah build`.

**Comment by Romain-Geissler-1A** [comment]
So there will never be any support for `podman/buildah build --squash --layers` (`--layers` being actually enabled by default in podman) ? And podman/buildah will forever disagree on what the flag `--squash` actually does ? How do you usually change flag semantic ? By adding new flags and keep the old ones compatible, or you allow yourself incompatible changes in things like major version ?

**Comment by nalind** [comment]
> So there will never be any support for `podman/buildah build --squash --layers` (`--layers` being actually enabled by default in podman) ?

Using `--squash` with `podman build` implicitly disables its enabled-by-default `--layers` option.  In that case, it doesn't commit an image and display the new image's truncated image ID after each step.  Attempting to explicitly enable both options should trigger an error message.

**Comment by Romain-Geissler-1A** [comment]
Yes what you describe is the current behavior, it works exactly as you wrote it.

But what about the people who want the feature of `--squash` (ie squash only the new layers, not the ones of the base image) and have layer cache at the same time (so that building the same Dockerfile twice on the same machine uses cache the second time) ? It will never be implemented, only `--squash-all` + `--layers` will be implemented ?

**Comment by flouthoc** [comment]
> It will never be implemented, only --squash-all + --layers will be implemented ?

@Romain-Geissler-1A Yes it seems like that `--squash and --layers` will work with buildah only and for equivalent feature at podman end you will have to use `--squash-all and --layers` once this https://github.com/containers/podman/pull/14320 and https://github.com/containers/buildah/pull/4013 is merged.
