### ISSUE TITLE
Quay.io container images are outdated

### ISSUE THREAD

**Issue by der-eismann** [containers/buildah#4026]
**Description**

On the buildah.io [release notes to the latest release](https://buildah.io/releases/2022/05/09/Buildah-version-v1.26.1-mini.html) it is noted that container images should be available at Quay
> In addition, container images will be available at
> https://quay.io/repository/buildah/stable and
> https://quay.io/repository/containers/buildah

However both repos are severely outdated with the latest release available being v1.23.3. Even if you argue that it says `*will be* available`, it's been three weeks since the post was created. Is there no automated release pipeline for this?

**Describe the results you received:**

Outdated buildah images

**Describe the results you expected:**

Images of current buildah versions

**Comment by flouthoc** [comment]
Hi @der-eismann , Thanks for creating the issue and pointing this out. Could you use `quay.io/buildah/upstream:latest` till this is fixed in upstream. @cevich Could you please take a look ? I am not sure why `quay.io/containers/buildah` and `buildah/stable` is not updated.

**Comment by cevich** [comment]
>The image should be built off of F36 at this point.

Agree, something must be broken with the build process...yep, it's [been broken for the last 6 days.](https://github.com/containers/buildah/actions/workflows/multi-arch-build.yaml) for the same reason the podman images are broken and [likely needs a similar fix.](https://github.com/containers/podman/pull/14437).

I've also got a PR open to [move the build process into Cirrus-CI](https://github.com/containers/buildah/pull/4019) where we'll notice it's broken a lot sooner.  In any case, I'll work on a fix for this as well.

**Comment by cevich** [comment]
Actually, @TomSweeneyRedHat while I work on #4019 (it won't fix the `sed` problem) do you think you could help apply the `sed`, fix to the Dockerfile's here?

**Comment by der-eismann** [comment]
Thanks for investigating and working on it everyone! 
On another note, the [1.26 blog post](https://buildah.io/releases/2022/05/09/Buildah-version-v1.26.1-mini.html) says:
> We are shipping this release on Fedora 35, Fedora 36, and RHEL 8.6.0.2.

This is wrong for Fedora 35 as [buildah is still on 1.23.3/4 there](https://src.fedoraproject.org/rpms/buildah) and I can't find anything on Google about a RHEL version 8.6.0.2. Is this some kind of internal versioning or is there a public roadmap to anticipate when the release is happening?

**Comment by cevich** [comment]
> tried to get to it today but lost the battle. Will try to do it tomorrow.

No worries, you should see my browser tab collection.  It would excite even the prehistoric archaeologists :rofl:
