### ISSUE TITLE
[FEATURE REQUEST] --tls-verify --> BUILDAH_TLS_VERIFY

### ISSUE THREAD

**Issue by resmo** [containers/buildah#4027]
Allow to set `--tls-verify` as ENV variable `BUILDAH_TLS_VERIFY`

**Comment by vrothberg** [comment]
Thanks for reaching out, @resmo!

@mtrmac @rhatdan WDYT?

If, I think it should be `CONTAINERS_TLS_VERIFY` that could be set in libimage or c/image FWIW.

**Comment by vrothberg** [comment]
@resmo, did you consider configuring this setting in the [registries.conf](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md)?

**Comment by mtrmac** [comment]
Disabling TLS is a last-resort alternative to correctly configuring systems. Adding a global switch like that, that could affect all users in a shell session (including third-party scripts that might not need that at all) is something I think we should _never_ do.

`registries.conf` already provides a global, persistent, way to configure a specific registry to disable TLS. I don’t see why it would be responsible make it any easier to disable TLS, especially in a less discriminating way.

**Comment by resmo** [comment]
To clarify, --tls-verify exists already (push, pull) but in ci/cd it would be easier to switch on or off, especially if buildah runs in a container as in our case.

**Comment by rhatdan** [comment]
Can't you just drop a registries.conf file with the correct settings in your CI/CD system then?

**Comment by resmo** [comment]
Nobody claimed it is "better or worse" to configure a env var instead of registries.conf but why should I write to a registry.conf into a container if I could configure it by en ENV var.

I mean, it is the usual way one configures containers (and I know you know that too) is not to write files into containers but to pass ENV vars. 

I just though, why should this not be an built-in feature of buildah itself: to have the choice to either use a switch --something  or ENV var  BUILDAH_SOMETHING.
