### ISSUE TITLE
Rootless and Google Container Registry

### ISSUE THREAD

**Issue by petersenna** [containers/buildah#4030]
Google Container Registry gets confused if I build and push using my user instead of root.

**Steps to reproduce the issue:**
1. Build and push a container using my user
2. Try to pull the container
3. It fails with: "Error: parsing image configuration: Error fetching blob: invalid status code from registry 403 (Forbidden)"
4. Build and push same container as root
5. Try to pull the container
6. It works

**Describe the results you received:**
Please see https://pastebin.com/Wj1gGGuA

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
package buildah is not installed
```

**Output of `buildah version`:**

```
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      3.4.7
API Version:  3.4.7
Go Version:   go1.16.15
Built:        Thu Apr 21 15:14:26 2022
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 35 (Thirty Five)
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 35 (Thirty Five)
Fedora release 35 (Thirty Five)
```

**Output of `uname -a`:**

```
Linux fedora 5.16.18-200.fc35.x86_64 #1 SMP PREEMPT Mon Mar 28 14:10:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat /etc/containers/storage.conf |grep -v '#'
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]

[storage.options.overlay]
mountopt = "nodev,metacopy=on"

[storage.options.thinpool]
```

**Comment by petersenna** [comment]
@vrothberg like this?

**Comment by petersenna** [comment]
I am sorry, but I used versions and system information from the wrong host. Let me updated it.

**Comment by vrothberg** [comment]
Thanks, @petersenna.

If possible, could share the output of `skopeo inspect --config docker://$IMAGE`? Once when it's broken, once when it works?

It seems curious that it's only happening on the config but the 403 ultimately looks like a registry-side error.  Does it work using another registry?

**Comment by petersenna** [comment]
Frustratingly, I cannot reproduce it any longer. Now everything works as expected. From yesterday to about 2 hours ago, I could reproduce it consistently. Now it all works.

**Comment by vrothberg** [comment]
> Frustratingly, I cannot reproduce it any longer. Now everything works as expected. From yesterday to about 2 hours ago, I could reproduce it consistently. Now it all works. I haven't tried other registries.

It could very well be a fart on the registry.  I am going to close the issue but we can re-open in case it's happening again.
