### ISSUE TITLE
open /etc/containers/policy.json: no such file or directory

### ISSUE THREAD

**Issue by Alanthur** [containers/buildah#4039]
I follow the tutorials https://github.com/containers/buildah/blob/main/docs/tutorials/04-include-in-your-build-tool.md
My code
`func BuildImages() {
	if buildah.InitReexec() {
		return
	}
	unshare.MaybeReexecUsingUserNamespace(false)

	buildStoreOptions, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
	if err != nil {
		panic(err)
	}

	buildStore, err := storage.GetStore(buildStoreOptions)
	if err != nil {
		panic(err)
	}
	defer buildStore.Shutdown(false)

	builderOpts := buildah.BuilderOptions{
		FromImage: "docker.io/library/alpine:latest",
	}

	builder, err := buildah.NewBuilder(context.TODO(), buildStore, builderOpts)
	if err != nil {
		panic(err)
	}
	defer builder.Delete()

	err = builder.Run([]string{"mkdir -p /data"}, buildah.RunOptions{})
	if err != nil {
		panic(err)
	}

	err = builder.Add("/data", false, buildah.AddAndCopyOptions{}, "test-v1")
	if err != nil {
		panic(err)
	}
	err = builder.Run([]string{"chmod +x /data/test-v1"}, buildah.RunOptions{})
	if err != nil {
		panic(err)
	}

	builder.SetCmd([]string{"/data/test-v1"})

	imageRef, err := is.Transport.ParseStoreReference(buildStore, "mytest:10.0")
	if err != nil {
		panic(err)
	}

	imageId, _, _, err := builder.Commit(context.TODO(), imageRef, buildah.CommitOptions{})
	if err != nil {
		panic(err)
	}

	fmt.Printf("Image built! %s\n", imageId)
}
`

I run this code got errors:
`INFO[0006] [graphdriver] using prior storage driver: overlay 
2022/06/07 10:10:22 http: panic serving 192.168.0.254:58731: open /etc/containers/policy.json: no such file or directory
goroutine 21 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xf91920, 0xc0002e1d70})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
s2i-deploy/pkg/runtime/buildah.BuildImages()
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/runtime/buildah/buildah.go:36 +0x606
s2i-deploy/pkg/web/controller/ocifile.(*OciBinaryFile).Server(0xf62f20, {0x0, 0xc00019b4a5}, 0xb)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/ocifile/binary.go:13 +0x29
s2i-deploy/pkg/web/controller.(*Controller).ServeHTTP(0x0, {0x125ada0, 0xc000576380}, 0xc00057e400)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/controller.go:27 +0x6b
net/http.serverHandler.ServeHTTP({0xc00025c1b0}, {0x125ada0, 0xc000576380}, 0xc00057e400)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc00012dea0, {0x1268340, 0xc00025c030})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8`

os: Ubuntu 20.04.2 LTS
runc: runc version 1.0.1
containerd: containerd github.com/containerd/containerd v1.4.9

I want to know how to get /etc/containers/policy.json?

**Comment by flouthoc** [comment]
Hi @Alanthur, Thanks for creating the issue. 

Default policy.json is equivalent to https://src.fedoraproject.org/rpms/containers-common/raw/main/f/default-policy.json

If you don't want any default registries configured feel free to use this one
```json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports":
        {
            "docker-daemon":
                {
                    "": [{"type":"insecureAcceptAnything"}]
                }
        }
}
```

If you want to read more about how to configure `policy.json` for a fine grained control then you can follow the man-page here: https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md

Thanks

( I am closing this issue since above should resolve this issue but please feel free to continue discussion below)

**Comment by Alanthur** [comment]
@flouthoc 
thanks for your help. 
I solve this problem.
But then I run this code,I got another errors:

`INFO[0001] [graphdriver] using prior storage driver: overlay 
2022/06/07 14:40:49 http: panic serving 192.168.0.254:64209: error decoding response from copier subprocess: invalid character 'æ' looking for beginning of value
goroutine 34 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xfd0a20, 0xc00000ee10})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
s2i-deploy/pkg/runtime/buildah.BuildImages()
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/runtime/buildah/buildah.go:42 +0x5f7
s2i-deploy/pkg/web/controller/ocifile.(*OciBinaryFile).Server(0xf62f20, {0x0, 0xc0001fa345}, 0xb)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/ocifile/binary.go:13 +0x29
s2i-deploy/pkg/web/controller.(*Controller).ServeHTTP(0x0, {0x125ada0, 0xc0004ce380}, 0xc0005ba400)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/controller.go:27 +0x6b
net/http.serverHandler.ServeHTTP({0xc000097800}, {0x125ada0, 0xc0004ce380}, 0xc0005ba400)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000206a00, {0x1268340, 0xc000097710})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8`

what should I do?

**Comment by flouthoc** [comment]
@Alanthur Since I can't see the stack trace could you check with break points after which call this fails cause I cannot see the complete stack trace so its hard to tell from this side but it seems issue is with your business logic now.

To confirm if something is not wrong with your setup try running a simpler example and see if this works and then try debugging your custom implementation.

```go
package main

import (
  "context"
  "fmt"

  "github.com/containers/buildah"
  is "github.com/containers/image/v5/storage"
  "github.com/containers/storage"
  "github.com/containers/storage/pkg/unshare"
)

func main() {
  if buildah.InitReexec() {
    return
  }
  unshare.MaybeReexecUsingUserNamespace(false)

  buildStoreOptions, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
  if err != nil {
    panic(err)
  }

  buildStore, err := storage.GetStore(buildStoreOptions)
  if err != nil {
    panic(err)
  }
  defer buildStore.Shutdown(false)

  builderOpts := buildah.BuilderOptions{
    FromImage:        "docker.io/library/alpine:latest",
  }

  builder, err := buildah.NewBuilder(context.TODO(), buildStore, builderOpts)
  if err != nil {
    panic(err)
  }
  defer builder.Delete()
  // Note!!!! please change this to actual path on your host
  err = builder.Add("/home/some/", false, buildah.AddAndCopyOptions{}, "somefile")
  if err != nil {
    panic(err)
  }

  imageRef, err := is.Transport.ParseStoreReference(buildStore, "docker.io/myusername/my-image")
  if err != nil {
    panic(err)
  }

  imageId, _, _, err := builder.Commit(context.TODO(), imageRef, buildah.CommitOptions{})
  if err != nil {
    panic(err)
  }

  fmt.Printf("Image built! %s\n", imageId)
}
```

**Comment by Alanthur** [comment]
`INFO[0003] [graphdriver] using prior storage driver: overlay 
2022/06/07 15:19:59 http: panic serving 192.168.0.254:59141: error decoding response from copier subprocess: invalid character 'æ' looking for beginning of value
goroutine 22 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xfd0a20, 0xc0001100c0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
s2i-deploy/pkg/runtime/buildah.BuildImages()
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/runtime/buildah/buildah.go:47 +0x725
s2i-deploy/pkg/web/controller/ocifile.(*OciBinaryFile).Server(0xf62f20, {0x7fe2f0bcfa68, 0xc0004a0005}, 0xb)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/ocifile/binary.go:13 +0x29
s2i-deploy/pkg/web/controller.(*Controller).ServeHTTP(0x0, {0x125adc0, 0xc0002c8000}, 0xc0002be000)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/controller.go:27 +0x6b
net/http.serverHandler.ServeHTTP({0xc00057a0c0}, {0x125adc0, 0xc0002c8000}, 0xc0002be000)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000300000, {0x1268360, 0xc0003e3140})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8`

**Comment by Alanthur** [comment]
> @Alanthur Since I can't see the stack trace could you check with break points after which call this fails cause I cannot see the complete stack trace so its hard to tell from this side but it seems issue is with your business logic now.
> 
> To confirm if something is not wrong with your setup try running a simpler example and see if this works and then try debugging your custom implementation.
> 
> ```go
> package main
> 
> import (
>   "context"
>   "fmt"
> 
>   "github.com/containers/buildah"
>   is "github.com/containers/image/v5/storage"
>   "github.com/containers/storage"
>   "github.com/containers/storage/pkg/unshare"
> )
> 
> func main() {
>   if buildah.InitReexec() {
>     return
>   }
>   unshare.MaybeReexecUsingUserNamespace(false)
> 
>   buildStoreOptions, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
>   if err != nil {
>     panic(err)
>   }
> 
>   buildStore, err := storage.GetStore(buildStoreOptions)
>   if err != nil {
>     panic(err)
>   }
>   defer buildStore.Shutdown(false)
> 
>   builderOpts := buildah.BuilderOptions{
>     FromImage:        "docker.io/library/alpine:latest",
>   }
> 
>   builder, err := buildah.NewBuilder(context.TODO(), buildStore, builderOpts)
>   if err != nil {
>     panic(err)
>   }
>   defer builder.Delete()
>   // Note!!!! please change this to actual path on your host
>   err = builder.Add("/home/some/", false, buildah.AddAndCopyOptions{}, "somefile")
>   if err != nil {
>     panic(err)
>   }
> 
>   imageRef, err := is.Transport.ParseStoreReference(buildStore, "docker.io/myusername/my-image")
>   if err != nil {
>     panic(err)
>   }
> 
>   imageId, _, _, err := builder.Commit(context.TODO(), imageRef, buildah.CommitOptions{})
>   if err != nil {
>     panic(err)
>   }
> 
>   fmt.Printf("Image built! %s\n", imageId)
> }
> ```

if I run this code ,I got some errors:

`INFO[0001] [graphdriver] using prior storage driver: overlay 
2022/06/07 15:23:44 http: panic serving 192.168.0.254:59175: error checking on destination /var/lib/containers/storage/overlay/780218b39779e3bf79a21b4169e381d50a077a258c739d9b008fb096011f44d1/merged/home/some: error decoding response from copier subprocess: invalid character 'æ' looking for beginning of value
goroutine 11 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0xfd0a20, 0xc00014c078})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
s2i-deploy/pkg/runtime/buildah.BuildImages()
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/runtime/buildah/buildah.go:42 +0x445
s2i-deploy/pkg/web/controller/ocifile.(*OciBinaryFile).Server(0xf62f20, {0x0, 0xc000149ea5}, 0xb)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/ocifile/binary.go:13 +0x29
s2i-deploy/pkg/web/controller.(*Controller).ServeHTTP(0x0, {0x125ad40, 0xc00054e380}, 0xc0005bc800)
        /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/controller.go:27 +0x6b
net/http.serverHandler.ServeHTTP({0xc0001ef740}, {0x125ad40, 0xc00054e380}, 0xc0005bc800)
        /usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001ac5a0, {0x12682e0, 0xc0001ef5f0})
        /usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3034 +0x4e8`

**Comment by flouthoc** [comment]
> > @Alanthur Since I can't see the stack trace could you check with break points after which call this fails cause I cannot see the complete stack trace so its hard to tell from this side but it seems issue is with your business logic now.
> > To confirm if something is not wrong with your setup try running a simpler example and see if this works and then try debugging your custom implementation.
> > ```go
> > package main
> > 
> > import (
> >   "context"
> >   "fmt"
> > 
> >   "github.com/containers/buildah"
> >   is "github.com/containers/image/v5/storage"
> >   "github.com/containers/storage"
> >   "github.com/containers/storage/pkg/unshare"
> > )
> > 
> > func main() {
> >   if buildah.InitReexec() {
> >     return
> >   }
> >   unshare.MaybeReexecUsingUserNamespace(false)
> > 
> >   buildStoreOptions, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
> >   if err != nil {
> >     panic(err)
> >   }
> > 
> >   buildStore, err := storage.GetStore(buildStoreOptions)
> >   if err != nil {
> >     panic(err)
> >   }
> >   defer buildStore.Shutdown(false)
> > 
> >   builderOpts := buildah.BuilderOptions{
> >     FromImage:        "docker.io/library/alpine:latest",
> >   }
> > 
> >   builder, err := buildah.NewBuilder(context.TODO(), buildStore, builderOpts)
> >   if err != nil {
> >     panic(err)
> >   }
> >   defer builder.Delete()
> >   // Note!!!! please change this to actual path on your host
> >   err = builder.Add("/home/some/", false, buildah.AddAndCopyOptions{}, "test")
> >   if err != nil {
> >     panic(err)
> >   }
> > 
> >   imageRef, err := is.Transport.ParseStoreReference(buildStore, "docker.io/myusername/my-image")
> >   if err != nil {
> >     panic(err)
> >   }
> > 
> >   imageId, _, _, err := builder.Commit(context.TODO(), imageRef, buildah.CommitOptions{})
> >   if err != nil {
> >     panic(err)
> >   }
> > 
> >   fmt.Printf("Image built! %s\n", imageId)
> > }
> > ```
> 
> if I run this code ,I got some errors:
> 
> `INFO[0001] [graphdriver] using prior storage driver: overlay 2022/06/07 15:23:44 http: panic serving 192.168.0.254:59175: error checking on destination /var/lib/containers/storage/overlay/780218b39779e3bf79a21b4169e381d50a077a258c739d9b008fb096011f44d1/merged/home/some: error decoding response from copier subprocess: invalid character 'æ' looking for beginning of value goroutine 11 [running]: net/http.(*conn).serve.func1() /usr/local/go/src/net/http/server.go:1802 +0xb9 panic({0xfd0a20, 0xc00014c078}) /usr/local/go/src/runtime/panic.go:1047 +0x266 s2i-deploy/pkg/runtime/buildah.BuildImages() /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/runtime/buildah/buildah.go:42 +0x445 s2i-deploy/pkg/web/controller/ocifile.(*OciBinaryFile).Server(0xf62f20, {0x0, 0xc000149ea5}, 0xb) /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/ocifile/binary.go:13 +0x29 s2i-deploy/pkg/web/controller.(*Controller).ServeHTTP(0x0, {0x125ad40, 0xc00054e380}, 0xc0005bc800) /home/project/paas/s2i-deploy/paas-s2i-deploy/pkg/web/controller/controller.go:27 +0x6b net/http.serverHandler.ServeHTTP({0xc0001ef740}, {0x125ad40, 0xc00054e380}, 0xc0005bc800) /usr/local/go/src/net/http/server.go:2879 +0x43b net/http.(*conn).serve(0xc0001ac5a0, {0x12682e0, 0xc0001ef5f0}) /usr/local/go/src/net/http/server.go:1930 +0xb08 created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:3034 +0x4e8`

@Alanthur Does it works if you comment the `builder.Add` call ? Could you add break points or dummy `fmt.Printf(` calls to check on which this is failing ?

**Comment by Alanthur** [comment]
@flouthoc 
It is not work on the builder.Add call. And `builder.Run` also not work.

**Comment by Alanthur** [comment]
@flouthoc 
![Uploading 微信图片_20220607153908.png…]()

**Comment by Alanthur** [comment]
@flouthoc 
![1](https://user-images.githubusercontent.com/9957813/172329348-c1132c43-e723-4a70-85e4-b3068909d957.png)
![QQ截图20220607160659](https://user-images.githubusercontent.com/9957813/172329374-074ecf3f-5027-4c70-9405-4cf4a557d2dc.png)
