### ISSUE TITLE
How to push images to harbor?

### ISSUE THREAD

**Issue by Alanthur** [containers/buildah#4047]
I successful run code from the tutorials https://github.com/containers/buildah/blob/main/docs/tutorials/04-include-in-your-build-tool.md
I build  images successful:
![QQ截图20220609164309](https://user-images.githubusercontent.com/9957813/172804712-f8e253f0-1450-41ca-a0a7-60e1a9ee3cb6.png)

Then I want to push to my harbor.
My harbor address：192.168.0.186:30102
Then I writing code:
![QQ截图20220609164727](https://user-images.githubusercontent.com/9957813/172805597-45f6d1e1-3cee-48d4-80fb-490034b52a4d.png)
It is works without errors.
But there is not images in my harbor.
What should I do?

**Comment by rhatdan** [comment]
This is most likely a bug in harbor not showing OCI images properly. You could attempt to push them in docker format.
--format docker

**Comment by nalind** [comment]
The parsed `dest` value refers to a location in local storage.  References to locations in image registries typically start with "docker://".  There's a brief summary of the various location types at https://github.com/containers/skopeo/blob/main/docs/skopeo.1.md#image-names, which links to a longer one at https://github.com/containers/image/blob/main/docs/containers-transports.5.md.

**Comment by Alanthur** [comment]
@rhatdan I push images in docker format.
![QQ截图20220610092113](https://user-images.githubusercontent.com/9957813/172971347-d547e9b0-5d1b-49da-98d2-9a51694b053b.png)
But I got errors:
![QQ截图20220610092245](https://user-images.githubusercontent.com/9957813/172971472-723bad4f-6d4a-4d96-8142-390f98300ce3.png)

**Comment by Alanthur** [comment]
@nalind Thanks for your help,I push images to harbor successfully.
