### ISSUE TITLE
Can't store output in TAR when only FROM is used in Dockerfile

### ISSUE THREAD

**Issue by jpolara2016** [containers/buildah#4094]
**Description**
can't output tar file when only FROM step is used in Dockerfile. Discussed in the comments https://github.com/containers/buildah/issues/3789

**Steps to reproduce the issue:**
1. echo "FROM alpine" > alpine/Dockerfile
2. buildah build --file alpine/Dockerfile -t alpine:latest -o type=tar,dest=/build/out.tar alpine/

**Describe the results you received:**
No **out.tar** is created

**Describe the results you expected:**
**out.tar** should be created 

**Output of `buildah version`:**

```
[root@3c39c5cf427f build]# buildah version
Version:         1.26.0
Go Version:      go1.18
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.0
image Version:   5.21.1
Git Commit:
Built:           Wed May  4 19:49:14 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Comment by flouthoc** [comment]
@jpolara2016 Thanks above PR https://github.com/containers/buildah/pull/4097 should close this

**Comment by flouthoc** [comment]
Should be out in next release thanks for reporting.
