### ISSUE TITLE
ctr images ls cannot find the image that is builded by buildah

### ISSUE THREAD

**Issue by JcJinChen** [containers/buildah#4110]
**Description**
According this [article](https://wasmedge.org/book/en/kubernetes/demo/wasi.html), I have builded images.
```
sudo buildah images
REPOSITORY                    TAG      IMAGE ID       CREATED        SIZE
localhost/wasm-wasi-example   latest   d230f65c92e0   24 hours ago   2.01 MB
```
The context of my Dockerfile is 
```
FROM scratch
ADD wasi_example_main.wasm /
CMD ["/wasi_example_main.wasm"]
```
By using the following command, I builded the image:
```
sudo buildah build --annotation "module.wasm.image/variant=compat" -t wasm-wasi-example .
```
However,when I want to use the command `ctr` to check whether the image is exit or not,
I didn't find it.

**Steps to reproduce the issue:**
1.download the example code 
```
git clone https://github.com/second-state/wasm-learning
cd wasm-learning/cli/add
```

2.build the wasm bytecode 
```
rustup target add wasm32-wasi
cargo build --target wasm32-wasi --release
```

3.change the mode of the wasm file
```
chmod +x target/wasm32-wasi/debug/add.wasm
```
4.create the dockerfile in the `target/wasm32-wasi/debug/` folder with the following content:
```
FROM scratch
ADD add.wasm /
CMD ["/add.wasm"]
```
5.[Build and install the latest buildah on Ubuntu](https://wasmedge.org/book/en/kubernetes/demo/wasi.html#build-and-install-the-latest-buildah-on-ubuntu)

6.Create  a container image with buildah
```
sudo buildah build --annotation "module.wasm.image/variant=compat" -t wasm-wasi-example .

```

**Describe the results you received:**

Of cousre, I actually find the image by the command`sudo buildah images`,
at the same time, i can create a container from this image,
`sudo buildah from localhost/wasm-wasi-example`
However, when I want to exec /add.wasm, an error  has occurred
```
exec container process `/add.wasm`: Exec format error
error while running runtime: exit status 1
```

I also try to use the command `ctr i ls ` to list all images,
but, i didn't find it.
I would like to know if `ctr` is supported to list the images that are builded by buildah and which tools we can use to create container except `buildah from ***`? 

**Describe the results you expected:**
```
ctr i ls
```
empty.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
apt list buildah
Listing... Done
buildah/unknown 100:1.22.3-2 amd64
buildah/unknown 100:1.22.3-2 arm64
buildah/unknown 100:1.22.3-2 armhf
buildah/unknown 100:1.22.3-2 s390x
```

**Output of `buildah version`:**

```
Version:         1.27.0-dev
Go Version:      go1.16.6
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.1
image Version:   5.21.2-dev
Git Commit:      2bd5083364d977d480a4fa0465fb9f035be50116
Built:           Wed Jul 13 10:00:27 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Output of `uname -a`:**

```
Linux VM-0-17-ubuntu 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flouthoc** [comment]
If you want to tryout running with `podman` you can try following steps: https://github.com/containers/crun/blob/main/docs/wasm-wasi-example.md#examples

**Comment by JcJinChen** [comment]
> Hi @JcJinChen , thanks for creating the issue.
> 
> I am not sure which command `ctr` you are referring to , could you share the full command ? But just curious why do you want to create a buildah container from a `wasm-compat` images.
> 
> I think `buildah images` should be enough to show if built image exists or not, then further you can use `podman` or any other container manager to run the image but underlying OCI runtime must support `wasm` so you need to make sure that `crun` with wasm support exists on your system and `crun --version` should be enough to tell you if your `crun` supports web assembly or not.



> Hi @JcJinChen , thanks for creating the issue.
> 
> I am not sure which command `ctr` you are referring to , could you share the full command ? But just curious why do you want to create a buildah container from a `wasm-compat` images.
> 
> I think `buildah images` should be enough to show if built image exists or not, then further you can use `podman` or any other container manager to run the image but underlying OCI runtime must support `wasm` so you need to make sure that `crun` with wasm support exists on your system and `crun --version` should be enough to tell you if your `crun` supports web assembly or not.

Thanks for your reply. The commad `ctr` is cli tool of [containerd](https://github.com/containerd/containerd).
I have installed containerd on my system, the tool `ctr` can be used to list container, image and so on.
I am confusion that why  the `tool` ctr cannot be used to list image builded by `buildah`.
At the same time, I cannot use `tool` to run the image builded by `buildah`.

Actually, I also want to test these example in this [article](https://github.com/containers/crun/blob/main/docs/wasm-wasi-example.md), using podman to run the image.

**Comment by flouthoc** [comment]
Ah i see so `containerd` cannot see containers created by buildah since they use different storage underneath and they are different tools.

Since this issue is being discussed here: https://github.com/containers/crun/issues/966 I think this issue can be closed but please feel free to re-open.

**Comment by rhatdan** [comment]
If you use CRI-O instead of containerd, you will be able to see the images and still work with kubernetes.
