### ISSUE TITLE
IO redirection causes error

### ISSUE THREAD

**Issue by gpettey** [containers/buildah#4122]
**Description**

A Dockerfile with shell I/O redirection fails to build with `syntax error near unexpected token '('`.

**Steps to reproduce the issue:**
1. Dockerfile:
```
FROM docker.io/redhat/ubi8:latest

RUN cat <(curl -fSs https://github.com)
```
3. buildah bud -t testingTag .
4. fail

**Describe the results you received:**

```
STEP 1/2: FROM docker.io/redhat/ubi8:latest
STEP 2/2: RUN cat <(curl -fSs https://github.com)
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `cat <(curl -fSs https://github.com)'
error building at STEP "RUN cat <(curl -fSs https://github.com)": error while running runtime: exit status 1
ERRO[0002] exit status 1
```

The same Dockerfile is fine with `podman build -t testingTag .`. Only buildah fails.

**Output of `rpm -q buildah` or `apt list buildah`:
```
  apt list podman buildah
Listing... Done
buildah/jammy,now 1.23.1+ds1-2 amd64 [installed]
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Output of `buildah version`:**

```
buildah version 1.23.1 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 3.4.4
```

**Comment by flouthoc** [comment]
@gpettey To me this looks like more of problem with the `sh` version inside the image `docker.io/redhat/ubi8:latest`. It works for me with other images like `fedora` and `alpine`.

I tried following container file and worked fine for me
```Containerfile
FROM fedora

RUN cat <(curl -fSs https://github.com)
```

also with `alpine` works fine
```Containerfile
FROM alpine

RUN cat <(echo hello)
```
output 
```console
STEP 1/2: FROM alpine
STEP 2/2: RUN cat <(echo hello)
hello
COMMIT test
Getting image source signatures
Copying blob ec34fcc1d526 skipped: already exists  
Copying blob ce4de1501518 done  
Copying config 2c34ad96d1 done  
Writing manifest to image destination
Storing signatures
--> 2c34ad96d1f
Successfully tagged localhost/test:latest
2c34ad96d1f9aa0e582f6a6f343e19032da6f1f91249f00fe3716ea8d3424263
```

**Comment by rhatdan** [comment]
Older version of Bash
cat /tmp/Containerfile
FROM docker.io/redhat/ubi8:latest
RUN rpm -qf /bin/sh
FROM  fedora
RUN rpm -qf /bin/sh

buildah build /tmp
[1/2] STEP 1/2: FROM docker.io/redhat/ubi8:latest
[1/2] STEP 2/2: RUN rpm -qf /bin/sh
bash-4.4.20-3.el8.x86_64
[2/2] STEP 1/2: FROM fedora
[2/2] STEP 2/2: RUN rpm -qf /bin/sh
bash-5.1.16-2.fc36.x86_64

If you use ubi9 it works.
