### ISSUE TITLE
Output generated using "--output" sometimes contains more files than expected

### ISSUE THREAD

**Issue by leotaku** [containers/buildah#4131]
**Description**

As I understand it, the command `buildah build --output TARGET` should create a directory at the path pointed at by target that contains only the contents of the last container generated by a multi-stage build. In some cases, this happens as expected, in others it does not. I have not yet been able to find out the exact circumstances that cause this issue to appear, but I will provide a minimal Dockerfile that consistently produces this issue for me.

The same issue occurs when using `podman build . --output TARGET`.

The issue also occurs when using the tar output format.

**Steps to reproduce the issue:**
1. Create the following Dockerfile
```Dockerfile
FROM alpine:latest as builder
RUN touch rogue

FROM builder as intermediate
RUN touch artifact

FROM scratch as outputs
COPY --from=intermediate artifact target
```
3. Run `buildah build --output build`
4. Observe the contents of the `build` directory

**Describe the results you received:**
The build directory contains the files `rogue` and `target`, as well as seemingly the contents of a full FHS root. It does not contain the file `artifact`.

**Describe the results you expected:**
The build directory contains only the file `target`.

**Output of `rpm -q buildah` or `apt list buildah`:**
I am not using a Linux variant that uses either of these package managers.

**Output of `buildah version`:**

```
Version:         1.26.2
Go Version:      go1.18.4
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.0
image Version:   5.21.1
Git Commit:      unknown
Built:           Tue Jan  1 01:00:00 1980
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_CODENAME=raccoon
DISTRIB_DESCRIPTION="NixOS 22.11 (Raccoon)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="22.11"
LSB_VERSION="22.11 (Raccoon)"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.11.20220721.dirty"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.11 (Raccoon)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.11 (Raccoon)"
VERSION_CODENAME=raccoon
VERSION_ID="22.11"
```

**Output of `uname -a`:**

```
Linux nixos-laptop 5.15.55 #1-NixOS SMP Fri Jul 15 08:13:00 UTC 2022 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
graphroot = "/var/lib/containers/storage"
runroot = "/run/containers/storage"
```

**Comment by leotaku** [comment]
Issue #4132 may or may not be related. I have created a separate issue for it because that problem seems to be exclusive to `podman build`.

**Comment by flouthoc** [comment]
Thanks for creating the issue. I'll take a look at this :)

**Comment by flouthoc** [comment]
Thanks PR https://github.com/containers/buildah/pull/4135 should close this added a test case to verify use-case.

**Comment by leotaku** [comment]
Thanks for the fast response!
