### ISSUE TITLE
Output for "--output" from `podman build` is only generated when container is not cached

### ISSUE THREAD

**Issue by leotaku** [containers/buildah#4132]
**Description**

The `podman build . --output TARGET` command only produces output if the generated container image is freshly built and not when fetched from cache.

**Steps to reproduce the issue:**
1. Create the following Dockerfile
```Dockerfile
FROM alpine:latest as builder
RUN touch empty.txt
```
3. Run `podman build . --output build`
4. Observe that a new directory named `build` is created
5. Run `podman build . --output build2`
6. Observe that no new directory named `build2` is created

**Describe the results you received:**
Podman only generated the expected output when the container that makes up the output was freshly built. On the second run, where the container had already been built, no output was generated.

**Describe the results you expected:**
Podman always generates the output corresponding to the container described in the Dockerfile.

**Output of `rpm -q buildah` or `apt list buildah`:**
I am not using a Linux variant that uses either of these package managers.

**Output of `buildah version`:**
Not applicable

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_CODENAME=raccoon
DISTRIB_DESCRIPTION="NixOS 22.11 (Raccoon)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="22.11"
LSB_VERSION="22.11 (Raccoon)"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.11.20220721.dirty"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.11 (Raccoon)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.11 (Raccoon)"
VERSION_CODENAME=raccoon
VERSION_ID="22.11"
```

**Output of `uname -a`:**

```
Linux nixos-laptop 5.15.55 #1-NixOS SMP Fri Jul 15 08:13:00 UTC 2022 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
graphroot = "/var/lib/containers/storage"
runroot = "/run/containers/storage"
```

**Comment by flouthoc** [comment]
Thanks PR https://github.com/containers/buildah/pull/4135 should close this added a test case to verify use-case.
