### ISSUE TITLE
Allow to expire cached build layers use after some time period

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#4160]
With `podman build` there is a `--no-cache` option. It would be great if we could add a feature to support adding an expiration for using cached layers.

Right now we either have `--no-cache` (which means don't use cached layers) or not (which means to use cached layers). I'd like to have some sort of `--no-cache=1d` that says "you are allowed to use cached layers that are younger than 1d".

A use case like this is especially clear for cases like `RUN dnf update` or `RUN dnf install` directives in a Containerfile where the line doesn't change but you get different results based on when it gets executed.

Another idea along this same vein is to support some sort of "decorator" in the Containerfile itself that tells podman/buildah to do the same thing:

```
FROM fedora
COPY file /path/to/file
# cache-expire 1d
RUN dnf install htop
```

But that could be a separate feature request if the idea has merit.

**Comment by nalind** [comment]
kaniko's equivalent option appears to be named [`--cache-ttl`](https://github.com/GoogleContainerTools/kaniko#--cache-ttl-duration), and takes a duration as its argument.

**Comment by dustymabe** [comment]
I don't have a strong opinion on the argument. `--cache-ttl` seems fair.

**Comment by flouthoc** [comment]
PR https://github.com/containers/buildah/pull/4165 should close this issue.

**Comment by rhatdan** [comment]
I like this idea.  I am fine with a decorator as well, although that would be difficult to descover.
