### ISSUE TITLE
buildah load/save

### ISSUE THREAD

**Issue by justadogistaken** [containers/buildah#4164]
**Description**

Does buildah support save or load image like docker save/load?

I checked the supported commands. But I didn't find the related commands.

**Comment by flouthoc** [comment]
Hi @justadogistaken , Thanks for creating the issue. Podman already contains these commands, do you have any specific use-case where you are using only buildah and need these commands ?

**Comment by justadogistaken** [comment]
> Hi @justadogistaken , Thanks for creating the issue. Podman already contains these commands, do you have any specific use-case where you are using only buildah and need these commands ?

We are integrating `buildah` into [sealer](https://github.com/sealerio/sealer). Sealer will also build a specific image for delivering k8s cluster and applications. Sometimes the "save/load" is essential in offilne delivery case. We are able to build oci image based on `buildah`, but I found that `buildah` fails to support `save/load`.

**Comment by vrothberg** [comment]
`buildah` supports the functionality via `push` and `pull`.  `save` and `load` are, in a way, just wrappers around that.

```bash
$ buildah push ubi8 oci-archive:/tmp/ubi8.tar
$ buildah pull oci-archive:/tmp/ubi8.tar
```

Note that `oci-archive` is one of the supported transports in `man containers-transports`.  Given it's working, I am closing the issue but feel free to drop further questions here.

**Comment by justadogistaken** [comment]
> `buildah` supports the functionality via `push` and `pull`. `save` and `load` are, in a way, just wrappers around that.
> 
> ```shell
> $ buildah push ubi8 oci-archive:/tmp/ubi8.tar
> $ buildah pull oci-archive:/tmp/ubi8.tar
> ```
> 
> Note that `oci-archive` is one of the supported transports in `man containers-transports`. Given it's working, I am closing the issue but feel free to drop further questions here.

Thanks for you reley. I found that the core is libImageRuntime. Which is able to help me out.

**Comment by vrothberg** [comment]
Happy to help!  You can also find some examples in the man pages of buildah-push and buildah-pull.
