### ISSUE TITLE
Containerfile with RUN --network none ... Does not work.

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#4230]
Dockerfile is documented to support

RUN --network ...

But with Buildah this blows up:

   STEP 1/2: FROM alpine
   STEP 2/2: RUN --network=none ping -c 1 4.2.2.2
   error building at STEP "RUN --network=none ping -c 1 4.2.2.2": RUN only supports the --mount flag

https://docs.docker.com/engine/reference/builder/#run---network

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
https://docs.docker.com/engine/reference/builder/#run---network

**Comment by flouthoc** [comment]
Sure, SGTM I think a small change in imagebuilder should make it work.

**Comment by flouthoc** [comment]
I'm taking over https://github.com/openshift/imagebuilder/pull/237 and will implement this there.

**Comment by flouthoc** [comment]
This is bit delayed but I'll get to it.

**Comment by rhatdan** [comment]
@flouthoc still delayed?

**Comment by rhatdan** [comment]
@flouthoc friendly ping.

**Comment by flouthoc** [comment]
PR https://github.com/containers/buildah/pull/4566 should close this.

**Comment by rhatdan** [comment]
Getting close.
