### ISSUE TITLE
`<Dockerfile>.dockerignore` implicit dockerignore file definition is not supported

### ISSUE THREAD

**Issue by SpencerMalone** [containers/buildah#4236]
**Description**

`<Dockerfile>.dockerignore` implicit dockerignore file definition is not supported. This feature has been in the docker CLI since 2019 and works as follows:

> docker build searches for a .dockerignore file relative to the Dockerfile name. For example, running docker build -f myapp.Dockerfile . will first look for an ignore file named myapp.Dockerfile.dockerignore. If such a file is not found, the .dockerignore file is used if present.

I'm not sure if this is a feature request or a bug, since the lack of it breaks the goal of parity with the dockerfile build mechanisms, but it would be an additional feature for buildah.

**Steps to reproduce the issue:**
1. Create Dockerfile.mytest
2. Create Dockefile.mytest.dockerignore
3. Build with buildah, notice the dockerignore is not utilized.

**Describe the results you received:**
Files intended to be ignore were copied in

**Describe the results you expected:**
Files intended to be ignored are not copied in

**Output of `rpm -q buildah` or `apt list buildah`:**

```
N/A
```

**Output of `buildah version`:**

```
N/A
```

**Output of `podman version` if reporting a `podman build` issue:**

```
podman version 3.4.2
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```

**Output of `uname -a`:**

Can't share, unfortunately.

**Output of `cat /etc/containers/storage.conf`:**

Can provide upon request, but I don't thinkkkk it's relevant here.

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by flouthoc** [comment]
I think this is only supported with buildkit backend, PR https://github.com/containers/buildah/pull/4239 should close this.

**Comment by nalind** [comment]
Yeah, I don't know where it's documented, but can confirm it happens when `docker build` is run with `DOCKER_BUILDKIT=1` set in the environment.

**Comment by rhatdan** [comment]
I think we should default to BUILDKIT enabled mode.  I don't believe people will accidentally create files with these names.

**Comment by SpencerMalone** [comment]
Y'all are actually the best ❤️
