### ISSUE TITLE
allow `--cache-ttl=0` to be equivalent to `--no-cache`

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#4244]
`--cache-ttl` was added in https://github.com/containers/buildah/pull/4165. Currently `--cache-ttl=0` is equivalent to having not specified `--cache-ttl` at all. It would be nice if the option accepted a value of `0` and allowed it to effectively mean `--no-cache`.

This would allow programs that pass through values to `podman` or `buildah` to use one pass through argument rather than two. i.e. something like https://github.com/coreos/coreos-assembler/blob/5ffbf12d229854a79c0b1e53ce2bc4ffdeda5c88/src/cmd-remote-build-container#L194-L197

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
@dustymabe Above PR https://github.com/containers/buildah/pull/4248 should close this.

**Comment by nalind** [comment]
Did `--cache-ttl=0` still populate the cache, even if its contents weren't used?

**Comment by flouthoc** [comment]
@nalind I think `--no-cache` also populates the cache without using it. We had a different opened card somewhere to introduce new API split populating and using cache.

**Comment by nalind** [comment]
Well the cache is still just the images we build along the way.
