### ISSUE TITLE
Add support for BuildKit's interpretation of the VOLUME instruction

### ISSUE THREAD

**Issue by eriksjolund** [containers/buildah#4247]
**Description**

Docker has an optional builder [BuildKit](https://docs.docker.com/engine/reference/builder/#buildkit) that interprets the `VOLUME` instruction in a new way. Implement an optional mode in Buildah that interprets the `VOLUME` instruction in the same way as BuildKit.
The GitHub comment:

* https://github.com/moby/moby/discussions/44104#discussioncomment-3593939

describes the difference between the classic Docker builder and Buildkit in regards to their handling of  the `VOLUME` instruction.

**Comment by rhatdan** [comment]
I would rather just use the buildkit definition, and move forward.

**Comment by eriksjolund** [comment]
> I would rather just use the buildkit definition, and move forward.

Sounds good
