### ISSUE TITLE
architecture variant (v8) is not set on arm64

### ISSUE THREAD

**Issue by kit-ty-kate** [containers/buildah#4276]
**Description**

Using the following dockerfile:
```
FROM --platform=freebsd/arm64/v8 scratch
COPY some-empty-file /some-empty-file
```
`buildah build` will create an image with `os=freebsd`, `architecture=arm64` but the `variant` (`v8`) is not set (as shown by `buildah inspect`)

If you replace `--platform=freebsd/arm64/v8` with `--platform=freebsd/arm/v7` the `variant` is set this time.

**Describe the results you expected:**

The `variant` variable should probably be set, though I'm not sure what is supposed to be the default. I'm only basing my assumption on the behaviour of docker.

**Output of `buildah version`:**

```
buildah version 1.27.1 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

**Comment by flouthoc** [comment]
@kit-ty-kate Thanks for creating the issue, above PR should close this https://github.com/containers/buildah/pull/4286
