### ISSUE TITLE
Feature request - ${VAR_NAME:?} dockerfile syntax to error on unset variables

### ISSUE THREAD

**Issue by jwhitaker-swiftnav** [containers/buildah#4284]
## Description

Docker supports ${SOME_VAR:?} syntax, which will give an error at build if SOME_VAR is unset. I believe this is directly in the Dockerfile syntax, not via a shell. Buildah doesn't support this, so this feature request is to request support for this syntax.

Example:

### Docker

```Dockerfile
FROM public.ecr.aws/docker/library/node:16-alpine as builder

ARG USERID

USER ${USERID:?}
```
```sh
docker build .
```
```
...
Step 3/3 : USER ${USERID:?}
failed to process "${USERID:?}": USERID: is not allowed to be unset
# exit 1
```

### Buildah/Podman

Buildah/Podman don't support this syntax:
```sh
podman build .
```
```
...
Error: error resolving step {Value:user Next:0xc0002ae8c0 Children:[] Attributes:map[] Original:USER ${USERID:?} Flags:[] StartLine:5 EndLine:5}: Unsupported modifier (?) in substitution: ${USERID:?}
```

This is a genuinely useful feature, so my request goes beyond just for the sake of compatibility.

## Extra Info

**Output of `podman version`:**

```
podman version 4.2.1
buildah version 1.27.1 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 4:4.2.1-0ubuntu22.04+obs57.1 amd64 [installed]
buildah/unknown,now 1.27.1-0ubuntu22.04+obs25.1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No
Latest version in the kubic repo, haven't tried building from master.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker version for comparison:
```
Docker version 20.10.18, build b40c2f6
```

**Comment by flouthoc** [comment]
Hi @jwhitaker-swiftnav , Thanks for creating the issue. 

I was unable to find any formal documentation for this, but I think we can implement this at imagebuilder. @nalind Any thoughts ? Since this is not a documented  behavior.

**Comment by rhatdan** [comment]
If this is a legitimate Dockerfile then we should support it. Whether it is documented or not. (Well maybe not if it is considered experimental)

@edsantiago Is this a special Bashism?

**Comment by edsantiago** [comment]
It's a common bashism; I have no knowledge of docker's level of support for it.
```
Parameter Expansion

  ${parameter:?word}
     Display  Error if Null or Unset.  If parameter is null or unset, the
     expansion of word (or a message to that effect if word is not present) is
     written to the standard error and the shell, if it is not interactive, exits.
     Otherwise, the value of parameter is substituted.
```

**Comment by sanmai-NL** [comment]
@rhatdan @edsantiago Importantly, this is not Bashism, but [standard/POSIX/SUS](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02). It also works in practice in other shells, e.g., Ash.

**Comment by rhatdan** [comment]
@flouthoc any time to work on it?

**Comment by rhatdan** [comment]
@flouthoc any time to work on it?

**Comment by flouthoc** [comment]
I'll check this thanks.

**Comment by flouthoc** [comment]
@jwhitaker-swiftnav Thanks PR https://github.com/openshift/imagebuilder/pull/243 should close this.
