### ISSUE TITLE
golangci-lint throws error when using podman/v4/bindings

### ISSUE THREAD

**Issue by amokkara** [containers/buildah#4294]
**Description**

Raising issue here since its mentioned in podman issues page 

~/aditya/podman_test # CGO_ENABLED=0 ./bin/golangci-lint run --timeout 5m
WARN [runner] Can't run linter goanalysis_metalinter: buildssa: failed to load package images: could not load export data: no export data for "github.com/containers/podman/v4/pkg/bindings/images"
ERRO Running error: 1 error occurred:
* can't run linter goanalysis_metalinter: buildssa: failed to load package images: could not load export data: no export data for "github.com/containers/podman/v4/pkg/bindings/images"

But surprisingly, this works for v3/pkg/bindings. No error seen there. need help to understand the issue here.

**Steps to reproduce the issue:**
1.Run golangci-lint on a project using podman/bindings v4
2.
3.

**Describe the results you received:**
error when running golint

**Describe the results you expected:**
expected to pass the lint

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by flouthoc** [comment]
Hi @amokkara , Could you run `make vendor` and try again ? I think this needs `go mod tidy`.

Also this issue looks more like `podman` repo, could you let us know the reason of opening this in buildah repo ?

**Comment by amokkara** [comment]
> Hi @amokkara , Could you run `make vendor` and try again ? I think this needs `go mod tidy`.
> 
> Also this issue looks more like `podman` repo, could you let us know the reason of opening this in buildah repo ?

Hi @flouthoc , thanks for the response. In podman issues page, its mentioned to open issue in buildah if its related to podman build issue. hence i raised it here.

**Comment by flouthoc** [comment]
Ah I see fair enough, I think this is rather a local config issue could you please try `make vendor` or `go mod tidy` and try again.

**Comment by amokkara** [comment]
i have tried go mod tidy. Same result. I dont see an entry for v4/bindings/images in go.sum file even after running go mod tidy.
i dont know if its issue with golint or the code or ...

Anyways thanks for your input. closing the issue
