### ISSUE TITLE
CONTRIBUTING.md out of date? Freenode?

### ISSUE THREAD

**Issue by AndASM** [containers/buildah#4308]
The `CONTRIBUTING.md` file directs new contributors to the `#buildah` channel on `irc.freenode.net`, which appears to be dead. It also appears there may have been some major changes and drama at freenode in the last year that resulted in many projects and individuals moving to libera.chat, or other platforms.

Is `CONTRIBUTING.md` out of date? What are the current recommendations for communication? Where should more general questions that aren't direct issues with this repository or software go? Such as if someone had questions on how to contribute, standards, or similar? Or is it just that no one has the time or interest for that relating to this project?

**Comment by rhatdan** [comment]
It should be changed to irc.libera.chat

But it might be best to change the line to:

```
For general questions and discussion, please use the IRC #podman channel on irc.libera.chat.
```

Since there is much more activity over there and likely someone who can help you with your issues/questions.

Care to open a PR to make the change?

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL
