### ISSUE TITLE
COPY DOT DOT considered harmful

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4314]
Followup to #4310. Test is [failing under podman](https://api.cirrus-ci.com/v1/artifact/task/5960273050730496/html/bud-podman-fedora-36-root-host.log.html#t--00004):
```
STEP 6/6: COPY . .
Error: building at STEP "COPY . .": reading "/var/tmp/buildah_tests.hnlvcs": error during bulk transfer for copier.request{Request:"GET", Root:"/", preservedRoot:"/var/tmp/buildah_tests.hnlvcs", rootPrefix:"/var/tmp/buildah_tests.hnlvcs", Directory:"/", preservedDirectory:"/var/tmp/buildah_tests.hnlvcs", Globs:[]string{"/"}, preservedGlobs:[]string{"/var/tmp/buildah_tests.hnlvcs"}, StatOptions:copier.StatOptions{CheckForArchives:false, Excludes:[]string(nil)}, GetOptions:copier.GetOptions{UIDMap:[]idtools.IDMap(nil), GIDMap:[]idtools.IDMap(nil), Excludes:[]string(nil), ExpandArchives:false, Cho
...long long long long list of stuff
```
Is it super-important to use `COPY . .`? Can it be just `RUN echo hi` or something?

Anyhow, @flouthoc, if you're working on the `--os` thing, could you also fix this?

**Comment by flouthoc** [comment]
@edsantiago Not a real bug, it looks like code is hitting system/env limit for path length. Its just that context dir in podman and buildah tests have different content. But I agree the test does not needs a blanket/expensive `COPY . .` therefore removing it here: https://github.com/containers/buildah/pull/4316
