### ISSUE TITLE
--all-platforms clobbers --build-arg

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4399]
Using `--all-platforms` removes the ability to use `--build-arg`:
```console
$ printf "ARG foo\nFROM \$foo\n" | bin/buildah build --build-arg foo=quay.io/libpod/alpine --all-platforms -t foo -
Error: resolving image name "$foo": cannot parse input: "$foo": invalid reference format
```
When you fix this, please also fix this instance of evil hardcoding:
```diff
diff --git a/tests/bud/multiarch/Dockerfile.no-run b/tests/bud/multiarch/Dockerfile.no-run
index dbdac3e1e..ef89ae651 100644
--- a/tests/bud/multiarch/Dockerfile.no-run
+++ b/tests/bud/multiarch/Dockerfile.no-run
@@ -3,5 +3,6 @@ FROM docker.io/library/alpine                                                                                                                  
 COPY Dockerfile.no-run /root/
 # A different base image that is known to be a manifest list, supporting a
 # different but partially-overlapping set of platforms.
-FROM quay.io/libpod/testimage:20221018
+ARG SAFEIMAGE
+FROM $SAFEIMAGE
 COPY --from=0 /root/Dockerfile.no-run /root/
```

**Comment by rhatdan** [comment]
@edsantiago I just fixed this and accidentally force pushed it to main branch.

**Comment by edsantiago** [comment]
Oh! Now I get it, thanks. That was a weird email notification ("closed in SHA", but no associated PR).

Your fix doesn't look quite right. Now when I use the `printf` above I get:
```
Error: resolving image name "": cannot parse input: "": repository name must have at least one component
```

**Comment by flouthoc** [comment]
@rhatdan You accidentally pushed to main without PR

**Comment by flouthoc** [comment]
@rhatdan We might wanna revert it since not all tests are passing with it and main is broken.

**Comment by flouthoc** [comment]
`main` is broken and commit https://github.com/containers/buildah/commit/217b2d524c041674066f2e0d329ec2ad5a62004b also assumes that `ENV` must be evaluated while actually `ENV` must be only evaluated inside `RUN` statement and not for any `Containerfile` instructions.

I have created a PR https://github.com/containers/buildah/pull/4401 to fix this and it should fix `main` as well.
