### ISSUE TITLE
`.dockerignore`/`.containerignore` `podman build` glob semantics differ from Docker Engine's `docker build`

### ISSUE THREAD

**Issue by sanmai-NL** [containers/buildah#4434]
[`podman build` supports `**`](https://docs.podman.io/en/latest/markdown/podman-build.1.html#files).
[`docker build` does not](https://docs.docker.com/engine/reference/builder/#dockerignore-file). See also e.g. https://github.com/moby/moby/issues/30018#issuecomment-271649155.

Is it possible to limit the `**` support to `.containerignore` files? Or is that unhelpful in terms of interoperability?

**Comment by rhatdan** [comment]
Does it work if you use
docker buildx build?

Buildah is closer to buildx versus classic docker build.

I don't see Buildah removing this, so I am going to close.  But continue the conversation here.
