### ISSUE TITLE
Software installation always report errors with Buildah version v1.28 when building image

### ISSUE THREAD

**Issue by xinfeingxia85** [containers/buildah#4436]
**Description**
Software installation always fails with Buildah version v1.28, the error is as follows:
```
STEP 1/2: FROM ubuntu
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob e96e057aae67 done
Copying config a8780b506f done
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN apt-get update &&     apt-get install -y curl
error running subprocess: creating new mount namespace for [/bin/sh -c apt-get update &&     apt-get install -y curl]: operation not permitted
Error: building at STEP "RUN apt-get update &&     apt-get install -y curl": exit status 1
```
But it works fine with Buildah version v.1.27
**Steps to reproduce the issue:**
1. Environment setting
 ```
export BUILDAH_FORMAT=docker
export STORAGE_DRIVER=vfs
export BUILDAH_LAYERS=true
 ```
2. Create one Dockerfile
```
FROM ubuntu

RUN apt-get update && \
    apt-get install -y curl
```
3. Build image
```
docker run --rm -it --security-opt seccomp=unconfined  quay.io/buildah/stable:v1.28 /bin/bash
buildah bud -t test:v1 .
```

**Describe the results you received:**
The result is that installing software fails and has the above error.

**Describe the results you expected:**
The building image is successful.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.28.0-6.fc37.x86_64
```

**Output of `buildah version`:**

```
Version:         1.28.0
Go Version:      go1.19.2
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.23.0
Git Commit:
Built:           Tue Oct 25 14:14:21 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 37 (Thirty Seven)
NAME="Fedora Linux"
VERSION="37 (Container Image)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
VARIANT="Container Image"
VARIANT_ID=container
Fedora release 37 (Thirty Seven)
Fedora release 37 (Thirty Seven)
```

**Output of `uname -a`:**

```
Linux 7697521d3c52 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flouthoc** [comment]
Hi @xinfeingxia85 , Thanks for reporting this. I was able to reproduce with `docker` and can confirm that this is been fixed on `main` branch after as a by-product of  https://github.com/containers/storage/pull/1415 and https://github.com/containers/buildah/pull/4388 by @giuseppe 

Unfortunately there is no already built image for `main` branch but I think buildah should publish it if maintainers agree on it.

Meanwhile if you want a temporary workaround with your existing image you can use additional `--cap-add SYS_ADMIN` i.e `sudo docker run --rm -it --security-opt seccomp=unconfined  --cap-add SYS_ADMIN quay.io/buildah/stable:v1.28 /bin/bash`

**Comment by flouthoc** [comment]
@xinfeingxia85 You can use `quay.io/buildah/upstream` for using the buildah directly from upstream till new version i.e `v1.29` is released.

**Comment by flouthoc** [comment]
I'm closing this issue but please feel free to discuss below.
