### ISSUE TITLE
quay.io: publish `main` tag  on `quay.io/buildah`

### ISSUE THREAD

**Issue by flouthoc** [containers/buildah#4437]
Hi Team,

Just creating this issue for discussion. Would it be possible to publish a build from `main` branch on `quay.io/buildah` since it will allow users to use build directly from `main` branch in their pipelines.

Could be helpful in issues like this: https://github.com/containers/buildah/issues/4436

Thanks

**Comment by flouthoc** [comment]
@cevich @lsm5 @containers/buildah-maintainers WDYT ?

**Comment by lsm5** [comment]
I'm guessing `quay.io/buildah/upstream` should do that already?? It installs buildah from `rhcontainerbot/podman-next`.

**Comment by flouthoc** [comment]
@lsm5 Thanks, this works and contains buildah from `upstream`. Closing this.
