### ISSUE TITLE
checking for build stage status 10 times/second via external runtime exec

### ISSUE THREAD

**Issue by paravz** [containers/buildah#4481]
**Description**
Buildah checks if a build stage container is running every 100 msec per https://github.com/containers/buildah/blob/d87b736c39219009693c3dbc553ae786c0fb236a/run_common.go#L676

I noticed that invoking https://github.com/containers/buildah/blob/d87b736c39219009693c3dbc553ae786c0fb236a/run_common.go#L649 results in running `/usr/bin/crun --systemd-cgroup state buildah-buildahXXXX` 10 times a second for duration of the build step, a few minutes in my case

**Steps to reproduce the issue:**
1. Create a sample Docker file with "RUN sleep 300" as one of the steps
2. run podman build (or equivalent buildah command)
3. in a separate terminal run `sudo dnf install bcc-tools && sudo /usr/share/bcc/tools/execsnoop -TxU` to see runtime (ie crun) invocations, alternatively strace or debugger can be used

**Describe the results you received:**
Execution of `/usr/bin/crun --systemd-cgroup state buildah-buildahXXXX` 10 times a second for the duration of a Dockerfile build step

**Describe the results you expected:**
Exponential back off or similar solution to reduce overhead for longer jobs.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
# rpm -q buildah podman
package buildah is not installed
podman-4.3.1-1.fc37.x86_64
```

**Output of `buildah version`:**

```
#per https://github.com/containers/podman/blob/main/RELEASE_NOTES.md:
v1.28.0
```

**Output of `podman version` if reporting a `podman build` issue:**

```
# podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 07:01:27 2022
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 37 (Thirty Seven)
```

**Output of `uname -a`:**

```
Linux 6.0.12-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:58:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# cat /etc/containers/storage.conf|grep -vE "^\s*#|^\s*$"
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

**Comment by flouthoc** [comment]
@paravz Thanks I created a PR , could you please try the patch and see if max delay limit is correct for your use-case.

**Comment by paravz** [comment]
@flouthoc thank you for the PR! Code makes sense to me, but i don't have a good understanding on how to test this change in isolation.

**Comment by rhatdan** [comment]
Basically run your tests against the new backoff you should see quite a lot less checks on output.

**Comment by giuseppe** [comment]
why is it a problem?

The proposed solution will make the build slower since it takes longer to realize the container terminated

**Comment by flouthoc** [comment]
@paravz If you could help describing the actual issue due to polling 10times/second it will help us decide the correct way to implement this and maybe make exponential backoff configurable via a flag.

**Comment by paravz** [comment]
I noticed some resource consumption during longer build steps. I was monitoring all execs on the system via `sudo dnf install bcc-tools && sudo /usr/share/bcc/tools/execsnoop -TxU`. For me this issue is mostly an annoyance (resource consumption is still low), looks a lot like an accidental fork bomb.

**Comment by flouthoc** [comment]
@paravz We were discussing it here https://github.com/containers/buildah/pull/4492 the exec calls are pretty cheap and the problem is that it will make build slower for users who are not concerned with this issue. I have a suggestion if you and maintainers agree with it that we make this behavior configurable via `--exponential-backoff-monitor` ( or some better name ) and let it be opt in choice for the users. Would something like this work for you ? 

@rhatdan @giuseppe WDYT ?

**Comment by giuseppe** [comment]
before we opt for complicating the design, let's understand the issue first.  One thing we can try is to monitor the container PID using pidfd or even the equivalent of `kill -0 $PID` on older systems

**Comment by giuseppe** [comment]
barely tested, but is there any disadvantage in the following simplification?

```diff
diff --git a/run_common.go b/run_common.go
index b11f38da1..b561ba30d 100644
--- a/run_common.go
+++ b/run_common.go
@@ -580,10 +580,12 @@ func runUsingRuntime(options RunOptions, configureNetwork bool, moreCreateArgs [
 	var stopped uint32
 	var reaping sync.WaitGroup
 	reaping.Add(1)
+	exited := make(chan interface{}, 1)
 	go func() {
 		defer reaping.Done()
 		var err error
 		_, err = unix.Wait4(pid, &wstatus, 0, nil)
+		exited <- nil
 		if err != nil {
 			wstatus = 0
 			options.Logger.Errorf("error waiting for container child process %d: %v\n", pid, err)
@@ -644,33 +646,12 @@ func runUsingRuntime(options RunOptions, configureNetwork bool, moreCreateArgs [
 	signal.Notify(interrupted, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM)
 	for {
 		now := time.Now()
-		var state specs.State
-		args = append(options.Args, "state", containerName)
-		stat := exec.Command(runtime, args...)
-		stat.Dir = bundlePath
-		stat.Stderr = os.Stderr
-		stateOutput, err := stat.Output()
-		if err != nil {
-			if atomic.LoadUint32(&stopped) != 0 {
-				// container exited
-				break
-			}
-			return 1, fmt.Errorf("reading container state from %s (got output: %q): %w", runtime, string(stateOutput), err)
-		}
-		if err = json.Unmarshal(stateOutput, &state); err != nil {
-			return 1, fmt.Errorf("parsing container state %q from %s: %w", string(stateOutput), runtime, err)
-		}
-		switch state.Status {
-		case "running":
-		case "stopped":
-			atomic.StoreUint32(&stopped, 1)
-		default:
-			return 1, fmt.Errorf("container status unexpectedly changed to %q", state.Status)
-		}
 		if atomic.LoadUint32(&stopped) != 0 {
 			break
 		}
 		select {
+		case <-exited:
+			atomic.StoreUint32(&stopped, 1)
 		case <-finishedCopy:
 			atomic.StoreUint32(&stopped, 1)
 		case <-time.After(time.Until(now.Add(100 * time.Millisecond))):
```

**Comment by rhatdan** [comment]
Can you try it with libkrun to see if it works?

**Comment by rhatdan** [comment]
I believe that for libkrun the process running the VM is the PID1 of the container.
I don't know about KATA but I would figure something similar.

**Comment by rhatdan** [comment]
Since I have had no further feedback , I am closing.
