### ISSUE TITLE
Add command to clear build cache, and especially cache mounts

### ISSUE THREAD

**Issue by Clockwork-Muse** [containers/buildah#4486]
**Description**

Currently, there does not appear to be a command to clear build cache via buildah (nothing obvious presents itself with `buildah --help`, anyways).  

Additionally, even if build cache is cleared via `podman system prune`, build-time cache mounts are not removed.  
So far, the only workaround I've found is `podman system reset` which seems... rather much.  Attempting to "reset" the cache via modifying the `RUN ...` directive seems potentially terrifying, depending on the environment the offending cache lives, and could be troublesome in distributed CI scenarios

Build-time cache mounts also are not discarded/ignored in conjunction with `--cache-ttl`, but I'm not completely sure if that's intended behavior or not.

**Steps to reproduce the issue:**
1. Build the following containerfile:
```Dockerfile
FROM docker.io/ubuntu

ARG CACHE_DIR=/some_cache_dir

RUN \
    #
    # Mounted cache directories
    --mount=type=cache,id=15022054c90073ed509dc66593e80ff4ae5dcd6c9967911024bc85ed64069b6e,target=${CACHE_DIR} \
    ls -al ${CACHE_DIR} \
    && touch ${CACHE_DIR}/some-cache-file \
    && ls -al ${CACHE_DIR}
```
2. "Attempt" to clear the build cache via `podman system prune -af --volumes`
3. Rebuild

**Describe the results you received:**

Despite clearing the build cache, build-time cache mounts retain data.

**Describe the results you expected:**

Clearing the build cache also clears build-time cache mounts.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Listing... Done
buildah/unknown,now 1.28.2-0ubuntu22.04+obs36.6 amd64 [installed]
buildah/unknown 1.28.2-0ubuntu22.04+obs36.6 arm64
buildah/unknown 1.28.2-0ubuntu22.04+obs36.6 armhf
buildah/unknown 1.28.2-0ubuntu22.04+obs36.6 s390x
```

**Output of `buildah version`:**

```
Version:         1.28.2
Go Version:      go1.18.1
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  
image Version:   5.23.0
Git Commit:      
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.1
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Output of `uname -a`:**

```
Linux bumblebee 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by flouthoc** [comment]
I agree that `system prune` should clean the build cache and mount cache both. Also I think buildah should contain `prune` command as well just like buildkit https://github.com/moby/buildkit#cache

**Comment by flouthoc** [comment]
Created a PR https://github.com/containers/buildah/pull/4490
