### ISSUE TITLE
Documentation outdated; newer Golang is needed for compilation

### ISSUE THREAD

**Issue by lxg** [containers/buildah#4488]
Following the installation instructions for Linux, I tried compiling with Go 1.13 (as indicated in the docs) which yielded me the following result: 

```
build github.com/opencontainers/runc: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
make: *** [Makefile:132: runc] Error 1
```

With Go 1.16, I got

```
GO111MODULE=on go build -mod=vendor -ldflags '-X main.GitCommit=d87b736c39219009693c3dbc553ae786c0fb236a -X main.buildInfo=1672315441 -X main.cniVersion=v1.1.2 ' -gcflags "" -o bin/buildah -tags "apparmor seccomp btrfs_noversion exclude_graphdriver_btrfs libdm_no_deferred_remove  " ./cmd/buildah
vendor/github.com/openshift/imagebuilder/builder.go:14:2: //go:build comment without // +build comment
vendor/github.com/klauspost/compress/zstd/blockdec.go:17:2: //go:build comment without // +build comment
vendor/github.com/containers/storage/pkg/archive/archive_zstd.go:6:2: //go:build comment without // +build comment
make: *** [Makefile:73: bin/buildah] Error 1
```

After upgrading to Go 1.19, it compiled flawlessly.

I would be happy to contribute a PR to fix the documentation; however, I’m not really familiar with Go and how to write universally applicable instructions. My recommendation would be to avoid hardcoding the version number in the shell commands, as it currently is, and instead provide more generic instructions.

**Comment by rhatdan** [comment]
Care to open a PR to fix the documentation

**Comment by lxg** [comment]
As mentioned, I have no clue about best practices for Go. Should I give it a try anyway?

**Comment by rhatdan** [comment]
Just change it to the latest version go 1.19

**Comment by flouthoc** [comment]
I am not sure if buildah is officially being tested with `go 1.16` anywhere. I'd recommend updating to newer version. I think @lsm5 was trying to build with `go 1.16` or `go 1.17` few weeks back and in IRC it was decided that we are not testing with older versions anymore.

I am closing this issue but we should reopen if you think something is unresolved.

**Comment by lsm5** [comment]
> I am not sure if buildah is officially being tested with `go 1.16` anywhere. I'd recommend updating to newer version. I think @lsm5 was trying to build with `go 1.16` or `go 1.17` few weeks back and in IRC it was decided that we are not testing with older versions anymore.
> 
> I am closing this issue but we should reopen if you think something is unresolved.

wasn't 1.16 EOL'd recently ?
