### ISSUE TITLE
make: btrfs.go:385:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4494]
Not sure what's going on, but buildah no longer builds on my f37 laptop:
```console
$ make
GO111MODULE=on go build -mod=vendor -ldflags '-X main.GitCommit=f8eb73820a20d8c72af469c0ac4b56ec1d503816 -X main.buildInfo=1672774878 -X main.cniVersion=v1.1.2 ' -gcflags "" -o bin/buildah -tags "seccomp      systemd" ./cmd/buildah
# github.com/containers/storage/drivers/btrfs
vendor/github.com/containers/storage/drivers/btrfs/btrfs.go:385:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)
make: *** [Makefile:73: bin/buildah] Error 2
```
I tried `git-co` an older version, same thing. So it looks like it might be f37 breakage. I don't have time to explore right now, filing so it doesn't fall through the cracks.

**Comment by edsantiago** [comment]
Cause: my f37 laptop went from btrfs 6.0 to 6.1

Root cause: https://github.com/kdave/btrfs-progs/commit/03451430de7cd2fad18b0f01745545758bc975a5

Solution: wait for btrfs to unsnafu, release, and upgrade. See also https://github.com/containers/storage/issues/1454

**Comment by flouthoc** [comment]
@edsantiago Following PR https://github.com/containers/buildah/pull/4495 should fix it.
