### ISSUE TITLE
CI and f37 gating tests: failure in --runtime-flag test - maybe crun?

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4503]
Impossible-to-debug failure in [f37 gating tests](https://artifacts.dev.testing-farm.io/ce80a461-8a70-4fb4-a94c-b948cd0eecec/):
```
not ok 696 run --runtime --runtime-flag
# (in test file /usr/share/buildah/test/system/run.bats, line 810)
#   `[ -n "$output" ]' failed
# /usr/share/buildah/test/system /var/str
# # [checking for: docker.io/library/alpine]
# # [restoring from cache: /var/tmp/buildah-image-cache.5515 / docker.io/library/alpine]
# Getting image source signatures
# Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
# Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
# Writing manifest to image destination
# Storing signatures
# $ /usr/bin/buildah from --security-opt seccomp=/var/tmp/buildah_tests.6b1cxe/seccomp.json --quiet --pull=false --signature-policy /usr/share/buildah/test/system/policy.json alpine
# alpine-working-container
# $ /usr/bin/buildah run --runtime=crun --runtime-flag=debug alpine-working-container true
# /var/str
```
The broken test is being fixed in #4502; until that merges we can't actually know what happened. One possibility is that `crun` changed somehow, such that `debug` no longer produces debug output? The test failure suggests that this command:
```console
$ buildah run --runtime=crun --runtime-flag=debug alpine-working-container true
```
...should produce output, but it isn't? Could this be a crun change? A change in how buildah passes the `--runtime-flag` option?

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by edsantiago** [comment]
This is now breaking all CI jobs [[example]( https://cirrus-ci.com/task/6294483348750336?logs=integration_test#L1438)]:
```
[+2905s] # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[+2905s] # #|     FAIL: Output from running 'true' with --runtime-flag=debug
[+2905s] # #| expected: != ''
[+2905s] # #|   actual:    ''
[+2905s] # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by edsantiago** [comment]
@flouthoc @giuseppe @nalind PTAL high priority? All of CI is broken, and gating-tests will be too. I don't know if this is a breakage in crun, or buildah, or some other component. This should be very quick for one of you to figure out. TIA.

**Comment by Luap99** [comment]
I guess https://github.com/containers/buildah/pull/4514 broke it here because it updated the VM images without running the full tests. Likely some change in the underlying oci runtime that is used.
cc @cevich

**Comment by Luap99** [comment]
git bisect points to https://github.com/containers/crun/pull/1042/commits/c4af47ea4daae9125dc175c8c0affb3816f77983
I have no idea how this is related, @giuseppe @flouthoc PTAL

**Comment by flouthoc** [comment]
Checking

**Comment by giuseppe** [comment]
that happens because newer crun versions use a cache for seccomp, so the warning happens only the first time it is built

**Comment by giuseppe** [comment]
one way to address it would be to use a new root directory:

```
diff --git a/tests/run.bats b/tests/run.bats
index 7f8d1d7d9..8c82b124f 100644
--- a/tests/run.bats
+++ b/tests/run.bats
@@ -824,7 +824,7 @@ _EOF
 
        if [ -n "$(command -v crun)" ]; then
                found_runtime=y
-               run_buildah run --runtime=crun --runtime-flag=debug $cid true
+               run_buildah run --runtime=crun --runtime-flag=root=${TEST_SCRATCH_DIR}/crun --runtime-flag=debug $cid true
                assert "$output" != "" "Output from running 'true' with --runtime-flag=debug"
        fi
```

**Comment by Luap99** [comment]
are there no debug logs in crun? runc prints a lot of verbose logs, maybe crun should do so too? At least --debug implies that it does not only print warnings.

**Comment by giuseppe** [comment]
not really, we added --debug just for CLI compatibility with runc

**Comment by Luap99** [comment]
fair enough, if your diff fixes the test please open a PR with it

**Comment by giuseppe** [comment]
I'd rather prefer we drop the check, it has an assumption on the behavior of the runtime that is not documented anywhere

**Comment by Luap99** [comment]
That is an option but how should `--runtime-flag` be tested then? I guess it could use the same thing like the bud test does? https://github.com/containers/buildah/blob/39dfa738929571c05dd595d3fb9804de583769cc/tests/bud.bats#L4754-L4773

**Comment by giuseppe** [comment]
proposed fix: https://github.com/containers/buildah/pull/4523
