### ISSUE TITLE
Flake: bud-multiple-platform-with-base-as-default-arg: duplicate 'arm'

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4520]
New flake blowing up in podman-land today:
```
[+1439s] not ok 322 bud-multiple-platform-with-base-as-default-arg
...
# buildah manifest inspect localhost/testlist
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: arch list in manifest
#| expected: = '386 amd64 arm arm arm64 ppc64le s390x'
#|   actual:   '386 amd64 arm arm64 ppc64le s390x'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Culprit seems to be the duplicate "arm" here:  https://github.com/containers/buildah/blob/9d987b92129dd41bd5e1643efa4914448970d2a4/tests/bud.bats#L5314

No idea why it's a flake: it seems like the sort of thing that should always fail.

### [bud] bud-multiple-platform-with-base-as-default-arg
* fedora-37 : bud podman fedora-37 root host
  * Podman PR 17126
    * [01-16 09:18](https://api.cirrus-ci.com/v1/artifact/task/5329548850495488/html/bud-podman-fedora-37-root-host.log.html#t--00322)
* fedora-37 : bud remote fedora-37 root host [remote]
  * Podman PR 17126
    * [01-16 09:47](https://api.cirrus-ci.com/v1/artifact/task/6084458609115136/html/bud-remote-fedora-37-root-host.log.html#t--00322)

**Comment by edsantiago** [comment]
Submitted #4521 as possible fix. I'll leave it to others to understand what actually went wrong; all I care about is eliminating flakes.

**Comment by edsantiago** [comment]
Per discussion on IRC: the two `arm`s are intentional. Something about v6 and v7.

**Comment by vrothberg** [comment]
@nalind is this the flake you were referring to in libimage?  It is suuuuuper flaky in Podman at the moment.

**Comment by nalind** [comment]
Yes, I believe that this is also https://github.com/containers/common/issues/1295#issuecomment-1387043876.
