### ISSUE TITLE
Docker-format image in Manifest List `application/vnd.oci.image.manifest.v1+json`

### ISSUE THREAD

**Issue by flouthoc** [containers/buildah#4551]
### Discussed in https://github.com/containers/buildah/discussions/4549

<div type='discussions-op-text'>

<sup>Originally posted by **andrewm-aero** February  1, 2023</sup>
I'm not sure if this is a bug, and if so, on whose side, but the [latest dockerhub ubuntu images](https://hub.docker.com/layers/library/ubuntu/focal-20230126/images/sha256-d5d4814ffb155d588f10ec8926d9e1cd09b6d41a3110d2f42959e2fc37f6d0b4?context=explore) (pushed today) are not pull-able by buildah, complaining that they have an `unsupported OCIv1 media type: "application/vnd.docker.container.image.v1+json"`. Docker, on the other hand, pulls it just fine. Taking it apart, it does in fact appear to be an OCIv1 wrapper with an entire docker v1 image as an element, rather than separate layers and configs as you'd expect. 

I've never heard of such a thing. Is this valid, or does this suggest an error on Ubuntu's part? [This code](https://github.com/containers/image/blob/abae97a8306d61cc66addba6b3d0e1ad81d83045/manifest/oci.go#L44) appears to be what determines this (non-)compatibility, and sure enough, that media type is not listed.</div>

**Comment by IceWreck** [comment]
Facing the same thing here.

**Comment by flouthoc** [comment]
I think issue might be with how ubuntu list was created but docker supports it so I think podman should support it too.

**Comment by giuseppe** [comment]
@mtrmac @vrothberg PTAL

**Comment by vrothberg** [comment]
Looks like a bug in c/image to me since the manifest includes
```
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2
}
```

**Comment by saschagrunert** [comment]
I agree we should accept the `DockerV2Schema2` in that case.

**Comment by vrothberg** [comment]
Scratch what I wrote above.  The Ubuntu image is invalid:
```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 2299,
    "digest": "sha256:58db3edaf2be6e80f628796355b1bdeaf8bea1692b402f48b7e7b8d1ff100b02"
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 29528717,
      "digest": "sha256:677076032cca0a2362d25cf3660072e738d1b96fe860409a33ce901d695d7ee8"
    }
  ]
}
```

An OCI image cannot ship with a Docker config.  It's violating the OCI spec.

**Comment by vrothberg** [comment]
@rcj4747 are you the right contact person for the Ubuntu images?

**Comment by rcj4747** [comment]
> @rcj4747 are you the right contact person for the Ubuntu images?

Not, not for a little while now, but @j5awry or @philroche might be about to get you a step closer to the right owners.

**Comment by vrothberg** [comment]
Thanks a lot, @rcj4747!

**Comment by stefanstoeckigt** [comment]
They seem to be aware of the issue: https://github.com/docker-library/official-images/pull/13950

**Comment by philroche** [comment]
Also being tracked @ https://bugs.launchpad.net/cloud-images/+bug/2004425

@cjdcordeiro is tracking.

**Comment by cjdcordeiro** [comment]
:+1: 

I'll be posting updates here -> https://github.com/docker-library/official-images/issues/13983

In short, some tools are quite forgiving of this mixing of mediaTypes, while others aren't. We are building new images with all media types being oci-specific.

**Comment by vrothberg** [comment]
Thanks a lot, @cjdcordeiro!

I am going to close the issue here and ask folks to follow/engage in https://github.com/docker-library/official-images/issues/13983 instead.

**Comment by cjdcordeiro** [comment]
quick update: PR with the fix- > https://github.com/docker-library/official-images/pull/13988

**Comment by flouthoc** [comment]
Thanks for the update @cjdcordeiro
