### ISSUE TITLE
buildah login fails if syntax is wrong

### ISSUE THREAD

**Issue by sando38** [containers/buildah#4557]
**Description**

Not sure if this is a bug or feature.

This fails:

```
$ cat password.txt | buildah login docker.io -u user --password-stdin
Error: too many arguments, login takes only 1 argument
```

However, this works: 

```
$ cat password.txt | buildah login -u user --password-stdin docker.io 
Login Succeeded
```

When using `podman` instead of `buildah` both variants work.

**Describe the results you expected:**

I would have expected that `buildah` and `podman` behave similar.

**Output of `buildah version`:**

```
$ buildah --version
buildah version 1.29.0 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

The machine runs ArchLinux.

**Comment by flouthoc** [comment]
Thanks I think PR should close this https://github.com/containers/buildah/pull/4558
