### ISSUE TITLE
Versions after 1.28.0 are not available in Docker registry as separate tags

### ISSUE THREAD

**Issue by slonopotamus** [containers/buildah#4560]
1. Navigate to [buildah releases](https://github.com/containers/buildah/releases)
2. Observe that there exist 1.29.0, 1.28.2, 1.28.1 and so on.
3. Navigate to https://quay.io/repository/buildah/stable?tab=tags
4. Observe that the latest available version is 1.28.0

I would expect to be able to run any of the released versions as an image.

I additionally checked https://quay.io/repository/buildah/testing?tab=tags. It provides `latest` tag that resolves to 1.29.0 as of today. But it will most likely change when there's a new buildah release and might break my CI builds. Just in case: 1.28.1 and 1.28.2 are not available.

I additionally checked https://quay.io/repository/buildah/upstream?tab=tags. It also provides `latest` tag that resolves to 1.30.0-dev, which is too much unreliable for production use. 1.28.1 and 1.28.2 are still not seen anywhere.

**Comment by flouthoc** [comment]
Hi @slonopotamus , I think it will be automatically updated once released for fedora. cc @cevich

**Comment by slonopotamus** [comment]
Well, I have no idea what the process is) But I see that neither of 1.25.x ever got published. Maybe you might want to consider decoupling of image publishing process from Fedora and instead build images (using CI or whatever) as soon as buildah release is cut?

**Comment by slonopotamus** [comment]
Okay
