### ISSUE TITLE
[regression] Almost all buildah commands started to require either `CAP_SYS_ADMIN` or `unshare(CLONE_NEWUSER)` syscomp policy

### ISSUE THREAD

**Issue by slonopotamus** [containers/buildah#4563]
**Steps to reproduce the issue:**
1. Default Docker 20.10.x (in my case, 20.10.22) seccomp policy
2. `docker run --rm -it quay.io/buildah/upstream:latest buildah --storage-driver=vfs info` or `docker run --rm -it quay.io/buildah/upstream:latest buildah --storage-driver=vfs images`

**Describe the results you received:**

```
Error during unshare(CLONE_NEWUSER): Operation not permitted
ERRO[0000] parsing PID "": strconv.Atoi: parsing "": invalid syntax 
ERRO[0000] (Unable to determine exit status)
```

**Describe the results you expected:**

I'd expect that `CAP_SYS_ADMIN` or `unshare(CLONE_NEWUSER)` are only required in case buildah **runs** nested containers. I should even be able to `buildah build` a Dockerfile that doesn't contain `RUN` instructions.

This all **worked** for buildah v1.28.0:

```
$ docker run --rm -it quay.io/buildah/stable:v1.28.0 buildah --storage-driver=vfs info
{
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "fedora",
            "version": "37"
        },
< snip>
}

$ docker run --rm -it quay.io/buildah/stable:v1.28.0 buildah --storage-driver=vfs images
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
```

**Output of `buildah version`:**

```
$ docker run --rm -it quay.io/buildah/upstream:latest buildah --storage-driver=vfs version
Version:         1.30.0-dev
Go Version:      go1.19.5
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.24.0
Git Commit:      
Built:           Thu Feb  2 14:10:01 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `uname -a`:**

```
$ uname -a
Linux noblesse 5.15.80-gentoo-x86_64 #1 SMP Sat Dec 10 21:45:12 MSK 2022 x86_64 AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux
```

**Additional info:**

The issue comes from the fact that [buildah calls `unshare.MaybeReexecUsingUserNamespace`](https://github.com/containers/buildah/blob/v1.29.0/cmd/buildah/main.go#L150), which, starting with https://github.com/containers/storage/pull/1415 attempts to `unshare(CLONE_NEWUSER)` when run as a root without `CAP_SYS_ADMIN`.

**Comment by devurandom** [comment]
I get a similar issue when trying to build an image in CircleCI:
```sh
buildah build \
  --tag "${IMAGE_NAME}:${CIRCLE_SHA1}" \
  --annotation org.opencontainers.image.authors="${CIRCLE_USERNAME}" \
  --annotation org.opencontainers.image.revision="${CIRCLE_SHA1}" \
  .
```

The error is:
```
Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: operation not permitted
WARN[0000] failed to shutdown storage: "mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: operation not permitted" 

Exited with code exit status 125
```

The `Containerfile` is:
```Containerfile
FROM docker.io/library/eclipse-temurin:17.0.6_10-jre@sha256:ab4ea8ace9acd2a9b19489cd2a8e8236a722257668d07a0a5a1f7ecaa9242bb1
CMD ["-javaagent:/javaagent.jar", "-jar", "/app.jar"]
COPY javaagent/javaagent.jar /javaagent.jar
COPY target/app-*-standalone.jar /app.jar
```

Is this related, or should I open a separate issue?

**Comment by rhatdan** [comment]
Most likely a separate issue.

**Comment by sjdrc** [comment]
Also started experiencing the exact same issue all of a sudden, After bumping gitlab-runner from 0.49.0 to 0.51.0

**Comment by rhatdan** [comment]
@giuseppe @flouthoc thoughts?

**Comment by giuseppe** [comment]
this seems like a duplicate of https://github.com/containers/buildah/issues/1901.

Buildah needs CAP_SYS_ADMIN to be useful, either granted directly to its environment or being able to create a new user namespace (so `unshare` must be allowed)

**Comment by rhatdan** [comment]
FROM and COPY also need to be able to store UIDs that are not the same as the UID of the user running BUILDAH, which means that we need to create a user namespace for rootless users at least.

**Comment by ivanov17** [comment]
I have the similar issue with a custom Buildah image  based on the official Fedora 38 image. The reason I build custom image is because I'm using a Buildbot worker in the same container to run the Buildah process. I use the almost the same build instructions for my image that are used for the official Buildah image. I'm running containers using Podman on Centos 9 Stream. 

My bild process fails every time when Buildah tries to chroot into its own build directory. Here is the build log:

```
buildah build --root /data/buildah/storage --file buildbot-worker/Containerfile --tag 192.168.100.110:5000/buildbot-worker
 in dir /data/buildah/build (timeout 1200 secs)
 watching logfiles {}
 argv: [b'buildah', b'build', b'--root', b'/data/buildah/storage', b'--file', b'buildbot-worker/Containerfile', b'--tag', b'192.168.100.110:5000/buildbot-worker']
 environment:
  BUILDAH_ISOLATION=chroot
  DISTTAG=f38container
  FGC=f38
  HOME=/data
  HOSTNAME=buildbot
  LC_CTYPE=C.UTF-8
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PWD=/data/buildah/build
  TERM=xterm
  TZ=Etc/UTC
  WORKERNAME=containers
  container=oci
 using PTY: False
STEP 1/24: FROM quay.io/fedora/fedora-minimal:latest
STEP 2/24: ENV TZ=Etc/UTC
STEP 3/24: ENV BUILDAH_ISOLATION=chroot
STEP 4/24: RUN mkdir /data && chown 101:101 /data
Error: building at STEP "RUN mkdir /data && chown 101:101 /data": error in copier subprocess: chrooting to directory "/data/buildah/storage/overlay/e3513e69bf4327c9f973802dd80e4b97b7867a431dffa64866c56c1e17d595f2/merged": operation not permitted
program finished with exit code 125
elapsedTime=2.244802
```

My image is labeled with `io.containers.capabilities`:

```
"io.containers.capabilities": "CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,NET_BIND_SERVICE,SETFCAP,SETGID,SETPCAP,SETUID,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,NET_BIND_SERVICE,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT"
```


I even tried to add `CAP_SYS_ADMIN` to the capabilities list, but it has no effect. 

Is this the same issue, or do I need to create a new issue for this?

**Comment by ivanov17** [comment]
A thousand apologies... I just forgot to use the `--security-opt label=disable` and `--security-opt seccomp=unconfined` options. If I run my container with them, it works as it should. I'll just leave this here for those who have a bad memory like me.

**Comment by slonopotamus** [comment]
This is a **bad** advice because it removes lots of layers of security.

----

Anyway. I got the impression that buildah devs are not going to continue to support unprivileged containers, so this issue can be closed.

**Comment by ivanov17** [comment]
> This is a **bad** advice because it removes lots of layers of security.

But this is an official recommendation: 

>  turn off label and seccomp confinement in the container

https://quay.io/repository/buildah/stable?tab=info

I think it's okay if the container is not on the host network, but in the same pod with the local registry

**Comment by slonopotamus** [comment]
> But this is an official recommendation

So what? This is a bad official recomendation. Code running as root inside `seccomp=unconfined` can [load kernel modules](https://tbhaxor.com/breakout-from-seccomp-unconfined-container/) and do other nasty stuff.

**Comment by giuseppe** [comment]
You only need to allow unshare and clone*.  You don't need to allow all the syscalls

**Comment by ivanov17** [comment]
> Code running as root inside `seccomp=unconfined` container can [load kernel modules into host](https://tbhaxor.com/breakout-from-seccomp-unconfined-container/) and do other nasty stuff.

This is true, but using Buildah to create container images does not require root privileges

**Comment by slonopotamus** [comment]
> But using Buildah to create container images does not require root privileges

But documentation [documentation that was referenced above](https://quay.io/repository/buildah/stable?tab=info) suggests running with root privileges inside unconfined container.

**Comment by dghubble** [comment]
I hit this in an environment that runs buildah within a Kubernetes Pod.

```
Error during unshare(CLONE_NEWUSER): Permission denied
level=error msg="parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
```

The changelog doesn't mention that suddenly buildah has different needs, starting around v1.30. For Kubernetes pods, just adding the `SYS_CAP_ADMIN` capability to the security context wasn't sufficient. `privileged` solves it, but that's not a great workaround.

**Comment by rhatdan** [comment]
This looks like you are running on a platform with seccomp rules that dropped the unshare syscall,

**Comment by magnus-longva-bouvet** [comment]
> I hit this in an environment that runs buildah within a Kubernetes Pod.
> 
> ```
> Error during unshare(CLONE_NEWUSER): Permission denied
> level=error msg="parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
> ```
> 
> The changelog doesn't mention that suddenly buildah has different needs, starting around v1.30. For Kubernetes pods, just adding the `SYS_CAP_ADMIN` capability to the security context wasn't sufficient. `privileged` solves it, but that's not a great workaround. End result here is our security is weakened, when the intention was certainy the opposite.

Did you just misspell the capability? `CAP_SYS_ADMIN` , not `SYS_CAP_ADMIN`. It works for me.
