### ISSUE TITLE
Feature Request - Provide compiled execautables in release tags

### ISSUE THREAD

**Issue by vikas027** [containers/buildah#4577]
It would be great to have the releases as executable in the [release ](https://github.com/containers/buildah/releases) tags. I know I can can build one on my own but again just good customer experience :)

How/Where it is helpful?
I am using `Ubuntu 22.04` and the latest available release I have is `v1.23.1` (Sep 29, 2021) while the latest released version is v.1.29.0. I have had the executable in the release, I would have just downloaded off via curl and get going.

**Comment by flouthoc** [comment]
I am not sure why we don't ship the binary but I think @cevich @TomSweeneyRedHat could tell this better.

**Comment by rhatdan** [comment]
Because Buildah requires additional tools to run, netavark, aardvark-dns, crun, conmon ...

Static linking of buildah would break certain functionality as well.

We only support use within distributions.

**Comment by rhatdan** [comment]
If you want to use buildah, you can run it in  a container.

quay.io/buildah/stable.
