### ISSUE TITLE
Disable Dependabot after renovate trial

### ISSUE THREAD

**Issue by cevich** [containers/buildah#4588]
**Description**

With https://github.com/containers/buildah/pull/4567 merged, both renovate and dependabot are operating on this repo. Assuming things go well, (they both find the same set of dep. updates) once this issue goes stale, dependabot may be disabled. That includes BOTH the settings and any .github/dependabot.yml configuration file.

**Steps to reproduce the issue:**
1. Wait

**Describe the results you received:**

Both Renovate and Dependabot open PRs on the same dependency updates

**Describe the results you expected:**

Only one tool opens PRs for dependency updates

**Output of `rpm -q buildah` or `apt list buildah`:**

N/A

**Output of `buildah version`:**

N/A

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

N/A

**Output of `uname -a`:**

N/A

**Output of `cat /etc/containers/storage.conf`:**

N/A

**Comment by rhatdan** [comment]
@cevich should we disable Dependabot?

**Comment by cevich** [comment]
Yep, I think we're ready now.  I'll take care of it.
