### ISSUE TITLE
Buildah does not use pulled layers for caching

### ISSUE THREAD

**Issue by kponichtera** [containers/buildah#4612]
**Description**

I noticed that Buildah does not reuse the layers, pulled from the registry before building the same image. It doesn't do it even when the `--layers` parameter or `BUILDAH_LAYERS` variable is used. Instead, when the image is freshly pulled, subsequent `buildah build` calls still execute all the steps in the Dockerfile. The issue is still there when `podman` is used instead of `buildah`. I'm trying to pull and build in my Gitlab pipelines, where it's faster than using `--cache-from` and `--cache-to`, and doesn't require me to configure registry cleanup policies.

This is different than how Docker behaves, where calling `docker build` after pulling the image will reuse all the layers and finish the build without running single Dockerfile instruction. I'm not sure if it's a bug, if it's by design or if I'm missing another flag or toggle.

Dockerfile for reproducing the issue:

```Dockerfile
FROM docker.io/library/golang:1.20

ARG GOFUMPT_VERSION=v0.3.1

RUN go install mvdan.cc/gofumpt@$GOFUMPT_VERSION \
    && go clean --cache
```

**Steps to reproduce the issue:**
1. Build the Dockerfile with `buildah build -t docker.io/<your_repo>/buildahcachetest:latest --layers`
2. Push the image with `buildah push docker.io/<your_repo>/buildahcachetest:latest`
3. Try to build it again to make sure that local cache is utilized
4. Purge Buildah and Podman local data with `buildah rm --all && podman system reset -f`
5. Pull the previously built image `buildah pull docker.io/<your_repo>/buildahcachetest:latest`
6. Try to build the image again

**Describe the results you received:**

The output from first build looks as follows:

```
STEP 1/3: FROM docker.io/library/golang:1.20
Trying to pull docker.io/library/golang:1.20...
Getting image source signatures
Copying blob 52d5f431180a done  
Copying blob 6c1024729fee done  
Copying blob aa54add66b3a done  
Copying blob 1e4aec178e08 done  
Copying blob c3aa11fbc85a done  
Copying blob bb80f942c8f4 done  
Copying blob 36946d8e120b done  
Copying config 56d1b895b7 done  
Writing manifest to image destination
Storing signatures
STEP 2/3: ARG GOFUMPT_VERSION=v0.3.1
--> 1569c84cc2b
STEP 3/3: RUN go install mvdan.cc/gofumpt@$GOFUMPT_VERSION     && go clean --cache
go: downloading mvdan.cc/gofumpt v0.3.1
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8
go: downloading github.com/google/go-cmp v0.5.7
go: downloading golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3
go: downloading golang.org/x/tools v0.1.10
COMMIT docker.io/konpon96/buildahcachetest:latest
--> 2ebc62ac34d
Successfully tagged docker.io/konpon96/buildahcachetest:latest
2ebc62ac34db99fcf1cdd7891eb804e3922cf06e3e5209e0444b4fdb26bbd18d
```

Running second build reuses the built layers:

```
STEP 1/3: FROM docker.io/library/golang:1.20
STEP 2/3: ARG GOFUMPT_VERSION=v0.3.1
--> Using cache 1569c84cc2b258de6195a77d9be8581c95b0a5b32c8b25649c4cf8fcde621fd6
--> 1569c84cc2b
STEP 3/3: RUN go install mvdan.cc/gofumpt@$GOFUMPT_VERSION     && go clean --cache
--> Using cache 2ebc62ac34db99fcf1cdd7891eb804e3922cf06e3e5209e0444b4fdb26bbd18d
COMMIT docker.io/konpon96/buildahcachetest:latest
--> 2ebc62ac34d
Successfully tagged docker.io/konpon96/buildahcachetest:latest
2ebc62ac34db99fcf1cdd7891eb804e3922cf06e3e5209e0444b4fdb26bbd18d
```

After purging Buildah and Podman's local data, pulling the image from the registry, I get the following output:

```
STEP 1/3: FROM docker.io/library/golang:1.20
Trying to pull docker.io/library/golang:1.20...
Getting image source signatures
Copying blob 52d5f431180a skipped: already exists  
Copying blob 6c1024729fee skipped: already exists  
Copying blob 36946d8e120b skipped: already exists  
Copying blob aa54add66b3a skipped: already exists  
Copying blob c3aa11fbc85a skipped: already exists  
Copying blob bb80f942c8f4 skipped: already exists  
Copying blob 1e4aec178e08 skipped: already exists  
Copying config 56d1b895b7 done  
Writing manifest to image destination
Storing signatures
STEP 2/3: ARG GOFUMPT_VERSION=v0.3.1
--> 43fbd555a54
STEP 3/3: RUN go install mvdan.cc/gofumpt@$GOFUMPT_VERSION     && go clean --cache
go: downloading mvdan.cc/gofumpt v0.3.1
go: downloading golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/google/go-cmp v0.5.7
go: downloading golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3
go: downloading golang.org/x/tools v0.1.10
COMMIT docker.io/konpon96/buildahcachetest:latest
--> e658fa0d334
Successfully tagged docker.io/konpon96/buildahcachetest:latest
e658fa0d334a2dd0bfbc5e943df1cc38f1340ef728067249b55d76228434d46a
```

**Describe the results you expected:**

Once the local Buildah/Podman data is removed and the built image is pulled from the registry, I expected its output to look as follows, where no Dockerfile instruction is executed and instead all of them are taken from the freshly-pulled image.

```
STEP 1/3: FROM docker.io/library/golang:1.20
STEP 2/3: ARG GOFUMPT_VERSION=v0.3.1
--> Using cache 1569c84cc2b258de6195a77d9be8581c95b0a5b32c8b25649c4cf8fcde621fd6
--> 1569c84cc2b
STEP 3/3: RUN go install mvdan.cc/gofumpt@$GOFUMPT_VERSION     && go clean --cache
--> Using cache 2ebc62ac34db99fcf1cdd7891eb804e3922cf06e3e5209e0444b4fdb26bbd18d
COMMIT docker.io/konpon96/buildahcachetest:latest
--> 2ebc62ac34d
Successfully tagged docker.io/konpon96/buildahcachetest:latest
2ebc62ac34db99fcf1cdd7891eb804e3922cf06e3e5209e0444b4fdb26bbd18d
```

**Output of `pacman -Ss buildah`:**

```
community/buildah 1.29.0-1 [installed]
    A tool which facilitates building OCI images
```

**Output of `buildah version`:**

```
Version:         1.29.0
Go Version:      go1.19.5
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.24.0
Git Commit:      94b723cb5b70948efd282bd62ef07e8c7c04fdaf
Built:           Sun Jan 29 01:55:20 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```
**Output of `cat /etc/*release`:**

```
cat: /etc/release: No such file or directory)
```

(using Arch Linux)

**Output of `uname -a`:**

```
Linux pc 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

Comments skipped for brevity.

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]
pull_options = {enable_partial_images = "false", use_hard_links = "false", ostree_repos=""}

[storage.options.overlay]
mountopt = "nodev"

[storage.options.thinpool]

```

**Comment by flouthoc** [comment]
Hi @kponichtera , build's distributed cache is different from `buildkit` inorder to use intermediate images buildah only supports `--cache-to` and `--cache-from`, the image you pulled from the repo does not works because its missing the intermediate layers. I'd suggest switching to `--cache-to` and `--cache-from` approach.

**Comment by kponichtera** [comment]
Thanks for clarifying @flouthoc. I ended up using `--cache-to` and `--cache-from`, it's not as fast as the aforementioned pull in Docker, but after optimizations of the Dockerfile instructions, the layers are loaded from the repository much faster (e.g. after placement of `ARG` instructions just below `FROM`, no idea why it affected the performance).

However, I still find it intriguing. From my understanding, the OCI image consists of multiple layers, which are pushed and pulled to and from the registry. That's why I expected Buildah to reuse the pulled layers during the build - they must be available anyway, otherwise the pulled image couldn't be instantiated into the container. The only thing that comes to my mind is that there is a local cache layer storage, which is separate from the standard container one - especially since building the image locally makes subsequent builds instantaneous. However, it could lead to inefficient storage, since many layers would be stored twice. Is that a thing?

Many CI/CD instructions out there (e.g. for Github and Gitlab), which rely on starting ephemeral Docker, could use some daemonless goodness. Reusing layers would allow for drop-in replacement of Docker, by simply changing the tool from `docker` to `buildah` and removing the extra service, spawned for each job. However, being able to pull layers directly into Buildah's cache would allow avoiding having an extra repository for `--cache-to` and `--cache-from` layers. Doing it this way not only requires a separate repo, but also configuring additional retention policies to purge old cache, which is often overkill. People who believe too much in the `alias docker=podman` or `alias docker=buildah` approach might spend a lot of time (and CI/CD minutes) to figure out why their builds do not get cached, even though they are not using multi-stage Dockerfiles.

Since it's a deviation from the usual Docker behavior and workflow, is there a place in the documentation where it could be beneficial to mention that discrepancy?

**Comment by flouthoc** [comment]
@kponichtera Yes buildah's distrubuted cache is different from docker and more in line with how distributed cache works in kaniko, it is due to how buildah intermediate caching mechanism is designed. The kaniko and buildah's method have their own perks i.e parent image is not inflated with intermediate images, intermediate images are truly distributed ( can be kept in different registry or same as well ), two different images don't need to carry same intermediate image.

 > Doing it this way not only requires a separate repo

 No it does not needs a different repo, all intermediate image can be kept in the same repo but they will have different tags
 
 @kponichtera However i agree with you that difference need to be documented hence I created a PR: https://github.com/containers/buildah/pull/4644 and maybe in future maybe buildah could support both its original cache mechanism and buildkit's model as well.
