### ISSUE TITLE
Buildah in rootless podman : "mkdir [dir] : operation not permitted"

### ISSUE THREAD

**Issue by hiimheregit** [containers/buildah#4627]
**Description**

Hello,

Building a simple container using this Containerfile : 

```
FROM private.registry.com/[...]/ubi8-minimal:8.7
USER root
COPY file.txt /opt/tstt/file.txt
```

I have tried a few things along these lines to get it working but that didn't help, it keeps failing :

Edit : I have also tried adding `--cap-add=all`, same result.

```
(root)$ buildah bud --tls-verify=false --storage-driver=overlay  --device=/dev/fuse --cgroup-manager cgroupfs --security-opt seccomp=unconfined --security-opt label=disable /tmp/test

Fails with `error building at STEP "COPY file.txt /opt/tstt/file.txt": error ensuring target directory exists: copier: mkdir: error checking directory "/opt/tstt": mkdir /opt/tstt: operation not permitted
```

Instead using `vfs` works : 

```
(root)$ buildah bud --tls-verify=false --storage-driver=vfs /tmp/test

[...]
Writing manifest to image destination
Storing signatures
--> 38dda0f376f
38dda0f376f5b2437034e97f393fbc26a28932b9c808ee877a88c2b384758f2d
```

This is how I run buildah with podman : 

```
(unpriv user)$ podman run -it --device=/dev/fuse -v "./test/:/tmp/test" private.registry.com/[...]/buildah:8.6
```

I was hoping somebody could eventually help me out understanding why it doesn't work.

Thanks for help in advance.

**Steps to reproduce the issue:**
1. Configure rootless podman (and all the deps like explained in the doc)

```
$ vim ~/.config/containers/storage.conf

[storage]

driver = "overlay"
runroot = "/run/user/$UID/containers"
rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options.overlay]

mount_program = "/usr/bin/fuse-overlayfs"
```

2. Run buildah with podman using an unprivileged user : `podman run -it --device=/dev/fuse -v "./test/:/tmp/test" reg.com/[...]/buildah:8.6`
3. Try to build a test image : `buildah bud --tls-verify=false --storage-driver=overlay --device=/dev/fuse /tmp/test` -> operation not permitted to mkdir

**Describe the results you received:**

Operation not permitted

**Describe the results you expected:**

Image should build ?

**Output of `rpm -q buildah` or `apt list buildah` (inside container) :**

```
buildah-1.26.2-1.module+el8.6.0+16771+28dfca77.x86_64
```

**Output of `buildah version` (inside container):**

```
Version:         1.26.2
Go Version:      go1.17.7
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.0
image Version:   5.21.1
Git Commit:      
Built:           Thu Sep 29 22:54:19 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
Red Hat Enterprise Linux release 8.7 (Ootpa)
Red Hat Enterprise Linux release 8.7 (Ootpa)
```

**Output of `uname -a`:**

```
Linux 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of ~~`cat /etc/containers/storage.conf`~~ `cat /home/[unpriv-user]/.config/containers` :**

```
[storage]

driver = "overlay"
runroot = "/run/user/$UID/containers"
rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options.overlay]

mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by giuseppe** [comment]
what is the environment where you are running buildah?

A podman container?

**Comment by hiimheregit** [comment]
Yes, a podman container.

**Comment by giuseppe** [comment]
could you try using the `:testing` image for buildah?

**Comment by hiimheregit** [comment]
Indeed, it works.

Running podman : 

`podman run -it --device=/dev/fuse -v "./test/:/tmp/test" quay.io/buildah/testing:latest`

Buildah in podman rootless : 

`buildah bud --tls-verify=false /tmp/test`

And it works without specifying any of the parameters I tried above.

Would you mind providing an insight about what the problem is ?

**Comment by giuseppe** [comment]
we need this patch: https://github.com/containers/storage/pull/1415
