### ISSUE TITLE
Podman build adds labels if building the same image with different tags, unlike docker, buildah

### ISSUE THREAD

**Issue by Victoremepunto** [containers/buildah#4632]
### Issue Description

I'm observing a discrepancy with regards to how `podman` build handles labels in comparison with the equivalent `docker` or `buildah` commands.

Building a `dockerfile` for a specific tag adding a specific label, and then building the same dockerfile for a different tag, without the label, has different results in `podman` , where the metadata is added to the new tag too. This is different from what `Docker` or `Buildah` do for the exact same command.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman build -t some-image:some-tag-with-labels --labels somefancylabel=true .
2. podman build -t some-image:some-tag-without-labels .
3. podman inspect some-image:some-tag-without-labels | grep 'somefancylabel'

step 3 should not have any match. 

Repeating the same steps but replacing `podman` with either `docker` or `buildah` does not produce any output (as expected?) on step 3.

I prepared a [dummy repo with a Github Action showcasing this behavior](https://github.com/Victoremepunto/test-image-labels/pull/1/files), feel free to check it, I hope is self-explanatory

### Describe the results you received

Step 3 - inspecting the image looking for labels - should not yield any labels

### Describe the results you expected

Step 3 yields labels when inspecting the second image and using `grep` to find matches for the label created for the first image

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Tested on Fedora 37, and on Github Actions with current `ubuntu-latest`

**Comment by flouthoc** [comment]
This is happening because we are applying labels to all the intermediate layers as well instead of applying label only to the final image, one solution is to modify stage_executor so we only actually apply label to the final step and skip applying label to all the intermediate steps. @nalind WDYT ?

**Comment by Victoremepunto** [comment]
> podman build --no-cache -t some-image:some-tag-without-labels

That should work, but we loose the ability to reuse the cache which slows down our build time, unfortunately. 
Is there any other mitigation / workaround we could use ? we're working around this by either using `docker` in some pipelines, or adding the label to the Dockerfile at runtime (so we get a different hash) that won't be present on the release. 

It's a bit ugly but works for now, tough I would not like to keep it like this for much time

**Comment by nalind** [comment]
> This is happening because we are applying labels to all the intermediate layers as well instead of applying label only to the final image, one solution is to modify stage_executor so we only actually apply label to the final step and skip applying label to all the intermediate steps. @nalind WDYT ?

Yes, the bit in `StageExecutor.commit()` that applies the passed-in labels to every image should probably have been ditched in #4511, with the "append a synthetic LABEL line" logic from `buildDockerfilesOnce()` being appended to either the final stage or every stage instead.

**Comment by flouthoc** [comment]
PR https://github.com/containers/buildah/pull/4673 should close this.
