### ISSUE TITLE
Update the packages in Debian and Ubuntu

### ISSUE THREAD

**Issue by teokon90** [containers/buildah#4646]
Hello,

i am checking the versions in Debian:Bullseye and Ubuntu:Jammy in official packages.

In Debian is the 1.19 version and in Ubuntu the 1.23 of Buildah.

Are you going to upgrade the latest versions to both distributions ?

Thank you

**Comment by flouthoc** [comment]
I am not sure if any buildah maintainer have access to that but @lsm5 can help you in pointing to right direction.

**Comment by lsm5** [comment]
@teokon90 Hi, the containers upstream doesn't own the official debian and ubuntu packages, so there's nothing we can do. I suggest filing an issue on the distro's bug tracker. Also copying @siretart who maintains the official buildah packages on those distros. He generously donates his spare time towards maintaining these and I'm sure he'll appreciate any additional hands if you're able and willing.

Closing ...
