### ISSUE TITLE
Buildah `--cache-to` not working with remote AWS Elastic Container Registry

### ISSUE THREAD

**Issue by DaanGebraad** [containers/buildah#4672]
**Description**

When building an image using buildah build in combination with `--layers` and `--cache-to` with a remote AWS ECR image an error is thrown.

**Steps to reproduce the issue:**
1. Build an image using `--layers` and `--cache-to` using an ECR remote location
`
aws ecr get-login-password | buildah login --username AWS --password-stdin $CI_REGISTRY
buildah build
            --layers
            --cache-to ${CI_REGISTRY}:latest-develop
            --target server
            -f .docker/Dockerfile
            -t $CI_REGISTRY:$BUILD_TAG
            -t $CI_REGISTRY:$CI_COMMIT_SHORT_SHA .
`

**Describe the results you received:**
The following error is thrown:
`Error: unable to parse value provided `[****:latest-develop]` to --cache-to: repository must contain neither a tag nor digest: ****:latest-develop`

**Describe the results you expected:**
A successful build leveraging the remote image as a cache.

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
@DaanGebraad Could you remove tag `latest-develop` from `--cache-to` and only pass `--cache-to ${CI_REGISTRY} ... your other options`. Since buildah stores intermediate images as cache with tags automatically.

**Comment by DaanGebraad** [comment]
This solved it, thanks!
