### ISSUE TITLE
Pass multiple host environment variables during `buildah run`

### ISSUE THREAD

**Issue by cbandy** [containers/buildah#4688]
**Description**

`podman run` will pass multiple environment variables from the host to the container when the name passed to [`--env` ends with `*`](https://docs.podman.io/en/latest/markdown/podman-run.1.html#env-e-env):

> As a special case, if an environment variable ending in `*` is specified without a value, Podman will search the host environment for variables starting with the prefix and will add those variables to the container.

> ```
> $ export ENV1=a
> $ podman run --env 'ENV*' alpine env | grep ENV
> ENV1=a
> ```

I have found this very useful for tools that can be configured through the environment. It would be great if `buildah run` also had this behavior. For example,

```console
$ export TOOL_ONE=1 TOOL_TWO=profit
$ CONTAINER=$(buildah from alpine)
$ buildah run --env 'TOOL_*' "${CONTAINER}" -- env
…
TOOL_ONE=1
TOOL_TWO=profit
```

**Output of `buildah version`:**

```
buildah version 1.27.3 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version`:**

```
podman version 4.2.0
```

**Comment by rhatdan** [comment]
This sounds like a good idea, and I would recommend that it be done to buildah run as well as buildah build.

Interested in opening a PR to make this happen?

**Comment by cbandy** [comment]
I started to look at this. `buildah build` also has an `--unsetenv` flag. Should it do any globbing?

```
      --unsetenv strings               unset environment variable from final image
```

**Comment by rhatdan** [comment]
If we do globbing on setenv, then to me it makes sense that we do it on unsetenv.

**Comment by cbandy** [comment]
🤔 I see also `buildah config --env`. Any thoughts about that?

**Comment by rhatdan** [comment]
Same.  They should all handle globs.

**Comment by flouthoc** [comment]
This seems to be already fixed.
