### ISSUE TITLE
buildah quay.io image now triggers an overlay mount error

### ISSUE THREAD

**Issue by duck-rh** [containers/buildah#4727]
**Description**

We use the quay.io buildah stable image to build an image and it now fails. It seems the image changed while the buildah version stayed at 1.29.1 and the GL runners as well our personal runners all trigger the problem. Using the same version but not this image is a simple workaround though, more below.

**Steps to reproduce the issue:**

I'm not totally sure about all conditions that are necessary to trigger the problem.

1. build an image using quay.io/buildah/stable on a GL runner

**Describe the results you received:**

```
time="2023-04-10T05:24:38Z" level=error msg="Unmounting /var/lib/containers/storage/overlay/2ab7e2e69ab745698479320e2ec6a357d878a688e3fcc141c3eb7dc3c55545c1/merged: invalid argument"
Error: mounting new container: mounting build container "cf1cf827797128f6b16338d15d4046733b6a758aa44a5fb760f918b85afcf04e": creating overlay mount to /var/lib/containers/storage/overlay/2ab7e2e69ab745698479320e2ec6a357d878a688e3fcc141c3eb7dc3c55545c1/merged, mount_data="lowerdir=/var/lib/containers/storage/overlay/l/UYVRA2Y5XFAFZ2VMMYIES47F5L,upperdir=/var/lib/containers/storage/overlay/2ab7e2e69ab745698479320e2ec6a357d878a688e3fcc141c3eb7dc3c55545c1/diff,workdir=/var/lib/containers/storage/overlay/2ab7e2e69ab745698479320e2ec6a357d878a688e3fcc141c3eb7dc3c55545c1/work,nodev,fsync=0,userxattr,volatile": invalid argument
```
See https://gitlab.com/osci/prometheus-exporter-exporter-container/-/jobs/4085194541
(I just added a tag command but the build part is unchanged)

I got this error with gitlab.com runners, but can replicate it with our runners, one on F37 kernel 6.0.7-301.fc37.x86_64 and the other F36 and kernel 5.18.9-200.fc36.x86_64.

It looks a little bit like #4704 but it is not the same. Also 1.29.1 worked before.

**Describe the results you expected:**

It should build the image without problem like it did not long ago with the same version.
See https://gitlab.com/osci/prometheus-exporter-exporter-container/-/jobs/4039291717

If I use a centos stream 9 image, install buildah (which happens to have the same exact version) and do the build, then all works well.
See https://gitlab.com/osci/prometheus-exporter-exporter-container/-/jobs/4085112209
(the CI fails because I made a mistake in the tag command but the build works)

**Output of `buildah version`:**

```
Version:         1.29.1
Go Version:      go1.19.5
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.24.1
Git Commit:      
Built:           Fri Feb 17 10:05:41 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Comment by flouthoc** [comment]
Dup of : https://github.com/containers/buildah/issues/4715 , therefore I am closing this.

**Comment by duck-rh** [comment]
@flouthoc I don't understand. This bug states that this is a problem for *old* kernels, but 6.0.7 is way newer than the 5.13 version stated in your own comment which led me to think this is a different problem.

**Comment by flouthoc** [comment]
@duck-rh I think its happening because `mount_program` `fuseoverlay` is removed now its using `native overlay` but setting wrong mount options which were valid for `fuseoverlay`, we need to fix default config which is being shipped with image, previously it worked cause storage driver was hard set to use `fuse-overlay`.

**Comment by flouthoc** [comment]
I have closed this because underlying problem is same as #4715 , either is using native overlay with wrong options or not using fuseoverlay for older functions I think quick fix is this one https://github.com/containers/buildah/pull/4722

**Comment by duck-rh** [comment]
@flouthoc thanks for the explanation, makes sense now. I'll follow the development on the other ticket then.

Btw since there is a CI problem too, I would suggest keeping 1or 2 older images around, that would have made testing the different pieces easier instead of guessing the image was the problem (since buildah version displays everything identical this was really not obvious).
