### ISSUE TITLE
store name of stage inside metadata/labels

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#4729]
### Discussed in https://github.com/containers/buildah/discussions/4728

<div type='discussions-op-text'>

<sup>Originally posted by **tobwen** April  9, 2023</sup>
## summary
When building images with **named** multiple stages, the name isn't stored anywhere. Making the name available in metadata (for example in labels) would make developing and debugging way easier.

## example
``` sh
podman build -t stages_demo - <<EOF
# stage 1
FROM alpine AS findme
RUN echo "hello" >> /podman.txt

# stage 2
FROM findme AS release
RUN echo "world" >> /podman.txt
EOF

[1/2] STEP 1/2: FROM alpine AS findme
[1/2] STEP 2/2: RUN echo "hello" >> /podman.txt
--> c54f74d6cc9
[2/2] STEP 1/2: FROM c54f74d6cc97487a1116841a2b2d380a387a38d111bb7b28116ed4d3f2110251 AS release
[2/2] STEP 2/2: RUN echo "world" >> /podman.txt
[2/2] COMMIT stages_demo
--> 9669170f524
Successfully tagged localhost/stages_demo:latest
9669170f5249c48ef090de9748c20781956d97304972f19818c91399a3be32ab
```

## test
Neither `findme`, nor `release` can be found.

``` sh
# docker image inspect c54f74d6cc97487a1116841a2b2d380a387a38d111bb7b28116ed4d3f2110251 | grep -i findme; echo $?
1

# docker image inspect 9669170f5249c48ef090de9748c20781956d97304972f19818c91399a3be32ab | grep -i findme; echo $?
1

# docker image inspect c54f74d6cc97487a1116841a2b2d380a387a38d111bb7b28116ed4d3f2110251 | grep -i release; echo $?
1

# docker image inspect 9669170f5249c48ef090de9748c20781956d97304972f19818c91399a3be32ab | grep -i release; echo $?
1
```</div>

**Comment by danishprakash** [comment]
How do you think the output should look like, if we were to add the stage names as an array under labels or metadata, something like the following?

```
	  "Labels": {
	      "stages": ["findme", "release"],
	  }
```

**Comment by rhatdan** [comment]
@flouthoc WDYT?

**Comment by flouthoc** [comment]
@tobwen Could you please let us know why do you need such feature, I am trying to understand the use-case behind this requirement ? Just wondering in case we have a easier workaround for your use-case using existing features.

**Comment by rhatdan** [comment]
Since we never heard back, closing, reopen if you have feed back and still want this feature.

**Comment by tobwen** [comment]
I'm so sorry, I completely forgot about this topic.

I'm building via the multistage method with 6 stages in total. Every now and then I want to peek into a stage. Luckily, the stages aren't deleted by default, but it's hard to find them.

During build, each stage gets a image ID only, for example:

``` dockerfile
# image ID: --> d57b5a995f2f
FROM docker://postgres:15-bookworm AS deps ...
RUN ...

# image ID: --> a8064d84a4f7
FROM deps AS cgal
RUN ...

# image ID: 8469cdf2daba
FROM cgal AS proj
RUN...
```
Therefore I can `podman run -it a8064d84a4f7 bash`, but I need to take care during the build process to figure out which stage gets which image ID.

So it would be optimal if `42af5392` gets a hint, which stage it was in the Dockerfile, e.g. `FROM deps AS cgal`.

**Comment by flouthoc** [comment]
Ah i see your use-case now. One thing which you can use is: it prints image ID while building and also if nothing is changed in image and you rebuild it will `reprint` image ID which will be used as cache without changing anything in the final image. Does that works for you ? 

I mean feature request is valid but it sounds like a very very specific use-case ( which has a workaround ) WDYT ? Should we wait to see if more users need this before implementing this as a feature :)

```console
[1/2] STEP 1/2: FROM alpine
[1/2] STEP 2/2: RUN touch hey
--> Using cache 9d6d75a602fe7f417b96278116936aba54561fa2d937402bf01d884b0a852178
--> 9d6d75a602fe
[2/2] STEP 1/2: FROM busybox
[2/2] STEP 2/2: COPY --from=0 hey .
--> Using cache 2b2b4edb25b5d21a8187d68f3fc87a9a94738c9074231e309c9a6394dd008e23
[2/2] COMMIT test
--> 2b2b4edb25b5
Successfully tagged localhost/test:latest
2b2b4edb25b5d21a8187d68f3fc87a9a94738c9074231e309c9a6394dd008e23
```

**Comment by tobwen** [comment]
> Ah i see your use-case now. One thing which you can use is: it prints image ID while building and also if nothing is changed in image and you rebuild it will `reprint` image ID which will be used as cache without changing anything in the final image. Does that works for you ?

At the moment I just log the output of _buildah_ with it. But sure, a rebuild would be a work-around.

But wouldn't it be a totally simple, low-threshold and compatible solution to put the information anywhere in the metadata?

For example `$ podman inspect 8459cdfbd2ba`:
``` json
          "Labels": {
               "io.buildah.version": "1.31.2"
               "io.buildah.stage": "FROM kebab AS döner" <-- HERE
          },
          "Annotations": {
               "org.opencontainers.image.base.digest": "sha256:41c3f372c160576268fd269c0717871d7f9080468e312bdb66f9510ba3981b54",
               "org.opencontainers.image.base.name": "docker.io/library/postgres:15-bookworm",
               "org.opencontainers.image.revision": "8a631b939a0b4197cb6bef49b50b6c40c80ddf5b",
               "org.opencontainers.image.source": "https://github.com/docker-library/postgres.git#8a631b939a0b4197cb6bef49b50b6c40c80ddf5b:15/bookworm",
               "org.opencontainers.image.url": "https://hub.docker.com/_/postgres",
               "org.opencontainers.image.version": "15.4"
                <-- OR ANYWHERE HERE -->
          }
```
