### ISSUE TITLE
Add ability to clear cache just for one build

### ISSUE THREAD

**Issue by clarfonthey** [containers/buildah#4747]
#4490 added the `buildah prune` command which can be used to prune the entire cache of images for buildah, although this can be very slow since it clears the cache for the entire system. It would be useful to be able to run `buildah prune` specifically for the images related to a build, e.g. so that the following `buildah build` is similar to running `buildah build --no-cache`.

This would be useful for scripts that include build commands since you can just run a cache-clear command and then rerun the scripts, instead of having to duplicate the script functionality or have some way of injecting a `--no-cache` flag into the commands from the outside.

Perhaps this could be the default behaviour of the `buildah prune` command, since right now it doesn't seem to do anything for me without the `--all` flag. Alternatively, it could accept a `Containerfile` to use to find the images.

**Comment by flouthoc** [comment]
The intermediate images generated from one build can be used by other builds as well hence they are separate entity, also as of now a build does not contains any metadata about the intermediate images associated to it ( in order to build such feature we will need this data ).

IMHO I think while this is a valid feature request, at least a couple of users should comment here to classify this as a popular request. Lets wait for opinion of other build maintainers. @containers/buildah-maintainers WDYT ?

**Comment by rhatdan** [comment]
Can't you inspect the buildah cache directory and then run rm -rf $CACHEDIR?

**Comment by clarfonthey** [comment]
Indeed, why do any `buildah prune` commands exist when you can "just" perform all the logic they do manually?

**Comment by rhatdan** [comment]
No need to have an attitude, especially when you are asking others to do the work.  If you opened a PR for this, then it might get better consideration.

**Comment by clarfonthey** [comment]
I responded the way I did not because I feel entitled to this being implemented for me (I think that this kind of feature would be relatively challenging to figure out and don't expect it to be prioritised unless it has greater support than it currently has), but because I don't like the framing of "just" doing said complicated logic by hand, since this actually would require decently complicated logic to do properly.

In other words, your comment implies that this is a simple task to work around when I don't think it is. So, I responded with a particularly rude comment because yours felt rude as well, and I wanted to point that out. I doubt that was your intention, just, it's not very productive to the conversation.

Particularly, the issue is that the actual hash used for the image isn't easily correlated with the current directory, since it depends on the `Containerfile` directly. There are probably other ways to do it that I'm unaware of (and if you know, I would love to hear), but imho this would be most useful *because* the logic is difficult to figure out as an end user *and* easy to mess up (for example, deleting an overlay image for an in-use container), whereas the alternative is *only* slower, doing a full prune.

If you think this feature will realistically never be implemented even by an interested volunteer, feel free to close it, if that's standard for stale tickets. I do think it would be useful, however.

**Comment by flouthoc** [comment]
@clarfonthey I can understand sometimes these things can be a bit frustrating and having them implemented as a feature surely makes life easier, I think what dan meant is sometimes if feature is taking time to get implemented upstream till then you can use manual steps for the time being.

> If you think this feature will realistically never be implemented even by an interested volunteer, feel free to close it, if that's standard for stale tickets. I do think it would be useful, however.

This is perfectly valid feature request and by my comment here https://github.com/containers/buildah/issues/4747#issuecomment-1514310498 I meant to wait for while till more folks show interest in this. But yeah again there is no point in waiting endlessly for more people to show up if this is valid feature request.

I'll take it up and see if this can be quickly implemented in coming weeks.

Cheers :smile:

**Comment by flouthoc** [comment]
The design could be as this

* All Intermediate images gets a new internal label `buildah-builtfor: image-name`
* `buildah prune` gets a filter `--by-image` where `buildah prune` will remove intermediate image associated to an image

```buildah prune --by-image my-build1```

**Comment by clarfonthey** [comment]
This has been left open because it is a worthwhile thing to consider, even though it's not prioritised. If that's ever not the case, it should be closed. I don't think that auto-staleness-marking changes that situation.

**Comment by clarfonthey** [comment]
Previous comment still applies.

**Comment by clarfonthey** [comment]
Previous comment still applies.

**Comment by clarfonthey** [comment]
Congrats on pissing a user off enough to get them to close their own issue.
