### ISSUE TITLE
Buildah ignores STORAGE_DRIVER=overlay2 as environment variable

### ISSUE THREAD

**Issue by alvicsam** [containers/buildah#4748]
**Description**

I run buildah inside docker. When I use `--storage-driver overlay2` flag buildah works as expected. If I set `STORAGE_DRIVER=overlay2` as env variable buildah fallbacks to `overlay` and tries to use `fuse-overlayfs`

**Steps to reproduce the issue:**

Run

```
docker run --security-opt apparmor:unconfined --cap-add SYS_ADMIN -e STORAGE_DRIVER=overlay2 quay.io/buildah/stable /bin/bash -c "env; buildah info"
```

**Describe the results you received:**

```bash
HOSTNAME=6566d58d50e5
DISTTAG=f37container
PWD=/
container=oci
HOME=/root
FGC=f37
STORAGE_DRIVER=overlay2
BUILDAH_ISOLATION=chroot
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
time="2023-04-19T08:15:57Z" level=warning msg="Switching default driver from overlay2 to the equivalent overlay driver"
{
    "host": {
        "CgroupVersion": "v2",
        "Distribution": {
            "distribution": "fedora",
            "version": "37"
        },
        "MemFree": 5563019264,
        "MemTotal": 8337420288,
        "OCIRuntime": "crun",
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 8,
        "hostname": "6566d58d50e5",
        "kernel": "5.18.0-0.bpo.1-amd64",
        "os": "linux",
        "rootless": true,
        "uptime": "853h 15m 41.47s (Approximately 35.54 days)",
        "variant": ""
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay2.imagestore=/var/lib/shared",
            "overlay.mount_program=/usr/bin/fuse-overlayfs",
            "overlay.mountopt=nodev,fsync=0"
        ],
        "GraphRoot": "/var/lib/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 0
        },
        "RunRoot": "/run/containers/storage"
    }
}
```

**Describe the results you expected:**

 The same as I would run `buildah --storage-driver overlay2 info`:

```bash
{
    "host": {
        "CgroupVersion": "v2",
        "Distribution": {
            "distribution": "fedora",
            "version": "37"
        },
        "MemFree": 5560561664,
        "MemTotal": 8337420288,
        "OCIRuntime": "crun",
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 8,
        "hostname": "0b6475b771da",
        "kernel": "5.18.0-0.bpo.1-amd64",
        "os": "linux",
        "rootless": true,
        "uptime": "853h 19m 36.56s (Approximately 35.54 days)",
        "variant": ""
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [],
        "GraphRoot": "/var/lib/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "true",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 0
        },
        "RunRoot": "/run/containers/storage"
    }
}
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.29.1-1.fc37.x86_64
```

**Output of `buildah version`:**

```
Version:         1.29.1
Go Version:      go1.19.5
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.24.1
Git Commit:
Built:           Fri Feb 17 10:05:41 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```bash
$ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux alvicsam-build-vm11 5.18.0-0.bpo.1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1~bpo11+1 (2022-06-14) x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
-
```

**Comment by flouthoc** [comment]
Hi @alvicsam , `overlay` and `overlay2` are same in the context of `c/storage`.

**Comment by alvicsam** [comment]
Hi @flouthoc! Yes, but they work in a different way. `overlay ` does use `fuse-overlayfs` and `overlay2` doesn't. I see that `"GraphDriverName": "overlay"` is the same in both cases but `"GraphOptions"` are different. So I'm expecting that env variable `STORAGE_DRIVER=overlay2` works in the same way as flag `--storage-driver overlay2` and doesn't use `fuse-overlayfs`.

**Comment by rhatdan** [comment]
Most likely this is a string comparison issue somewhere in the stack, but does it really matter?

**Comment by alvicsam** [comment]
I think yes because with env variable `STORAGE_DRIVER=overlay2` buildah doesn't work as expected. 

As en example I can give my use case: I use buildah in CI and I want switch to overlay2. I need to go to each repo and add `--storage-driver overlay2` in each job that uses buildah. Instead I could set a global environment variable for all projects. 

But the main problem that I see here is that `buildah` behaves inconsistently.

**Comment by rhatdan** [comment]
Sure, but changing to STORAGE_DRIVER=overlay, everything works.  I am just saying that I don;t see this as a priority for us to fix, since you are using a storage driver that really should not be used.  If you want to dig into the code to find where the bug it, we would welcome a PR.

**Comment by alvicsam** [comment]
> you are using a storage driver that really should not be use

May I ask why? Modern kernels support rootless overlay2. Why should I use fuse-overlayfs which is usually used as a fallback?

**Comment by rhatdan** [comment]
overlay2 is just a string of characters. The kernel does not support overlay2. Docker had two implementations of the overlay storage driver, the newer one it called overlay2, In Podman we use the newer one only and just call it "overlay". We support an alias in storage.conf that supports overlay2 by substituting "overlay" for people who get confused.  In this case we must have missed one of the code paths when users are setting the environment variable, is my guess.  This has nothing to do with the kernel support for overlay or rootless overlay, which is what I think you are thinking is overlay2.

**Comment by rhatdan** [comment]
My major point is the people who actively work on Buildah, Podman and friends have hundreds of bugs to work on along with new features.  The problem you found is not likely to bubble up in importance to be fixed by one of these engineers.  So I advise you, if you want to fix this to open a PR or if you can't then just use the string "overlay" with the environment variable.

**Comment by rhatdan** [comment]
Since this is easily worked around, I am closing this issue.
