### ISSUE TITLE
`podman build` doesn't handle Windows `--volume` paths correctly

### ISSUE THREAD

**Issue by PJayB** [containers/buildah#4749]
**Description**

`podman build` doesn't handle `:` in `--volume` paths on Windows systems.

**Steps to reproduce the issue:**

1. Execute a build command with a --volume argument that points to a fully-qualified Windows path, e.g.:

```
podman build --volume="C:\Users:/home" .
```

**Describe the results you received:**

This error message appears:
```
Error: invalid host path, must be an absolute path "C"
```

**Describe the results you expected:**

The result should be the same as `podman run`, which correctly handles the same case, i.e. mounts the specified file into the container.

**Output of `rpm -q buildah` or `apt list buildah`:**

N/A

**Output of `buildah version`:**

N/A

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.2
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 08:21:09 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 07:24:13 2022
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

N/A

**Output of `uname -a`:**

N/A

**Output of `cat /etc/containers/storage.conf`:**

N/A

**Windows Version:**

```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023-‎01-‎11
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0
```

**Comment by flouthoc** [comment]
Thanks for reporting , this needs to be fixed on buildah side.

**Comment by leadoflife** [comment]
Bump as it is an active issue awaiting resolution

**Comment by leadoflife** [comment]
I have confirmed that `podman run --volume ...` does indeed work and `podman build --volume ...` does not. However, I have discovered two workarounds:

- Use `COPY ...` with performance implications
- Run `podman build` inside of a Podman container and use `podman run --volume ...` to mount the host volume to the Podman container and then `podman build --volume ...` to mount the volume inside of the build process. This has a bonus side effect of containerizing the podman version used by the build as well as the build command itself. However, it also has added complexity and potential constraints.

**Comment by rhatdan** [comment]
@flouthoc Ping

**Comment by Incrediblestorm** [comment]
Is this not going to become a much larger issue with image mode/bootc container builds. Because you are building an entire OS there are much larger amounts of data being built into the container. 
As such, I am considering building a base image with minor/major versions, and then building patch releases by using something like rsync. This should reduce blob downloads for upgrade. 

Podman Desktop has great integrations for building isos/vmdks, so I'm trying to use it more.

**Comment by rhatdan** [comment]
@l0rd Could you look at this?

**Comment by michaelcress** [comment]
I solved it by using "/mnt/c/" instead of "C:\".

It also might be worth trying %userprofile% instead of "C:\Users\<user id>"
