### ISSUE TITLE
4757 broke podman-remote: failed to parse query parameter 'platform'

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4763]
PR #4757 broke podman-remote:
```console
$ echo "FROM sfsdf" | bin/podman-remote build  -
Error: failed to parse query parameter 'platform': "/": invalid platform syntax for --platform="": "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```
No `podman-remote build` commands work at all any more. [log](https://api.cirrus-ci.com/v1/artifact/task/6515049724903424/html/bud-remote-fedora-37-root-host-boltdb.log.html)

I don't know if this needs to be fixed on the podman side or buildah side. Please reassign issue as needed.

**Comment by flouthoc** [comment]
Uh-oh let me fix it for `podman-remote`, thanks for reporting @edsantiago

**Comment by flouthoc** [comment]
This actually needs to be also fixed at `podman-remote` end , it sends `/` on no `--platform` argument.
