### ISSUE TITLE
inline platform broken on podman-remote

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4768]
Maybe #4757, maybe #4765, maybe something else:
```console
$ echo "FROM --platform=freebsd/arm64/v8 scratch" | bin/podman-remote build -t foo -
STEP 1/1: FROM scratch
COMMIT foo
--> 1a05e1b02e01
Successfully tagged localhost/foo:latest
1a05e1b02e01a2b74e780a184958ee38d882fe17260daea7cc3c156ef3c04e84
$ bin/podman image inspect foo|grep -i arch
          "Architecture": "amd64",    <<<<<<<<<<< should be arm64
```
Works fine (as expected) with podman non-remote. [log](https://api.cirrus-ci.com/v1/artifact/task/5537910707978240/html/bud-remote-fedora-38-root-host-boltdb.log.html#t--00025).

**Comment by flouthoc** [comment]
@edsantiago I think following PR should fix it,  reason is `podman-remote` passes invalid value `/` and expects an invalid response for it https://github.com/containers/podman/pull/18411

**Comment by edsantiago** [comment]
Fix confirme, podman-remote [root](https://api.cirrus-ci.com/v1/artifact/task/6562364024160256/html/bud-remote-fedora-38-root-host-boltdb.log.html) and [rootless](https://api.cirrus-ci.com/v1/artifact/task/5858676582383616/html/bud-remote-fedora-38-rootless-host-boltdb.log.html). Thank you!
