### ISSUE TITLE
podman-remote build --pull-always: outputs unwanted "Resolved ... as an alias"

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#4769]
Found in latest buildah treadmill, [podman-remote only](https://api.cirrus-ci.com/v1/artifact/task/5537910707978240/html/bud-remote-fedora-38-root-host-boltdb.log.html#t--00317):
```console
$ podman pull alpine    ! to make sure we have the image locally
$ echo "FROM alpine" | bin/podman-remote build --pull-always -t foo -
STEP 1/1: FROM alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)     <<<<< BAD
Trying to pull docker.io/library/alpine:latest...
```
The "Resolved alpine" message is now always output under podman-remote (not under podman). This breaks the "bud with --pull-always" test.

No idea if this is a buildah bug or podman bug.

**Comment by rhatdan** [comment]
I vendored in buildah and tried it out but am not seeing what you are seeing?
```
-       github.com/containers/buildah v1.30.0
+       github.com/containers/buildah v1.30.1-0.20230501124043-3908816d5310
```
I see nothing on the server side and the following on the client side.
```
echo "FROM alpine" | bin/podman-remote build --pull-always -t foo -
STEP 1/1: FROM alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob sha256:f56be85fc22e46face30e2c3de3f7fe7c15f8fd7c4e5add29d7f64b87abdaa09
Copying config sha256:9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e
Writing manifest to image destination
Storing signatures
COMMIT foo
--> 9ed4aefc74f6
Successfully tagged localhost/foo:latest
Successfully tagged docker.io/library/alpine:latest
9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e
```

**Comment by rhatdan** [comment]
```
+       if platform == "local" || platform == "" || platform == "/" {
+               return Platform(DefaultPlatform())
+       }
```
It is coming from this fix, but I am not sure that that text is wrong to show.

**Comment by edsantiago** [comment]
I don't have a strong opinion about it, but it does bother me that podman-remote != podman

**Comment by flouthoc** [comment]
> ```
> +       if platform == "local" || platform == "" || platform == "/" {
> +               return Platform(DefaultPlatform())
> +       }
> ```
> 
> It is coming from this fix, but I am not sure that that text is wrong to show.

@rhatdan @edsantiago I don't think its coming from this fix, this also happens with `podman` upstream without pulling in the latest buildah. @edsantiago Could you confirm this please if you see this is upstream as well I'm on `6e34fdb4b555dc83785f39ebc2b4862517835536` commit of podman.

**Comment by flouthoc** [comment]
Okay nvm I maybe wrong maybe this PR fixes the issue: https://github.com/containers/podman/pull/18411

**Comment by edsantiago** [comment]
Fix confirmed, podman-remote [root](https://api.cirrus-ci.com/v1/artifact/task/6562364024160256/html/bud-remote-fedora-38-root-host-boltdb.log.html) and [rootless](https://api.cirrus-ci.com/v1/artifact/task/5858676582383616/html/bud-remote-fedora-38-rootless-host-boltdb.log.html). Thank you!
