### ISSUE TITLE
[question] To use buildah as a package in go, is the dependency requires only on develop computer or requires on user's computer too?

### ISSUE THREAD

**Issue by dayeguilaiye** [containers/buildah#4778]
I found [04-include-in-your-build-tool.md](https://github.com/containers/buildah/blob/main/docs/tutorials/04-include-in-your-build-tool.md), which is exactly what I need. but I found that:

> Bootstrap the project and install the dependencies

I have to know that are those dependencies required only on my own development computer or also required on user's computer?

**Comment by rhatdan** [comment]
There only required to build/compile the application.  They should not be needed by users of your application.
