### ISSUE TITLE
Why does buildah commit replace replace bin/ with usr/bin/, losing contents of bin/

### ISSUE THREAD

**Issue by stevecj** [containers/buildah#4784]
I'm trying to use `buildah from scratch` to create a new rhel8 container image. I found that the resulting container had no `dnf` or `yum`, but I'm actually trying to create a VM-like container for use in WSL, so I need those.

After digging a bit, I found that, although before committing, there is a bin/ directory containing `dnf`, after running
```
buildah commit working-container localhost/myrhel8:latest
```
the bin/ directory had been removed and replaced by a symlink to usr/bin/. Additionally, `lib -> usr/lib`, `lib64 -> usr/lib64`, and `sbin -> usr/sbin`.

1. Is this what is supposed to happen, and why?
2. What should I be doing to get what I am looking for?
3. Is this something that can be clarified in the documentation?

**Comment by stevecj** [comment]
I might have figured this out?

I went through the process again, listing the target contents along the way, and I see that the only reason the bin/ directory existed there at all prior to commit is because they were added during a package installation. That doesn't completely explain why `buildah` creates those symlinks, but at least I know that if I create the symlinks myself before installing any packages, then the files will be installed into the locations that remain present in the final image.

**Comment by flouthoc** [comment]
@stevecj I am not entirely sure if buildah itself is doing it, could you please share a minimal reproducer ?

**Comment by stevecj** [comment]
If it has nothing to do with Buildah itself, then it must be in something that rhel8 does that Buildah invokes during commit. Right? Does Buildah run anything during the commit that we don't explicitly specify?

**Comment by rhatdan** [comment]
Buildah is using golang tar on the file system on COW file systems.

**Comment by rhatdan** [comment]
Since we have not heard any other feedback, closing.
