### ISSUE TITLE
labels are still being applied to intermediate images

### ISSUE THREAD

**Issue by akanix42** [containers/buildah#4804]
**Description**

https://github.com/containers/buildah/pull/4673 applies a fix to only add labels (as provided by `--label`) to the final image; however, it is currently not working, so the label is incorrectly added to all images in the chain. After looking over the code, I _think_ (I'm not set up to develop buildah so I haven't tested this) that this block https://github.com/containers/buildah/blob/main/imagebuildah/executor.go#L474-L501 needs to be nested in an `if` like the one right above it so that it only applies to the final stage: https://github.com/containers/buildah/blob/main/imagebuildah/executor.go#L471-L473

The test as written doesn't actually test the issue - the hash of the COPY instruction doesn't change regardless of the label being added, so the cache isn't invalidated, but the label is still being added. The issue quickly becomes apparent when you inherit from the image rather than referencing it for a COPY (for example, run the test with [Dockerfile.reused](https://github.com/containers/buildah/blob/main/tests/bud/multi-stage-builds/Dockerfile.reused) instead).

**Steps to reproduce the issue:**
1. Create a simple Dockerfile
```dockerfile
FROM alpine:3.18.0 as stage1
RUN echo stage1!

FROM stage1 as stage2
RUN echo stage2!
```
2. Run buildah with a sample label. The label is applied at the end of both stages.
```
buildah build --layers --label 'foo=abc' -t podman-issue .
[1/2] STEP 1/3: FROM alpine:3.18.0 AS stage1
[1/2] STEP 2/3: RUN echo stage1!
stage1!
--> 333078e6b464
[1/2] STEP 3/3: LABEL "foo"="abc"
--> 764249bb2f05
[2/2] STEP 1/3: FROM 764249bb2f05051e10095df75c06f33149802275aaa55b838c12ff40393a2944 AS stage2
[2/2] STEP 2/3: RUN echo stage2!
stage2!
--> f7b373419016
[2/2] STEP 3/3: LABEL "foo"="abc"
[2/2] COMMIT podman-issue
--> 584682d27f96
Successfully tagged localhost/podman-issue:latest
584682d27f96c4335ad72322f65b0378b6dc9e7e3bb673fdfafcfb78b96f01ea
```
3.  Run the same buildah command again. The layers are cached.
```
buildah build --layers --label 'foo=abc' -t podman-issue .
[1/2] STEP 1/3: FROM alpine:3.18.0 AS stage1
[1/2] STEP 2/3: RUN echo stage1!
--> Using cache 333078e6b4643f318e90753bf582bfce8f974fa678a47f1aebe4d2067ce84508
--> 333078e6b464
[1/2] STEP 3/3: LABEL "foo"="abc"
--> Using cache 764249bb2f05051e10095df75c06f33149802275aaa55b838c12ff40393a2944
--> 764249bb2f05
[2/2] STEP 1/3: FROM 764249bb2f05051e10095df75c06f33149802275aaa55b838c12ff40393a2944 AS stage2
[2/2] STEP 2/3: RUN echo stage2!
--> Using cache f7b3734190160e90d222f643e8f6766a663bbaeac9c1ca423c791dfe475d7436
--> f7b373419016
[2/2] STEP 3/3: LABEL "foo"="abc"
--> Using cache 584682d27f96c4335ad72322f65b0378b6dc9e7e3bb673fdfafcfb78b96f01ea
[2/2] COMMIT podman-issue
--> 584682d27f96
Successfully tagged localhost/podman-issue:latest
584682d27f96c4335ad72322f65b0378b6dc9e7e3bb673fdfafcfb78b96f01ea
```
4. Run buildah with a different value for the label. The cache is broken due to the label being incorrectly added to stage1.
```
buildah build --layers --label 'foo=123' -t podman-issue .
[1/2] STEP 1/3: FROM alpine:3.18.0 AS stage1
[1/2] STEP 2/3: RUN echo stage1!
--> Using cache 333078e6b4643f318e90753bf582bfce8f974fa678a47f1aebe4d2067ce84508
--> 333078e6b464
[1/2] STEP 3/3: LABEL "foo"="123"
--> b5b06c0c78a6
[2/2] STEP 1/3: FROM b5b06c0c78a69aa9501931a24a076910ddef1580c5b2da9d6315b7379f8b4015 AS stage2
[2/2] STEP 2/3: RUN echo stage2!
stage2!
--> 0fa567360979
[2/2] STEP 3/3: LABEL "foo"="123"
[2/2] COMMIT podman-issue
--> 73000248e2dd
Successfully tagged localhost/podman-issue:latest
73000248e2dd5b31af7d37a8913f9cdaea3b66731179c20432dbb4bee480b12f
```

**Describe the results you received:**

The label is added to each image, not just the final one.

**Describe the results you expected:**

As with docker, the label should only be added to the final image, not each intermediate one.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.30.0-1.fc38.aarch64
```

**Output of `buildah version`:**

```
Version:         1.30.0
Go Version:      go1.20.2
Image Spec:      1.0.2-dev
Runtime Spec:    1.1.0-rc.1
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.25.0
Git Commit:      
Built:           Mon Apr 10 02:25:32 2023
OS/Arch:         linux/arm64
BuildPlatform:   linux/arm64/v8
```

**Output of `cat /etc/*release`:**

```
Fedora release 38 (Thirty Eight)
NAME="Fedora Linux"
VERSION="38.20230514.2.0 (CoreOS)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora CoreOS 38.20230514.2.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='38.20230514.2.0'
Fedora release 38 (Thirty Eight)
Fedora release 38 (Thirty Eight)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 6.2.15-300.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Thu May 11 16:54:06 UTC 2023 aarch64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by flouthoc** [comment]
@akanix42 Thanks for reporting, last time we modified buildah but missed setting it only for last stage, following PR should close this and newly added test should make sure we don't hit it again. https://github.com/containers/buildah/pull/4817
