### ISSUE TITLE
build manual page uses dead URL

### ISSUE THREAD

**Issue by stuartayeates** [containers/buildah#4814]
https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md links to https://github.com/scollier/purpletest as an example git repository to build from directly.  This URL is 404. It needs to be replaced with a URL (anu URL) to a git that may be built from directly.

1 Go to https://docs.podman.io/en/latest/markdown/podman-build.1.html 
2 click on the link in the example "podman build https://github.com/scollier/purpletest"

**Describe the results you received:**

404 not found

**Describe the results you expected:**

A working git repository that I could build a container from.

**Comment by flouthoc** [comment]
@containers/buildah-maintainers @containers/podman-maintainers Should this be redirected to some `hello-world` project in `containers` org ?

**Comment by rhatdan** [comment]
SGTM

**Comment by flouthoc** [comment]
PR: https://github.com/containers/buildah/pull/5020 closes this.
