### ISSUE TITLE
rootless integration tests run with vfs not $STORAGE_DRIVER

### ISSUE THREAD

**Issue by kolyshkin** [containers/buildah#4838]
I have noticed that in cirrus-ci a task named "Integration rootless fedora-37 w/ overlay" contains the following output:

> [+3284s] ok 631 overlay specific level # skip skipping overlay test because $STORAGE_DRIVER = vfs
> [+3285s] ok 632 overlay source permissions and owners # skip skipping overlay test because $STORAGE_DRIVER = vfs
> [+3285s] ok 633 overlay path contains colon # skip skipping overlay test because $STORAGE_DRIVER = vfs

Which does not looks correct to me

**Comment by kolyshkin** [comment]
See e.g. https://cirrus-ci.com/task/6569942594617344?logs=integration_test#L1362 (under `integration_test`).

**Comment by kolyshkin** [comment]
OK, because the test is re-executed via `ssh $ROOTLESS_USER@localhost`, and ssh does not pass all the environment by default, a bunch of configuration is lost during that step.

Looks like this was added in #3804

**Comment by kolyshkin** [comment]
@flouthoc @cevich PTAL


There are multiple ways to fix this
 - do not use ssh, use `sudo -E` instead;
 - write/source a file with all environment variables that needs to be passed;
 - add a bunch of `export VAR=$VALUE` to ssh invocation, before test.sh (e.g. `export STORAGE_DRIVER=$STORAGE_DRIVER; $GOSRC/$SCRIPT_BASE/test.sh`;
 - configure ssh AND sshd to send and accept extra env vars (`SendEnv` for ssh, `AcceptEnv` for sshd).

**Comment by cevich** [comment]
Thanks @kolyshkin for noticing. I know exactly what's causing this and have a somewhat-related TODO kicking around to take care of it.

**Comment by kolyshkin** [comment]
> I know exactly what's causing this

Do you mean something else than ssh? I'm curious.

**Comment by cevich** [comment]
Nope, we still need to use ssh.  The issue has to do with very old and ugly env. var. processing code.  I'm planning to replace it with something similar to [what we do for podman CI](https://github.com/containers/podman/blob/aee7a3c16aee82d11689db91e42f82e52a690d98/contrib/cirrus/setup_environment.sh#L48-L58) (it fixed the same problem over there).

**Comment by cevich** [comment]
Oh gosh, forgot about this.  Moving back on my TODO list.

**Comment by rhatdan** [comment]
@cevich reping

**Comment by cevich** [comment]
Thanks, I've still got https://github.com/containers/buildah/pull/4872 on my list.  Though it's near the bottom of my stack.  Is there reason I should bump it more toward the top?
