### ISSUE TITLE
Hostname resolution errors running buildah on RedHat vs Ubuntu

### ISSUE THREAD

**Issue by mikepurvis** [containers/buildah#4860]
**Description**

I'm using Buildah in Kubernetes (`privileged: true`) to create some basic Ubuntu container images. Unfortunately, the packages involved are internal, so I don't have a good public reproduction for this (if there's value I can create one!), but the long and short of it is that a package's preinst script is calling `hostname -f`, and that is failing my build _only for the Fedora-based Buildah container on quay.io_:

```
Preparing to unpack .../37-cpr-nginx-web-cfg_0.6.10_all.deb ...
hostname: Temporary failure in name resolution
dpkg: error processing archive /tmp/apt-dpkg-install-pyVkJM/37-cpr-nginx-web-cfg_0.6.10_all.deb (--unpack):
 new cpr-nginx-web-cfg package pre-installation script subprocess returned error exit status 1
```

Where the preinst is basically:
```
set -e
HOST=`hostname -f`
# generate a self-signed cert with the hostname
```

I know those packages are badly behaved and shouldn't be doing that (it's meaningless when the container hostname is ephemeral anyway), and that's the real source of the issue here. But the odd thing about this is that when I switched back from doing this build in `quay.io/buildah/stable:v1.30` to doing it in an Ubuntu Focal container and installing `buildah` (1.22.3-2) from the Kubic apt repository, the problem went away entirely.

It surprised me that buildah's host container could be having this kind of effect on the build, and I wanted to ask here in case it's something easy/obvious, or if there would be value in trying to put together a MWE to isolate whatever this issue is.

**Output of `uname -a`:**

```
13:25:08  + uname -a
13:25:08  Linux container-lorem-ipsum-28-djs2s--m7834 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

The default that came with the container, or:

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by flouthoc** [comment]
Hi @mikepurvis , does problem persists in recent versions as well ? Could you please try `quay.io/buildah/upstream`

**Comment by rhatdan** [comment]
Since we never heard back, closing
