### ISSUE TITLE
Copier walks full build context directory tree even if large subtrees are ignored

### ISSUE THREAD

**Issue by sanmai-NL** [containers/buildah#4873]
**Description**

**Steps to reproduce the issue:**
1. Write a (dummy) Containerfile and a `.containerignore` that excludes directory subtrees of >1 height. (This is the common case.)

    ```gitignore
    *
    .venv/
    .git/
    !/src/
    ```

3. Run `podman build --log-level debug buildx build`

**Describe the results you received:**

```ansi
ESC[37mDEBUESC[0m[0000] DoRequest Method: POST URI: http://d/v4.5.1/libpod/build 
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .DS_Store            
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .editorconfig        
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .env                 
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git                 
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/COMMIT_EDITMSG  
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/FETCH_HEAD      
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/HEAD            
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/ORIG_HEAD       
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/config          
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/description     
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/hooks           
ESC[37mDEBUESC[0m[0000] Skipping excluded path: .git/hooks/applypatch-msg.sample 
```

**Describe the results you expected:**

`.git/hooks/` shouldn't be traversed at all, since its parent `.git/` was excluded.

This quality defect has the following impacts:

- Log noise and excessive growth given common large ignored subtrees, such as `.venv/`, `node_modules/`, `build/` etc.
- Performance including scalability: a good number of unnecessary syscalls to retrieve filesystem node metadata about irrelevant nodes.

**Output of `podman version` if reporting a `podman build` issue:**

```console
$ podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Git Commit:   9eef30051c83f62816a1772a743e5f1271b196d7
Built:        Fri May 26 17:10:12 2023
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 19:58:48 2023
OS/Arch:      linux/amd64
```

**Comment by flouthoc** [comment]
Hi @sanmai-NL ,

I am not sure but I think this matches with `buildkit`,  since `.somedir/` means excluding only the the level == 1 it will still try to add if there are any subdirectory below it, for example `.somedir/somesubdir` will still be added. Since matching is here done using `Go's` filepath.Match rules.

**Comment by sanmai-NL** [comment]
@flouthoc The ignore file syntax aside, the semantics of the example ignore file are that subtrees should be ignored (due to the asterisk glob). The logging indicates that large subtrees are indeed ignored, but they are walked.

**Comment by sanmai-NL** [comment]
@flouthoc I'm not a Go programmer. Am I correct that the site of improvement is around here: https://github.com/containers/buildah/blob/8c6b787241278930e09875935ec69d867fb0a64c/copier/copier.go#L1009?
