### ISSUE TITLE
missing dir to build source 

### ISSUE THREAD

**Issue by gabrielfsousa** [containers/buildah#4919]
vendor/github.com/containers/image/v5/openshift/openshift-copies.go:11:2: cannot find package "." in:
       ./buildah/fedora/buildah-1.31.0/vendor/net/netip

**Comment by flouthoc** [comment]
@gabrielfsousa Could you please tell on which environment and how are you building this ? Please share your `go` version as well.

**Comment by flouthoc** [comment]
Closing this since there is not enough info. Please feel free to re-open.
