### ISSUE TITLE
unchanged files duplicated in layers using buildah in github actions runner 

### ISSUE THREAD

**Issue by srd424** [containers/buildah#4942]
**Description**

[This is mostly here as a placeholder for other people who are stuck and searching for a solution, so feel free to instantly close it - I appreciate this report involves fairly old versions of multiple components]

I moved a working buildah-based image build process to Github Actions, but the built image sizes produced when run on GHA were substantially bigger than those on my dev machine. Closer inspection showed that files from a base image that hadn't been touched were being duplicated in the next layer 'up.'

* Switching from the Ubuntu 20.04 to the 22.04 based runner didn't help.
* Forcing the use of fuse-overlayfs (not detected and used by default even though it's installed by default in the runner) seemed to result in the build outright failing (possibly #3655 or similar)
* Switching back to overlayfs and trying to force metacopy on (desperation, trying random things to get a different code path) caused the build to fail in a different way (and metacopy didn't seem to get detected either.)

The solution in the end seemed to be to pull a newer fuse-overlayfs into the runner (it has 1.7.1 installed by default) and force its use. My best guess is containers/fuse-overlayfs/pull/329 did the trick?

**Steps to reproduce the issue:**
The offending Dockerfile:
```
FROM bnpi-build-common AS build
[..]
ADD --chmod=0644 build /build-scripts
RUN bash -x /build-scripts/build-server.sh
RUN du -sch /home/pi/BirdNET-Pi/birdnet

FROM bnpi-common AS final
[..]
COPY --from=build /home/pi/BirdNET-Pi/birdnet /home/pi/BirdNET-Pi/birdnet
ADD --chmod=0644 build /build-scripts
RUN bash -x /build-scripts/final.sh
RUN rm -f /home/pi/BirdNET-Pi/scripts/gotty
```
**Describe the results you received:**

`/home/pi/BirdNET-Pi/birdnet` here is a python venv which already exists in bnpi-common/bnpi-build-common with a few packages installed. `build-server.sh` adds some more, but even packages in the venv which haven't been touched end up duplicated into the final layer of the final image when using kernel overlayfs in the GH runner.

**Describe the results you expected:**
For the final layer only to contain files that had been added or changed.

**Output of `buildah version`:**

```
buildah version 1.23.1 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```

**Comment by flouthoc** [comment]
Thanks @srd424 for creating this issue, I am sure this will help other users. Closing this issue.
