### ISSUE TITLE
Fedora 38 package for 1.31 seems to have regressed wrt #4063

### ISSUE THREAD

**Issue by mhjacks** [containers/buildah#4944]
**Description**

FreeIPA-provided subuid/subgid seem not to be recognized by buildah-1.31.0-1.fc38.x86_64

**Steps to reproduce the issue:**
1. Join a  machine to FreeIPA domain that provides subuid/subgid
2. Configure NSS to use sss-provided subids
3. Observe warnings

**Describe the results you received:**

```
++ buildah from registry.access.redhat.com/ubi9/openjdk-11-runtime:latest
WARN[0000] Reading allowed ID mappings: reading subuid mappings for user "mjackson" and subgid mappings for group "mjackson": no subuid ranges found for user "mjackson" in /etc/subuid 
WARN[0000] Found no UID ranges set aside for user "mjackson" in /etc/subuid. 
WARN[0000] Found no GID ranges set aside for user "mjackson" in /etc/subgid. 
+ ctr=openjdk-11-runtime-working-container-4
+ buildah copy openjdk-11-runtime-working-container-4 run.sh /home/jboss/run.sh
WARN[0000] Reading allowed ID mappings: reading subuid mappings for user "mjackson" and subgid mappings for group "mjackson": no subuid ranges found for user "mjackson" in /etc/subuid 
WARN[0000] Found no UID ranges set aside for user "mjackson" in /etc/subuid. 
WARN[0000] Found no GID ranges set aside for user "mjackson" in /etc/subgid. 
```

Yet the subids are present:

```
% getsubids mjackson                    
0: mjackson 2147483648 65536

% getsubids -g mjackson
0: mjackson 2147483648 65536

```

Meanwhile, a locally compiled buildah against commit 7201967 does not experience this issue.
Also, `podman build` can correctly utilize the ipa-provided subids.

**Describe the results you expected:**

The WARN lines should not be present. Buildah should be able to use the subuid/subgid that IPA provides

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
buildah-1.31.0-1.fc38.x86_64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 12:58:48 2023
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 38 (Thirty Eight)
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 38 (Thirty Eight)
Fedora release 38 (Thirty Eight)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
Linux elrond.imladris.lan 6.4.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jul 24 20:51:12 UTC 2023 x86_64 GNU/Linux
```

**Comment by mhjacks** [comment]
Seems to relate to Issue #4063

**Comment by flouthoc** [comment]
Hi @mhjacks ,

> Meanwhile, a locally compiled buildah against commit 7201967

Could paste the link to commit or full commit ID i'm unable to find such commit in buildah repo.

Tagging @giuseppe since he found a fix for #4063 he might have more idea on this one.

**Comment by mhjacks** [comment]
The one I built locally shows the following version info:

```
$ ./buildah version
Version:         1.32.0-dev
Go Version:      go1.20.6
Image Spec:      1.1.0-rc.4
Runtime Spec:    1.1.0
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.26.1
Git Commit:      d9248be1a1c599dd282edc436761685b8077252a
Built:           Sat Jul 29 07:04:57 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

I'm guessing that the script to include the subid flag might not be working right - I'll check the koji build logs and see if that holds up or not.

**Comment by mhjacks** [comment]
Looking at the koji build logs (https://kojipkgs.fedoraproject.org//packages/buildah/1.31.0/1.fc38/data/logs/x86_64/build.log):

I see this:

```
+ go build -buildmode pie -compiler gc '-tags=rpm_crashtraceback seccomp exclude_graphdriver_devicemapper $(hack/systemd_tag.sh) $hack/libsubid_tag.sh)' -ldflags '-X main.buildInfo=1688562635 -X main.cniVersion=  -B 0xc31a50ff5e0be68f114022507ac1031d2f748a41 -compressdwarf=false -linkmode=external -extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  '\''' -a -v -x -o bin/imgtype ./tests/imgtype
```

The missing paren on the subid check hack/subid_tag.sh check concerns me. I'm doing a local mockbuild to see if there's weight to that or not.

**Comment by mhjacks** [comment]
When I build a -2 rpm after adding that paren to the specfile locally I got the same result (the subid warnings, I mean), so adding the paren is not the fix. I'm not an expert on go build systems though so I could be on entirely the wrong path.

**Comment by giuseppe** [comment]
@lsm5 could we miss the build dependency on `shadow-utils-subid-devel` in the rpm?

**Comment by mhjacks** [comment]
Looks like the new version has the right BR (from a local mockbuild):

```
% rpm -qpR  buildah-1.31.2-2.fc38.src.rpm
btrfs-progs-devel
device-mapper-devel
git-core
glib2-devel
glibc-static
go-rpm-macros
golang >= 1.16.6
gpgme-devel
libassuan-devel
libseccomp-static
make
ostree-devel
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
shadow-utils-subid-devel
```

**Comment by lsm5** [comment]
fixes pushed to fedora: https://bodhi.fedoraproject.org/updates/?packages=buildah . Also see #4971

**Comment by mhjacks** [comment]
I see the fixes pushed, and I'm trying the new build from koji. I agree that the extra paren should fix the problem, but with the new RPM, I still see the problematic behavior:
```
$ rpm -qi buildah
Name        : buildah
Version     : 1.31.2
Release     : 2.fc38
Architecture: x86_64
Install Date: Fri 11 Aug 2023 10:39:21 AM CDT
Group       : Unspecified
Size        : 29524380
License     : Apache-2.0 and BSD-2-Clause and BSD-3-Clause and ISC and MIT and MPL-2.0
Signature   : (none)
Source RPM  : buildah-1.31.2-2.fc38.src.rpm
Build Date  : Fri 11 Aug 2023 09:12:22 AM CDT
Build Host  : buildvm-x86-07.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://buildah.io
Bug URL     : https://bugz.fedoraproject.org/buildah
Summary     : A command line tool used for creating OCI Images
Description :
The buildah package provides a command line tool which can be used to
* create a working container from scratch
or
* create a working container from an image as a starting point
* mount/umount a working container's root file system for manipulation
* save container's root file system layer to create a new image
* delete a working container or an image
```

```
++ buildah from registry.access.redhat.com/ubi9/openjdk-11-runtime:latest
WARN[0000] Reading allowed ID mappings: reading subuid mappings for user "mjackson" and subgid mappings for group "mjackson": no subuid ranges found for user "mjackson" in /etc/subuid 
WARN[0000] Found no UID ranges set aside for user "mjackson" in /etc/subuid. 
WARN[0000] Found no GID ranges set aside for user "mjackson" in /etc/subgid.
```

I wonder if this is relevant? https://github.com/shadow-maint/shadow/issues/465

**Comment by lsm5** [comment]
either that or it might be the single quotes v/s double quotes. Podman package has double quotes, but buildah used single quotes. And IIRC, the buildlogs should actually say `libsubid` instead of `$(hack/libsubid_tag.sh)`. I'll do a new build and verify.

**Comment by lsm5** [comment]
scratch build with double quotes correctly shows `libsubid` instead of `$(hack/libsubid_tag.sh)` https://kojipkgs.fedoraproject.org//work/tasks/1102/104691102/build.log . I'll do new builds with that change and also update the PR.

**Comment by lsm5** [comment]
@mhjacks please try with https://bodhi.fedoraproject.org/updates/FEDORA-2023-ccefa32a9b

**Comment by mhjacks** [comment]
That worked perfectly. Thanks! I'll add karma to the update
