### ISSUE TITLE
Support for ADD <git ref> in Containerfile

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#4974]
It seems Dockerfile supports adding a git repo files via:

```
ADD [--keep-git-dir=<boolean>] <git ref> <dir>
```

https://docs.docker.com/engine/reference/builder/#adding-a-git-repository-add-git-ref-dir

Do we support that? Can we support that?

**Comment by flouthoc** [comment]
@dustymabe Thanks for creating the issue.

> Do we support that?

Afaik No, buildah supports adding contents from remote URL but it does not treats `git` or `git ref` as a special case. @nalind Could you confirm.

> Can we support that ?

Sure this can be implemented.

**Comment by rhatdan** [comment]
If docker supports it, so should we.

**Comment by danishprakash** [comment]
Mind If I take a look at this?

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
@danishprakash any progress?

**Comment by danishprakash** [comment]
Not yet, I'll take a look at it end of next week.

**Comment by jfroy** [comment]
I might take a stab at this if @danishprakash has more important stuff to do.

**Comment by rhatdan** [comment]
After 30 days it is up for grabs. go for it.

**Comment by douglascamata** [comment]
Would love to see this feature make it to buildah and eventually podman. Docker's been supporting it since a while and it's not under any sort of experimental flag.

**Comment by douglascamata** [comment]
In the mean time, do any of you have a suggested workaround that's not going to mess up image layer caching  (like `git clone`) and stays within the Dockerfile?

**Comment by rhatdan** [comment]
@jfroy did  you ever get a chance to work on it?

**Comment by jfroy** [comment]
Not yet, haven't had the time.

**Comment by rhatdan** [comment]
I think most of the code is in something like:

 path, subdir, err := define.TempDirForURL(tmpdir.GetTempDir(), internal.BuildahExternalArtifactsDir, src)

**Comment by danishprakash** [comment]
I can start looking at it now, is this still open?

**Comment by jfroy** [comment]
> I can start looking at it now, is this still open?

Yep, I haven't started! Take it.
