### ISSUE TITLE
Missing information in buildah-build.1.md: More info on JSON and hook injection....

### ISSUE THREAD

**Issue by PeterWhittaker** [containers/buildah#4987]
**Description**

The `--hooks-dir path` section of `man buildah-build` reads as follows:

>  Each *.json file in the path  configures  a  hook  for  buildah build  containers.  For more details on the syntax of the JSON files and the semantics of hook  injection.  Buildah  currently support  both  the  1.0.0  and 0.1.0 hook schemas, although the 0.1.0 schema is deprecated.

It looks like text is missing after `For more details on the syntax of the JSON files and the semantics of hook  injection`.

**Steps to reproduce the issue:**
1. `man buildah-build`
2. Head to `--hooks-dir`
3. Attempt to interpret the paragraph as written

**Describe the results you received:**

Information about hook injection is missing.

**Describe the results you expected:**

A reference to additional information about hook injection.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.27.3-1.el9_1.x86_64
```

**Output of `buildah version`:**

```
Version:         1.27.3
Go Version:      go1.18.4
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.22.1
Git Commit:      
Built:           Mon Jan 23 10:38:35 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
AlmaLinux release 9.1 (Lime Lynx)
NAME="AlmaLinux"
VERSION="9.1 (Lime Lynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.1 (Lime Lynx)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
AlmaLinux release 9.1 (Lime Lynx)
AlmaLinux release 9.1 (Lime Lynx)

```

**Output of `uname -a`:**

```
Linux lapa.sphyrna.ca 5.14.0-162.23.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Apr 11 10:43:28 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
pull_options = {enable_partial_images = "false", use_hard_links = "false", ostree_repos=""}
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

**Comment by flouthoc** [comment]
Thans PR https://github.com/containers/buildah/pull/5004 should close this.
