### ISSUE TITLE
buildah images were deleted in quay.io

### ISSUE THREAD

**Issue by alvicsam** [containers/buildah#5009]
Not sure that this is the right place to create an issue but I don't know where else I can find information. 
About 40 minutes ago all buildah images were removed from quay.io: https://quay.io/repository/buildah/stable?tab=history

**Comment by romsnl** [comment]
Most likely related to the security notice present on the information page

**Comment by alvicsam** [comment]
ah, thx

**Comment by TomSweeneyRedHat** [comment]
For updates and status, we've opened a discussion in Podman's GitHub.  https://github.com/containers/podman/discussions/19796
