### ISSUE TITLE
Upgrading buildah from 1.28 to 1.30.0 breaks buildah pull

### ISSUE THREAD

**Issue by blevz** [containers/buildah#5015]
**Description**

When upgrading buildah from version 1.28.0 to 1.30.0 for our kubernetes based build workers (running as root in the container on a debian based image) pulls are failing with the line 
`Error: mkdir /run/containers/networks: read-only file system`
That folder does not exist in our image

Prior to the upgrade buildah pull was working fine

**Describe the results you expected:**

**Output of `buildah info -d`**
```
{
    "debug": {
        "buildah version": "1.30.0",
        "compiler": "gc",
        "git commit": "",
        "go version": "go1.20.7"
    },
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "debian",
            "version": "11"
        },
        "MemFree": 153209995264,
        "MemTotal": 270473363456,
        "OCIRuntime": "crun",
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 4,
        "hostname": "<the pod hostname>",
        "kernel": "5.15.107+",
        "os": "linux",
        "rootless": false,
        "uptime": "7h 14m 15.59s (Approximately 0.29 days)",
        "variant": ""
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "overlay",
        "GraphOptions": null,
        "GraphRoot": "/var/lib/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "overlayfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 0
        },
        "RunRoot": "/data/scratch/local"
    }
}```


**Output of `apt list buildah`:**

```
buildah/bullseye 1.19.6+dfsg1-1+b6 amd64
buildah/bullseye 1.19.6+dfsg1-1+b6 i386
```

**Output of `buildah version`:**

```
Version:         1.30.0
Go Version:      go1.20.7
Image Spec:      1.0.2-dev
Runtime Spec:    1.1.0-rc.1
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.25.0
Git Commit:      
Built:           Tue Jan  1 00:00:00 1980
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```



**Output of `cat /etc/*release`:**

```
file doesn't exist in our image
```

**Comment by flouthoc** [comment]
@blevz Could explain a bit more by what do you mean by `image` in `That folder does not exist in our image` ? Are you running buildah as a containers ? If yes which buildah image are you using.

**Comment by blevz** [comment]
We have /run/containers in our image but not /run/contaniers/networks.  V1.28.0 of buildah didn't attempt to create that directory but v1.30.0 does and fails to do so because its read only.

We are running in containers using the nix packaging of buildah baked into an image we build.

**Comment by rhatdan** [comment]
buildah is making the assumption that /run is writable and usually a tmpfs.

**Comment by blevz** [comment]
Ah, that is useful and fixes my issue
