### ISSUE TITLE
`v1.28` tag was removed from Docker registry

### ISSUE THREAD

**Issue by slonopotamus** [containers/buildah#5019]
Up until last week, `v1.28` tag existed in [quay.io](https://quay.io/repository/buildah/stable?tab=tags) docker registry, but now it's gone. Please, restore it (and maybe switch to a more reliable docker registry that doesn't suddenly delete historical data).

Way to test:

```
$ docker pull quay.io/buildah/stable:v1.28
Error response from daemon: unknown: Tag v1.28 was deleted or has expired. To pull, revive via time machine
```

**Comment by flouthoc** [comment]
Hi @slonopotamus , Thanks for reporting, this is expected, please see: https://github.com/containers/podman/discussions/19796 and I'd suggest following up there so context remains there :)

I'm closing this since this looks duplicate.
