### ISSUE TITLE
where did quay.io/buildah/stable:v1.26.0 go?

### ISSUE THREAD

**Issue by paleozogt** [containers/buildah#5023]
**Description**

`quay.io/buildah/stable:v1.26.0` is gone.

**Steps to reproduce the issue:**
1. `docker pull quay.io/buildah/stable:v1.26.0`

**Describe the results you received:**

```bash
$ docker pull quay.io/buildah/stable:v1.26.0
Error response from daemon: unknown: Tag v1.26.0 was deleted or has expired. To pull, revive via time machine
```

**Describe the results you expected:**

To be able to pull `1.26.0`.  Our cicd was setup to use this version and now its broken. Are we going to be able to depend on any given image staying put?

**Comment by edsantiago** [comment]
Please see https://github.com/containers/podman/discussions/19796 . Some restorations are in progress, I do not know the specific status of `v1.26.0`.

I apologize for the inconvenience.
