### ISSUE TITLE
Unable to install buildah in linux fedora AWS EC2 instance

### ISSUE THREAD

**Issue by WINIQMAR** [containers/buildah#5024]
Hi,
Iam trying to install buildah but throwing below errors.
dnf install buildah
yum install buildah   as well same errors for both

**_No match for argument: buildah
Error: Unable to find a match: buildah_**
I tried all the possibilities like downloading rpm packages and install but its not working. Can you pls help on this and install buildah in my linux fedora instance.

**Comment by vrothberg** [comment]
Which version of Fedora are you using?  Please provide more details.
If you are installing some custom Fedora, there is nothing we can do upstream.

**Comment by WINIQMAR** [comment]
It’s fedora 33

**Comment by rhatdan** [comment]
Fedora 33 is no longer supported, you need to update to F37 or 38.

**Comment by vrothberg** [comment]
Yes, please upgrade your systems.  Fedora 33 has hit [EOL 399 days ago](https://docs.fedoraproject.org/en-US/releases/eol/).  That implies no security updates etc.

**Comment by WINIQMAR** [comment]
Hi,

Could you please suggest which Amazon linux version best to install buildah
through aws dashboard.

Thanks,
Vinay.

**Comment by vrothberg** [comment]
Sorry, I have no experience in or knowledge about Amazon Linux.  Please reach out to Amazon.
