### ISSUE TITLE
`podman-build`: DNS lookup fails using `--net slirp4netns` (using `systemd-resolved` on the host)

### ISSUE THREAD

**Issue by sudoforge** [containers/buildah#5033]
**Description**

I am unable to perform any hostname-based network operations (when using the default `--net slirp4netns` option) as part of the build process of any container image using `podman-build` (or `buildah-build`, which is expected), as DNS lookups consistently fail. The build environment is 64-bit Linux, with networking managed by `systemd-networkd`, and (relevant to this issue) `systemd-resolved` being used for DNS resolution.

This appears to be somewhat related to containers/buildah#2780 and containers/buildah#3806, but both issues are closed and locked.

**Steps to reproduce the issue:**

Use `systemd-resolved`. Confirm this is the active DNS resolution service by ensuring `/etc/resolv.conf` is a symlink to `/run/systemd/resolve/stub-resolv.conf`, and contains a single `nameserver` entry to `127.0.0.53` (by default). You can check that this works on the host machine by running `resolvectl status` and confirming that the output matches the configuration you have supplied to `systemd-resolved`.

Run the following command to create a temporary directory and move into it:

```
cd $(mktemp -d)
```

Run the following command to create a `Containerfile` that pings an IP address (attempts to resolve `github.com` from the host, but will default to `1.1.1.1` if that fails), and then attempts to resolve `github.com` to an IP address:

```
cat <<EOF > Containerfile
FROM docker.io/library/alpine:3.18.3@sha256:c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33

RUN cat /etc/resolv.conf
RUN ping -c 3 $(timeout 10s sh -c "getent hosts github.com | awk '{print \$1}'" || echo "1.1.1.1")
RUN getent hosts github.com
EOF
```

Run the following command to use `podman-build` to attempt to build the container image:

```
# Use podman...
podman build --no-cache .

# Or buildah directly
buildah build --no-cache .
```

Your output should be similar to the following (with differences to specific nameservers, latencies, etc):

```
➜ podman build --no-cache .
STEP 1/4: FROM docker.io/library/alpine:3.18.3@sha256:c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33
STEP 2/4: RUN cat /etc/resolv.conf
search lan
nameserver 10.0.2.3
nameserver 9.9.9.9
nameserver 149.112.112.112
nameserver 2620:fe::fe
nameserver 2620:fe::9
nameserver 10.100.0.1
--> 46b9b598e31d
STEP 3/4: RUN ping -c 3 140.82.112.3
PING 140.82.112.3 (140.82.112.3): 56 data bytes
64 bytes from 140.82.112.3: seq=0 ttl=42 time=95.157 ms
64 bytes from 140.82.112.3: seq=1 ttl=42 time=97.963 ms
64 bytes from 140.82.112.3: seq=2 ttl=42 time=85.759 ms

--- 140.82.112.3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 85.759/92.959/97.963 ms
--> 20736d6cba3a
STEP 4/4: RUN getent hosts github.com
Error: building at STEP "RUN getent hosts github.com": while running runtime: exit status 2
```

A couple things to note.

1. `10.0.2.3` must be the address of the container, since I don't have any sort of custom network configuration and `man containers.conf` indicates that the default CIDR for the engine is `10.0.2.0/24`.
2. The next four entries (from `9.9.9.9` to and including`2620:fe::9`) are the global DNS servers set in my `systemd-resolved` configuration, and `10.100.0.1` is the gateway address of the network my host machine is connected to, but is not set in my `systemd-resolved` configuration at all (rather, it is the active DNS server for my network interface). I'm confused as to why `buildah` is adding all five of these addresses; I would expect it to only add one of those (either my global nameservers, or my interface's current nameservers).
3. I don't know why DNS resolution is failing.

**Describe the results you received:**

_See above._

**Describe the results you expected:**

I expected to be able to resolve DNS within the container.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
➜ pacman -Qi buildah | awk '/^Version/ { gsub(/-.*/, ""); print $3 }'
1.31.3
```

**Output of `buildah version`:**

```
➜ buildah version
Version:         1.31.3
Go Version:      go1.21.0
Image Spec:      1.1.0-rc.3
Runtime Spec:    1.1.0-rc.3
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.26.2
Git Commit:      3ae75d4a4a72228e2eb2f90b29441728bc8af87e
Built:           Mon Sep  4 15:44:21 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

This also occurs when using `podman-build`, so I'm including podman's version here, too. In `podman v4.6.2`, the version of `buildah` that is used is `v1.31.2`.

```
➜ podman version
Client:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.21.0
Git Commit:   5db42e86862ef42c59304c38aa583732fd80f178-dirty
Built:        Tue Aug 29 14:19:21 2023
OS/Arch:      linux/amd64
```

**Output of `uname -a`:**

```
➜ uname -movrs
Linux 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

I've only included settings which are not commented (and thus resolve to their defaults).

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = [
]

pull_options = {enable_partial_images = "false", use_hard_links = "false", ostree_repos=""}
```

**Comment by Luap99** [comment]
We just use the servers from `/run/systemd/resolve/resolv.conf` when systemd resolved is used.
The 10.0.2.3 address is the slirp4netns forward address. How does you /erc/resolv.conf sysmlink look like? If it is outside of /etc or /run it may not work correctly with slirp4netns

**Comment by sudoforge** [comment]
```
➜ stat --format '%N' /etc/resolv.conf
'/etc/resolv.conf' -> '/run/systemd/resolve/stub-resolv.conf'
```

The container is successfully reading the stub file, which contains:

```
➜ rg --no-line-number -v '^#|^$' /etc/resolv.conf 
nameserver 127.0.0.53
options edns0 trust-ad
search lan
```

`127.0.0.53:53` is...

```
➜ sudo ss -tulpn | awk '/127.0.0.53%lo:53/ {print substr($7, 10, 15)}'
systemd-resolve
```

and my `systemd-resolved` configuration contains:

```
➜ rg --no-line-number -v '^#|^$' /etc/systemd/resolved.conf.d/*.conf | head -n 3
[Resolve]
DNS=9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net 2620:fe::fe#dns.quad9.net 2620:fe::9#dns.quad9.net
FallbackDNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com
```

> We just use the servers from `/run/systemd/resolve/resolv.conf` when systemd resolved is used

This would appear to be an incorrect statement. As my original comment shows, buildah appears to be parsing my upstream resolvers (instead of just reading `/run/systemd/resolve/resolv.conf`), as well as the dns server dynamically fetched for my currently active non-loopback network interface (`10.100.0.1`).

**Comment by Luap99** [comment]
As said we only read `/run/systemd/resolve/resolv.conf` which always contains the upstream resolvers once we detect systemd-resolved is in use. It is completely impossible to use 127.0.0.53 as server in the container as this is a loopback address and nothing will be listening there in the container.

Did you verify which of these servers even work from the container?

**Comment by rhatdan** [comment]
Since we never heard back, closing.
