### ISSUE TITLE
buildah-copy unexpected behavior when using --context-dir and relative source path

### ISSUE THREAD

**Issue by wtcross** [containers/buildah#5049]
**Description**

I am experiencing odd behavior when using `buildah run` to copy files into a working container in the following scenario:

1. The build script is in the context directory containing files for a given build
2. `--contextdir` option is passed to `buildah copy` 
3. The build script is run from a parent directory

Example directory structure:

```
<project-root>
│
└───one
    │
    └───two
        │
        └───three
            │   test.txt
            │   build.sh
```

The `<project-root>` directory is where the `<project-root>/one/two/three/build.sh` script is run. Here is how `buildah copy` is ran in the script:

```bash
buildah copy --chown nonroot:nonroot --contextdir "<project-root>/one/two/three" "${ctr}" test.txt /home/nonroot/test.txt
```

The error I am getting appears to claim that there is no way to compute the path of the file being copied using the context dir and relative path I'm passing in.

Maybe I am misunderstanding the intent of the context dir. I thought if I pass that in and use a relative path for the file being copied that it would resolve correctly. The code path for this feature is very complex otherwise I would have submitted a fix for fun. Looking for guidance on whether or not this is actually an issue. Really appreciate all the hard work on this project!

**Steps to reproduce the issue:**
The following bash script will reproduce the issue:

```bash
#!/usr/bin/env bash
set -o nounset
set -o errexit

_remove_temp_working_dir() {
  local working_dir_path="${1}"
  rm -rf "${working_dir_path}"
}

_create_temp_working_dir() {
  local dir_path=$(mktemp -d)
  trap "_remove_temp_working_dir '${dir_path}'" EXIT
  echo -n "${dir_path}"
}

_create_test_fixtures() {
  local working_dir_path="${1}"
  local context_dir_path="${working_dir_path}/one/two/three"
  local test_file_path="${context_dir_path}/test.txt"
  local script_file_path="${context_dir_path}/build.sh"

  mkdir -p "${context_dir_path}"

  echo "super cool test file" > "${test_file_path}"

  cat <<EOF > "${script_file_path}"
#!/usr/bin/env bash
set -o nounset
set -o errexit

ctr=$(buildah from "cgr.dev/chainguard/static:latest-glibc")
buildah copy --chown nonroot:nonroot --contextdir "${context_dir_path}" "\${ctr}" "$(basename $test_file_path)" /home/nonroot/test.txt
EOF

  echo -n "${script_file_path}"
}

working_dir_path=$(_create_temp_working_dir)
test_script_path=$(_create_test_fixtures "${working_dir_path}")

pushd "${working_dir_path}" > /dev/null
bash "${test_script_path}"
popd > /dev/null
```

**Describe the results you received:**
```
Error: adding content to container "static-working-container-1": computing path of "test.txt" relative to "/tmp/tmp.8jVPvF5ZTC/one/two/three": Rel: can't make test.txt relative to /tmp/tmp.8jVPvF5ZTC/one/two/three
```

**Describe the results you expected:**
I expect the file to be copied using a valid context directory and relative path.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.31.0-1.fc38.x86_64
```

**Output of `buildah version`:**

```
Version:         1.31.0
Go Version:      go1.20.5
Image Spec:      1.1.0-rc.3
Runtime Spec:    1.1.0-rc.3
CNI Spec:        1.0.0
libcni Version:
image Version:   5.26.1
Git Commit:
Built:           Wed Jul  5 09:10:35 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
NAME="Fedora Linux"
VERSION="38 (Thirty Eight)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
```

**Output of `uname -a`:**

```
Linux monad 6.4.15-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep  7 00:25:01 UTC 2023 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

This file is not present on my system.

**Comment by nalind** [comment]
Eek, this seems to be a case we overlooked.  Putting a / in front of the relative path should work around it (so that it looks like an absolute path, though it'll still be interpreted with the context directory as the "root") until it's fixed properly.  Thanks!

**Comment by wtcross** [comment]
Oops didn’t mean to close the issue. I’m on my phone and hit the wrong button.

@nalind I see you work fast. Thanks for jumping on this. For future reference is there developer documentation? I’m dusting off my coding skills and want to be able to contribute to the buildah and podman projects. I did look, but wasn’t able to find dev docs for buildah.
