### ISSUE TITLE
support buildah build --push

### ISSUE THREAD

**Issue by willzhang** [containers/buildah#5052]
**Description**

support buildah build --push.

i usually build image and run image for test many times, but i must run `buildah push` after `buildah build`.

is it possilbe  let buildah directly push to remote registry after building an image,  like `dokcer build --push`
```
buildah build -t docker.io/myrepo/myimage:v1.0 --push=true
```
**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `rpm -q buildah` or `apt list buildah`:**

```
(paste your output here)
```

**Output of `buildah version`:**

```
(paste your output here)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
(paste your output here)
```

**Output of `uname -a`:**

```
(paste your output here)
```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by flouthoc** [comment]
Already being worked here: https://github.com/containers/buildah/pull/4677
