### ISSUE TITLE
How to enable the use of image layer cache while using imagebuildah go sdk 

### ISSUE THREAD

**Issue by parthyadav3105** [containers/buildah#5059]
**Description**
When I am using [imagebuildah](https://pkg.go.dev/github.com/containers/buildah/imagebuildah)-pkg to build multiple images using Dockerfiles. Images are able to build successfully but layers build cache are not being used while building images. I have set *[define.BuildOptions.Layers](https://pkg.go.dev/github.com/containers/buildah@v1.32.0/define#BuildOptions)=true*

**Steps to reproduce the issue:**
1. Dockerfile: `test/Dockerfile`
```dockerfile
FROM docker.io/library/ubuntu:latest
RUN apt update
RUN apt install nano -y
```
2. Code: `main.go`
```go
package main

import (
	"context"
	"fmt"

	"github.com/containers/buildah"
	"github.com/containers/buildah/define"
	"github.com/containers/buildah/imagebuildah"
	"github.com/containers/storage"
	"github.com/containers/storage/pkg/unshare"
)

func main() {
	if buildah.InitReexec() {
		return
	}
	unshare.MaybeReexecUsingUserNamespace(false)

	// buildStore
	buildStoreOptions, err := storage.DefaultStoreOptionsAutoDetectUID()
	if err != nil {
		panic(err)
	}
	buildStore, err := storage.GetStore(buildStoreOptions)
	if err != nil {
		panic(err)
	}
	defer buildStore.Shutdown(false)

	buildOpts := define.BuildOptions{
		Output:              "new-test-image",
		Layers:              true,
		SignaturePolicyPath: "conf/policy.json",
	}

	id, ref, err := imagebuildah.BuildDockerfiles(context.TODO(), buildStore, buildOpts, "test/Dockerfile")
	if err != nil {
		panic(err)
	}

	fmt.Printf("id: %+v\n", id)
	fmt.Printf("ref: %+v\n", ref)
}
```
3. Run:
```bash
go run main.go
```
4. SignaturePolicyPath: `conf/policy.json`<html>
  <details>
      <summary><i>hidden</i></summary>
      <code>
  {
      "default": [
          {
              "type": "insecureAcceptAnything"
          }
      ],
      "transports":
          {
              "docker-daemon":
                  {
                      "": [{"type":"insecureAcceptAnything"}]
                  }
          }
  }
  </code>
  </details></html>

**Describe the results you received:**
The image was built successfully but didn't use cache for intermediate layers on rebuild.

**Describe the results you expected:**
The goal is to use `imagebuildah-pkg` to build Containerfile/Dockerfile while it uses the layer cache from previous builds. Same as what we would get using the CLI command: `buildah build --layers -t test:latest .  ` 

**Output of `buildah version`:**

```
Version:         1.23.1
Go Version:      go1.17
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.16.0
Git Commit:      
Built:           Thu Jan  1 05:30:00 1970
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Output of `uname -a`:**

```
Linux 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by flouthoc** [comment]
@parthyadav3105 You need to set `OutputFormat` in build options, it is used by buildah's cache mechanism to match against the correct type, following line to fix your issue.

```diff
	buildOpts := define.BuildOptions{
		Output:              "new-test-image",
+		OutputFormat:        "application/vnd.oci.image.manifest.v1+json",
		Layers:              true,
		SignaturePolicyPath: "conf/policy.json",
	}
```

I'm closing this, please feel free to re-open if you see any issues.

**Comment by parthyadav3105** [comment]
Thanks a lot @flouthoc🌟. It worked!😀
