### ISSUE TITLE
 npm commands fail inside container when built using buildah version 1.19.6 on Debian bullseye (illegal instruction)

### ISSUE THREAD

**Issue by nodify-at** [containers/buildah#5098]
**Description**

buildah version 1.19.6 (image-spec 1.0.1, runtime-spec 1.0.2-dev) using Debian bullseye

While using buildah version 1.19.6 (with image-spec 1.0.1 and runtime-spec 1.0.2-dev) on Debian bullseye, I encountered an issue where npm commands cannot be run inside the container.

```shell
sudo -E buildah bud --tls-verify=false --isolation=chroot -t ts-test-api:1.2.580 --build-arg ARTIFACT_VERSION=1.2.000 --build-arg ARTIFACT_SHORTVERSION=1.2.000 -f ./Dockerfile .
```

Error Message:

* If running bullseye image (FROM node:18.18.2-bullseye), we are getting an error:
```shell
STEP 13: RUN npm -v
Illegal instruction
subprocess exited with status 132
subprocess exited with status 132
error building at STEP "RUN npm -v": exit status 132
```

* If running bookworm image (FROM node:18.18.2-bookworm), `npm -v` hangs without error.

#### Environment Information:

* **CPU Details:**
Model: Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
```
processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
stepping	: 7
microcode	: 0x71a
cpu MHz		: 2699.999
cache size	: 20480 KB
physical id	: 30
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 30
initial apicid	: 30
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ssbd ibrs ibpb stibp tsc_adjust arat md_clear flush_l1d arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management:
```

#### Steps to Reproduce:

* Setup buildah version 1.19.6 on Debian bullseye.
* Use the aforementioned command to build a container.
* Observe the error when trying to run npm commands like npm -v or npm ci.
##### Expected Behavior:
* npm commands should run successfully inside the container.

##### Actual Behavior:
The commands fail with an "Illegal instruction" error.

**Comment by flouthoc** [comment]
This is very old version of buildah, is there any reason for not using more newer version ?

**Comment by nalind** [comment]
Can you use `buildah from` to build a working container based on the `node:18.18.2-bullseye` image and get the working container's ID, then use `buildah run $containerid apt-get -y update` and `buildah run $containerid apt-get -y install gdb` to install a debugger, and `buildah unshare -m root=$containerid sh -c 'env SHELL=/bin/sh chroot $root gdb /usr/local/bin/node'` to fire up the debugger with the binary, and lastly give gdb the `run -v` command, to see if it runs to completion under the debugger or if it still triggers a SIGILL?

I'm wondering if the binary in the image is built with an optimization that depends on a feature your CPU doesn't have, and if that's the case I'm hoping the debugger will show us where that happens.

**Comment by nodify-at** [comment]
Thanks, our infra team solved this issue by updating buildnah
