### ISSUE TITLE
`buildah from` / `buildah unshare --mount` problem with hyphens

### ISSUE THREAD

**Issue by smerschjohann** [containers/buildah#5132]
**Description**

Currently `buildah from` creates containerids that contain hyphens. `buldah unshare --mount` mounts the containerId and sets an environment variable `$containerId=<path to mount location>`. This leads to problems as hyphens aren't allowed in variables. You cannot easily access the set env variable. 

**Steps to reproduce the issue:**
```
buildah bud -t wtest:latest
newcontainer=$(buildah from localhost/wtest:latest) # newcontainer=wtest-working-container
buildah unshare --mount $newcontainer sh -c 'echo ${wtest-working-container}'
```

**Describe the results you received:**

working-container

**Describe the results you expected:**

The mount directory e.g. /var/home/simon/.local/share/containers/storage/overlay/6cf0d46a77cc70b2ea2038cedb96506668c46c704932b7df6dc25bafbc20ad4f/merged

A workaround for this is this:

```bash
buildah bud -t wtest:latest
newcontainer=$(buildah from localhost/wtest:latest)
buildah unshare --mount $newcontainer sh -c 'c=$(env | grep '"${newcontainer}"' | cut -d'=' -f2-); echo $c'
```

So getting the value manually by extracting the environment variable using `env`, `grep` and `cut`. I think it would be better, if `buldah unshare --mount` would simply set a static variable $BUILDAH_UNSHARE_MOUNTED etc. 

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.31.0-2.fc39.x86_64
```

**Output of `buildah version`:**

```
buildah version
Version:         1.31.0
Go Version:      go1.21rc3
Image Spec:      1.1.0-rc.3
Runtime Spec:    1.1.0-rc.3
CNI Spec:        1.0.0
libcni Version:  
image Version:   5.26.1
Git Commit:      
Built:           Wed Jul 19 17:13:31 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Fedora Linux"
VERSION="39.20231030.n.0 (Kinoite)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39.20231030.n.0 (Kinoite)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://kinoite.fedoraproject.org"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-kinoite/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://pagure.io/fedora-kde/SIG/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
VARIANT="Kinoite"
VARIANT_ID=kinoite
OSTREE_VERSION='39.20231030.n.0'
```

**Output of `uname -a`:**

```
Linux fedora 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
file does not exist

**Comment by rhatdan** [comment]
Why not name the container?  --name?

**Comment by smerschjohann** [comment]
Ah! Thanks for the tip! I did not realize that I can simply set my own name.

So yes, this also works:

```bash
newcontainer=$(buildah from --name=wltest$RANDOM localhost/wtest:latest)
buildah unshare --mount $newcontainer sh -c 'echo ${'"$newcontainer"'}'
```

Still it feels like a workaround and users can run into this issue. 

The current long example at https://github.com/containers/buildah/blob/main/docs/buildah-unshare.1.md does not name the container and the short one `buildah unshare --mount containerID sh -c 'cat ${containerID}/etc/os-release'` is a bit misleading. But if I look at it now, it is completely correct. 
It just does not state that it expects a container with the name `containerID` be created. With a command like `buildah from --name containerID scratch`.

**Comment by rhatdan** [comment]
Please open a PR to clean up the docs.

**Comment by smerschjohann** [comment]
@cbandy thanks! That seems to be the best approach for my use case :+1:
