### ISSUE TITLE
webpage: Dead link to 1.32 Release Announcement

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/buildah#5140]
https://buildah.io contains
```
What’s New!

03 Oct 2023 » [Buildah v1.32.0 Release Announcement](https://buildah.io/new/2023/10/03/new.html)

Buildah v1.32.0 is here with lots of improvements and enhancements. Check out the [Release Announcement](https://buildah.io/releases/2023/10/02/Buildah-version-v1.32.0.html).
```
The second hyperlink destination - https://buildah.io/releases/2023/10/02/Buildah-version-v1.32.0.html - does not exits.

The first hyperlink - https://buildah.io/new/2023/10/03/new.html - does exist, but it just contains a hyperlink to https://buildah.io/releases/2023/10/02/Buildah-version-v1.32.0.html , which on its own does not exist.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?

**Comment by dilyanpalauzov** [comment]
No.  I also do not know where the release notes are.

**Comment by rhatdan** [comment]
I think they are in the buildah.io repo.
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
They are in the Buildah.io repo, I'll take a look.

**Comment by TomSweeneyRedHat** [comment]
Fixed with https://github.com/containers/buildah.io/pull/112.  Thanks for the issue report @dilyanpalauzov !
