### ISSUE TITLE
`failed to set net.ipv6.conf.default.accept_dad sysctl: failed to Statfs \"/proc/273/ns/net\": permission denied`

### ISSUE THREAD

**Issue by deliciouslytyped** [containers/buildah#5157]
I'm running buildah in a nested podman (i.e. buildah in rootful podman (because I haven't got nesting working as I need yet) in rootless podman) and have run into the below error. Can anyone shed some light on what's going on?

```
level=warning msg="failed to set net.ipv6.conf.default.accept_dad sysctl: failed to Statfs \"/proc/273/ns/net\": permission denied"
```

The outer and inner containers presumably have /proc unmasked and the inner container is allegedly started with `--privileged --cap-add=NET_RAW --cap-add=NET_ADMIN --cap-add=SYS_ADMIN --security-opt unmask=/proc/* --volume=/var/lib/containers/storage --device=/dev/fuse`

ls inside the container shows something like:
```
ls: cannot read symbolic link '/proc/273/ns/net': Permission denied
ls: cannot read symbolic link '/proc/273/ns/uts': Permission denied
ls: cannot read symbolic link '/proc/273/ns/ipc': Permission denied
ls: cannot read symbolic link '/proc/273/ns/pid': Permission denied
ls: cannot read symbolic link '/proc/273/ns/pid_for_children': Permission denied
ls: cannot read symbolic link '/proc/273/ns/user': Permission denied
ls: cannot read symbolic link '/proc/273/ns/mnt': Permission denied
ls: cannot read symbolic link '/proc/273/ns/cgroup': Permission denied
ls: cannot read symbolic link '/proc/273/ns/time': Permission denied
ls: cannot read symbolic link '/proc/273/ns/time_for_children': Permission denied
total 0
dr-x--x--x 2 root root 0 Nov 12 14:55 .
dr-xr-xr-x 9 root root 0 Nov 12 14:55 ..
lrwxrwxrwx 1 root root 0 Nov 12 15:07 cgroup
lrwxrwxrwx 1 root root 0 Nov 12 15:07 ipc
lrwxrwxrwx 1 root root 0 Nov 12 15:07 mnt
lrwxrwxrwx 1 root root 0 Nov 12 14:55 net
lrwxrwxrwx 1 root root 0 Nov 12 15:07 pid
lrwxrwxrwx 1 root root 0 Nov 12 15:07 pid_for_children
lrwxrwxrwx 1 root root 0 Nov 12 15:07 time
lrwxrwxrwx 1 root root 0 Nov 12 15:07 time_for_children
lrwxrwxrwx 1 root root 0 Nov 12 15:07 user
lrwxrwxrwx 1 root root 0 Nov 12 15:07 uts
```

Whereas inspecting from the outer container shows:
```
# ls -alh /proc/77132/root/proc/273/ns
total 0
dr-x--x--x 2 root root 0 Nov 12 14:55 .
dr-xr-xr-x 9 root root 0 Nov 12 14:55 ..
lrwxrwxrwx 1 root root 0 Nov 12 15:07 cgroup -> 'cgroup:[4026533738]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 ipc -> 'ipc:[4026533152]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 mnt -> 'mnt:[4026533150]'
lrwxrwxrwx 1 root root 0 Nov 12 14:55 net -> 'net:[4026533193]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 pid -> 'pid:[4026533191]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 pid_for_children -> 'pid:[4026533191]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 time -> 'time:[4026531834]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 time_for_children -> 'time:[4026531834]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 user -> 'user:[4026532387]'
lrwxrwxrwx 1 root root 0 Nov 12 15:07 uts -> 'uts:[4026533151]'
```

I also get errors like "WARN[42442] Could not locate device 10:229 on host)" repeating when I enter the inner container in lazydocker but I expect that's somehow caused by the above.

The outer podman is 4.5.0, the inner is 4.7.0 and buildah is 1.32.1 .

**Comment by deliciouslytyped** [comment]
OK I decided to heed some of my own advice and try to check some kernel source, with apparently some success.
It appears CAP_SYS_ADMIN was needed to deal with that directory. 

This is alluded to in the namespaces(7) man page: `Permission to dereference or read (readlink(2)) these symbolic links is governed by a ptrace access mode PTRACE_MODE_READ_FSCREDS check; see ptrace(2).`

**Comment by flouthoc** [comment]
@deliciouslytyped Is this issue resolved ? Could you please close this issue if it is resolved. Thanks.

**Comment by deliciouslytyped** [comment]
I have exams coming up so I don't really have time to think about this for two months or so. I guess it's resolved, I may come back and try to add more info later.

**Comment by flouthoc** [comment]
@deliciouslytyped Thank you, closing this for now. Please feel free to re-open.
