### ISSUE TITLE
`build --layers` does not rebuild layer on heredoc change

### ISSUE THREAD

**Issue by rijenkii** [containers/buildah#5225]
**Description**

When changing heredoc contents in a Containerfile, buildah does not detect changes in the heredoc contents and does not rebuild the layer.

**Steps to reproduce the issue:**
1. Run first build, `hello, world` will be printed while building second layer:
   ```bash
   echo -e "from docker.io/alpine:latest\nrun cat <<eof\nhello, world\neof" | buildah build --layers -
   ```
2. Run second build, adding `!!!` after the original message:
   ```bash
   echo -e "from docker.io/alpine:latest\nrun cat <<eof\nhello, world!!!\neof" | buildah build --layers -
   ```

**Describe the results you received:**
On the second build second layer is grabbed from cache.

**Describe the results you expected:**
I would have expected second layer to be rebuilt.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.33.2-1.fc39.x86_64
```

**Output of `buildah version`:**

```
Version:         1.33.2
Go Version:      go1.21.4
Image Spec:      1.1.0-rc.5
Runtime Spec:    1.1.0
CNI Spec:        1.0.0
libcni Version:  
image Version:   5.29.0
Git Commit:      
Built:           Mon Nov 27 16:54:37 2023
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Output of `uname -a`:**

```
Linux rijenkiipc 6.6.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Dec  3 18:13:11 UTC 2023 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by flouthoc** [comment]
I think this is happening because heredoc syntax is not being totally added to history, easy fix is to add heredoc syntax to history. Let me check if buildkit is doing the same and we can easily do this for buildah.

**Comment by flouthoc** [comment]
@rijenkii PR https://github.com/containers/buildah/pull/5261 should close this.
