### ISSUE TITLE
official published container image

### ISSUE THREAD

**Issue by cforce** [containers/buildah#5298]
I was trying to locate a container registry where buildah is officially published by this project
I did not found any mentioned here in the docs.
On dockerhub there is none up top date,  even non verified 
![image](https://github.com/containers/buildah/assets/393286/1d1c5b09-063f-479a-beea-a5c7a2d21b88)
On Quay i found a version before recent version but still missing latest 1.34.0 -> https://quay.io/repository/buildah/stable

These images would be required for container based CI build envs.

**Comment by jwhonce** [comment]
Test Comment... Please Ignore.

**Comment by TomSweeneyRedHat** [comment]
Sorry for the delayed response to the issue. As you noted, the images created live at https://quay.io/buildah/stable. We also post them to https:/quay.io/containers/buildah. The repository that creates them lives at https://github.com/containers/image_build along with the documentation. 

When we create a release, it takes upwards of two weeks before the container image shows up on quay.io.  Once the release is created, it's submitted to Fedora.  Once the release makes it through Fedora's testing process, it is considered stable.  There's a monitoring job that runs once a day to check for any new stable versions in Fedora; once found, it creates the stable variant of the container image for that version.

To speed up the process, we need folks to test the releases on [bohdi](https://bodhi.fedoraproject.org/)  and then up vote the release.  That can considerably shrink the two-week window after a release.

Or you can make use of the images in https://quay.io/buildah/upstream which gets the images directly each day from the upstream project, or https://quay.io/buildah/testing which gets the latest test image on Fedora.  However, they're both not quite as stable as the ones in the stable project.

I do think we need an entry on the README.md pointing to the repo, I've just created: https://github.com/containers/buildah/issues/5500
