### ISSUE TITLE
Please make a new release for 1.34.x

### ISSUE THREAD

**Issue by rahilarious** [containers/buildah#5320]
as Tom [has mentioned](https://github.com/TomSweeneyRedHat/buildah/commit/aba8661dddee0530c1c70c97d2a3e25886f73576#commitcomment-138169970) things are not ready to be stable in main branch. 

But as 1.34.0 is already released, shouldn't it receive same kind of treatment as 1.33.x and get mod-bumps? There are some CVEs [fixes](https://github.com/containers/podman/releases/tag/v4.9.2) (buildkit related) in mod-bumps which are security concerns. 

Or should 1.34.x users downgrade to 1.33.x?

**Comment by rahilarious** [comment]
CC @TomSweeneyRedHat @ashley-cui

**Comment by TomSweeneyRedHat** [comment]
@nalind or @rhatdan any concerns with dropping a 1.34.1 sometime next week?

**Comment by TomSweeneyRedHat** [comment]
That is after we get the recent CVE fixes that are bubbling in.

**Comment by rhatdan** [comment]
I am fine with that.

**Comment by rahilarious** [comment]
> That is after we get the recent CVE fixes that are bubbling in.

Has dust been settled? :-)

**Comment by TomSweeneyRedHat** [comment]
@rahilarious 
The dust finally settled:  https://github.com/containers/buildah/pull/5343

Once that's in, I'll need to bump the vendoring on 10 or 12 libraries, then we'll be able to spin a release.

**Comment by rahilarious** [comment]
> @rahilarious The dust finally settled: #5343
> 
> Once that's in, I'll need to bump the vendoring on 10 or 12 libraries, then we'll be able to spin a release.

Perfect. Can't wait to read Podman 5's release notes.

**Comment by TomSweeneyRedHat** [comment]
Done!

https://github.com/containers/buildah/releases/tag/v1.34.1

**Comment by rahilarious** [comment]
> Done!
> 
> https://github.com/containers/buildah/releases/tag/v1.34.1

woohoo. High (podman)five !
