### ISSUE TITLE
--root option naming inconsistent with storage.conf file

### ISSUE THREAD

**Issue by pixdrift** [containers/buildah#533]
**Description**
The '--root' option is inconsistently named across command line / configuration file (/etc/containers/storage.conf)

**Steps to reproduce the issue:**
1. Run the following to use alternate root directory (works as expected)
`buildah --root /myrootdir images`

2. Add the following to `/etc/containers/storage.conf`
`root = "/myrootdir"`

As per documentation here:
> --root value
> 
> Storage root dir (default: "/var/lib/containers/storage") Default root dir is configured in /etc/containers/storage.conf
> 

3. Attempt to run buildah using the globally configured '--root' option (fails)
`buildah images`

4. Change `/etc/containers/storage.conf` to
`graphroot = "/myrootdir"`

5. Run buildah using the globally configured '--root' option (works)
`buildah images`

**Describe the results you received:**
buildah fails to run when 'root' option is specified in configuration file, 'graphroot' is used from configuration file.

**Describe the results you expected:**
buildah to use the 'root' value in storage.conf. Instead it is using the value 'graphroot' and it isn't clear that these are one and the same. Documentation may need to be updated? or the value renamed/updated in the configuration file?

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.12-1.git8badcc2.el7.x86_64
```

**Output of `buildah version`:**

```
Version:       0.12
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    8badcc2
Built:         Tue Feb 13 07:35:11 2018
OS/Arch:       linux/amd64
```

**Comment by pixdrift** [comment]
I see the `/etc/containers/storage.conf` file is owned by skopeo, so changing the option there may not be viable.

**Comment by rhatdan** [comment]
We really can not change the configuration file since it is used by buildah, skopeo, cri-o and podman.

Easiest is to change the documentation.  We could also change the buildah option to be --graphroot rather then root.

**Comment by pixdrift** [comment]
I don't mind the suggestion to change the option to --graphroot, but my concern is that it's not clear what 'graph' means in this context.. that can probably be fixed with documentation too though.

**Comment by rhatdan** [comment]
Well we don't expect any Users to ever use this option unless they are using it in a QE Environment.  So the name and option should match.
Do you want to open a PR to change it, or do you want us to do it?

**Comment by pixdrift** [comment]
@rhatdan, I can't meet the PR signing requirement, so can I ask that you raise the PR?

**Comment by rhatdan** [comment]
Closing because of lack of response.  Reopen if this is still an issue.
