### ISSUE TITLE
Buildah container image is over 700MB

### ISSUE THREAD

**Issue by cevich** [containers/buildah#5351]
**Description**

https://github.com/containers/buildah/pull/5347 did a great job of cutting down the image size.  Unfortunately (#5349) it also dropped the `dnf` command.  We need a smaller image, but must retain essential tools (or workalikes).

**Steps to reproduce the issue:**
1. podman pull quay.io/buildah/stable:v1.34.0
2. podman images

**Describe the results you received:**

The buildah image is HUGE

**Describe the results you expected:**

The buildah image is 500MB or less.

**Output of `rpm -q buildah` or `apt list buildah`:**

N/A

**Output of `buildah version`:**

N/A

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

N/A

**Output of `uname -a`:**

N/A

**Output of `cat /etc/containers/storage.conf`:**

N/A

**Comment by cevich** [comment]
Re-post:

@lsm5 any idea where the `dnf` -> `dnf5` -> `microdnf` went in fedora-minimal?  Any ideas how we can avoid installing things like qemu-user-static in our buildah container image?

@isker had a great idea, but I worry that `microdnf` might not be enough `dnf` to satisfy most users.  Opinions?

**Comment by isker** [comment]
> Again, @isker please don't take this badly. I really like your motivation behind the change. 

Thanks for your concern, but I’m not taking it badly. I took my knowledge of buildah (zero) and combined it with my knowledge of fedora (zero) and quickly threw something over the wall 🌞.

I won’t be contributing further attempts at this, as I’m not even using buildah myself. I’d perhaps like to, but the way the project is packaged and distributed makes it more challenging than alternatives. My PR was an attempt to work one angle of that problem, but I can’t spare the time for further efforts.

**Comment by cevich** [comment]
> but I can’t spare the time for further efforts.

No worries!  Thanks for the ideas and thanks for taking the initiative.  I'll attempt to carry thte torch forward and see what can be done to make the image smaller.  I completely agree with you that it's way to big!

**Comment by cevich** [comment]
Oops, this is a dupe of #5321
