### ISSUE TITLE
Error writing blob: Error saving image to docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by groogiam** [containers/buildah#5390]
**Description**

I am trying to use buildah to push to a docker daemon running in docker desktop 4.28.0 but I get the following error

`Error writing blob: Error saving image to docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

**Steps to reproduce the issue:**
1. Build container using buildah
2. Push to docker using this command `buildah push my-container docker-daemon:my-container:latest`

**Describe the results you received:**
`Error writing blob: Error saving image to docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

**Describe the results you expected:**
Push should succeed

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/oldstable,now 1.19.6+dfsg1-1+b6 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.19.6
Go Version:      go1.15.9
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.3
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```
**Output of `cat /etc/*release`:**

```
# apt list buildah
Listing... Done
buildah/oldstable,now 1.19.6+dfsg1-1+b6 amd64 [installed]
# ^C
# buildah version
Version:         1.19.6
Go Version:      go1.15.9
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.3
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
# ^C
# cat /etc/release
cat: /etc/release: No such file or directory
# bash
root@0fc2e30f4ce7:/app# cat /etc/release
cat: /etc/release: No such file or directory
root@0fc2e30f4ce7:/app# cat /etc/*release~
cat: '/etc/*release~': No such file or directory
root@0fc2e30f4ce7:/app# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@0fc2e30f4ce7:/app# ^C
root@0fc2e30f4ce7:/app# 
```

**Output of `uname -a`:**

```
Linux 0fc2e30f4ce7 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

File does not exist.

** docker version output **

```
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by groogiam** [comment]
Any updated on when docker client version 1.24 will be supported on buildah? Thanks.

**Comment by rhatdan** [comment]
YOu are using an ancient version of buildah

```
$ buildah -v
buildah version 1.35.3 (image-spec 1.1.0, runtime-spec 1.1.0)
$ buildah version
Version:         1.35.3
Go Version:      go1.22.1
Image Spec:      1.1.0
Runtime Spec:    1.1.0
CNI Spec:        1.0.0
libcni Version:  
image Version:   5.30.0
Git Commit:      
Built:           Mon Apr  1 07:04:32 2024
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Comment by groogiam** [comment]
@rhatdan Thanks for pointing that out. It looks like the most up to date version from apt-get in Debian 11. Is there a way to get the docker api version supported for a particular version of buildah? Thanks.

**Comment by rhatdan** [comment]
Sorry we do not support older versions in the upstream. It is up to distributions like RHEL and Debian to support older versions.

**Comment by groogiam** [comment]
@rhatdan I understand. I am not asking for any change to be made. What I am looking for is a way to determine what docker api version is supported for a particular version so I can determine what base container to use for my application that will have the supported buildah package. Is there a specific place in the code this is documented or possible some command I can run to get that information? Thanks.

**Comment by rhatdan** [comment]
@baude @mheon Ideas?

**Comment by groogiam** [comment]
@rhatdan @baude @mheon Any update on a way to determine what docker api version is supported in a specific version of buildah? Thanks.

**Comment by mheon** [comment]
This seems like more of a @mtrmac question given `docker-daemon` is a c/image transport?

**Comment by rhatdan** [comment]
We don't keep track of what versions of Buildah supported which docker-daemon version.

**Comment by mtrmac** [comment]
c/image has stopped using version 1.22 in c/image 5.29.2 , but that’s not directly helpful in the way you are probably looking for.

Since c/image 5.29.3, the supported versions are determined by the included version of the Docker client, a dependency that is being updated fairly often but not with a guaranteed timeline. It can be determined by inspecting the `vendor` subtree of any particular Buildah release, but as Dan says, we don’t keep a table.
