### ISSUE TITLE
buildah run fails : net ns permission denied with pasta

### ISSUE THREAD

**Issue by wdouglascampbell** [containers/buildah#5462]
**Description**

Running on latest Fedora CoreOS 39 stable stream I get a permission error when attempting to use ```build run```.

**Steps to reproduce the issue:**
1.  ```buildah from --pull docker.io/library/php:8.1.22```
2.  ```buildah run php-working-container /bin/bash```

**Describe the results you received:**

```
error running container: did not get container start message from parent: EOF
Error: setup network: pasta failed with exit code 1:
No routable interface for IPv6: IPv6 is disabled
Couldn't open network namespace /proc/27630/ns/net: Permission denied
```

**Describe the results you expected:**

Something like this where I am running the BASH shell in the running container.

```
root@6df475daffde:/var/www/html#
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.35.0-1.fc39.x86_64
```

**Output of `buildah version`:**

```
Version:         1.35.0
Go Version:      go1.21.7
Image Spec:      1.1.0
Runtime Spec:    1.1.0
CNI Spec:        1.0.0
libcni Version:
image Version:   5.30.0
Git Commit:
Built:           Thu Mar  7 21:20:46 2024
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.9.3
API Version:  4.9.3
Go Version:   go1.21.7
Built:        Mon Feb 19 23:41:34 2024
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 39 (Thirty Nine)
NAME="Fedora Linux"
VERSION="39.20240309.3.0 (CoreOS)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora CoreOS 39.20240309.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='39.20240309.3.0'
Fedora release 39 (Thirty Nine)
Fedora release 39 (Thirty Nine)
```

**Output of `uname -a`:**

```
Linux coreos.l2d.biz 6.7.7-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Mar  1 16:53:59 UTC 2024 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
(cat: /etc/containers/storage.conf: No such file or directory)
```

**Comment by wdouglascampbell** [comment]
I also reported this with Fedora CoreOS project at https://github.com/coreos/fedora-coreos-tracker/issues/1703.

**Comment by wdouglascampbell** [comment]
This seems similar to https://github.com/containers/buildah/issues/5440 but appears to be SELinux related instead.

**Comment by danishprakash** [comment]
That error seems to be due to `ptrace`(by extension `CAP_SYS_PTRACE`) being denied to pasta. Can you check the AppArmor profiles once to ensure that's not the case?

**Comment by Luap99** [comment]
> > Couldn't open network namespace /proc/27630/ns/net: Permission denied
> 
> This error seems to be due to `ptrace`(by extension `CAP_SYS_PTRACE`) being denied to pasta. Can you check the AppArmor profiles once to ensure that's not the case?

The system uses fedora so there is no apparmor.


Most likely the reason is that selinux is blocking the access. Can you check what version of container-selinux is installed and what is the context of buildah (`ls -Z /usr/bin/buildah`)?

**Comment by wdouglascampbell** [comment]
Yes.  SELinux definitely appears to be blocking access since if I put it in permissive mode everything works.
```
$ rpm -q container-selinux
container-selinux-2.229.0-1.fc39.noarch
```
```
$ ls -Z /usr/bin/buildah
system_u:object_r:bin_t:s0 /usr/bin/buildah
```

**Comment by rhatdan** [comment]
What AVC's are you seeing?

Also does `restorecon /usr/bin/buildah` change anything?

**Comment by wdouglascampbell** [comment]
```
type=AVC msg=audit(1712592038.157:4759): avc:  denied  { setgid } for  pid=1953124 comm="pasta" capability=6  scontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tclass=cap_userns permissive=0
type=AVC msg=audit(1712592038.157:4760): avc:  denied  { setgid } for  pid=1953124 comm="pasta" capability=6  scontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tclass=cap_userns permissive=0
type=AVC msg=audit(1712592038.157:4761): avc:  denied  { setuid } for  pid=1953124 comm="pasta" capability=7  scontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tclass=cap_userns permissive=0
type=AVC msg=audit(1712592038.157:4762): avc:  denied  { search } for  pid=1953124 comm="pasta" name="1953123" dev="proc" ino=9028859 scontext=unconfined_u:unconfined_r:pasta_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:container_runtime_t:s0-s0:c0.c1023 tclass=dir permissive=0
```
```restorecon /usr/bin/buildah``` doesn't bring any change.

**Comment by Luap99** [comment]
https://github.com/containers/container-selinux/pull/300 was merged for 2.229.1 not .0 so I don't think container-selinux is new enough for this buildah version to use pasta.

**Comment by Luap99** [comment]
Closing as I think this will work with the newer container-selinux version

**Comment by wdouglascampbell** [comment]
Okay.  I can confirm.  I did the following:

```
sudo rpm-ostree override replace https://rpmfind.net/linux/fedora/linux/updates/39/Everything/x86_64/Packages/c/container-selinux-2.230.0-1.fc39.noarch.rpm
sudo systemctl restart
```
After rebooting, the issue is no longer occurring.

Question:  Will I need to run ```rpm-ostree override reset``` to remove this once Fedora CoreOS includes this updated package in a future release?  Or will it automatically happen?
