### ISSUE TITLE
quay.io image locations are not noted in the README.md

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#5500]
**Description**

The main README.md does not mention the quay.io location for the container images nor has a pointer to the repository where they are created from (https://github.com/containers/image_build).  We probably ought to add that to Buildah's README.md and also Podman and Skopeo.

@cevich FYI

**Comment by cevich** [comment]
Good point.  Do you think you'd be able to take this on?  I'm rather overloaded at the moment.

**Comment by TomSweeneyRedHat** [comment]
@cevich, sure, I'll try to get it done by the end of this week, at least for Buildah, and then extrapolate from there.

**Comment by cevich** [comment]
Thanks Tom.
