### ISSUE TITLE
tutorial for including buildah in build tool

### ISSUE THREAD

**Issue by lgmg** [containers/buildah#5620]
the tutorial https://github.com/containers/buildah/blob/main/docs/tutorials/04-include-in-your-build-tool.md is not updated :
- storage.DefaultStoreOptionsAutoDetectUID() shall be replaced by storage.DefaultStoreOptions
- depencies with pasta (passt)
- use json-iterator 1.1.12 instead of 1.1.11 (this latter causes a segmentation fault)

**Comment by nalind** [comment]
Thanks for that, updating the first two in #5665.  I'm not sure where json-iterator 1.1.11 comes in; we've been using 1.1.12 since v1.24, so anything that was keying off of our dependency information should be defaulting to the later version.

**Comment by lgmg** [comment]
I am using buildah binding as a go imported module (and not building the source itself), then it is important to indicate that the last json-iterator is necessary to avoid the seg fault.

**Comment by nalind** [comment]
What would bring in 1.1.11, though?

**Comment by lgmg** [comment]
sorry, i just wanted to say than one need to update to json-iterator 1.1.12 because I had a segmentation fault with the 1.1.11 used by my current version of podman binding

**Comment by lgmg** [comment]
1.1.12 is the version used by the source of buildah, but if someone faces the same seg fault, the solution is just to update json-iterator
