### ISSUE TITLE
New --exclude directive from Dockerfile

### ISSUE THREAD

**Issue by slinkydeveloper** [containers/buildah#5678]
### Feature request description

Dockerfile recently added support for the `COPY --exclude` parameter, see https://www.docker.com/blog/new-dockerfile-capabilities-v1-7-0/. Would it be possible to add it to podman too?

**Comment by rhatdan** [comment]
This needs to bed enhanced in Buildah

Seems reasonable to me. But would require work in imagebuilder, I blieve.

@nalind @flouthoc WDYT?

**Comment by rhatdan** [comment]
If you were interested in opening a PR that would help this along.

**Comment by flouthoc** [comment]
Yes imagebuilder changes are needed afaics, I can give this a stab if @slinkydeveloper is not already working on this.

**Comment by nalind** [comment]
The imagebuilder parts should have landed in https://github.com/openshift/imagebuilder/pull/285.

**Comment by nalind** [comment]
Yeah, the main stumbling block I hit is getting the conformance tests to pass, since they're turning up behavior which seems counterintuitive, to me at least, in a few cases.
