### ISSUE TITLE
Provide secrets using environment variables for buildah bud

### ISSUE THREAD

**Issue by miopp2** [containers/buildah#5877]
Would it be possible to implement the passing of secrets via env variables to buildah bud in the same manner as it has been done in buildah build?

I am referencing this issue https://github.com/containers/buildah/issues/3524 and the solution for buildah build https://github.com/containers/buildah/pull/3598

According to this issue: https://github.com/containers/buildah/issues/5808 it should already work, however, it does not work for me. 

I tried to pass secrets from env variables to my buildah build like this

buildah bud --secret id=MY_SECRET and it throws the following error: 

error creating build executor: incorrect secret flag format: should be --secret id=foo,src=bar
ERRO[0000] exit status 125   

The same happens if I use --secret id=MY_SECRET,type=env

Am I missing something or is the usage from env variables not supported with buildah bud?

**Comment by rhatdan** [comment]
buildah bud and buildah build are aliases for each other?  Are you talking about podman build versus buildah bud?
