### ISSUE TITLE
Validate image signatures before build

### ISSUE THREAD

**Issue by p5** [containers/buildah#5886]
A lot of images are signed by tools like Cosign so people can confirm they are actually pushed by the maintainers, and not been involved in a supply-chain attack.  

It would be good if buildah (and subsequently Podman) supports a build flag for `--verify-signatures` or similar which checks the signatures for all images involved in a build are valid.  This includes images used in the `FROM` fields, and `COPY --from`.

A flag for known-good signatures can also be provided if the user needs to specify a trusted pubkey (e.g. `--trusted-signature ./cosign.crt`).

**Comment by p5** [comment]
Realised I can probably do this without additional flags by simply making use of the containers/policy.json

**Comment by rhatdan** [comment]
Yes, we already support this.
