### ISSUE TITLE
buildah bud params don't match docker build params

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#599]
**Description**

The available parameters for `buildah bud` don't match the ones available for `docker build`.  We need to match them and/or create documentation stating what we don't match.

Reported by @dustymabe

**Comment by TomSweeneyRedHat** [comment]
@pixdrift thanks for putting this together.  At a quick glance, most if not all of the ones that are "Yes" in Buildah, but "No" in Docker I'm fine with.  A lot of those were additions to make logging into registries more secure and/or more convenient.  For instance authfile, creds, tls-verify, etc.  The ones that are "N o" for Buildah and "Yes" for Docker are ones we'll have to look into further.  I'm guessing @rhatdan will squash some, but the others we probably ought to open an issue for so folks can pick them off and we can track them.   I'm going to guess that some of params in this category are new from when the set of params were established for Buildah.

I've added a "changes needed" column to you table and did a first pass scrub.  @rhatdan?

FYI @mheon and @baude

**Comment by rhatdan** [comment]
I agree any one that is N for Buildah and Y for Docker, should have an issue opened for it.  And people can just grab them and open a PR.  Most should be fairly easy.

BTW This would be a decent table to add to the github repo to show compatibility.

**Comment by rhatdan** [comment]
Thanks @pixdrift great job.

**Comment by TomSweeneyRedHat** [comment]
I've added an issue for each question mark in the table with the exception of #598 that @pixdrift created earlier.  I've updated the table replacing the "?" with the issue number link.

**Comment by rhatdan** [comment]
@pixdrift Could you update your table.

**Comment by rhatdan** [comment]
@pixdrift Can we get this table updated?  Perhaps as a docs file off of the readme.

**Comment by rhatdan** [comment]
@pixdrift Would love to see where we stand now.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat and @umohnani8 I think we are close to  having this done.

**Comment by rhatdan** [comment]
No work on this in months closing.
