### ISSUE TITLE
buildah bud --platform functionality missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#629]
**Description**
`buildah bud --platform` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by pixdrift** [comment]
@TomSweeneyRedHat, need minor edit to issue name to add `--platform`

**Comment by TomSweeneyRedHat** [comment]
@pixdrift, darn tricky cut/paste tricks.  TY!

**Comment by TomSweeneyRedHat** [comment]
OK, tried to reset the title one more time....

**Comment by rhatdan** [comment]
Does anyone know what this is. Probably something like

buildah bud --platform i686 and then allows you to create 32 bit containers on a a 64 bit machine?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, you're example is my understanding of what --platform does, or at least is intended to do.

**Comment by rhatdan** [comment]
I guess this would only inform the from command or buildah command to tell containers/image to pull images with that architecture.  Probably would not be that difficult.

WDYT @mtrmac

**Comment by mtrmac** [comment]
Sure, c/image can be told which platform (and which OS) to use when pulling images (`types.SystemContext.ArchitectureChoice`, `types.SystemContext.OSChoice`). That’s trivial.

I don’t know how RunC deals with cross-architecture containers, and it will make it much more noticeable that the host and container environments may differ for `buildah` users, e.g. somebody will need to make sure `dnf --installroot ${buildah_mounted_dir}` does the right thing (and can work at all), or document the necessary extra options. I suppose as long as the kernel can executables for the target platform at all (i.e. mostly 32-on-64, same architecture), it should all be _possible_ but it may get tricky. (Or maybe this has all been extensively researched, tested, and is known to work, and I’m just unaware.)

_After_ implementing this, at some point the question of creating (not just consuming) multi-arch images will probably come up, i.e. something like https://github.com/projectatomic/libpod/issues/713 or a related `Buildah` feature.

**Comment by rhatdan** [comment]
@vrothberg or @umohnani8 Would you like to take a look at this?

**Comment by vrothberg** [comment]
> @vrothberg or @umohnani8 Would you like to take a look at this?

I can start looking into it next week. But @umohnani8, feel free to tackle it before if you want to :)

**Comment by vrothberg** [comment]
> Does anyone know what this is. Probably something like
> 
> buildah bud --platform i686 and then allows you to create 32 bit containers on a a 64 bit machine?

The semantics of the `--platform` flag are actually quite different. In this context, platform refers to Linux, Windows, etc. and is mainly used to support use-cases for Docker on Windows where Linux images can be executed via Hyper-V.

I think that we cannot support it :hear_no_evil: but we could add this flag (and maybe similar cases) as a nop? @rhatdan WDYT?

**Comment by rhatdan** [comment]
SGTM
