### ISSUE TITLE
buildah bud --stream functionality missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#631]
**Description**
`buildah bud --stream` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
@runcom @vbatts Any idea what --stream does?

**Comment by vbatts** [comment]
@rhatdan i don't get why `--stream` is even there. `docker build` does not have a `--stream` option, and `buildah bud --help` says it is a noop. Remove it.

**Comment by rhatdan** [comment]
We were going by Docker web content.
But I will gladly drop it.
https://docs.docker.com/engine/reference/commandline/build/
