### ISSUE TITLE
Parallelizing Container Builds

### ISSUE THREAD

**Issue by 14rcole** [containers/buildah#633]
I'm working on a project for a distributed systems class in which I parallelize container builds in order to speed up build time, particularly on distributed systems.  I was initially building the functionality into buildah, but it seems like the functionality could just as well go into openshift/imagebuilder.  Do you feel that either project would find this feature useful in production?  Also, given that I'm not too familiar yet with openshift/imagebuilder, should I be adding functionality there instead?  It looks like the code I would be adding exists somewhere around the spot where the buildah executes the build, which it calls into imagebuilder for.

**Comment by rhatdan** [comment]
Ryan it is probably best if you opened a review here, and then allow us to figure out if it should go somewhere else.

**Comment by rhatdan** [comment]
@14rcole Did you ever complete this?

**Comment by 14rcole** [comment]
@rhatdan For the most part, yes.  There's some bugs that still need to be worked out

**Comment by rhatdan** [comment]
Any chance you can open a PR so we could examine it?

**Comment by rhatdan** [comment]
I don't mind vendoring it in. But I think it would be worth while for a few of us to look at it, including @nalind to see what he thinks.

**Comment by 14rcole** [comment]
Sounds good, I'll clean up some of the code and then submit a PR

**Comment by AkihiroSuda** [comment]
@14rcole Do you have benchmark result?

**Comment by 14rcole** [comment]
I do not, the bug I mentioned earlier prevented me from getting accurate results.  However, once I have that worked out I can share the results with you

**Comment by TomSweeneyRedHat** [comment]
@14rcole welcome back from vacation and a little reminder nudge!

**Comment by rhatdan** [comment]
CLosing as I believe this proved to be unsuccessful
