### ISSUE TITLE
official release binaries (static binaries)

### ISSUE THREAD

**Issue by bacongobbler** [containers/buildah#682]
Hey there! Just saw the v1.0 announcement this evening. Congratulations! :)

I would love to get started testing buildah, but optimally I would just have to fetch a tarball with the compiled assets for my operating system of choice. Right now it looks like [the installation docs](https://github.com/projectatomic/buildah/blob/master/install.md) notes that you have to compile from source. Are there any plans to release cross-compiled static binaries for buildah?

Some background context: I'm working on a cross-platform package manager called [gofish](https://www.gofi.sh/), and I'd love to distribute buildah there with a `gofish install buildah` which requires a static binary to distribute. Not sure if this is possible but I thought I'd throw out the idea that I want to try out buildah, but I prefer to test official releases through a package manager's release channels than from source.

**Comment by TomSweeneyRedHat** [comment]
Howdy @bacongobbler 

Do rpm's work for you?  You should be able to get them for Fedora and several variants of Ubuntu at the moment.  RHEL in the very near future along with OpenSuse.  Which distro's are you interested in in particular?

**Comment by bacongobbler** [comment]
I'm not a RHEL user so I would prefer debs but RPMs are fine. Would you prefer the community takes over support for alternative package managers such as apt?

**Comment by pixdrift** [comment]
@bacongobbler, I do compiles for every commit here on CentOS 7.x, but they don't come with any guarantee 😉 
http://rpmbuild.pixeldrift.net/projectatomic/el7/x86_64/Packages/

**Comment by pixdrift** [comment]
Following this thread I started looking at the potential to include the Arch package build in the CI.

There is an Arch package here:
https://www.archlinux.org/packages/community/x86_64/buildah/

What's interesting is that they have a patch to remove SELinux references from the ostree components:
https://git.archlinux.org/svntogit/community.git/tree/trunk/0001-Revert-ostree-add-selinux-label-for-each-file.patch?h=packages/buildah

@bacongobbler, is there a reason you wouldn't use this package as a base?

**Comment by rhatdan** [comment]
I have no problem if the Aarch guys wanted to remove SELinux support by default from the ostree patches.  But we need to get them through the review process.

**Comment by bacongobbler** [comment]
The main reason why I opened this issue was for static binaries of buildah, but if that's not possible then we can close this out.

**Comment by rhatdan** [comment]
No I think this is a good conversation. We should figure out how we could build a static version of buildah.

**Comment by mkobit** [comment]
Hosting static binaries on GitHub releases would be useful as well.

**Comment by rhatdan** [comment]
Took a quick stab at this but the golang static flag seemed to have no effect.

```
+buildah-static:  *.go imagebuildah/*.go cmd/buildah/*.go docker/*.go pkg/cli/*.go pkg/parse/*.go util/*.go
+       $(GO) build -ldflags '-w -extldflags "-static"'  -o buildah $(BUILDFLAGS) ./cmd/buildah
```

**Comment by Conan-Kudo** [comment]
@rhatdan the static build flags have been somewhat ineffective since I think golang 1.10? At least, they don't work as expected for other golang packages I build.

**Comment by vbatts** [comment]
so the goal here is a statically linked `buildah`?

**Comment by rhatdan** [comment]
Correct, and when I run golang with the commands everyone says to run it with, nothing happens, I seems to ignore the flags.

**Comment by vbatts** [comment]
oh something happens, it is just missing loads of `*.a` archives of its dependencies.
```
go build -ldflags '-X main.gitCommit=ba976ed3 -X main.buildInfo=1533324372 -X main.cniVersion=v0.6.0' -ldflags "-extldflags '-static'" -o buildah -tags "   selinux seccomp" ./cmd/buildah
# github.com/projectatomic/buildah/cmd/buildah
/home/vbatts/go1.10/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lselinux
/usr/bin/ld: cannot find -lostree-1
/usr/bin/ld: cannot find -lgio-2.0
/usr/bin/ld: cannot find -lgobject-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -lgpgme
/usr/bin/ld: cannot find -lassuan
/usr/bin/ld: cannot find -lgpg-error
/usr/bin/ld: cannot find -lseccomp
/usr/bin/ld: cannot find -lostree-1
/usr/bin/ld: cannot find -lgio-2.0
/usr/bin/ld: cannot find -lgobject-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -lgobject-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -ldevmapper
/tmp/go-link-960288058/000002.o: In function `mygetgrouplist':
/home/vbatts/src/go/src/os/user/getgrouplist_unix.go:15: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-960288058/000001.o: In function `mygetgrgid_r':
/home/vbatts/src/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-960288058/000001.o: In function `mygetgrnam_r':
/home/vbatts/src/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-960288058/000001.o: In function `mygetpwnam_r':
/home/vbatts/src/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-960288058/000001.o: In function `mygetpwuid_r':
/home/vbatts/src/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-960288058/000011.o: In function `_cgo_f7895c2c5a3a_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:46: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
```

Not all of these will be in a distribution, so it may require a length build from source recipe

**Comment by rhatdan** [comment]
go build -ldflags '-X main.gitCommit=ba976ed3 -X main.buildInfo=1533324372 -X main.cniVersion=v0.6.0' -ldflags "-extldflags '-static'" -o buildah -tags "   selinux seccomp" ./cmd/buildah

When I run that command it comes back in with no errors.   But the binary is the same.
on F28?

**Comment by vbatts** [comment]
@rhatdan you might have something else going on ;-)

**Comment by vbatts** [comment]
on f28, with packages glibc-static, libselinux-static, glib2-static, and libseccomp-static installed,
That still leaves missing: ostree-1, gpgme, assuan, gpg-error, and devmapper

**Comment by rhatdan** [comment]
Well we can drop ostree-1 and devimapper support  Not sure about the others.

**Comment by rhatdan** [comment]
@mtrmac Is there a way to remvoe those others?

**Comment by vbatts** [comment]
Oh right. Damn. Here I was making a build recipe to statically link all those things ...

**Comment by vbatts** [comment]
`go build -ldflags '-X main.gitCommit=ba976ed3 -X main.buildInfo=1533330547 -X main.cniVersion=v0.6.0' -ldflags "-extldflags '-static'" -o buildah.static -tags "   selinux containers_image_os
tree_stub containers_image_openpgp exclude_graphdriver_devicemapper" ./cmd/buildah
`

**Comment by rhatdan** [comment]
@vbatts Still failing on the other missing static libs?

**Comment by vbatts** [comment]
Nope. This compiles fine for me. Loads of warnings though

**Comment by rhatdan** [comment]
Excellent.  We should add that to the Makefile and start making a static binary, which people could download.

**Comment by mtrmac** [comment]
Fairly recently a glibc maintainer has explicitly warned that there is no ABI for the NSS modules, so basically any non-trivial statically linked binary, _even if it seems to work in simple cases_, is _fundamentally_ unportable to different environments (or different times). Is everyone happy just pretending that isn’t the case? Or is the plan to build a CGO-less binary which can’t work with users with LDAP?

**Comment by mtrmac** [comment]
(`containers_image_openpgp` will make it impossible to sign images, but that’s the least of the downsides really.)

**Comment by vbatts** [comment]
Why is the openpgp tag prohibit signing?

**Comment by mtrmac** [comment]
The lazy answer is that it hasn’t been implemented.

The underlying concern is that it would require working with private key material in garbage-collected objects, which is completely unsuitable for any long-living processes, and uncertifiable in any process; it’s simpler not to implement that than to deal with people who want their, for example,  static binaries, no matter the risks and cost :)

**Comment by mtrmac** [comment]
> The underlying concern …

(The _history_ is that the GPGME implementation was first, and then OpenShift wanted the Golan-only one for verification it its code; there has never been serious demand for signing in the Golang-only one so far, IIRC, so the question whether it is a good idea never really came up. But that’s basically why I’d advise against implementing it if it did came up.)

**Comment by rhatdan** [comment]
I was thinking that we could just provide this static binary with all sorts of caviats about not supported and what will probably not work. so other people could play with it on distros that don't currently ship it.

Seems like something people in the go world are looking for anyways.  But I would always recommend using the supported, dynamically linked versions available for the distribution.

**Comment by mtrmac** [comment]
> I was thinking that we could just provide this static binary with all sorts of caviats about not supported and what will probably not work.

Do note that this issue starts with
> I'm working on a cross-platform package manager called `gofish`, and I'd love to distribute buildah there with a `gofish install buildah` which requires a static binary to distribute. 

There’s not a lot of space for “probably will not work” caveats in that.

\*shrug\* I realize that people want whatever they want and there’s only so much one can do to persuade them not to want that. All I really want is for everyone to understand the trade-offs involved.

**Comment by rhatdan** [comment]
Make static now works, although when I play with the binary it crashes.  Not sure what to do next.

**Comment by rhatdan** [comment]
Closing since the issue seems to have gone stale

**Comment by mikepurvis** [comment]
The binaries available from https://github.com/nicholasdille/buildah-static worked for me!
