### ISSUE TITLE
don't persist builds across reboots by default

### ISSUE THREAD

**Issue by cgwalters** [containers/buildah#757]
In a discussion with mheon, I was suggesting that podman store state in `/run` for containers that use `--rm`.

For buildah, is there really any use case for persisting build containers for a long time?  If we had them automatically be pruned by rebooting, that would help a lot in flushing random transient state.  I had some very old builds in my `buildah containers` on my Silverblue workstation.

```
$ rpm -q buildah
buildah-1.0-1.git1ab80bc.fc28.x86_64
$ rpm-ostree status
● ostree://fedora-atomic:fedora/28/x86_64/workstation
                   Version: 28.20180603.0 (2018-06-03 19:01:33)
                BaseCommit: 84115a3333e88544bbe8108c9eb173736c04c29d4784502da83e7a9883040ea3
...
```

**Comment by rhatdan** [comment]
@nalind WDYT
@cgwalters currently `buildah from foobar` creates a buildah container.  Users could then run other commands and commit at a far later date.  But I would think it is up to Nalin if we want these to persist on a reboot.

**Comment by pixdrift** [comment]
I think the 'containers' in buildah are a work in progress, why would I want a reboot to clean them up, or more importantly, would a user expect their work to be erased on reboot? This is suggesting a default behaviour that is destructive.

**Comment by TomSweeneyRedHat** [comment]
FWIW.  I'm not a fan of "automatic" anything especially when it comes to the destruction of objects.  If we could swangle a way to allow the end user to toggle whether or not containers persist across a reboot, that would be fine with me.  I'm not coming up with a way quickly, but it is pre-tea.

My $.02

**Comment by cgwalters** [comment]
> If a user wants this behaviour they can add it to their boot scripts
> `buildah rm --all`

That mostly would work, though there'd be races (I think) if it happened to be running concurrently while something else started a build.

Probably the best would be something like `buildah from --rm <image>` where `--rm` would be defined to attach to the lifetime of the parent process - *implementing* that would be tricky though without a daemon.  Maybe the parent process could create a lock file or so, and then one could have `buildah rm --all --orphaned` which would delete all containers that are unlocked?

**Comment by rhatdan** [comment]
buildah from --rm image 

Could cleanup when you do a buildah commit, although we currently allow you to continue to work with the container when you do a commit.  IE you can do lots of commits.

buildah commit --rm $CTR

Might be an option that cleans up all container information.
