### ISSUE TITLE
Multiple registry issues returning generic registries.conf error message

### ISSUE THREAD

**Issue by pixdrift** [containers/buildah#849]
**Description**
When using `buildah from` or bud `FROM` to pull an image from a private registry, various errors can occur that appear to be reported under a generic error message in `buildah` referring to registries.conf which can be misleading when troubleshooting.

The message is:
```
image "nexus.pixeldrift.local:8080/centos:latest" not found in /etc/containers/registries.conf registries: image not known
```

Example situations:
- Host unreachable (eg. bad DNS / no route)
- Connection refused (networking/firewall)
- TLS negotiation (have seen attempts to connect to http server using https rejected in strace return this error)
- Authentication/login required (but login has not yet been executed)

**Note:**
I don't currently have a specific reproducer for this, but I wanted to raise an issue to hopefully get more feedback from others that may be seeing this.

**Steps to reproduce the issue:**
1. `buildah from nexus.pixeldrift.local:8080/centos:latest`

**Describe the results you received:**
Standard error message for all error types:
```
image "nexus.pixeldrift.local:8080/centos:latest" not found in /etc/containers/registries.conf registries: image not known
```

**Describe the results you expected:**
Error messages more specific to the issue, eg. network timeout, host unreachable, authentication required, TLS required.

**Output of `rpm -q buildah`:**

```
buildah-1.2-201807041005.gita59fb7a.el7.x86_64.rpm 
```

**Output of `buildah version`:**

```
Version:         1.2-dev
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      a59fb7a
Built:           Wed Jul  4 21:01:24 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.5.1804 (Core)
```

**Comment by rhatdan** [comment]
@pixdrift @TomSweeneyRedHat Could you look into creating PRs to resolve these issues?

**Comment by rhatdan** [comment]
@mtrmac Do we get back this type of information from containers/image?

**Comment by mtrmac** [comment]
> @mtrmac Do we get back this type of information from containers/image?

The error should in general be specific about the failure, at least c/image is not _intentionally_ being opaque; the errors may not be well-typed enough for callers to make detailed decisions about them, but they should at least be fairly readable and clear about the context (or maybe confusingly overzealous about the context).

It’s hard to be definite about a generic complaint, looking at the specific examples cited:
> - Host unreachable (eg. bad DNS / no route)
```console
$ skopeo copy docker://this-does-not-exist.example.com/foo dir:t
FATA[0000] Error determining manifest MIME type for docker://this-does-not-exist.example.com/foo:latest: pinging docker registry returned: Get https://this-does-not-exist.example.com/v2/: dial tcp: lookup this-does-not-exist.example.com: no such host
```
> - Connection refused (networking/firewall)
```console
$ skopeo copy docker://www.example.com:3128/foo dir:t
FATA[0060] Error determining manifest MIME type for docker://www.example.com:3128/foo:latest: pinging docker registry returned: Get https://www.example.com:3128/v2/: dial tcp 93.184.216.34:3128: i/o timeout 
```
> - TLS negotiation (have seen attempts to connect to http server using https rejected in strace return this error)
```console
$ skopeo copy docker://docker.io:80/foo dir:t
FATA[0000] Error determining manifest MIME type for docker://docker.io:80/foo:latest: pinging docker registry returned: Get https://docker.io:80/v2/: http: server gave HTTP response to HTTPS client
```
> - Authentication/login required (but login has not yet been executed)
```console
$ skopeo copy docker://docker.io/mtrmac/foo dir:t
FATA[0001] Error determining manifest MIME type for docker://mtrmac/foo:latest: Error reading manifest latest in docker.io/mtrmac/foo: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

(In all the above, `skopeo copy` only adds the `FATA[0001]` prefix; all other text text comes from `c/image/copy.Image`.)

---

But that does not do any good when `buildah` is throwing the error away, e.g.
https://github.com/projectatomic/buildah/blob/c5051bc81624556923dc007150c572d2ae8ab850/pull.go#L170-L177 completely discards the error returned by `c/image/copy.Image` and uses a generic “unable to find image” text, or https://github.com/projectatomic/buildah/blob/c5051bc81624556923dc007150c572d2ae8ab850/new.go#L195-L198 just logs most errors in debug output and returns no error indication to the caller. (I realize that searching in several registries makes error reporting a bit tricky, but _at least_ in the case of a single attempted registry the error should be returned.)

**Comment by nalind** [comment]
@TomSweeneyRedHat yes, I think those should be getting reported correctly now.

**Comment by rhatdan** [comment]
@pixdrift Can we close this issue now?
