### ISSUE TITLE
error creating new mount namespace

### ISSUE THREAD

**Issue by Spindel** [containers/buildah#875]
**Description**

 STEP 12: ENV LC_ALL C.utf8
 STEP 13: ADD rootfs.tar /
 STEP 14: RUN dnf remove -y selinux-policy-targeted
error running container: error creating new mount namespace for [/bin/sh -c dnf remove -y selinux-policy-targeted]: operation not permitted
error building at step {Env:[LC_ALL=C.utf8 LANGUAGE=en_US:en LANG=C.utf8 LC_CTYPE=C.utf8      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LC_CTYPE=C.utf8 LANG=C.utf8 LANGUAGE=en_US:en LC_ALL=C.utf8 DATE=2018-07-20T12:34+0000 HOST=Linux runner-ae852df3-project-1283324-concurrent-0 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux BRANCH=new-container-image 
 COMMIT=f3b76804c39a3728aae93e688037683528a99024 URL=https://gitlab.com/ModioAB/base-image] Command:run Args:[dnf remove -y selinux-policy-targeted] Flags:[] Attrs:map[] Message:RUN dnf remove -y selinux-policy-targeted Original:RUN dnf remove -y selinux-policy-targeted}: exit status 1

This happens when rootfs.tar is  a fedora27 root, created with:
```
dnf install \
  --installroot $(CURDIR)/$$tmpdir \
  --releasever $(FEDORA_ROOT_RELEASE) \
  --disablerepo "*" \
  --enablerepo "fedora" \
  --enablerepo "updates" \
  $(FEDORA_ROOT_PACKAGES) \
  glibc-minimal-langpack \
  --setopt install_weak_deps=false \
  --assumeyes && \
rm -rf \
  $$tmpdir/var/cache \
  $$tmpdir/var/log/dnf* && \
tar -C $$tmpdir -cf $(CURDIR)/$@ . && \

```
**Steps to reproduce the issue:**
1.build a rootfs for fedora 27
2. fails.

Same code, but the rootfs is fedora 28:
 success

**Output of `rpm -q buildah` or `apt list buildah`:**
`buildah-1.1-1.gitfbf46d3.fc28.x86_64`

**Output of `buildah version`:**

```
Version:         1.1
Go Version:      go1.10.2
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      fbf46d3
Built:           Sun Jun 10 21:30:54 2018
OS/Arch:         linux/amd64

```

**Output of `cat /etc/*release`:**

```
bash-4.4# cat /etc/os-release 
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Twenty Eight)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

```

**Output of `uname -a`:**

```
Linux 59b47feb60ab 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```

[storage]

# Default Storage Driver
driver = "vfs"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"



```

**Comment by TomSweeneyRedHat** [comment]
Thanks for the problem report @Spindel.  I might have missed it in IRC, but could you share the buildah command that you issued to get this error?  Dockerfile too if one was in play please.

**Comment by Spindel** [comment]
define _cmd_image_buildah_build =
  $(_buildah) --storage-driver=vfs bud --pull-always \
    --file=$< \
    --build-arg=BRANCH="$(CI_COMMIT_REF_NAME)" \
    --build-arg=COMMIT="$(CI_COMMIT_SHA)" \
    --build-arg=URL="$(CI_PROJECT_URL)" \
    --build-arg=DATE="$(_date)" \
    --build-arg=HOST="$(_host)" \
    --tag=$(IMAGE_LOCAL_TAG) \
    .
endef

**Comment by Spindel** [comment]
```
FROM scratch
MAINTAINER "D.S. Ljungmark" <spider@modio.se>


ARG URL=unknown
ARG COMMIT=unknown
ARG BRANCH=unknown
ARG HOST=unknown
ARG DATE=unknown

LABEL "se.modio.ci.url"=$URL \
      "se.modio.ci.branch"=$BRANCH \
      "se.modio.ci.commit"=$COMMIT \
      "se.modio.ci.host"=$HOST \
      "se.modio.ci.date"=$DATE

ENV LC_CTYPE C.utf8
ENV LANG C.utf8
# Because OS X
ENV LANGUAGE en_US:en
ENV LC_ALL C.utf8


ADD rootfs.tar /
# https://github.com/projectatomic/buildah/issues/874
RUN dnf remove -y selinux-policy-targeted

COPY storage.conf /etc/containers/storage.conf

```

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by TomSweeneyRedHat** [comment]
Thx @Spindel !

**Comment by rhatdan** [comment]
Very cool install, @Spindel Does this mean it works on F28 and Fails only on F27?

**Comment by Spindel** [comment]
Indeed that’s what it means.

**Comment by rhatdan** [comment]
Well f27 is going  away so closing issue.

**Comment by raffaelespazzoli** [comment]
I am getting the same error in fedora 30

**Comment by TomSweeneyRedHat** [comment]
Going to reopen until this can be investigate/verified on F30.

**Comment by rhatdan** [comment]
@raffaelespazzoli Are you doing this as non-root?

**Comment by TomSweeneyRedHat** [comment]
@raffaelespazzoli can you provide more details please?  Are you doing this as non-root?  Can you provide your Dockerfile and any associated commands that you used?

**Comment by TomSweeneyRedHat** [comment]
As this has been opened for over 6 months and no response or further incidents, I'm closing.

**Comment by tvvignesh** [comment]
@TomSweeneyRedHat @rhatdan I have the same issue. Have added the details here: https://github.com/containers/podman/issues/7982 Any way I can proceed? Thanks.
