### ISSUE TITLE
error with limited user build on Centos

### ISSUE THREAD

**Issue by vbatts** [containers/buildah#926]
**Description**
This is in the effort to get a buildah template for github.com/knative/build and https://github.com/knative/build-templates working

**Steps to reproduce the issue:**
1. build a container with buildah to do in-container builds
2. attempt to build cri-o inside the container
3.

**Describe the results you received:**
```
time="2018-08-13T15:10:43Z" level=error msg="error reading allowed ID mappings: error reading subuid mappings for user \"limited\" and subgid mappings for group \"limited\": No subuid ranges found for user \"limited\" in /etc/subuid"
```

**Describe the results you expected:**
successful build

**Output of `buildah version`:**

```
buildah version
Version:         1.4-dev
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      0a7389c
Built:           Mon Aug 13 14:49:01 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
```

**Output of `uname -a`:**

```
Linux d16709548d4d 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Dockerfile of buildah image:
```Dockerfile
FROM centos
ARG REVISION="master"

RUN \
  # Install buildah dependencies.
  yum -y install \
    make \
    golang \
    bats \
    btrfs-progs-devel \
    device-mapper-devel \
    glib2-devel \
    gpgme-devel \
    libassuan-devel \
    libseccomp-devel \
    ostree-devel \
    git \
    bzip2 \
    go-md2man \
    runc \
    skopeo-containers && \
  # Install buildah.
  mkdir ~/buildah && \
  cd ~/buildah && \
  export GOPATH=`pwd` && \
  git clone https://github.com/opencontainers/runc ./src/github.com/opencontainers/runc && \
  cd $GOPATH/src/github.com/opencontainers/runc && \
  make runc && \
  mv runc /usr/bin/runc && \
  cd $GOPATH/ && \
  git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah && \
  cd $GOPATH/src/github.com/projectatomic/buildah && \
  git checkout "${REVISION}" && \
  make && \
  make install && \
  buildah --help

RUN adduser limited
USER limited
ENTRYPOINT ["buildah"]
```

**Comment by vbatts** [comment]
This error is due to an older-than-latest `shadow` in centos7 (`shadow-utils-4.1.5.1-24.el7.x86_64`).
And with the userns features added in v1.3.

**Comment by vbatts** [comment]
Trying again with the end of the Dockerfile like:
```Dockerfile
RUN adduser limited && \
  echo "limited:100000:65536" > /etc/subuid && \
  echo "limited:100000:65536" > /etc/subgid
USER limited
ENTRYPOINT ["buildah"]
```
And it fails with:
```
Error: error running newgidmap: exec: "newgidmap": executable file not found in $PATH:
time="2018-08-13T16:33:55Z" level=error msg="error running newgidmap: : exec: \"newgidmap\": executable file not found in $PATH"
```

**Comment by vbatts** [comment]
@nalind thoughts?

**Comment by rhatdan** [comment]
That is packaged up in shadow-utils.  I don't think any of this will work without that package, since this is a setuid and does the heavy lifting of setting up the userns.

@giuseppe PTAL

**Comment by vbatts** [comment]
The curious thing is that all this worked as expected when I was testing from #900

**Comment by vbatts** [comment]
arrrgh, i'm not able to reproduce when it _did_ worked :grimacing: 
And `newgidmap` does not appear available to centos7 or epel.

**Comment by vbatts** [comment]
checking on ubuntu for something, and seeing similer there too (regarding less than latest shadow):
```shell
limited@ca519028bed7:~/gopath/src/github.com/kubernetes-incubator/cri-o$ buildah bud -t cri-o .
Error: error running newgidmap: exec: "newgidmap": executable file not found in $PATH: 
ERRO[0000] error running newgidmap: : exec: "newgidmap": executable file not found in $PATH 
ERRO[0000] (unable to determine exit status)            
limited@ca519028bed7:~/gopath/src/github.com/kubernetes-incubator/cri-o$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by giuseppe** [comment]
there is a BZ to track inclusion of newuidmap/newgidmap in RHEL 7:

https://bugzilla.redhat.com/show_bug.cgi?id=1498628

Please weight in there :-)

There is not much we can do without these tools when running as unprivileged user, as we wouldn't be able to set multiple mappings in an user namespace and that breaks most images.

But... we should not need any user namespace when running as root, and the `chroot` isolation should not require that.  Could you please add an ENV variable `"BUILDAH_ISOLATION=chroot"` and see if it makes a difference?

**Comment by vbatts** [comment]
I agree that it is very risky to update shadow-utils. Is there not a help that we could provide that accomplishes the same, @giuseppe ?

**Comment by giuseppe** [comment]
the only alternative I can think of is to run as root without setting up a new usernamespace.  This is what "BUILDAH_ISOLATION=chroot" should do when it is used by root.

Unfortunately there is no other way to setup a new user namespace with multiple mappings, it is a privileged operation and only root can do it, an unprivileged user can map only one user into the new userns (what `unshare -r ...` does).

**Comment by vbatts** [comment]
ohman makes progress! but it seems like that same logic could see if `container=` is set ...

**Comment by rhatdan** [comment]
Ok can I close this?

**Comment by vbatts** [comment]
sure. I've moved on to new issues :-)
