### ISSUE TITLE
Feature request for outputing to stdout.

### ISSUE THREAD

**Issue by xinminglai** [containers/buildah#936]
Hi, Can we add feature that buildah can send the docker-archive to stdout directly?
This way, we can just do something like
buildah push image-name "STDOUT" | ssh example.com docker load

For now, I have to dump to a file, and
cat file.tgz | ssh example..com docker load
Which is tedious to dump file before loading to docker.

**Comment by rhatdan** [comment]
Can't you do a podman save |  ssh example.com docker load

**Comment by rhatdan** [comment]
If you are building with Dockerfile, then you can even just do 
```
podman build -t foobar .
podman save foobar | ssh example docker load
```

**Comment by xinminglai** [comment]
But podman is not in gentoo, And I thought this can also be done in buildah, without needing other things.

**Comment by rhatdan** [comment]
Who do I ping to get podman into gentoo?

**Comment by TomSweeneyRedHat** [comment]
@lsm5 any contacts for gentoo?

**Comment by lsm5** [comment]
@TomSweeneyRedHat I'd start with @wking

**Comment by rhatdan** [comment]
@xinminglai Any idea who I should contact in Gentoo to get podman in?

**Comment by xinminglai** [comment]
Sorry, I don't. I'm just normal user in gentoo.
But according to what I found. The contact for the ebuild author seems to be zmedico@gentoo.org
You can try this email. Thanks!

**Comment by zmedico** [comment]
Hi, yes I would like to add podman to gentoo. I tried a few months ago but wasn't able to get it working easily. I will try again. @rhatdan thanks for the ping!

**Comment by rhatdan** [comment]
@zmedico Any progress?  Anything we can do to help?

**Comment by zmedico** [comment]
podman is now available in gentoo:

https://packages.gentoo.org/packages/app-emulation/libpod

**Comment by rhatdan** [comment]
Use Podman for this feature.
