### ISSUE TITLE
buildah from /path

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#942]
I was thinking it would be cool to be able to do `buildah from /PATH`.

The idea would be I could populate a directory or have a directory on my system that looks like a rootfs.  

buildah from /path 

Would figure out that the user specified a path (Command begins with /, ../, ./)

Then it would do the equivalent of

```
ctr=buildah from scratch
mnt=buildah mnt $ctr
cp -RP /PATH $mnt
buildah umount $ctr
```

**Comment by rhatdan** [comment]
One think buildah would need to do is make sure the STORAGE_DIR is not a subdir of /PATH, since this could get recursive.

`buildah from /`

Would be invalid.

**Comment by TomSweeneyRedHat** [comment]
SGTM, and I concur on the subpath check, that could get messy quick.

**Comment by vrothberg** [comment]
+1 on the proposal!

> Would figure out that the user specified a path (Command begins with /, ../, ./)

I wonder if that's a potential candidate for a new `raw:` image transport. I am not sure if that's something that should be fully supported by containers/image but adding something like a `raw:` transport could be a good placeholder for now. The benefit is that the interface of `buildah-from` wouldn't need to change in case `raw:` became a thing.

**Comment by rhatdan** [comment]
@mtrmac WDYT?

**Comment by rhatdan** [comment]
I am going to close this issue, since we have not made any progress in months.  Reopen if someone wants to work on it.
