### ISSUE TITLE
buildah inspect ContainerConfig info empty in comp to Docker

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/buildah#950]
During conformance testing it was discovered:

ContainerConfig in buildah inspect output  almost empty from buildah image. But it has value from docker image.

Per Yiqiao Pu

[1] https://github.com/ypu/buildah/tree/conformance

Buildah version 1.4

**Comment by ypu** [comment]
After add "--format docker" to the build command line. The ContainerConfig have value now. Now the test results is similar with Config section. Following items still have some difference:
 Cmd, WorkingDir, Volumes, Entrypoint and Hostname.

**Comment by rhatdan** [comment]
@ypu Could you list out the differences.  Show the values in for each field in docker versus those in buildah.

**Comment by ypu** [comment]
Sure. The details about the test:
Dockerfile:
    	FROM centos:7
    	COPY dir /dir
    	RUN ls -al /dir/file

Output for each field:
Field Name | Value in docker image| Value in buildah image
------------ | ------------- | -------------
Cmd|  ["/bin/sh", "-c", "ls -al /dir/file" ]|["/bin/bash" ]
WorkingDir | "" | "/"
Volumes | null | {}
Entrypoint| null |[]
Hostname| "23baa52527a7" | ""

**Comment by rhatdan** [comment]
I think we can fix everything but Cmd.  I don't think docker behaviour on Cmd is correct.  
They basically grab the last RUN command and make it equal to CMD.
If someone later adds another RUN then the CMD will change.  Does anyone know if this is documented behaviour or just random.

**Comment by rhatdan** [comment]
I think this is fixed in latest buildah 1.5, or at least we are happy with the differences.
