### ISSUE TITLE
"push docker-daemon:" gets permission denied

### ISSUE THREAD

**Issue by tliron** [containers/buildah#978]
Running on Fedora 28 with SELinux enabled. Buildah version 1.3.

The user is in the docker group, and I can run "docker images" just fine.

But when I try to push from buildah to `docker-deamon:` I get this:
```
Post http://%2Fvar%2Frun%2Fdocker.sock/v1.22/images/load?quiet=1: dial unix /var/run/docker.sock: connect: permission denied
```
As far as I know, buildah does not run with a separate user, so if this user has privileges to access docker, so should buildah. No? Or is there some SELinux-specific protection going on?

**Comment by rhatdan** [comment]
I don't know, could you check if it works in permissive mode?  
Any avc's?

ausearch -m avc -ts recent

**Comment by tliron** [comment]
I apologize, I should have tried that first. The answer is: it's not SELinux. Even in SELinux permissive mode I'm getting the same error.

I should also mention that using `sudo` does work, but that's obviously something I want to avoid.

So, what could be the issue here? If the current user can access the Docker daemon, why can't buildah when running under the current user? Is buildah doing some kind of user switch?

**Comment by TomSweeneyRedHat** [comment]
@giuseppe any thoughts?

**Comment by tliron** [comment]
Another thought: buildah is accessing Docker daemon via the named pipe (`/var/run/docker.sock`). Could it be that the docker CLI uses a different method, and that's why one has permissions and the other doesn't? I tried to experiment using `buildah push docker:` instead of `buildah push docker-daemon:` but didn't get anywhere.

**Comment by giuseppe** [comment]
skopeo copy won't probably work as it doesn't run in an userns.  The issue is caused by buildah re-executing into an user namespace and dropping all the additional groups.

We can change the hardcoded value here (it should probably be configurable):
```
diff --git a/cmd/buildah/unshare.go b/cmd/buildah/unshare.go
index b495de26..295efbc6 100644
--- a/cmd/buildah/unshare.go
+++ b/cmd/buildah/unshare.go
@@ -181,7 +181,7 @@ func maybeReexecUsingUserNamespace(c *cli.Context, evenForRoot bool) {
        cmd.UidMappings = uidmap
        cmd.UseNewgidmap = uidNum != 0
        cmd.GidMappings = gidmap
-       cmd.GidMappingsEnableSetgroups = true
+       cmd.GidMappingsEnableSetgroups = false
 
        // Finish up.
        logrus.Debugf("running %+v with environment %+v, UID map %+v, and GID map %+v", cmd.Cmd.Args, os.Environ(), cmd.UidMappings, cmd.GidMappings)
```

Since the default breaks the rootless push to docker use case, should we change it?

**Comment by rhatdan** [comment]
What is the risk of changing it?

**Comment by giuseppe** [comment]
rootless containers won't be able to use `setgroups`.  We could also leave `setgroups(2)` enabled but still not use `setgroups(0, NULL)` in `unshare.c`, so that the additional groups of the user are not dropped.  @nalind what do you think?

**Comment by tliron** [comment]
Skopeo won't run at all on `containers-storage` without elevated privileges. I get the follow error with Skopeo:
```
> skopeo inspect containers-storage:1b85fb6a857a
FATA[0000] mkdir /var/run/containers/storage: permission denied
```

**Comment by giuseppe** [comment]
@tliron would it be possible for you to try this patch https://github.com/projectatomic/buildah/pull/985?

**Comment by tliron** [comment]
The patch works and resolved this issue, great job! I'll keep this issue open and let you manage it/

I've discovered another issue but will open it separately.
