### ISSUE TITLE
"push docker-daemon:" always uses "docker.io/" prefix

### ISSUE THREAD

**Issue by tliron** [containers/buildah#987]
Tested with version 1.3.

Example:
```
buildah push c1589518a3be docker-daemon:prefix/test:1.0
```
And then running `docker images` you will the name as:
```
docker.io/prefix/test
```
This makes it difficult to use buildah with non-public Docker repositories.

**Comment by rhatdan** [comment]
So you would rather see 
localhost/prefix/test

**Comment by tliron** [comment]
Well, I would rather have no added extra prefix, as this much complicates the rest of the CI/CD chain. Other Docker building tools do not tend to add extra prefixes.

**Comment by rhatdan** [comment]
@mtrmac @umohnani8 PTAL

**Comment by mtrmac** [comment]
This is intentional and necessary for `atomic pull` to work as expected (or as close to it as possible, anyway).  See https://github.com/containers/image/issues/72 for the complex details if you are interested (perhaps start with the tables at the bottom).

hostname-unprefixed destinations for `docker-daemon:` are fundamentally equivalent to `docker.io/*` on upstream Docker, and not interoperable (different from `docker pull` / `docker tag`) on projectatomic/docker.

If buildah wanted to implement `buildah push --to-daemon prefix/test` which implicitly treats it as `localhost/` instead of `docker.io/`, that would be possible (_please_ don’t edit `docker-daemon:` strings to reinterpret their semantics, though); the desired support for ~ `buildah push --to-daemon prefix/test` to not add _any_ prefix is not supportable.

**Comment by tliron** [comment]
Well. All I can say is that the assumption that everyone will want to push to `docker.io` is wrong. Many of us use internal repositories.

I wonder if perhaps we can support multiple use cases via an extra CLI switch? E.g.:
```
buildah push c1589518a3be docker-daemon:prefix/test:1.0 --docker-repository=internal.org
```
Would result in this name:
```
internal.org/prefix/test
```
The default `--docker-repository` could be `docker.io`, so that your other use case (Atomic?) would continue working as it does now.

**Comment by umohnani8** [comment]
@tliron you could also give it the full name including the registry, that way the default docker.io won't be added to the name.
`buildah push image docker-daemon:internal.org/prefix/test:1.0`

**Comment by rhatdan** [comment]
@tliron I think @umohnani8 way to handle this is the best.

**Comment by tliron** [comment]
OK, I did some testing and this indeed does work:
```
buildah push image docker-daemon:internal.org/prefix/test:1.0
```
However, this doesn't (it adds `docker.io` as prefix):
```
buildah push image docker-daemon:internal/prefix/test:1.0
```
So apparently the parsing requires a `.` in order to extract the domain. So, I guess this is the real bug. (In our use case we are using local hostnames without a `.` in their name.)

**Comment by rhatdan** [comment]
Can you try localhost instead of internal.

**Comment by mtrmac** [comment]
> Apparently the parsing requires a `.` in order to extract the domain.

Yes, or a `:`, or the hostname to be `localhost`.  This rule is used consistently throughout the docker name ecosystem:

```console
# docker tag fedora internal/foo:latest
# docker push internal/foo:latest
The push refers to a repository [docker.io/internal/foo]
(and fails because I don’t have rights)
```

I expect using short hostnames will be similarly painful anywhere else in the container ecosystem.  As a workaround, you probably can use `internal:443` (or whatever the port is); whether that is better than `internal.my.corp.example.com` is a matter of personal preference, of course.

**Comment by tliron** [comment]
Thanks. I would recommend documenting this heuristic [online](https://github.com/projectatomic/buildah/blob/master/docs/buildah-push.md) and in the CLI help. If this is indeed a Docker convention, then perhaps there's a convenient link to documentation there that can be added.

It's definitely not obvious, and I'm sure I won't be the only one to be confused...

**Comment by rhatdan** [comment]
Could you suggest wording in the man page that would help?

**Comment by mtrmac** [comment]
The closest to an official spec would probably be the “repository” term in https://github.com/moby/moby/blob/master/image/spec/v1.2.md#terminology , but that does not document the “is it a DNS name or a repository” heuristic.

**Comment by tliron** [comment]
Was this closed with a commit to fix the documentation?

**Comment by rhatdan** [comment]
Nope.

**Comment by tliron** [comment]
Well, here's my suggestion for documentation, a modification of [doc](https://github.com/containers/buildah/blob/master/docs/buildah-push.md):

> **docker-daemon**:_docker-reference_ An image _docker-reference_ stored in the docker daemon internal storage. If _docker-reference_ does not begin with a valid registry name (a domain name containing "." or the reserved name "localhost") then the default registry name "docker.io" will be prepended. _docker-reference_ must contain either a tag or a digest. Alternatively, when reading images, the format can also be docker-daemon:algo:digest (an image ID).

Hopefully this or similar can go into both the MD file and the CLI help.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Any update on this, I think this is just fix the docs correct?

**Comment by TomSweeneyRedHat** [comment]
No update, it bubbled down my stack, will try to bubble it back up.

**Comment by rhatdan** [comment]
Closing as the documentation has been fixed and we have had lots of fixes in push.
