### ISSUE TITLE
hard coded constants outside 'int' range on 32-bit platforms

### ISSUE THREAD

**Issue by andreasbaumann** [containers/buildah#990]
Building on 32-bit Intel results in:

```
# github.com/projectatomic/buildah/vendor/github.com/opencontainers/runc/libcontainer/system
vendor/github.com/opencontainers/runc/libcontainer/system/linux.go:119:89: constant 4294967295 overflows int
```

int and uint are platform-dependent, as you can check with a test program like
in https://gist.github.com/petergloor/1eacd3ebcfc3e09ed578dd0d4f80cabe

on 32-bit:

```
Integer range on this computer
MinUint: 0
MaxUint: 4294967295
MinInt: -2147483648
MaxInt: 2147483647
```

I hacked the sources with:

```
  find . -type f -exec sed -i 's/4294967295/2147483647/g' {} \;
```

but this feels - well hacky :-)

**Comment by andreasbaumann** [comment]
Mmh. I realize this should maybe be reported upstream for opencontainers/runc?

**Comment by andreasbaumann** [comment]
Reported upstream as https://github.com/opencontainers/runc/issues/1885

**Comment by rhatdan** [comment]
Nothing has happened upstream...

**Comment by rhatdan** [comment]
@andreasbaumann This was fixed upstream does it work for you now?

**Comment by andreasbaumann** [comment]
seems to work. thanks.
